### ISSUE TITLE
[Feature Request] Restore/Destroy files "trashed" from the current directory.

### ISSUE THREAD

**Issue by jtrv** [sxyazi/yazi#1009]
### Please describe the problem you're trying to solve

I got this idea from https://github.com/TD-Sky/conceal which has the ability to restore from the trash in a useful directory-aware way that seems like it should be easy to add to yazi as well.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

A new key mapped command that displays a list of files discarded under the current directory, of which you can:
	- restore file(s) with a new key-mapped command
	- permanently delete file(s) with a key-mapping

**Comment by sxyazi** [comment]
Hi, you can call the interactive UI from `conceal restore` through the `shell --block` command, so you can have:

```bash
# Trash hovered file
{ on = [ "T", "t" ], run = '''shell 'cnc "$0"' --confirm''' },

# Restore files interactively
{ on = [ "T", "r" ], run = 'shell "conceal restore" --block --confirm' }
```

Doc of `shell` command: https://yazi-rs.github.io/docs/configuration/keymap/#manager.shell
