### ISSUE TITLE
Add yazi to scoop bucket

### ISSUE THREAD

**Issue by so1ve** [sxyazi/yazi#101]
I know users can create their own scoop bucket, but it would be great if yazi can be added to https://github.com/ScoopInstaller/Main.

**Comment by sxyazi** [comment]
I'm not familiar with Windows, do you think `winget` is a better option? And what's the difference between them?

**Comment by so1ve** [comment]
Hmmmm, IMO they are not competitors. Scoop allows users to create their own bucket, however winget requires users to publish everything to their registry. I think scoop is better (personally) I can create a PR to fix this

**Comment by sxyazi** [comment]
Sounds good, go for it!

**Comment by so1ve** [comment]
https://github.com/ScoopInstaller/Main/pull/5072 🎉

**Comment by sxyazi** [comment]
Awesome work, thank you very much!

I'll wait for a merge to close this issue.

**Comment by so1ve** [comment]
https://github.com/so1ve/destiny/blob/master/bucket/yazi.json Yazi is also available in my scoop bucket :)

**Comment by so1ve** [comment]
Merged!
