### ISSUE TITLE
[Feature request] Color/Shade gradient for linemode information

### ISSUE THREAD

**Issue by freijon** [sxyazi/yazi#1011]
### Please describe the problem you're trying to solve

It's not visible on first glance how the files vary in terms of size, modification date, etc. Especially with the human readable file size (which I like generally) it's harder to detect the big files without sorting by size

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

When displaying the linemode, it could be rendered with a color/shading gradient. For simplicity, it could apply the gradient to max/min of the current folder. Example:

- The biggest file would have the best visible shade, the smallest file would have the least visible shade
- The newest file would have the best visible shade, the oldest file would have the least visible shade
- Permissive permissions would have the best visible shade, restrictive permissions would have the least visible shade
Here a mockup:
![image](https://github.com/sxyazi/yazi/assets/1387831/f35ba940-36c1-4385-93e3-bb00d8046e44)

There could be an option to enable/disable this behavior. If disabled, display like today.

It would increase the readability a lot in my opinion. Like this you can still sort alphabetically but big/small new/old files would stand out.

**Comment by sxyazi** [comment]
Could you describe the implementation details in more detail please? 

Yazi's default theme [uses 16 colors](https://yazi-rs.github.io/docs/faq#why-text-indistinct) to better fit the terminal theme's color scheme. I'm not sure how to express this gradient effect.

**Comment by freijon** [comment]
Well, I'm no expert, but I'm thinking about something like [this](https://github.com/mellite/colorful), but the gradient could use colors from theme.toml, for example a gradient from `darkgray` to `gray`

**Comment by sxyazi** [comment]
I quickly checked out the code for this crate, and it seems to use 256 colors based on RGB/HSL.

I don't know much about colors, but from my experience, it's usually best to steer clear of 256 colors when you're not sure about the user's terminal color scheme (like whether it's white text on black background or vice versa). It often leads to poor visibility.

So, my suggestion is to pick a few colors that suit your terminal and implement it yourself by overriding the [`Folder:linemode()`](https://github.com/sxyazi/yazi/blob/faa1d9f37b7900fc8fdaa40bd67d2c4885ef78ab/yazi-plugin/preset/components/folder.lua#L7) method, and you can set the foreground and background colors of text respectively through Span's [`fg()` and `bg()`](https://yazi-rs.github.io/docs/plugins/layout#span) methods.
