### ISSUE TITLE
Update file permission after shell command

### ISSUE THREAD

**Issue by raffaem** [sxyazi/yazi#1017]
### Please describe the problem you're trying to solve

Hover over a file, open shell with `;`, and type `chmod +x $1`. The file is rendered executable, but the permissions shown on the bottom right corner are not updated.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Update file permissions after shell command is run

**Comment by raffaem** [comment]
[20240509T042024.webm](https://github.com/sxyazi/yazi/assets/54762742/12a65fba-e2e0-4f4a-9122-82e237e1f1d9)

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1024

**Comment by raffaem** [comment]
> Please try #1024

seems to work

**Comment by kohane27** [comment]
I had the same problem in `ya 0.2.5` (stable version installed from archlinux extra package 0.2.5-2).

Confirmed it's fixed in `Yazi 0.2.5 (0ff4835 2024-05-18)`

Thank you!
