### ISSUE TITLE
Large images look smaller than they should be

### ISSUE THREAD

**Issue by gaesa** [sxyazi/yazi#1021]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.33.1

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.5 (Arch Linux 2024-04-27)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect: Kitty

Adaptor
    Adaptor.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY: Some("wayland-0")
    DISPLAY: Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/usr/bin/zsh")
    EDITOR: Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.45\nmagic file from /usr/share/file/misc/magic\nseccomp support included\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

```

</details>

### Describe the bug

The image appears smaller in the preview panel than it should be, not utilizing the available space effectively.

<details>
  <summary>Example</summary>

![problem](https://github.com/sxyazi/yazi/assets/71256557/d210658c-563d-449d-a0aa-f18c4343154a)
</details>

### Expected Behavior

The image should scale appropriately to utilize the available space in the preview panel, maintaining its aspect ratio.

### To Reproduce

Just find some large images, then see them using yazi.

### Configuration

yazi.toml
```toml
[manager]
ratio = [2, 3, 5]
sort_by = "modified"
sort_dir_first = true

[preview]
image_filter = "lanczos3"
image_quality = 90

[tasks]
image_alloc = 0
image_bound = [0, 0]
```

### Anything else?

<details>
  <summary>The huge image example</summary>
  
![anime-smug-faces](https://github.com/sxyazi/yazi/assets/71256557/17f35dd6-99c3-4899-9596-79ca2c0319c1)

</details>

**Comment by sxyazi** [comment]
See https://yazi-rs.github.io/docs/image-preview#size

**Comment by sxyazi** [comment]
To speed up image preview, Yazi will use this size for pre-caching images, see https://yazi-rs.github.io/blog/#pre-loading

While the terminal size is constantly changing. This means that every time the user slightly moves the terminal, it needs to regenerate the cache for **all** images because the size has changed. This is a very inefficient approach.

**Comment by sxyazi** [comment]
I'm confused. Do you mean to generate cache according to the current terminal window size? What if you open another terminal window with a larger size? Re-cache all images again? Also what should do if you can't get the actual pixel width of the terminal (like node-pty based terminals that doesn't implement the `ioctl` system call)?
