### ISSUE TITLE
Exiting yazi leaves some ascii characters in terminal

### ISSUE THREAD

**Issue by dtolnay** [sxyazi/yazi#1026]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

rxvt-unicode (urxvt) v9.30

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```
Yazi
    Version: 0.2.5 (VERGEN_IDEMPOTENT_OUTPUT 2024-05-11)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("rxvt-unicode-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Unknown([])

Adaptor
    Adaptor.matches: X11

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY: None
    DISPLAY: Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/bin/bash")
    EDITOR: None
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.41\nmagic file from /etc/magic:/usr/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/david/.local/state/yazi" directory.
```

yazi.log:

```
  2024-05-11T20:56:02.500109Z  WARN yazi_adaptor::emulator: [Adaptor] No special environment variables detected
    at /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yazi-adaptor-0.2.5/src/emulator.rs:66

  2024-05-11T20:56:02.500132Z  WARN yazi_adaptor::emulator: [Adaptor] Unknown TERM_PROGRAM: 
    at /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yazi-adaptor-0.2.5/src/emulator.rs:80

  2024-05-11T20:56:02.500135Z  WARN yazi_adaptor::emulator: [Adaptor] Unknown TERM: rxvt-unicode-256color
    at /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yazi-adaptor-0.2.5/src/emulator.rs:87

  2024-05-11T20:56:02.502460Z  WARN yazi_adaptor::ueberzug: ueberzugpp spawning failed: No such file or directory (os error 2)
    at /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yazi-adaptor-0.2.5/src/ueberzug.rs:84
```

</details>

### Describe the bug

When run in rxvt-unicode, after exiting yazi, the characters `Gi=31,s=1,v=1,a=q,t=d,f=24;AAAA` are left in the terminal.

<img src="https://github.com/sxyazi/yazi/assets/1940490/e9f94bb0-8cc5-47ce-b9a1-bef95644e80c" width="400">

### Expected Behavior

No leftover characters from yazi after exiting.

### To Reproduce

- Install urxvt (`sudo apt install rxvt-unicode`)
- Run `rxvt-unicode`
- Run `yazi`
- Press `q` to exit

### Configuration

no config

### Anything else?

_"Unknown TERM: rxvt-unicode-256color"_ in yazi.log might be relevant.

**Comment by sxyazi** [comment]
Thanks for the report!

It seems like urxvt doesn't recognize Kitty's graphics protocol [detecting sequence](https://sw.kovidgoyal.net/kitty/graphics-protocol/#querying-support-and-available-transmission-mediums), perhaps the easiest way to fix it is to add urxvt's `TERM` value `rxvt-unicode-256color` to the list of known terminals:

https://github.com/sxyazi/yazi/blob/c1e1f26c4c388ed4a39de117062a2db364535a22/yazi-adaptor/src/emulator.rs#L83-L89

so further CSI process can be skipped. Would you like to raise a PR for it?
