### ISSUE TITLE
Selected for yank is not unselected with Esc

### ISSUE THREAD

**Issue by raffaem** [sxyazi/yazi#1031]
### Please describe the problem you're trying to solve

After selecting a file for yanking with `y`, the selection cannot be undone with "Esc"

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Unselect the file with "esc"

**Comment by sxyazi** [comment]
Hi, cancel the `yank` is a separate command `unyank`, if you use the [default keymap](https://yazi-rs.github.io/docs/quick-start#filedirectory-operations), you can press `Y` or `X` to `unyank`

Closing as already exists

**Comment by raffaem** [comment]
Oh sorry, should have read the doc more carefully. Thanks!
