### ISSUE TITLE
Output chooser-file or cwd directly to stdout

### ISSUE THREAD

**Issue by QiBaobin** [sxyazi/yazi#1049]
### Please describe the problem you're trying to solve

 For now, we have to create a temp file to communicate with other tools instead of using pipes or subshells. 

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Is it be simper that just output the chooser-files if any, otherwise cwd, to the stdout?

### Additional context

Regarding other events or debug information, I think we can write them to stderr or a log file, as they are only used for debug.

**Comment by sxyazi** [comment]
See https://github.com/sxyazi/yazi/discussions/823#discussioncomment-8811630, and here's an example https://yazi-rs.github.io/docs/tips#helix-with-zellij

Closing as already supported.
