### ISSUE TITLE
Ctrl-z doesn't send yazi to foregroud

### ISSUE THREAD

**Issue by teto** [sxyazi/yazi#105]
sry for yet another report but that's because I like the program :) 

Usually when I hit `Ctrl-Z`, it sends the program in background (it sends SIGSTOP), I go back to a shell prompt, I can run a few commands and then I can resume the program by typing `fg`. 
Hitting `Ctrl-Z`does nothing with 0.1.4 , and it is not mapped in my ~/.config/yazi/keymap.toml .

I would like `Ctrl-Z` to pause, which may imply for yazi to react to the STOP signal

**Comment by sxyazi** [comment]
Seems that `SIGTSTP` is the signal that should be handled, and `SIGCONT` for resuming?

**Comment by teto** [comment]
ha indeed, I looked for the signal quickly to give you some hint but looked like I was wrong :'(

**Comment by teto** [comment]
Note: same remark for Ctrl-C that usually kills the command

**Comment by sxyazi** [comment]
Okay, I will address it as soon as I finish refactoring.

**Comment by teto** [comment]
thanks a lot for your hard work.
