### ISSUE TITLE
Open SVG as text file interactively

### ISSUE THREAD

**Issue by fishBone000** [sxyazi/yazi#1055]
### Please describe the problem you're trying to solve

Yazi treats SVG files as image files. With default config I can open them as image files. But SVG files are text files too, users might want to edit them directly.  
I know there should be a way to configure yazi to let it open them as text files, but add it to the default config can save some time.  
Thanks!

### Would you be willing to contribute this feature?

- [ ] Yes, I'd like to give it a shot, but I don't know rust

### Describe the solution you'd like

I'd like to have a text editing option for opening SVG files interactively, like the $EDITOR option.

**Comment by sxyazi** [comment]
Hi, I think the current behavior is correct (i.e., opening it as an image rather than a text file), because its mime-type indicates this - it is `image/svg+xml` rather than `text/svg+xml`, so I prefer to maintain the existing behavior. 

Closing as not in the plan, sorry.
