### ISSUE TITLE
iterm2 image preview in tmux sometimes has wrong position

### ISSUE THREAD

**Issue by tianze0926** [sxyazi/yazi#1064]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

wezterm 20240203-110809-5046fc22

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.5 (bf1c325 2024-05-20)
    OS: linux-x86_64 (unix)
    Debug: true

Ya
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "ya 0.2.5\n", stderr: "" })

Emulator
    Emulator.via_env: ("tmux-256color", "tmux")
    Emulator.via_csi: Ok(WezTerm)
    Emulator.detect: WezTerm

Adaptor
    Adaptor.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

SSH
    shared.in_ssh_connection: true

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/home/leo/.local/bin/fish")
    EDITOR: None
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.38\nmagic file from /home/leo/miniconda3/envs/build/share/misc/magic\n", stderr: "" })

Text Opener
    default: None
    block: None

tmux
    TMUX: true

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

```

</details>

### Describe the bug

In tmux when previewing images, some have wrong positions (at the bottom right corner):

![image](https://github.com/sxyazi/yazi/assets/66857124/468b5277-ac38-4e66-ba4b-a3790e98e10b)

### Expected Behavior

Positions should be correct.

### To Reproduce

- this jpg has correct position: https://github.com/sxyazi/yazi/assets/66857124/0554cbee-7434-4105-8aad-2b44488d23e7
- this however has the wrong position: https://github.com/sxyazi/yazi/assets/66857124/b4801afa-98ee-4482-96d5-1bc97899963f

### Configuration

no config

### Anything else?

I’ve noticed that smaller images tend to cause the issue, whereas normal-sized images haven’t caused any problems.

### Possible fix

Interestingly, I found that making the following change as in `#[cfg(windows)]` can help mitigate the issue, although I’m not sure why.

```diff
diff --git a/yazi-shared/src/term/cursor.rs b/yazi-shared/src/term/cursor.rs
index 4cbbd0f..1a46b3f 100644
--- a/yazi-shared/src/term/cursor.rs
+++ b/yazi-shared/src/term/cursor.rs
@@ -36,6 +36,11 @@ impl Term {
                #[cfg(unix)]
                {
                        queue!(buf, SavePosition, MoveTo(x, y))?;
+
+                       use std::{thread, time::Duration};
+                       buf.flush()?;
+                       thread::sleep(Duration::from_millis(1));
+
                        let result = cb(&mut buf);
                        queue!(buf, RestorePosition)?;
                        buf.flush()?;
```

**Comment by sxyazi** [comment]
I can't reproduce it. 


https://github.com/sxyazi/yazi/assets/17523360/856cf844-3d1a-4104-b6ca-56ef11a18c6f



What's your tmux version? Is it the latest one? Can you try using the default configurations for both tmux and WezTerm and set https://yazi-rs.github.io/docs/image-preview#tmux to see if the issue still? 

Here’s my tmux version:

```
tmux -V
tmux 3.4
```

**Comment by tianze0926** [comment]
The issue remains on the two systems I've tried:

- NixOS unstable, Hyprland master branch
- Arch Linux latest, KDE 6.0.4

Yazi is built from the main branch and has no config.

tmux version is 3.4 and the configuration only contains https://yazi-rs.github.io/docs/image-preview#tmux.

WezTerm has no config.

**Comment by sxyazi** [comment]
Can you record a GIF to show me your steps? Also does it only happen with the specific combination of tmux and wezterm? Does this issue occur in other situations as well?

**Comment by tianze0926** [comment]
[untitled.webm](https://github.com/sxyazi/yazi/assets/66857124/a68a55f6-7452-403a-a70f-48e7e7c5bcd6)

Without tmux everything works fine. As for other terminals that support iterm2, VS Code is nearly unusable in combination with tmux:

![image](https://github.com/sxyazi/yazi/assets/66857124/8b658ab5-7741-4907-a9ad-7564de21b465)

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1070

**Comment by tianze0926** [comment]
Yes that works! Thanks for your help~

**Comment by sxyazi** [comment]
Alright lemme merge then
