### ISSUE TITLE
Command/Meta/Windows key in keybindings

### ISSUE THREAD

**Issue by mskvsk** [sxyazi/yazi#1065]
### Please describe the problem you're trying to solve

Currently, there is no way to use the Command/Meta/Windows key in keybindings. While it is possible to go without Meta/WIndows on Linux and WIndows, the Command key is central to the macOS workflow.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Neovim has implemented a D- notation (e.g. D-A) to support that key because more obvious choices are already taken by Control (C) and Alt/Option (M).

So, I would suggest to use that notation as well.

### Additional context

As far as I understand, Kitty Terminal has [something that resembles a standard](https://sw.kovidgoyal.net/kitty/keyboard-protocol/) on how to send key codes including the ones that use the Meta key. At least, the D- notation in Neovim works with Kitty out of the box and enabling this protocol is [recommended](https://github.com/wez/wezterm/issues/3731#issuecomment-1551441381) by the creator of Wez's Terminal as the solution to the issue.

Also, [this issue](https://github.com/rogual/neovim-dot-app/pull/250) could be helpful as well.

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1069

**Comment by mskvsk** [comment]
> Please try #1069

Works like a charm, ready to merge. Thank you!
