### ISSUE TITLE
File previewer displays tab characters inconsistently

### ISSUE THREAD

**Issue by redbeardymcgee** [sxyazi/yazi#1067]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

WezTerm

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.5 (7177317 1980-01-01)
    OS: linux-x86_64 (unix)
    Debug: false

Ya
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(WezTerm)
    Emulator.detect: WezTerm

Adaptor
    Adaptor.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY: Some("wayland-0")
    DISPLAY: Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/usr/bin/fish")
    EDITOR: Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.45\nmagic file from /nix/store/h5pshzq92r2xcv6w1p10cmkar4nyv0xp-file-5.45/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/var/home/josh/.local/state/yazi" directory.

```

</details>

### Describe the bug

![Screenshot from 2024-05-20 22-03-39](https://github.com/sxyazi/yazi/assets/73571278/5b0457e5-d957-43b2-9f64-878781716e2a)

This is an image of the file preview pane in yazi, previewing a plaintext file named `foobar.txt`. In the file, I separated the first column by various spaces and tab characters. 

As you can see, the tab characters do strange things.

It's especially strange in a scenario like crontabs which yazi does not seem to associate with any filetype. If I remove the `.txt` extension, then:

![Screenshot from 2024-05-20 22-05-15](https://github.com/sxyazi/yazi/assets/73571278/1a53d014-6e8d-476a-b05f-7abf38dad43c)

### Expected Behavior

Tabstops should be displayed consistently.

### To Reproduce

[foobar.txt](https://github.com/sxyazi/yazi/files/15383887/foobar.txt)

 View the above file in yazi.

Alternatively, create a file yourself with various tabstops.

### Configuration

no config

**Comment by sxyazi** [comment]
The first (`foobar` with `.txt` extension) is expected because tabs are zero-width (see https://github.com/sxyazi/yazi/issues/996#issuecomment-2093216714), and Yazi replaces them with spaces when rendering, with a default of 2 spaces. You can adjust this as needed through [tab_size](https://yazi-rs.github.io/docs/configuration/yazi#preview.tab_size).

The second one (`foobar` without `.txt` extension) is definitely a bug. It looks like tabs for unassociated files weren't replaced with spaces. I'll investigate it and create a PR to fix it.
