### ISSUE TITLE
Enter custom command to open file.

### ISSUE THREAD

**Issue by mkblast** [sxyazi/yazi#1071]
### Please describe the problem you're trying to solve

I would like a binding that open a prompt that takes a command and open the files with it.  

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Something like what Joshuto did. it has a command called `open_with` that opens a prompt to write the command.

### Additional context

![image](https://github.com/sxyazi/yazi/assets/73954836/f779834f-beef-46b6-b37f-e3b7664e9c2b)

like this.

**Comment by sxyazi** [comment]
`open --interactive` is what are you looking for:

https://github.com/sxyazi/yazi/blob/f2b7f3eaf7bbfee5fdd4719f4fabe32c08aec1b5/yazi-config/preset/keymap.toml#L62-L63

See docs at https://yazi-rs.github.io/docs/quick-start#filedirectory-operations, closing as already exists.

**Comment by mkblast** [comment]
Im well aware of this. But if i need to open something with another program, i will need to add it to the config. I was looking for prompt that i could enter my command.

**Comment by sxyazi** [comment]
Oh! I must have misunderstood - I haven't used Joshuto's `open_with`, I just thought it looked similar to Yazi's interactive `open` from the screenshot.

It sounds like the [`shell` command](https://yazi-rs.github.io/docs/configuration/keymap#manager.shell) is what you're looking for - you can run any shell command on the selected file using `;` or `:`.

**Comment by c02y** [comment]
@mkblast Did you get what you asked? I still don't know how to get `Open with ...` prompt with any custom command to open a file.

**Comment by mkblast** [comment]
I use these variables from the docs. Works fine

![Screenshot_20240616_120046_Firefox.jpg](https://github.com/sxyazi/yazi/assets/73954836/fbf9d935-df09-40b1-9717-a48a4066fe62)

**Comment by c02y** [comment]
Yeah. I already read that.

So I tried again, you mean `:` on the selected file, and then type command such as `vim $0` in the shell box? It works.

But I was trying to use dropdown list of `O` which is `open --interactive`:

```toml
# yazi.toml config file
reveal = [
	{ run = '${EDITOR:=vim} "$1"', block = true, desc = "Edit with vim", for = "unix" },
	# TODO: prompt for command to open with...
	{ run = "shell '$1'", desc = "Open with ...", for = "unix" },
	{ run = 'xdg-open "$(dirname "$1")"',            desc = "Reveal", for = "linux" },
	{ run = 'open -R "$1"',                          desc = "Reveal", for = "macos" },
	{ run = 'explorer /select, "%1"', orphan = true, desc = "Reveal", for = "windows" },
	{ run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
```
