### ISSUE TITLE
Wrong folder for Windows in keymap preset

### ISSUE THREAD

**Issue by 8LWXpg** [sxyazi/yazi#1072]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Windows Terminal 1.20.11271.0

### Did you try the latest code to see if this problem got fixed?

Not tried, and I'll explain why below

### Describe the bug

The `config` and `temp` directory is different on Windows.

https://github.com/sxyazi/yazi/blob/0ebfacb677aeb32ba749c738493993af997c0485/yazi-config/preset/keymap.toml#L144-L149

### Expected Behavior

`config` should be `~/AppData/Roaming/yazi/config` and `temp` should be `~/AppData/Local/Temp` on Windows

**Comment by sxyazi** [comment]
Hi, `cd ~/.config` here doesn't refer to Yazi's configuration but rather the configuration for all software. AFAIK, some Windows software does store their configuration files in `~/.config`, so I don't think this is an issue. 

Regarding `/tmp`, it is indeed a directory that doesn't exist on Windows. I'll create a PR to remove it – I want to try and find the largest common subset between Unix and Windows.
