### ISSUE TITLE
Add file name expansion when running a shell command

### ISSUE THREAD

**Issue by fishBone000** [sxyazi/yazi#1075]
### Please describe the problem you're trying to solve

Sometimes user might want to open a file with a non-default program which is neither listed in the open interactively list.  
For example there's a PDF file, the default program in use should be a PDF viewer. The user might want to open it with nvim (I know PDF has binary data, just giving an example here), then the user had to type `:nvim filename`.  
But the file name can be long, or can be in non-English language, and switching IME is required to input the file name, let alone that there's no auto completion for entering shell commands in yazi. 

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

This would be more convenient if the filename can be expanded, like `:nvim $F`, and `$F` will be expanded to `filename` when the command is actually run. And which file's name to expand? The file under the cursor of course. Also it can be expanded to multiple file names if several files are selected.

**Comment by Alexpv86** [comment]
Sorry, my English is bad. Is it possible to make this function as an additional item "Open with" when choosing to open interactively? That is, we press the key to open interactively, and among the list of things we can open with, the command open with, and when we select this item, we need to enter the name of the program with which to open? That would be very cool! Thak you!

**Comment by sxyazi** [comment]
> This would be more convenient if the filename can be expanded, like :nvim $F, and $F will be expanded to filename when the command is actually run

It's already supported, you can use `$0`, `$1`, `$2` etc. variables in the shell, see https://yazi-rs.github.io/docs/configuration/keymap#manager.shell

> Also it can be expanded to multiple file names if several files are selected.

Likewise you can use `$@` to represent multiple files.

**Comment by sxyazi** [comment]
> Is it possible to make this function as an additional item "Open with" when choosing to open interactively?

The items in "Open with" come from user-configured opener rules, and they also support variables like `$0`, `$1`, `$@`, see https://yazi-rs.github.io/docs/configuration/yazi#opener

**Comment by fishBone000** [comment]
Oh I didn't know this. Thanks!
