### ISSUE TITLE
[Bug] open a folder with Chinese name and trigger jump fzf to search and select a file, nothing is visible.

### ISSUE THREAD

**Issue by DreamMaoMao** [sxyazi/yazi#108]
This problem is very strange, and will only happen the first time, when you can not see file list in the current path, press the left arrow key, then press the right arrow key, the file in the current path can be saw again .

After that, I repeated the first operation (jump fzf to search and select a file in the same path). After the selection, I can see  file list in the path.

**Comment by DreamMaoMao** [comment]
press left key and right key:

https://github.com/sxyazi/yazi/assets/30348075/f18881eb-14ea-4b01-a59b-50810827a513

**Comment by DreamMaoMao** [comment]
secode time search:

https://github.com/sxyazi/yazi/assets/30348075/b58d008b-e66a-4414-8e42-b7d6349abbcc

**Comment by sxyazi** [comment]
Thank you for your report. I will investigate it.

**Comment by sxyazi** [comment]
I cannot reproduce this issue on the latest HEAD. Please try the latest code to see if the issue has gone.

https://github.com/sxyazi/yazi/assets/17523360/1a097ea5-b484-4e75-906a-8d9dc607e994

**Comment by sxyazi** [comment]
Do they have any patterns, and how can I reproduce them?

**Comment by DreamMaoMao** [comment]
I found the Rules that trigger bugs. I have a path that is
~/down

And then I have keymap config:
```
{ on = [ "g", "d" ],       exec = "cd ~/down",   desc = "Go to the downloads directory" },
```

The down path create method is:

```
ln -s /media/wrq/UUI/down  ~/down
```


This problem occurs when I use the yazi gd command to open ~/down and then jump fzf. Other directories don't have this problem

That is to say, only the Chinese folder in the soft link directory has this problem

**Comment by sxyazi** [comment]
Sounds like it might be related to symbolic links. I will investigate it further.

**Comment by DreamMaoMao** [comment]
There are other  bugs about link path. After opening link path, whether it is deleted, created, or renamed, it will automatically trigger a jump to the previous level of directory

**Comment by sxyazi** [comment]
> There are other bugs about link path. After opening link path, whether it is deleted, created, or renamed, it will automatically trigger a jump to the previous level of directory

Can you record a GIF for this?

**Comment by DreamMaoMao** [comment]
> > There are other bugs about link path. After opening link path, whether it is deleted, created, or renamed, it will automatically trigger a jump to the previous level of directory还有其他关于链接路径的bug。打开链接路径后，无论是删除、创建还是重命名，都会自动触发跳转到上一级目录
> 
> Can you record a GIF for this?你能为这个录个GIF吗？

https://github.com/sxyazi/yazi/assets/30348075/a8205fa5-7728-4128-8d36-fe3e800c5e89

**Comment by sxyazi** [comment]
I made a PR to fix this, can you take a look if the issue has gone

https://github.com/sxyazi/yazi/pull/121

**Comment by DreamMaoMao** [comment]
> I made a PR to fix this, can you take a look if the issue has gone我做了一个公关来解决这个问题，你能看看这个问题已经解决了吗
> 
> #121

The problem has been solved

**Comment by sxyazi** [comment]
Thanks for the testing

**Comment by DreamMaoMao** [comment]
It's a little strange that after I updated the main branch code to compile, I found that the first fzf problem was solved, and the problem that automatic jump to the upper level directory was still not solved

Then I went back to test the pr branch and found the same thing, the problem that  automatic jump problem appeared again

**Comment by sxyazi** [comment]
Unfortunately I can't reproduce the issue, it works fine on my side.

I created a symlink directory as you did and put it under HOME, then added files and deleted files to it, but did not encounter a "leave".


https://github.com/sxyazi/yazi/assets/17523360/5383cb60-f7a1-48b0-8d5f-449bbb5b062c

**Comment by DreamMaoMao** [comment]
I know why the first time I tested no problem, because I tested fzf first, but after the test,fzf jumped to the real path, so the automatic leave directory is not a valid test


https://github.com/sxyazi/yazi/assets/30348075/5f444f0d-d262-4f0d-85b3-ded9ea1981fc

**Comment by sxyazi** [comment]
I'm not sure how to reproduce your issue. Could you try applying the following patch, then perform the same operation, and paste the results of `cat ~/.local/state/yazi/yazi.log` here?

```patch
diff --git forkSrcPrefix/core/src/manager/watcher.rs forkDstPrefix/core/src/manager/watcher.rs
index 1e6c3fcd041c9600d711e831b0ca79d481f61e89..6962b8a7f64649a27458bc670cb02115a462e74e 100644
--- forkSrcPrefix/core/src/manager/watcher.rs
+++ forkDstPrefix/core/src/manager/watcher.rs
@@ -6,6 +6,7 @@ use parking_lot::RwLock;
 use shared::Url;
 use tokio::{fs, pin, sync::mpsc::{self, UnboundedReceiver}};
 use tokio_stream::{wrappers::UnboundedReceiverStream, StreamExt};
+use tracing::info;
 
 use crate::{emit, external, files::{File, Files, FilesOp}};
 
@@ -156,6 +157,7 @@ impl Watcher {
 	}
 
 	async fn file_changed(urls: &[Url], watched: Arc<RwLock<IndexMap<Url, Option<Url>>>>) {
+		info!("file changed: {:?}", urls);
 		let Ok(mut mimes) = external::file(urls).await else {
 			return;
 		};
@@ -177,6 +179,7 @@ impl Watcher {
 	}
 
 	async fn dir_changed(url: &Url, watched: Arc<RwLock<IndexMap<Url, Option<Url>>>>) {
+		info!("dir changed: {:?}", url);
 		let linked: Vec<_> = watched
 			.read()
 			.iter()
```

By the way, it seems like your password got leaked in the video...

**Comment by DreamMaoMao** [comment]
thanks  i will try tomorrow

**Comment by DreamMaoMao** [comment]
before patch , i have see many error in the log ,
![image](https://github.com/sxyazi/yazi/assets/30348075/85fd4b6e-1f1e-49ad-808d-72946d40d1cf)

**Comment by sxyazi** [comment]
You can do a `file -bL --mime-type /home/wrq/down` and `file -bL --mime-type /home/wrq/test` manually to see what was happening

**Comment by DreamMaoMao** [comment]
> You can do a `file -bL --mime-type /home/wrq/down` and `file -bL --mime-type /home/wrq/test` manually to see what was happening您可以手动执行 `file -bL --mime-type /home/wrq/down` 和 `file -bL --mime-type /home/wrq/test` 以查看发生了什么

![image](https://github.com/sxyazi/yazi/assets/30348075/12fedd12-85e5-4a24-a3e7-6bb38bbe54b5)

**Comment by DreamMaoMao** [comment]
https://github.com/sxyazi/yazi/assets/30348075/bcfd8dd8-a747-4e81-af4c-cb2cbb89c64b
the error caused the automatic jump

**Comment by DreamMaoMao** [comment]
![image](https://github.com/sxyazi/yazi/assets/30348075/a94b4ee2-0960-43f9-babc-21f30f510f97)
after patch:

https://github.com/sxyazi/yazi/assets/30348075/c5de4fc1-3a72-4dfa-b5f4-93009c5766f1

log:

[yazi.log](https://github.com/sxyazi/yazi/files/12554452/yazi.log)

**Comment by DreamMaoMao** [comment]
> Not sure why `/home/wrq/down` is being recognized as a file.不知道为什么 `/home/wrq/down` 被识别为文件。
> 
> This might be a Linux-specific behavior. I'll install a Linux to test it shortly.这可能是Linux特有的行为。我将安装一个Linux来测试它。

The linux symlink seems to be a special file

**Comment by sxyazi** [comment]
> The linux symlink seems to be a special file

That makes sense. Please try the new PR https://github.com/sxyazi/yazi/pull/125

**Comment by DreamMaoMao** [comment]
it work now
