### ISSUE TITLE
file tree in folder preview?

### ISSUE THREAD

**Issue by GNOMES** [sxyazi/yazi#1085]
### Please describe the problem you're trying to solve

Is it already possible to have a file tree in folder preview? Or will this require a custom previewer?

in VIFM for example I accomplish this by leveraging EZA using:

`fileviewer */,.*/ eza -T --color=always --level=5 %c`

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Would like to see a file tree of folders and files while the cursor is over a directory

**Comment by sxyazi** [comment]
Yeah it needs a custom previewer, you can refer to https://github.com/ndtoan96/ouch.yazi to implement it, and then configure it as the directory previewer in your `yazi.toml`:

```
prepend_previewers = [
  { name = "*/", run = "your-previewer" },
]
```

The docs can be found at https://yazi-rs.github.io/docs/plugins/overview#previewer and https://yazi-rs.github.io/docs/configuration/yazi#plugin.previewers

**Comment by sxyazi** [comment]
FYI, @sharklasers996 made it a plugin, check out https://github.com/sharklasers996/eza-preview.yazi 🎉👍
