### ISSUE TITLE
Word wrapping in preview

### ISSUE THREAD

**Issue by mskvsk** [sxyazi/yazi#1089]
### Please describe the problem you're trying to solve

Word wrapping in preview has been a pretty contentious issue in the discussions of at least two terminal file managers. Some people like to scroll it, some people prefer it to word wrap.

Personally, I would like some of my documents to word wrap, while the others and code to not to.

I suspect, many people have their own expectations around that which I will try to address in the solution.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

An optional "wrap" field in the previewers array in yazi.toml

True for word wrapping, false for long lines. The default is false. Ignored if the active preview is not wrappable.

Example:

```
previewers = [
	{ name = "*/", run = "folder", sync = true },
	# Code
	{ mime = "text/*", run = "code" },
	{ mime = "*/{xml,javascript,x-wine-extension-ini}", run = "code" },
	# JSON
	{ mime = "application/json", run = "json", wrap = true},
]

```

**Comment by mskvsk** [comment]
Also, I have never written any Rust but can give it a shot if @sxyazi deems this feature good to have.

We can also downscale the scope of this feature to a single boolean (wordwrap = true/false) in the config if it seems an overkill.

All I need is my text files to word wrap as I use text preview on them daily.

**Comment by sxyazi** [comment]
Nice to have!

Would you like to raise a PR for it? Here is the method that handles code highlighting: https://github.com/sxyazi/yazi/blob/9df256f7f4abc312ae94b59c948502310ecb2c87/yazi-plugin/src/external/highlighter.rs#L59

Maybe we can change its function signature to:

```rust
pub async fn highlight(&self, skip: usize, area: Rect, wrap: bool) -> Result<Text<'static>, PeekError> {
```

And handle text wrapping when `wrap = true`.

**Comment by mskvsk** [comment]
Sure, will do. I'm half-way through the solution alredy.

**Comment by sxyazi** [comment]
If anyone is interested in implementing it, https://github.com/sxyazi/yazi/pull/1142 would be a great starting point.

**Comment by mskvsk** [comment]
I might also add that I am ready to pay a small bounty of $50 in crypto (USDC/USDT) to anyone who solves this issue without using an external crate (I don't mind if you copypaste the solution from the crate I have used in my PR).

This feature is quite nice to have to me, as I use Yazi to browse a lot of personal content that is stored as separate text files which don't look good without wrapping.

**Comment by ArtyomArtamonov** [comment]
Hello @mskvsk, I tried to solve this problem  in #1159. Your previous commits helped me a bit, so thanks for that! You can try and build my solution, check it out on your use cases, maybe you will find some bugs. Feel free to comment and review my code!

**Comment by ArtyomArtamonov** [comment]
I found an issue with files that are handled by plugins, like `json`, `toml` etc. They use `preview_widgets`, not `preview_code` function. But `file.lua` plugin has word wrapping functionality in it, handled by Lua. Should Rust application handle the word wrapping or this is responsibility of plugins?

**Comment by mskvsk** [comment]
Thank you, I tried it out and have left some comments!

**Comment by sxyazi** [comment]
Thanks for the PR @ArtyomArtamonov! I'll review it ASAP

**Comment by mskvsk** [comment]
@ArtyomArtamonov It seems that your PR is accepted so feel free to send me your Ethereum address for the bounty. Thank you.

**Comment by DirkFi** [comment]
Is this issue fixed by the PR by ArtyomArtamonov? If so, we may close this one. I'm trying to look into some issues to commit.

**Comment by sxyazi** [comment]
Done in https://github.com/sxyazi/yazi/pull/1159 🎉
