### ISSUE TITLE
Brew instructions are outdated

### ISSUE THREAD

**Issue by glensc** [sxyazi/yazi#1099]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

-

### Did you try the latest code to see if this problem got fixed?

Not tried, and I'll explain why below

### `yazi --debug` output

-

### Describe the bug

```
Error: homebrew/cask-fonts was deprecated. This tap is now empty and all its contents were either deleted or migrated.
```

### Expected Behavior

👍🏿 

### To Reproduce

Run the following from https://yazi-rs.github.io/docs/installation#homebrew:

```sh
brew install yazi ffmpegthumbnailer unar jq poppler fd ripgrep fzf zoxide
brew tap homebrew/cask-fonts && brew install --cask font-symbols-only-nerd-font
```

also, poppler is conflicted, is xpdf also fine?

```
Error: Cannot install poppler because conflicting formulae are installed.
  xpdf: because poppler, pdftohtml, pdf2image, and xpdf install conflicting executables

Please `brew unlink xpdf` before continuing.

Unlinking removes a formula's symlinks from /opt/homebrew. You can
link the formula again after the install finishes. You can `--force` this
install, but the build may fail or cause obscure side effects in the
resulting software.
```

### Anything else?

I installed with the following:

```sh
brew install yazi ffmpegthumbnailer unar jq 
brew install fd ripgrep fzf zoxide
brew install font-symbols-only-nerd-font
```

**Comment by sxyazi** [comment]
Thanks for the report. 

I fixed the font issue in https://github.com/yazi-rs/yazi-rs.github.io/commit/4b3c95dd8956b991e076cf36be23cd73ce8ea98f. 

Regarding the conflict between xpdf and poppler, I don't think they are interchangeable equivalents. If you need poppler, you might need to uninstall xpdf, or you can unlink it with `brew unlink xpdf`.
