### ISSUE TITLE
Add option to turn off selection cursor blink in input

### ISSUE THREAD

**Issue by dangooddd** [sxyazi/yazi#1101]
### Please describe the problem you're trying to solve

Search, find and other popups got cursor blink (or some sort of animation). I thought that it can be changed in theme.toml [input] -> selected field, but changing anything here does nothing to ui. 

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Add option to theme.toml that turn off cursor blink animation.
If it exist, add some guidelines for it in documentation

**Comment by dangooddd** [comment]
I figured out what selected field in theme.toml does, and it don't change cursor behavior

**Comment by sxyazi** [comment]
I don't quite understand what you mean, can you record a gif?

**Comment by dangooddd** [comment]
![blink](https://github.com/sxyazi/yazi/assets/113844030/7ade80d8-465e-4d19-9fa4-3e31653d3aae)
Sorry, hope here you understand! (in find popup there is cursor animation)

**Comment by sxyazi** [comment]
I see, but Yazi doesn’t add a blinking to the cursor. I think it largely depends on your terminal style/config - what terminal are you using? Is it the same with other terminals?

My terminal (kitty) looks like :


https://github.com/sxyazi/yazi/assets/17523360/2a3d4979-bcb7-4f30-8058-4be033940ebb

**Comment by dangooddd** [comment]
idk why, but wezterm draws blinking cursor in all yazi's input popups. But disabling blinking globally is not a great solution. Can it be changed in other way?

**Comment by dangooddd** [comment]
And also, it seems like you also got some sort of blink, or i misunderstand it

**Comment by dangooddd** [comment]
Check foot, also got blinking in input fields. I mean is there a way to make cursor in input field completely constant?
/home/dangoodd/Downloads/foot_blink.mp4

**Comment by og900aero** [comment]
> foot_blink.mp4 
> Checked out foot, also got blinking in input fields. I mean is there a way to make cursor in input field completely constant? Maybe add settings group for cursor in theme.toml (it will be nice!) ?

It is terminal "problem"/config. I'm on Debian 12 stable and I try with any terminal, but doesnt blink:
- alacritty
- st
- kitty
- xterm
- urxvt

**Comment by dangooddd** [comment]
@og900aero i got cursor blink in kitty too... (zero config)

https://github.com/sxyazi/yazi/assets/113844030/9180015b-b33d-403b-b6b7-2386787cdd49
