### ISSUE TITLE
Support Close Current Tab

### ISSUE THREAD

**Issue by chaozwn** [sxyazi/yazi#1102]
### Please describe the problem you're trying to solve

link: https://yazi-rs.github.io/docs/configuration/keymap/#manager.tab_close

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Add a --current argument to close the current tab

**Comment by sxyazi** [comment]
https://github.com/sxyazi/yazi/blob/46cd42f923d11a2bf29b13d8a01de63137fb70f5/yazi-config/preset/keymap.toml#L12

closing as already exist
