### ISSUE TITLE
mark/unmark feature?

### ISSUE THREAD

**Issue by KaleTheDemon** [sxyazi/yazi#1106]
### Please describe the problem you're trying to solve

Perhaps this already exists and I don't know how to do it but I am looking for a mark and unmark feature like ranger has. Where, for example, one could type :mark .mp3 and it would select all of the mp3 files in the current directory. Or :unmark cheese and it would deselect any files which had cheese in the name.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

A mark and unmark feature similar to ranger.

**Comment by Brixy** [comment]
Would this be a solution for you:

- `f` (filter)
- type `\.mp3<Enter>`
- `Ctrl + a` (select all)

Yet, when you press `ESC` to clear the filter, the selected files will be unselected first. `mark`/`unmark` would probably solve this.

And to unselect:

- select all files
- `f`
- type `\.mp3<Enter>`
- `Ctrl + r` (invert selection) or `VG`

**Comment by KaleTheDemon** [comment]
@Brixy That does work exactly the way I would like. It allows me to easily select all files of a certain type and then deselect a specific group of files within that. Thank you for your help.
