### ISSUE TITLE
Possibility to navigate different drives on Windows

### ISSUE THREAD

**Issue by cbr9** [sxyazi/yazi#1107]
### Please describe the problem you're trying to solve

I'd like to switch drives from yazi itself, without tricks like zoxide or jumping back to the shell, changing directory, and then opening yazi

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

When you go to the root folder, it should be possible to switch to a different drive letter

**Comment by sxyazi** [comment]
You can either:

- Click `g<Space>` to open the interactive `cd`, then type `D:\` to navigate
- Bind a key to navigate like this:
  ```
  { on = [ "g", "d" ], run = "cd 'D:\\'" }
  ```

With the nightly build, you can use `D:` instead of `D:\` / `D:\\` for convenience. Closing as already supported.
