### ISSUE TITLE
[Feature Request] add rg search preview

### ISSUE THREAD

**Issue by DreamMaoMao** [sxyazi/yazi#111]
![image](https://github.com/sxyazi/yazi/assets/30348075/74d8bf8b-6927-4dce-80fb-efe78fa1caed)

Can rg search preview like this in the nvim plugin, or can it jump directly to fzf, like using the `rg | fzf` command on the command line

**Comment by sxyazi** [comment]
I'm not sure how to preview file content in `rg`. Does `rg` have any parameters itself that can achieve the effect shown in the image?

**Comment by DreamMaoMao** [comment]
> I'm not sure how to preview file content in `rg`. Does `rg` have any parameters itself that can achieve the effect shown in the image?

it not only use rg, it more like use command like this "rg  ./ | fzf "

**Comment by DreamMaoMao** [comment]
![image](https://github.com/sxyazi/yazi/assets/30348075/da83a2a8-efcf-4335-a810-6891b4391529)

![image](https://github.com/sxyazi/yazi/assets/30348075/baab0cbc-be39-463d-989a-0c5f71510086)

**Comment by DreamMaoMao** [comment]
rg ./ --line-number | fzf :
you can get filename  to show filecontent preview and get the linenumber to highlight 
![image](https://github.com/sxyazi/yazi/assets/30348075/76b4c8a5-793a-4db9-ab4e-e4e77daa9a39)

**Comment by sxyazi** [comment]
It seems that allowing users to customize the `rg` and `fzf` commands for execution would be helpful, but I'm not sure whether this should belong to `rg` or `fzf`, since both are being used. Does it seem like `rg` is a good choice?

**Comment by DreamMaoMao** [comment]
> It seems that allowing users to customize the `rg` and `fzf` commands for execution would be helpful, but I'm not sure whether this should belong to `rg` or `fzf`, since both are being used. Does it seem like `rg` is a good choice?

The simplest way  is to add a `jump rg` option similar to the existing `jump fzf`, which actually uses `rg ./ --line-number | fzf`

**Comment by sxyazi** [comment]
I see. I won't implement it immediately; I'll wait until Yazi's plugin system is available and then implement it as a plugin.

**Comment by sxyazi** [comment]
Done in https://github.com/sxyazi/yazi/pull/884, I reimplemented `fzf` as a plugin and provided a code template. You can make minor changes based on this template to combine `fzf` with `rg`.

**Comment by sxyazi** [comment]
Looks cool!

Why not directly embed the shell into init.lua, like `Command("sh"):args({"-c", "your fzf command"})`, so there's no need to rely on a specific shell (bash or fish) or external files

**Comment by DreamMaoMao** [comment]
make sense
