### ISSUE TITLE
Add a 20ms delay before loading files

### ISSUE THREAD

**Issue by Zeioth** [sxyazi/yazi#1115]
### Please describe the problem you're trying to solve

If I keep <Down> pressed to scroll the files in a directory, the cursor scroll is not 100% smooth. This happen because Yazi tries to load files ASAP.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

By hardcoding a tiny delay before loading files, we can achieve smoother scroll and improve the user experience.

**Comment by sxyazi** [comment]
Are you talking about loading directories in the preview pane? If so, all directory read operations are asynchronous and can be discarded, with only one directory being loaded at a time, so I don't think that's causing the lag.

**Comment by sxyazi** [comment]
Also, some terminals add a delay which can make things seem slow. Have you tried other terminals, like Alacritty, to see if the issue still?
