### ISSUE TITLE
Print the cwd to stdout

### ISSUE THREAD

**Issue by linsui** [sxyazi/yazi#112]
Currently yazi provide `--cwd-file` to get the cwd from a file. I thought it would be more intuitive to print the path to stdout directly, similiar to fzf. `yazi --cwd-file=/dev/stdout` doesn't works so I guess the implementation is different.

**Comment by sxyazi** [comment]
The impl of Yazi and fzf fundamentally differs. fzf sends its TUI to `stderr`; you can verify this by running `fzf 2> /dev/null`, which will not display any content.

Yazi uses `stdout` as its TUI endpoint, which I believe is a more suitable approach for TUI apps. Therefore it's no longer an option for using `stdout` as `cwd-file`.

For `yazi --cwd-file=/dev/stdout`, this is an incorrect case. You should specify a temporary file for `cwd-file`, just like it's mentioned in the README:

https://github.com/sxyazi/yazi/blob/eee68a99b4db9de0cba4b4e0b2a5b63bff618071/README.md?plain=1#L137-L146

**Comment by linsui** [comment]
> The impl of Yazi and fzf fundamentally differs. fzf sends its TUI to stderr; you can verify this by running fzf 2> /dev/null, which will not display any content.

Interesting! And just for fun, this also works:

`cd $(yazi --cwd-file /dev/stderr 3>&1 1>&2 2>&3 | cat)`

**Comment by sxyazi** [comment]
> `cd $(yazi --cwd-file /dev/stderr 3>&1 1>&2 2>&3 | cat)`

Oh that's really cool! Could you explain its principle?

**Comment by linsui** [comment]
It's stolen from https://serverfault.com/questions/63705/how-to-pipe-stderr-without-piping-stdout. ;)
