### ISSUE TITLE
Implement `org.freedesktop.FileManager1`

### ISSUE THREAD

**Issue by poperigby** [sxyazi/yazi#1120]
### Please describe the problem you're trying to solve

This might be totally out of scope and maybe even impossible, but I was wondering if the `org.freedesktop.FileManager1` interface could be implemented for Yazi. This would allow Yazi to be opened when this interface is called, like from within Firefox.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Implement the interface as described here: https://www.freedesktop.org/wiki/Specifications/file-manager-interface/

**Comment by sxyazi** [comment]
Yeah this goes beyond the scope of a terminal file manager because it involves the user's desktop environment, and it’s only applicable to Linux systems. 

So I suggest using https://github.com/GermainZ/xdg-desktop-portal-termfilechooser along with Yazi to achieve this functionality.

**Comment by poperigby** [comment]
Oh cool, that works with `org.freedesktop.FileManager1` and the file manager portal, or are those the same thing?

**Comment by sxyazi** [comment]
I'm not quite sure about the implementation details, from the code, it seems to implement the [`org.freedesktop.impl.portal.FileChooser` interface](https://github.com/GermainZ/xdg-desktop-portal-termfilechooser/blob/71dc7ab06751e51de392b9a7af2b50018e40e062/termfilechooser.portal#L3). 

I found the specification here https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.impl.portal.FileChooser.xml
