### ISSUE TITLE
Circular navigation

### ISSUE THREAD

**Issue by ih8d8** [sxyazi/yazi#1121]
### Please describe the problem you're trying to solve

By circular navigation, I mean when navigating a list with arrow keys, reaching the end and continuing to press the arrow key moves the selection back to the beginning of the list (or vice versa). 

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

When navigating a list with arrow keys, reaching the end and continuing to press the arrow key moves the selection back to the beginning of the list (or vice versa).

**Comment by sxyazi** [comment]
Hi there, check out this tip https://yazi-rs.github.io/docs/tips#navigation-wraparound

Closing as already exists.

**Comment by sxyazi** [comment]
It's now a built-in feature with https://github.com/sxyazi/yazi/pull/2485 🎉
