### ISSUE TITLE
konsole terminal cannot automatically clean image previews

### ISSUE THREAD

**Issue by DreamMaoMao** [sxyazi/yazi#1122]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

konsole 23.08.4

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh

Yazi
    Version: 0.2.5 (2c84c48 2024-06-04)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.2.5

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Konsole)
    Emulator.detect : Konsole

Adaptor
    Adaptor.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-1")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/fish")
    EDITOR             : Some("nvim ")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "$EDITOR \"$1\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: false })
    block  : Some(Opener { run: "$EDITOR \"$1\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: false })

tmux
    TMUX   : false
    Version: 3.4

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-27
    fzf              : 0.42.0
    fd               : 9.0.0
    rg               : 13.0.0
    chafa            : 1.14.0
    zoxide           : 0.9.2
    unar             : ExitStatus(unix_wait_status(32512)), "unar: error while loading shared libraries: libicuuc.so.74: cannot open shared object file: No such file or directory\n"
    jq               : 1.7


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/wrq/.local/state/yazi" directory.



```

</details>

### Describe the bug

After selecting an image file, and then selecting another non-image file, the preview of the previous image file remains, and the image is not cleared.

https://github.com/sxyazi/yazi/assets/30348075/168bb6be-ea23-4a47-9091-c1e5fd051fca

### Expected Behavior

the image preview should be clear after swith to a non-image file.

### To Reproduce

1.select a image file
2. then select a non-image file

**Comment by sxyazi** [comment]
Try upgrading your Konsole to the latest

**Comment by DreamMaoMao** [comment]
> Try upgrading your Konsole to the latest

still not work

![image](https://github.com/sxyazi/yazi/assets/30348075/c75e651e-2db8-437e-939e-fa0c7759fef7)


![image](https://github.com/sxyazi/yazi/assets/30348075/87285683-24c4-4342-8d98-ec1097c3bfac)

**Comment by DreamMaoMao** [comment]
![image](https://github.com/sxyazi/yazi/assets/30348075/4572ae38-09b8-4f87-8505-0c7e2ee5a966)


this commit cause it

**Comment by sxyazi** [comment]
Fixed in https://github.com/sxyazi/yazi/commit/5f8c20e2b517faea53680f720553d20ec363e9ab

Switched back to the old kitty protocol as the iterm2 and sixel protocol implementations in Konsole are buggy, https://bugs.kde.org/show_bug.cgi?id=456354.
