### ISSUE TITLE
Files in .ndjson format fail to open

### ISSUE THREAD

**Issue by FoxWDN** [sxyazi/yazi#1129]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.35.1

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.5 (9df256f 2024-06-05)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.2.5

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adaptor
    Adaptor.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-1")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "$EDITOR \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "$EDITOR \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.5
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-33
    fzf              : 0.52.1
    fd               : 10.1.0
    rg               : No such file or directory (os error 2)
    chafa            : 1.14.0
    zoxide           : No such file or directory (os error 2)
    unar             : No such file or directory (os error 2)
    jq               : 1.7.1

```

</details>

### Describe the bug

Yazi hangs with `99%, 1 left` when trying to open any file in ndjson format, running xdg-open works as expected

### Expected Behavior

ndjson files open without errors

### To Reproduce

1. Open yazi
2. Navigate to any file in ndjson format
3. Try to open it

### Configuration

no config

### Anything else?

![yazi-ndjson](https://github.com/sxyazi/yazi/assets/124158438/6e04c373-468f-4ba9-b6b2-24bc8e23ef41)

**Comment by sxyazi** [comment]
Press `w` to see what task stuck the progress, then click `Enter` to inspect the error

**Comment by FoxWDN** [comment]
`w` returns `Run "xdg-open \"$@\"" with /home/foxwdn/Downloads/test.ndjson /home/foxwdn/Downloads/test.ndjson`, `Enter` returns nothing but blinking cursor

**Comment by sxyazi** [comment]
Try running `xdg-open /home/foxwdn/Downloads/test.ndjson /home/foxwdn/Downloads/test.ndjson` directly without Yazi in your shell to see what happened

**Comment by FoxWDN** [comment]
Running `xdg-open` with two `test.ndjson` inputs fails as expected:
```
xdg-open: unexpected argument '/home/foxwdn/Downloads/test.ndjson'
Try 'xdg-open --help' for more information.
```
Running `xdg-open` with one `test.ndjson` argument opens the file in default editor, also as expected.

**Comment by FoxWDN** [comment]
Never mind, just had to add an [open] rule in `yazi.toml`:
```
{ mime = "application/x-ndjson", use = [ "edit", "reveal" ] },
```
Sorry for the inconvenience.
