### ISSUE TITLE
Since mouse event support was added, selection and copying of strings in yazi seems impossible.

### ISSUE THREAD

**Issue by ThGrSoRu** [sxyazi/yazi#1132]
### Please describe the problem you're trying to solve

Strings in file previews used to be selectable with the mouse, aswell as filenames, allowing to copy parts of a filename or words in a textfile preview.
This seems no longer possible even when disabling all mouse events.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

When setting `mouse_events=[]`, make all strings selectable with the mouse so that it can be copied, just as before mouse event support was added.

**Comment by DreamMaoMao** [comment]
you can keep press shift key, and then you can use cursor to select and copy text like before

**Comment by sxyazi** [comment]
`mouse_events = []` should disable mouse completely, i.e. original behavior, reopening
