### ISSUE TITLE
Copy files / dirs with keep create/mod data as in origin

### ISSUE THREAD

**Issue by mmuruev** [sxyazi/yazi#1134]
### Please describe the problem you're trying to solve

Not sure it's here or but, other managers suffers with this, if you do copy (not move it updates) all creation time and mod time, which can be seem as correct, but for example you have an huge archive with photos for 5-10 years and want copy it to spare drive to keep it save..on copy all data will be updated and you got lost you create date and all arch will be 'created' in the day of copy. Which is not what you want in this case.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Must be some choice what to do with create/update date.

**Comment by sxyazi** [comment]
Currently, Yazi maintains the modification time of the original file when copying (implemented in https://github.com/sxyazi/yazi/pull/926). However, the creation time is set to the current time since it is a newly created file.

Let me know if this meets your needs, or if you also need the creation time to match the original file.

**Comment by mmuruev** [comment]
Yes I need way to keep creation time. I give you example when exactly this important. In fact I belive most 'human' will expect preserve the time on copy.. cause it's convenient despite fact that this is 'created' file.

**Comment by sxyazi** [comment]
Resubmitted https://github.com/sxyazi/yazi/commit/0f84717a1b459d9c2dc24f8b0440bed6b9218d64, now supports Windows as well

**Comment by sxyazi** [comment]
Hmmm I'm confused. Linux has the concept of creation time?
