### ISSUE TITLE
Previewing the content of archives with many files takes too long

### ISSUE THREAD

**Issue by ih8d8** [sxyazi/yazi#1138]
### Please describe the problem you're trying to solve

I'm migrating from nnn to yazi. I recently realized when previewing a zip file with many files and directories, nnn can list the data instantly but it takes tens of seconds for yazi to do the same. I don't know how nnn does it but the difference in user experience is very noticeable.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

It'd be a lot better for user experience if yazi was also able to instantly list the content of a zip file with a large number of files and directories.

**Comment by sxyazi** [comment]
This is a known issue - the builtin archive preview is currently a temporary implementation. It will be optimized in the future with the implementation of "Archives as directories" noted in [Feature Requests](https://github.com/sxyazi/yazi/issues/51). 

For now, please use a custom previewer for archive files, such as https://github.com/ndtoan96/ouch.yazi

**Comment by sxyazi** [comment]
Done in https://github.com/sxyazi/yazi/pull/1220
