### ISSUE TITLE
[Bug]When the file name is too long to renamed, it will retain the overflow part of the name .

### ISSUE THREAD

**Issue by DreamMaoMao** [sxyazi/yazi#114]
https://github.com/sxyazi/yazi/assets/30348075/207a8c77-42d7-4d58-a481-b978a3dec02d

my picture name is:
1ce2dcf7efb043fbe85800eeb9fda11d6f3ac93a4987a236beaced8bb18d2190.jpg

when I rename it, i can't see the fullname  on rename Input field.  so,when i just delet what i can see and input a new name, it will remain   some old string from the old fullname.

**Comment by sxyazi** [comment]
This is not a bug; you simply deleted the latter part of the file name, but the preceding content was not removed. Use `h` and `l` to scroll left and right within the input.

Also, for cases like this, you can use `cb` to delete all the preceding content at once, just like in Vim, without the need to delete each character one by one. (Demonstrated in the video at 00:10).

**Comment by DreamMaoMao** [comment]
> This is not a bug; you simply deleted the latter part of the file name, but the preceding content was not removed. Use `h` and `l` to scroll left and right within the input.这不是一个bug;你只是删除了文件名的后一部分，但前面的内容没有被删除。使用 `h` 和 `l` 在输入中左右滚动。
> 
> Also, for cases like this, you can use `cb` to delete all the preceding content at once, just like in Vim, without the need to delete each character one by one. (Demonstrated in the video at 00:10).此外，对于这种情况，你可以使用 `cb` 一次删除前面的所有内容，就像在Vim中一样，而不需要逐个删除每个字符。（在00：10的视频中展示）。
> 
>  11.mp4

thanks ,

重点词汇
19/5000
传统翻译模型
通用场景
I didn't notice that input field can switch to command mode by pressing esc
