### ISSUE TITLE
Any pop-up windows in rio terminal has jagged edges

### ISSUE THREAD

**Issue by cavivie** [sxyazi/yazi#1149]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

Yazi 0.2.5 (Homebrew 2024-04-23) / rioterm 0.1.0

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh

Yazi
    Version: 0.2.5 (Homebrew 2024-04-23)
    OS: macos-aarch64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("rio", "rio")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Iterm2

Adaptor
    Adaptor.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/bin/zsh")
    EDITOR: Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.41\nmagic file from /usr/share/file/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/Users/cavivie/.local/state/yazi" directory.
```

</details>

### Describe the bug

Rio terminal:
![image](https://github.com/sxyazi/yazi/assets/103884097/f47315ec-98fc-49b6-b519-d460fa2c221d)

iTerm2 terminal:
![image](https://github.com/sxyazi/yazi/assets/103884097/cd868863-8bbc-4416-aebf-d07c2d839cfc)

macOS builtin terminal:
![image](https://github.com/sxyazi/yazi/assets/103884097/e06e7f03-220c-4d42-a5ef-4308a21dac05)

### Expected Behavior

There should be no jagged edges on any pop-up windows. At least, this problem is not found in other terminals such as iterm2 and built-in terminal. Is it possible that this problem should be reported to rio?

### To Reproduce

Install yazi in rio terminal, start yazi and pop up any built-in command window. To reproduce, press `c` to pop up the copy related window, or press `g` to pop up the change directory related window, etc.

**Comment by sxyazi** [comment]
> Is it possible that this problem should be reported to rio?

Yes, this is a bug introduced in Rio v0.1.0, see https://github.com/raphamorim/rio/issues/534. You can try reverting to an older version as a workaround until the devs fix it.

Closing as not Yazi.
