### ISSUE TITLE
No file preview under windows

### ISSUE THREAD

**Issue by ShrykeWindgrace** [sxyazi/yazi#115]
Hi! 

I was waiting for the windows release, thanks for making that happen!

I have a couple issues/question however - I have neither file preview (regardless of file extension - tested on txt, nix, json, md, and ini) nor file editing.

Config:
- `Win10`, latest `WindowsTerminal` for emulator, and `pwsh` for shell
- `yazi` installed via `scoop` (but the problem is present on a standalone executable)
- tools like `vim`, `jq`, `fd`, `fzf`, and `ripgrep` are present in `$PATH`

`yazi` is run with the default config - by the way, where is its config folder under windows?

Setting `$env:EDITOR`  does not bring back file editing upon hitting `enter`.

Cheers!

**Comment by sxyazi** [comment]
Hi there, thank you for giving Yazi's Windows version a try and for reporting the related issues. Your feedback is greatly appreciated, and it will be instrumental in making Yazi for Windows even better!

Regarding the issue with file preview not working, have you followed the instructions in the Wiki to install Git and manually set the `PATH` to the location of `file(1)`? You can check this by running `file` in Windows Terminal.

The configuration files for Windows can be placed in `C:\Users\YourName\AppData\Roaming\yazi\config`, and I will add this to the Wiki. You will need to edit the [`opener` in `yazi.toml`](https://github.com/sxyazi/yazi/blob/eee68a99b4db9de0cba4b4e0b2a5b63bff618071/config/preset/yazi.toml#L24) to set an application for opening files, such as VSCode.

**Comment by ShrykeWindgrace** [comment]
Thanks for the prompt answer! 

> Regarding the issue with file preview not working, have you followed the instructions in the Wiki to install Git and manually set the PATH to the location of file(1)? You can check this by running file in Windows Terminal.

Indeed, that was the missing piece. In my case, after a `scoop install file` the preview works as intended, thanks a lot!

> The configuration files for Windows can be placed in C:\Users\YourName\AppData\Roaming\yazi\config, and I will add this to the Wiki. You will need to edit the [opener in yazi.toml](https://github.com/sxyazi/yazi/blob/eee68a99b4db9de0cba4b4e0b2a5b63bff618071/config/preset/yazi.toml#L24) to set an application for opening files, such as VSCode.

I'll test that shortly, thanks!

**Comment by sxyazi** [comment]
Hi @ShrykeWindgrace, since the file preview is working now, I think it's time to close this issue.

If you have any other issues, feel free to file a new issue!
