### ISSUE TITLE
add vim like `find/jump_to_character` command.

### ISSUE THREAD

**Issue by hakan-demirli** [sxyazi/yazi#1154]
### Please describe the problem you're trying to solve

- 999+ files
- Files have random/long names.
- All I know is the file of interest starts with letter `a`.

I wish to quickly jump to that file.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Same solution as `lf`:
- Two key operation like vim. Example: `fa` cursor goes to first word starting with letter `a`.
- I wish to do the same in yazi. Example: `fa` cursor/selection goes to first file starting with letter `a`.

### Additional context
Currently find command has no position priority. If it finds the character in the middle of the name it settles.
![image](https://github.com/sxyazi/yazi/assets/78746991/65bacbba-d4a9-4990-a2a0-c456db07507a)
In the image, I am trying to jump to a file starting with letter `c`.

**Comment by sxyazi** [comment]
You can easily implement it through the plugin system. 

Here's a version I implemented, feel free to use it: https://github.com/yazi-rs/plugins/tree/main/jump-to-char.yazi


https://github.com/sxyazi/yazi/assets/17523360/01e2d193-60b9-4894-8967-47da901346cf

**Comment by sxyazi** [comment]
BTW, you might also be interested in https://github.com/DreamMaoMao/keyjump.yazi and https://github.com/DreamMaoMao/searchjump.yazi. 

They are two other powerful jump plugins, corresponding to `hop.nvim` and `flash.nvim` in Vim respectively.
