### ISSUE TITLE
Scale is messed up if yazi is resized when it is in another workspace.

### ISSUE THREAD

**Issue by hakan-demirli** [sxyazi/yazi#1158]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.35.1

### Did you try the latest code to see if this problem got fixed?

Not tried, because only commit referencing `resize` is in Jan 6 and the latest release is in April.

### `yazi --debug` output

<details>

```sh

❯ yazi --debug

Yazi
    Version: 0.2.5 (VERGEN_IDEMPOTENT_OUTPUT 1980-01-01)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-kitty", "tmux")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Kitty

Adaptor
    Adaptor.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY: Some("wayland-1")
    DISPLAY: Some(":1")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/run/current-system/sw/bin/bash")
    EDITOR: Some("hx")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.45\nmagic file from /nix/store/cz28fainhxq78r4l4wgr140izc9hxsxp-file-5.45/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "$EDITOR \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "$EDITOR \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: true

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })


--------------------------------------------------
```

</details>

### Describe the bug

Expected/Normal GUI.
![image](https://github.com/sxyazi/yazi/assets/78746991/a2a74c6c-4391-4c0c-b500-c824e68d0365)

Broken/Messed up GUI. (I had to take a photo using my phone since pressing prtscrn fixes the issue.
![image](https://github.com/sxyazi/yazi/assets/78746991/5b139889-f035-427e-bfc1-3027b1d86283)

### Expected Behavior

No distortion or wrong scale/zoom.

### To Reproduce

In Hyprland WM using Kitty terminal:
* Open yazi and another app side by side.
* Switch to another workspace
* Kill the app that was next to yazi
* Return back to the workspace which yazi was open
* Observe the messed up scale/zoom

### Anything else?

This bug does not effect me. I also don't care if it is fixed or not. I just wanted to document a weird behavior I have encountered. This does not happen in `lf` file manager. So, I thought it is a yazi bug. Feel free to close as `won't fix` if this is too minor to be called a bug or can't reproduce.

**Comment by sxyazi** [comment]
I'm not quite sure what you mean - could you record a GIF and show me what's happening please?

**Comment by hakan-demirli** [comment]
[Kooha-2024-06-16-13-39-30.webm](https://github.com/sxyazi/yazi/assets/78746991/9017ae0a-3a88-4edf-bf78-af297d8f0a7c)

**Comment by hakan-demirli** [comment]
* Problem does not exist on Alacritty and Termite.
* Problem only happens on Kitty.
* No difference between latest release and main branch.

Yea, It is a kitty specific issue.
