### ISSUE TITLE
Quick filter method

### ISSUE THREAD

**Issue by oiiiiiiii** [sxyazi/yazi#1161]
### Please describe the problem you're trying to solve

I'm always frustrated when the following happens:
1. I search for a directory I want to enter using the filter option
2. I enter an unambiguous name, so there i only 1 result
3. I have to manually enter it

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

I understand, that not everyone want to enter a directory they filtered for. Maybe it's supposed to be copied/deleted/etc. But I feel like there should be a better way to navigate. Maybe using capital F as a quick filter method that enters the directory / opens the file once the name is distinct (only 1 result).

**Comment by sxyazi** [comment]
Hi, I made a plugin for it a few days ago that extends the existing filter - it will automatically enter the only directory, and I've also added other enhancements, like supporting continuous filtering and automatically opening the hovered file on submitting:


https://github.com/sxyazi/yazi/assets/17523360/0007e5e5-ed9e-4104-ad13-0678b73af1f1



Feel free to use it: https://github.com/yazi-rs/plugins/tree/main/smart-filter.yazi

Closing as already exists
