### ISSUE TITLE
heic thumbnails don't show foot terminal 

### ISSUE THREAD

**Issue by pepperonipizzah** [sxyazi/yazi#1168]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

Yazi
    Version: 0.2.5 (Arch Linux 2024-04-27)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect: Foot

Adaptor
    Adaptor.matches: Sixel

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY: Some("wayland-1")
    DISPLAY: Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/usr/bin/fish")
    EDITOR: None
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.45\nmagic file from /usr/share/file/misc/magic\nseccomp support included\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=nvim} \"$@\"", block: true, orphan: false, desc: "\u{e7c5}", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=nvim} \"$@\"", block: true, orphan: false, desc: "\u{e7c5}", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/joebiden/.local/state/yazi" directory.

### Describe the bug

![image](https://github.com/sxyazi/yazi/assets/76881322/1b7ba3b9-fe73-4ba3-ae9d-f5200fcd35b5)

downloaded libheif and still nothing.

### Expected Behavior

thumbnail should show for heif/heic files

### To Reproduce

hover over a heic file and the thumbnail won't show

### Configuration

no config

**Comment by sxyazi** [comment]
I noticed you're not using the latest code of Yazi - HEIC is a new feature added recently in https://github.com/sxyazi/yazi/pull/1050 and currently requires the latest main branch

Closing as already supported
