### ISSUE TITLE
Cyrillic characters are displayed smaller than Latin in file/folder names

### ISSUE THREAD

**Issue by VKondakoff** [sxyazi/yazi#1177]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

iTerm2 3.5.2

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh

Yazi
    Version: 0.2.5 (Homebrew 2024-06-20)
    Debug  : false
    OS     : macos-x86_64 (unix)

Ya
    Version: 0.2.5

Emulator
    Emulator.via_env: ("xterm-256color", "iTerm.app")
    Emulator.via_csi: Ok(Iterm2)
    Emulator.detect : Iterm2

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("kak")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: No such file or directory (os error 2)

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : No such file or directory (os error 2)
    fzf              : 0.53.0
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    unar             : 1.10.7
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/Users/valerykondakoff/.local/state/yazi" directory.


```

</details>

### Describe the bug

I noticed, that Cyrillic characters are displayed much smaller than Latin ones in file/folder names. This does not depends of what font I choose to use in iTerm2 settings. 

### Expected Behavior

All characters should be displayed in the same size independent of layout.

### To Reproduce

Create file named `ТЕСТ TEST тест test.txt`.
Screenshot:
<img width="570" alt="Снимок экрана 2024-06-21 в 00 46 38" src="https://github.com/sxyazi/yazi/assets/230824/6b88116b-2a40-44cb-b9f5-08cd11392afc">

### Configuration

no config

**Comment by sxyazi** [comment]
Yazi as a TUI application, doesn't have control over terminal fonts, and it's up to your terminal to render fonts and how you've configured them. 

You can paste the filename into your shell (without and outside Yazi) to see how your terminal renders it:

![screenshot-000740](https://github.com/sxyazi/yazi/assets/17523360/32bb92b9-00bf-4794-98eb-df7f171d378c)



Closing as not Yazi and nothing to do with Yazi.

**Comment by VKondakoff** [comment]
Ah, yes, sorry for a false alarm: Cyrillic characters were displayed using Nerd font instead of the default one. I fixed the issue by setting an exception for Cyrillic range (U+0400–U+04FF). Now it is displayed correctly.
Thank you!
