### ISSUE TITLE
Strange error "failed to connect to a Wayland server"

### ISSUE THREAD

**Issue by DreamMaoMao** [sxyazi/yazi#118]
https://github.com/sxyazi/yazi/assets/30348075/e4d3aa68-1a85-485a-bd7a-b74882582b78

I use the platform is xorg(dwm), why yazi occur such fail message.

**Comment by DreamMaoMao** [comment]
But there is nothing wrong with the operation, i  don't know why it reported this error, and I am not using wayland

**Comment by DreamMaoMao** [comment]
this error will occur when i use delet commad like(dd cb ce)你 input field.

**Comment by sxyazi** [comment]
What is your terminal, and are you using Überzug++? Please paste the output of `echo $TERM, $TERM_PROGRAM, $XDG_SESSION_TYPE` here.

**Comment by DreamMaoMao** [comment]
![image](https://github.com/sxyazi/yazi/assets/30348075/4fb631c6-ad7f-4b2e-bd72-d96cea004e06)
my terminal is konsole

**Comment by sxyazi** [comment]
Thanks for reporting, https://github.com/sxyazi/yazi/pull/119 should fix the issue, please give it a try.
