### ISSUE TITLE
New Line Delimited JSON cannot be opened/previewed

### ISSUE THREAD

**Issue by xfzv** [sxyazi/yazi#1183]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.34.1

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh

Yazi
    Version: 0.2.5 (505de05 2024-06-22)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: No such file or directory (os error 2)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("tty")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-25
    fzf              : 0.53.0
    fd               : 9.0.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    unar             : No such file or directory (os error 2)
    jq               : 1.7.1
```

</details>

### Describe the bug

Opening/previewing regular `json` files works just fine.
However, I have a `json` file which is actually a "New Line Delimited JSON text data" and this one can neither be opened (pressing "o" / "Enter" does nothing) or previewed (see screenshot). Works fine with `Lf`.

- `test-1.json`

```json
{
  "test": 1,
  "test2": 2
}{
  "test": "test",
  "test2": {
    "test": 1
  }
}
```

```console
% file test-1.json
test-1.json: New Line Delimited JSON text data

% mimetype -bL test-1.json
application/json
```

Manually editing the formatting to turn the file into a regular `json` file solves the issue:

- `test-2.json`

```json
[
  {
    "test": 1,
    "test2": 2
  },
  {
    "test": "test",
    "test2": {
      "test": 1
    }
  }
]
```

```console
% file test-2.json
test-2.json: JSON text data

% mimetype -bL test-2.json
application/json
```

### Expected Behavior

"New Line Delimited JSON text data" files are opened/previewed just fine like regular JSON files.

### To Reproduce

1. Create a `file.json` with the following content:
```json
{
  "test": 1,
  "test2": 2
}{
  "test": "test",
  "test2": {
    "test": 1
  }
}
```
2. Open `yazi` and highlight `file.json`: no preview
3. Press either "o" or "<Enter>" to open the file: nothing happens 

### Configuration

can reproduce without `~/.config/yazi` directory (stock config)

### Anything else?

![yazi-preview](https://github.com/sxyazi/yazi/assets/78810647/18d0f0a6-2e5e-43d6-b80f-8f647b384c4b)

`~/.local/state/yazi/yazi.log` is empty

**Comment by sxyazi** [comment]
> % mimetype -bL test-1.json

What is the `mimetype` program? Is it an alias for `file(1)` (which is used by Yazi)? What does `file -bL test-2.json` output?

**Comment by sxyazi** [comment]
Now what's the output of `file -bL --mime-type test-1.json` and `file -bL --mime-type test-2.json`?

**Comment by sxyazi** [comment]
Thanks for the reporting, should be fixed in https://github.com/sxyazi/yazi/pull/1190, please give it a try (make sure you're using the default Yazi config)
