### ISSUE TITLE
Files not opening on Windows 11 after upgrade (folders open fine)

### ISSUE THREAD

**Issue by CharlyGT3** [sxyazi/yazi#1188]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Windows Terminal and WezTerm

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

Yazi
    Version: 0.2.5 (VERGEN_IDEMPOTENT_OUTPUT 2024-06-23)
    OS: windows-x86_64 (windows)
    Debug: false

Emulator
    Emulator.via_env: ("", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Unknown([])

Adaptor
    Adaptor.matches: Chafa

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: None
    EDITOR: None
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Err(Error { kind: NotFound, message: "program not found" })

Text Opener
    default: Some(Opener { run: "micro \"%1\"", block: true, orphan: false, desc: "Micro", for_: None, spread: false })
    block: Some(Opener { run: "micro \"%1\"", block: true, orphan: false, desc: "Micro", for_: None, spread: false })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Error { kind: NotFound, message: "program not found" })

--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "C:\\Users\\Charly\\AppData\\Roaming\\yazi\\state" directory.

### Describe the bug

Hi,

I am experiencing an issue with Yazi. It was working perfectly on my Windows 10 setup, but after upgrading to Windows 11, I can no longer open files, although folders open without any problems. My configuration is the same as before the upgrade.

Here are the steps I've taken to try and resolve the issue:

Initially, I had Yazi installed using Scoop. I switched to compiling it directly, but the issue persists.
I typically use Yazi with Windows Terminal, but I have also tried using WezTerm, with no difference.
I have tried different configurations and also ran the program in administrator mode.
When I press 'O' on a folder, I can choose how I want to open it, but doing the same on specific files does nothing.
I would appreciate any help or suggestions on how to resolve this issue

### Expected Behavior

be able to open files

### To Reproduce

update windows 11 24h2

**Comment by sxyazi** [comment]
> file(1)
> Version: Err(Error { kind: NotFound, message: "program not found" })

Please ensure that `file(1)` is in your PATH, or set it with `YAZI_FILE_ONE`. For more details, see https://yazi-rs.github.io/docs/installation/#requirements

**Comment by CharlyGT3** [comment]
thank you very much, the problem of not reading the documentation in English well, a Latam thing
