### ISSUE TITLE
Add `wait` flag to `quit` command, to close after the current operations have completed

### ISSUE THREAD

**Issue by thomasschafer** [sxyazi/yazi#1193]
### Please describe the problem you're trying to solve

I'm using Yazi inside of Helix in a Tmux popup, and I've set it up so that the popup sends keys back to the main window to open the selected file(s). I'd like to be able to quit Yazi (and by extension the Tmux popup) with something like this:

```toml
[[manager.prepend_keymap]]
on = ["<Enter>"]
run = ["open", "quit"]
desc = "Open the selected files"
```

This works fine, except that I need to hit `y` in the Yazi menu that says "1 task running, are you sure you want to quit? (y/N)". When I type `y` and press enter, the tmux popup closes as expected and I am returned to Yazi.

It would be great to have a flag (e.g. `--wait`) added to the `quit` command, that exits after the currently in-progress operations have completed.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

A new `--wait` flag so that Yazi quits after the current operations are complete.

**Comment by sxyazi** [comment]
Are you using the latest Yazi code? This should already be set as the default behavior in https://github.com/sxyazi/yazi/pull/997

**Comment by sxyazi** [comment]
See also https://github.com/sxyazi/yazi/issues/1059#issuecomment-2122403165

**Comment by thomasschafer** [comment]
Apologies I indeed wasn't on the latest version, it works great now that I've built from source - thanks so much! 🙌
