### ISSUE TITLE
More options for "open" command

### ISSUE THREAD

**Issue by allpandasarecute** [sxyazi/yazi#1194]
### Please describe the problem you're trying to solve

Now you can only map keybinging to "open" or "open --interactive", which, for me, seems strange

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I think, it would be could, if there was an option to use "`open`" command with specific opener
For example:
```toml
[manager]
prepend_keymap = [
	{ on = [ "o" ], run = 'open', desc = "Open just for view" },
	{ on = [ "e" ], run = 'open --opener edit', desc = "Open for editing" },
]
```

**Comment by sxyazi** [comment]
Why you don't use the `shell` command? https://yazi-rs.github.io/docs/configuration/keymap/#manager.shell

```bash
{ on = [ "e" ], run = '''shell '$EDITOR "$@"' --confirm --block''', desc = "Open for editing" },
```
