### ISSUE TITLE
image not opened when press enter on it 

### ISSUE THREAD

**Issue by woshichuanqilz** [sxyazi/yazi#1201]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.35.1 created by Kovid Goyal

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh

Yazi
    Version: 0.2.5 (Arch Linux 2024-04-27)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Kitty

Adaptor
    Adaptor.matches: X11

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY: None
    DISPLAY: Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/usr/bin/fish")
    EDITOR: Some("nvim")
    ZELLIJ_SESSION_NAME: Some("拼搏与梦想")
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.45\nmagic file from /usr/share/file/misc/magic\nseccomp support included\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "$EDITOR \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "$EDITOR \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/lizhe/.local/state/yazi" directory.

```

### Describe the bug

when I move cursor on `jpg` or `png` file and press <kbd>Enter</kbd>. 

The file not opened. The file association is set. 
```fish
> xdg-mime query default image/png                                  ╯
org.kde.gwenview.desktop

> xdg-mime query default image/jpeg                                ─
org.kde.gwenview.desktop
```
 it works in dolphin. Change program to open not work ( I change gwenview to qimgv). 

# log file
There is a error keep showing in the log file. 
```
  2024-06-24T15:42:56.683806Z ERROR yazi::components::status: runtime error: [string "yazi-plugin/src/lua.rs:50:13"]:2: attempt to index a nil value (field 'hovered')
stack traceback:
	[C]: in metamethod 'index'
	[string "yazi-plugin/src/lua.rs:50:13"]:2: in method 'modified'
	[string "yazi-plugin/src/lua.rs:50:13"]:10: in function <[string "yazi-plugin/src/lua.rs:50:13"]:6>
    at yazi-fm/src/components/status.rs:17
```

[yazi.log](https://github.com/user-attachments/files/15958096/yazi.log)

### Expected Behavior

open the image with corresponding program. 

### To Reproduce

enter yazi press enter on image

**Comment by sxyazi** [comment]
Please fill out the bug report template correctly (bug description, steps to reproduce, etc.), otherwise I'm not sure what action to take.

**Comment by woshichuanqilz** [comment]
> Please fill out the bug report template correctly (bug description, steps to reproduce, etc.), otherwise I'm not sure what action to take.

I post everything I know may related to this issue. 

The reproduce 
1. install yazi 
2. config yazi use the file I posted. 
3. press enter on a jpg/png file on image. 
4. the image file wont open in the corresponding program. 

I don't know what else do you need ?

**Comment by sxyazi** [comment]
What happens when you run `file -bL mime-type /path/to/your-image-file` and `xdg-open /path/to/your-image-file`? Is this issue still with the default Yazi config?

**Comment by woshichuanqilz** [comment]
- `file -bL mime-type /path/to/your-image-file`
```
file -bL mime-type ~/wallpaper/ori/0001.jpg                                                                                               ─╯
cannot open `mime-type' (No such file or directory)
JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, progressive, precision 8, 4592x3448, components 3
```

- `xdg-open /path/to/your-image-file`
works fine.

- change to default config 
I delete the `~/.config/yazi` folder then start yazi, still has the issue.

**Comment by sxyazi** [comment]
Please upload the failed file

**Comment by zaeboba** [comment]
![image](https://github.com/sxyazi/yazi/assets/57330346/f7201240-e4c2-4353-8e4d-194fa96f5610)
 
I also don't have a preview for any file.

https://0x0.st/XAFK.log - log

**Comment by sxyazi** [comment]
@zaeboba Please create a new bug report and fill out the template. I need to know your specific environment information and the steps to reproduce the issue.

**Comment by woshichuanqilz** [comment]
> Please upload the failed file

what failed file? 
The log file with default config to press enter on the image contains nothing. 

![image](https://github.com/sxyazi/yazi/assets/11295355/690bd946-5632-4cd2-ba53-347a4bb847ac)

**Comment by sxyazi** [comment]
> what failed file?

The image file failed to open

**Comment by woshichuanqilz** [comment]
> > what failed file?
> 
> The image file failed to open

The images seems ok. It can be opened in dolphin

![0016](https://github.com/sxyazi/yazi/assets/11295355/af05c837-ebb4-4948-a0c9-04843766237d)
![0017](https://github.com/sxyazi/yazi/assets/11295355/03a55a35-b44c-4dac-9b3c-fcc4c31660bd)
![0018](https://github.com/sxyazi/yazi/assets/11295355/81809b12-b543-488d-bd82-631b943d9aa8)
![Snipaste_2024-06-25_21-37-16](https://github.com/sxyazi/yazi/assets/11295355/de6d3239-f3eb-4508-9fa4-8a832bd59229)

**Comment by sxyazi** [comment]
Weird, I can't reproduce it with your image on my Linux VM


https://github.com/sxyazi/yazi/assets/17523360/63ad092f-1e3a-41a3-96c6-ba1775ab6b88

This is my Yazi version:

```
Yazi 0.2.5 (9a5b756 2024-06-25)
```

The mime-type of this image on my side (`file-5.45`):

```
file -bL --mime-type 342757779-af05c837-ebb4-4948-a0c9-04843766237d.jpg
image/jpeg
```

And I'm using the default config of Yazi

**Comment by woshichuanqilz** [comment]
> Weird, I can't reproduce it with your image on my Linux VM
> 
>  screenshot-000832.mp4 
> This is my Yazi version:
> 
> ```
> Yazi 0.2.5 (9a5b756 2024-06-25)
> ```
> 
> The mime-type of this image on my side (`file-5.45`):
> 
> ```
> file -bL --mime-type 342757779-af05c837-ebb4-4948-a0c9-04843766237d.jpg
> image/jpeg
> ```
> 
> And I'm using the default config of Yazi

I want to add some code in the yazi, compile it with source code and check the log. 
Seems there is no log file currently about what happened when I press enter on image file . 

Can you tell me which part of the code should I read?

**Comment by sxyazi** [comment]
You can try: 

1. Press `O` on the image and see what the first opener is.
2. Copy the command of that opener, run it in the terminal, and see what happens.

**Comment by woshichuanqilz** [comment]
> You can try:
> 
> 1. Press `O` on the image and see what the first opener is.
> 2. Copy the command of that opener, run it in the terminal, and see what happens.

This? Cant see the opener. I use `qimgv` as the default program to open images. It works from command line 
![image](https://github.com/sxyazi/yazi/assets/11295355/1c8876ac-f761-4b11-b02b-995f5319b75b)

**Comment by woshichuanqilz** [comment]
> Curious as to what would happen with a custom `opener` that explicitly uses `qimgv`:
> 
> ```toml
> [opener]
> open-image = [{ run = 'qimgv "$@"', orphan = true, desc = "qimgv" }]
> 
> [open]
> rules = [
>   { mime = "image/*", use = [
>     "open-image",
>     "reveal",
>   ] },
> ]
> ```
> 
> Then use `O` and select `qimgv` in the pop-up menu

Oh it worked with your config. Why is that ?

**Comment by woshichuanqilz** [comment]
> > Oh it worked with your config. Why is that ? I can press enter on the image and the image will be open
> 
> Good question. I don't know why
> 
> ```
> % xdg-open /path/to/file
> ```
> 
> works for you but the same command doesn't when run from `yazi`.
> 
> Can your reproduce the issue with other TUI file managers such as [joshuto](https://github.com/kamiyaa/joshuto) or [lf](https://github.com/gokcehan/lf)? If not, I don't think the issue is with `yazi`.
> 
> Is there any other file type that open fine with Dolphin but won't open from `yazi` or does it only happen with images?
> 
> What is the content of `~/.config/mimeapps.list` (if it exists)?

- I use TUI manager `ranger` it works fine. 
> Is there any other file type that open fine with Dolphin but won't open from yazi or does it only happen with images?

Havent found yet. 

- `~/.config/mimeapps.list`
```
[Added Associations]
application/x-extension-htm=firefox.desktop;
application/x-extension-html=firefox.desktop;
application/x-extension-shtml=firefox.desktop;
application/x-extension-xht=firefox.desktop;
application/x-extension-xhtml=firefox.desktop;
application/xhtml+xml=firefox.desktop;
text/html=google-chrome.desktop;firefox.desktop;
x-scheme-handler/baiduyunguanjia=baidunetdisk.desktop;
x-scheme-handler/chrome=firefox.desktop;
x-scheme-handler/clash=clash_win.desktop;
x-scheme-handler/http=google-chrome.desktop;firefox.desktop;
x-scheme-handler/https=google-chrome.desktop;firefox.desktop;
x-scheme-handler/jetbrains=jetbrains-toolbox.desktop;
x-scheme-handler/x-github-client=github-desktop.desktop;GitHub Desktop.desktop;
x-scheme-handler/x-github-desktop-auth=github-desktop.desktop;GitHub Desktop.desktop;
x-scheme-handler/mailto=google-chrome.desktop
text.html=google-chrome.desktop
image/png=qimgv.desktop
image/jpeg=qimgv.desktop

[Default Applications]
application/x-extension-htm=firefox.desktop
application/x-extension-html=firefox.desktop
application/x-extension-shtml=firefox.desktop
application/x-extension-xht=firefox.desktop
application/x-extension-xhtml=firefox.desktop
application/xhtml+xml=firefox.desktop
text/html=google-chrome.desktop
x-scheme-handler/baiduyunguanjia=baidunetdisk.desktop
x-scheme-handler/chrome=firefox.desktop
x-scheme-handler/clash=clash_win.desktop
x-scheme-handler/http=google-chrome.desktop;
x-scheme-handler/https=google-chrome.desktop;
x-scheme-handler/jetbrains=jetbrains-toolbox.desktop
x-scheme-handler/x-github-client=github-desktop.desktop
x-scheme-handler/x-github-desktop-auth=github-desktop.desktop
x-scheme-handler/mailto=google-chrome.desktop
text.html=google-chrome.desktop
image/png=qimgv.desktop
image/jpeg=qimgv.desktop

```

**Comment by sxyazi** [comment]
If you use the config from @xfzv but just change `qimgv` to `xdg-open` what will happen? And what will happen if you run `xdg-open` on the image using the built-in shell by clicking `;` or `:`?

**Comment by woshichuanqilz** [comment]
> If you use the config from @xfzv but just change `qimgv` to `xdg-open` what will happen? 
works. 
> And what will happen if you run `xdg-open` on the image using the built-in shell by clicking `;` or `:`?
works too.

**Comment by sxyazi** [comment]
> Version: 0.2.5 (Arch Linux 2024-04-27)

Are you sure you're using the latest code?

**Comment by woshichuanqilz** [comment]
> > Version: 0.2.5 (Arch Linux 2024-04-27)
> 
> Are you sure you're using the latest code?

![image](https://github.com/sxyazi/yazi/assets/11295355/35b83774-95c2-401e-b55f-17a14d43a293)

**Comment by sxyazi** [comment]
Why is your build date 2024-04-27?

**Comment by woshichuanqilz** [comment]
> Why is your build date 2024-04-27?

I download from aur. I just download the yazi from the release build date 4-23. Same issue

**Comment by sxyazi** [comment]
What does yazi -V output?

**Comment by woshichuanqilz** [comment]
> What does yazi -V output?
What is the differences with --version ?
```
╰─❯ yazi --version                                                  ─╯
Yazi 0.2.5 (c65a14c 2024-04-23)

╭─ ~/Applications                                                 ─╮
╰─❯ yazi -V                                                         ─╯
Yazi 0.2.5 (c65a14c 2024-04-23)
```

**Comment by sxyazi** [comment]
> > What does yazi -V output?
> 
> What is the differences with --version ?
> 
> ```
> ╰─❯ yazi --version                                                  ─╯
> Yazi 0.2.5 (c65a14c 2024-04-23)
> 
> ╭─ ~/Applications                                                 ─╮
> ╰─❯ yazi -V                                                         ─╯
> Yazi 0.2.5 (c65a14c 2024-04-23)
> ```

No, this is not the latest code, please verify if this problem exists in the latest code

**Comment by woshichuanqilz** [comment]
> > > What does yazi -V output?
> > 
> > 
> > What is the differences with --version ?
> > ```
> > ╰─❯ yazi --version                                                  ─╯
> > Yazi 0.2.5 (c65a14c 2024-04-23)
> > 
> > ╭─ ~/Applications                                                 ─╮
> > ╰─❯ yazi -V                                                         ─╯
> > Yazi 0.2.5 (c65a14c 2024-04-23)
> > ```
> 
> No, this is not the latest code, please verify if this problem exists in the latest code

use the latest version. Same issue 

 yazi -V                                                                                                                                   ─╯
Yazi 0.2.5 (c64530b 2024-06-26)

**Comment by woshichuanqilz** [comment]
> @woshichuanqilz `-V` and `--version` is the same (short/long):
> 
> ```
> % yazi --help
>   -V, --version                        Print version
> ```
> 
> What if you replace
> 
> ```toml
> open = [
>   { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
> ```
> 
> with
> 
> ```toml
> open = [
>   { run = 'xdg-open "$@"', orphan = true, desc = "Open" },
> ```
> 
> ?

Still work

**Comment by sxyazi** [comment]
In that case, I think we can simply add `orphan = true` to the default `xdg-open` opener rule to fix it. I don't know why, but it works.

**Comment by sxyazi** [comment]
I tried again and still couldn't reproduce the issue. I'm not sure if adding `orphan = true` to the default config is reasonable, so I've decided not to add it atm - I'll see if anyone else reports the same problem. 

For now, please override the default image opener in your `yazi.toml` as a workaround.
