### ISSUE TITLE
Feat Request: Path Bookmarks 

### ISSUE THREAD

**Issue by GianniBYoung** [sxyazi/yazi#1203]
### Please describe the problem you're trying to solve

hello, I would like to see a way to track personal bookmarks for paths similar to ranger. 

I see that there are a few 'built in' ones accessible by using `gd`, `gh`, and `gt` to take you to standard locations. 

### Describe the solution you'd like

I would like to see this expanded to include personal 'bookmarks' without the requirement of modifying the keymaps file.

 I would like to see a keymap that can add the current dir as a book mark and a way to remove 'bookmarks'

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/bookmarks-persistence.yazi

are you mean this?


also there are other choice in here: [](https://yazi-rs.github.io/docs/resources)
![image](https://github.com/sxyazi/yazi/assets/30348075/33cafd7d-fa59-4964-af32-65aaf0e3b6ad)

**Comment by sxyazi** [comment]
closing as already exists
