### ISSUE TITLE
can not install with cargo

### ISSUE THREAD

**Issue by cndeng** [sxyazi/yazi#1207]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

windterm

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
$ cargo install --locked yazi-fm yazi-cli
    Updating `tuna` index
  Installing yazi-fm v0.2.5
  Installing yazi-cli v0.2.5
error: failed to select a version for `mlua`.
    ... required by package `yazi-plugin v0.2.5`
    ... which satisfies dependency `yazi-plugin = "^0.2.5"` (locked to 0.2.5) of package `yazi-core v0.2.5`
    ... which satisfies dependency `yazi-core = "^0.2.5"` (locked to 0.2.5) of package `yazi-fm v0.2.5`
versions that meet the requirements `^0.9.7` (locked to 0.9.7) are: 0.9.7

the package `yazi-plugin` depends on `mlua`, with features: `mlua_derive` but `mlua` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.


failed to select a version for `mlua` which could resolve this conflict
error: failed to compile `yazi-cli v0.2.5`, intermediate artifacts can be found at `/tmp/cargo-installLpzkWN`

Caused by:
  package `clap_complete v4.5.2` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.63.0
     Summary Failed to install yazi-fm, yazi-cli (see error(s) above).
error: some crates failed to install
```

</details>

### Describe the bug

failed to select a version for `mlua`

### Expected Behavior

is mlua version correct ?

### To Reproduce

$ cargo install --locked yazi-fm yazi-cli
    Updating `tuna` index
  Installing yazi-fm v0.2.5
  Installing yazi-cli v0.2.5
error: failed to select a version for `mlua`.
    ... required by package `yazi-plugin v0.2.5`
    ... which satisfies dependency `yazi-plugin = "^0.2.5"` (locked to 0.2.5) of package `yazi-core v0.2.5`
    ... which satisfies dependency `yazi-core = "^0.2.5"` (locked to 0.2.5) of package `yazi-fm v0.2.5`
versions that meet the requirements `^0.9.7` (locked to 0.9.7) are: 0.9.7

the package `yazi-plugin` depends on `mlua`, with features: `mlua_derive` but `mlua` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.

failed to select a version for `mlua` which could resolve this conflict
error: failed to compile `yazi-cli v0.2.5`, intermediate artifacts can be found at `/tmp/cargo-installLpzkWN`

Caused by:
  package `clap_complete v4.5.2` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.63.0
     Summary Failed to install yazi-fm, yazi-cli (see error(s) above).
error: some crates failed to install

**Comment by sxyazi** [comment]
> Caused by:
> package clap_complete v4.5.2 cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.63.0

I believe the error report clearly explains the issue - Yazi needs the latest stable version of the Rust toolchain. You need to follow the instructions at https://yazi-rs.github.io/docs/installation#cargo to upgrade your Rust.
