### ISSUE TITLE
`yazi` is "eating" the `fn` key (treating `fn+key` combinations as a plain `key` combination

### ISSUE THREAD

**Issue by VKondakoff** [sxyazi/yazi#1212]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

iTerm2

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh

Yazi
    Version: 0.2.5 (Homebrew 2024-06-22)
    Debug  : false
    OS     : macos-x86_64 (unix)

Ya
    Version: 0.2.5

Emulator
    Emulator.via_env: ("xterm-256color", "iTerm.app")
    Emulator.via_csi: Ok(Iterm2)
    Emulator.detect : Iterm2

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("kak -c vk")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: No such file or directory (os error 2)

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : No such file or directory (os error 2)
    fzf              : 0.53.0
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    unar             : 1.10.7
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/Users/valerykondakoff/.local/state/yazi" directory.


```

</details>

### Describe the bug

I can not use `fn-key' combinations when yazi is launched, because yazi thinks `fn-key` is just a plain `key`.

### Expected Behavior

`fn` is a modifier key similar to `ctrl` and `shift`. So, the `fn-f` hotkey differs from just `f`.

### To Reproduce

`Fn-f` is a default hotkey to launch window fullscreen on macOS:

<img width="704" alt="Снимок экрана 2024-06-25 в 16 00 16" src="https://github.com/sxyazi/yazi/assets/230824/c9dea180-e90e-4b81-b05e-c3830a34b4b7">

When there is no yazi launched I can press `fn-f` to make iTerm2 window fullscreen. If there is yazi loaded the `fn-f` hotkey is treated as the plain `f`:

<img width="704" alt="Снимок экрана 2024-06-25 в 16 00 26" src="https://github.com/sxyazi/yazi/assets/230824/77570d83-e30a-40e5-ba4e-19093bae21bd">

**Comment by sxyazi** [comment]
> `fn` is a modifier key similar to `ctrl` and `shift`. So, the `fn-f` hotkey differs from just `f`.

No, as far as I know, no terminal supports sending the `Fn` key as a modifier to CLI/TUI programs because the `Fn` key is not included in the keyboard protocol.

Closing as nothing Yazi can do
