### ISSUE TITLE
Change drive letter on windows

### ISSUE THREAD

**Issue by lxl66566** [sxyazi/yazi#1215]
### Please describe the problem you're trying to solve

yazi couldn't change drive letter on windows now, neither type `h` on disk root dir nor type `:` and exec `cd /d D:\` command

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

since disk root dir has no `parent`, it may need a manual additional page to show disk letters and switch between them.using [GetLogicalDrives](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getlogicaldrives) api to show all disk letters?
or design a command to switch disk?

**Comment by sxyazi** [comment]
You can either:

- Click `g<Space>` to open the interactive `cd`, then type `D:\` to navigate
- Bind a key to navigate like this:
  ```
  { on = [ "g", "d" ], run = "cd 'D:\\'" }
  ```

With the nightly build, you can use `D:` instead of `D:\` / `D:\\` for convenience. Closing as already supported.

**Comment by lxl66566** [comment]
My fault. thank you!
