### ISSUE TITLE
Detach tasks user launched tasks

### ISSUE THREAD

**Issue by Lcchy** [sxyazi/yazi#1218]
### Please describe the problem you're trying to solve

Hi, thanks a lot for the amazing file manager, I use it every day.

When using yazi, I often open a file, e.g. an image in an image viewer, and then want to quit yazi.

When quitting, yazi prompts me to confirm as there is a task running, I would like to not have this prompt.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

I understand the necessity of the prompt for data sensitive operations like cp, mv etc.

Would it be possible to detach all user started tasks from the terminal (e.g. `nohup`) in order to be able to close yazi without a prompt ? The processes could still be tracked/managed in the task view.

If this is not something desirable by default, would there be a way to modify the task spawning in the configuration ? Or could it be done with a plugin ?

**Comment by sxyazi** [comment]
Set [`orphan = true`](https://yazi-rs.github.io/docs/configuration/yazi#opener) for your opener rule:

> `orphan`: Keep the process running even if Yazi has exited, once specified, the process will be detached from the task scheduling system.

BTW, the `shell` command also has a [`--orphan` option](https://yazi-rs.github.io/docs/configuration/keymap#manager.shell) available.

Closing as already supported

**Comment by Lcchy** [comment]
Oh I see! Thanks a lot!

Sorry for the noise, I thought I looked at all the docs but I missed this.
