### ISSUE TITLE
How to bulk_rename in windows?

### ISSUE THREAD

**Issue by soluty** [sxyazi/yazi#122]
great job! 
i read source and know rename command can do bulk_rename, and config is opener in yazi.toml, but how to pass args in exec command?
in windows , config like this is useless.  and i have no idea on how to bulk rename . please help me 
```
[opener]
text = [
	{ exec = 'nvim "$@"', block = true },   // useless
       { exec = 'nvim "%*"', block = true },    // useless
]
```

**Comment by sxyazi** [comment]
Is `nvim` already in your `PATH` and can it be executed directly in the cmd? It seems that Windows doesn't require adding quotes. Please try:

```toml
{ exec = 'nvim %*', block = true },
```

**Comment by soluty** [comment]
> Is `nvim` already in your `PATH` and can it be executed directly in the cmd? It seems that Windows doesn't require adding quotes. Please try:
> 
> ```toml
> { exec = 'nvim %*', block = true },
> ```

i tryed and it can not work.

**Comment by soluty** [comment]
another problem is $EDITOR can use in cmd, i tryed %EDITOR% that is cmd version , it also can not work now. 
thats why i change it into nvim , but how to pass args, i dont know.

**Comment by sxyazi** [comment]
```toml
{ exec = 'nvim', block = true },
```

Just use `nvim` instead of it, after testing it works. Windows seems only `%*` can be used in a `.bat` file.


https://github.com/sxyazi/yazi/assets/17523360/be535cce-89eb-45c7-b536-01cc655f78fb

**Comment by sxyazi** [comment]
As the config mentioned above is working, I will now close this issue. If you have any other questions please reply within this issue, and I will reopen it.
