### ISSUE TITLE
Support image preview in Alacritty?

### ISSUE THREAD

**Issue by leoliu0** [sxyazi/yazi#1223]
### Please describe the problem you're trying to solve

Do you mind adding Alacritty for the image preview?

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Work out of box for alacritty users.

**Comment by sxyazi** [comment]
Alacritty doesn't support any image protocols, there's an unmerged PR here you might be interested in https://github.com/alacritty/alacritty/pull/4763

Closing as not something Yazi can do, needs Alacritty to support some image protocol.
