### ISSUE TITLE
Default theme contrast is bad with a dark background

### ISSUE THREAD

**Issue by bellini666** [sxyazi/yazi#1225]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

iterm2 3.5.3beta2

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.5 (Homebrew 2024-04-23)
    OS: macos-aarch64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "iTerm.app")
    Emulator.via_csi: Ok(Iterm2)
    Emulator.detect: Iterm2

Adaptor
    Adaptor.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/bin/zsh")
    EDITOR: Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.41\nmagic file from /usr/share/file/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

</details>

### Describe the bug

I just installed yazi with `brew install yazi`, and when opening it I noticed that the default color contrast is bad with an almost black background, making text very hard to read.

You can see an example in here of what it looks like to me

![Screenshot 2024-06-27 at 11 33 13](https://github.com/sxyazi/yazi/assets/134025/d606887e-25a0-4ebb-b769-703d44b4754a)

### Expected Behavior

The default theme to have better color contrast

### To Reproduce

Just open yazi on a terminal with `#191919` (which is a common black pattern used by a lot of dark themes)

### Anything else?

Yazi looks awesome, looking forward to start using it more :)

**Comment by sxyazi** [comment]
Hi, I have explained it in the FAQ here: https://yazi-rs.github.io/docs/faq#why-text-indistinct.

If you find a color that better covers most terminals, feel free to raise a PR :)
