### ISSUE TITLE
Add the `--hovered` option for the `rename` and `remove` command

### ISSUE THREAD

**Issue by hankertrix** [sxyazi/yazi#1226]
### Please describe the problem you're trying to solve

With cross-directory selection, I often forget that I still have items selected before running the `rename` and `remove` commands, which can end in disaster, especially for the `remove` command.

### Would you be willing to contribute this feature?

- [x] Yes, I'll give it a shot

### Describe the solution you'd like

The `--hovered` option to be added for both the `rename` and `remove` commands, similar to the `open` command.

### Additional context

Forgetting to unselect files:

![image](https://github.com/sxyazi/yazi/assets/91734413/58ec920d-0427-4583-b5bf-268c11d468c5)

Expecting to delete the currently hovered file:

![image](https://github.com/sxyazi/yazi/assets/91734413/e061b237-5ccb-496c-8f05-64add1480903)

Accidentally delete the files that were selected in another directory:

![image](https://github.com/sxyazi/yazi/assets/91734413/ea350ea5-8781-4ee1-9d5e-f0f57dfa982a)
![image](https://github.com/sxyazi/yazi/assets/91734413/e0fb80e9-4255-4cf0-8ef2-ca17ffb7969c)

**Comment by sxyazi** [comment]
Try:

```sh
{ on = [ "h" ], run = [ "leave", "escape --select" ] },
{ on = [ "l" ], run = [ "enter", , "escape --select" ] },
```

Doc of `escape` command: https://yazi-rs.github.io/docs/configuration/keymap#manager.escape

**Comment by hankertrix** [comment]
Thank you for the blazingly fast response!

However, this wouldn't really work for my use case as I would like to be able to use cross-directory selection, but not shoot myself in the foot when I forget to deselect after selecting in another directory when I use the `rename` and `remove` commands.

Ideally, I would like to create a plugin that will only run the `remove` and `rename` commands on the selected files only when the currently hovered file is selected, like the plugin in [this issue](https://github.com/sxyazi/yazi/issues/807#issuecomment-1994973336) for the `open` command.

**Comment by sxyazi** [comment]
> Ideally, I would like to create a plugin that will only run the remove and rename commands on the selected files only when the currently hovered file is selected, like the plugin in https://github.com/sxyazi/yazi/issues/807#issuecomment-1994973336 for the open command

It's possible. Basically, you just need to bind your `remove` and `rename` keys to your custom plugin. You can implement both in the same plugin; just differentiate them with parameters:

```sh
{ on = [ "d" ], run = [ "plugin --sync your-plugin --args=remove" ] },
{ on = [ "r" ], run = [ "plugin --sync your-plugin --args=rename" ] },
```

Then, in your plugin, when the conditions are met, use `ya.manager_emit()` to emit them.

Doc of `ya.manager_emit()`: https://yazi-rs.github.io/docs/plugins/utils/#ya.manager_emit

**Comment by hankertrix** [comment]
I see, that's helpful.

The issue is that the `remove` and `rename` commands don't have the option to operate only on the hovered file like the `open` command does. Emitting the `rename` or `remove` commands will end up operating on all of the selected files instead of just the hovered file.

**Comment by mskvsk** [comment]
I had this issue I as well.

I like how it is solved in nnn. If you have some selection and try to do rename/open/delete on a file _outside_ of the selection the file manager specifically asks what should be the object of the operation, the hover or the selection.

**Comment by hankertrix** [comment]
> I like how it is solved in nnn.

Do you have a screenshot or maybe a video of the prompt?

**Comment by hankertrix** [comment]
@mskvsk I implemented the prompt in my plugin, but you have to be on the latest Git version of Yazi for the prompt to work on the `remove` and `rename` commands.

Check it out here:
https://github.com/hankertrix/augment-command.yazi
