### ISSUE TITLE
Is it possible to make copy / move tasks sequential sometimes?

### ISSUE THREAD

**Issue by ShawnMcCool** [sxyazi/yazi#1231]
### Please describe the problem you're trying to solve

When I'm transferring over a slow USB connection, having a bunch of concurrent copies slows down all operations.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I'd like to be able to ask yazi to process these operations sequentially while doing this kind of work.

**Comment by sxyazi** [comment]
Hey, it's possible. 

In Yazi, copying and cutting are considered macro tasks. You can adjust them using [`macro_workers`](https://yazi-rs.github.io/docs/configuration/yazi/#tasks.macro_workers) - you might need to gradually lower this value to find a suitable balance. 

For more information on micro tasks and macro tasks, see: https://yazi-rs.github.io/blog#async-task-scheduling

Closing as already supported.

**Comment by ShawnMcCool** [comment]
Thank you for the resource. I'm looking forward to continuing to learn and use Yazi. =)
