### ISSUE TITLE
Any way to call shell scripts through yazi keymap.toml?

### ISSUE THREAD

**Issue by SafriXV** [sxyazi/yazi#1233]
### Please describe the problem you're trying to solve

I want to integrate yazi as a pywal theme switcher, is there any way to call shell scripts from keymap.toml? ["open", "shell '/path/to/script' --confirm"] doesn't seem to work for me.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

A way to call and execute shell scripts from keymap.toml or yazi.toml.

**Comment by sxyazi** [comment]
It should work, maybe you can try:

```
run = "shell 'bash /path/to/script' --confirm"
```

**Comment by SafriXV** [comment]
Works perfectly, thank you.
