### ISSUE TITLE
Add man page for yazi

### ISSUE THREAD

**Issue by SamIsTheFBI** [sxyazi/yazi#1235]
### Please describe the problem you're trying to solve

I am a heavy user of man pages and I recently noticed that yazi does not have it. Also `yazi --help` doesn't provide as much help. So, I'd like to contribute to prepare man page that will list out quick reference to all the preset commands, configuration files and more.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

I'd like to make the man page with troff syntax. I can make use of docs already present in the website for the content. 

### Additional context

I have made one locally and will write the rest soon.

|![image](https://github.com/sxyazi/yazi/assets/70562711/2ce4596b-e966-4109-8f91-c1f4d0b5a69f)|
|--|
| a little preview |

**Comment by sxyazi** [comment]
Awesome work, thank you!

**Comment by SamIsTheFBI** [comment]
Glad you like it so far! I'll work on the rest of the man page now. Can you please guide me where to put it in the repository?

**Comment by sxyazi** [comment]
Hi, I created a new repo for it: https://github.com/yazi-rs/manpages

**Comment by sxyazi** [comment]
Moved to https://github.com/yazi-rs/manpages/issues/1, closing in favor of that
