### ISSUE TITLE
docx preview

### ISSUE THREAD

**Issue by jaennil** [sxyazi/yazi#1239]
### Please describe the problem you're trying to solve

it will be nice to how a preview of docx files

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

maybe just a text, without formatting

**Comment by sxyazi** [comment]
You can achieve this by using a custom previewer - call LibreOffice to convert DOCX files into image previews. Just like what [pdf.lua](https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/plugins/pdf.lua) does, you can refer to its code and replace the `pdftoppm` command and parameters with the corresponding LibreOffice command.

Previewer doc: https://yazi-rs.github.io/docs/plugins/overview#previewer and https://yazi-rs.github.io/docs/configuration/yazi#plugin.previewers
