### ISSUE TITLE
Improve the TSV preview

### ISSUE THREAD

**Issue by GrimPixel** [sxyazi/yazi#1243]
### Please describe the problem you're trying to solve

For the preview of TSV files, fields are still split by commas and a field can be rendered with different colours.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Keep Tab as the only field separator for “tsv”, “tab” files.

**Comment by sxyazi** [comment]
You can achieve this by using a custom previewer - call [Miller](https://github.com/johnkerl/miller) to preview TSV files. Just like what [miller.yazi](https://github.com/Reledia/miller.yazi) does, you can refer to its code and replace parameters within it with the corresponding TSV parameters.

Previewer doc: https://yazi-rs.github.io/docs/plugins/overview#previewer and https://yazi-rs.github.io/docs/configuration/yazi#plugin.previewers
