### ISSUE TITLE
Folder contents no longer displaying

### ISSUE THREAD

**Issue by bertradio** [sxyazi/yazi#1244]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.35.2

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh

```

</details>
Yazi
    Version: 0.2.5 (VERGEN_IDEMPOTENT_OUTPUT 2024-07-01)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect: Kitty

Adaptor
    Adaptor.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY: None
    DISPLAY: Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/bin/bash")
    EDITOR: Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.41\nmagic file from /etc/magic:/usr/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })
    block: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

### Describe the bug

With latest version the contents of directories no longer display. The same version with the same config on my laptop runing Debian 12 behaves properly.

### Expected Behavior

When focused on a directory the files in the directory should display in the pane to the right

### To Reproduce

HIghlight a directory in yazi

**Comment by bertradio** [comment]
Also see this repeated error in yazi.log:

  2024-07-01T19:26:48.284843Z ERROR yazi_plugin::isolate::peek: runtime error: [string "/home/bert/.cargo/registry/src/index.crates.i..."]:56: attempt to index a nil value (local 'child')
stack traceback:
	[string "/home/bert/.cargo/registry/src/index.crates.i..."]:56: in function <[string "/home/bert/.cargo/registry/src/index.crates.i..."]:28>
    at /home/bert/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yazi-plugin-0.2.5/src/isolate/peek.rs:50

**Comment by sxyazi** [comment]
Is it still without any config? If not please upload your ~/.config/yazi

**Comment by bertradio** [comment]
Just tried with no config and the problem is not there. So it must be somewhere in my config. The strange thing is that I have the identical config on my laptop and the problem is not there.

Attached is my config.

**Comment by sxyazi** [comment]
I can't see any attached config

**Comment by bertradio** [comment]
I found the problem. It was in my yazi.toml, not yazi itself. Thanks for the reply. All is well now.

**Comment by sxyazi** [comment]
Alright lets close this issue then

**Comment by bertradio** [comment]
Thanks. Sorry for the bother. It was my problem. I was away for 2 months. I did a lot of modifications with yazi. I had added the eza plugin. When I copied everything to my desktop I forgot to install eza. So yazi was calling a non-existent program. When I installed eza on my desktop everything worked as it should.

Really appreciate your work on yazi. It's the BEST>
