### ISSUE TITLE
Ability to copy file data

### ISSUE THREAD

**Issue by yorunoken** [sxyazi/yazi#1246]
### Please describe the problem you're trying to solve

I was very saddened when I realized I couldn't copy file data.
you can only copy the path and the path of other stuff related to it, not the actual data (which is the most important one imo)

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

add one more option to the option tree shown when someone presses "c"

### Additional context

could look something like this
![image png](https://github.com/sxyazi/yazi/assets/69751661/b430afec-7d51-45f6-a367-1f7b60f17ab5)
keybind should be C because I feel like this is the more important one, of course you can change it if you want.

**Comment by eljamm** [comment]
If I'm not misunderstanding, you can already do this using [yank](https://github.com/sxyazi/yazi/blob/987b1d5c49f5d11ab9e6a9cdea21974b440ae463/yazi-config/preset/keymap.toml#L66C59-L66C91) by pressing `y` to copy the file and `p` to paste it, which you can remap to another key combination in your [keymap.toml](https://yazi-rs.github.io/docs/configuration/keymap/):

```toml
[[manager.prepend_keymap]]
on  = [ "c", "g" ]
run = "yank"
desc = "Copy the selected files"
```

If you'd like to also copy the file content to the clipboard, you can follow the [Copy selected files to the system clipboard while yanking](https://yazi-rs.github.io/docs/tips#selected-files-to-clipboard) tip and [Smart paste](https://yazi-rs.github.io/docs/tips#smart-paste) to paste files without entering the directory.

**Comment by yorunoken** [comment]
that worked, thank you a lot!

**Comment by Brixy** [comment]
Maybe it makes sense to extend the default `keymap.toml` in case `yank` as vim slang is not known: `cy` or `cs` (or the currently used `cc`) for "copy selection" and ch for "copy hovered".

This would play well together with #1227.

(I am happy to open a new issue for this if a closed issue is not a good place for this comment.)
