### ISSUE TITLE
Add alternative keybindings for people coming from a GUI file manager

### ISSUE THREAD

**Issue by Brixy** [sxyazi/yazi#1250]
### Please describe the problem you're trying to solve

For vimmers yazi's keybindings are extremely intuitive; but if you come from a GUI onboarding is more difficult.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

That's why I would like to suggest to add these keybindings to the default keybindings.toml file. Of course, everything is a bit more redundant this way.

- `Ctrl + c`: yank/copy (currently used)
- `Ctrl + x`: yank --cut
- `Ctrl + v`: paste

Together with arrow keys, `<Space>`, `<Enter>`, `d` and maybe `r` it's maybe all people will ever need.

Maybe, it is even possible to add

- `<Del>`: remove/delete

According to #1246 I would also suggest

`cy`/`cs`/`cc`: yank
`ch`: yank --hovered (I think this is not possible at the moment)

**Comment by sxyazi** [comment]
Sorry, but I think this is a bit redundant and would take up more key space, I'd rather reserve more keys for plugins to use, at least to avoid conflicts with Yazi's own keys.

Also I don't think mixing multiple key schemes together is a good idea. If enough people need it, perhaps creating it as a separate configuration template and redesigning it would be better, like `keymap_gui.toml`. Users familiar with GUI keys could then choose to copy it to `~/.config/yazi` and use it.
