### ISSUE TITLE
Command for creating hard links

### ISSUE THREAD

**Issue by Ape** [sxyazi/yazi#1258]
### Please describe the problem you're trying to solve

I'd like to have a keymappable command for creating a hard link of the yanked file. In case of multiple files or directories, I'd like it to create the directories and hard links for all of them in a tree structure.

### Would you be willing to contribute this feature?

- [x] Yes, I'll give it a shot

### Describe the solution you'd like

`hardlink` command would be similar to `link`.

**Comment by sxyazi** [comment]
Nice to have, maybe we can add a `--hard` to the existing `link` command, i.e. `link --hard`.

Anyone want to give it a go? We need to add the `hard` argument to the `link` command here:

https://github.com/sxyazi/yazi/blob/11547eefe0346006a1a82455577784a34d67c9b7/yazi-core/src/manager/commands/link.rs#L5-L8

And this should be the only place we need to change in the scheduler:

https://github.com/sxyazi/yazi/blob/11547eefe0346006a1a82455577784a34d67c9b7/yazi-scheduler/src/file/file.rs#L84-L95

**Comment by Ape** [comment]
I have a work-in-progress patch here: https://github.com/sxyazi/yazi/pull/1268

I still want to add support for directories.

**Comment by Ape** [comment]
The pull request is now ready for review.

I also added an optional second commit for adjusting the default keymap. This is how I would configure the keys, but I understand that my opinion might differ from other people.

**Comment by sxyazi** [comment]
Done in https://github.com/sxyazi/yazi/pull/1268
