### ISSUE TITLE
In tmux on Windows with MinGW acting weird

### ISSUE THREAD

**Issue by hjm7** [sxyazi/yazi#1260]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

mintty 3.7.3

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.5 (11547ee 2024-07-05)
    Debug  : true
    OS     : windows-x86_64 (windows)

Ya
    Version: 0.2.5

Emulator
    Emulator.via_env: ("xterm-256color", "mintty")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Mintty

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("D:\\msys64\\usr\\bin\\bash.exe")
    EDITOR             : None
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "code %*", block: false, orphan: true, desc: "code", for_: None, spread: true })
    block  : Some(Opener { run: "code -w %*", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })

tmux
    TMUX   : false
    Version: 3.4

Dependencies
    file             : 5.45
    ueberzugpp       : program not found
    ffmpegthumbnailer: program not found
    magick           : program not found
    fzf              : program not found
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : program not found
    zoxide           : 0.9.4
    unar             : program not found
    jq               : program not found

```

</details>

### Describe the bug

ditto

### Expected Behavior

Can start

### To Reproduce

1. Run  `pacman -S mingw-w64-clang-x86_64-yazi` at mintty in msys2-x86_64-20240507.
2. Run `pacman -Ss yazi` get output: `clang64/mingw-w64-clang-x86_64-yazi 0.2.5-1 [installed]`
3. Run `yazi` get output: `Segmentation fault`

### Configuration

no config

**Comment by sxyazi** [comment]
This may be a mingw specific issue, but I'm not sure since I've never tested yazi in mingw

There is a possible similar issue, https://github.com/sxyazi/yazi/issues/979, please read through it and try https://github.com/sxyazi/yazi/issues/979#issuecomment-2085038156 to see what happens

**Comment by hjm7** [comment]
> This may be a mingw specific issue, but I'm not sure since I've never tested yazi in mingw这可能是 mingw 特定的问题，但我不确定，因为我从未在 mingw 中测试过 yazi
> 
> There is a possible similar issue, #979, please read through it and try [#979 (comment)](https://github.com/sxyazi/yazi/issues/979#issuecomment-2085038156) to see what happens可能存在类似问题 #979 ，请仔细阅读并尝试 [#979 (comment)](https://github.com/sxyazi/yazi/issues/979#issuecomment-2085038156) 看看会发生什么

I corss compile to build a x86_64-pc-windows-gnullvm yazi  by rustup x86_64-pc-windows-gnu toolchain. It works in msys2 clang64 shell. 
But it seem like don't work well in tmux, need keystroke 'j' or 'k' trigger cursor move up or down to display ui, what should I do?

**Comment by hjm7** [comment]
`yazi --debug` output have been editd.
[yazi.log](https://github.com/user-attachments/files/16114623/yazi.log)
[yazi-tmux.log](https://github.com/user-attachments/files/16114624/yazi-tmux.log)

**Comment by sxyazi** [comment]
So after rebuilding, did the 'Segmentation fault' disappear right? Now the issue is not being able to use it in tmux on mingw, but it works fine directly on mingw right?

**Comment by sxyazi** [comment]
Can you provide more information please? How does it fail to work in tmux? What exactly happens? It would be even better if there's a video.

**Comment by hjm7** [comment]
> Can you provide more information please? How does it fail to work in tmux? What exactly happens? It would be even better if there's a video.



> So after rebuilding, did the 'Segmentation fault' disappear right? Now the issue is not being able to use it in tmux on mingw, but it works fine directly on mingw right?

Yes, I capture a screen video by xbox game bar,  but I can't compress to smaller than 10mb.

**Comment by sxyazi** [comment]
Looks like a rendering issue with your terminal or tmux. Have you tried starting your terminal and tmux with the default configurations?

**Comment by hjm7** [comment]
> Looks like a rendering issue with your terminal or tmux. Have you tried starting your terminal and tmux with the default configurations?看起来像是您的终端或 tmux 的渲染问题。您是否尝试过使用默认配置启动终端和 tmux？

I remove my tmux config and terminal is the built-in mintty of msys2 which is default config. Tried it still work as the same way.

**Comment by sxyazi** [comment]
In that case I think this means Yazi can't work on MinGW, or at least can't work fully on MinGW. I'm not familiar with the MinGW platform and not sure why `tmux` would be a decisive factor here.

I did a quick search and found this issue: https://github.com/crossterm-rs/crossterm/issues/580. It seems that the `crossterm` library used by Yazi also doesn't fully support MinGW, which could be causing the rendering issues.

I'll keep this issue open for a while to see if any Windows users familiar with MinGW want to investigate it further.

**Comment by hjm7** [comment]
I‘ve given up tmux in msys2，by replace 'mintty' with 'wezterm' terminal to get its multiplexing feature. Because of its multiplexer is target crossplatform first and no historical burden, so it works well . Besides that, I can get almost the same tmux keybinding because of Lua's flexible config.
