### ISSUE TITLE
Preview for Jupyter notebooks

### ISSUE THREAD

**Issue by AnirudhG07** [sxyazi/yazi#1267]
### Please describe the problem you're trying to solve

I would like an inbuilt feature where Jupyter notebooks *.ipynb have good previews. Cause it is something which is hard to read without proper formatting. This will also give yazi a nice inbuilt feature too.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

There is a tool called nbpreview. It displays good previews for Jupyter notebooks. For yazi, we can support atleast these 3 flags which are `--nerd-font`, `--no-files`, `--no-paging`. Of course, more can be added. Plus nbpreview has a "width" flag which can adjust the length in which the text is added. So we can like give it the width of preview. 
<img width="859" alt="image" src="https://github.com/sxyazi/yazi/assets/146579014/160472d9-6736-4828-a7f5-889765af8afb">
I propose we add it as a preset plugin.

**Comment by sxyazi** [comment]
> I would like an inbuilt feature where Jupyter notebooks *.ipynb have good previews

No, this requires adding new dependencies for Yazi, which I'd like to avoid if possible. It should be implemented as a custom previewer plugin rather than a default previewer.

**Comment by AnirudhG07** [comment]
Sure. I'll try to implement the plugin for it. If I am not able to, ill let you know.

**Comment by AnirudhG07** [comment]
<img width="1414" alt="image" src="https://github.com/sxyazi/yazi/assets/146579014/2a7361d8-6ad3-4598-93f6-11289ed11232">
How does this look??
