### ISSUE TITLE
Open With

### ISSUE THREAD

**Issue by SunnyTamang** [sxyazi/yazi#1271]
### Please describe the problem you're trying to solve

Lets say there is a video and i want to open it using any media player, i have vlc and any other player. And i could select the desired media player for the video player

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

The solution that i could think of is that, if there is any video or media, there should be one keybind lets say ["o","w"] for openwith or just a properties window for the media/video. So the user can select it/

**Comment by sxyazi** [comment]
`open --interactive` is what are you looking for:

https://github.com/sxyazi/yazi/blob/f2b7f3eaf7bbfee5fdd4719f4fabe32c08aec1b5/yazi-config/preset/keymap.toml#L62-L63

See docs at https://yazi-rs.github.io/docs/quick-start#filedirectory-operations and https://yazi-rs.github.io/docs/configuration/yazi#opener, closing as already exists.

**Comment by SunnyTamang** [comment]
This is exactly what i required. Though i think I have to configure MPV.
So indorder to change the media player, i guess there might be something in the docs.
