### ISSUE TITLE
Show "Loading" instead of "No items" if the directory is not empty but the items are still loading

### ISSUE THREAD

**Issue by Ape** [sxyazi/yazi#1273]
### Please describe the problem you're trying to solve

Currently, if you navigate to a directory in a particularly slow file system, yazi will show "No items" until it has loaded some directory entries. This looks just like an empty directory would, but happens regardless of if the directory is actually empty.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Yazi should show something like "Loading" instead of "No items" until it actually knows that the directory is empty, or until we have some actual directory contents to show.

**Comment by sxyazi** [comment]
Should be fixed in https://github.com/sxyazi/yazi/pull/1439
