### ISSUE TITLE
Show number of files for folders in size linemode

### ISSUE THREAD

**Issue by Ape** [sxyazi/yazi#1277]
### Please describe the problem you're trying to solve

I'd like to see the number of files in each folder when I am using the size linemode.

And no, the size of the folder on disk in bytes is not meaningful. I want to have the number of files inside.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

It would look this:
```
empty_folder       0
small_folder       4
big_folder        53
regular_file   15.8K
big_file        3.2G
```

**Comment by PoisonFrog** [comment]
I also prefer it like this, but I think the best would be if we had an option called "dirlinemode" or something like this, then the user would be able to choose if he wants to show the number of files inside the directory or the size of the folder.

**Comment by sxyazi** [comment]
Done in https://github.com/sxyazi/yazi/pull/1591 🎉
