### ISSUE TITLE
Open with command

### ISSUE THREAD

**Issue by Ape** [sxyazi/yazi#1284]
### Please describe the problem you're trying to solve

I'd like to have a Yazi command (for keymap) to ask for a command with a text prompt and then open the file with that command.

The current `open --interactive` with the fixed options feels too restrictive to me.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Something like `open --cmd`

**Comment by sxyazi** [comment]
The `shell` command is what you're looking for. 

You can use it to execute any program or shell script and use familiar variables like `$1`, `$2`, `$@` etc to represent the list of selected files.

Doc of the `shell` command: https://yazi-rs.github.io/docs/configuration/keymap#manager.shell, closing as already exists.

**Comment by Ape** [comment]
Hmm, thanks. `shell --interactive --orphan` is almost what I need. But I'd really like to skip typing the `$@`. If I add it to the shell template then the cursor will be annoyingly after it, not before it.

**Comment by sxyazi** [comment]
You can achieve it through a simple plugin with a few lines of code:

```lua
return {
  entry = function()
    local value, event = ya.input {
      title = "Shell with `$@`:",
      position = { "top-center", y = 3, w = 40 },
    }
    if event == 1 then
      ya.manager_emit("shell", {
        value .. ' "$@"',
        orphan = true,
        confirm = true,
      })
    end
  end,
}
```

Save it as `~/.config/yazi/plugins/my-shell.yazi/init.lua` and bind it in your `keymap.toml`:

```sh
{ on = [ ":" ], run = "plugin my-shell" }
```

**Comment by Ape** [comment]
Thank you so much!

I hope you don't mind that I created a repository for this plugin: https://github.com/Ape/open-with-cmd.yazi

**Comment by sxyazi** [comment]
Awesome! 

Would like to [add it to the resource page](https://yazi-rs.github.io/docs/resources#add-yours) so more people can use it?
