### ISSUE TITLE
Add random sort

### ISSUE THREAD

**Issue by DVN196** [sxyazi/yazi#1285]
### Please describe the problem you're trying to solve

I'd like to be able to list the file in random order. This is useful when browsing a large library folder without specific target.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

List file and folder in randomize order. Remember the randomize order within session.

**Comment by sxyazi** [comment]
Sounds good to me, anyone want to give it a go?

We need to add a new `SortBy::Random` sorting type here:

https://github.com/sxyazi/yazi/blob/f5598ebb8adf13b78e24b9456c9ae32605687817/yazi-core/src/folder/sorter.rs#L33-L38

And generate a random number for sorting purposes, almost like what `SortBy::Modified` does but not involve any file metadata just a random factor

**Comment by zooeywm** [comment]
Hi I've been using yazi for a long time, and wishing to contribute. I would like to have a try

**Comment by sxyazi** [comment]
Nice, thank you! @zooeywm

**Comment by zooeywm** [comment]
Added in #1291, thanks for review ; )

**Comment by sxyazi** [comment]
Done in https://github.com/sxyazi/yazi/pull/1291, thanks!
