### ISSUE TITLE
mode_normal's fg color changes after returning from file

### ISSUE THREAD

**Issue by Archdsenna** [sxyazi/yazi#1289]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

Terminal

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####
release ❯ ./yazi --debug                                                                                                                                                       (main)
Gi=31,s=1,v=1,a=q,t=d,f=24;AAAA
Yazi
    Version: 0.2.5 (5b75a8f 2024-07-13)
    Debug  : false
    OS     : macos-aarch64 (unix)

Ya
    Version: 0.2.5

Emulator
    Emulator.via_env: ("xterm-256color", "Apple_Terminal")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Apple

Adapter
    Adapter.matches: Chafa

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : None
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })
    block  : Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })

tmux
    TMUX   : false
    Version: 3.4

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : No such file or directory (os error 2)
    fzf              : 0.54.0
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    unar             : 1.10.7
    jq               : 1.7.1


--------------------------------------------------
[yazi.log](https://github.com/user-attachments/files/16200645/yazi.log)


```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug
To be precise, I'm not sure if this is a bug, but the behavior of yazi is definitely not what I expected.

The fg color of NORMAL displayed in the bottom status bar is inconsistent when the yazi interface is opened from the terminal and returned from the file.

I have tried both yazi downloaded from brew and yazi built from source, and they have the same problem.

This is gif:
![20240713104238_rec_](https://github.com/user-attachments/assets/da1856d0-5b2c-40cc-8a72-2a78fe16e743)

Here is the comparison
![image](https://github.com/user-attachments/assets/3f4b705f-3e28-4f42-930d-02a6f906fa20)

More information [Here](https://github.com/sxyazi/yazi/discussions/1286) 

### Expected Behavior

When you close the file and return to yazi again, the fg color of the NORMAL in the bottom status bar will not change

### To Reproduce

There is no more for now, I will continue to add if necessary

### Configuration

theme.toml:

`[status]
mode_normal = { fg = "yellow", bg = "23", bold = true }
`

**Comment by sxyazi** [comment]
I haven't tested Yazi in `Terminal.app`, it's likely that it doesn't support some of the terminal features Yazi uses. I suggest switching to a more modern terminal emulator like iTerm, kitty, WezTerm, Alacritty, etc. They've all been tested and work well.

You can also run the official Ratatui example to test your terminal's compatibility: https://github.com/ratatui-org/ratatui/tree/main/examples#examples

**Comment by Archdsenna** [comment]
Got it, thanks a lot! I will try tmux.
