### ISSUE TITLE
Add `rust-toolchain.toml` config file

### ISSUE THREAD

**Issue by zooeywm** [sxyazi/yazi#1292]
### Please describe the problem you're trying to solve

The yazi terminal file manager is the best one I've ever seen. But the first time when I try to contribute, I have to manually switch channel to nightly.

And [there is one deprecated fmt option](https://rust-lang.github.io/rustfmt/?version=master&search=#hide_parse_errors), which recommended by using `show_parse_errors` instead of `hide_parse_errors`

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Add a `rust-toolchain.toml` in the project's root directory to automatically switch channel.

**Comment by zooeywm** [comment]
I attempted it in #1293.

**Comment by sxyazi** [comment]
Closed in https://github.com/sxyazi/yazi/pull/1293
