### ISSUE TITLE
Dual panel like total commander 

### ISSUE THREAD

**Issue by vladimir-salvador** [sxyazi/yazi#1294]
### Please describe the problem you're trying to solve

It would be great to have a dual panel view of files in which I can quickly have 2 directories side by side and I can copy with a keyword the selected file on one panel to the other panel

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

User opens yazi 
A dual panel appears

**Comment by sxyazi** [comment]
Tracked by https://github.com/sxyazi/yazi/issues/51
