### ISSUE TITLE
Search for keybinding by description

### ISSUE THREAD

**Issue by Daniel-Chin** [sxyazi/yazi#1298]
### Please describe the problem you're trying to solve

You need to find the keybinding of a specific action. 

E.g., you want to go to the downloads dir, but you can't remember / don't know it's "gd".  

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

In the "help (~)" screen, press "f" to filter the list of keybindings. 

### Additional context

- This will help beginners like me to familiarize themselves with `yazi`. 
- It is a time-tested workflow to use natural language to describe your need. 
  - In VS Code, you can "F1" or "Ctrl+Shift+P" to open the *command palette*. 
  - In Google Doc/Sheet/Slides, "Alt+/" searches commands. 
  - In MS Office, "Alt Q" searches commands.

**Comment by Daniel-Chin** [comment]
Related: #1153

**Comment by AnirudhG07** [comment]
When you press "~" to get the helpscreen, you only get keybindings, the keybindings at the left, command in middle and description at right. Even your plugins keybindings show up. You can always search for "downloads" using "/" there, to get to "gd".

**Comment by Daniel-Chin** [comment]
> When you press "~" to get the helpscreen, you only get keybindings, the keybindings at the left, command in middle and description at right. Even your plugins keybindings show up. You can always search for "downloads" using "/" there, to get to "gd".

Thank you for mentioning "/"! In conclusion, the feature I ask for already exists. Closing the issue now. ;-)
