### ISSUE TITLE
Permanently deleting folder crashes on Windows

### ISSUE THREAD

**Issue by ndtoan96** [sxyazi/yazi#1320]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Windows Terminal

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####
Yazi
    Version: 0.2.5 (66e83f3 2024-07-20)
    Debug  : false
    OS     : windows-x86_64 (windows)

Ya
    Version: program not found

Emulator
    Emulator.via_env: ("", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Chafa

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : None
    EDITOR             : Some("hx")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE      : Some("C:\\Program Files\\Git\\usr\\bin\\file.exe")
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "%EDITOR% \"%*\"", block: true, orphan: false, desc: "EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "%EDITOR% \"%*\"", block: true, orphan: false, desc: "EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: program not found

Dependencies
    file             : 5.45
    ueberzugpp       : program not found
    ffmpegthumbnailer: program not found
    magick           : program not found
    fzf              : 0.43.0
    fd               : 8.7.1
    rg               : 13.0.0
    chafa            : program not found
    zoxide           : 0.9.4
    unar             : program not found
    jq               : program not found


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "C:\\Users\\ASUS\\AppData\\Roaming\\yazi\\state" directory.

```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

When deleting a folder permanently (i.e. `D`), the app just crashes with error `STATUS_ILLEGAL_INSTRUCTION`. I checked the log in `yazi/state` but no error was logged there. Interestingly, it only crashes with `--release` build, while `--debug` build works fine.

### Expected Behavior

The app does not crash.

### To Reproduce

1. Create an empty folder (or with files, it does not matter)
2. Use `D` to delete the folder permanently
3. Wait a little to see the app crashes

### Anything else?

https://github.com/user-attachments/assets/abced270-60dc-4bea-9a87-4cbf0ea6ab21

_No response_

**Comment by ndtoan96** [comment]
Seems like this is a really old bug, I checked out version 0.2.4 and it's still there.

**Comment by sxyazi** [comment]
I can reproduce it on my Windows VM, after some investigating, it seems to be a bug in the [notify-rs](https://github.com/notify-rs/notify) library — on Windows, when the file being watched is no longer available, it causes the program to crash.

Also I noticed this behavior only occurs on Windows; macOS and Linux don't have this issue.

I can reproduce it with the following code:

```rust
fn main() {
  let p = Path::new("C:\\Users\\ika\\Desktop\\abc");
  std::fs::create_dir(p).unwrap();

  let mut watcher = ::notify::RecommendedWatcher::new(|_| {}, Default::default()).unwrap();
  watcher.watch(p, ::notify::RecursiveMode::NonRecursive).unwrap();

  // Try to comment on this line you'll see "Exit successful" printed normally
  std::fs::remove_dir_all(p).unwrap();

  std::thread::sleep(Duration::from_secs(5));
  println!("Exited successfully");
}
```

Unfortunately it's unclear how to fix it right now, I'll report it upstream.

**Comment by sxyazi** [comment]
Hi, I've temporarily pinned `notify` to an [unreleased commit](https://github.com/notify-rs/notify/commit/128bf6230c03d39dbb7f301ff7b20e594e34c3a2) in https://github.com/sxyazi/yazi/commit/1e1ae637a8cd183b1e95f8c218b5022d547df7a9#diff-5bc5ff0b737104e617ec3aef2e05502b7f8aeafe84a73914ca5d0692c954b800 as a workaround which includes a fix for that UB, let me know if it works for you!

**Comment by ndtoan96** [comment]
> Hi, I've temporarily pinned `notify` to an [unreleased commit](https://github.com/notify-rs/notify/commit/128bf6230c03d39dbb7f301ff7b20e594e34c3a2) in [1e1ae63#diff-5bc5ff0b737104e617ec3aef2e05502b7f8aeafe84a73914ca5d0692c954b800](https://github.com/sxyazi/yazi/commit/1e1ae637a8cd183b1e95f8c218b5022d547df7a9#diff-5bc5ff0b737104e617ec3aef2e05502b7f8aeafe84a73914ca5d0692c954b800) as a workaround which includes a fix for that UB, let me know if it works for you!

Thank you, I just tested an it works.
