### ISSUE TITLE
Start with multiple tabs with different paths

### ISSUE THREAD

**Issue by gotbletu** [sxyazi/yazi#1322]
### Please describe the problem you're trying to solve

yazi only works with 1 path.
i dont see any options in the help pages that allows to open multiple tabs on startup.

eg.
`yazi ~/Downloads`

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

add option to start yazi with multiple tabs with different paths on startup

`yazi ~/Download ~/Documents ~/Public ~/Music`

**Comment by sxyazi** [comment]
Sounds good to me, anyone wants to give it a go? 

We need to change the `entry`

https://github.com/sxyazi/yazi/blob/db9332133886f2a2335d56194cae5ac14e3bf0a0/yazi-boot/src/args.rs#L10

to

```rust
pub entities: Vec<PathBuf>
```

and here is the code to parse it:

https://github.com/sxyazi/yazi/blob/db9332133886f2a2335d56194cae5ac14e3bf0a0/yazi-boot/src/boot.rs#L21-L33
