### ISSUE TITLE
Cut files still appear on dir preview

### ISSUE THREAD

**Issue by wojciech-kulik** [sxyazi/yazi#1330]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

kitty 0.35.2

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####

Yazi
    Version: 0.2.5 (Homebrew 2024-04-23)
    OS: macos-aarch64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect: Kitty

Adaptor
    Adaptor.matches: Kitty

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/bin/zsh")
    EDITOR: Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.41\nmagic file from /usr/share/file/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

I'm migrating from `lf` so I'm not yet fully fluent with yazi, but I noticed a weird issue that doesn't refresh dir preview after some operations.

Environment:
macOS 14.5
kitty 0.35.2
Yazi 0.2.5 (Homebrew 2024-04-23)

### Expected Behavior

Dir preview should be refreshed and it should reflect the current state.

### To Reproduce

1. Go to sub-folder
2. Select some files and cut them
3. Go back to the parent, **move the focus somewhere else**, and paste them.
4. Check out dir preview

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1331

**Comment by wojciech-kulik** [comment]
Wow, that's fast!

How can I build the project? I read: https://github.com/sxyazi/yazi/blob/main/CONTRIBUTING.md, however, I'm getting this error:

```
  cargo build                                                                                                                                                                                                                             01:57
error: failed to select a version for `mlua`.
    ... required by package `yazi-plugin v0.2.5 (/Users/wkulik/repositories/yazi/yazi-plugin)`
    ... which satisfies path dependency `yazi-plugin` (locked to 0.2.5) of package `yazi-core v0.2.5 (/Users/wkulik/repositories/yazi/yazi-core)`
versions that meet the requirements `^0.9.9` (locked to 0.9.9) are: 0.9.9

the package `yazi-plugin` depends on `mlua`, with features: `mlua_derive` but `mlua` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.


failed to select a version for `mlua` which could resolve this conflict
```

**Comment by sxyazi** [comment]
See https://yazi-rs.github.io/docs/installation#cargo or https://yazi-rs.github.io/docs/installation#build-from-source

**Comment by sxyazi** [comment]
You can also do `brew install yazi --HEAD` if you're using Homebrew

**Comment by wojciech-kulik** [comment]
I installed it now via Homebrew and I get:
```
  yazi                                                                                                                                                                                                                                    02:16
Error: TOML parse error at line 258, column 1
    |
258 | [[manager.prepend_keymap]]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^
missing field `run`
```

It's not from my config. I don't have 250+ lines.

**Comment by sxyazi** [comment]
The main branch is the upcoming Yazi v0.3 and the `exec` has been deprecated and replaced with `run`, see https://github.com/sxyazi/yazi/issues/1046

**Comment by wojciech-kulik** [comment]
I've just figured it out :D. It worked now, but as you said, the fix is not merged yet. I will try tomorrow to build it from source to verify the fix (it's getting really late on my side 🌃 )

**Comment by wojciech-kulik** [comment]
Confirmed, now it works properly after your fix 🔥

**Comment by sxyazi** [comment]
Thanks for confirming, let's just merge it now
