### ISSUE TITLE
F1 should open the help page

### ISSUE THREAD

**Issue by CyberShadow** [sxyazi/yazi#1333]
### Please describe the problem you're trying to solve

https://github.com/sxyazi/yazi/issues/736

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

F1 is the standard "Help" key, it should open a help page or some documentation menu

### Additional context

See also how ranger does it

**Comment by sxyazi** [comment]
Hi, Yazi uses `~` instead of `F1` to open help because it's more universal. Some keyboards don't have function keys or require pressing them along with the `Fn` key, so I wanted to avoid using function keys as much as possible.

Closing as not in the plan.

**Comment by CyberShadow** [comment]
What a strange decision.

- F1 is a standard key on PC keyboards, meaning, all PC software ought to assume it is a key that a user might press.
- Even if there are "minimal" keyboards which do not have some standard keys, Yazi could still recognize it as an alternative to ~.
- F1 is also the standard help key in a lot of software out there, that many people use every day.
- I don't know of any other program that uses ~ for a help key.
- Having the help key on a key that a user will never think of pressing defeats the point. As it stands, this feature is completely undiscoverable.
- If I have to look up an external resource just to discover what key to press to get help, you might as well just put all help text somewhere on the Internet too.

Well, it's your project.

**Comment by CyberShadow** [comment]
What do you think about, any time the user presses an unbound key, showing a message such as "Press ~ for help"? This should make the keybind discoverable without explicitly binding it to a function key.

**Comment by sxyazi** [comment]
Ah I must've misunderstood you - I'm ok with adding a new `F1` as an alternative to `~`, as long as it's not replacing it. Do you want to raise a PR for it?

**Comment by CyberShadow** [comment]
Ah, sorry - indeed I proposed it as an alternative, not moving the existing keybind.

https://github.com/sxyazi/yazi/pull/1336
