### ISSUE TITLE
`ya pub "$YAZI_ID" dds-cd "..."` doesn't work on the main branch

### ISSUE THREAD

**Issue by wojciech-kulik** [sxyazi/yazi#1334]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

kitty 0.35.2

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####
Yazi
    Version: 0.2.5 (Homebrew 2024-07-22)
    Debug  : false
    OS     : macos-aarch64 (unix)

Ya
    Version: 0.2.5

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: 3.4

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-35
    fzf              : 0.54.1
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    unar             : 1.10.7
    jq               : 1.7.1

```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

On the version from main branch navigation via `ya pub` stopped working. It returns exit code 2. On the stable version from Homebrew it works correctly.

### Expected Behavior

`ya` should not return error and should navigate to the pointed directory

### To Reproduce

My sample binding
```
  { on = ["i", "f"], run = '''
    shell --confirm --block '
      # some other operations
      ya pub "$YAZI_ID" dds-cd --str "$HOME/Desktop/mydir"
    '
  ''', desc = "Do something" },
```

**Comment by sxyazi** [comment]
Use `ya pub dds-cd` instead, which is a breaking change in the upcoming Yazi 0.3, https://github.com/sxyazi/yazi/pull/1111#issue-2329283022

**Comment by wojciech-kulik** [comment]
Great! It works well now. Thank you!

**Comment by wojciech-kulik** [comment]
There is a bug in the documentation then, it is showing the old way:
https://yazi-rs.github.io/docs/dds/#cd

**Comment by sxyazi** [comment]
Yeah the doc is for the stable version, I will update it after the 0.3 release. We don't have nightly docs yet
