### ISSUE TITLE
Cursor starts blinking after launching and exiting yazi

### ISSUE THREAD

**Issue by CyberShadow** [sxyazi/yazi#1337]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

rxvt-unicode (urxvt) v9.31 - released: 2023-01-02

### `yazi --debug` output

<details>

```sh

Yazi
    Version: 0.2.5 (4a05226 1980-01-01)
    Debug  : true
    OS     : linux-x86_64 (unix)

Ya
    Version: No such file or directory (os error 2)

Emulator
    Emulator.via_env: ("rxvt-unicode-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Urxvt

Adapter
    Adapter.matches: X11

Desktop
    XDG_SESSION_TYPE: Some("tty")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some("localhost:18.0")

SSH
    shared.in_ssh_connection: true

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("/home/vladimir/bin/editor")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: 3.4

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : 7.1.1-35
    fzf              : 0.54.0
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    unar             : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/vladimir/.local/state/yazi" directory.

```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Running `yazi` and then quitting it (by pressing `q`) makes the cursor blink in urxvt.

This could be undesirable if the user doesn't want to have a blinking cursor in their shell (bash/zsh).

By default, cursor blink is disabled in urxvt.

I don't know if it's possible to query/restore the cursor blink state in the terminal, but if it is, then I think it would be nice if yazi did so.

### Expected Behavior

Cursor properties should ideally be preserved.

### To Reproduce

Start `urxvt`
Run `yazi`
Press `q`

### Configuration

no config

**Comment by sxyazi** [comment]
Yazi will reset the cursor to the default when exiting:

https://github.com/sxyazi/yazi/blob/1ab3eb911a071fa1a01e2f31ce93afcb385195fb/yazi-fm/src/term.rs#L82

I haven't used `urxvt` myself, does it support [this sequence](https://docs.rs/crossterm/latest/src/crossterm/cursor.rs.html#394) (`"\x1b[0 q"`)?

**Comment by CyberShadow** [comment]
> does it support [this sequence](https://docs.rs/crossterm/latest/src/crossterm/cursor.rs.html#394) (`"\x1b[0 q"`)?

This sequence makes the cursor blink.

The linked page suggests that it should reset the cursor to the "default" (`DefaultUserShape`). But, I'm not sure that is accurate - for example, this page suggests that this sequence makes the cursor a "blinking block": https://st.suckless.org/patches/blinking_cursor/

**Comment by CyberShadow** [comment]
I found a very similar issue on Vim's bug tracker: https://github.com/vim/vim/issues/1986

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1346

**Comment by CyberShadow** [comment]
Doesn't seem to have an effect.

**Comment by sxyazi** [comment]
Please do `echo -e '\033[?12$p'; cat` and `echo -e '\033P$q q\033\\'; cat` and copy the response of your urxvt here

**Comment by CyberShadow** [comment]
`^[[?12;2$y` and nothing.

**Comment by sxyazi** [comment]
I added some logs in https://github.com/sxyazi/yazi/pull/1346/commits/14d6c962106502cde5c6890bd9511b3500ea9fc4, please try it and paste the log from your `~/.local/state/yazi/yazi.log`

**Comment by CyberShadow** [comment]
OK, here it is:

```
  [2m2024-07-25T09:55:32.619764Z[0m [33m WARN[0m [1;33myazi_adapter::emulator[0m[33m: [33m[Adapter] No special environment variables detected[0m
    [2;3mat[0m yazi-adapter/src/emulator.rs:70

  [2m2024-07-25T09:55:32.619818Z[0m [33m WARN[0m [1;33myazi_adapter::emulator[0m[33m: [33m[Adapter] Unknown TERM_PROGRAM: [0m
    [2;3mat[0m yazi-adapter/src/emulator.rs:84

  [2m2024-07-25T09:55:32.619828Z[0m [33m WARN[0m [1;33myazi_adapter::adapter[0m[33m: [33m[Adapter] Could not identify XDG_SESSION_TYPE[0m
    [2;3mat[0m yazi-adapter/src/adapter.rs:101

  [2m2024-07-25T09:55:32.619857Z[0m [33m WARN[0m [1;33myazi_adapter::adapter[0m[33m: [33m[Adapter] Falling back to chafa[0m
    [2;3mat[0m yazi-adapter/src/adapter.rs:113

  [2m2024-07-25T09:55:32.620184Z[0m [33m WARN[0m [1;33myazi_adapter::ueberzug[0m[33m: [33mueberzugpp spawning failed: No such file or directory (os error 2)[0m
    [2;3mat[0m yazi-adapter/src/ueberzug.rs:87

  [2m2024-07-25T09:55:32.627543Z[0m [31mERROR[0m [1;31myazi::term[0m[31m: [31mCSI_U: false[0m
    [2;3mat[0m yazi-fm/src/term.rs:55

  [2m2024-07-25T09:55:32.627565Z[0m [31mERROR[0m [1;31myazi::term[0m[31m: [31mBLINK: false[0m
    [2;3mat[0m yazi-fm/src/term.rs:56

  [2m2024-07-25T09:55:32.627572Z[0m [31mERROR[0m [1;31myazi::term[0m[31m: [31mSHAPE: 0[0m
    [2;3mat[0m yazi-fm/src/term.rs:57

  [2m2024-07-25T09:55:33.347748Z[0m [31mERROR[0m [1;31myazi::term::cursor[0m[31m: [31mRestoring cursor shape: 0[0m
    [2;3mat[0m yazi-fm/src/term.rs:229

  [2m2024-07-25T09:55:33.347817Z[0m [31mERROR[0m [1;31myazi::term::cursor[0m[31m: [31mRestoring cursor blink2: false[0m
    [2;3mat[0m yazi-fm/src/term.rs:245

```

**Comment by sxyazi** [comment]
That's so weird, according to the log:

`Restoring cursor blink2: false`

it's going through the `DisableBlinking` branch, so the cursor blinking should be turned off. Can you confirm if `urxvt` supports [`DisableBlinking`](https://github.com/crossterm-rs/crossterm/blob/33b4e37223cff704fc81d683386742066f73619b/src/cursor.rs#L357) (`?12l`)?

**Comment by CyberShadow** [comment]
By itself, `printf $'\x1b[?12h'` enable blinking and `printf $'\x1b[?12l'` disable blinking.

However, if I start and then quit `yazi`, `printf $'\x1b[?12l'` does not disable blinking. It looks like yazi is making the cursor blink in some other way, which `printf $'\x1b[?12l'` is not enough to disable.

**Comment by sxyazi** [comment]
Thanks for the info! 

The only possibility I can think of is that `DefaultUserShape` is affecting `DisableBlinking` - when the cursor shape can't be got (`echo -e '\033P$q q\033\\'; cat` returns an empty string), it falls back to `DefaultUserShape` as this is a safe assumption, but it seems to be causing issues in `urxvt`.

I've removed it for now, but I'm not sure if this will always be effective. I've pushed a new commit; please give it a try.

**Comment by CyberShadow** [comment]
It works! Blinking is preserved when starting and quitting `yazi` - upon quitting it is restored to the preference specified with `-bc` or `+bc`.

It doesn't bother me, but I noticed that if you 1) Start `urxvt` with blinking enabled 2) Start `yazi` 3) Open and close an input popup (e.g. press <kbd>:</kbd> <kbd>Esc</kbd> <kbd>Esc</kbd>), 4) quit `yazi`, then the cursor will always stop blinking.

**Comment by sxyazi** [comment]
Nice to see it works now!

> then the cursor will always stop blinking

This is a current limitation in the implementation - Yazi changes the cursor shape when opening the input popup to indicate insert or normal mode (bar for insert, block for normal). 

But:

1. `urxvt` does not support querying the cursor shape at the startup (`echo -e '\033P$q q\033\\'; cat` returns an empty string)
2. it also does not support a default cursor shape (`DefaultUserShape` not working)

This results in:

1. being unable to restore the cursor to a determined shape (got by `\033P$q q\033\\` above) upon exit
2. being unable to fallback to the default shape (by `DefaultUserShape`) when the cursor shape (1) is unknown.

Hence, I recommend setting Yazi's `cursor_blink` in your `yazi.toml` to match the blinking state of the shell, which can serve as a workaround for this:

https://github.com/sxyazi/yazi/blob/152b9ea75e12409bbe679be8a712624d1e60eb9f/yazi-config/preset/yazi.toml#L124-L125

Anyway let's merge the PR now, thanks for the report and help to test!

**Comment by sxyazi** [comment]
OK, I've resubmitted that commit, after more attempts, I believe the issue with `urxvt` is now completely fixed in https://github.com/sxyazi/yazi/commit/df1f094a28c924504fac5d1f9585ba609a2a98e9, give it a try!

**Comment by CyberShadow** [comment]
OK, I tested all combinations:

| Blinking (`?12h/l`) | Cursor (`0/2 q`) | Initial state | Start and quit  | Start, input popup, quit |
|---------------------|------------------|---------------|-----------------|--------------------------|
| Off (l)             | Non-blinking (2) | Not blinking  | Not blinking 👍 | Not blinking 👍          |
| Off (l)             | Blinking (0)     | Blinking      | Not blinking 🐛 | Not blinking 🐛          |
| On (h)              | Non-blinking (2) | Blinking      | Blinking 👍     | Blinking 👍              |
| On (h)              | Blinking (0)     | Blinking      | Blinking 👍     | Blinking 👍              |

Also, if you think that there is something obviously broken or missing in urxvt, I can look into it and send them a patch.

Thanks!

**Comment by sxyazi** [comment]
Ah looks like there are still issues, what a headache🤦🏻

I'll check it out more tomorrow.

**Comment by sachinsenal0x64** [comment]
> Ah looks like there are still issues, what a headache🤦🏻
> 
> I'll check it out more tomorrow.

![image](https://github.com/user-attachments/assets/3f246b98-8bd2-4cb4-ab8c-663b29482fa3)

When I open with Neovim, my cursor is a block and I can't change it.

**Comment by sxyazi** [comment]
Hey @sachinsenal0x64, you're on nightly right? Just pushed a new commit, please try https://github.com/sxyazi/yazi/commit/bf206fcf310f21af74da87b03d9959c66280e539

**Comment by sachinsenal0x64** [comment]
> Hey @sachinsenal0x64, you're on nightly right? Just pushed a new commit, please try [bf206fc](https://github.com/sxyazi/yazi/commit/bf206fcf310f21af74da87b03d9959c66280e539)

I'm currently using this build https://aur.archlinux.org/packages/yazi-git

**Comment by sxyazi** [comment]
> > Hey @sachinsenal0x64, you're on nightly right? Just pushed a new commit, please try [bf206fc](https://github.com/sxyazi/yazi/commit/bf206fcf310f21af74da87b03d9959c66280e539)
> 
> I'm currently using this build https://aur.archlinux.org/packages/yazi-git

Yeah that's nightly version
