### ISSUE TITLE
Alacritty + ueberzug on Nix OS

### ISSUE THREAD

**Issue by theduke** [sxyazi/yazi#134]
I'm running yazi on NixOS inside Alacritty, and the image previews are not working.

I also tried opening a shell with uberezugpp available and then starting alacritty and yazi from there, but this doesn't seemt o make a difference.

Any tips on getting this working?

**Comment by sxyazi** [comment]
Please do a `echo $TERM, $TERM_PROGRAM, $XDG_SESSION_TYPE` and paste the result here.

**Comment by theduke** [comment]
```
❯ echo term: $TERM, termprogr: $TERM_PROGRAM, sesstype: $XDG_SESSION_TYPE
term: alacritty, termprogr: sesstype: wayland
```

**Comment by sxyazi** [comment]
Please run `ueberzug layer` and paste 

```json
{"action":"add","identifier":"preview","max_height":0,"max_width":0,"path":"/your/image-path.jpg","x":0,"y":0}
``` 

into it, then Enter, and to see if any image is shown, without exit the `ueberzug`

**Comment by sxyazi** [comment]
I think you might have the same issue

https://github.com/sxyazi/yazi/issues/207#issuecomment-1732191416

**Comment by sxyazi** [comment]
Please reopen this issue if the problem persists, closing then
