### ISSUE TITLE
Provide controls over whether the terminal title is updated

### ISSUE THREAD

**Issue by chriszarate** [sxyazi/yazi#1350]
### Please describe the problem you're trying to solve

Yazi automatically updates the terminal window title using ANSI escape sequences. When it exits, it updates the title to an empty string. However, Yazi may be invoked within another process (like Vim). When Yazi updates the terminal title, it overrides the title set by the parent process, and cannot restore the previous title.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Some users have preferences for setting the terminal title and may not want it overridden in any case. Other users may want a command line flag to control this behavior—this would allow updating the title in most cases but provide an opt-out when `yazi` is invoked by embedded tooling (e.g., a Vim plugin).

I opened a PR to provide an `update_title` configuration option to control whether the title is updated:
https://github.com/sxyazi/yazi/pull/1281

Correct me if I'm wrong, but there is no way to "read" the current terminal title when `yazi` starts and restore it when `yazi` exits. If there is, consider that a preferred alternate solution.

**Comment by sxyazi** [comment]
I'm not quite sure what you mean - do you want to not set the title at all, or set the title and then restore the original one when exiting? 

If it's the latter, that's the current behavior - Yazi sets the title to `""` upon exit to restore it:

https://github.com/sxyazi/yazi/blob/df1f094a28c924504fac5d1f9585ba609a2a98e9/yazi-fm/src/term.rs#L93

but some terminal emulators don't support this. Which terminal emulator are you using?

**Comment by chriszarate** [comment]
> Which terminal emulator are you using?

I use Kitty, which supports this. The issue is that most implementations of customizing the terminal title are implemented by the user's shell, e.g., via a user's `.bashrc` or via [`fish_title`](https://fishshell.com/docs/current/cmds/fish_title.html).

As you noted, Yazi doesn't restore the previous terminal title, it just sets it to an empty string. In a single Yazi session launched from the user's shell, this works ok: Upon exiting `yazi`, you return to the shell which updates the title and you don't notice that it was very briefly empty.

The issue is when `yazi` is launched within another process. Upon exiting `yazi`, you are returned not to the shell but to the parent process, and the title remains empty. Eventually the user exits the parent process, returns to a shell, and things get back to normal.

You can even see this behavior within Yazi itself by running `yazi` inside `yazi`:

https://github.com/user-attachments/assets/a12b1738-a4d0-4168-8198-1824901d84b4

In the clip above, upon exiting the nested `yazi` process, the title reverts to the default (until I navigate to another directory). This is even more disruptive in a program like `vim` that does not have the ability to update the terminal title. The title is effectively set to the default until the process exits.

**Comment by chriszarate** [comment]
> do you want to not set the title at all, or set the title and then restore the original one when exiting?

Restoring the original terminal title would be ideal, but I'm not sure that's possible. Correct me if I'm wrong. If it's not possible, then not setting the title at all (ideally controlled by a command-line flag, so that I can do it conditionally) is an acceptable solution.

**Comment by chriszarate** [comment]
> Yazi sets the title to "" upon exit to restore it

Maybe I misunderstood you, are you saying some terminal emulators handle the task of storing the previous title and restoring it when it is set to empty string? If so, can you provide an example?

**Comment by sxyazi** [comment]
I changed `update_title` to `title_format`, which will allow users more flexibility in controlling the behavior of the title. It also covers the functionality of `update_title` — if the user sets it to an empty string (`""`), the title won't be updated.
