### ISSUE TITLE
Paste files to clipboard

### ISSUE THREAD

**Issue by LGraz** [sxyazi/yazi#1353]
### Please describe the problem you're trying to solve

I want to copy a file (i.e. a picture) and paste it to a GUI (e.g. whatsappWeb or ChatGPT).
Until now I open a GUI fm (Thunar / Nautilus) to do this job which feels frustrating.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

New copy_file_to_clipboard command. Or automatic behavior when yanking files.

### Additional context

So far I tried on wayland:
wl-copy --type image/png < 20181105_191237.jpg
does the Job for me in the terminal
Somehow, specifying the wrong MIME type is necessary to get it work.

**Comment by sxyazi** [comment]
Does this tip work for you? https://yazi-rs.github.io/docs/tips#selected-files-to-clipboard
