### ISSUE TITLE
The fetchers files list includes directories when there are changes in the folder

### ISSUE THREAD

**Issue by leihaojun** [sxyazi/yazi#1355]
### Please describe the problem you're trying to solve

Currently fetcher can only fetch non-directory files, so the plugin cannot get the list of subfolders in the directory when the folder changes.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/bcb69e5d-1d9c-431d-a85f-69606355adf9)

Can we add a condition to get a list of all files, including directories.

**Comment by sxyazi** [comment]
This is because directories always have the mime-type `"inode/directory"`. 

Changing it to `if="!mime | mime"` should work.

**Comment by leihaojun** [comment]
```lua
function M:fetch()
	for index, value in ipairs(self.files) do
		ya.err(tostring(value.url))
	end
	return 3	
end
```

I have tried, when the condition is 
```
{ id = "test", name = "*", run = "test",if = "mime", prio = "normal" }
```

 still can not get any directory, but when paste a file , the file name is contained in self.files.


when the condition is 
```
{ id = "test", name = "*", run = "test",if = "mime | ！mime", prio = "normal" }
```

 not only the directory, even the file can not get.
 
 maybe this is a bug?

**Comment by sxyazi** [comment]
Oh it should be:

```sh
fetchers = [
  { id = "test", name = "*", run = "test", if = "!mime | mime" },  # For files
  { id = "test", name = "*/", run = "test", if = "!mime | mime" }, # For dirs
]
```

In most cases only file prefetching is needed, so directories and files are handled separately to improve performance. Sorry forgot about that.
