### ISSUE TITLE
Commit df1f094 breaks foot sixel

### ISSUE THREAD

**Issue by Gajus84** [sxyazi/yazi#1357]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot 1.17.2

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####
Yazi
    Version: 0.2.5 (bf206fc 2024-07-26)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.2.5

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Err(deadline has elapsed)
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Wayland

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-1")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("zsh")
    EDITOR             : Some("hx")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : Some("/home/gajus/.config/yazi")

Text Opener
    default: Some(Opener { run: "[ -n \"chezdit\" ] &&  chezdit \"$@\"", block: true, orphan: false, desc: "chezdit", for_: None, spread: true })
    block  : Some(Opener { run: "[ -n \"chezdit\" ] &&  chezdit \"$@\"", block: true, orphan: false, desc: "chezdit", for_: None, spread: true })

tmux
    TMUX   : false
    Version: No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-35
    fzf              : 0.54.0
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 0.9.73
    zoxide           : 0.9.4
    unar             : 1.10.7
    jq               : 1.7.1
``

</details>


### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Yazi takes a long time to start (20s+). After that sixel-support will not work and ueberzugpp will be used as a fallback.

Reverting Commit df1f094 and rebuilding will fix it.

### Expected Behavior

Sixel support working in foot terminal.

### To Reproduce

Open Yazi (Git-Version) with foot and hover over a picture. Without ueberzugpp no preview will be shown.

### Configuration

_No response_

### Anything else?

_No response_

**Comment by sxyazi** [comment]
Please do `echo -e '\033[?12$p\033P$q q\033\\\033[?u\033[c'; cat` and paste the output here

**Comment by Gajus84** [comment]
> Please do `echo -e '\033[?12$p\033P$q q\033\\\033[?u\033[c'; cat` and paste the output here

Output is: ^[[?12;0$y^[P1$r1 q^[\^[[?0u^[[?62;c

**Comment by sxyazi** [comment]
I added some logs, please run https://github.com/sxyazi/yazi/pull/1359 and paste the log from your `~/.local/state/yazi/yazi.log` here

**Comment by Gajus84** [comment]
``2024-07-26T14:44:48.885096Z  WARN yazi_adapter::emulator: [Adapter] No special environment variables detected
     at yazi-adapter/src/emulator.rs:70

  2024-07-26T14:44:48.885110Z  WARN yazi_adapter::emulator: [Adapter] Unknown TERM_PROGRAM: 
    at yazi-adapter/src/emulator.rs:84

  2024-07-26T14:44:48.885111Z  WARN yazi_adapter::emulator: [Adapter] Unknown TERM: xterm-256color
    at yazi-adapter/src/emulator.rs:92

  2024-07-26T14:44:58.885303Z ERROR yazi_adapter::emulator: read_until_da1 timed out: [27, 80, 62, 124, 102, 111, 111, 116, 40, 49, 46, 49, 55, 46, 50, 41, 27, 92, 27, 91, 63, 54, 50, 59, 52, 59, 50, 50, 59, 50, 56, 99], error: Elapsed(())
    at yazi-adapter/src/emulator.rs:213

  2024-07-26T14:44:58.887302Z ERROR yazi_dds::client: Could not parse payload:
yank,0,300,{"cut":false,"urls":[]}

Error:
data did not match any variant of untagged enum Data
    at yazi-dds/src/client.rs:59

**Comment by sxyazi** [comment]
I resubmitted the commit https://github.com/sxyazi/yazi/commit/f024ce03e7b97f55f3bfad9da4b33458cea765d5, please give it a try

**Comment by Gajus84** [comment]
Fixed it. Thanks for the quick help, as always!
