### ISSUE TITLE
incorrect fetchers filter causes the self.files arg  can't contain folder

### ISSUE THREAD

**Issue by leihaojun** [sxyazi/yazi#1358]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

foot version: 1.17.2 +pgo +ime +graphemes -assertions

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.5 (bf206fc 2024-07-26)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.2.5

Emulator
    Emulator.via_env: ("foot", "")
    Emulator.via_csi: Err(deadline has elapsed)
    Emulator.detect : Foot

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-1")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/fish")
    EDITOR             : Some("nvim ")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "$EDITOR \"$1\"", block: true, orphan: false, desc: "neovim", for_: None, spread: false })
    block  : Some(Opener { run: "$EDITOR \"$1\"", block: true, orphan: false, desc: "neovim", for_: None, spread: false })

tmux
    TMUX   : false
    Version: 3.4

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-35
    fzf              : 0.54.0
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.1
    zoxide           : 0.9.4
    unar             : 1.10.7
    jq               : 1.7.1


--------------------------------------------------


```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

refer to https://github.com/sxyazi/yazi/issues/1355#issuecomment-2252622583

### Expected Behavior

self.files arg should be able to contain folder.

### To Reproduce

1.impl a fetcher
```lua
function M:fetch()
	for index, value in ipairs(self.files) do
		ya.err(tostring(value.url))
	end
	return 3	
en
```

2. use the fetcher
{ id = "test", name = "*", run = "test",if = "mime", prio = "normal" }

**Comment by leihaojun** [comment]
![image](https://github.com/user-attachments/assets/23e10ca1-beca-4084-8d99-56a48edc588b)

There is an error in this filter `match_path`

![image](https://github.com/user-attachments/assets/f05fb75d-ae4e-47c6-aade-d4ebe549f172)

the `self.is_dir` is always false.


because the `s` var  is not a `path string` but a `mime-type string`

![image](https://github.com/user-attachments/assets/9c5a7d43-4f4d-4766-9107-e1d1f0e345d6)

![image](https://github.com/user-attachments/assets/da337144-a035-4dd9-99fc-23dfac1b1c13)

**Comment by leihaojun** [comment]
so b.len() is always euqal a.len()

**Comment by sxyazi** [comment]
file and dir rules are different, just try the demo in https://github.com/sxyazi/yazi/issues/1355#issuecomment-2252696511, it should just work

![screenshot-001919](https://github.com/user-attachments/assets/018f9680-a69a-4541-84a8-71c25756a84d)

**Comment by leihaojun** [comment]
He seems to be work now.

**Comment by sxyazi** [comment]
OK closing the issue then

**Comment by leihaojun** [comment]
It seems that this condition is superfluous

if = "!mime"   or if ='"mime"

Because it can already be distinguished in this way:

name = "*/" and name = "*"

**Comment by leihaojun** [comment]
But the above code is also very strange why compare two mime-type strings length

**Comment by sxyazi** [comment]
> It seems that this condition is superfluous

That's right because the `fetcher` isn't fully complete yet (it's not in the current target), this is just a workaround.

> why compare two mime-type strings length

The `name` rule is a glob that compares file paths rather than mime-types, unless you use `mime` rules. The length comparison checks if the glob contains `\s` (case-sensitive) or `/` (indicating it must be a directory).
