### ISSUE TITLE
Image alignment issues

### ISSUE THREAD

**Issue by musjj** [sxyazi/yazi#136]
The way image previews are positioned is kind of wrong:

![image](https://github.com/sxyazi/yazi/assets/72612857/ebccf5ef-7101-4c58-bd78-d942f83a52c3)

They "bleed" out of their container a bit.

**Comment by sxyazi** [comment]
Thanks for the feedback. I will investigate this soon.

**Comment by sxyazi** [comment]
https://github.com/sxyazi/yazi/pull/144

I think this PR should fix the issue, please give it a try

**Comment by musjj** [comment]
Thanks, the PR fixed the issue for me!
