### ISSUE TITLE
High CPU/RAM usage after updating to `1e1ae63`

### ISSUE THREAD

**Issue by xfzv** [sxyazi/yazi#1368]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.35.2

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.5 (1e1ae63 2024-07-30)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.2.5

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("tty")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR} \"$@\"", block: true, orphan: false, desc: "Neovim", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR} \"$@\"", block: true, orphan: false, desc: "Neovim", for_: None, spread: true })

tmux
    TMUX   : false
    Version: No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-25
    fzf              : 0.53.0
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    7z               : 16.02
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/xfzv/.local/state/yazi" directory.

```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

After updating to [`1e1ae637a8cd183b1e95f8c218b5022d547df7a9`](https://github.com/sxyazi/yazi/commit/1e1ae637a8cd183b1e95f8c218b5022d547df7a9) today via `cargo`, I'm observing noticeable higher CPU/RAM usage.

Downgrading to the previous commit (f024ce03e7b97f55f3bfad9da4b33458cea765d5) with

```sh
cargo install --locked --git https://github.com/sxyazi/yazi.git --ref f024ce03e7b97f55f3bfad9da4b33458cea765d5 yazi-fm yazi-cli
```

restores usual CPU/RAM usage (see screenshots below).

### Expected Behavior

Usual CPU/RAM usage

### To Reproduce

1. Update to https://github.com/sxyazi/yazi/commit/1e1ae637a8cd183b1e95f8c218b5022d547df7a9
2. Notice high CPU/RAM usage
3. Downgrade to https://github.com/sxyazi/yazi/commit/f024ce03e7b97f55f3bfad9da4b33458cea765d5
4. CPU/RAM usage returned to normal

### Configuration

The issue occurs without any config file, i.e. without any `~/.config/yazi` directory.

### Anything else?

- With [`1e1ae637a8cd183b1e95f8c218b5022d547df7a9`](https://github.com/sxyazi/yazi/commit/1e1ae637a8cd183b1e95f8c218b5022d547df7a9)

![new](https://github.com/user-attachments/assets/e734eee8-ef9d-4174-91d3-8994ca2f79c1)

- With [`f024ce03e7b97f55f3bfad9da4b33458cea765d5`](https://github.com/sxyazi/yazi/commit/f024ce03e7b97f55f3bfad9da4b33458cea765d5)

![old](https://github.com/user-attachments/assets/e5ad7d47-02a6-40ac-ae94-5816c9d22a25)

Both screenshots were taken in the same directory. The CPU usage is especially abnormal in my opinion, not to mention that it's constant.

**Comment by ThGrSoRu** [comment]
I also seem to get higher cpu usage and constant minor pagefaults, when preloading iamges and fetching the mime type of certain files.

**Comment by sxyazi** [comment]
Thanks for reporting, please try https://github.com/sxyazi/yazi/commit/23a56c24a4c15807bc74dc904da10ed4cb5c3e6e

**Comment by ThGrSoRu** [comment]
That fixes it for me.
