### ISSUE TITLE
Real-time filter current directory

### ISSUE THREAD

**Issue by musjj** [sxyazi/yazi#137]
`ranger`, `nnn` and `lf` allows you to filter the current directory.

`yazi` already allows you to perform a recursive search using `fd`, but sometimes you just want to search for files within the current directory in real-time (search results are shown on every keypress, instantly).

**Comment by sxyazi** [comment]
I think https://github.com/sxyazi/yazi/pull/104 is what you expected, it was just merged 20 hours ago, you can build from source to experience it in advance!

**Comment by musjj** [comment]
Thank you, it seems pretty close to what I want! But it'd be nice if it can also narrow down the search results, similar to `/` within the `?` help menu.

**Comment by sxyazi** [comment]
> But it'd be nice if it can also narrow down the search results, similar to / within the ? help menu.

This seems to be a duplication of the `search` (note, not `find`) feature.

It searches for specific files and only displays matches. What you might be looking for is a feature to `search` within the current directory. I have plans to add this, but currently don't have enough time, of course, PR welcome.

**Comment by musjj** [comment]
Hmm, I'm not really sure if this should be a part of of a `search` option. A real-time filter have to update for every key-stroke, so wouldn't it be a bit slow since `search` needs to spawn `fd` every time? I feel that `find` is a better fit for this feature.

**Comment by sxyazi** [comment]
This is a challenge for large directories IMO, because it involves matching all files in the entire directory with every keystroke and then relaying out the Vec, which requires a lot of memory movement.

The current implementation of "Find" keeps the file list read-only and only checks and jumps to the first matching item. "Search" seems more suitable for such scenarios, even though it's not triggered with every keystroke.

**Comment by sxyazi** [comment]
It seems like fzf may use multi-threading to speed up matching -- I'm not very familiar with the specific details of fzf. However, Yazi has already integrated fzf, so you can see if it meets your needs.

Also, are there any other terminal file managers that have smoothly implemented this feature? I could use that as a reference. I've previously tried ranger's filtering feature, but it performed poorly with large directories (100,000 files) and was frustratingly slow.

**Comment by musjj** [comment]
`nnn` and `lf` implements this feature. With `nnn` you can just use the `/` command. For `lf`, put `set incfilter` in `~/.config/lf/lfrc` and run the `:filter` command. From my experience, the speed is pretty acceptable.

**Comment by sxyazi** [comment]
Okay, add it to the Feature Request and find time to implement it

**Comment by sxyazi** [comment]
Added, closing this issue in favor of the Feature Requests list

**Comment by sxyazi** [comment]
Hey @musjj, your feature request of "Filter files in real-time" has been implemented in https://github.com/sxyazi/yazi/pull/454 by @Rolv-Apneseth.
