### ISSUE TITLE
display multiple linemode options

### ISSUE THREAD

**Issue by jreuben11** [sxyazi/yazi#1371]
currently `linemode` can only display a single mode - there is no way to display both size and mdate simultaneously

make linemode a comma delimmeted list of options

**Comment by sxyazi** [comment]
With https://github.com/sxyazi/yazi/pull/1257, you can easily create your custom linemode (here's an example https://github.com/sxyazi/yazi/discussions/1288#discussioncomment-10033306), or add multi linemode alongside the preset one [through `Linemode:children_add()`](https://github.com/sxyazi/yazi/blob/23a56c24a4c15807bc74dc904da10ed4cb5c3e6e/yazi-plugin/preset/components/linemode.lua#L71)

Closing as already supported.
