### ISSUE TITLE
Nix flake is broken

### ISSUE THREAD

**Issue by sxyazi** [sxyazi/yazi#1372]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.35.2

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####


```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

After [this commit](https://github.com/sxyazi/yazi/commit/23a56c24a4c15807bc74dc904da10ed4cb5c3e6e), the Nix flake is broken. I think it might be because I used an unreleased version of `notify-rs` (https://github.com/notify-rs/notify/commit/96dec74316a93bed6eec9db177b233e6e017275e) to fix a [Windows crash issue](https://github.com/sxyazi/yazi/issues/1320), but it seems like this is affecting Nix.

I'm not sure how to fix it, if anyone could provide any tips or submit a PR, it would be greatly appreciated.

### Expected Behavior

The Nix flake is expected to build successfully.

### To Reproduce

Build using the latest commit.

**Comment by uncenter** [comment]
Was just discussing this in the Discord, I'll have a fix in a moment.
