### ISSUE TITLE
`manager_emit("open")` doesn't support multiple files

### ISSUE THREAD

**Issue by Zeioth** [sxyazi/yazi#1378]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot version: 1.17.2 +pgo +ime +graphemes -assertions

### `yazi --debug` output

x

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

[The example from the website](https://yazi-rs.github.io/docs/tips/#smart-enter) work for single files, but when more than one file is selected, pressing enter, only one file opens.

This bug is only present when using `manager_emit("open")`. Disabling the plugin, I can open multiple files again (but then I wouldn't have smart enter).

### Expected Behavior

when multiple files are selected, `manager_emit("open")` open all of them.

### To Reproduce

* Follow the [instructions from the website](https://yazi-rs.github.io/docs/tips/#smart-enter).
* press `v` and select multiple text files.
* open them.

Only one file will open. Disabling the plugin solves the issue.

### Anything else?

Please let me know if you need more details, I'm around.

**Comment by sxyazi** [comment]
That isn't a bug but intentional. The idea is to make "open" act like "enter" since "enter" only targets the currently hovered file. If you don't want it to work this way, just remove `hovered = true`.

Doc of `open`: https://yazi-rs.github.io/docs/configuration/keymap#manager.open

**Comment by Zeioth** [comment]
That did the trick thanks. I suggest updating the example in the `tips` section with `hovered = false` (or removing it) to avoid people from running into the same issue.

**Comment by sxyazi** [comment]
Well it used to be set to false, but I added it because some users reported accidental triggers, though your experience seems to be the opposite. 

Maybe we can add a note explaining it below. Do you want to raise a PR to change it? Just click the "Edit this page" link on that page.

**Comment by Zeioth** [comment]
Thank you referring me! Coming from ranger, I would vote for making this plugin behavior the default.

It's still possible to open entire directories with:
```toml
{ on = [ "<C-Enter>" ],   run = "open --interactive", desc = "Open the selected files interactively" },
```
Which is probably enough for such a border case.

**Comment by sxyazi** [comment]
AFAIK, Ranger doesn't support selecting files across directories, and that's the main reason I set it to true - when you've selected files in multiple directories, it's easy to accidentally trigger something by pressing `l` or `Enter` in the current directory.
