### ISSUE TITLE
Show owner and group with permissions

### ISSUE THREAD

**Issue by fdw** [sxyazi/yazi#1379]
### Please describe the problem you're trying to solve

While `yazi` can perfectly show the permissions for files and directories, it doesn't (or I can't find) the owner and group, which often would be very helpful to understand the permissions.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I can imagine several possible solutions:
- Adding user and group to the permissions mode line (but that takes a lot of space)
- A separate mode line for user and group
- Trying to use color in the permissions to signify users (but how exactly?)
- Showing user and group in the status line

**Comment by sxyazi** [comment]
Do these work for you?

- https://yazi-rs.github.io/docs/tips#user-group-in-status
- https://yazi-rs.github.io/docs/tips#username-hostname-in-header

**Comment by fdw** [comment]
I'll try that out! Thank you very much :)

**Comment by fdw** [comment]
Unfortunately, that snippet throws an error for me:
```
The application panicked (crashed).
  Lua runtime failed: RuntimeError("[string \"yazi-plugin/src/lua.rs:50:13\"]:5: attempt to call a nil value (method 'children_add')\nstack traceback:\n\t[C]: in method 'children_add'\n\t[string \"yazi-plugin/src/lua.rs:50:13\"]:5: in main chunk")
```

I made to sure to follow the instructions at https://yazi-rs.github.io/docs/tips/#user-group-in-status exactly. My yazi version is `0.2.5`.

**Comment by sxyazi** [comment]
You need to upgrade your Yazi to the latest 0.3, https://github.com/sxyazi/yazi/releases/tag/v0.3.0

**Comment by fdw** [comment]
Thank you!
