### ISSUE TITLE
Add a new `load` DDS event

### ISSUE THREAD

**Issue by sxyazi** [sxyazi/yazi#1381]
### Please describe the problem you're trying to solve

I discussed with @Rolv-Apneseth on Discord about [adding a new `load` event](https://discord.com/channels/1136203602898194542/1223322656317898842/1224772948288864306) to make implementing [`bypass.yazi`](https://github.com/Rolv-Apneseth/bypass.yazi) easier. 

I just tried some changes in https://github.com/sxyazi/yazi/pull/1374 and found that a larger-scale refactor is needed to make it work. Specifically, the `yazi_dds` crate can't access the [`FolderStage`](https://github.com/sxyazi/yazi/blob/main/yazi-core/src/folder/stage.rs) in `yazi_core` because `yazi_dds` is a dependency of `yazi_core`, which would cause a circular dependency. 

So, I'll track it in this issue and implement it in the next target (0.3.1).

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

.

**Comment by Rolv-Apneseth** [comment]
That's great, thank you. Sounds tricky.

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1980
