### ISSUE TITLE
CI: Add automatic nightly build to the workflow

### ISSUE THREAD

**Issue by sxyazi** [sxyazi/yazi#1382]
### Please describe the problem you're trying to solve

This will allow users to download pre-built binaries from the release page instead of building them themselves. 

It will also benefit downstream projects like `yazi.nvim`, where automated testing in CI relies on the latest nightly version for some features, https://github.com/mikavilpas/yazi.nvim/issues/135#issuecomment-2205571261.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Add a workflow for nightly builds to the current GitHub Actions

**Comment by uznog** [comment]
I'll open a PR soon!

**Comment by sxyazi** [comment]
Done in https://github.com/sxyazi/yazi/pull/1397, thanks for contributing this feature @uznog!
