### ISSUE TITLE
The `yazi-fm` crate can't be published to crates.io

### ISSUE THREAD

**Issue by sxyazi** [sxyazi/yazi#1384]
### Please describe the problem you're trying to solve

In the just released Yazi 0.3, we used [an unpublished commit](https://github.com/notify-rs/notify/commit/96dec74316a93bed6eec9db177b233e6e017275e) from `notify-rs` to fix a serious [crash issue on Windows](https://github.com/sxyazi/yazi/issues/1320). 

Unfortunately, this prevents Yazi from being published on [crates.io](https://crates.io/), as crates.io requires that dependencies cannot be specified using a commit. 

When I attempted to publish the `yazi-fm` crate, I got the following error: 

```
❯ cargo publish -p yazi-core
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `notify` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```

This indicates that `yazi-core` cannot be published, which in turn prevents `yazi-fm` from being published since `yazi-core` is a required dependency.

This situation will persist until `notify` releases a new version with the fix (tracked by https://github.com/notify-rs/notify/issues/624). Please use other package managers to install Yazi for now, or wait until the issue is resolved.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

.

**Comment by obedm503** [comment]
For anyone else using cargo, installing from git still works.

```
cargo install --locked --git https://github.com/sxyazi/yazi.git yazi-fm yazi-cli
```

**Comment by uncenter** [comment]
> For anyone else using cargo, installing from git still works.
> 
> ```
> cargo install --locked --git https://github.com/sxyazi/yazi.git yazi-fm yazi-cli
> ```

Pretty sure you don't need the `yazi-fm yazi-cli` part now: https://github.com/sxyazi/yazi/blob/3fdbbfe915717f2ddd0ba891b4d19354e3136ff9/Cargo.toml#L4.
