### ISSUE TITLE
No status bar config snippit is not 3.x.x compatible

### ISSUE THREAD

**Issue by GNOMES** [sxyazi/yazi#1386]
### Please describe the problem you're trying to solve

The snippit on Yazi tips for no Status Bar is not working with 3.x.x: https://yazi-rs.github.io/docs/tips#no-status-bar

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Please update with new syntax

**Comment by sxyazi** [comment]
Please move this issue to https://github.com/yazi-rs/yazi-rs.github.io
