### ISSUE TITLE
Possible to run commands in series so tasks aren't pending?

### ISSUE THREAD

**Issue by theherk** [sxyazi/yazi#1387]
### Please describe the problem you're trying to solve

I am looking for a way to run multiple commands in one keybinding without the latter commands triggering the confirmation that tasks are pending.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I'd like to be able to use:

```toml
prepend_keymap = [{ on = ["e"], run = ["open", "quit"], desc = "edit" }]
```

to launch my application in my editor and have yazi close immediately. When running open with my EDITOR, the file is opened elsewhere so I don't need yazi to remain.

### Additional context

My usual workflow is the open the file in yazi, which actually opens it elsewhere outside yazi, then I hit `q` to close yazi and continue elsewhere. I'd rather have both these actions take place immediately. But when I do the above I get:

> 1 task running, sure to quit?

Which I am sure of, because the file is already opened elsewhere.

**Comment by sxyazi** [comment]
Have you set `orphan=true` for your opener?

> Keep the process running even if Yazi has exited, once specified, the process will be detached from the task scheduling system.

https://yazi-rs.github.io/docs/configuration/yazi#opener

**Comment by theherk** [comment]
I did just set this based on your feedback:

```toml
[opener]
edit = [{ run = 'editor "$@"', orphan = true }]
```

But this doesn't really help. The process being orphaned is not an issue. That is already taken care of by launching it in my listening nvim server. Which is why I can press `o` to open the file in my running nvim server, then immediately press `q` to close yazi. Then the file is still open in my editor, no problem. However, I'd like to in one keystroke open the file and close yazi.

**Comment by sxyazi** [comment]
What's the `editor`?

**Comment by sxyazi** [comment]
I can't reproduce it with:

```
# yazi.toml
[opener]
edit = [
  { run = 'code "$@"', orphan = true },
]
```

```
# keymap.toml
[manager]

prepend_keymap = [
  { on = "<C-o>", run = [ "open", "quit" ] },
]
```


https://github.com/user-attachments/assets/dd1702bc-6284-4974-975e-cbc3fd54c23e

```
❯ yazi -V
Yazi 0.3.0 (Homebrew 2024-08-01)
```

You're using the latest Yazi right?

**Comment by theherk** [comment]
Oh, actually I wasn't. I was still on 0.2.5 even though I remember seeing the 0.3.0 migration and knowing it was out. But yeah that fixes it. It actually looks like the popup still comes but it still closes straight away. Perfect. Thanks @sxyazi.
