### ISSUE TITLE
One `escape` key press to exit from filter/search

### ISSUE THREAD

**Issue by adriangalilea** [sxyazi/yazi#1389]
### Please describe the problem you're trying to solve

Currently you need to press <kbd>esc</kbd> twice to exit from filter/search popups

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

One <kbd>esc</kbd> key press to exit from filter/search.

### Additional context

I understand this is for character-wise and word-wise stuff, but I see no use of that on a file explorer, I rarely write more than a few words for matching, the <kbd>esc</kbd> thingy trips me very often, so I would love to be able to disable, so I can also free up some keys.

**Comment by sxyazi** [comment]
https://yazi-rs.github.io/docs/tips#close-input-by-esc is exactly what are you looking for

Closing as already exists
