### ISSUE TITLE
how to require file in plugin init.lua

### ISSUE THREAD

**Issue by zsytssk** [sxyazi/yazi#1394]
### Please describe the problem you're trying to solve

I want split my plugin file, and use require to connect them. but I can't find a way to make it work.

### Describe the solution you'd like

maybe just make require relative path work or provide some local variable as current plugin path. then I can use it to load other file...

**Comment by sxyazi** [comment]
You need to place it in the plugins directory, and it has to be a directory containing an `init.lua` file to work as a Lua module, see https://yazi-rs.github.io/docs/plugins/overview
