### ISSUE TITLE
DDS kind for switching tabs

### ISSUE THREAD

**Issue by Rolv-Apneseth** [sxyazi/yazi#1396]
### `yazi --debug` output

N/A

### Please describe the problem you're trying to solve

I had [an issue](https://github.com/Rolv-Apneseth/starship.yazi/issues/6) opened for `starship.yazi` that pointed out that it wasn't updating when switching between tabs. When I was looking into it, I couldn't find a way to run the plugin when the tabs change.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

If I'm not missing something, would it be possible to add a DDS kind when switching tabs so plugins can subscribe to that event?

### Additional context

I can give it a shot if you point me in the right direction (haven't touched the code in a while).

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by mikavilpas** [comment]
@Rolv-Apneseth I opened a PR that could help implement this. It currently sends the index of the tab that was switched to as an event.

Do you think this could be enough for implementing this feature in your plugin? I'm not sure if the current directory is available from yazi's APIs as long as we know the current tab.

**Comment by Rolv-Apneseth** [comment]
Oh nice, thanks. I believe the cwd is based on the current tab anyway but yeah seems to work perfectly for me, just subbed to the `tab-switch` event and it updates no problem.
