### ISSUE TITLE
Cannot install Yazi 0.3.0 on Debian 12

### ISSUE THREAD

**Issue by og900aero** [sxyazi/yazi#1401]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

st 0.9.1

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####
Error: TOML parse error at line 1038, column 1
     |
1038 | [[icon.conds]]
     | ^^^^^^^^^^^^^^
missing field `if`

```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

I cannot install yazi with cargo description. I run the following:
1. curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup update
2. cargo install --locked --git https://github.com/sxyazi/yazi.git yazi-fm yazi-cli

When I try run Yazi, or yazi -V, then I get error message:

```
Error: TOML parse error at line 1038, column 1
     |
1038 | [[icon.conds]]
     | ^^^^^^^^^^^^^^
missing field `if`
```

### Minimal reproducer

1. curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup update
2. cargo install --locked --git https://github.com/sxyazi/yazi.git yazi-fm yazi-cli

**Comment by Jelenkee** [comment]
Seems like your theme.toml is incorrect.

According to docs `if` is a required attribute
https://yazi-rs.github.io/docs/configuration/theme#icon

Can you show your ~/.config/yazi/theme.toml ?

**Comment by og900aero** [comment]
> Seems like your theme.toml is incorrect.
> 
> According to docs `if` is a required attribute https://yazi-rs.github.io/docs/configuration/theme#icon
> 
> Can you show your ~/.config/yazi/theme.toml ?

Thx, I got it. Now working.
