### ISSUE TITLE
Flavor's tmTheme overrides the syntect_theme specified in users' theme.toml

### ISSUE THREAD

**Issue by llanosrocas** [sxyazi/yazi#1407]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

kitty 0.35.2

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.3.0 (Homebrew 2024-08-01)
    Debug  : false
    OS     : macos-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : Some("/private/tmp/com.apple.launchd.kDXnrWHzpU/org.macosforge.xquartz:0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })
    block  : Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })

tmux
    TMUX   : false
    Version: No such file or directory (os error 2)

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : No such file or directory (os error 2)

```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

_Video demo is too big for github so please watch it here: https://streamable.com/esght4_

I'm using the [catppuccin-macchiato](https://github.com/yazi-rs/flavors/tree/main/catppuccin-macchiato.yazi) flavor as a base for my theme. I want to override the tmTheme by placing a `custom.tmTheme` file in the Yazi root folder and using the `syntect_theme` property to link it, as described [here](https://yazi-rs.github.io/docs/configuration/theme/#manager).

However, when I specify the custom `tmTheme` like this:
```toml
[manager]
syntect_theme = "~/.config/yazi/custom.tmTheme"
```
I can't see the changes in the preview because Yazi is still using the flavor's tmTheme file.

I’ve tried different options and file extensions, such as `.xml` and `.tmTheme`. However, if I delete the [tmtheme.xml](https://github.com/yazi-rs/flavors/blob/main/catppuccin-macchiato.yazi/tmtheme.xml) file from the flavor, it works as expected.

So, I believe that the flavor is somehow overriding the user's `syntect_theme`.

### Minimal reproducer
- N/A

### Anything else?

Please make the tmTheme configuration more consistent by using a single extension, either `.xml` or `.thTheme`. I understand that these are essentially the same file, but it was confusing at first when reading the documentation and searching for a solution in the source code.

**Comment by sxyazi** [comment]
This is expected - `syntect_theme` only works with themes, not with flavors. A flavor is considered a complete package, including both the Yazi theme itself and code highlighting. 

So, if you want to combine Catppuccin (for Yazi) with Onedark (for code highlighting), you should either create a new flavor or use `theme.toml` rather than `flavor.toml`.

As for why it started working after you removed the tmTheme from the flavor, it's because in the current implementation, when Yazi can't find that file, it falls back to the default ANSI colors, which are your terminal's theme colors, but this might change in the future.

I took a quick look at the docs, indeed the description isn't accurate. I'll create a PR to fix it later. Closing as it's working as expected.

**Comment by sxyazi** [comment]
> I'll create a PR to fix it later 

Done in https://github.com/yazi-rs/yazi-rs.github.io/commit/9363cf6bfb8b1b8c7f0578b9237f01e0ff466e4b
