### ISSUE TITLE
Support for grep and find

### ISSUE THREAD

**Issue by Jelenkee** [sxyazi/yazi#1410]
### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####

Yazi
    Version: 0.3.0 (VERGEN_IDEMPOTENT_OUTPUT 2024-08-03)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: X11

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0.0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("micro")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.0
    fd               : 10.1.0
    rg               : No such file or directory (os error 2)
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

</details>

### Please describe the problem you're trying to solve

Hi,
I wondered why `ripgrep` and `fd` are supported out of the box and `grep` and `find` are not though the latter are way more common.

Can you use them as a fallback when `ripgrep` or `fd` are not installed? Or add a config where one can choose which tool should be used for searchin files.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

`grep` and `find` are supported out of the box without an external plugin

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
I didn't quite understand what you meant, are you meaning that when a user runs `search rg` and doesn't have `rg` installed, it should fallback to using `grep` instead? If so, how would you handle the differences in their parameters? For example, if a user passes `search rg --args="--a --b"`, but `--a` and `--b` might only be valid with `rg`?

**Comment by Jelenkee** [comment]
Ok. Maybe the idea with directly fallbacking to another tool isn't the best solution.

Other ideas:
* add `search find`/`search grep` as valid commands
* add a more generic command (additionally to current ones) like `search files`/`search content` (names could be better) which looks if fd exists and if not, fallbacks to find
  * though these commands could not accept specific arguments

In the first place I don't want to add an additional tool to my machine for a basic feature like searching text in files when there is a tool installed OOTB on any Linux/BSD/MacOS which can be used for that use case (it might be a bit slower :wink: )

**Comment by sxyazi** [comment]
In this case, I don't think it's necessary to add them:

- Adding new `find` and `grep` commands would create overlapping functionality, and we'd have to explain the differences in the documentation, along with the dependencies needed for each command. Plus, we can't just say "fd is used for filename search" in the dependency list—we'd have to say "fd is used for `search fd`", which would be even more confusing.
- This would also block deeper integration of search features in the future. For example https://github.com/sxyazi/yazi/issues/1095, `rg` has a `--json` option to output results in JSON, which Yazi could parse to enable highlighting in the preview pane (similar to what `telescope.nvim` does). But I'm not sure if `grep` can output JSON, and if it can't, we'd have to find another solution, which would add unnecessary maintenance costs.
- Adding `find` and `grep` would only make things easier for Unix users, but they'd still be a problem for Windows users—or maybe even worse. `fd` and `rg` both offer Windows binaries, but I'm not sure there's a reliable way to install `grep` and `find` on Windows, which would introduce new cross-platform issues.
- As for adding new "search files / search content", I don't think implementing these features ourselves is a good idea. It would add unnecessary maintenance burden, and we'd probably end up with worse performance. Plus, we'd lose all the functionality provided by `fd` and `rg` already, leading to a bad user experience. Implementing a search tool isn't as simple as it sounds—here are some of the technical details behind `rg` (https://blog.burntsushi.net/ripgrep/), and after reading them, I got a headache.

For these reasons, I'm closing this issue.
