### ISSUE TITLE
No re-sort after mass name change

### ISSUE THREAD

**Issue by bertradio** [sxyazi/yazi#1418]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 32.3

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####


```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

When I select several filenames and change them. I then save and return to yazi. Unfortunately, the display does not re-sort to reflect new file order. I need to leave the directory and enter again to get a re-sort.

### Minimal reproducer

Select several files and select "r" to change the names. Change the names in a way that would change the sort order. Save and return.

### Anything else?

I suggest forcing a re-sort after a mass name change. Or at least providing a command to refresh/reload a directory.

**Comment by AnirudhG07** [comment]
I was wondering, we can just have "refresh" in the keybinding in the keybinding for re-sort. I tested and it works just fine. 
```toml
    { on = "r", run = ["rename --cursor=before_ext", "refresh"], desc = "Rename selected file(s)" },
```

This won't require any generalization of refreshing for every operation in src code. If the person wants, they can just adjust the keybindings.

**Comment by AnirudhG07** [comment]
The issue here i feel like is, after renaming, adding content to an empty file (which shows "Empty File") just after exiting EDITOR, etc. are simply that it is not reloaded, it takes on the previous value. Once you move away and see again, it recalculates the order/preview content, etc. and we see it fine.

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1691
