### ISSUE TITLE
[Smart Enter] Not working, yazi 0.3.0

### ISSUE THREAD

**Issue by ManuLinares** [sxyazi/yazi#1424]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

alacritty 0.13.2

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####

Yazi
    Version: 0.3.0 (Arch Linux 2024-08-06)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("alacritty", "tmux")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: X11

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0.0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("/usr/bin/micro")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : true
    Version: 3.4

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.1
    zoxide           : No such file or directory (os error 2)
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1

```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

https://yazi-rs.github.io/docs/tips/#smart-enter-enter-for-directory-open-for-file

Trying to open a directory via ENTER gives `Error: /home/user/directory is a directory and cannot be opened`

Adding the plugin listed in Tips gives the same behaviour.

### Minimal reproducer

1. Open `yazi`
2. hover a directory and press 'enter'.

### Anything else?

I expected one of the following.

- Or directory opens in the default filemanager
- Or yazi exits changing the pwd to the directory selected

**Comment by sxyazi** [comment]
`micro` doesn't support opening directories.

![screenshot-001941](https://github.com/user-attachments/assets/d868a919-9382-4e0a-8070-cced83bfab58)

You need to switch to a different directory opener. See https://yazi-rs.github.io/docs/configuration/yazi/#open

**Comment by ManuLinares** [comment]
> You need to switch to a different directory opener. See https://yazi-rs.github.io/docs/configuration/yazi/#open

Docs aren't very clear. May I ask you how can I achieve that?

Pressing enter on a directory should exit yazi and 'cd' intyo the dir.

**Comment by sxyazi** [comment]
> Pressing enter on a directory should exit yazi and 'cd' intyo the dir

I'm a bit confused. If you want to exit Yazi, you need to use the [`quit` command](https://yazi-rs.github.io/docs/configuration/keymap/#manager.quit), not the `open` command. The `open` command is for opening files within or outside of Yazi, not for exiting Yazi.

**Comment by ManuLinares** [comment]
> > Pressing enter on a directory should exit yazi and 'cd' intyo the dir
> 
> I'm a bit confused. If you want to exit Yazi, you need to use the [`quit` command](https://yazi-rs.github.io/docs/configuration/keymap/#manager.quit), not the `open` command. The `open` command is for opening files within or outside of Yazi, not for exiting Yazi.

What I'm tryint to achieve: When pressing 'enter' on a directory, yazi must exit and 'cd' into that directory.

I have no idea how to get this behaviour.
