### ISSUE TITLE
Yazi does not update the contents of a directory after it is deleted once

### ISSUE THREAD

**Issue by hankertrix** [sxyazi/yazi#1426]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty v0.35.2

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####

Yazi
    Version: 0.3.0 (Arch Linux 2024-08-06)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/hanker/.local/state/yazi" directory.

```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

It seems that Yazi does not update the contents of a deleted directory after it has been deleted once, even if a new directory with the same name is created and has content inside. Below is an example using an archive file.

Before extracting the archive:

![image](https://github.com/user-attachments/assets/a9a968fa-532a-4b28-9356-f3a722ecb63c)

After extracting the archive:

![image](https://github.com/user-attachments/assets/a3165d84-06d8-4955-bdc8-5b9f77c6706b)

Deleting the directory:

![image](https://github.com/user-attachments/assets/2bd18b8a-0c67-4e72-9de5-3f49d9a63911)

Extracting the archive again:

![image](https://github.com/user-attachments/assets/2aa89020-d7cd-4f7d-978a-39d6ecda8a8f)

### Minimal reproducer

1. Open Yazi
2. Navigate to an archive file.
3. Extract the archive.
4. Delete the directory containing the contents of the archive.
5. Extract the archive again.
6. The directory should be filled with the archive's contents, but is empty.

### Anything else?

The extraction program used to extract the archive is `p7zip`, which is the `7z` command.

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1434

**Comment by hankertrix** [comment]
#1434 does fix the issue! Thank you!
