### ISSUE TITLE
Error: TOML parse error at line 3, column

### ISSUE THREAD

**Issue by jeromefaria** [sxyazi/yazi#1432]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

zsh 5.9 (arm-apple-darwin21.3.0)

### `yazi --debug` output

```Shell
Error: TOML parse error at line 3, column 1
  |
3 | [[manager.keymap]]
  | ^^^^^^^^^^^^^^^^^^
missing field `run`
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

When I try to run yazi, i get the following output:
```bash
Error: TOML parse error at line 3, column 1
  |
3 | [[manager.keymap]]
  | ^^^^^^^^^^^^^^^^^^
missing field `run`
```

### Minimal reproducer

❮ yazi
Error: TOML parse error at line 3, column 1
  |
3 | [[manager.keymap]]
  | ^^^^^^^^^^^^^^^^^^
missing field `run`

### Anything else?

ProductName:            macOS
ProductVersion:         14.6
BuildVersion:           23G80

**Comment by t-ober** [comment]
exec has been replaced by run in newest release: https://github.com/sxyazi/yazi/issues/1046
just search and replace the instances across your configuration files

**Comment by sxyazi** [comment]
Yeah @t-ober is right, this is a breaking change in Yazi 0.3, see https://github.com/sxyazi/yazi/issues/1046
