### ISSUE TITLE
Can't open videos in v0.3 on Windows

### ISSUE THREAD

**Issue by AntoniosBarotsis** [sxyazi/yazi#1436]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Wezterm

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.0 (a9d2d9c 2024-08-07)
    Debug  : false
    OS     : windows-x86_64 (windows)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : None
    EDITOR             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "code \"%*\"", block: true, orphan: false, desc: "code", for_: None, spread: true })
    block  : Some(Opener { run: "code \"%*\"", block: true, orphan: false, desc: "code", for_: None, spread: true })

tmux
    TMUX   : false
    Version: program not found

Dependencies
    file             : 5.45
    ueberzugpp       : program not found
    ffmpegthumbnailer: program not found
    magick           : 7.1.1-36
    fzf              : 0.44.1
    fd               : 8.6.0
    rg               : 13.0.0
    chafa            : program not found
    zoxide           : 0.9.2
    7z               : 23.01
    7zz              : program not found
    jq               : 1.7.1
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Updating from `0.2.5` to `0.3` breaks opening any non-text files (in my case, videos). I don't seem to get any relevant error when pressing `s` or `<ENTER>` to open a file, I get the following errors for the various files in my folder:

```
  2024-08-07T20:00:23.746203Z ERROR yazi_plugin::utils::log: "spawn `ffmpegthumbnailer` command returns nil"
    at yazi-plugin\src\utils\log.rs:20

  2024-08-07T20:00:23.746524Z ERROR yazi_scheduler::prework::prework: Returned 0 when running preloader `video` with `path\to\file.mkv`
    at yazi-scheduler\src\prework\prework.rs:76
```

but nothing else.

### Minimal reproducer

I'm on Nu 0.91.0 with the following config:

```
[manager]
show_hidden = true

[opener]
edit = [
  { run = 'code "%*"', block = true },
]
play = [
  { run = 'nu -c "`<PATH TO VLC>` `%*` --one-instance"', orphan = true },
]
open = [
  { run = 'nu -c "start `%*`"', orphan = true },
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "image/*", use = "open" },
	{ mime = "video/*", use = "play" },
  { mime = "*/", use = [ "open", "edit" ] },
]
```

**Comment by sxyazi** [comment]
> nu -c "`<PATH TO VLC>` `%*` --one-instance"

I haven't used Nushell myself, what does the backtick (`) mean here? Is it used to escape parameters, similar to how double quotes are used in Bash?

**Comment by AntoniosBarotsis** [comment]
According to [this](https://www.nushell.sh/book/working_with_strings.html#backtick-quoted-strings), it is just to escape spaces essentially.

I tried this in WSL with the same config (swapped out the absolute path to vlc with just `vlc` after I installed it via apt) and that works fine. I'm not sure if it is a windows issue or a nu issue, I'll try to do some more digging.

**Comment by sxyazi** [comment]
Why did you add `nu -c` to it? Wouldn't it work if you just ran VLC's binary directly like

```sh
{ run = 'C:\path\to\vlc.exe %* --one-instance', orphan = true },
```

Yazi uses traditional quotes (`"`) to escape characters for parameters, so if Nushell uses a different syntax, I can't really say it will work.

**Comment by AntoniosBarotsis** [comment]
Ok that is a good point, I should've tried to just do it via CMD directly. The problem with that is that in CMD I need double quotes `"` for the paths to be escaped correctly (because of backslashes or spaces or both?) and yazi seems to remove them in its parsing when I try to print the command arguments [here](https://github.com/sxyazi/yazi/blob/407ad266e94c813e5de9439862590627396bdcba/yazi-scheduler/src/process/shell.rs#L52). Single quotes or backticks don't seem to work.

**Comment by AntoniosBarotsis** [comment]
Ok so, good point about just using CMD directly instead of invoking Nu again. After a bunch of digging in the source code I eventually figured the issue was that the command passed to `cmd /C` needs to be a string. Which like obviously *however* that meant I had to wrap everything in another set of double quotes

```js
play = [
  { run = '""C:\vlc.exe" %* --one-instance"', orphan = true },
]
```

so this eventually gets invoked as

```cmd
cmd.exe /C ""C:\vlc.exe" %* --one-instance"
```

The paths need to be quoted to escape them properly for cmd (I don't put quotes around %* because yazi does that for me).

I'm not sure if this is intended in the sense that, when I write my `yazi.toml` I instinctively write the command as if I was to type it into my own shell (in which case the extra quotes don't make sense). Now obviously that is not how it works internally but maybe it would make more sense to do the extra wrapping [here](https://github.com/sxyazi/yazi/blob/main/yazi-scheduler/src/process/shell.rs#L52). This could break existing users' configs but its a simple fix. Should I shoot a PR for this or what do you think 😅

**Comment by sxyazi** [comment]
That sounds like a bug - I'll look into it later

**Comment by sxyazi** [comment]
Hi, I just tested it, and it seems to work great for me. I don't need to add extra quotes, and it also works fine when the file names contain spaces:

```toml
[opener]
edit = [
  { run = 'nvim %*', block = true, desc = "nvim - rel path" },
  { run = 'C:\Users\ika\scoop\apps\neovim\0.10.1\bin\nvim.exe %*', block = true, desc = "nvim - abs path" },
]
```


https://github.com/user-attachments/assets/4e4c37b5-cfd6-4345-86c1-f40a7d441adf

**Comment by AntoniosBarotsis** [comment]
I'm not sure what's going on.

```toml
play = [
  { run = '""C:\Program Files\VideoLAN\VLC\vlc.exe" %* --one-instance"', orphan = true }, # works
  { run = '"C:\Program Files\VideoLAN\VLC\vlc.exe" %* --one-instance', orphan = true },   # works
  { run = 'C:\Program Files\VideoLAN\VLC\vlc.exe %* --one-instance', orphan = true },     # does nothing
]
```

Could this be a vlc issue instead?

**Comment by 8LWXpg** [comment]
Can confirm, looks like quoiting is done automatically for variables, but not executable path.

**Comment by aasril** [comment]
{ run = 'C:\Program Files\VideoLAN\VLC\vlc.exe %* --one-instance', orphan = true },     # does nothing

@AntoniosBarotsis The space in **Program Files* could be the problem here.

**Comment by sxyazi** [comment]
Hmm, I think this is expected behavior because I tested `cmd /C`, and it indeed requires escaping the executable path if it contains spaces. 

In this case, I don't think Yazi has any way to automatically escape it since it includes spaces, and Yazi can't distinguish between the part of the path that belongs to the executable and the part that's an argument.

**Comment by AntoniosBarotsis** [comment]
This is a bit of an annoying issue. On one hand, you're right, it doesn't make sense for yazi to need to figure this out. On the other hand, as a user I don't consciously think that my command is going to be passed to `cmd /C`, I just write it out as I would in my terminal.

[The docs](https://yazi-rs.github.io/docs/configuration/yazi#opener) do actually get it right, maybe we could just add a note for windows users to be careful with their string escapes?

I also think that such an issue should dump some error log either in the terminal or the log file, that was really the main issue for me, because I couldn't figure out what was going on. I could perhaps look into this when I find the time for it, what do you think? It looks like this is not the case right now because [orphan processes dump `stdout` to null](https://github.com/sxyazi/yazi/blob/58ba459b63a0ab004f210436b9abcc44974e28eb/yazi-scheduler/src/process/shell.rs#L18), is there a reason for this?

**Comment by AntoniosBarotsis** [comment]
I'll just close this then, thanks for the replies and the project itself!
