### ISSUE TITLE
Issue with extracting archives

### ISSUE THREAD

**Issue by f73** [sxyazi/yazi#1444]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

gnome terminal

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.0 (Arch Linux 2024-08-07)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("tmux-256color", "tmux")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Wayland

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-0")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : true
    Version: 3.4

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

I am not sure is it a bug, or something on my side. So, when extracting any archive (enter), in the bottom right status corner, there is indicator with: **_99%, 1 left_**. The archive get extracted, but when trying to exit yazi there is a message: **_1 task running, sure to quit? (y/N)_**

### Minimal reproducer

Select archive and press enter.

### Anything else?

![yazi](https://github.com/user-attachments/assets/ced74b80-6d0a-490f-93e7-4bfa913f7e7e)

**Comment by sxyazi** [comment]
Press "w" to open the task manager, then hit Enter on that task to see what the error is

**Comment by f73** [comment]
```
Cannot send message: Incompatible version (Ya 0.3.0 VERGEN_IDEMPOTENT_OUTPUT, Yazi 0.3.0 Arch Linux)
Exited with status code: 1
Process failed
```

**Comment by sxyazi** [comment]
This is because `ya` wasn't packaged correctly, its version must match Yazi's version exactly to ensure compatibility. 

Please report this issue to Arch Linux, or use the official prebuilt binaries of Yazi available at https://yazi-rs.github.io/docs/installation#official-binaries
