### ISSUE TITLE
Have a menu bar (in the style of gitui) showing the possible actions. 

### ISSUE THREAD

**Issue by jclopes** [sxyazi/yazi#1449]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.0 (Arch Linux 2024-08-07)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-1")
    DISPLAY         : Some(":1")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("helix")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : ExitStatus(unix_wait_status(32256)), "No version is set for command jq\nConsider adding one of the following versions in your config file at \njq 1.7\n"


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/joao/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

It's hard to know what you can do or how to do it.
Having a menu bar that shows you some common commands and how to get to the help screen.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I would copy the way gitui does it. showing a menu at the bottom of the screen.

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
Sorry, I don't want to implement it as a built-in feature because it conflicts with Yazi's status bar. Ideally, we should only include one bar at the bottom to maximize space efficiency. 

However, I'd love to see someone implement it as a plugin for those who really want a menu bar instead of a status bar - Yazi's plugin system already provides [a rich layout API](https://yazi-rs.github.io/docs/plugins/layout), with the capability to completely rewrite or extend it. A great example is https://github.com/imsi32/yatline.yazi, which significantly expands both the default header and footer.

Closing as not in the plan.
