### ISSUE TITLE
multiple openers for a single rule

### ISSUE THREAD

**Issue by Linus789** [sxyazi/yazi#145]
Would it be possible to add multiple openers for a rule? For example with
```toml
[opener]
text = [
	{ exec = 'nano "$1"', block = true, display_name = "Edit with nano" },
]
browser = [
	{ exec = 'chromium "$@"', display_name = "Open in Chromium" },
]

[open]
rules = [
	{ name = "*.html", use = ["browser", "text"] },
]
```
it would show
```
Open in Chromium
Edit with nano
```
as options.

This would reduce the overhead of duplicating entries.

**Comment by Linus789** [comment]
Would you accept a PR for this issue?

**Comment by sxyazi** [comment]
Of course! I really like this proposal and want to see it happen, just not get around to completing it...
