### ISSUE TITLE
bug(?): truncated modes labels

### ISSUE THREAD

**Issue by xfzv** [sxyazi/yazi#1453]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.35.2

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.0 (4150f40 2024-08-09)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("tty")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR} \"$@\"", block: true, orphan: false, desc: "Neovim", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR} \"$@\"", block: true, orphan: false, desc: "Neovim", for_: None, spread: true })

tmux
    TMUX   : false
    Version: No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-25
    fzf              : 0.53.0
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    7z               : 16.02
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/xfzv/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Not sure if it's a feature or a bug but I noticed that the modes labels in status bar are now truncated:

- left: `Yazi 0.3.0 (7a380c2 2024-08-01)`
- right: `Yazi 0.3.0 (4150f40 2024-08-09)`
![Untitled](https://github.com/user-attachments/assets/018540c7-3fe9-48ad-b032-63fb16a2f5ac)

### Minimal reproducer

Occurs without `~/.config/yazi` directory.

**Comment by sxyazi** [comment]
No, it's not a bug. I've made some adjustments to the status bar recently because I tried out Helix and really liked it. Its mode is displayed with just three letters instead of the full name, and I found that makes a lot of sense :)

![screenshot-001950](https://github.com/user-attachments/assets/02bdea31-e4b4-4ba7-9139-4ee2b3d0fb69)

**Comment by sxyazi** [comment]
No problem. By the way your colors look a bit off. Maybe you could apply a flavor to Yazi, https://github.com/yazi-rs/flavors
