### ISSUE TITLE
Return results from `cx.active.current.files` in the same order as configured in `sort_by`

### ISSUE THREAD

**Issue by ValdezFOmar** [sxyazi/yazi#1455]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.0 (Arch Linux 2024-08-07)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/bash")
    EDITOR             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : No such file or directory (os error 2)


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/omar/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

Im trying to get the list of files under the current directory in the same order as I'm viewing the files in yazi, but the files seem to be returned in a random order every time.

Using this plugin at `~/.config/lazy/plugins/repro.yazi/init.lua`:

```lua
local M = {}

local get_files = ya.sync(function()
    local files = cx.active.current.files
    local names = {}
    for i = 1, #files do
        names[i] = tostring(files[i].name)
    end
    return names
end)

function M.entry()
    local files = get_files()
    ya.notify {
        title = 'files',
        content = table.concat(files, '\n'),
        timeout = 10,
    }
end

return M
```

And using a keymap like this:

```toml
[[manager.append_keymap]]
on = '<C-l>'
run = 'plugin repro'
desc = 'Show files'
```

I get this result using `sort_by = 'natural'`, note that the results in the notification are in a different order from those in the middle column:

![image](https://github.com/user-attachments/assets/db598f40-3fe3-4548-9368-8ad7d874b476)

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Return the the list of current files in the same order as configured in `yazi.toml`. Alternatively, expose the functions to sort filenames under the global `ya`, maybe `ya.sort_natural`, `ya.sort_modified`, etc.

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by ValdezFOmar** [comment]
After experimenting a bit more, it seems that it works as expected when the `--sync` flag is used to call the plugin:

```toml
[[manager.append_keymap]]
on = '<C-l>'
run = 'plugin --sync repro'
desc = 'Show files'
```

Is this intended?

**Comment by ValdezFOmar** [comment]
Though this is still a problem, because then I can't use any of the async features (like the `Command` object), so I have to pick between async or receiving the files in the order that I want.

**Comment by sxyazi** [comment]
Thanks for the report! 

I can reproduce the issue, will create a PR to fix it.

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1457

**Comment by ValdezFOmar** [comment]
I can confirm that it works, thanks!
