### ISSUE TITLE
Exit select mode after finishing renaming the files.

### ISSUE THREAD

**Issue by TobisLee** [sxyazi/yazi#1459]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.0 (4150f401 2024-08-09)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-0")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/fish")
    EDITOR             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: 3.4

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.1
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/tlss/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

After renaming the files, I need to exit select mode with `<Esc>`. Should we consider exiting automatically?

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Exit select mode after finishing renaming the files.

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
> Exit select mode after finishing renaming the files.

What do you mean?

**Comment by TobisLee** [comment]
After renaming the files, these files will back to normal mode automatically, I should not press the extra `<Esc>` key.

For now, after renaming the files, the files looks like this.
![屏幕截图_20240810_172809](https://github.com/user-attachments/assets/ddf2c3f1-886c-4e73-9d47-e8ea0feb3753)

**Comment by sxyazi** [comment]
You want to de-select after bulk renaming right? Use this

```
{ on = 'r', run = [ "rename", "escape --select" ] }
```

Doc of `escape` command: https://yazi-rs.github.io/docs/configuration/keymap/#manager.escape

Closing as already supported.

**Comment by TobisLee** [comment]
It works. Thanks to the reply.
