### ISSUE TITLE
parquet

### ISSUE THREAD

**Issue by wybert** [sxyazi/yazi#1479]
### `yazi --debug` output

```Shell
WARNING: `exec` will be deprecated in the next major version v0.3 and replaced by `run`.

Please replace all `exec = ...` with `run = ...`, in your `yazi.toml` and `keymap.toml`.

---
Add `disable_exec_warn = true` to your `yazi.toml` under `[headsup]` to suppress this warning.


Yazi
    Version: 0.2.5 (Homebrew 2024-04-23)
    OS: macos-aarch64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect: Kitty

Adaptor
    Adaptor.matches: Kitty

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/opt/homebrew/bin/fish")
    EDITOR: Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.41\nmagic file from /usr/share/file/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "$EDITOR \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "$EDITOR \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/Users/kang/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

I am wondering if yazi could support parquet preview as table 
<img width="1395" alt="image" src="https://github.com/user-attachments/assets/5acbc8ea-c3e5-4526-b6dd-ed188c642664">

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

preview parquet as table like preview csv,
<img width="1443" alt="image" src="https://github.com/user-attachments/assets/ee9da7d1-c326-4c18-b1ef-cd937944b7d2">

not sure how to implemnt this, but duckdb could preview parquet very quick

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
No plans to have it built-in, as that would require pulling in an additional dependency, but you should be able to implement it as a custom previewer via https://github.com/chhantyal/parquet-cli or https://github.com/manojkarthick/pqrs

Doc https://yazi-rs.github.io/docs/plugins/overview#previewer
