### ISSUE TITLE
Glob pattern matching also includes children in filetype rules

### ISSUE THREAD

**Issue by GrzegorzKozub** [sxyazi/yazi#1481]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.35.2

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.0 (Arch Linux 2024-08-07)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("tmux-256color", "tmux")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-0")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "$EDITOR \"$@\"", block: true, orphan: false, desc: "Edit", for_: None, spread: true })
    block  : Some(Opener { run: "$EDITOR \"$@\"", block: true, orphan: false, desc: "Edit", for_: None, spread: true })

tmux
    TMUX   : true
    Version: 3.5

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/greg/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

Before yazi 0.3.0 I was able to use glob patterns `**/.?*` and `**/.*/` to change the color of the hidden files and directories, respectively. This did not alter the colors of the hidden directory contents.

On yazi 0.3.0 these glob patterns seem to also change the colors of all the contents across directory tree level, no matter if they are files or directories.

![image](https://github.com/user-attachments/assets/fc06bd97-1008-47bd-9861-9cdca0f28724)

This might be related to 681612f.

### Minimal reproducer

```toml
[filetype]
rules = [
  { name = "**/.?*", fg = "darkgray" },
  { name = "**/.*/", fg = "darkgray" },
]
```

### Anything else?

Maybe my patterns are incorrect but I gave them a try using compgen -G "**/.?*" and they seem to catch only the files wanted.

**Comment by sxyazi** [comment]
I can't reproduce it, it works for me - files and folders begin with `.` are all gray

![screenshot-001958](https://github.com/user-attachments/assets/477de68c-7360-4c07-b217-e9c44cf16b96)

**Comment by sxyazi** [comment]
Oh I get what you mean, will create a PR to fix it

**Comment by sxyazi** [comment]
With https://github.com/sxyazi/yazi/pull/1483, you can use `is="hidden"`

```
[filetype]
rules = [
  { name = "*", is = "hidden", fg = "darkgray" },
  { name = "*/", is = "hidden", fg = "darkgray" },
]
```

to achieve it

**Comment by GrzegorzKozub** [comment]
That. Was. Fast. Thank you!
