### ISSUE TITLE
Image preview is not work correctly in Tmux

### ISSUE THREAD

**Issue by dhay3** [sxyazi/yazi#1502]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

konsole 24.05.2

### `yazi --debug` output

On Konsole(Yakuake) with Tmux configuration is unset

```Shell
Yazi
    Version: 0.3.1 (99a3b3a 2024-08-16)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.1 (99a3b3a 2024-08-16)

Emulator
    Emulator.via_env: ("screen-256color", "tmux")
    Emulator.via_csi: Ok(Konsole)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-0")
    DISPLAY         : Some(":1")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("/usr/bin/vim")
    VISUAL             : Some("/usr/bin/vim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vim} \"${@}\"", block: true, orphan: false, desc: "Edit file in $EDITOR", for_: None, spread: false })
    block  : Some(Opener { run: "${EDITOR:-vim} \"${@}\"", block: true, orphan: false, desc: "Edit file in $EDITOR", for_: None, spread: false })

Multiplexers
    TMUX               : true
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.1
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

On Konsole(Yakuake) with Tmux configuration is set

```

Yazi
    Version: 0.3.1 (99a3b3a 2024-08-16)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.1 (99a3b3a 2024-08-16)

Emulator
    Emulator.via_env: ("xterm-256color", "tmux")
    Emulator.via_csi: Ok(Konsole)
    Emulator.detect : Konsole

Adapter
    Adapter.matches: Wayland

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-0")
    DISPLAY         : Some(":1")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("/usr/bin/vim")
    VISUAL             : Some("/usr/bin/vim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vim} \"${@}\"", block: true, orphan: false, desc: "Edit file in $EDITOR", for_: None, spread: false })
    block  : Some(Opener { run: "${EDITOR:-vim} \"${@}\"", block: true, orphan: false, desc: "Edit file in $EDITOR", for_: None, spread: false })

Multiplexers
    TMUX               : true
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.1
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Some preview image drift to left with some red square blocks in right panel on Konsole(Yakuake) which has opened a Tmux session.  However Kitty works correctly with Tmux. When the configuration of Tmux is not set which is followed by yazi's official docs.

```
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
```

On Konsole(Yakuake) with Tmux

Rendered with red square blocks
![image](https://github.com/user-attachments/assets/a894d2f9-ae3d-4a31-946c-e76807a0fe11)

On Kitty with Tmux

![image](https://github.com/user-attachments/assets/0ad88e7f-6a73-4373-899f-8a183d3ae8f1)

And when the configuration of Tmux is set and restart Tmux. Either Konsole(Yakuake) or Kitty do not show the image preview.

On Konsole(Yakuake) with Tmux

![image](https://github.com/user-attachments/assets/3297c24b-9f02-494b-bc5c-285a8494a40a)

On Kitty with Tmux

![image](https://github.com/user-attachments/assets/54ae6bd8-d27b-44d4-80c2-79bcbfaec4fe)

It dims the `Emulator.detect` is mess up for some reason.

### Minimal reproducer

1. add the following configuration in `~/.tmux.conf`

```
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
```

2. Browse images in yazi

**Comment by sxyazi** [comment]
This is because Konsole currently only correctly implements the old Kitty protocol, which doesn't work under tmux. 

There's nothing Yazi can do about this; we can only wait for Konsole to implement the new [Kitty unicode placeholders](https://sw.kovidgoyal.net/kitty/graphics-protocol/#unicode-placeholders) or fix the [bug in its Inline Images protocol implementation](https://bugs.kde.org/show_bug.cgi?id=456354) that can't properly erase images.

**Comment by sxyazi** [comment]
Regarding the mentioned issue with Kitty and tmux, please make sure that both Kitty and tmux are the latest official versions. Older versions of Kitty do not support displaying images in tmux.

**Comment by dhay3** [comment]
Sorry for the late reply, I use kitty instead now, everything works like a charm :)
