### ISSUE TITLE
Ranger like file/dir tagging

### ISSUE THREAD

**Issue by Muhammad95959** [sxyazi/yazi#1503]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.0 (Arch Linux 2024-08-14)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.0

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/muhammad/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

I'd like to be able to mark/tag files and directories

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

My suggestion is to add tagging mechanism like the one in the ranger screenshot below:-
![2024-08-16_19-34](https://github.com/user-attachments/assets/139cb0aa-f04a-4cd6-953e-a1496eeb83c5)

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
Sorry, there are no plans to build this feature in, as different users might have varying needs for tags/marks. For example, I personally need to share the same database with the tags provided by macOS, so Anirudh and I wrote this plugin: https://github.com/yazi-rs/plugins/tree/main/mactag.yazi.

I believe the tag feature in ranger is another possible implementation. Although I haven't actually used it, I'd love to see someone interested in that workflow implement it. It's not difficult, and the link above is a valid example. This way, we can have multiple options to maintain maximum flexibility.
