### ISSUE TITLE
Add an option when interactively opening a file

### ISSUE THREAD

**Issue by ricardoseriani** [sxyazi/yazi#1504]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.1 (4112bf4 2024-08-17)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.1 (4112bf4 2024-08-17)

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(WezTerm)
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: Some("tty")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("vim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.2a
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.40.1

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : 0.46.1
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 
    zoxide           : No such file or directory (os error 2)
    7z               : 16.02
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

### Please describe the problem you're trying to solve

There is a way to add an option when I try to interactively open a file with Ctrl + O ?

I tried following the https://yazi-rs.github.io/docs/configuration/yazi#open to add an option to open an .mp4 file with xdg-open or with VLC, but it replaced the default actions, like open with mpv, Show media info, Reveal and Show EXIF.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Add a way to append a new open rule then interactively opening a file.

### Additional context

 I don't know if this is a bug or really a missing feature, but if there is any way to already do this, please, let me known.

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by aasril** [comment]
Did you mean Shift+O to interactively open a selection? Because that's the default keymap anyway.

You can refer to this [preset](https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi.toml)

On the [play] section, you can list openers you want, in order you want them to show up.

**Comment by sxyazi** [comment]
> add an option to open an .mp4 file with xdg-open or with VLC, but it replaced the default actions, like open with mpv, Show media info, Reveal and Show EXIF


This is because the default Media uses two openers: "play" and "reveal":

https://github.com/sxyazi/yazi/blob/99a3b3a043502a32877148515d6992e0fa121137/yazi-config/preset/yazi.toml#L65-L66

 If you want your `mp4` rule to inherit these as well, you need to include them:

```
	{ name = "*.mp4", use = [ "your_opener", "play", "reveal" ] },
```

Closing as already supported

**Comment by ricardoseriani** [comment]
> > add an option to open an .mp4 file with xdg-open or with VLC, but it replaced the default actions, like open with mpv, Show media info, Reveal and Show EXIF
> 
> This is because the default Media uses two openers: "play" and "reveal":
> 
> https://github.com/sxyazi/yazi/blob/99a3b3a043502a32877148515d6992e0fa121137/yazi-config/preset/yazi.toml#L65-L66
> 
> If you want your `mp4` rule to inherit these as well, you need to include them:
> 
> ```
> 	{ name = "*.mp4", use = [ "your_opener", "play", "reveal" ] },
> ```
> 
> Closing as already supported

Yeah, something like that.
What I'm trying to achieve it's to add a new option for all files, like open with `xdg-open` in linux.

There is any way that I can do that and still keep the other default options?
