### ISSUE TITLE
Wide image doesn't take all available horizontal space in previewer when using a different aspect ratio

### ISSUE THREAD

**Issue by ValdezFOmar** [sxyazi/yazi#1506]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.35.2

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.1 (Arch Linux 2024-08-17)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.1 (Arch Linux 2024-08-17)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/bash")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : No such file or directory (os error 2)
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : No such file or directory (os error 2)
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

When previewing images with a greater width than its height, the image might not take all the available horizontal space. This only happens when using a different ratio in `yazi.toml`, but not when using the default value.

With default config:

![image](https://github.com/user-attachments/assets/8d444ffd-7a26-4dda-9b23-e6a18070bf92)

With custom ratio (notice the empty space to the right of the image):

![image](https://github.com/user-attachments/assets/4931b45f-3573-42cf-bd73-be21e8d8465e)

### Minimal reproducer

In `~/.config/yazi/yazi.toml`

```toml
# This is the configuration that I'm using, but any ratio 
# will work as long as the third panel has the greater width
[manager]
ratio = [1, 3, 4]
```

Download this image and preview it in yazi:

![Ultra-Wide-Angle-Panoramas-1](https://github.com/user-attachments/assets/334e880f-ddf8-433f-9ce7-25bed1042cd3)

**Comment by sxyazi** [comment]
Does https://yazi-rs.github.io/docs/image-preview#size help?

**Comment by ValdezFOmar** [comment]
Yes, it worked, I've should of read the docs with more care!
