### ISSUE TITLE
TUI frames are broken when used in zellij

### ISSUE THREAD

**Issue by beeb** [sxyazi/yazi#1508]
### What system are you running Yazi on?

Windows WSL

### What terminal are you running Yazi in?

alacritty 0.13.2

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.1 (Nixpkgs 2024-08-18)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.1 (Nixpkgs 2024-08-18)

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Unknown([Sixel]))
    Emulator.detect : Unknown([Sixel])

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : Some("wayland-0")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: true

Variables
    SHELL              : Some("/home/valentin/.nix-profile/bin/zsh")
    EDITOR             : Some("hx")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "yz-fp \"$0\"", block: false, orphan: false, desc: "Use yazi as file picker within helix", for_: None, spread: false })
    block  : None

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.2a
    ZELLIJ_SESSION_NAME: Some("circular-glockenspiel")
    Zellij version     : 0.40.1

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : No such file or directory (os error 2)


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/valentin/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Frames display is broken when used inside zellij 0.40.1

![image](https://github.com/user-attachments/assets/a02f9ae9-e57f-4d73-a759-4b120f1ae6ab)

### Minimal reproducer

I'm using the 'JetBrainsMono Nerd Font' font.

```console
$ zellij
$ yazi
```

**Comment by sxyazi** [comment]
This is a rendering error, please submit it to Zellij so their devs can investigate further, as we've received another report similar to this one https://github.com/sxyazi/yazi/issues/1149, although this is actually a terminal emulator bug, not a terminal multiplexer, but they function in the same way.

**Comment by beeb** [comment]
My bad, it happens also outside of zellij:

![image](https://github.com/user-attachments/assets/0dbaffa0-f3da-4174-84b0-5a4bd5baa315)


To do this, I opened yazi while the terminal window was full-screen, then resized the terminal window down.

**Comment by beeb** [comment]
Can you re-open @sxyazi ?

**Comment by beeb** [comment]
Submitted to alacritty https://github.com/alacritty/alacritty/issues/8136

**Comment by sxyazi** [comment]
> This would point to alacritty being the culprit it seems. Can you confirm?

I found these two issues, and it looks like they might also be related to ConPTY:

- https://github.com/alacritty/alacritty/issues/7758
- https://github.com/alacritty/alacritty/issues/7914

According to [this comment](https://github.com/alacritty/alacritty/issues/7792#issuecomment-1972693143), unlike WezTerm, Alacritty doesn't include the latest `conpty.dll` with each release but instead uses the system's default. So, you can try downloading and installing WezTerm to see if Alacritty will use the latest DLL to fix the issue, or you could try upgrading your system

**Comment by beeb** [comment]
I confirm that installing wezterm fixed the issue in alacritty!
