### ISSUE TITLE
Support more Git forges with `ya pack`

### ISSUE THREAD

**Issue by uncenter** [sxyazi/yazi#1509]
### `yazi --debug` output

```Shell
N/A
```

### Please describe the problem you're trying to solve

`ya pack` currently only supports GitHub. I tried to solve this in #1325, but gave up after it sat dormant and had conflicts. Mentioned in #1471 as well.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Keep the shorthand `ya pack -a user/repo:dir` syntax for GitHub, but support new Git hosts - arbitrary URLs probably won't work since the URL pattern isn't the same for all of them (GitHub and Gitee use `/tree/main/directory`, GitLab uses `-/tree/main/directory`, Gitea/Forgejo use `/src/branch/main/directory`, etc.). The aforementioned 4/5 Git hosts could be explicitly supported for now.

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
Added to the feature request list, closing in favor of that

**Comment by uncenter** [comment]
Closing issues and consolidating to a single feature request issue makes it super difficult for discoverability... also means that any conversation around development of this feature happens in a "closed issue"...
