### ISSUE TITLE
Support custom branches with `ya pack`

### ISSUE THREAD

**Issue by uncenter** [sxyazi/yazi#1510]
### `yazi --debug` output

```Shell
N/A
```

### Please describe the problem you're trying to solve

Mentioned in #1471, support for specifying a branch from which to install the plugin. Plugin authors may want to use branches to support upcoming/unreleased or older Yazi versions, or to test out features.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

`ya pack` already can track a `rev` (formerly `commit`) in package.toml, so it should just be a matter of parsing the branch (rev) from the CLI arg.

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
Added to the feature request list, closing in favor of that.

But note that, as I mentioned in https://github.com/sxyazi/yazi/issues/1471#issuecomment-2294850919, it might not end up happening as I still need to think about it more.
