### ISSUE TITLE
Support plugins in subdirectories with `ya pack`

### ISSUE THREAD

**Issue by uncenter** [sxyazi/yazi#1511]
### `yazi --debug` output

```Shell
N/A
```

### Please describe the problem you're trying to solve

It appears that `ya pack` can't support a plugin in a subdirectory of a repository. `ya pack -a "imsi32/yazi#plugins"` works (Yazi at least trys to install it before failing since the files aren't in the right places), but `ya pack -a "imsi32/yazi#plugins/yatline-catppuccin"` does not (fails with "Error: Invalid package `use`").

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Support for installing a plugin from a subdirectory of a repository with `ya pack`.

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
No, this was a deliberate design choice to only support up to one level of subdirectories because I don't want the `ya pack` command to become too complex. A long URL like `ya pack -a "imsi32/yazi#plugins/yatline-catppuccin"` doesn't align with the simplicity philosophy of `ya pack`, nor is it ergonomic.

**Comment by uncenter** [comment]
Supporting subdirectories isn't ergonomic? Monorepos aren't ergonomic? Why is Yazi so inflexible *on every possible instance* against users and extension authors? You've made it incredibly annoying to make flavors and have been totally unreceptive to feedback around how to improve that aspect, and now you are refusing to add a this basic feature? I encourage you to listen more to feedback from users and developers interested in Yazi, because right now this is seemingly very opinionated and closed off. Not a great environment for contributing either.

**Comment by drmikecrowe** [comment]
See https://github.com/yazi-rs/plugins/issues/16#issuecomment-2306833496 -- issue is not using the latest version

**Comment by uncenter** [comment]
Nope, I'm on the latest version and installing from a plugin from a non-root folder/subdirectory does not work. Try it yourself!

**Comment by drmikecrowe** [comment]
So is this the same issue as https://github.com/yazi-rs/plugins/issues/16 or something different?

**Comment by uncenter** [comment]
That was the correct format for 0.3.0, the `:` character is the new syntax introduced in #1471 and released in 0.3.1.
