### ISSUE TITLE
GitHub readme does not include homebrew instructions (E.g. for @google, @aws, other teams using macbooks)

### ISSUE THREAD

**Issue by jaanli** [sxyazi/yazi#1514]
### `yazi --debug` output

```Shell
https://yazi-rs.github.io/docs/installation#homebrew
```

### Please describe the problem you're trying to solve

Need to install easily.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

see above

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
Hey, the installation guide URL has already been added to the README:

https://github.com/sxyazi/yazi/blob/0f106b591c7be48508821313a6b2a9566f8dca62/README.md?plain=1#L29-L32

**Comment by jaanli** [comment]
> Hey, the installation guide URL has already been added to the README:
> 
> https://github.com/sxyazi/yazi/blob/0f106b591c7be48508821313a6b2a9566f8dca62/README.md?plain=1#L29-L32

Ah sorry I meant the actual home brew command - this should be in the README like in other repos, no?
