### ISSUE TITLE
Yazi slow / lags on basic operations

### ISSUE THREAD

**Issue by praharshbhatt** [sxyazi/yazi#1519]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.21.2

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.1 (VERGEN_IDEMPOTENT_OUTPUT 2024-08-18)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.1 (VERGEN_IDEMPOTENT_OUTPUT 2024-08-18)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/fish")
    EDITOR             : None
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.2a
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : No such file or directory (os error 2)
    fzf              : 0.29
    fd               : No such file or directory (os error 2)
    rg               : No such file or directory (os error 2)
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : 16.02
    7zz              : No such file or directory (os error 2)
    jq               : 1.6
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

# Introduction

I just intalled yazi using `cargo install`. Surprisingly, basic commands have been slow for some reason. I cannot reproduce this latency / lag on ranger / other gui file managers.

https://github.com/user-attachments/assets/c7ab5bde-4c71-4e7e-92e3-9300f0c9bef9

# Specs
CPU: 11th Gen Intel i7-11700F (16) @ 4.800GHz
GPU: NVIDIA GeForce RTX 3090
Memory: 63976MiB

### Minimal reproducer

1. Use Linux Mint
2. Install yazi using `cargo install --locked --git https://github.com/sxyazi/yazi.git yazi-fm yazi-cli`
3. run yazi with `yazi`

### Anything else?

`yazi.log` was empty.

**Comment by SolitudeSF** [comment]
Any reason you are running a 3 year old version of kitty?

**Comment by praharshbhatt** [comment]
@SolitudeSF seems like the pm has `0.21.2-1ubuntu0.22.04.1` as kitty's latest version. which is, infact too old.
re-running the same steps in konsole works well, so not a Yazi issue :)
