### ISSUE TITLE
support image display for `windows terminal`

### ISSUE THREAD

**Issue by echaya** [sxyazi/yazi#1522]
### `yazi --debug` output

```Shell
.
```

### Please describe the problem you're trying to solve

Hi, 

I have only discovered yazi today (From reddit) and fall in love with it immediately! 

Since `Windows terminal` is my daily drive, and per https://github.com/microsoft/terminal/issues/448, sixel is supported natively by `windows terminal`, can we please consider support image please? Thanks in advance!!!

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

support image view out of box for windows terminal

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
Please *do not* skip `yazi --debug`, as I won't have enough information to handle the issue without it - I need to know what image protocol Yazi detects for MS Terminal and whether MS Terminal returns the [correct DA1 response](https://vt100.net/docs/vt510-rm/DA1.html) to indicate that it supports Sixel.

**Comment by echaya** [comment]
Hi there, please see the debug info below

```

Yazi
    Version: 0.3.1 (4112bf4 2024-08-15)
    Debug  : false
    OS     : windows-x86_64 (windows)

Ya
    Version: 0.3.1 (4112bf4 2024-08-15)

Emulator
    Emulator.via_env: ("", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Chafa

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : None
    EDITOR             : None
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : Some("c:\\tools\\Scripts\\yazi_config")

Text Opener
    default: Some(Opener { run: "nvim \"%*\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })
    block  : Some(Opener { run: "nvim \"%*\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : program not found
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file             : 5.45
    ueberzugpp       : program not found
    ffmpegthumbnailer: program not found
    magick           : program not found
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : program not found
    zoxide           : 0.9.4
    7z               : program not found
    7zz              : program not found
    jq               : program not found


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "C:\\Users\\abcdef\\AppData\\Roaming\\yazi\\state" directory.


```

**Comment by sxyazi** [comment]
>     Emulator.via_csi: Ok(Unknown([]))

It seems that MS Terminal isn't returning any response that indicating supports Sixel. Can you confirm if your terminal supports Sixel? It looks like the PR you linked was merged very recently.

**Comment by echaya** [comment]
Seems you are right. I got overexcited =)

Can we keep this open. I'll revert back once it is available in the preview version. Thanks

**Comment by sxyazi** [comment]
I don't think there's any point in keeping it open since it's a feature that's already supported. 

As soon as MS Terminal supports Sixel and returns the correct response, Yazi will be able to recognize and use it. In other words, there's no additional work needed on Yazi's side.

**Comment by echaya** [comment]
Nice  - thanks for explaining

**Comment by sxyazi** [comment]
Of course if MS Terminal supports Sixel but you find it doesn't work with Yazi, feel free to create a new bug report anytime :)
