### ISSUE TITLE
Crashed immediately on macOS 10.13

### ISSUE THREAD

**Issue by hronro** [sxyazi/yazi#1523]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

Alacritty 0.13.2

### `yazi --debug` output

```Shell
dyld: cannot load 'yazi' (load command 0x80000034 is unknown)
fish: Job 1, './yazi  --debug' terminated by signal SIGABRT (Abort)
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Got this error when try to run it:

```
dyld: cannot load 'yazi' (load command 0x80000034 is unknown)
fish: Job 1, './yazi' terminated by signal SIGABRT (Abort)
```

### Minimal reproducer

Simply download the latest build from GitHub Releases and run it, it will crash.

**Comment by sxyazi** [comment]
This is because your macOS version is too old, and GitHub Actions' Xcode is no longer compatible with your system, please build it manually https://yazi-rs.github.io/docs/installation#build-from-source

**Comment by hronro** [comment]
It seems that can be solved by adding a simple environment variable `MACOSX_DEPLOYMENT_TARGET` when running `cargo build`, check [how Alacritty does](https://github.com/alacritty/alacritty/blob/5abb4b73937b17fe501b9ca20b602950f1218b96/Makefile#L40) as a reference.

It is OK for me to build it from source, but for people who are still using old OS like me,  it would be much more convenient if we can download Yazi from GitHub Releases directly.

**Comment by sxyazi** [comment]
Sounds good to me, would you like to raise a PR? Should be easy to fix:

https://github.com/sxyazi/yazi/blob/573ca5287fcc62c97ead4a2c9ee19815a40d9328/scripts/build.sh#L15
