### ISSUE TITLE
File names not quoted when using $@ in shell command

### ISSUE THREAD

**Issue by ArijanJ** [sxyazi/yazi#1524]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.32.2

### `yazi --debug` output

```Shell
N/A
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

When opening a file called for example "this is a file", running `shell --block --confirm 'nvim $@'` actually runs `nvim this is a file`, so files get opened called "this", "is", "a", and "file".

### Minimal reproducer

A binding to `shell --block --confirm 'nvim $@'` in keymap.toml illustrates this, but if you don't have nvim you can do `ls $@` instead.

```
{ on = [ "n" ], run = "shell --block --confirm 'nvim $@'", desc = "Open selected files in Neovim" },
``` 

### Anything else?

Should be pretty straightforward, I'll try fixing this later today but should there be an option to disable it or do we want it as the default?

**Comment by sxyazi** [comment]
This is expected behavior because in the shell, you do need to add quotes to escape `$@`, https://unix.stackexchange.com/questions/41571/what-is-the-difference-between-and/41595#41595

> Should be pretty straightforward, I'll try fixing this later today but should there be an option to disable it or do we want it as the default?

Do you mean writing a parser to escape `$@`? I don't think that's an easy task, as it would need to account for various nested shell constructs, like `sh -c 'sh -c "sh -c \"$@\""'`.

**Comment by ArijanJ** [comment]
You're correct, I completely forgot about having to quote "$@" and was expecting this to be the default behavior. 
I will PR an additional line in the documentation to warn about this later today, thank you
