### ISSUE TITLE
Can't open text file if the path contains a space

### ISSUE THREAD

**Issue by Tyarel8** [sxyazi/yazi#1526]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

wezterm 20240203-110809-5046fc22

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.1 (0f106b5 2024-08-20)
    Debug  : false
    OS     : windows-x86_64 (windows)

Ya
    Version: 0.3.1 (0f106b5 2024-08-20)

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : None
    EDITOR             : Some("hx")
    VISUAL             : None
    YAZI_FILE_ONE      : Some("C:\\Users\\<user>\\scoop\\apps\\git\\2.46.0\\usr\\bin\\file.exe")
    YAZI_CONFIG_HOME   : Some("C:\\Users\\<user>\\Sync\\config\\yazi")

Text Opener
    default: Some(Opener { run: "hx \"%*\"", block: true, orphan: false, desc: "hx", for_: None, spread: true })
    block  : Some(Opener { run: "hx \"%*\"", block: true, orphan: false, desc: "hx", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : program not found
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file             : 5.45
    ueberzugpp       : program not found
    ffmpegthumbnailer: program not found
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : program not found
    zoxide           : 0.9.4
    7z               : 24.08
    7zz              : program not found
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "C:\\Users\\<user>\\AppData\\Roaming\\yazi\\state" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

I have helix as the opener for editing text like this:
```toml
[opener]
edit = [{ run = 'hx "%*"', block = true, for = "windows" }]
```
and if I try to open a text file with a space in it's path it opens a blank file in readonly mode. If I open another buffer with helix it shows in the tab that the file that yazi tried to open included the `"` in the name, like `a b.txt"` instead of `a b.txt`, so that probably is the issue.

### Minimal reproducer

Add 
```toml
[opener]
edit = [{ run = 'hx "%*"', block = true, for = "windows" }]
```
to `yazi.toml` and press `o` to open a text file that contains a space in it's path, like `a b.txt`

### Anything else?

Shows file `a b.txt` with contents "hello world!"
![image](https://github.com/user-attachments/assets/4e6a37d4-0ec9-4b53-8e34-c7af79935695)
After opening, the file is empty with readonly and the tab is called `a b.txt"` (the scratch is just so that the tab name shows)
![image](https://github.com/user-attachments/assets/7b9c5052-24ae-4376-b49b-cf7329942ffb)

**Comment by sxyazi** [comment]
Try `hx %*` - `%*` is already the escaped file list, you don't need to escape it again

**Comment by Tyarel8** [comment]
Thanks, that worked. Maybe it would be a good idea to point out the difference between `%*` and `$@` in the [example](https://yazi-rs.github.io/docs/configuration/yazi#opener) if one is escaped and the other is not, because I copied the neovim example in there.

**Comment by Tyarel8** [comment]
I added a [pull request](https://github.com/yazi-rs/yazi-rs.github.io/pull/130) to the docs with an example using `%*` in windows.
