### ISSUE TITLE
/tmp/yazi directory ownership issue on multi-user Linux

### ISSUE THREAD

**Issue by Donjae-Wang** [sxyazi/yazi#1527]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

iTerm2 SSH

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.0 (7a380c2 2024-08-01)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: No such file or directory (os error 2)

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Iterm2)
    Emulator.detect : Iterm2

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: true

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("vim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None
    ZELLIJ_SESSION_NAME: None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX   : false
    Version: tmux 3.2a

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    7z               : No such file or directory (os error 2)
    7zz              : 24.08
    jq               : No such file or directory (os error 2)
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

There is a bug in yazi when used on multi-user Linux systems. The issue arises when the application creates the /tmp/yazi directory, which is generated with ownership tied to the user who first runs the command. This leads to permission issues when other users try to interact with or clear the cache, causing functionality problems.

The issue arose when I discovered that after restarting the system, only a specific user could batch rename files, and PDF previews were not working. After using "sudo yazi --clear-cache", I could use both functions as usual, but another user who was previously able to use these functions could no longer do so. I suspect this might be a permission issue with /tmp/yazi.

### Minimal reproducer

1. On a multi-user Linux system, log in as user `asd`.
2. Run the following command:  
   `sudo yazi --clear-cache`
3. Observe that the `/tmp/yazi` directory is created with ownership as user `asd`. 
4. `ll /tmp` shows `drwxr-xr-x 2 asd usr_grp 4.0K Aug 20 22:12 yazi` and other users can't write to the `/tmp/yazi` folder

**Comment by sxyazi** [comment]
Any idea how to fix it? 

I ran `ls /tmp` and it looks like all the subdirectories in `/tmp` are set to 755 or lower. If we change `/tmp/yazi` to 777, it might cause some security issues.

**Comment by igorepst** [comment]
Maybe you can create a directory with the suffix of UID

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1541

**Comment by TobisLee** [comment]
If I already have an old `/tmp/yazi` directory, I need to clean it up manually for now. Yazi will regenerate the iamge cache in the new directory, but I still have cached images in the old one. Can we simply rename the old `/tmp/yazi` directory to `/tmp/yazi-{uid}` for a single user?

**Comment by sxyazi** [comment]
No, any files under `/tmp/*` will automatically disappear after a reboot, that's not a big deal

**Comment by Donjae-Wang** [comment]
> Please try #1541

Thank you so much for fixing this bug
