### ISSUE TITLE
"line 1: open: command not found" when `open` on a folder

### ISSUE THREAD

**Issue by c02y** [sxyazi/yazi#153]
When I try to `Enter` on the folder, which is using `exec = "open"` (I know it is saying `Enter` is to open a file instead of a folder), it will make the open task into a background process, which is in error status, and when you try to investigate the task, it will say
```
: line 1: open: command not found
Exited with status code: 127
```

`yazi 0.1.4-1`
`Arch Linux`

Actually, what ranger does this: if it is a folder, `open` will cd into the folder, if it is a file, open the file, which a new command like `open_or_enter` to combine `open` and `enter` of yazi into one can be provided so we don't have to care about whether the item is a folder or file anymore.

https://github.com/sxyazi/yazi/assets/2135996/cd23693c-e18d-4563-b489-00aa2e2e09a3

**Comment by Linus789** [comment]
See https://github.com/sxyazi/yazi/issues/110.

**Comment by sxyazi** [comment]
> Actually, what ranger does this: if it is a folder, open will cd into the folder, if it is a file, open the file, which a new command like open_or_enter to combine open and enter of yazi into one can be provided so we don't have to care about whether the item is a folder or file anymore.

This is the expected behavior. Yazi intentionally separates `enter` from `open`, because Yazi will later integrate an archive feature, which treats archives as directories, and allows operations on files within them. 

An archive is a file, so it's openable; but it also enterable. So the user needs to choose their action.

**Comment by c02y** [comment]
Sorry, how can I change the `opener` part 
```
[opener]
folder = [
	{ exec = 'xdg-open "$@"', display_name = "Reveal in Finder" },
	{ exec = '$EDITOR "$@"' },
]
```
to `cd` into the selected dir within yazi instead of opening the folder with my file manager?

**Comment by sxyazi** [comment]
This is the rule for opening files used with the `open` command; you need to `enter` and `leave`.

Copied from [the docs](https://github.com/sxyazi/yazi/blob/main/config/docs/keymap.md):

> leave: Go back to the parent directory.
> enter: Enter the child directory.
> open: Open the selected files.

The default keybinding is the Vim keybinding of `h` and `l`:

https://github.com/sxyazi/yazi/blob/9c6b3c9d1d1763074341042ef0f74ab45bb56da1/config/preset/keymap.toml#L16-L17

**Comment by c02y** [comment]
OK, I thought `folder = [` in the beginning of that part is for folder.

So this is the problem, I have to use `enter` for folder and `open` for file separately. 

IMHO, archive is not worthy of sacrificing the convenience of one open command for both folder and file. Let's not worry about it for now, maybe we can rethink this after the archive's open/enter feature is implemented.

**Comment by sxyazi** [comment]
Apart from archive, I also have the need to "open" directories in the system file manager or terminal, and in such cases, I would perform an "open" action on a directory rather than "enter". I am unsure how to do it without the distinction between "open" and "enter".

**Comment by sxyazi** [comment]
There is a workaround to implement your need:

```toml
 { on = [ "<Enter>" ], exec = [ "enter", "open" ] }, 
```

Make sure you removed this line:

```diff
[open]
rules = [
-	{ name = "*/", use = "folder" },
]
```

Anyway, I'm currently investing time in developing Yazi's plugin system, which will allow users to write their own plugins to customize their behaviors.

**Comment by c02y** [comment]
It is not actual workaround, since it runs two commands, if the item is a folder, it will cd into it and run `open` the first item in it, if the first item in it is a folder, it will `open` the folder in my file manager, if it is a file, it will open it automatically.

No hurries.

**Comment by ManuLinares** [comment]
what is this "open" strange command? I always use xdg-open, my system is arch

**Comment by sxyazi** [comment]
@ManuLinares Seems you are not in this case, see https://github.com/sxyazi/yazi/issues/110#issuecomment-1706538851 should help you

**Comment by sxyazi** [comment]
> So as suggested, maybe a command like `open` should handle both folder and file which cd into the folder or open the file.

We've supported it now, see this tip https://yazi-rs.github.io/docs/tips/#smart-enter-enter-for-directory-open-for-file.

Note that Yazi main branch is currently required.
