### ISSUE TITLE
ueberzugpp shifts preview left

### ISSUE THREAD

**Issue by offeex** [sxyazi/yazi#1531]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

cool-retro-term / alacritty

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.1 (Arch Linux 2024-08-17)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.1 (Arch Linux 2024-08-17)

Emulator
    Emulator.via_env: ("xterm", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Wayland

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-1")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/fish")
    EDITOR             : Some("/usr/bin/vim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/offeex/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

well, the preview is self-explanatory, image is offset left. Don't have such an issue with wezterm
![image](https://github.com/user-attachments/assets/b5cb904e-20c8-428d-88a9-185d2d13164c)

### Minimal reproducer

install `ueberzugpp` and just try previewing any image on yazi (i'm using hyprland)

**Comment by sxyazi** [comment]
This is a bug with `ueberzugpp` itself, not Yazi. Please use `ueberzug_scale` and `ueberzug_offset` to compensate for it, https://yazi-rs.github.io/docs/configuration/yazi#preview.ueberzug_scale.

If you believe this is a bug with Yazi, please follow the instructions at https://yazi-rs.github.io/docs/image-preview#debug-ueberzug to try using `ueberzugpp` on its own. You can specify fixed values for `x` and `y`, like 5 for both, to see if the position is correct. If it is, please upload these files/info for me to investigate.
