### ISSUE TITLE
Files with binary breaking preview

### ISSUE THREAD

**Issue by AnirudhG07** [sxyazi/yazi#1546]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

Wezterm

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.1 (92112de 2024-08-22)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.1 (92112de 2024-08-22)

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(WezTerm)
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":1")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : No such file or directory (os error 2)
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/anirudhgupta/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

A file in random binary is messing the preview and yazi window.
[bug_preview_.webm](https://github.com/user-attachments/assets/c82b5b41-7517-4502-bb15-66c3c5bce351)
In the yazi.toml, emphasis on my preview for "applications/octet-stream" mime type.

### Minimal reproducer

1) In yazi.toml, put preview for "application/octet-stream" with "code".
2) now see a file with above mime type, full of binary and it will mess the preview.

### Anything else?

in the original yazi.toml, the above mime type was in `*` fallback, but i wanted to see `.zsh_history`, which `file` was showing as just `data`, so i manually changed it, then i discovered this issue.

**Comment by sxyazi** [comment]
You shouldn't use the `code` previewer to view binaries, as it's not designed for that purpose. If you need to preview binaries, consider using a plugin like `hexyl.yazi`: https://github.com/Reledia/hexyl.yazi. If your `.zsh_history` is recognized as binary by `file`, you can use the `name` rule to match it precisely.

That said, I'll create a PR later to fix the `code` previewer for binary previews. However, it'll only give users an error message to prompt them to switch previewers. I think that's better than breaking the screen, and I don't think there's a higher-performance or simpler way.

**Comment by AnirudhG07** [comment]
It is not just with above. Files with random chars also mess up.

https://github.com/user-attachments/assets/ec5a2c29-1b85-43b9-b247-cc5323fdd3f4

(ignore the line mode "custom") You can see the preview mess up for python files, having wrong chars present.

**Comment by sxyazi** [comment]
Can you send me these files for testing?

**Comment by AnirudhG07** [comment]
Okie, sent you on discord DM. not sharing publicly. Hope its fine.

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1550

**Comment by AnirudhG07** [comment]
Perfect! Thanks so much!!!
