### ISSUE TITLE
Make the builtin `extract` and `archive` plugins handle `*.tar` formats better

### ISSUE THREAD

**Issue by xfzv** [sxyazi/yazi#1548]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.35.2

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.1 (69c20d4 2024-08-24)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.1 (69c20d4 2024-08-24)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("tty")
    WAYLAND_DISPLAY : None
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-25
    fzf              : 0.53.0
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    7z               : 16.02
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/xfzv/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

When extracting a `tar.gz` archive that contains a single file in it (no directory):

```
 archive.tar.gz
└──  binary
```

with default `extract` opener

https://github.com/sxyazi/yazi/blob/69c20d4dd3df49b22d80b11d63b35e8a914475bb/yazi-config/preset/yazi.toml#L49

Here's what happens:

1. A directory named after the archive is created (`archive`)
2. An `archive.tar` file is created inside `archive` directory
3. After pressing `Enter` to extract the `archive.tar` file, another directory called `archive` is created
4. Inside this `archive` directory, we finally have `binary`
5. `binary` file permissions are not preserved (644, is actually 755)

The final file hierarchy structure:

```
 .
├──  archive                               # 1. first directory created
│   ├──  archive                           # 3. second directory created
│   │   └──  file                          # 4. binary
│   └──  archive.tar                       # 2. second archive created
├──  archive.tar.gz                        # 0. original archive
```

I'm aware this is the default `7z` behavior (can reproduce with `7z x archive.tar.gz`)
but this is really not convenient. With:

```console
% tar -xvz archive.tar.gz
```

the binary is directly extracted to the current directory and permissions are preserved.

Any chance the extract feature could be more optimized? In this case, `tar` is definitely more suitable than `7z`.

### Minimal reproducer

1. Download [this `tar.gz` file](https://github.com/sachaos/viddy/releases/download/v1.0.1/viddy-v1.0.1-linux-x86_64.tar.gz)
2. Without any `~/.config/yazi` directory, reproduce steps detailed in `Describe the bug` to extract the `tar.gz` archive and observe the final file structure
3. Now try the following instead:

```console
% tar -xvz viddy-v1.0.1-linux-x86_64.tar.gz
viddy

% ls -al viddy
-rwxr-xr-x 1 xfzv users 8.2M Aug 24 16:08 viddy

% lsd --tree
 .
├──  viddy
└──  viddy-v1.0.1-linux-x86_64.tar.gz
```

- The binary is extracted to the current directory
- Permissions (755) are preserved

**Comment by sxyazi** [comment]
> Any chance the extract feature could be more optimized? In this case, `tar` is definitely more suitable than `7z`.

I think this is possible, but I have a few questions/concerns:

- What about Windows users?
- Is tar available on all platforms (such as NixOS as well)? Do we need to add it to Yazi's dependency list?
- Can tar provide an efficient archive preview feature? We need to make sure that the content users preview matches the content that's ultimately extracted. 7zip only previews the outer structure, so if we use 7zip to preview tar extractions, it might confuse users.
- What if the user has only installed tar or 7zip (considering both extraction and preview)?

**Comment by veltza** [comment]
Windows 10 and 11 come with tar.

Links
* [The Windows Process Journey — tar.exe (BSD tar Archive Tool)](https://medium.com/@boutnaru/the-windows-process-journey-tar-exe-bsd-tar-archive-tool-d307a4412c46)
* [How to extract .tar.gz files on Windows 11](https://pureinfotech.com/extract-tar-gz-files-windows-11/)

**Comment by sxyazi** [comment]
Thanks for the info! I think it's worth a try. 

Is anyone interested in implementing it? If it's simple enough and doesn't add too much maintenance overhead (let's say <100 lines), I'd be open to accepting a PR. 

The code for the `extract` plugin is here: https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/plugins/extract.lua

**Comment by DirkFi** [comment]
Hi, @xfzv . 
Can you tell a bit more about steps to reproduce? I'm using Arch Linux and have deleted the `~/.config/yazi` to use the default extract opener. But heres what happened: I only gets a dir called `viddy-v1.0.1-linux-x86_64` with a file `viddy-v1.0.1-linux-x86_64.tar` in it. And the state in the right corner shows the task is processing 99%.
Check out here: [reproduce preview](https://github.com/user-attachments/assets/9575c7eb-1276-46cc-88ae-815922abf69b).

**Comment by DirkFi** [comment]
@xfzv 

I did not see any useful info in log file. My version is 0.3.1 and i also tried to install from the source code which was just now updated to 0.3.2 but still got similar results.

And, yes, I have p7zip installed and can run 7z command. Maybe I need to try another tarball.

BTW, how to open the task manager inside Yazi?

**Comment by DirkFi** [comment]
Fix in [PR1583](https://github.com/sxyazi/yazi/pull/1583).
