### ISSUE TITLE
feat: allow to change border type

### ISSUE THREAD

**Issue by Axlefublr** [sxyazi/yazi#1552]
In case this issue already exists, or this functionality already exists, I preemtively am sorry for wasting your time; I went through most of the docs and searched the issues, didn't find this.

I want to change the *type* of the borders used. You can already change the styles, which is great, but I really dislike the type. \
I believe yazi is built with ratatui? It provides `BorderType`, and I'm guessing it's the only one used (for stuff like input / select I mean)

The interface to configure that could be either just a direct option to pick out of the options `BorderType` gives (like, solid, double, thick iirc); Another option would be to let the user provide their own 6 / 8 characters to use for the border.

Personally all I need, is to be able to change all borders to solid; Maybe other users would want to change the border types per popup type (one type for input, another for select for example)

**Comment by sxyazi** [comment]
Sounds good! We could add a `type = "rounded",` field to the existing `border`:

https://github.com/sxyazi/yazi/blob/58ba459b63a0ab004f210436b9abcc44974e28eb/yazi-config/preset/theme.toml#L93

Do you want to give it a try?

**Comment by Axlefublr** [comment]
oooohh lovely! that makes a lot of sense to put the type field into the style, rather than a separate option!

**Comment by Axlefublr** [comment]
if by "giving it a try" you mean testing the feature - absolutely! if you mean trying to implement it, it'll be a while until I get the time to do that; still, ideas like this should be tracked in case someone is nice enough to add it themselves :3

**Comment by sxyazi** [comment]
Thanks! Please create a new type `BorderStyle` rather than adding it to the existent `Style` as it's a common one, maybe you can flatten the fields of `Style` into `BorderStyle` to keep the maximum maintainability, see https://serde.rs/attr-flatten.html

**Comment by ionnux** [comment]
how about the ability to add title to the border.

**Comment by Axlefublr** [comment]
why? there are already titles there. do you mean being able to change them?

**Comment by sxyazi** [comment]
Tracked by https://github.com/sxyazi/yazi/issues/51
