### ISSUE TITLE
Winget workflow fail

### ISSUE THREAD

**Issue by ChetdeJong** [sxyazi/yazi#1567]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

-

### `yazi --debug` output

```Shell
-
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

Workflow is failing due underlying library
https://github.com/sxyazi/yazi/actions/runs/10590625055/job/29346712872
`0: invalid Zip archive: No valid central directory found`
See: https://github.com/russellbanks/Komac/issues/770

For the time being can you possibly submit update manually? Or change workflow to use Windows instead, it seems to be working there.

### Minimal reproducer

`winget search yazi` currently shows 0.3.0

**Comment by sxyazi** [comment]
It looks like it's been broken for a while. Can someone help manually submit the latest version?

**Comment by ChetdeJong** [comment]
I tried to push update myself, let's see if it works
https://github.com/microsoft/winget-pkgs/pull/170527

**Comment by sxyazi** [comment]
It looks like that PR has been merged, thanks for your help! 🎉 

Let's close this issue then, hope upstream fix this problem in the next release.

**Comment by russellbanks** [comment]
Sorry about this issue - I've found the fix and will create a new update to komac with this :)
