### ISSUE TITLE
Does not open pdf

### ISSUE THREAD

**Issue by Dass99** [sxyazi/yazi#157]
i dont know if is a error or is a possible feature to you implement,  but will be great has this working.

**Comment by sxyazi** [comment]
> Does not open pdf

Are you referring to not being able to "open" the PDF file, or "preview" it?

If it's "preview," have you already installed the latest `poppler` as instructed in the README?

**Comment by Dass99** [comment]
i refer to be able to open the pdf file. when press w to see the tasks running seems they run an open command and the process being finished and exited with status code 127.
![20230915_22h10m46s_grim](https://github.com/sxyazi/yazi/assets/98425664/9c84bdc8-f
![20230915_22h12m34s_grim]

(https://github.com/sxyazi/yazi/assets/98425664/1d088e48-6a4c-4da3-809a-b35c9a0152dc)
55f-4dfd-9e35-66e5eb22e450)

**Comment by sxyazi** [comment]
See https://github.com/sxyazi/yazi/issues/110

**Comment by sxyazi** [comment]
Please reopen this issue if the problem persists, closing then
