### ISSUE TITLE
Add Multi-language support and translations

### ISSUE THREAD

**Issue by Kol9yN** [sxyazi/yazi#1578]
### `yazi --debug` output

```Shell
!
```

### Please describe the problem you're trying to solve

!

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

use PO and MO files maybe?

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
The prompt texts aren't hardcoded, you can change them as what you want freely in your `yazi.toml` even the positions:

https://github.com/sxyazi/yazi/blob/907ac09e341b941e53a9a550ee9345130ca932a9/yazi-config/preset/yazi.toml#L136-L197

Doc of `yazi.toml`: https://yazi-rs.github.io/docs/configuration/yazi

Closing as already supported

**Comment by Kol9yN** [comment]
I mean make it possible to translate it on many languages and make autodetection of system language!
