### ISSUE TITLE
Non-default hover background colors overwrite marker colors if no left manager column is visible

### ISSUE THREAD

**Issue by Brixy** [sxyazi/yazi#1584]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot version: 1.18.1

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.2 (907ac09 2024-08-31)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.2 (907ac09 2024-08-31)

Emulator
    Emulator.via_env: ("foot", "")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect : Foot

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("hx")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : 7.1.1-37
    fzf              : 0.54.3
    fd               : 10.2.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : No such file or directory (os error 2)
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

When using a two column layout without the left manager column, marker colors are overwritten by the hover colors, if the hover colors is _not_ the default color.

In the screenshot _all_ folders and files are `yank --cut`, but the marker color for `preset/` is not visible.

![yazi](https://github.com/user-attachments/assets/2c10ac42-a51e-4c74-a163-e1b85dc53326)

(If you use managers with the three column default layout, hover background colors and marker colors always play nicely together because marker colors are placed above the column border.)

### Minimal reproducer

Use this as your **only** config:

```
# yazi.toml
[manager]
ratio = [ 0, 4, 3 ]
```

In yazi:

```
C-a
```

and optionally `x` or `y` after selecting all files.

Thanks a lot for investigating this.

### Anything else?

Maybe, this issue will be addressed in #1228.

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1585

**Comment by Brixy** [comment]
Thanks so much. This works perfectly.
