### ISSUE TITLE
Yazi fails to refresh contents, any way to manual refresh?

### ISSUE THREAD

**Issue by Felipe-9** [sxyazi/yazi#1596]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

kitty 0.36.1

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.2 (Homebrew 2024-08-28)
    Debug  : false
    OS     : macos-aarch64 (unix)

Ya
    Version: 0.3.2 (Homebrew 2024-08-28)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-nvim} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-nvim} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-37
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Just like this issue #1356 im experiencing a bug where after i copy or move files around yazi fails to detect the new files, often happens when doing long operations like copying big files, i often find myself having to close and re-open yazi for the new files to show up.

It seems that the refresh command existed but its lost as `<C-r>` inverts selection instead of refreshing the window

### Minimal reproducer

Do an operation that change files in the current directory that takes some time, and notice that yazi fails to update the new files in the dir

**Comment by sxyazi** [comment]
`refresh` has never been added to the default key bindings, which I explained in https://github.com/sxyazi/yazi/issues/1356#issuecomment-2252454207, and `<C-r>` has always been used for reverse selection and that hasn't changed. If you need it, you'll have to add it yourself

**Comment by Felipe-9** [comment]
Oh i see, for some reason i mistook myself when reading your comment on that issue, thanks.

**Comment by sxyazi** [comment]
No, the `refresh` command only refreshes the file list and doesn't update the directory sizes. Currently, there's no way to refresh the directory sizes. This is a known issue, and there's an open issue for it here https://github.com/sxyazi/yazi/issues/842

**Comment by Felipe-9** [comment]
Ah i see, well then i guess i will wait for that issue to resolve. thanks!
