### ISSUE TITLE
Windows Terminal (Arch in WSL) mistaken for WezTerm

### ISSUE THREAD

**Issue by MarvinJWendt** [sxyazi/yazi#1611]
### What system are you running Yazi on?

Windows WSL

### What terminal are you running Yazi in?

Windows Terminal

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.2 (Arch Linux 2024-08-31)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.2 (Arch Linux 2024-08-31)

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Wayland

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : Some("wayland-0")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: true

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.40.1

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-38
    fzf              : 0.54.3
    fd               : 10.2.0
    rg               : 14.1.0
    chafa            : 1.15.0
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/main/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

Bug discovered in discussion previously. (https://github.com/sxyazi/yazi/discussions/1470#discussioncomment-10373055)

Yazi is mistaking the Windows Terminal for WezTerm. Yazi always detects either Wayland or X11, which is not available on my system (Windows Terminal with Arch in WSL). I do have some hacks in place in my WSL to make some tools work. It simulates a display, which sets the DISPLAY env var. There is no Wayland/X11 running, but some of those env variables are set.

Setting `DISPLAY` env var to empty:
![image](https://github.com/user-attachments/assets/2dd8b0c4-e4fc-4efd-83a4-8f4f25a5a8ee)

Setting `WAYLAND_DISPLAY` to empty string:
![image](https://github.com/user-attachments/assets/c171399b-89f9-45a7-b491-ff784ea26294)

Completely unsetting the env variables:
```
Adapter
    Adapter.matches: KittyOld

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY : None
    DISPLAY         : None
```

### Minimal reproducer

1. Windows Terminal with Arch Linux in WSL
2. Run `yazi --debug`
3. Wrong detection

### Anything else?

If you do not have access to a WSL instance, I would be happy to test nightlies for you.

**Comment by e82eric** [comment]
@MarvinJWendt I am wondering if it is getting more than one of the environment variables that it uses to detect the emulator and picking the non Windows Terminal one.

If you look at your environment variables in that shell do you see the WT_Session one?  And any others from this list?  https://github.com/sxyazi/yazi/blob/0cdaff98d0b3723caff63eebf1974e7907a43a2c/yazi-adapter/src/emulator.rs#L61

**Comment by MrDwarf7** [comment]
@MarvinJWendt Could you share some further details in terms of what you're hack/workarounds are for other applications? I've got almost the same setup (Using WSL(2) Arch in a Windows via Windows Terminal) and would like to see if I can reproduce this to have a better look into it.

**Comment by e82eric** [comment]
It might have to do with this issue where the WT_* environment variables don't get set when opening Windows Terminal as a default.  Any chance it works if you open the Windows Terminal app and then go into WSL2?

https://github.com/microsoft/terminal/issues/13006

**Comment by sxyazi** [comment]
With https://github.com/sxyazi/yazi/pull/1735 you should be able to get the Chafa work, please make sure you don't have `XDG_SESSION_TYPE` or `WAYLAND_DISPLAY` or `DISPLAY` set
