### ISSUE TITLE
ya gives 99 left in Void linux

### ISSUE THREAD

**Issue by bitterhalt** [sxyazi/yazi#1634]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot

### `yazi --debug` output

```Shell
yazi --debug output

Yazi
    Version: 0.3.2 (0.3.2_1 2024-08-29)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: No such file or directory (os error 2)

Emulator
    Emulator.via_env: ("foot", "")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect : Foot

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-1")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : No such file or directory (os error 2)
    rg               : 14.1.0
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : 24.08
    7zz              : 24.08
    jq               : 1.7.1


--------------------------------------------------
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

ya won't do anything

### Minimal reproducer

Type any ``ya`` command in shell and it only gives: "99 left"

### Anything else?

yazi --debug output

Yazi
    Version: 0.3.2 (0.3.2_1 2024-08-29)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: No such file or directory (os error 2)

Emulator
    Emulator.via_env: ("foot", "")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect : Foot

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY : Some("wayland-1")
    DISPLAY         : Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : No such file or directory (os error 2)
    rg               : 14.1.0
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : 24.08
    7zz              : 24.08
    jq               : 1.7.1

--------------------------------------------------

**Comment by sxyazi** [comment]
> Ya
>    Version: No such file or directory (os error 2)

It seems like your `ya` isn't in the PATH, have you installed it? It's a necessary dependency introduced in v0.3, see https://github.com/sxyazi/yazi/issues/1046#issuecomment-2255993749

**Comment by bitterhalt** [comment]
Oh, I see. I thought that ya comes with yazi. I build it by myself then and see how it goes. ;)

**Comment by sxyazi** [comment]
Did you install it via the system package manager? It looks like it's indeed missing there https://github.com/void-linux/void-packages/blob/master/srcpkgs/yazi/template, I'll file an issue to them later. 

Anyway, I am glad to see the problem solved

**Comment by bitterhalt** [comment]
> Did you install it via the system package manager? It looks like it's indeed missing there https://github.com/void-linux/void-packages/blob/master/srcpkgs/yazi/template, I'll file an issue to them later.
> 
> Anyway, I am glad to see the problem solved

Yes I installed it from xbps.
