### ISSUE TITLE
bulk rename no longer working?

### ISSUE THREAD

**Issue by ehula** [sxyazi/yazi#1641]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.36.1

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Nixpkgs 2024-09-04)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Nixpkgs 2024-09-04)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: Some("0f594732b063a90d44df8c5d402d658f27471dfe_1726348582_1455908278")
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/run/current-system/sw/bin/bash")
    EDITOR             : Some("kak")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "kitty kak $0", block: false, orphan: true, desc: "Edit", for_: None, spread: false })
    block  : Some(Opener { run: "exiftool \"$1\"; echo \"Press enter to exit\"; read _", block: true, orphan: false, desc: "Show EXIF", for_: None, spread: false })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-38
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : 24.08
    jq               : 1.7.1
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

Instead of opening my editor with all the selected filenames ready for editing, it run exiftool on /tmp/yazi-1000.

### Minimal reproducer

Select two files. Type 'r' to initiate bulk-rename.

**Comment by sxyazi** [comment]
> Text Opener
>    default: Some(Opener { run: "kitty kak $0", block: false, orphan: true, desc: "Edit", for_: None, spread: false })
>    block  : Some(Opener { run: "exiftool \"$1\"; echo \"Press enter to exit\"; read _", block: true, orphan: false, desc: "Show EXIF", for_: None, spread: false })


Bulk rename stores your selected file list in a txt file (with a mime-type of `text/plain`). So, if you want to open this txt file using an editor, you need to correctly set txt files to open with an editor, not `exiftool`.

See the default config how to get it done:

https://github.com/sxyazi/yazi/blob/49639aa34ca69fc72008dbae6a2ad033d888805f/yazi-config/preset/yazi.toml#L64

https://github.com/sxyazi/yazi/blob/49639aa34ca69fc72008dbae6a2ad033d888805f/yazi-config/preset/yazi.toml#L32-L37

Doc of `[opener]`: https://yazi-rs.github.io/docs/configuration/yazi#opener
