### ISSUE TITLE
toggle preview

### ISSUE THREAD

**Issue by Axlefublr** [sxyazi/yazi#1645]
I have searched issues, and haven't found this being mentioned; sorry if it has already been discussed.

I almost never want to see the preview: I use yazi in a netrw/oil.nvim style, however especially with *images*, having a preview is very helpful.

I would love to have an ability to toggle the preview! You can currently set the ratio, and that's *also* how you can disable the preview. I want to be able to set the ratio, but keep the preview disabled by default (via a config option; I don't suggest that to be the *actual* default); then I would be able to press a mapping to toggle it on / off.

I assume I can achieve this by writing a plugin (correct me if I'm wrong), but it felt to me like something obvious to have, and so I think it would be a good thing to add to core.

**Comment by sxyazi** [comment]
https://github.com/yazi-rs/plugins/tree/main/hide-preview.yazi is exactly what are you looking for

You can find more awesome plugins at https://yazi-rs.github.io/docs/resources

Closing as already exists

**Comment by Axlefublr** [comment]
thank you! missed that completely
