### ISSUE TITLE
[fd] with show_hidden to true, not showing git ignored files

### ISSUE THREAD

**Issue by Jonathanm10** [sxyazi/yazi#1655]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

iterm2

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Homebrew 2024-09-16)
    Debug  : false
    OS     : macos-aarch64 (unix)

Ya
    Version: 0.3.3 (Homebrew 2024-09-16)

Emulator
    Emulator.via_env: ("xterm-256color", "iTerm.app")
    Emulator.via_csi: Ok(Iterm2)
    Emulator.detect : Iterm2

Adapter
    Adapter.matches: Iip

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : None
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-38
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.5
    7z               : No such file or directory (os error 2)
    7zz              : 24.08
    jq               : 1.6
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Hi,

Even though I have the `show_hidden` parameter set to `true`, `fd` doesn't find git ignored files.

Sorry in advance if I misunderstood something.

### Minimal reproducer

1. Copy the repo yazi.toml file into ~/.config/yazi
2. Update the `show_hidden` to `true`
3. Run yazi
4. Type "s" and search for a gitignored file
5. No results

**Comment by sxyazi** [comment]
This is expected behavior, `show_hidden` literally refers to "hidden" files, while Git ignored files are "ignored".

Hidden and ignored are two different concepts in `fd`, controlled separately by `--no-hidden` and `--no-ignore`. When you set `show_hidden=true`, Yazi will only pass the former. 

If you want to pass `--no-ignore`, use `search --args="--no-ignore"`, doc of the `search` command https://yazi-rs.github.io/docs/configuration/keymap/#manager.search. Also see this related PR here https://github.com/sxyazi/yazi/pull/1043

**Comment by Jonathanm10** [comment]
Sorry, I looked for this but somehow missed that config. Thanks for taking time to respond. 
Have a great day!
