### ISSUE TITLE
Add the ability to display line mode on the left side of the pane.

### ISSUE THREAD

**Issue by ze0987** [sxyazi/yazi#1656]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Arch Linux 2024-09-16)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Arch Linux 2024-09-16)

Emulator
    Emulator.via_env: ("foot-extra", "")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect : Foot

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : Some("/run/user/1001/sway-ipc.1001.288373.sock")
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:=nvim} \"$@\"", block: true, orphan: false, desc: "Edit with nvim", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=nvim} \"$@\"", block: true, orphan: false, desc: "Edit with nvim", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.40.1

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-38
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.2
    zoxide           : 0.9.5
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

### Please describe the problem you're trying to solve

The current layout for displaying filenames with corresponding information on the opposite side of the pane may not be optimal on large, high res screens and tilling window managers.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

The ability to display line mode to the left of the filename would make eye tracking much easier in the above cases.

### Additional context

![yazi_layout](https://github.com/user-attachments/assets/d4cfd5ce-c93f-48e6-b365-1aae8d725a16)

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
With https://github.com/sxyazi/yazi/pull/1667, you can achieve it by overwriting the [`Current:render()` method](https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/components/current.lua#L26) with the following code:

```lua
-- ~/.config/yazi/init.lua
local current_render = Current.render
function Current:render()
  local t = current_render(self)
  if #t < 2 then
    return t
  end

  local area, width = t[1]:area(), t[2]:max_width()
  t[1] = t[1]:area(ui.Rect { x = area.x + width, y = area.y, w = math.max(0, area.w - width), h = area.h })
  t[2] = t[2]:align(ui.Paragraph.LEFT)
  return t
end
```

Set [`linemode`](https://yazi-rs.github.io/docs/configuration/yazi#manager.linemode) to `mtime`:

![screenshot-002015](https://github.com/user-attachments/assets/c431125c-5d2d-4066-8da2-15a9d739b7f6)

Set [`linemode`](https://yazi-rs.github.io/docs/configuration/yazi#manager.linemode) to `permissions`:

![screenshot-002016](https://github.com/user-attachments/assets/6c7fde64-89ca-4585-841e-7f7455425a99)

Set [`linemode`](https://yazi-rs.github.io/docs/configuration/yazi#manager.linemode) to `owner`:

![screenshot-002017](https://github.com/user-attachments/assets/d874eb40-14bd-4a92-bbdb-2960c3f25b56)

**Comment by ze0987** [comment]
Thank you! Is it possible to right align?

![y](https://github.com/user-attachments/assets/0a5af0ed-8580-4a42-9457-2fb8bb0e1afb)

**Comment by sxyazi** [comment]
It's possible, just a small change based on https://github.com/sxyazi/yazi/issues/1656#issuecomment-2364234167

```diff
-  t[2] = t[2]:align(ui.Paragraph.LEFT)
+  t[2] = t[2]:area(ui.Rect { x = area.x, y = area.y, w = math.min(width, area.w), h = area.h })
```

![screenshot-002020](https://github.com/user-attachments/assets/489f6f51-001b-490a-8af4-d7e7148502ca)

Yazi offers a rich layout API, allowing you to implement just about any functionality you want. Check out the layout API doc here: https://yazi-rs.github.io/docs/plugins/layout
