### ISSUE TITLE
Some keymap ("shift" character) does not work on Windows Terminal

### ISSUE THREAD

**Issue by ndtoan96** [sxyazi/yazi#166]
`~` or `?` in keymap config file does not work on Windows Terminal, instead we have to use `<S-~>` or `<S-?>`.

I have tracked down the issue: on Windows Terminal when I press `~`, crossterm returns key event with code `Char(~)` and SHIFT modifier, but with current implementation (https://github.com/sxyazi/yazi/blob/902c0942244f2e1753899ed0aa1d4faf5b01c7eb/config/src/keymap/key.rs#L58C7-L58C7), SHIFT is only enabled for uppercase characters.

Since I don't use linux or mac, I don't know how it behaves there. I'm not sure how to fix it.

**Comment by sxyazi** [comment]
Thanks for the report, I'll look into it!
