### ISSUE TITLE
Flavor not working with Windows 11

### ISSUE THREAD

**Issue by songlim327** [sxyazi/yazi#1662]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

cmd

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (7c445ce 2024-09-04)
    Debug  : false
    OS     : windows-x86_64 (windows)

Ya
    Version: 0.3.3 (7c445ce 2024-09-04)

Emulator
    Emulator.via_env: ("", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Chafa

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : None
    EDITOR             : None
    VISUAL             : None
    YAZI_FILE_ONE      : Some("C:\\Program Files\\Git\\usr\\bin\\file.exe")
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "code %*", block: false, orphan: true, desc: "code", for_: None, spread: true })
    block  : Some(Opener { run: "code -w %*", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : program not found
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file             : 5.45
    ueberzugpp       : program not found
    ffmpegthumbnailer: program not found
    magick           : program not found
    fzf              : program not found
    fd               : program not found
    rg               : program not found
    chafa            : program not found
    zoxide           : program not found
    7z               : 24.06
    7zz              : program not found
    jq               : program not found
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

I am using **yazi v0.3.3** in windows 11, in overall, the tool is working well, except for the flavors feature. It appears that yazi is able to read the config successfully (I tested this by inserting a random string to `use =` field in `theme.toml`, triggered an error as expected). However, the theme itself is not being applied.

![image](https://github.com/user-attachments/assets/c7200ea2-8ee4-456c-a056-44dbabb21c7d)

### Minimal reproducer

Below are the steps I had go through:

OS: Windows 11 Pro

1. Created a new directory `C:\Users\[REDACTED]\AppData\Roaming\yazi\config`
2. Installed the flavor: `ya pack -a yazi-rs/flavors:catppuccin-macchiato`
3. Created `C:\Users\[REDACTED]\AppData\Roaming\yazi\config\theme.toml`, the file content as below:

```theme.toml
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
use = "catppuccin-macchiato"
```

**Comment by sxyazi** [comment]
Based on your screenshot, this is exactly the effect after applying the Catppuccin-Macchiato flavor - the status bar's mode uses blue as the primary color and gray as the secondary color, see:

![screenshot-002014](https://github.com/user-attachments/assets/398f8b52-e3f4-49ff-9d28-f84ddaa7ee95)

Closing as it's the expected behavior of Catppuccin-Macchiato flavor.

**Comment by uncenter** [comment]
If you want the background / rest of Windows Terminal themed with Catppuccin, you'll need to set up https://github.com/catppuccin/windows-terminal.
