### ISSUE TITLE
cd into hovered directory 

### ISSUE THREAD

**Issue by DrVoidest** [sxyazi/yazi#1670]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Nixpkgs 2024-09-04)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Nixpkgs 2024-09-04)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: Some("0f594732b063a90d44df8c5d402d658f27471dfe_1726964397_440865075")
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/run/current-system/sw/bin/fish")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.40.1

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-38
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : No such file or directory (os error 2)
    7zz              : 24.08
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/neon/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

It would be very convent to have a keybinding to enter the currently hovered directory instead of cding all over the place. Example, say I was in /foo and open up yazi to go into /bar/apple instead of exiting yazi and doing cd /bar/apple I could just hit ctrl-enter, and it would cd be into the select directory. I don't know rust well enough currently to commit code for this, but thank you for taking the time to read this. 

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Any key bind to enter the hover directory, I could update the documentation for the key bind if it gets added to help. 

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
https://yazi-rs.github.io/docs/quick-start#shell-wrapper is exactly what are you looking for.

If you want to enter the hovered directory on exiting instead of the current working directory, you can simply re-bind the `q` from:

https://github.com/sxyazi/yazi/blob/631afd09ee22ec7cfb1453e13c546adfdeace487/yazi-config/preset/keymap.toml#L10

to 

```sh
{ on = "q", run = [ "enter", "quit" ] }
```

Doc of the `keymap.toml`: https://yazi-rs.github.io/docs/configuration/keymap/

Closing as already exists.

**Comment by DrVoidest** [comment]
Oh, thank you, sorry for wasting your time
