### ISSUE TITLE
Yazi fails to use provided CWD unless each path element is readable

### ISSUE THREAD

**Issue by kseistrup** [sxyazi/yazi#168]
My Linux box uses the [pam-tmpdir](https://tracker.debian.org/pkg/pam-tmpdir "PAM module for creating safe per-user temporary directories") PAM module for creating safer per-user temporary directories in `/tmp/user/$UID`.

If I `yazi /tmp/user/$UID` in order to see what I have in my personal temporary directory, `yazi` will stop at `/tmp` because `/tmp/user` has permissions 0711 (root:root) only. The `/tmp/user/$UID` directory has permissions 0700 and belongs to `$USER:$USER`, so it's prefectly visitable and RW'able, even if the parent directory isn't.

+ **Yazi**: 0.1-4
+ **Linux**: ArchLinux on x86_64

**Comment by sxyazi** [comment]
https://github.com/sxyazi/yazi/pull/172 should fix this issue, please give it a try!

**Comment by kseistrup** [comment]
Confirmed: The PR in #172 solves this issue. :+1:
