### ISSUE TITLE
parent cursor

### ISSUE THREAD

**Issue by SH-ke** [sxyazi/yazi#1694]
### `yazi --debug` output

```Shell
no error
```

### Please describe the problem you're trying to solve

i want to know is there any operations move the parent cursors like joshuto ?

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

is there any operations move the parent cursors like joshuto ?
  { keys = ["["], commands = ["parent_cursor_move_up"] },
  { keys = ["]"], commands = ["parent_cursor_move_down"] },

### Validations

- [X] I have searched the existing issues
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
See https://yazi-rs.github.io/docs/tips#parent-arrow

Closing as already exists

**Comment by SH-ke** [comment]
@sxyazi  thank you !!
