### ISSUE TITLE
Binary name detection for dependencies

### ISSUE THREAD

**Issue by sntp** [sxyazi/yazi#1697]
### `yazi --debug` output

```Shell
n/a
```

### Please describe the problem you're trying to solve

While installing and configuring Yazi on Ubuntu, I noticed that Yazi doesn't recognize the installed ImageMagick and fd packages on my system. The issue is that APT provides binaries with different names. For ImageMagick, Yazi expects the binary to be called `magick`, but on Ubuntu, it's called `convert`. Similarly, `fd` is named `fdfind`.

After briefly checking Yazi's source code, I found that hardcoded names are used for all utilities.

https://github.com/sxyazi/yazi/blob/3e4973dbbfa7d34a95b6005822db84db51ebddb7/yazi-boot/src/actions/debug.rs#L71-L81

https://github.com/sxyazi/yazi/blob/3e4973dbbfa7d34a95b6005822db84db51ebddb7/yazi-plugin/preset/plugins/magick.lua#L22-L33

This seems to be a common issue across various distributions and operating systems since program names don't always match.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Yazi should make its best effort to identify the correct binary name or allow plugin developers and users to configure it. There could be a registry for program names where developers and users can register the appropriate names for their systems.

For example, since dependency versions are printed in `debug.rs`, Yazi could come with a default registry:

```rust
let binaryNameRegistry = hashmap! {
  "magick" => hashmap! {
    "Ubuntu" => "convert",
    "Windows" => "magick.exe"
  },
  "fzf" => ...,
  "ffmpegthumbnailer" => ...
  ...
}
```

Then, plugin developers could add overrides like this:

```lua
-- allows to override, but if ImageMagick.exe is missing on the system, try to use magick.exe
local cmd = ya.resolve_binary("magick", { Mydistro = "mymagick", Windows ="ImageMagick.exe" })
```

Additionally, users could customize it for ad-hoc fixes:

```toml
[binaryNameRegistry.magick]
MyDistro = "my-magic"
```

This is just the first idea that came to mind.

### Validations

- [X] I have searched the existing issues/discussions
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
> For ImageMagick, Yazi expects the binary to be called `magick`, but on Ubuntu, it's called `convert`.

No, `convert` is a deprecated command, if you run `convert`, you'll see a warning telling you to use the new `magick` command instead:

```
❯ convert
WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"
```

Please make sure you're using the latest version of ImageMagick.

> Similarly, `fd` is named `fdfind`.

After a quick check, you're absolutely right - some systems call `fd` as `fdfind`, so introducing a name check makes sense. 

Would you like to raise a PR for it? Here's the code:

https://github.com/sxyazi/yazi/blob/3e4973dbbfa7d34a95b6005822db84db51ebddb7/yazi-plugin/src/external/fd.rs#L14-L17

**Comment by sntp** [comment]
> No, convert is a deprecated command, if you run convert, you'll see a warning telling you to use the new magick command instead:

Oh I see this in version 7. They still have version 6 in the repository.

```shell
❯ docker run --rm -it ubuntu:24.10

root@6b10945cccb4:/# apt update -qq && apt install imagemagick -y -qq

root@6b10945cccb4:/# magick
bash: magick: command not found

root@6b10945cccb4:/# convert
Version: ImageMagick 6.9.13-12 Q16 x86_64 18420 https://legacy.imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5) 
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png raw tiff webp wmf x xml zlib
Usage: convert-im6.q16 [options ...] file [ [options ...] file ...] [options ...] file
...
```

Do you think it's not worth creating an option to override the utility name and simply try known names in the code instead? There also an option to override `find` with environment variable: https://github.com/search?q=repo%3Asxyazi%2Fyazi+YAZI_FILE_ONE&type=code. How about introducing common variables for utilities?
