### ISSUE TITLE
scrolling limited to some height in yazi

### ISSUE THREAD

**Issue by AnirudhG07** [sxyazi/yazi#1699]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

WezTerm

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (7222e17 2024-09-20)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (7222e17 2024-09-20)

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(WezTerm)
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Iip

Desktop
    XDG_SESSION_TYPE           : Some("x11")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":2")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : true
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.55.0
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/anirudhgupta/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

When you are scrolling some file, it stop under small heights of TMUX preview.

[Screencast from 29-09-24 12:15:09 AM IST.webm](https://github.com/user-attachments/assets/6de75e00-7776-49ea-a30b-06eb0bebeedb)

### Minimal reproducer

Take any file, keep decreasing the height in TMUX, and you ll see that scrolling stops.

### Anything else?

Again, just discovered by chance. :D
Is it supposed to be like this? like is it intended or a bug?

**Comment by sxyazi** [comment]
Are you referring to the preview scroll being reset when the terminal size changes? If so, that's by design to simplify the design, assuming users won't frequently change their terminal window size during the preview.

**Comment by AnirudhG07** [comment]
Nono. I mean that when you the height is bigger, u r able to scroll down the preview.
But when height is small, u r not able to scroll down the preview.
I am not talking about preview being reset.

**Comment by sxyazi** [comment]
I can't reproduce it:


https://github.com/user-attachments/assets/c59179bf-5581-4dd3-9798-b1e6e1671608




Did you use any custom configs/plugins? Can you reproduce it with the default config (`mv ~/.config/yazi ~/.config/yazi-backup`)? 

Also I noticed you're not using the latest nightly version; can you reproduce it with the latest nightly?

**Comment by sxyazi** [comment]
Have you tried running it outside of tmux to see if it works? Also, are you using key scrolling or mouse scrolling? Could you check if the behavior changes with https://github.com/sxyazi/yazi/issues/1328#issuecomment-2379689321 ?

**Comment by AnirudhG07** [comment]
Inside of TMUX, "mouse scrolling" doesnt work. Keyboard works just fine.
Outside of TMUX, weirdly up mouse scrolling works, not downwards. Keyboard works just fine both direction.

Yes with the mentioned changes, it works perfectly inside and outside tmux.

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1736
