### ISSUE TITLE
Cannot see the icons on Mac

### ISSUE THREAD

**Issue by curioustolearn** [sxyazi/yazi#170]
Hi,

I installed Yazi using homebrew on Mac. I followed the installation instructions. For some reason all files and folders have a square box with question mark inside them. The icons are not showing correctly. Can anyone please help with what I need to check and what steps I may take to get this working. Really hoping to use Yazi. 

Thank you for creating Yazi.

**Comment by sxyazi** [comment]
Hi, you need to install the [Nerd Fonts](https://www.nerdfonts.com/) and set it up for your terminal.

**Comment by curioustolearn** [comment]
Thank you @sxyazi. I have installed the Nerd Fonts as per your instruction. Here is the message from my terminal

`❯ brew install --cask font-symbols-only-nerd-font
==> Downloading https://formulae.brew.sh/api/cask.jws.json
###################################################################################################################################### 100.0%
Warning: Not upgrading font-symbols-only-nerd-font, the latest version is already installed`

I am using Iterm2 on macOS Monterey and Fish shell. I see icons for various things in my terminal (such as rust crab, when I visit a rust project; I am using starfish). But when I open `yazi`, I just see the boxed with question marks inside them. 

Thank you.

**Comment by curioustolearn** [comment]
Solved! I had to choose `Use a different font for non-ASCII text` in Iterm2. When I selected the nerd font there, it fixed the issue.

Thanks again @sxyazi. Looking forward to using `yazi`. It looks really cool and is fast.

**Comment by curioustolearn** [comment]
Closing the issue since it is resolved! See the message above.
