### ISSUE TITLE
Content retains in the preview panel

### ISSUE THREAD

**Issue by TobisLee** [sxyazi/yazi#1702]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.36.4

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (3e4973db 2024-09-27)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (3e4973db 2024-09-27)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-0")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/fish")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.5
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : ExitStatus(unix_wait_status(32512)), "ueberzugpp: error while loading shared libraries: libfmt.so.10: cannot open shared object file: No such file or directory\n"
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-38
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.2
    zoxide           : 0.9.6
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/tlss/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

When I navigated to a specific file, then go to the parent folder, there are some characters retain in the preview panel.

![屏幕截图_20240929_205259](https://github.com/user-attachments/assets/25ce9a14-c082-4aaf-9111-530e08824441)

### Minimal reproducer

1. Navigate to the specific file.
2. Go to the parent folder.

Download the specific file here: https://bellard.org/ioccc_lena/img.h

**Comment by sxyazi** [comment]
I can't reproduce it using the steps you provided:

https://github.com/user-attachments/assets/95b1db99-00e2-42bf-ac94-371e84b85e83

Did you use any custom configs/plugins? Can you reproduce it with the default config (`mv ~/.config/yazi ~/.config/yazi-backup`)? 

Also I noticed you're not using the latest nightly version; can you reproduce it with the latest nightly?

Let me know if I missed any details for replicating it.

**Comment by TobisLee** [comment]
I add the following line in `yazi.toml` to see the preview
```toml
prepend_previewers = [
 { name = "*.h", run = "code" },
 { name = "*.c", run = "code" },
]
```

**Comment by sxyazi** [comment]
Why not use the default code rules?

https://github.com/sxyazi/yazi/blob/a7b9275c06cb05e9a5e9308c93e9a7dd39be479e/yazi-config/preset/yazi.toml#L109-L111

**Comment by TobisLee** [comment]
the `img.h` file is treated as a `data` type, not in the default rule.

**Comment by sxyazi** [comment]
I can reproduce it with your custom config, will investigate it further

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1704

**Comment by TobisLee** [comment]
Yeah, it works. Thanks.
