### ISSUE TITLE
Copy `.git` dir to network device failed

### ISSUE THREAD

**Issue by TobisLee** [sxyazi/yazi#1703]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.36.4

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (a7b9275 2024-09-29)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (3e4973db 2024-09-27)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-0")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/fish")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.5
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : ExitStatus(unix_wait_status(32512)), "ueberzugpp: error while loading shared libraries: libfmt.so.10: cannot open shared object file: No such file or directory\n"
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-38
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.2
    zoxide           : 0.9.6
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/tlss/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

I copied a git repository dir to a samba device, and yazi got stucked, it says permission denied. I canceled the task, then tried to delete the dir, yazi got stuck again, also says permission denied.

![屏幕截图_20240929_220550](https://github.com/user-attachments/assets/3ccbf2a2-67d2-47c9-a598-66a89d492427)

![屏幕截图_20240929_220432](https://github.com/user-attachments/assets/e01ec998-9d10-456d-822c-53ddc0728e78)

### Minimal reproducer

Download the zip file and unzip, copy the file to a samba device.

[pack.zip](https://github.com/user-attachments/files/17179512/pack.zip)

### Anything else?

I tried 3 times use yazi, all failed. Finally, I use dolphin to make things done.

**Comment by sxyazi** [comment]
Does it work if you call [`std::fs::copy()` function](https://doc.rust-lang.org/std/fs/fn.copy.html) directly in a Rust app? It's the API that Yazi uses to copy files.

**Comment by TobisLee** [comment]
Not work. Same `permission denied` Error

**Comment by sxyazi** [comment]
Does it need a different API for copying network files - I'm not familiar with that

Also, what if you're running with root permissions?

**Comment by TobisLee** [comment]
> Does it need a different API for copying network files - I'm not familiar with that
I don't think there is a different API for network device, since other files is successfully copied.

> Also, what if you're running with root permissions?
I run `sudo yazi`, the file is copied successfully.

**Comment by sxyazi** [comment]
That's weird, I'm not sure how to fix it since what Yazi does is just call `std::fs::copy()` to copy files, and the error is returned by the operating system, while `std::fs::copy()` itself isn't working at all.

This might be a Rust bug, have you tried the `copy` function from the standard libraries of other languages to see if they work?

**Comment by TobisLee** [comment]
I tested `fs::copy_file` in C++ and `shutil.copyfile` in Python, they all work fine. It seems like a Rust bug.

**Comment by TobisLee** [comment]
Since this issue is not related to yazi, I'll close this issue.

**Comment by sxyazi** [comment]
FYI there's a related issue https://github.com/sxyazi/yazi/issues/1775

**Comment by TobisLee** [comment]
Glad to see this fix, but I think fix it in yazi is a little bit weird. Can you make a PR to Rust and we can still use `fs::copy` in yazi?

**Comment by sxyazi** [comment]
It's hard for me to say Rust would accept this because failing to copy files when permissions can't be set seems like a deliberate choice. 

From Rust's perspective, copying a file **must** succeed in both permissions and content to be considered successful, even if the target filesystem doesn't support setting permissions. 

However, this clearly contradicts our practical experience, where we hope at least the file content can be copied successfully, even if setting permissions fails.

**Comment by TobisLee** [comment]
Make sense to me, thanks!
