### ISSUE TITLE
How to skip `y/N` on moving to trash

### ISSUE THREAD

**Issue by kklot** [sxyazi/yazi#171]
and keep it only for permanently delete files. I could not find the option in the documentation.

**Comment by sxyazi** [comment]
Hi, there's no such feature at the moment, but it seems easy to implement, I'll add it soon!

**Comment by kklot** [comment]
Thanks, that'd be great, I think the default asking confirmation is good, but this as an extra option for those who know what they want.

**Comment by sxyazi** [comment]
I made a new PR that should resolve this, please give it a try: https://github.com/sxyazi/yazi/pull/173

**Comment by kklot** [comment]
That's fast, works for me! one thing, would it be better to change it to `--no-confirm` instead of `--confirm` to avoid confusion?

**Comment by sxyazi** [comment]
Seems `confirm` is more in line with natural language? `confirm to remove` vs `not confirm to remove` 🤔

**Comment by kklot** [comment]
So currently when we change the keyboard to 
`--confirm`, what it does it no longer asking for confirmation before sending the file to trash right? So I was thinking, if you would normally type in a command line mode it would be like

```
yazi remove file --confirm # currently, reading this line means the opposite
yazi remove file --no-confirm # clearly meaning no confirm
```

**Comment by sxyazi** [comment]
Sounds good 👍🏻

I'd like to change `shell --confirm` along with it, since it's already in use I'd like to add a new option and leave the old one as deprecated, but it seems that `shell --no-confirm` causes confusion with the deprecation.

Any other names suggested?

**Comment by kklot** [comment]
[Like `rm`](https://manpages.ubuntu.com/manpages/trusty/man1/rm.1.html), maybe something like `--force` (not really) or `--non-interactive` (too long) 🤔

**Comment by sxyazi** [comment]
The new one has been changed to `force`, while the old shell command remains unchanged.
