### ISSUE TITLE
Use `git mv` to move and rename files

### ISSUE THREAD

**Issue by WvW-vOiDs** [sxyazi/yazi#1713]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Homebrew 2024-09-04)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Homebrew 2024-09-04)

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: X11

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : Some("wayland-0")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: true

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : None
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })
    block  : Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.2a
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : 0.55.0
    fd               : No such file or directory (os error 2)
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : No such file or directory (os error 2)
```

### Please describe the problem you're trying to solve

能否使用 `git mv` 移动和重命名文件?
Is it possible to use `git mv` to move and rename files?

我在yazi中移动和重命名了一些文件, 但不幸的是我后来才发现这是一个git仓库, 因此我不得不把他们重新改回原来的名字并移回原来的位置. 然后使用 `git mv` 重新做了一遍.
I moved and renamed some files in yazi, but unfortunately I later realized that the folder was a git repository. As a result, I had to revert the changes by restoring the files to their original names and locations. After that, I used `git mv` to perform the actions correctly.

也许有一些更好的方法?
Are there perhaps better methods to accomplish this more effectively?

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

使用 `git mv` 移动和重命名文件.
Use `git mv` to move and rename files.

### Additional context

我看到了最新的 git 插件可以显示 git status. 也许可以检测到是在 git 仓库中时将 `mv` 替换为 `git mv`, 我不知道这样简单的操作是否可行.
I saw that the latest [git plugin](https://github.com/yazi-rs/plugins/tree/74a837c6eafba59e22dc3d8d8ec630934580c70c/git.yazi) can display git status. Perhaps it could detect when you're in a git repository and replace `mv` with `git mv`. I'm not sure if such a simple operation is feasible.

### Validations

- [X] I have searched the existing issues/discussions
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
Sorry, there's no plan to include this feature, but you should be able to implement it easily through the plugin system. 

Basically, you just need to bind your custom plugin to `p`. In that plugin, you can access the list of all files copied or cut by users using [`cx.yanked`](https://yazi-rs.github.io/docs/plugins/types/#app-data.manager-yanked). You can check whether the current action is a copy or a cut with `cx.yanked.is_cut`, and then use [`Command()`](https://yazi-rs.github.io/docs/plugins/utils#command) to do `git mv` or `git cp` on them.

Doc of `cx.yanked`: https://yazi-rs.github.io/docs/plugins/types/#app-data.manager-yanked

Doc of `Command`: https://yazi-rs.github.io/docs/plugins/utils#command
