### ISSUE TITLE
Image preview doesn't work inside of tmux popup window

### ISSUE THREAD

**Issue by casprwang** [sxyazi/yazi#1724]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

wezterm 20240928-215536-a2f2c07a
kitty 0.36.4

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Homebrew 2024-09-04)
    Debug  : false
    OS     : macos-aarch64 (unix)

Ya
    Version: 0.3.3 (Homebrew 2024-09-04)

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(WezTerm)
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : true
    tmux version       : 3.5
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.40.1

Dependencies
    file             : 5.41
    ueberzugpp       : 2.9.2
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-38
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.4
    zoxide           : 0.9.6
    7z               : No such file or directory (os error 2)
    7zz              : 24.08
    jq               : 1.7.1


--------------------------------------------------
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

image previewer works in tmux but not in its popup window, it shows blank in wezterm.

### Minimal reproducer

cd into a folder with images then run the followings: 
```bash
# wezterm 
$ tmux
$ yazi # preview works 

$ tmux popup
$ yazi # preview doesn't show
```

### Anything else?
As mentioned, the preview is blank in wezterm's tmux popup winodow, but in kitty, the preview shows for one img and the preview doesn't change while selecting other files.

**Comment by sxyazi** [comment]
`tmux popup` is not a complete terminal environment; it doesn't support [passthrough](https://yazi-rs.github.io/docs/image-preview#tmux), which is necessary for rendering images. 

After you set `set -g allow-passthrough all` in your `tmux.conf`, you can verify it with `echo -e '\x1bPtmux;\x1b\x1b[>q\x1b\\'; cat`:

In `tmux`:

```rust
❯ echo -e '\x1bPtmux;\x1b\x1b[>q\x1b\\'; cat
^[P>|kitty(0.36.4)^[\
```

In `tmux popup`:

```rust
❯ echo -e '\x1bPtmux;\x1b\x1b[>q\x1b\\'; cat
// No output here, this means `passthrough` is not supported in `tmux popup`
```

Unfortunately, there's not much Yazi can do here, as this requires support on the `tmux` side. I suggest filing an issue to `tmux` to request their support.

Closing as not Yazi and nothing can be done here.

**Comment by casprwang** [comment]
that makes a lot of sense, thanks!
