### ISSUE TITLE
Permission denied (os error 13) on aarch64.

### ISSUE THREAD

**Issue by voronind-com** [sxyazi/yazi#1726]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Termux

### `yazi --debug` output

```Shell
$ yazi --debug

Yazi
    Version: 0.3.3 (Nixpkgs 2024-09-04)
    Debug  : false
    OS     : linux-aarch64 (unix)

Ya
    Version: 0.3.3 (Nixpkgs 2024-09-04)

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Err(Permission denied (os error 13))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Chafa

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : None
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "Text", for_: None, spread: true })
    block  : Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "Text", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.5
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-38
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.4
    zoxide           : 0.9.6
    7z               : No such file or directory (os error 2)
    7zz              : 24.08
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/data/data/com.termux.nix/files/home/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

When I try to run yazi, I get this error: `Error: Permission denied (os error 13)`. It used to work in the past on the same device/environment, but stopped working a couple months ago or so. I couldn't find any issues related to this. 

### Minimal reproducer

yazi

**Comment by sxyazi** [comment]
This is a bug in the `crossterm` crate used by Yazi, https://github.com/crossterm-rs/crossterm/issues/912

You can either use the [nightly version](https://yazi-rs.github.io/docs/installation#official-binaries) or the [Termux official Yazi package](https://github.com/termux/termux-packages/tree/master/packages/yazi), both of which have been fixed it. 

Closing as already been fixed in the latest main branch, nothing can be done here.

**Comment by sxyazi** [comment]
Also see https://github.com/termux/termux-packages/issues/21364

**Comment by voronind-com** [comment]
I use nixpkgs version, not termux package. Still, thanks for the info!

**Comment by sxyazi** [comment]
Yazi also provides [Nix flakes](https://yazi-rs.github.io/docs/installation#nix-flakes) and [Cachix binary cache](https://yazi-rs.github.io/docs/installation#cache) you can use
