### ISSUE TITLE
bug in yazi.toml 

### ISSUE THREAD

**Issue by sikos** [sxyazi/yazi#1727]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.36.4

### `yazi --debug` output

```Shell
$ yazi --debug
Error: TOML parse error at line 253, column 16
    |
253 | create_title = ["Create:", "Create (dir):"]
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
invalid type: sequence, expected a string
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

the sample configuration is incorrect:
https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi.toml#L142
updated to:
`create_title  = "Create:"`

### Minimal reproducer

use the configuration from https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi.toml

starting the yazi would fail

**Comment by sxyazi** [comment]
You should use the `shipped` branch, see https://yazi-rs.github.io/docs/configuration/overview
