### ISSUE TITLE
Clarification of quotes, double quotes, backticks inside plugins, and the $0, $@ and $? variables

### ISSUE THREAD

**Issue by vvatikiotis** [sxyazi/yazi#1728]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Homebrew 2024-09-04)
    Debug  : false
    OS     : macos-aarch64 (unix)

Ya
    Version: 0.3.3 (Homebrew 2024-09-04)

Emulator
    Emulator.via_env: ("tmux-256color", "tmux")
    Emulator.via_csi: Ok(Iterm2)
    Emulator.detect : Iterm2

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some("/private/tmp/com.apple.launchd.2P03Exb1Sk/org.xquartz:0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim blocking", for_: None, spread: true })
    block  : Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim blocking", for_: None, spread: true })

Multiplexers
    TMUX               : true
    tmux version       : 3.5
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-38
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.4
    zoxide           : 0.9.6
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/Users/vatikiot/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

Trying to get the value of current hovered file, using $0, inside a simple plugin.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

I have something like the following:

```lua
local function matches_or(str, patterns)
	for pattern in patterns:gmatch("[^|]+") do
		if str:find(pattern) then
			return true
		end
	end
	return false
end

return {
	entry = function(_, args)
		local block = args[1] and args[1] == "block"
		local extensions = "%.mp4$|%.avi$|%.mkv$|%.mpeg$"
		local filename = "`$0`"
		-- local filename = ya.target_family() == "windows" and " %*" or ' "$@"'
		if matches_or(filename, extensions) then
			local osascript_cmd = [[
        osascript -e 'tell application "Finder" to activate' -e 'tell application "Finder" to select POSIX file "]] .. filename .. [["' -e 'tell application "System Events" to keystroke "y" using {command down}'

      ]]

			ya.manager_emit("shell", {
				osascript_cmd,
				block = block,
				orphan = true,
				confirm = true,
			})
		else
			ya.manager_emit("shell", {
				"qlmanage -p " .. ' "$0"',
				block = block,
				orphan = true,
				confirm = true,
			})
		end
	end,
}
```

and I can't expand the filename, or absolute path, of the currently hovered file.

Lua newbee here, however I can't figure out how and when $0 gets expanded and which of quotes/double quotes/backticks I need to use.

Thanks!

Definitely not a bug or feature request, maybe a clarification in the documentation. Thanks again

### Validations

- [X] I have searched the existing issues/discussions
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
`"$0"` is only available in the `shell` command as it's a shell expander symbol, if you want to access the filename in your Lua script, here's an example https://github.com/yazi-rs/plugins/blob/74a837c6eafba59e22dc3d8d8ec630934580c70c/chmod.yazi/init.lua#L6-L8

**Comment by vvatikiotis** [comment]
Thanks for your help, made it into a plugin https://github.com/vvatikiotis/quicklook.yazi

Any comments would be greatly appreciated. Thank you for the yazi awesomeness!

**Comment by sxyazi** [comment]
Looks awesome, nice work! A few suggestions: 

- use [`Command`](https://yazi-rs.github.io/docs/plugins/utils/#command) instead of [`shell`](https://github.com/vvatikiotis/quicklook.yazi/blob/d1a97350371afb67e0854b9ada915d24bb3236f5/init.lua#L25-L30), because it will automatically escape special characters in filenames, you can see some examples at https://github.com/search?q=repo%3Ayazi-rs%2Fplugins%20Command&type=code; 
- do a `nil` check on [`hovered`](https://github.com/vvatikiotis/quicklook.yazi/blob/d1a97350371afb67e0854b9ada915d24bb3236f5/init.lua#L2), as it will be `nil` when the user isn't hovering over any files - i.e. the directory has no files.

**Comment by vvatikiotis** [comment]
I'll get to it, Thanks!

**Comment by sxyazi** [comment]
BTW `Readme.md` should be `README.md` (full-uppercased)
