### ISSUE TITLE
Ability to choose editor for bulk rename.

### ISSUE THREAD

**Issue by amano-kenji** [sxyazi/yazi#1739]
### Please describe the problem you're trying to solve

Bulk rename chooses the first available opener for `bulk.txt` with `text/plain` mime type as the editor.

I want to pick a different editor for bulkrename.

### Describe the solution you'd like

Add --editor option to `rename` command.

### Validations

- [X] I have searched the existing issues/discussions
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by amano-kenji** [comment]
I made bulkrename use a different editor by specifying a new open rule for `name="bulk.txt"`, but this is not documented.

And, this is not reliable when `bulk.txt` is a real file.

**Comment by sxyazi** [comment]
> And, this is not reliable when `bulk.txt` is a real file.

No, a normal file is always an absolute path; it can never just be `bulk.txt`, hence `bulk.txt` is always reliable.

**Comment by sxyazi** [comment]
> but this is not documented

Done in https://github.com/yazi-rs/yazi-rs.github.io/commit/1c1671b9cdbf4d09b0aa958a5441a44d200af8e9
