### ISSUE TITLE
Tmux - Trailing Pixels after imagen preview

### ISSUE THREAD

**Issue by BearDad** [sxyazi/yazi#1750]
### What system are you running Yazi on?

Windows WSL

### What terminal are you running Yazi in?

Win Term Preview 

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Homebrew 2024-10-08)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Homebrew 2024-10-08)

Emulator
    Emulator.via_env: ("xterm-256color", "tmux")
    Emulator.via_csi: Ok(Unknown([Sixel]))
    Emulator.detect : Unknown([Sixel])

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : Some("wayland-0")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: true

Variables
    SHELL              : Some("/usr/bin/fish")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : true
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : 0.44.1
    fd               : No such file or directory (os error 2)
    rg               : 14.1.0
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.3
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : 1.7
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

when using tmux the image preview leaves a trail of pixels behind which is pretty annoying and it does not happen outside of tmux

### Minimal reproducer

i open tmux 
I open yazi to search for a pdf or img 
the img\pdf shows a trail behind it 
it does not happen outside of tmux
tmux.conf has the command stated in documentation:
![image](https://github.com/user-attachments/assets/9809fb86-5bf3-4973-be0a-23cd47cb19c2)
this is what yazi looks like: 
![image](https://github.com/user-attachments/assets/b9947d2d-6629-40fa-94e7-9175ec6a1a5d)

### Anything else?

[yazi.log](https://github.com/user-attachments/files/17317797/yazi.log)

**Comment by sxyazi** [comment]
The Windows terminal you're using only supports Sixel, since you're running Yazi inside `tmux`, your `tmux` also needs to support Sixel. 

Please make sure to pass `--enable-sixel` when building `tmux`, as it is disabled by default. You can verify this through https://github.com/tmux/tmux/issues/4104.

**Comment by sxyazi** [comment]
Added more info to the docs https://github.com/yazi-rs/yazi-rs.github.io/commit/028cb61a3646012cd8a840c839cabe6c79af3ae4
