### ISSUE TITLE
A keymap to restart yazi?

### ISSUE THREAD

**Issue by YousufSSyed** [sxyazi/yazi#1757]
### Please describe the problem you're trying to solve

I want to be able to restart yazi without quitting and entering `yazi`, when changing my config.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

A keymap or command to restart yazi

- [X] I have searched the existing issues/discussions
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
I don't think a process has the ability to restart itself. All processes work this way; you always need an external process to run it, which could be your parent process like a shell.
