### ISSUE TITLE
key 'o' should enter to the directory instead of opening it with $EDITOR

### ISSUE THREAD

**Issue by mrlogick** [sxyazi/yazi#1758]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (VERGEN_IDEMPOTENT_OUTPUT 2024-10-09)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: No such file or directory (os error 2)

Emulator
    Emulator.via_env: ("alacritty", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Wayland

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : Some("/run/user/1000/sway-ipc.1000.1139.sock")
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("hx")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-25
    fzf              : 0.54.3
    fd               : No such file or directory (os error 2)
    rg               : 14.1.1
    chafa            : 1.12.5
    zoxide           : 0.9.4
    7z               : 16.02
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/mrlogick/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

I'm using the default behaviour, not the "smart enter".
When I press many times the key `l` I often arrive to the end of subdirectories: there are no more directories to enter in, but there are some files. To open files I need to use `o`, not `l`, so it's safe to just press `l` few times more: I will simply remain in the last subdirectory. This is good, I think.
Sometimes, when I'm too fast pressing many keys `hjkl` and `o`, I think I'm arrived to the end of subdirectories, and so I press `o` to open the first file; but I'm in fact on the directory selected containing the file I want to open. Pressing `o` on the directory opens the directory with `$EDITOR`. I usually never want to do that. I would like to just press `o` and "enter" to the directory inside yazi. So I can press an other `o` to open the files inside. (Otherwise I am forced to close my editor every time i miss my keys).

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I would like to map the key 'o' so that it enters inside the directory if a direcotory is selected, and opens the file if a file is selected.

Inside yazi.toml, I'd like to change this:
```
[open]
rules = [
  ...
  { name = "*/", use = [ "edit", "open", "reveal" ] },
  ...
]
```

to this:
```
[open]
rules = [
  ...
  { name = "*/", use = [ "enter", "open", "reveal" ] },
  ...
]
```

But 'enter' doesn't seem to exist.
Is it possible to do it in an other way?

### Validations

- [X] I have searched the existing issues/discussions
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
> I would like to map the key 'o' so that it enters inside the directory if a direcotory is selected, and opens the file if a file is selected.

Smart enter is exactly what are you looking for, https://yazi-rs.github.io/docs/tips#smart-enter, you just need to bind `o` instead of `l` to it.

```
[[manager.prepend_keymap]]
on   = "o"
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

```

Closing as already exists

**Comment by kackerx** [comment]
awsome! 这就是我想要的, 使用enter来进入目录和打开文件, 符合我的直觉, thinks
