### ISSUE TITLE
Kitty won´t close window after exiting yazi if an orphaned mpv task is running

### ISSUE THREAD

**Issue by jagaimoworks** [sxyazi/yazi#1764]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.36.4

### `yazi --debug` output

```Shell
❯ yazi --debug

Yazi
    Version: 0.3.3 (da1b236 2024-10-11)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (da1b236 2024-10-11)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kgp

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: Some("b65773bea9b912a41cfcbc789fb2e60a07e3d0c1_1728652043_1885625831")
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("/usr/bin/nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.5a
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-39
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.6
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

Kitty won´t close window after exiting yazi if an orphaned mpv task is running until mpv itself is closed.
When trying to kill kitty (hyprland killactive in my case) it tells you that yazi is still running.

Other terminals like alacritty, wezterm and foot just close the window and keep mpv running.

### Minimal reproducer

1. `kitty yazi`
2. open a .mkv file with mpv (default config opens it with `orphan=true`
3. quit yazi with `q`
4. kitty shows an emtpy window (cursor but no prompt) until mpv is closed

### Anything else?

Seeing that other terminals like alacritty, wezterm and foot don´t have this problem Kitty might be the culprit.

**Comment by jagaimoworks** [comment]
https://github.com/user-attachments/assets/ea28eee9-a0e3-41a6-ae4b-7353e0cc6d86

I press *q* in yazi and it doesn´t *exit*, but keeps the kitty window with the cursor open.
Also, it only seems to happen when I run `kitty yazi`. If I just execute yazi within kitty it seems to close the process just fine.

**Comment by sxyazi** [comment]
Hmmm that's weird, the `yazi` process has indeed gone. 

Have you tried `kitty -e yazi`? Also, what's your mpv command? Adding `--force-window`, i.e. `{ run = 'mpv --force-window "$@"', orphan = true }` does that work?

This looks like a kitty bug, if none of these works, I suggest opening an issue with kitty to ask for their support.

**Comment by jagaimoworks** [comment]
Sadly, `kitty -e yazi` behaves the same. This doesn´t come as a surprise since kitty doesn´t document the flag in their manpage.

Well, let's see what the kitty people say.

**Comment by sxyazi** [comment]
It looks like kitty has responded in https://github.com/kovidgoyal/kitty/issues/7966#issuecomment-2408284669, so let's just close this one since it's a kitty-specific issue.
