### ISSUE TITLE
When using yazi, I cannot preview or open PDF or JPG formats, and mine does not recognize them

### ISSUE THREAD

**Issue by CSWLeTianPai** [sxyazi/yazi#1778]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

windows terminal

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (7c445ce 2024-09-04)
    Debug  : false
    OS     : windows-x86_64 (windows)

Ya
    Version: 0.3.3 (7c445ce 2024-09-04)

Emulator
    Emulator.via_env: ("", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Microsoft

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : None
    EDITOR             : Some("cursor")
    VISUAL             : None
    YAZI_FILE_ONE      : Some("C:\\Program Files\\Git\\usr\\bin\\file.exe")
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "cursor %*", block: false, orphan: true, desc: "code", for_: None, spread: true })
    block  : Some(Opener { run: "cursor -w %*", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : program not found
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file             : 5.45
    ueberzugpp       : program not found
    ffmpegthumbnailer: program not found
    magick           : 7.1.1-39
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : program not found
    zoxide           : 0.9.6
    7z               : 24.08
    7zz              : program not found
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "C:\\Users\\CSW_L\\AppData\\Roaming\\yazi\\state" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

log:
  2024-10-14T01:15:40.453203Z ERROR yazi_scheduler::prework::prework: Returned 2 when running fetcher `mime` with:
C:\Users\CSW_L\OneDrive\Photos\Graduate\本科毕业\2A5797EF-2234-4418-9887-B8CDAE46A62D-2122-0000007.jpg
C:\Users\CSW_L\OneDrive\Photos\Graduate\本科毕业\3C77AC88-CBCF-4414-BA0B-655D81DD4C9A-179-00000053.jpg
C:\Users\CSW_L\OneDrive\Photos\Graduate\本科毕业\7CD0E733C0FBB4ED9B1A51CD4903C1B6.png
C:\Users\CSW_L\OneDrive\Photos\Graduate\本科毕业\9BD3663F-4131-49AB-8492-D73885361E8D-179-00000056.jpg
C:\Users\CSW_L\OneDrive\Photos\Graduate\本科毕业\49F3AD5D-7306-4268-90E6-E000E8C59407-179-00000055.jpg
C:\Users\CSW_L\OneDrive\Photos\Graduate\本科毕业\74FFB8CC-8862-46AA-9693-A8B63E4AC09F-179-00000055.jpg
C:\Users\CSW_L\OneDrive\Photos\Graduate\本科毕业\75AB64B1-89B4-42F5-91B3-087F15CF9DCE-179-00000055.jpg
C:\Users\CSW_L\OneDrive\Photos\Graduate\本科毕业\89C06356-A380-4E6E-9DDF-F546C25D8AB5-179-00000055.jpg

### Minimal reproducer

when i use yazi, jpg、pdf can't preview and open

**Comment by sxyazi** [comment]
>     Emulator.via_csi: Ok(Unknown([]))

Windows Terminal only started supporting image display from the latest preview version, Windows Terminal Preview v1.22.2702.0. Please make sure you're using the latest preview version. https://yazi-rs.github.io/docs/image-preview
