### ISSUE TITLE
recenter feature?

### ISSUE THREAD

**Issue by aidancz** [sxyazi/yazi#1779]
### `yazi --debug` output

```Shell
(% aidan core ~) yazi --debug 
Yazi 
    Version: 0.3.3 (Arch Linux 2024-09-05) 
    Debug  : false 
    OS     : linux-x86_64 (unix) 
Ya 
    Version: 0.3.3 (Arch Linux 2024-09-05) 
Emulator 
    Emulator.via_env: ("st-256color", "") 
    Emulator.via_csi: Ok(Unknown([])) 
    Emulator.detect : Unknown([]) 
Adapter 
    Adapter.matches: X11 
Desktop 
    XDG_SESSION_TYPE           : Some("tty") 
    WAYLAND_DISPLAY            : None 
    DISPLAY                    : Some(":0") 
    SWAYSOCK                   : None 
    HYPRLAND_INSTANCE_SIGNATURE: None 
    WAYFIRE_SOCKET             : None 
SSH 
    shared.in_ssh_connection: false 
WSL 
    WSL: false 
Variables 
    SHELL              : Some("/usr/bin/zsh") 
    EDITOR             : Some("nvim") 
    VISUAL             : Some("nvim") 
    YAZI_FILE_ONE      : None 
    YAZI_CONFIG_HOME   : None 
Text Opener 
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true }) 
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true }) 
Multiplexers 
    TMUX               : false 
    tmux version       : tmux 3.5a 
    ZELLIJ_SESSION_NAME: None 
    Zellij version     : No such file or directory (os error 2) 
Dependencies 
    file             : 5.45 
    ueberzugpp       : 2.9.6 
    ffmpegthumbnailer: 2.2.3 
    magick           : 7.1.1-39 
    fzf              : 0.55.0 
    fd               : 10.2.0 
    rg               : 14.1.1 
    chafa            : 1.14.2 
    zoxide           : 0.9.6 
    7z               : 17.05 
    7zz              : No such file or directory (os error 2) 
    jq               : 1.7.1 
-------------------------------------------------- 
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time. 
You can find it in the "/home/aidan/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

Will yazi consider adding the `recenter` feature?
Like the effect of `zz zb zt <C-e> <C-y> H M L` keys in vim
in addition, recenter at the 1/4 and 3/4 of the screen (1/4: between `zt` and `zz`, 3/4: between `zz` and `zb`)

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

recenter current directory

for example, after pressing `zz`:

![pic-window-241014-1146-24](https://github.com/user-attachments/assets/ea208f16-6add-4d38-acf5-47a872ff12cd)

becomes

![pic-window-241014-1146-37](https://github.com/user-attachments/assets/5ec607f0-eb82-4884-bde9-ca9d14934acd)

### Additional context

similar issues in `lf`:

https://github.com/gokcehan/lf/issues/801
https://github.com/gokcehan/lf/issues/457

### Validations

- [X] I have searched the existing issues/discussions
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
Sorry, there are no plans to support it as a built-in feature. The `z` key is already occupied by zoxide/fzf, and changing it would be a breaking change. 

However, it should be easy to implement via the plugin system. Here's a similar plugin that changes the cursor behavior for your reference:  
https://github.com/lpanebr/yazi-plugins/tree/main/first-non-directory.yazi
