### ISSUE TITLE
Transparent images in Kitty are displayed with artefacts

### ISSUE THREAD

**Issue by hankertrix** [sxyazi/yazi#1781]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.36.4

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Arch Linux 2024-09-05)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Arch Linux 2024-09-05)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : Some("x11")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-39
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/hanker/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

The image previewer for Kitty is displaying weird artefacts on transparent PNG images like shown:

![image](https://github.com/user-attachments/assets/a5376d0c-aeb9-423f-82f5-3fdf819cda3e)

This is how it should look like:

![image](https://github.com/user-attachments/assets/6e2c8795-c542-4af7-b848-e92e023d0238)

### Minimal reproducer

Preview these images in Yazi:

![chin-chin](https://github.com/user-attachments/assets/36b916f6-6bc1-4457-9049-788caa905ae1)
![cultist](https://github.com/user-attachments/assets/b419a4b1-22bd-445e-b747-ac4434fcd951)
![dancer](https://github.com/user-attachments/assets/43f1cdbb-1c8c-498d-a2d5-a434c380073a)
![doll](https://github.com/user-attachments/assets/ca0d7feb-6df7-48ae-8249-805e8ebb75a4)
![fascination](https://github.com/user-attachments/assets/a5bb65ed-0da0-431f-8db5-716382f54f81)
![frangiclave](https://github.com/user-attachments/assets/661ce884-ec5a-4bbc-880a-1ba5990b24ce)
![grimoire](https://github.com/user-attachments/assets/d94fc7aa-f12a-4572-8741-c4bb7b52aeeb)
![injury](https://github.com/user-attachments/assets/d65c1006-db44-482e-a722-1f56d2b512c6)

You will find that all of them have weird artefacts.

### Anything else?

[Joshuto](https://github.com/kamiyaa/joshuto) seems to preview these images just fine, as shown:

![image](https://github.com/user-attachments/assets/94f5dab1-fa68-4b68-8078-374c1ca5b476)

[Joshuto](https://github.com/kamiyaa/joshuto) uses [ratatui-image](https://github.com/benjajaja/ratatui-image) to do its image previews, so maybe following what [ratatui-image](https://github.com/benjajaja/ratatui-image) does would work.

**Comment by sxyazi** [comment]
Yazi has supported transparent images only since [PR #1556](https://github.com/sxyazi/yazi/pull/1556). Currently, you need to use the nightly version.

**Comment by sxyazi** [comment]
Also make sure to do a `yazi --clear-cache` after upgrading to the latest version
