### ISSUE TITLE
Image display error in the Rio terminal.

### ISSUE THREAD

**Issue by Kevin-2483** [sxyazi/yazi#1786]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

rio

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Nixpkgs 2024-09-04)
    Debug  : false
    OS     : macos-aarch64 (unix)

Ya
    Version: 0.3.3 (Nixpkgs 2024-09-04)

Emulator
    Emulator.via_env: ("rio", "rio")
    Emulator.via_csi: Ok(Unknown([Sixel]))
    Emulator.detect : Unknown([Sixel])

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("lvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "lvim \"$@\"", block: true, orphan: false, desc: "Open with lunarVim", for_: None, spread: true })
    block  : Some(Opener { run: "lvim \"$@\"", block: true, orphan: false, desc: "Open with lunarVim", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.5a
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-39
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.4
    zoxide           : 0.9.6
    7z               : 17.05
    7zz              : 24.08
    jq               : 1.7.1


--------------------------------------------------
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

https://github.com/user-attachments/assets/bec4e110-9fd3-44c7-ac31-49172259d465

When running Yazi in Rio, the images displayed will remain in the terminal and cannot be removed. Sometimes, they overlap with each other, and text can overlap on top of the images. On the same computer, it works normally in Kitty. A video demonstrates the behavior of Rio.”

### Minimal reproducer

- macos 15.0.1
- rioterm 0.1.17
- yazi 0.3.3

they are all in nixpkgs-unstable

**Comment by sxyazi** [comment]
I can reproduce the issue on Rio, but using the same Inline Image Protocol code, I couldn't replicate it on any other terminal emulator (iTerm2, WezTerm, Tabby). 

Given that Rio only recently added support for the image rendering, this is likely an issue specific to Rio itself, which will require some debugging on the terminal emulator's side. I suggest filing an issue to request their support.

I'll also create a PR later to update the README, mentioning the issue with images not being properly cleared on Rio. Closing as not Yazi

**Comment by sxyazi** [comment]
> I'll also create a PR later to update the README, mentioning the issue with images not being properly cleared on Rio. Closing as not Yazi

Done in https://github.com/sxyazi/yazi/pull/1784/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by Kevin-2483** [comment]
I’m afraid Tabby can’t be used either. When I tested it today, the images were enlarged significantly, and the terminal text disappeared.

<img width="1880" alt="image" src="https://github.com/user-attachments/assets/e80ad54a-8728-413a-a5cf-ea2c4b09bce8">

**Comment by sxyazi** [comment]
> When I tested it today, the images were enlarged significantly

This is expected behavior, Tabby doesn't implement the `ioctl` system call, you need to tune down `max_width` and `max_height` manually. 

Already mentioned in https://yazi-rs.github.io/docs/image-preview#size, please read docs carefully

**Comment by raphamorim** [comment]
Thank you for the issue report and @sxyazi for the update on it. I will take a look on a fix for it 🙏
