### ISSUE TITLE
Crates.io upload

### ISSUE THREAD

**Issue by radek-sprta** [sxyazi/yazi#179]
Hello,

are you planning to upload yazi to crates.io?

**Comment by Eric-Song-Nop** [comment]
There is no plan to publish it for now, as there is already another yazi on crates.io:)

**Comment by mimikun** [comment]
How about changing the name and uploading?
e.g. `yazi-filer`

**Comment by sxyazi** [comment]
Maybe I'll try to release it as `yazi-fm` in the next version, but I can't make the promises, sorry.

**Comment by radek-sprta** [comment]
> Maybe I'll try to release it as `yazi-fm` in the next version, but I can't make the promises, sorry.

If you're not against the idea, I can make a PR with a Github Actions workflow to upload the crate to crates.io.

**Comment by sxyazi** [comment]
That would be great, go for it!

**Comment by tex** [comment]
I'd like to create a package for guix, I think it need to be on crates.io to be able to do it.

**Comment by radek-sprta** [comment]
> I'm trying to publish Yazi as a workspace on crates.io, but it's not going smoothly, seems we can only publish each crate independently, which adds some complexity to project management.
> 
> `cargo install --git` might become the recommended way in the end, not sure yet, still researching...

Yes, all creates need to be publishes separately. So you'd end up with `yazi-fm` for the binary and `yazi-...` for all the other components. There are tools the make the management easier (like `release-plz`), so you can publish everything in one action.

Sorry for not coming up with a PR, I was busier with other things than I've expected.

**Comment by T-256** [comment]
I really like the [Ruff crates](https://github.com/astral-sh/ruff/tree/main/crates) structure, Alternatively `yazi` could have:
```
crates/
    yazi_fm/
    yazi_core/
    yazi_adapter/
    ...
```

**Comment by sxyazi** [comment]
Hi folks! You can now install Yazi from crates.io 🎉

```bash
cargo install --locked yazi-fm
```

https://github.com/sxyazi/yazi/pull/298
