### ISSUE TITLE
show number of lines in the status bar for text files.

### ISSUE THREAD

**Issue by yuvals1** [sxyazi/yazi#1798]
### `yazi --debug` output

```Shell
.
```

### Please describe the problem you're trying to solve

.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

.

### Validations

- [X] I have searched the existing issues/discussions
- [X] The latest nightly build of Yazi doesn't already have this feature

**Comment by sxyazi** [comment]
Sorry, there are no plans to build this feature in, but you should be able to implement it easily through the plugin system. There are some examples in the tips: 

- https://yazi-rs.github.io/docs/tips#symlink-in-status
- https://yazi-rs.github.io/docs/tips#user-group-in-status
- https://yazi-rs.github.io/docs/tips#username-hostname-in-header
