### ISSUE TITLE
Readme里面的example.mp4视频

### ISSUE THREAD

**Issue by HaoliangXu** [sxyazi/yazi#180]
这个视频一打开的画面就是一个盗版的电子书标题，文件名还留了z开头的网站
建议隐藏掉

**Comment by sxyazi** [comment]
谢谢提醒！我没意识到这个问题，我会找时间尽快录制新的演示视频。

**Comment by sxyazi** [comment]
Hi，我重新录制了演示视频，并更新了 README https://github.com/sxyazi/yazi/commit/5a7b84a8fc06b037b5effffe697c10aac0da1f91

版权是需要被妥善对待的问题，该 issue 不会被删除以做记录。
