### ISSUE TITLE
Image preview being blocky 

### ISSUE THREAD

**Issue by ngomkhang134** [sxyazi/yazi#1812]
### What system are you running Yazi on?

Windows WSL

### What terminal are you running Yazi in?

wezterm 20241007-103714-ed430415

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (24a77d8 2024-10-19)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (24a77d8 2024-10-19)

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(WezTerm)
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Chafa

Desktop
    XDG_SESSION_TYPE           : Some("tty")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: true

WSL
    WSL: true

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.4
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.2
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-39
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.4
    zoxide           : 0.9.6
    7z               : No such file or directory (os error 2)
    7zz              : 24.08
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/pamhanni/.local/state/yazi" directory.
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

i followed the tutorial for image preview on windows wsl with wezterm . but in the last command i type "ssh 127.0.0.1" instead of "wezterm ssh 127.0.0.1" because "wezterm is not a command" and got the blocky image preview . 
![Screenshot 2024-10-19 210009](https://github.com/user-attachments/assets/612dd2fa-4360-49c1-b522-1cb510874a09)

i did tried to install wezterm in ubuntu,and alias "wezterm" then typed "wezterm ssh 127.0.0.1", and the image renders perfectly, but running wezterm IN ubuntu is really laggy. 
![Screenshot 2024-10-20 084030](https://github.com/user-attachments/assets/c4a9cddd-e2c3-477c-b945-39896c65b481)

if i type "wezterm ssh 127.0.0.1" in cmd terminal, this happens
![Screenshot 2024-10-20 085558](https://github.com/user-attachments/assets/96fc2b02-92eb-4ee9-89a8-2221d11f4bde)

and if i type that in wezterm but before running wsl, this happens
![Screenshot 2024-10-20 090159](https://github.com/user-attachments/assets/e2b2b1df-4f79-4206-b6f0-8bfa015d69a5)

if i uninstall ueberzugpp, the image wouldn't render at all.

### Minimal reproducer

windows 11 , wsl 2 , with wezterm 20241007-103714-ed430415.

sudo apt install openssh-server
sudo service ssh restart
ssh 127.0.0.1

**Comment by sxyazi** [comment]
> i did tried to install wezterm in ubuntu,and alias "wezterm" then typed "wezterm ssh 127.0.0.1"

No, you should install wezterm outside of WSL, i.e. on your physical host, and use it `wezterm ssh` into your WSL, which is currently the only way Yazi supports due to ConPTY limitations, see https://yazi-rs.github.io/docs/image-preview#wsl 

Make sure you've correctly installed and configured `sshd` within WSL, and that you can connect from your physical host. You can first try a regular `ssh`, and if that works, then use `wezterm ssh`; they're essentially the same.

**Comment by ngomkhang134** [comment]
so open wezterm(windows)--->type wsl --> type wezterm ssh 127.0.0.1 . then it shows me this:
libEGL warning: failed to open /dev/dri/renderD128: Permission denied

libEGL warning: failed to open /dev/dri/renderD128: Permission denied

10:25:37.577  ERROR  wezterm_gui > XOpenDisplay failed to open a display. Check the $DISPLAY env var; terminating

but if i type "ssh 127.0.0.1" then 
![image](https://github.com/user-attachments/assets/c10d4039-8b57-4b38-bb96-3ba837b9faad)
then when i open yazi, the image is still blocky
![image](https://github.com/user-attachments/assets/ecb05c23-46a5-4c9f-8dd8-7857f20bba29)

**Comment by sxyazi** [comment]
If you `ssh` into WSL and see pixelated images, that's expected behavior since it's using the Chafa backend — the normal `ssh` doesn't support any image protocol. 

You should **always use `wezterm ssh`**, as `ssh` is just for helping you test if the `sshd` service in WSL is enabled. 

As for why `wezterm ssh` isn't working, it's likely an issue with WezTerm itself, please report it to WezTerm and ask for their support, there's also a related issue you can look to https://github.com/wez/wezterm/issues/2850.

**Comment by ngomkhang134** [comment]
when i type "wezterm ssh 127.0.0.1" it shows this 
![image](https://github.com/user-attachments/assets/759901fa-e275-4f3a-811e-8b460219767b)

do you have any idea ?
