### ISSUE TITLE
Key `z` (open zoxide) leaves orphaned tmp-files

### ISSUE THREAD

**Issue by FreeHarry** [sxyazi/yazi#1813]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Arch Linux 2024-09-05)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Arch Linux 2024-09-05)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : Some("x11")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0.0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : None
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.5a
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-39
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.2
    zoxide           : 0.9.6
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

Using the `z` key to run `zoxide` within yazi, leaves orphaned tmp-files, that are no longer removed.

![image](https://github.com/user-attachments/assets/253a8811-7648-4ee9-a7fe-9a0a644622d8)

If I use zoxide directly in my shell, this is not the case. Only when using it within yazi.

After a while there are many unwanted tmp-files within this directory.

### Minimal reproducer

1. Open yazi
2. Press `z`
3. Look into `~/.local/share/zoxide` => There is now a tmp-file, that are no longer removed.

**Comment by FreeHarry** [comment]
Yes, but when I run zoxide directly, there are no temporary files left. Only if I run it via Yazi.

So my idea was, that yazi maybe don't finish the zoxide process fully and so the temp-files remaining.

The strange thing is, that only one temporary file will remain in the directory during a Yazi session, also if zoxide is started multiple times within.

**Comment by sxyazi** [comment]
Can you confirm which of the 3 commands listed above created these temporary files?

**Comment by FreeHarry** [comment]
Now I checked it again...

On my windows system I havent' that problem at all. It works without leaving any temp-files.

On my Archlinux system I checked all three commands above, like so e.g.:

```bash
zoxide query -l
zoxide query -i --exclude /home
zoxide add /home
```

I don't have any remaining temp-files in the folder `~/.local/share/zoxide`, when using zoxide directly. Even I cannot recognize any temp-file creation in the folder.

The problem appears only inside Yazi, when I click the `z` key, as described above.

**Comment by FreeHarry** [comment]
I debugged it. I figured out when I disabled the line `child:start_kill()`, then no temp-files stay in the folder.

![image](https://github.com/user-attachments/assets/7eca31d5-84b9-49bc-aef6-1edf8540df84)

Maybe that helps you. I'm not the expert to evaluate this.

**Comment by sxyazi** [comment]
Thanks for your debugging; it's really helpful. In this case, I think it's a `zoxide` bug: 

1. `zoxide query` should be a read-only operation and shouldn't create any temporary files. 
2. `zoxide query` doesn't have an option like `--limit 2`, so it just gets the first 2 entries from the history. To avoid excessive output, Yazi sends a kill signal to end the process after reading what it needs, which is a common optimization.

**Comment by FreeHarry** [comment]
#https://github.com/ajeetdsouza/zoxide/issues/924
