### ISSUE TITLE
Ziparchive preview empty if archive member name contains `ä`

### ISSUE THREAD

**Issue by FreeHarry** [sxyazi/yazi#1814]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Windows Terminal

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (7c445ce 2024-09-04)
    Debug  : false
    OS     : windows-x86_64 (windows)

Ya
    Version: 0.3.3 (7c445ce 2024-09-04)

Emulator
    Emulator.via_env: ("", "")
    Emulator.via_csi: Ok(Unknown([Sixel]))
    Emulator.detect : Microsoft

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : None
    EDITOR             : None
    VISUAL             : None
    YAZI_FILE_ONE      : Some("C:\\Users\\<user>\\scoop\\apps\\git\\current\\usr\\bin\\file.exe")
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "code %*", block: false, orphan: true, desc: "code", for_: None, spread: true })
    block  : Some(Opener { run: "code -w %*", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : program not found
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file             : 5.45
    ueberzugpp       : program not found
    ffmpegthumbnailer: program not found
    magick           : 7.1.1-39
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.4
    zoxide           : 0.9.6
    7z               : 24.08
    7zz              : program not found
    jq               : 1.7.1
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

The content of a ziparchive is not shown in Preview if an archive member name contains chars like `ä, ü, ö`.

Facts:
- 7-zip can open the ziparchive without any errors. Only preview in yazi is not working.
- On my linux system same ziparchive is shown. Only on Windows it isn't working.
- Unicode chars are replaced with `_` (also only on Windows)
- It seems, the file list of preview is broken after an archive member name contains one of the special chars.
- Obviously it is an encoding problem of the archive member names.

### Minimal reproducer

Open the following file in yazi on MS-Windows in Windows Terminal:
[test.zip](https://github.com/user-attachments/files/17450217/test.zip)

**Comment by sxyazi** [comment]
The preview only shows the first of 2 files because starting from the second one, `7zip`'s output contains non-UTF-8 characters, but Yazi's `read_line()` API currently only supports UTF-8, which is an incomplete todo: 

https://github.com/sxyazi/yazi/blob/24a77d8a5f07f15d3b7d4651c9acf1e372ea5aef/yazi-plugin/src/process/child.rs#L29-L30

I'll create a PR to support this.

---

As for the second issue, it's a problem with `7zip` itself - if you run `7z l -ba -slt "test.zip"`, you'll see that the filenames are already replaced with `__` in the output:

```
Path = unicode-in_name-__.txt 
Folder = -
Size = 0
Packed Size = 0
Modified = 2024-10-20 05:17:42.8772746
Created =
Accessed =
Attributes = A
Encrypted = -
Comment =
CRC = 00000000
Method = Store
Characteristics = NTFS : UTF8
Host OS = FAT
Version = 10
Volume Index = 0
Offset = 0

Path = äöü-in-name.txt
Folder = -
Size = 0
Packed Size = 0
Modified = 2024-10-20 05:17:28.6630827
Created =
Accessed =
Attributes = A
Encrypted = -
Comment =
CRC = 00000000
Method = Store
Characteristics = NTFS up
Host OS = FAT
Version = 10
Volume Index = 0
Offset = 54
```

I'm not sure why `7zip` does this, but I think it's hard to fix in Yazi side since this isn't caused by Yazi - Yazi just parses the `7zip` output as is.

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1816

**Comment by FreeHarry** [comment]
Cool. It is working now, tested with the nightly build.

But I found some inconsistency with the file size info of archive members. If a file is empty, no file size is shown for it. Is this intended? In my opinion it should show something like "0B", instead of nothing. So we could distinguish a file from a directory.

**Comment by sxyazi** [comment]
Yes, this is expected behavior. It will only be displayed when there is a size to reduce space waste

https://github.com/sxyazi/yazi/blob/0e118b5b3a5baacf7fe62971e2bfe2b0ad972bab/yazi-plugin/preset/plugins/archive.lua#L27-L31
