### ISSUE TITLE
Value error on sort_by key

### ISSUE THREAD

**Issue by ImSreyas** [sxyazi/yazi#1815]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.36.4 

### `yazi --debug` output

```Shell
Error: TOML parse error at line 7, column 11
  |
7 | sort_by = "modified"
  |           ^^^^^^^^^^
invalid sort_by value: modified
```

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

After the update (Yazi 0.3.3 (24a77d8 2024-10-20)), the sort_by key is showing an invalid value error, 

error is, 

Error: TOML parse error at line 7, column 11
  |
7 | sort_by = "modified"
  |           ^^^^^^^^^^
invalid sort_by value: modified

### Minimal reproducer

Happened after the update to the latest version on github (Yazi 0.3.3 (24a77d8 2024-10-20)), 
showing the error while trying to start the application.
And it is working fine when i remove the key from the configuration file, 
and the sorting functionality inside yazi is working fine.

**Comment by sxyazi** [comment]
This is a breaking change in the upcoming Yazi v0.4 to resolve https://github.com/sxyazi/yazi/pull/1761, please change it to `sort_by = "mtime"`

Closing as it's expected behavior
