### ISSUE TITLE
Async image preview renders over blocking shell command.

### ISSUE THREAD

**Issue by amano-kenji** [sxyazi/yazi#1827]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot 1.16.2

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (VERGEN_IDEMPOTENT_OUTPUT 2024-10-08)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (VERGEN_IDEMPOTENT_OUTPUT 2024-10-08)

Emulator
    Emulator.via_env: ("tmux-256color", "tmux")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect : Foot

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : Some("/run/user/1000/sway-ipc.1000.4379.sock")
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })
    block  : Some(Opener { run: "hx \"$@\"", block: true, orphan: false, desc: "helix", for_: None, spread: true })

Multiplexers
    TMUX               : true
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-38
    fzf              : 0.54.3
    fd               : No such file or directory (os error 2)
    rg               : No such file or directory (os error 2)
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : 16.02
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

If I enter a directory and execute a blocking shell command before any image preview is rendered, an image preview is rendered over the blocking shell command.

### Minimal reproducer

Enter a directory with lots of images or video files, and enter a blocking shell command before any image preview is rendered.

### Anything else?

The latest commits don't address this specific issue.

**Comment by sxyazi** [comment]
Can't reproduce it, a video showing your steps would be helpful

**Comment by amano-kenji** [comment]
https://github.com/user-attachments/assets/3ca321bf-b782-4bc3-9ee6-deb20483fa61

Recording sway screen was easier than I thought.

This issue requires a slow hard disk and a lot of files in a directory.

**Comment by sxyazi** [comment]
I still can't reproduce it by following your steps:


- Add a `ya.sleep(3)` to the image previewer to make it slower by 3s
- Hover on an image file then open the shell within Yazi in blocking mode

https://github.com/user-attachments/assets/4762ba65-f115-41a4-9d96-bac250751fc2

Did you use any custom configs/plugins? Can you reproduce it with the default config (`mv ~/.config/yazi ~/.config/yazi-backup`)? 

Also I noticed you're not using the latest nightly version; can you reproduce it with the latest nightly?

Let me know if I missed any details for replicating it.

**Comment by amano-kenji** [comment]
I guess the issue is triggered if you enter a blocking shell before image previews are generated in the cache directory.

**Comment by amano-kenji** [comment]
I reproduced the same issue with the default config on the latest commit.

**Comment by amano-kenji** [comment]
If I enter an empty directory, launch a blocking shell, and download a youtube video with yt-dlp, then I see the image preview of the video on the shell.

**Comment by amano-kenji** [comment]
If I enter an empty directory, launch a blocking shell, and copy a video from another directory to the current directory, then I see the image preview of the video on the shell.

**Comment by amano-kenji** [comment]
* Enter an empty directory
* Launch a blocking shell such as bash
* Copy a video from another directory to the current directory with a shell command, `cp`.
* An image preview appears on top of bash.

Execute

> cp /path/to/video.mp4 .

in an empty directory, and enjoy the image preview on bash.

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1833

**Comment by amano-kenji** [comment]
I tried it. It seems to fix the issue, but it takes more than one second to see an image preview. It used to be much faster than that.

**Comment by sxyazi** [comment]
I didn’t notice any slowdown. Are you sure you built it in release mode? What does yazi --debug say?

**Comment by amano-kenji** [comment]
I didn't specify the release mode.

```
Yazi
    Version: 0.3.3 (56f9a6a 2024-10-25)
    Debug  : true
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (VERGEN_IDEMPOTENT_OUTPUT 2024-10-08)

Emulator
    Emulator.via_env: ("tmux-256color", "tmux")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect : Foot

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : Some("/run/user/1000/sway-ipc.1000.4381.sock")
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default     : Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })
    block-create: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })
    block-rename: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })

Multiplexers
    TMUX               : true
    tmux version       : 3.4
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-38
    fzf              : 0.54.3
    fd               : No such file or directory (os error 2)
    rg               : No such file or directory (os error 2)
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : 16.02
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

**Comment by amano-kenji** [comment]
I just built in the relase mode, and the image preview is fast in the release mode.
