### ISSUE TITLE
[Feature Request] Support Backtab in Keymap

### ISSUE THREAD

**Issue by Neurognostic** [sxyazi/yazi#183]
## Support Backtab in Keymap

Crossterm has the KeyCode [`BackTab`](https://docs.rs/crossterm/latest/crossterm/event/enum.KeyCode.html#variant.BackTab), which is `shift+tab`, but it does not seem to work in `yazi`. 

https://docs.rs/crossterm/latest/crossterm/event/enum.KeyCode.html#variant.BackTab

Setting the following `keymap.toml` ought to work for switching tabs.

```toml
[manager]
keymap = [
	{ on = [ "<BackTab>" ], exec = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
	{ on = [ "<Tab>" ], exec = "tab_switch 1 --relative",  desc = "Switch to the next tab" },
]
```

Or is there some other way to specify `shift+tab` ?

**Comment by sxyazi** [comment]
I'll add it later

**Comment by sxyazi** [comment]
Done by https://github.com/sxyazi/yazi/issues/183, please give it a try!

**Comment by Neurognostic** [comment]
It works! Thank you.
