### ISSUE TITLE
Suggestion on Enabling Interactive Operations of Yazi in Different Terminal Instances

### ISSUE THREAD

**Issue by ovwxxwvo** [sxyazi/yazi#1838]
### `yazi --debug` output

```Shell
0
```

### Please describe the problem you're trying to solve

I suggest creating a service before launching the instance of the Yazi file manager. Afterwards, all instances of Yazi can interact through this service, realizing operations such as cutting, copying, and pasting. Moreover, we can also use this service to store variables, so that in many cases, there is no need to wrap Yazi with a shell script in order to perform some operations.

关于鸭子在不同终端实例中可交互操作的建议

我建议在启动鸭子文件管理器实例之前，创建一个服务。之后所有的鸭子实例都可以通过这个服务进行交互，实现剪切、复制、粘贴等操作。并且，我们还可以通过这个服务来存储变量，这样在很多情况下，就无需再用 shell 脚本将鸭子包裹起来才能进行一些操作。

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

0

### Validations

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

**Comment by ovwxxwvo** [comment]
I am new, but I learn.

**Comment by sxyazi** [comment]
This is a feature that has already been supported, see https://yazi-rs.github.io/docs/dds

**Comment by ovwxxwvo** [comment]
> This is a feature that has already been supported, see https://yazi-rs.github.io/docs/dds

Hey, my dear. Alright, I was too hasty.
I found down yazi yesterday, & tried it today. 
This project is better than the others ( ranger, joshuto, ).
You need to promote it & let people know.
I just config joshuto few month ago. 无耐。。。
One more suggestion, 
hope config files can be separated & constructed ourselves.

**Comment by ovwxxwvo** [comment]
@sxyazi HEY, one question,.
when use ueberzugpp preview image , sometimes work, sometimes crash my whole system.
I write some script for joshuto use ueberzug before, it seems work different.
How can I debug this, & help me know about how ueberzugpp work a little bit.
x11+alacritty+tmux.

**Comment by ovwxxwvo** [comment]
```
set -g allow-passthrough all
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
```
```
echo $TERM, $TERM_PROGRAM, and $XDG_SESSION_TYPE
tmux-256color, tmux, and x11
```
this one change nothing in my env, is this important.

**Comment by sxyazi** [comment]
> How can I debug this, & help me know about how ueberzugpp work a little bit

See https://yazi-rs.github.io/docs/image-preview#debug-ueberzug
