### ISSUE TITLE
[Feature Request] Bookmarks

### ISSUE THREAD

**Issue by Neurognostic** [sxyazi/yazi#184]
## Bookmarks

Implement bookmarking similar to [`vi` marks](https://neovim.io/doc/user/motion.html#mark-motions) for saving cursor location in the filesystem tree, recalling mark list, and removing marks.

https://neovim.io/doc/user/motion.html#mark-motions

**Comment by sxyazi** [comment]
The upcoming Yazi plugin system will allow users to write their own plugins. Would you be willing to implement it as a plugin?

**Comment by Neurognostic** [comment]
What kind of interface will the plugin system be? I would be willing to give it a shot if I can figure it out. 😉

**Comment by Neurognostic** [comment]
I would personally like a lua interface for plugins.

**Comment by sxyazi** [comment]
Hi, @dedukun made it into a plugin, see https://github.com/dedukun/bookmarks.yazi
