### ISSUE TITLE
copy/cut marks in the directory preview are not cleared by X and Y.

### ISSUE THREAD

**Issue by amano-kenji** [sxyazi/yazi#1848]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot 1.16.2

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (e350720 2024-10-28)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (VERGEN_IDEMPOTENT_OUTPUT 2024-10-08)

Emulator
    Emulator.via_env: ("foot", "")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect : Foot

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : Some("/run/user/1000/sway-ipc.1000.4409.sock")
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default     : Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })
    block-create: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })
    block-rename: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.4
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-38
    fzf              : 0.54.3
    fd               : No such file or directory (os error 2)
    rg               : No such file or directory (os error 2)
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
```

### Describe the bug

An exited directory's preview doesn't clear copy/cut marks when I press X or Y.

### Minimal reproducer

* Enter a directory.
* Cut or copy some files
* Go up a directory
* Press X or Y
* The cut/copy marks aren't cleared in the directory preview.

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by amano-kenji** [comment]
Another way to reproduce the issue.

* Press a keyboard shortcut to visit a directory
* Cut a file
* Go to another directory, and paste it
* Press the keyboard shortcut again to visit the directory where the file was cut.
* The file can still be seen in the first directory.

**Comment by sxyazi** [comment]
This is a known issue, work on other PRs, wait for a while

**Comment by amano-kenji** [comment]
The original issue was fixed

https://github.com/sxyazi/yazi/issues/1848#issuecomment-2475634139 is still not fixed.

I think it is a separate issue.

**Comment by amano-kenji** [comment]
https://github.com/sxyazi/yazi/issues/1990
