### ISSUE TITLE
zoxide not working on yazi, though it is working normally on the terminal

### ISSUE THREAD

**Issue by luccahuguet** [sxyazi/yazi#1850]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

wezterm 20240203-110809-5046fc22

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (7c445ce 2024-09-04)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (7c445ce 2024-09-04)

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(Unknown([Sixel]))
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":1")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/home/lucca/.cargo/bin/nu")
    EDITOR             : Some("/home/lucca/user_installs/helix/target/release/hx")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: Some("cubic-lemon")
    Zellij version     : 0.40.1

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : No such file or directory (os error 2)
    fd               : No such file or directory (os error 2)
    rg               : No such file or directory (os error 2)
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.6
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : 1.7


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/lucca/.local/state/yazi" directory.
```

### Describe the bug

zoxide not working on yazi, though it is working normally on the terminal

zoxide existed with error code 1

### Minimal reproducer

just press z

### Anything else?

this is my machine:

                         lucca@pop-os 
         a8888b.         ------------ 
        d888888b.        OS: Pop!_OS 24.04 
        8P"YP"Y88        Host: pop-os 
        8|o||o|88        Uptime: 30 minute(s) 
        8'    .88        Kernel: 6.9.3-76060903-generic 
        8`._.' Y8.       System OS version: 24.04 
       d/      `8b.      NB CPUs: 4 
      dP        Y8b.     CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz @ 3499 GHz 
     d8:       ::88b.    GPU #1: HD Graphics 620 
    d8"         'Y88b    GPU #2: GM108M [GeForce 940MX] 
   :8P           :888    Memory: 5631/15776 MiB 
    8a.         _a88P     
  ._/"Yaa     .| 88P|    ████████████████████████ 
  \    YP"    `|     `.  ████████████████████████ 
  /     \.___.d|    .'    
  `--..__)     `._.'      

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by luccahuguet** [comment]
also:

zoxide 0.9.6

**Comment by luccahuguet** [comment]
I've looked at zoxide's repo and there's nothing explaining where to find logs, so I couldn't read any logs from zoxide

**Comment by sxyazi** [comment]
>     fzf              : No such file or directory (os error 2)

You don't have `fzf` installed.

`fzf` is required for `zoxide`'s interactive mode to work, see the `zoxide` doc here https://github.com/ajeetdsouza/zoxide?tab=readme-ov-file#installation

**Comment by luccahuguet** [comment]
I would put a `*` on https://yazi-rs.github.io/docs/installation

in this line `[zoxide](https://github.com/ajeetdsouza/zoxide) (for historical directories navigation)`

explaining below, in the `*`, that you have to install `fzf`

**Comment by sxyazi** [comment]
Actually, we should be able to check if the user has fzf installed in Yazi and give them a prompt if they don't. Would you like to file a new issue for that as a record? I'll try to implement it then

**Comment by luccahuguet** [comment]
> Actually, we should be able to check if the user has fzf installed in Yazi and give them a prompt if they don't. Would you like to file a new issue for that as a record? I'll try to implement it then

awesome! will do

**Comment by luccahuguet** [comment]
https://github.com/sxyazi/yazi/issues/1851
