### ISSUE TITLE
parent dir items disappear when redraw

### ISSUE THREAD

**Issue by aidancz** [sxyazi/yazi#1855]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

st 0.8.5

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (5eabd7d 2024-10-29)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Arch Linux 2024-09-05)

Emulator
    Emulator.via_env: ("st-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: X11

Desktop
    XDG_SESSION_TYPE           : Some("tty")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.5a
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-39
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.2
    zoxide           : 0.9.6
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/aidan/.local/state/yazi" directory.
```

### Describe the bug

parent dir items disappear when redraw

https://github.com/user-attachments/assets/7398388b-30cc-4c0f-96f3-965035764341

### Minimal reproducer

download temp.zip and enter `dir_z` directory

[temp.zip](https://github.com/user-attachments/files/17568064/temp.zip)

I can reproduce this problem whether I use Kitty's built-in 'new window' feature (Ctrl+Shift+Enter) or open a new instance of Kitty

https://github.com/user-attachments/assets/f48076f3-ae7c-4001-af65-4b59c2fcc81f

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
I can't reproduce it by following your steps:


https://github.com/user-attachments/assets/4e8ab901-04bc-40f6-ab8a-6412a9583f53

**Comment by aidancz** [comment]
However, I can reproduce this problem whether I use Kitty's built-in 'new window' feature (Ctrl+Shift+Enter) or open a new instance of Kitty

https://github.com/user-attachments/assets/f48076f3-ae7c-4001-af65-4b59c2fcc81f

Maybe it’s an X11 issue？

Try downloading temp.zip, enter the dir_z directory, and see if you can reproduce the issue

[temp.zip](https://github.com/user-attachments/files/17560684/temp.zip)

**Comment by aidancz** [comment]
Furthermore, I prefer to make the parent folder visible as well

lf behavior:


https://github.com/user-attachments/assets/271af311-e030-420c-a406-da88896b711f

yazi behavior:


https://github.com/user-attachments/assets/63b949da-86cb-479a-89ee-55c32c6f1a6a

**Comment by sxyazi** [comment]
Please create a new feature request for it. This issue contains three different problems, which makes it hard to track

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1863
