### ISSUE TITLE
White box on file names in the directory?

### ISSUE THREAD

**Issue by greglearns** [sxyazi/yazi#186]
I'm getting a strange white box with characters in it on some of the files in the directory. Example: https://i.imgur.com/TlVWsoU.png

yazi 0.1.4

**Comment by sxyazi** [comment]
Did you install and configure nerd fonts as per the readme, or disable it?

**Comment by greglearns** [comment]
I enabled nerd fonts (using Home-manager, in packages), and enabled yazi (using home-manager in programs).

**Comment by sxyazi** [comment]
Have you set nerd-fonts as the default font in your terminal?

**Comment by greglearns** [comment]
Problem solved indirectly. I don't want to make nerd-fonts my default font in my terminal, so instead, I just copied down your theme.toml, and then in that file, when I edit it in vim, I can see which fields are not rendering correctly: e.g.
```
"*.json"  = ""
which, in my editor, looks like:
"*.json" = "E60B"
```
And so I just delete the "E60B".

Simple.

Thanks!

**Comment by sxyazi** [comment]
Oh, brilliant! Glad to see the issue has been resolved. I will now close this issue.
