### ISSUE TITLE
Vifm-like Tree View

### ISSUE THREAD

**Issue by ret2src** [sxyazi/yazi#1867]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (e3c9111 2024-10-31)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (e3c9111 2024-10-31)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty
```

### Please describe the problem you're trying to solve

Currently, I'm a `vifm` user.
`vifm` provides a so-called "tree view" mode, which expands all subdirectories in the current directory:

![vifm tree view](https://github.com/user-attachments/assets/effd85f0-b1da-40f0-9015-1f4e3abc4dd6)

This allows users to quickly filter, select, and move certain files in complex directory hierarchies.
For example, sometimes you might want to move all images or videos from all subdirectories to a common directory or simply rename them conveniently without traversing all the directories individually.

I'm currently unaware of anything in `yazi` that allows me to replicate this feature / workflow and I think it would be an amazing addition to your already amazing file manager.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

A feature that gives me the option to expand all subdirectories in the current directory would allow me to work more efficiently on large or complex directory hierarchies.

**Example:** Tree view filtered for files that end in `.nix$` (would allow me to move, rename, edit these files simultaneously)

![Tree view filtered for .nix files](https://github.com/user-attachments/assets/7cf9382b-df53-45fb-9b59-f74e94167acf)

Implementation of the feature could be solved as a "virtual overlay view" that can be toggled, just like in `vifm`.

### Validations

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

**Comment by sxyazi** [comment]
Hi, I plan to implement a "tree-view" for Yazi in the future, and it will be similar to the [dual-pane.yazi](https://github.com/dawsers/dual-pane.yazi) (an impl of vifm's dual-pane) as a separate plugin, the current plugin API is enough to support it, just haven't had the time to work on it yet.

Closing as already tracked in https://github.com/yazi-rs/plugins/issues/9 as the `tree.yazi` plugin
