### ISSUE TITLE
Use XDG paths for Goto.

### ISSUE THREAD

**Issue by voronind-com** [sxyazi/yazi#1878]
### Please describe the problem you're trying to solve

Current Goto definitions are as follows: `{ on = [ "g", "d" ],       run = "cd ~/Downloads",   desc = "Goto ~/Downloads" },`. Which is.. something, I guess. Why not use much more portable approach of `cd $XDG_DOWNLOAD_DIR`? Same goes for `~/.config`.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Use XDG variables.

### Additional context

I tested them, they work as expected.

### Validations

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

**Comment by sxyazi** [comment]
Closing with https://github.com/sxyazi/yazi/pull/1879
