### ISSUE TITLE
Ability to disable keybindings.

### ISSUE THREAD

**Issue by voronind-com** [sxyazi/yazi#1880]
### Please describe the problem you're trying to solve

Currently there's no way to disable default keybindings. I know about [this thread](https://github.com/sxyazi/yazi/discussions/629), however this won't work for Which dialog. For example, you can't remove `gc` config navigation, as it'll still be shown as an available option.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Either don't show "broken" suggestions or better provide a way to do this properly.

### Validations

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1882
