### ISSUE TITLE
Copy any file to a place with no write access hangs the copy job

### ISSUE THREAD

**Issue by fishBone000** [sxyazi/yazi#1888]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Alacritty

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (362fbeb 2024-11-05)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (362fbeb 2024-11-05)

Emulator
    Emulator.via_env: ("alacritty", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Chafa

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-0")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default     : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.5a
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : 7.1.1-39
    fzf              : 0.55.0
    fd               : No such file or directory (os error 2)
    rg               : 14.1.1
    chafa            : 1.14.2
    zoxide           : 0.9.6
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/fishbone/.local/state/yazi" directory.
```

### Describe the bug

Copy any file to a folder with no write access, e.g. copy your file to root folder, causes the copy job to hang with no error message. 

### Minimal reproducer

To reproduce:
1. Yank any file
2. Go to root `/`
3. Paste the file

Observed:
1. Copy job hangs: 0%, 1 left

Expected:
1. Fails immediately with error message

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [ ] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
The user might run multiple tasks concurrently, and showing an error message for each task failure would create a bad user experience. 

If you want to see the detailed error information for a specific task, just open the task manager and [`inspect`](https://yazi-rs.github.io/docs/configuration/keymap/#tasks.inspect) it. You'll find the full error message there, even the stack trace. 

Closing as it's expected behavior.
