### ISSUE TITLE
add flake.nix to be able to test the master version easily

### ISSUE THREAD

**Issue by teto** [sxyazi/yazi#189]
hi,

nix is a package manager with a focus on build reproducibility. It has a nice feature called flake.nix that once committed to the git ttree allows to run `nix run github:sxyazi/yazi` would let anyone build (if not in nix cache) and run directly the master version. 
One can also specify a ref/rev with  `nix run github:sxyazi/yazi?rev=ae313bc` for instance.

As the yazi software evolves quite fast, I would love to be able to test the latest version without having to pull/cargo run (I also need to run `nix develop nixpkgs#yazi` to get the required dev tools). 

It's more convenient when the flake is at the root of the repo but it's possible to put it in a subfolder, as in neovim's case; `nix run 'github:neovim/neovim?dir=contrib'`

@sxyazi would you mind a PR adding this to the repo ? @XYenon any interest in this as you submitted yazi to nixpkgs ?

**Comment by XYenon** [comment]
I haven't used it that way, but I'll have a try.

**Comment by musjj** [comment]
Yazi is already in `nixpkgs`. Just run `nix shell nixpkgs#yazi`. If you want to use `master`, I have this in my overlays:

```nix
final: prev: {
  yazi = prev.yazi.overrideAttrs (oldAttrs: rec {
    version = "unstable-2023-09-21";
    src = oldAttrs.src.override {
      rev = "6497df3a6f8e26312c0d0effc853b6b8348c3004";
      hash = "sha256-MpRGRJeD++s5gpH8h7KusjYTl55bOBoan8dOrbQ/IwI=";
    };
    cargoDeps = oldAttrs.cargoDeps.overrideAttrs {
      name = "${oldAttrs.pname}-${version}-vendor.tar.gz";
      inherit src;
      outputHash = "sha256-uFb/tCNT0U8AZfwtNm09mswC32hS/JlqiHjQ7hav3Cw=";
    };
  });
}
```

But you're right, an upstream flake would be nicer.

**Comment by phip1611** [comment]
Thanks for flakyfying this! It would be awesome to also have this in nixpkgs upstream, so that one can benefit from cached binaries. Is there a reason why this didn't happen yet?

I could upstream it theoretically, but I don't have the capacity I think to maintain it upstream in nixpkgs.

**Comment by teto** [comment]
it is in nixpkgs already https://github.com/NixOS/nixpkgs/pull/250697

**Comment by phip1611** [comment]
OHhh! I'm sorry. I only had a look at the 23.05 branch, not the unstable branch. Nice. Thanks!
