### ISSUE TITLE
Latest change to sync breaks smart-enter

### ISSUE THREAD

**Issue by bertradio** [sxyazi/yazi#1892]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.36.4

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (baf062f 2024-11-07)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (baf062f 2024-11-07)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kgp

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-0")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : None
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default     : Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_:None, spread: true })
    block-create: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_:None, spread: true })
    block-rename: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_:None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.44
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : 0.55.0
    fd               : No such file or directory (os error 2)
    fdfind           : 8.6.0
    rg               : 13.0.0
    chafa            : 1.12.4
    zoxide           : 0.9.4
    7z               : 16.02
    7zz              : No such file or directory (os error 2)
    jq               : 1.6
```

### Describe the bug

As per instructions, added to smart-enter init.lua --- @sync entry. 

I have smart-enter mapped to Enter. When hitting enter the process just hangs. This happens whether or not I have --sync in my keymap.toml.

### Minimal reproducer

I was able to change other plugins with --- @sync entry successfully.

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [ ] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by bertradio** [comment]
[yazi.log](https://github.com/user-attachments/files/17670228/yazi.log)

My yazi.log file.

Also here is my smart-enter init.lua:

-- init.lua
--
-- Created: 05/20/24

--- @sync entry

return {
	entry = function()
		local h = cx.active.current.hovered
		ya.manager_emit(h and h.cha.is_dir and "enter" or "open", { hovered = true })
	end,
}

**Comment by sxyazi** [comment]
> -- Created: 05/20/24

No, you need to place the `--- @sync entry` at the head of the file **without any other content before**, see https://yazi-rs.github.io/docs/tips#smart-enter

Closing as expected behavior

**Comment by bertradio** [comment]
Sorry to bother. Great work

**Comment by bertradio** [comment]
Thanks. Works now.

Yazi is the BEST!!!
