### ISSUE TITLE
Drag & Drop support on windows

### ISSUE THREAD

**Issue by skelewir** [sxyazi/yazi#1893]
### `yazi --debug` output

```Shell
-
```

### Please describe the problem you're trying to solve

No file drag and drop support on Windows

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Would be great to support drag and drop on Windows platform

### Validations

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

**Comment by sxyazi** [comment]
Yazi is a TUI app, not a GUI, so drag-and-drop isn't possible, you would need to create a GUI window to make that work anyway. 

To achieve it, you'd have to use third-party tools like [ripdrag](https://github.com/nik012003/ripdrag) or [dragon](https://github.com/mwh/dragon), but it seems they don't support Windows.

Closing as not doable in Yazi itself, yet there are no plans to create a completely new tool like `ripdrag` myself.
