### ISSUE TITLE
Add more debug info to `yazi --debug`

### ISSUE THREAD

**Issue by sxyazi** [sxyazi/yazi#1894]
- Include `FZF_DEFAULT_OPTS` and `YAZI_ZOXIDE_OPTS` environment variables
- Include Rust version that built with
- Include `xclip`, `wl-clipboard`, `xsel`, `poppler` dependency versions

Anyone want to give it a go? The source code can be found at:

https://github.com/sxyazi/yazi/blob/a9a8a190a4e3500c9aabc8288eb7b23665ef070e/yazi-boot/src/actions/debug.rs#L10-L103

**Comment by teodoradriann** [comment]
I have opened a pull request for this issue! 
#1898
