### ISSUE TITLE
Add `CODE_OF_CONDUCT.md`

### ISSUE THREAD

**Issue by sxyazi** [sxyazi/yazi#1905]
Some ideas:

- Respect different viewpoints
- Zero tolerance for harassment
- Communicate professionally and constructively
- Assume good intent in conversations – misunderstandings can happen, but give the benefit of the doubt before jumping to conclusions

Anyone want to give it a try? I'm not good at writing this kind of professional copy, especially since English isn't my first language :)

**Comment by Perfectio07** [comment]
I have been meaning to contribute to Yazi for a while now, so yeah sure why not, I will give it a go when I am off work. Let me know if there is anything specific you want me to include

**Comment by Perfectio07** [comment]
In regards to reporting incidents, where should an individual go to report something that breaks the COC?

**Comment by sxyazi** [comment]
Nice! Please use this link for reporting https://discord.com/users/638378964804698112
