### ISSUE TITLE
[Feature request] Different exit methods use different exit codes.

### ISSUE THREAD

**Issue by DreamMaoMao** [sxyazi/yazi#191]
![image](https://github.com/sxyazi/yazi/assets/30348075/007ffbde-5f55-4b2c-ac4e-892379a30b54)

I'm making an nvim plugin for yazi.
plugin:
 [yazi.nvim](https://github.com/DreamMaoMao/yazi.nvim)

However, what puzzles me is that both the normal exit of yazi and the exit after selecting a file using the --chooser-file parameter have a return code of 0, which makes it impossible for me to distinguish whether yazi exited with or without selecting a file.

Can you help return different exit codes for different exit methods?

**Comment by DreamMaoMao** [comment]
i find another way

**Comment by sxyazi** [comment]
I think you only need to check the `/tmp/test.txt` file (in your example).

BTW, this plugin looks pretty cool.
