### ISSUE TITLE
preview and edit don't work on windows

### ISSUE THREAD

**Issue by kicre** [sxyazi/yazi#1912]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

alacritty v0.14.0

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (7c445ce 2024-09-04)
    Debug  : false
    OS     : windows-x86_64 (windows)

Ya
    Version: 0.3.3 (7c445ce 2024-09-04)

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Chafa

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : None
    EDITOR             : None
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "hx %*", block: true, orphan: false, desc: "hx", for_: None, spread: true })
    block  : Some(Opener { run: "hx %*", block: true, orphan: false, desc: "hx", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : program not found
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file             : 5.45
    ueberzugpp       : program not found
    ffmpegthumbnailer: program not found
    magick           : 7.1.1-40
    fzf              : 0.56.3
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.5
    zoxide           : 0.9.6
    7z               : 24.08
    7zz              : program not found
    jq               : 1.6


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
```

### Describe the bug

The file preview does not display and using the Enter key to open the file has no effect at all.

### Minimal reproducer

  2024-11-16T13:07:02.641798Z  WARN yazi_adapter::adapter: [Adapter] Could not identify XDG_SESSION_TYPE
    at yazi-adapter\src\adapter.rs:109

  2024-11-16T13:07:02.641807Z  WARN yazi_adapter::adapter: [Adapter] Falling back to chafa
    at yazi-adapter\src\adapter.rs:118

  2024-11-16T13:07:02.644430Z  WARN yazi_adapter::ueberzug: ueberzugpp spawning failed: program not found
    at yazi-adapter\src\ueberzug.rs:96

  2024-11-16T13:07:02.711457Z ERROR yazi_scheduler::prework::prework: Returned 2 when running fetcher `mime` with:
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\.envrc
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\.gitignore
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\.styluaignore
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\Cargo.lock
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\Cargo.toml
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\CODE_OF_CONDUCT.MD
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\CONTRIBUTING.md
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\cspell.json
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\flake.lock
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\flake.nix
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\LICENSE
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\LICENSE-ICONS
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\README.md
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\rustfmt.toml
C:\Users\kicre\AppData\Roaming\yazi\state\yazi\stylua.toml
    at yazi-scheduler\src\prework\prework.rs:49

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
Please make sure to set up your file(1) correctly according to https://yazi-rs.github.io/docs/installation#windows
