### ISSUE TITLE
lua runtime failed (size_and_mtime from wiki)

### ISSUE THREAD

**Issue by bobblkabb** [sxyazi/yazi#1918]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot

### `yazi --debug` output

```Shell
Yazi
    Version: 0.2.5 (OpenSUSE 2024-04-26)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("foot", "")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect: Foot

Adaptor
    Adaptor.matches: Sixel

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY: Some("wayland-1")
    DISPLAY: Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/usr/bin/fish")
    EDITOR: Some("helix")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.45\nmagic file from /etc/magic:/usr/share/file/magic\nseccomp support included\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "hx \"$@\"", block: true, orphan: false, desc: "helix", for_: None, spread: true })
    block: Some(Opener { run: "hx \"$@\"", block: true, orphan: false, desc: "helix", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

### Describe the bug

Tried to replicate 'size_and_mtime' (including init.lua in ~/.config/yazi) setting from the wiki but yazi doesn't start anymore:
```
Error: Lua runtime failed

Caused by:
    runtime error: [string "init.lua"]:1: attempt to index a nil value (global 'linemode')
    stack traceback:
    	[C]: in metamethod 'newindex'
    	[string "init.lua"]:1: in main chunk
```

### Minimal reproducer

just starting yazi from foot terminal
[yazitoml.txt](https://github.com/user-attachments/files/17800171/yazitoml.txt)

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [ ] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
> attempt to index a nil value (global 'linemode')

Where did your "linemode" come from? It's `Linemode`, not `linemode`:

![screenshot-002136](https://github.com/user-attachments/assets/0a383183-56d7-4281-ad5b-ba4b889dfe68)

**Comment by bobblkabb** [comment]
That's it, thank you.
After that I was getting another message about "Deprecated API" to change modified to mtime.
You should change or mention it in the wiki where I got these lines.

**Comment by sxyazi** [comment]
No, that would break users who are using the stable version not nightly

**Comment by sxyazi** [comment]
I will update the documentation accordingly when the new version is released. For nightly, please see the pinned issue
