### ISSUE TITLE
cache_dir not working

### ISSUE THREAD

**Issue by Xygyl** [sxyazi/yazi#1919]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty v0.36.4

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (af565fb 2024-11-18)
    Debug  : false
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.82.0 (f6e511ee 2024-10-15)

Ya
    Version: 0.3.3 (VERGEN_IDEMPOTENT_OUTPUT 2024-10-09)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kgp

Desktop
    XDG_SESSION_TYPE           : Some("tty")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL           : Some("/bin/nu")
    EDITOR          : Some("/usr/bin/hx")
    VISUAL          : None
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(Opener { run: "hx \"$@\"", block: true, orphan: false, desc: "hx", for_: None, spread: true })
    block-create: Some(Opener { run: "hx \"$@\"", block: true, orphan: false, desc: "hx", for_: None, spread: true })
    block-rename: Some(Opener { run: "hx \"$@\"", block: true, orphan: false, desc: "hx", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    pdftoppm         : 24.08.0
    magick           : 7.1.1-38
    fzf              : 0.55.0
    fd               : 10.2.0
    fdfind           : No such file or directory (os error 2)
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.6
    7z               : No such file or directory (os error 2)
    7zz              : 24.08
    jq               : No such file or directory (os error 2)

Clipboard
    wl-copy/paste: 2.2.1 / 2.2.1
    xclip        : No such file or directory (os error 2)
    xsel         : No such file or directory (os error 2)


--------------------------------------------------
```

### Describe the bug

I have three drives in my system: my root drive, a hard drive, and an ssd. I have set the cache_dir to a directory on my ssd and when I load images on my hard drive they show up in that directory, so I know that it's working correctly. However, when I reboot, the cached images remain but when I load their counterparts on my hard drive it's as if they were never cached. 

### Minimal reproducer

Due to the nature of this issue, I'm not sure what to put here. I suppose you could reproduce the issue if you have a setup similar to mine: the media being on one drive and the cache_dir on another, with neither of them being the root drive. 

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
I can't reproduce it. 

Yazi uses file's path and mtime as the unique id for caching:

https://github.com/sxyazi/yazi/blob/6a4f6aa99f1c9422af68b8f5ea93082e84c12a9a/yazi-plugin/src/utils/cache.rs#L16-L22

Are you sure the mtime of your files hasn't changed?

**Comment by Xygyl** [comment]
Yes. The files haven't been edited since they've been written to the disk. I have

**Comment by Xygyl** [comment]
oops, didn't mean to close it. sorry.

**Comment by Xygyl** [comment]
I checked the mtime, checked the name of the files in my cache_dir, rebooted to see if the problem persisted (it did), deleted the files in my cache_dir, rebooted, recached the images (same names), rebooted, and the problem persisted. If you have any ideas or want anything from me then I'll be happy to provide.

**Comment by sxyazi** [comment]
Is it only happening with images? Does the issue also occur with videos or PDFs? Does it happen on a specific drive or all drives? Is that drive an external one? If it is, Windows seems to rename them based on the order they’re connected (D, E, F, etc.), which could be causing the filenames to keep changing.

**Comment by Xygyl** [comment]
I've only tested it with images and videos and it happens with all of them. It happens on every drive. All drives are internal. I'm running gentoo linux.

**Comment by sxyazi** [comment]
Please apply this patch, then send [your `yazi.log` file](https://yazi-rs.github.io/docs/plugins/overview#logging):

```diff
diff --git yazi-plugin/src/utils/cache.rs yazi-plugin/src/utils/cache.rs
index 8d2155764ab7ae61d6a039cba913195b3868d158..8ce16409a4caf0292dd1e1f4ad19713ed66cebb1 100644
--- yazi-plugin/src/utils/cache.rs
+++ yazi-plugin/src/utils/cache.rs
@@ -19,6 +19,14 @@ impl Utils {
 				format!("{:x}", digest.finalize())
 			};
 
+			tracing::error!(
+				"file_cache: url={}, mtime={:?}, skip={}, hex={}",
+				file.url.to_string_lossy(),
+				file.cha.mtime,
+				t.raw_get("skip").unwrap_or(0),
+				hex
+			);
+
 			Some(Url::cast(lua, PREVIEW.cache_dir.join(hex))).transpose()
 		})
 	}
```

**Comment by Xygyl** [comment]
I cloned the latest git, compiled with the patch, cached the same videos, and the files and sums are the same as they were before. The names of the cached files are identical. 

To be clear, when I cache a file and the go back to it in the same session everything works as it should. It's when I reboot and try to load those files again that things go wrong, so the system is clearly recognizing everything.

**Comment by sxyazi** [comment]
> It's when I reboot and try to load those files again that things go wrong

Is the info still identical after the reboot? If not, what information has changed? Can you compare the differences between before and after the reboot in the log?

**Comment by Xygyl** [comment]
After reboot is identical, though there are more entries that are identical to each other. If you really want to get specific I can set up the cache_dir to be on my root drive, cache pictures and videos that are also on my root drive, then share every log at every step of the way (before and after reboots and changes). 

Since you know how yazi works I don't know if that's necessary, but if it is then let me know and I'll get you all of that information and whatever else you need.

**Comment by Xygyl** [comment]
Just to be clear, all of this is being done with yazi's latest git and the patch you gave.

**Comment by sxyazi** [comment]
I'm confused. You mean the same info generates a different MD5?
