### ISSUE TITLE
Path(s) are added automatically to shell command on Windows

### ISSUE THREAD

**Issue by ndtoan96** [sxyazi/yazi#192]
https://github.com/sxyazi/yazi/assets/33489972/63042c3e-c655-44b2-9982-93882f18f11b

This issue has been reported via Discord but I'll also leave it here to keep track.

**Comment by sxyazi** [comment]
Thank you for bringing it up here.

Here are the reasons that caused it (quoted from [Discord](https://discord.com/channels/1136203602898194542/1136203604076802092/1153887478051250266)):

> Ah I see, this is because there is a difference between Windows' `cmd.exe \C "cargo build" "file1" "file2"` and Unix's `sh -c "cargo build" "file1" "file2"`
> 
> In Unix, the file list is passed as parameters to `cargo build` only when `$1` is explicitly specified; while Windows doesn't support `%*` used with `cmd \C`, which only can be used in a `.bat` file, and this results in passing the entire file list to `cargo build`.

**Comment by ndtoan96** [comment]
I want to ask a question before diving into this issue: should we support `%1`, `%*`, `%SOME_VAR%` on Windows, or we use the same syntax with Unix.

If we use the same syntax with Unix then I think we can leverage this crate https://crates.io/crates/shellexpand

If you want to support Windows style syntax then I'll think of some other way.

**Comment by sxyazi** [comment]
I think if Windows had a built-in way to support it, similar to Unix's `sh -c`, we wouldn't need to parse it ourselves.

AFAIK, `shellexpand` seems to only expand paths and doesn't support syntax like `$1`.

And, it's not clear how it handles multiple statements and nesting, similar to:

```bash
sh -c "sh -c 'echo $1; echo 123'; echo 456" "a" "b"
```

**Comment by ndtoan96** [comment]
I'm thinking of building context from arguments (`"1" => args[0]`, `"2" => args[1]`, `"*" => args.join(" ")`,...) then use `shellexpand` to expand the command for Windows.

**Comment by sxyazi** [comment]
I just do a simple test, and seems it doesn't handle nested and escaped issues very well:

```rust
fn context(s: &str) -> Result<Option<&'static str>, &'static str> {
	match s {
		"1" => Ok(Some(r#" "foo" "#)),
		_ => Ok(None),
	}
}
let x = shellexpand::env_with_context(r#" cmd.exe \C "echo $1" "#, context).unwrap();
println!("{}", x);
```

Expected:

```
cmd.exe \C "echo  \"foo\" "
```

Actual:

```
cmd.exe \C "echo  "foo" "
```

This could lead to potential injection vulnerabilities. I think creating temporary files might be the only viable option at the moment, or perhaps attempting to create and execute them in memory?

**Comment by sxyazi** [comment]
> The other uneasy option is to make something like shellexpand but with Windows syntax. It's a bit more complicated but we can reuse it for opener.

I have thought about and actually attempted this approach -- just parsing the quotes in the command and extracting the levels, and escaping the new `$1` string to be replaced, was already quite complex.

It was no less difficult than reimplementing a shell interpreter, and there were always some edge cases that couldn't be handled.

This was my attempt at the time, and it's quite clear it has failed 🤣

https://github.com/sxyazi/yazi/pull/45/commits/19465f0e9f7932344a585a17165e546832eccb03#diff-9bb8cc442c599e7891e529928a6320332353d3c02a740a5fa1ba852f49fa63a8

**Comment by ndtoan96** [comment]
How about making use of `std::process::Command` itself. We split the command into parts. If one part is "$1" or "%1" then we call `command.arg(args[0])`, else `command.arg(part)`.

**Comment by sxyazi** [comment]
The current argument is not whether to use `cmd.exe \C` or `std::process::Command`. In essence, `cmd.exe \C` also uses `Command` for creation.

The current issue is how to check if the user's `exec` contains placeholders like `$1`, which requires the ability to differentiate between variables and strings, as well as, if possible, the ability to handle nested cases.

**Comment by ndtoan96** [comment]
I tried the temporary file approach but it's not exactly easy. Since the process is spawn, we have to think of when to delete the temporary file. I would not prefer this approach. It's not elegant to say the least.

> I have thought about and actually attempted this approach -- just parsing the quotes in the command and extracting the levels, and escaping the new $1 string to be replaced, was already quite complex.
It was no less difficult than reimplementing a shell interpreter, and there were always some edge cases that couldn't be handled.

This picks my interest. Maybe I'll try to make a command expander library, it's not that difficult in my mind though. Perhaps I don't have enough experience to feel the difficulty yet, let's see.

**Comment by ndtoan96** [comment]
Well, took me a whole day to make this library: https://github.com/ndtoan96/cmdexpand/tree/main. Only supports Windows syntax (not exactly because we can use `%*` and `%@` just like Linux) for now but I plan to add Linux syntax support later.

I tested it with `yazi` on [this branch](https://github.com/ndtoan96/yazi/tree/command_windows) and it works quite well.

There're more refactoring, documentation and other stuffs to do to make it solid.

**Comment by sxyazi** [comment]
Looks quite amazing! I'll find a Windows system and try it out soon.
I want to include its Windows part in Yazi directly and make some simplifications. Do you think this is a good idea?
