### ISSUE TITLE
Keymap find [query] doesn't work

### ISSUE THREAD

**Issue by Etavioxy** [sxyazi/yazi#1929]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

alacritty

### `yazi --debug` output

```Shell
no need
```

### Describe the bug

add the keymap

`{ on = [ "t", "a" ], run = 'find a --smart',            desc = "Find with letter" },`

I tried debugging and outputted the query in both files. I found that find.rs had a query value, but find_do.rs did not.

yazi-core\src\tab\commands\find.rs
yazi-core\src\tab\commands\find_do.rs

yazi.log
[yazi.log](https://github.com/user-attachments/files/17847629/yazi.log)

### Minimal reproducer

```
[manager]
prepend_keymap = [
	{ on = [ "t", "a" ], run = 'find a --smart',            desc = "Find with letter" },
}
```

### Anything else?

https://github.com/sxyazi/yazi/blob/ea6e50cc9b81432b814719feba21c13b2005410a/yazi-core/src/tab/commands/find.rs#L24C1-L45C2

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
Use `find_do a --smart` instead of `find a --smart` – this is a documentation error, will create a commit to fix it.
