### ISSUE TITLE
%APPDATA%/local/wezterm/wezterm-blob-release-* directory taking up too much space (15 GB at one point) 

### ISSUE THREAD

**Issue by ngomkhang134** [sxyazi/yazi#1931]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

wezterm

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (7c445ce 2024-09-04)
    Debug  : false
    OS     : windows-x86_64 (windows)

Ya
    Version: 0.3.3 (7c445ce 2024-09-04)

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : None
    EDITOR             : None
    VISUAL             : None
    YAZI_FILE_ONE      : Some("C:\\Program Files\\Git\\usr\\bin\\file.exe")
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "nvim %*", block: true, orphan: false, desc: "nvim", for_: None, spread: true })
    block  : Some(Opener { run: "nvim %*", block: true, orphan: false, desc: "nvim", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : program not found
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file             : 5.45
    ueberzugpp       : program not found
    ffmpegthumbnailer: program not found
    magick           : 7.1.1-39
    fzf              : 0.56.0
    fd               : 10.2.0
    rg               : 14.1.0
    chafa            : program not found
    zoxide           : 0.9.6
    7z               : program not found
    7zz              : program not found
    jq               : 1.7.1
```

### Describe the bug

wezterm caching images too often when scrolling through image's previews in yazi .
Yazi has a cache directory in C:\Users\Dell\AppData\Local\Temp\yazi but when i scroll through images, it also get cached into C:\Users\Dell\AppData\Local\wezterm\wezterm-blob-lease-itAw1SkV , the problem is ... it caches everytime i go to an image, even images it has cached before. And it also creates another file

https://github.com/user-attachments/assets/21b7d7ee-b62b-4e91-bb23-c0bf5fbb63c2

 that has 3.6 MB as it does so, So the folder's size grows really fast .At one point reaching 15 GB, before i delete it. 

### Minimal reproducer

-install latest wezterm nightly-version (wezterm 20241119-101432-4050072d) through the setup.exe in [here](https://wezfurlong.org/wezterm/install/windows.html)
-scroll through images and check C:\Users\Dell\AppData\Local\wezterm\wezterm-blob-lease-* 

### Anything else?

https://github.com/user-attachments/assets/a0e96a0b-c214-410d-bf5d-b67a2e541e98

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
Yazi doesn't instruct WezTerm to create these caches in any way, nor is there any way to tell WezTerm not to cache them, so it's pretty clear that this is an issue on WezTerm's end, and I don't think there's anything that can be fixed on Yazi's side.

Closing as not Yazi and not doable

**Comment by ngomkhang134** [comment]
can you replicate this on your end? 
i did try to download wezterm in wsl,open wezterm through wsl then go to the images, and it still creates those cache files (in /home/pamhan/.cache/wezterm/wezterm-blob-lease-cft0g2F1/) 
so i think not only windows but linux also has this issue, i think you're using linux , does wezterm creates those caches in your machine?
![Screenshot 2024-11-22 094501](https://github.com/user-attachments/assets/3f7a3732-287d-44e4-bf42-f2b1ce20e561)
