### ISSUE TITLE
Focus cursor on the file after moving it to a target dir

### ISSUE THREAD

**Issue by exquo** [sxyazi/yazi#1950]
### `yazi --debug` output

```Shell
n/a
```

### Please describe the problem you're trying to solve

After moving a file to a new location (focusing the cursor on the file, pressing `x`, then navigating to a different directory, and pressing `p`), the cursor will still be on the first file in the directory. In some situations, it would be helpful if the focus was placed on the file being moved.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

After pressing `p` the focus / cursor is placed on the new file.

### Additional context

This is useful when some additional action with the moved file needs to be taken. For example, when [xdg-desktop-portal-termfilechooser](https://github.com/GermainZ/xdg-desktop-portal-termfilechooser) uses yazi (with `--chooser-file` argument) to save a file, it is often necessary to first move the file to a different location, after which the file is selected (with `Enter`), its path is then passed to `termfilchooser`, and the file is saved at that path.
With the current situation, after moving the file (pressing `p`), it is necessary to find the new file among all the other files already in the dir, put the cursor on it, and press `Enter`. Depending on how many files are already in the dir, and how distinctively the new file is named, this might be not effortless.

Perhaps there could be a switch / argument for it. Or it could be automatically enabled when `--chooser-file` is active. But offhand it seems like this might be convenient even enabled by default.

Somewhat relevant: https://github.com/sxyazi/yazi/discussions/1136 for other suggestions to making yazi more convenient to use with termfilechooser.

Related in case this is advised to be implemented with a plugin: https://github.com/sxyazi/yazi/issues/1713#issuecomment-2389952305 Tips on `p` action code.

### Validations

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

**Comment by sxyazi** [comment]
Duplicate of https://github.com/sxyazi/yazi/discussions/1706

**Comment by exquo** [comment]
Ah, I used different keywords when searching through the existing issues. Thanks!

**Comment by exquo** [comment]
Since the linked conversation appears to be locked, I'll ask here:

Would the following work?
After pressing `p`, an emtpty file is immediately created and the cursor / focus is placed on it. Then yazi (asynchronously) copies / movies the contents of the file.
There might be potential problems if performing certain actions on the file while it is still being copied (e.g. `d` should abort the ongoing copy, etc)

**Comment by sxyazi** [comment]
Can you explain your proposal in more detail? For example, are you suggesting creating it in Yazi's file system (file list) or actually creating it on the operating system's file system? How would cutting and copying work in each case? What happens if the creation of a new file fails? What if the file is created successfully, but copying or cutting fails? When dealing with multiple files, how would copying and cutting work? Would it create only the first file or all of them?

**Comment by exquo** [comment]
This is indeed a not-so-straightforward area of operating on partially transferred files. I don't know the internal mechanics of yazi, but from a UX perspective yazi appears to already have this type of user interaction:

When copying a large file or directory to a new location, the new file shows up while the transfer is still in progress. I propose to simply place the focus / cursor on the new file. So, to answer your first question: whatever way yazi currently handles partially-transferred files would be preserved, the only difference is that the focus would be on the new file right away.

In situations when yazi would remove the new file from the listing, due to e.g. unsuccessful transfer, the cursor could be moved to another file, e.g. returned to the position before the transfer start. This however might cause some UX issues if the user was in the middle of an attempt to perform an action on the new file (e.g. trying to delete it by pressing `d`), as now the action would be applied to the file the focus has jumped to. To overcome this kind of issue, one solution might be to not remove the file from the listing until the user manually moves focus to a different file.

When transferring multiple files, any reasonable option would be fine for the purposes of this issue. For instance, placing it on the first file that has started the transfer.

**Comment by sxyazi** [comment]
Added to the [Feature requests](https://github.com/sxyazi/yazi/issues/51)

**Comment by sxyazi** [comment]
This is now supported in https://github.com/sxyazi/yazi/pull/3846 🎉🎉
