### ISSUE TITLE
Toggle yazi and terminal

### ISSUE THREAD

**Issue by Fildo7525** [sxyazi/yazi#1951]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (VERGEN_IDEMPOTENT_OUTPUT 2024-11-25)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (VERGEN_IDEMPOTENT_OUTPUT 2024-11-25)

Emulator
    Emulator.via_env: ("screen-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: X11

Desktop
    XDG_SESSION_TYPE           : Some("x11")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/bash")
    EDITOR             : Some("/usr/bin/nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.2a
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.41
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : 0.29
    fd               : No such file or directory (os error 2)
    rg               : 13.0.0
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : No such file or directory (os error 2)
    7zz              : No such file or directory (os error 2)
    jq               : 1.6


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/fildo7525/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

Let's say you want to be in one tab and run the program you wrote. That will block Yazi until the program finishes the execution. If I want to see the output, there is no way to do so. I could also change to a different directory in the second tab to do other stuff there while the program runs in the first tab.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I would like to have something similar to what is in Midnight Commander. After invoking a keymap a terminal and its output will be displayed. Running a code in the terminal will not block yazi.

### Validations

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

**Comment by sxyazi** [comment]
I haven't used Midnight Commander myself. Could you explain in more detail what this feature is like? It would be really helpful if there's a video demo.

**Comment by Fildo7525** [comment]
For most of the questions you have I do not know the answer I did not study the repository for `mc`. https://github.com/MidnightCommander/mc. This is their repo. When I wind time for it I will try to look at it. From what I saw it is written in C. I do not use windows so I cannot tell you if it works there too

**Comment by Fildo7525** [comment]
# Regarding the commands run
I went throught the code. The bottom function they use is 
```c
/* --------------------------------------------------------------------------------------------- */
/**
 * Wrapper for execvp() system call.
 */

int
my_execvp (const char *file, char *const argv[])
{
    return execvp (file, argv);
}
```
It is located in file mc/lib/utillinux.c The file is the command

It is called via  fork in the same file in function `my_systemv (const char *command, char *const argv[])`
```c
    case FORK_CHILD:
        {
            my_signal (SIGINT, SIG_DFL);
            my_signal (SIGQUIT, SIG_DFL);
            my_signal (SIGTSTP, SIG_DFL);
            my_signal (SIGCHLD, SIG_DFL);

            my_execvp (command, argv);
            my_exit (127);      /* Exec error */
        }
        MC_FALLTHROUGH;
        /* no break here, or unreachable-code warning by no returning my_exit() */
```

# Subshell

The main code is in 
```c
int
invoke_subshell (const char *command, int how, vfs_path_t **new_dir_vpath)
```

They split the flow into 2 sections when the user hits C-o and when the user enters the command in the bottom line.

**Comment by Fildo7525** [comment]
I would be up to helping you to implement the stuff, but I do not know rust.

**Comment by Fildo7525** [comment]
I do not have much time now. If I have time, I will do it during the weekend. It will probably be easiest in C.

**Comment by pablospe** [comment]
Isn't this the same issue: https://github.com/sxyazi/yazi/issues/371 ?
