### ISSUE TITLE
Image preview refuses to fall back to chafa

### ISSUE THREAD

**Issue by oredaze** [sxyazi/yazi#1952]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

st 0.9.2  /  alacritty 0.14.0

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (0.3.3_1 2024-09-14)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (0.3.3_1 2024-09-14)

Emulator
    Emulator.via_env: ("st-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: X11

Desktop
    XDG_SESSION_TYPE           : Some("x11")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "xdg-open \"$@\"", block: false, orphan: false, desc: "Open", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "Bulk rename", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.5
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.41.1

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.56.2
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.4
    zoxide           : 0.9.6
    7z               : 24.08
    7zz              : 24.08
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/rat/.local/state/yazi" directory.
```

### Describe the bug

Yazi refuses to fall back to chafa for image preview. Chafa is working when called directly in terminal. Yazi finds it in `yazi --debug` too.

Log file:
```
2024-11-26T07:42:20.593899Z  WARN yazi_adapter::emulator: [Adapter] No special environment variables detected
    at yazi-adapter/src/emulator.rs:73

  2024-11-26T07:42:20.593914Z  WARN yazi_adapter::emulator: [Adapter] Unknown TERM_PROGRAM: 
    at yazi-adapter/src/emulator.rs:87

  2024-11-26T07:42:20.593930Z  WARN yazi_adapter::emulator: [Adapter] Unknown TERM: st-256color
    at yazi-adapter/src/emulator.rs:95

  2024-11-26T07:42:20.594582Z  WARN yazi_adapter::ueberzug: ueberzugpp spawning failed: No such file or directory (os error 2)
    at yazi-adapter/src/ueberzug.rs:96
```

### Minimal reproducer

Just installed yazi and chafa in void linux. As I understand it should work out of the box?

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
"Fallback" refers to the last resort when all available protocols/tools are not suitable. In your case, since ueberzug supports X11, Yazi chose ueberzugpp.


> Yazi automatically selects the appropriate preview method for you, based on the priority from top to bottom. That's relying on the $TERM, $TERM_PROGRAM, and $XDG_SESSION_TYPE variables, make sure you don't overwrite them by mistake!

**Comment by oredaze** [comment]
What if I don't want to use ueberzugpp? It is hard to install on void linux, plus it is too heavy for my taste.
The fallback should activate if primary method is not available. That's what fallbacks are for...

**Comment by sxyazi** [comment]
If you want to force it to use chafa, try something like this:

```
XDG_SESSION_TYPE=wayland yazi
```
