### ISSUE TITLE
Note on 'cd' navigation on windows

### ISSUE THREAD

**Issue by ShrykeWindgrace** [sxyazi/yazi#196]
The variable `~` is not expanded by `cd`, and environment variables like `USERPROFILE` (equivalent of `$HOME` on *nix systems) are not expanded either.

Therefore, to my knowledge, one needs to hardcode paths for `cd` as follows:
```toml
{ on = [ "g", "h" ],       exec = "cd c:/users/username",             desc = "Go to the home directory" },
```
or (note four backslashes):
```toml
{ on = [ "g", "h" ],       exec = "cd c:\\\\users\\\\username",             desc = "Go to the home directory" },
```

**Comment by ShrykeWindgrace** [comment]
I guess the main reason that `~` does not work is this line: https://github.com/sxyazi/yazi/blob/1793d635ebae3b276c0ff1da68f8ba14bd2d42a4/shared/src/fns.rs#L10-L10. Windows has no notion of `HOME`, it uses `USERPROFILE` instead.

**Comment by Eric-Song-Nop** [comment]
You can change the `keymap.toml` file according to your system and environment as you wish, it's just a default and might not work on some systeme.

The function `expand_path` that you are pointing out is not related to this keymap.

**Comment by ShrykeWindgrace** [comment]
> You can change the `keymap.toml` file according to your system and environment as you wish, it's just a default and might not work on some systeme.

Of course I can. I am merely pointing out a solution for windows. But defaults must work! It is awkward if new users have to tinker with keymap just to make "gh/gd" keybindings work at all.

> The function `expand_path` that you are pointing out is not related to this keymap.

I am pretty sure that it is; imagine a keymap that has `exec = "cd ~"`:
- `app/src/executor.rs:56` gets a `url` in its `cd` branch (https://github.com/sxyazi/yazi/blob/1793d635ebae3b276c0ff1da68f8ba14bd2d42a4/app/src/executor.rs#L77-L77)
- then it emits `Cd(url)`
- this event is handled in `dispatch_module` (https://github.com/sxyazi/yazi/blob/1793d635ebae3b276c0ff1da68f8ba14bd2d42a4/app/src/app.rs#L120-L120)
- we call `expand_url`, and in its turn it calls `expand_path` that I linked in my previous comment

**Comment by sxyazi** [comment]
Sounds good! I'm not familiar with Windows, so I've only implemented the Unix part. Besides USERPROFILE, are there any other Windows-specific variables available? I'm interested in adding them to the `expand_path` function.

The Windows version of Yazi is still in its early stages, and I really appreciate your interest in trying it out and providing feedback!

**Comment by ShrykeWindgrace** [comment]
> Sounds good! I'm not familiar with Windows, so I've only implemented the Unix part. Besides USERPROFILE, are there any other Windows-specific variables available? I'm interested in adding them to the `expand_path` function.
 
Of course, I'll take a look.

> 
> The Windows version of Yazi is still in its early stages, and I really appreciate your interest in trying it out and providing feedback!

Let's move it further from early stages then! =)
