### ISSUE TITLE
`ps.sub("sort", ...)` or folder-specific rules

### ISSUE THREAD

**Issue by qtyra** [sxyazi/yazi#1965]
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Arch Linux 2024-09-05)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Arch Linux 2024-09-05)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: Some("a425fbebe4cf4238e48a42f724ef2208959d66cf_1732736821_412414895")
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.5a
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-40
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.2
    zoxide           : 0.9.6
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "$HOME/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

I'm trying to use yazi's size sorting as a replacement for [ncdu](https://dev.yorhel.nl/ncdu) and similar programs. 

- When using Yazi normally, I want the ~/Downloads directory to be sorted by modification time. (https://yazi-rs.github.io/docs/tips/#folder-rules achieves this).
- When cleaning up files, all directories (including `~/Downloads`) should be sorted by size (partially achieved with some modifications to https://yazi-rs.github.io/docs/tips/#folder-rules).

The best solution I got:

```lua
local function setup()
    ps.sub("cd", function()
        local cwd = cx.active.current.cwd
        -- Assuming "alphabetical" is the default
        if cwd:ends_with("Downloads") and cx.active.conf.sort_by == "alphabetical" then
            p_sort = cx.active.conf.sort_by
            p_reverse = cx.active.conf.sort_reverse
            p_dir = cx.active.conf.sort_dir_first
            ya.manager_emit("sort", { "modified", reverse = true, dir_first = false })
        else
            ya.manager_emit("sort", { p_sort, reverse = p_reverse, dir_first = p_dir })
        end
    end)
end

return { setup = setup }
```

This works for most cases except when the sort type is changed within `~/Downloads`. However I realized that any changes I make to this code won't solve the problem because there is no event I can listen for to save the previous sort type. The `cd`  event only triggers when entering a directory, so i can't track if the sort type was changed while inside `~/Downloads` (Also adding code in the `else` part to check against the previous sort type will fail in other cases which I think is a lot to write but can be deduced).

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Add a `sort` kind to the [Builtin kinds](https://yazi-rs.github.io/docs/dds/#kinds) or a configuration option that does the same. Assuming the first solution, the problem will be solved by saving the sort type inside the callback `of ps.sub("sort", ...)` and restoring it in the `else` part of the `ps.sub("cd", ...)` callback.

### Validations

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

**Comment by sxyazi** [comment]
Nice to have!

To implement it, we need to add a new kind `Sort` under `Load` here:

https://github.com/sxyazi/yazi/blob/2771aef677305b9bbaab16dda78ab666744770c1/yazi-dds/src/body/body.rs#L16

Then, when setting the sorter, publish it:

https://github.com/sxyazi/yazi/blob/2771aef677305b9bbaab16dda78ab666744770c1/yazi-core/src/tab/tab.rs#L129

Would you like to raise a PR for it?

**Comment by qtyra** [comment]
Hi @sxyazi, I actually implement the `Sort` kind to at least print the value of `sort_by` when it's changed by the user, but it had several problems. I realized that I only needed to listen when the user changed the sort type, so I overrode the default sort keymaps (the ones starting with `,`) and it worked exactly as I wanted. I leave my solution in case someone needs it.

`keymap.toml`, I use `,,` to "reactivate" the directory rules.

```toml
[manager]
prepend_keymap = [
    # ...
    { on = [ ",", "m" ], run = [ "sort modified --reverse=no", "linemode mtime", "plugin folder-rules --sync --args='hi'" ], desc = "Sort by modified time" },
    { on = [ ",", "M" ], run = [ "sort modified --reverse", "linemode mtime", "plugin folder-rules --sync --args='hi'" ], desc = "Sort by modified time (reverse)" },
    { on = [ ",", "c" ], run = [ "sort created --reverse=no", "linemode ctime", "plugin folder-rules --sync --args='hi'" ], desc = "Sort by created time" },
    { on = [ ",", "C" ], run = [ "sort created --reverse", "linemode ctime", "plugin folder-rules --sync --args='hi'" ], desc = "Sort by created time (reverse)" },
    { on = [ ",", "e" ], run = [ "sort extension --reverse=no", "plugin folder-rules --sync --args='hi'" ], desc = "Sort by extension" },
    { on = [ ",", "E" ], run = [ "sort extension --reverse", "plugin folder-rules --sync --args='hi'" ], desc = "Sort by extension (reverse)" },
    { on = [ ",", "a" ], run = [ "sort alphabetical --reverse=no --dir-first", "plugin folder-rules --sync --args='hi'" ], desc = "Sort alphabetically" },
    { on = [ ",", "A" ], run = [ "sort alphabetical --reverse", "plugin folder-rules --sync --args='hi'" ], desc = "Sort alphabetically (reverse)" },
    { on = [ ",", "n" ], run = [ "sort natural --reverse=no", "plugin folder-rules --sync --args='hi'" ], desc = "Sort naturally" },
    { on = [ ",", "N" ], run = [ "sort natural --reverse", "plugin folder-rules --sync --args='hi'" ], desc = "Sort naturally (reverse)" },
    { on = [ ",", "s" ], run = [ "sort size --reverse=no", "linemode size", "plugin folder-rules --sync --args='hi'" ], desc = "Sort by size" },
    { on = [ ",", "S" ], run = [ "sort size --reverse", "linemode size", "plugin folder-rules --sync --args='hi'" ], desc = "Sort by size (reverse)" },
    { on = [ ",", "r" ], run = [ "sort random --reverse=no", "plugin folder-rules --sync --args='hi'" ], desc = "Sort randomly" },
    { on = [ ",", "," ], run = [ "plugin folder-rules --sync" ], desc = "Return to normality" },
]
```

`folder-rules.yazi/init.lua`

```lua
local M = {}

local function execute_rules(cx)
    local cwd = cx.active.current.cwd
    if cwd:ends_with("Downloads") then
        ya.manager_emit("sort", { "modified", reverse = true, dir_first = false })
    else
        ya.manager_emit("sort", { "alphabetical", reverse = false, dir_first = true })
    end
end

function M.setup()
    ps.sub("cd", function()
        if not user then
            execute_rules(cx)
        end
    end)
end

function M:entry(args)
    user = args[1] and true or false
    if not user then -- refresh
        execute_rules(cx)
    end
end

return M
```

**Comment by sxyazi** [comment]
Nice to see you've found a solution!

> but it had several problems

Could you tell me what problems have you had? Is this feature request still valuable to you - can I close it?

**Comment by qtyra** [comment]
@sxyazi you can close it, I don't need the feature request anymore.

> Could you tell me what problems have you had?

For example `ya.manager_emit(“sort”, { “modified”, ...})` changed the sort type to “none”, publish a SortBy object below `f.files.set_sorter()` made the callback of `ps.sub(“sort”, ...)` to be called many more times than I expected and that I couldn't 100% know if the sort was changed by the user anyway (that's why overriding the default keymaps works perfectly). But as I said, it doesn't matter because the problem is solved.

**Comment by sxyazi** [comment]
Ah I see. Thanks for the explanation!
