### ISSUE TITLE
Not obvious if we are in a `--block` shell mode.

### ISSUE THREAD

**Issue by jcguu95** [sxyazi/yazi#197]
```
	{ on = [ ";" ],         exec = "shell",                  desc = "Run a shell command" },
	{ on = [ ":" ],         exec = "shell --block",          desc = "Run a shell command (block the UI until the command finishes)" },
```

Pressing `:` and `;` brings the user to windows with the same message `"Shell:"`. I suggest that we can make it `"Shell (block):"` for the later.

**Comment by sxyazi** [comment]
Handled by https://github.com/sxyazi/yazi/commit/ec261a2708b6638a03797a8071b25c4db359b065, closing then
