### ISSUE TITLE
`mtime` sorting not updated correctly. Probably a caching issue.

### ISSUE THREAD

**Issue by dawsers** [sxyazi/yazi#1981]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty v0.37.0

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (4bd8b0b4 2024-12-03)
    Debug  : true
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.82.0 (f6e511ee 2024-10-15)

Ya
    Version: 0.3.3 (81ce040 2024-11-06)

Emulator
    Brand.from_env      : Some(Kitty)
    Emulator.detect     : Emulator { kind: Left(Kitty), light: false }
    Emulator.detect_full: Ok(Emulator { kind: Left(Kitty), light: false })

Adapter
    Adapter.matches: Kgp

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: Some("12f9a0d0b93f691d4d9923716557154d74777b0a_1733218567_1364812240")
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL           : Some("/usr/bin/bash")
    EDITOR          : Some("/usr/bin/nvim")
    VISUAL          : Some("/usr/bin/nvim")
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: Some("--no-mouse --height 50% -1 --reverse --multi --inline-info --preview=\'[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (bat --color always {} || cat {}) 2> /dev/null | head -300\' --preview-window=\'up:70%:hidden:wrap\' --bind=\'f3:toggle-preview\'")

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR (block)", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR (block)", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR (block)", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file          : 5.46
    ueberzugpp    : No such file or directory (os error 2)
    ffmpeg/ffprobe: 7.1 / 7.1
    pdftoppm      : 24.11.0
    magick        : 7.1.1-41
    fzf           : 0.56.3
    fd/fdfind     : 10.2.0 / No such file or directory (os error 2)
    rg            : 14.1.1
    chafa         : 1.14.3
    zoxide        : 0.9.6
    7z/7zz        : 17.05 / No such file or directory (os error 2)
    jq            : 1.7.1

Clipboard
    wl-copy/paste: 2.2.1 / 2.2.1
    xclip        : No such file or directory (os error 2)
    xsel         : No such file or directory (os error 2)
```

### Describe the bug

`mtime` seems to be broken in the caching system. If I copy a file to a directory, the directory's `mtime` should be updated to the time of the action. The caching system doesn't trigger a reload and keeps the original `mtime` for the directory. I can move out of the directory, back in, etc, and it won't trigger a reload (probably because it still thinks the cache is valid). But if I exit yazi or delete all the tabs referencing the directory and go back in, its `mtime` is correct again.

### Minimal reproducer

Using `mtime` sorting mode, open yazi

- Go to `/tmp`
- Create a `tmp` directory `:mkdir tmp`
- Create a file: `:touch file`
- Now the file should be sorted as newer than `tmp`. It is.
- Yank the file and copy it into `tmp`
- Go back from `tmp` to `/tmp`
- The file is still sorted as newer than `tmp`, but `tmp` should be newer, as we modified its `mtime` by copying something inside.
- If you exit yazi or delete every tab referencing `/tmp`, and go back to `/tmp`, we get the correct sorting and time for the directory.

So it seems the sorting cache doesn't get invalidated when copying something into a directory with `mtime` sorting.

### Validations

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by dawsers** [comment]
OK, I understand. You can close it with "not planned" if you want, so anybody searching can find the explanation here.

Thank you.

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/1987
