### ISSUE TITLE
zoxide does not find network folders

### ISSUE THREAD

**Issue by bobblkabb** [sxyazi/yazi#1992]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot 1.19.0

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (git20241106.6001f3c 2024-11-06)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: No such file or directory (os error 2)

Emulator
    Emulator.via_env: ("foot", "")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect : Foot

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: Some("_1733377584_980511530")
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/fish")
    EDITOR             : Some("helix")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default     : Some(Opener { run: "hx \"$@\"", block: true, orphan: false, desc: "helix", for_: None, spread: true })
    block-create: Some(Opener { run: "hx \"$@\"", block: true, orphan: false, desc: "helix", for_: None, spread: true })
    block-rename: Some(Opener { run: "hx \"$@\"", block: true, orphan: false, desc: "helix", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.41.1

Dependencies
    file             : 5.46
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-41
    fzf              : 0.56
    fd               : 10.2.0
    fdfind           : No such file or directory (os error 2)
    rg               : 14.1.1
    chafa            : 1.14.5
    zoxide           : 0.9.6
    7z               : 24.09
    7zz              : 24.09
    jq               : 1.7.1
```

### Describe the bug

zoxide does not work so well with mounted Windows shares. Folders are not found, although I have been on them many times with yazi.
e.g. windows share mounted as  /mnt/drive/ and trying to access/mnt/drive/folder/foldersomething 

However, a network folder is found if I had access in the shell before.

### Minimal reproducer

Press 'z' (zoxide dialogue opens)
Type 'fold...' but 'folder' or 'foldersomething' aren't found

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
I don't think this is a Yazi bug because all Yazi does is simply call `zoxide query -i` to bring up the `zoxide` interactive UI:

https://github.com/sxyazi/yazi/blob/c7d9265d25e51ab2ad7b4524b2be52e6b5bdf42a/yazi-plugin/preset/plugins/zoxide.lua#L91-L101

Please report this to `zoxide` for support. Closing as not Yazi and nothing can be done here
