### ISSUE TITLE
Color Palettes in Theming?

### ISSUE THREAD

**Issue by jcguu95** [sxyazi/yazi#200]
Instead of

```
[status]
primary	  = { normal = "#80AEFA", select = "#CD9EFC", unset = "#FFA577" }
```

I think it would be easier to allow variable bindings. For example,

```
[palette]
red = "#80AEFA"
green = "#CD9EFC"
white = "#FFA577"

[status]
primary	  = { normal = red, select = green, unset = white }
```

After all, there should not be too many colors in a beautiful palettes.

**Comment by sxyazi** [comment]
New theme system will allow setting colors individually for each component. See https://github.com/sxyazi/yazi/pull/161/files#diff-eb0af7086554c274cf62640c82fc124cd4d0fc9b55ee2635eca5c0f9e4f24926.
