### ISSUE TITLE
scrolling in the preview of a json file on windows messes up the terminal

### ISSUE THREAD

**Issue by sibouras** [sxyazi/yazi#2016]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

windows-terminal

### `yazi --debug` output

```Shell
Yazi
    Version: 0.4.0 (b8b3ab9 2024-12-08)
    Debug  : false
    Triple : x86_64-pc-windows-msvc (windows-x86_64)
    Rustc  : 1.83.0 (90b35a62 2024-11-26)

Ya
    Version: 0.4.0 (b8b3ab9 2024-12-08)

Emulator
    Brand.from_env      : Some(Microsoft)
    Emulator.detect     : Emulator { kind: Left(Microsoft), light: false, cell_size: None }
    Emulator.detect_full: Ok(Emulator { kind: Right(Unknown { kgp: false, sixel: false }), light: false, cell_size: None })

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL           : None
    EDITOR          : Some("nvim")
    VISUAL          : None
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(Opener { run: "hx %*", block: true, orphan: false, desc: "hx", for_: None, spread: true })
    block-create: Some(Opener { run: "hx %*", block: true, orphan: false, desc: "hx", for_: None, spread: true })
    block-rename: Some(Opener { run: "hx %*", block: true, orphan: false, desc: "hx", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : program not found
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file          : 5.45
    ueberzugpp    : program not found
    ffmpeg/ffprobe: 7.1 / 7.1
    pdftoppm      : program not found
    magick        : program not found
    fzf           : 0.56.3
    fd/fdfind     : 10.2.0 / program not found
    rg            : 14.1.1
    chafa         : program not found
    zoxide        : 0.9.6
    7z/7zz        : 24.08 / program not found
    jq            : 1.7.1

Clipboard
    wl-copy/paste: program not found / program not found
    xclip        : program not found
    xsel         : program not found
```

### Describe the bug

when scrolling the preview of a long json file on windows, the terminal messes up(see the gif)

https://github.com/user-attachments/assets/f0da9143-7e1e-481f-bf6e-40a065b6bb9d

i tried using [jaq](https://github.com/01mf02/jaq) instead of jq and it works.

```diff
 function M:peek(job)
-       local child = Command("jq")
+       local child = Command("jaq")
                :args({
-                       "-C",
+                       "--color=always",
```

https://github.com/user-attachments/assets/ff693f9b-b945-4a58-a936-8cec5950f796

### Minimal reproducer

scroll on any long json file

### Anything else?

tested it on wsl and the bug doesn't happen, also the same bug also happens on zip files with the builtin previewer, but im using [ouch.yazi](https://github.com/ndtoan96/ouch.yazi) and it works fine

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sibouras** [comment]
just tried it on that windows terminal preview and the bug is still there, here's the json file(it happens on every json and zip file)


[lazy-lock.json](https://github.com/user-attachments/files/18063751/lazy-lock.json)

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/2017

**Comment by sibouras** [comment]
its fixed thanks!

**Comment by sxyazi** [comment]
Released a new version with the fix https://github.com/sxyazi/yazi/releases/tag/v0.4.1 🎉
