### ISSUE TITLE
Unable to invoke `?` anymore

### ISSUE THREAD

**Issue by musjj** [sxyazi/yazi#203]
Both `/` and `?` invokes the `Find:` popup. Maybe it's some kind of shift modifier issue?

Tested on 6497df3a6f8e26312c0d0effc853b6b8348c3004

EDIT: `d` and `D` is properly distinguished, so I guess not?

**Comment by ndtoan96** [comment]
Which operating system and terminal are you using? I made a PR recently to fix the exact same issue on Windows. I tested it on Windows and Linux. Both works properly.

**Comment by sxyazi** [comment]
Seems to be a misinterpretation caused by the title. Please try https://github.com/sxyazi/yazi/commit/58df82498f14aaf3357b5b25295896d0b65160fd

**Comment by musjj** [comment]
Never mind, I was being dumb. It looks like the help menu is now binded to `~` (it was previously binded to `?`).
