### ISSUE TITLE
Paste into g<space> removes backquotes

### ISSUE THREAD

**Issue by panda7789** [sxyazi/yazi#2033]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Windows terminal 1.21.3231 with PowerShell 7.4.6

### `yazi --debug` output

```Shell
Yazi
    Version: 0.4.2 (c78f39b 2024-12-11)
    Debug  : false
    Triple : x86_64-pc-windows-msvc (windows-x86_64)
    Rustc  : 1.83.0 (90b35a62 2024-11-26)

Ya
    Version: 0.4.2 (c78f39b 2024-12-11)

Emulator
    Brand.from_env      : None
    Emulator.detect     : Emulator { kind: Right(Unknown { kgp: false, sixel: false }), light: false, cell_size: None }
    Emulator.detect_full: Ok(Emulator { kind: Right(Unknown { kgp: false, sixel: false }), light: false, cell_size: None })

Adapter
    Adapter.matches: Chafa

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

NVIM
    NVIM          : false
    Neovim version: program not found

Variables
    SHELL           : None
    EDITOR          : None
    VISUAL          : None
    YAZI_FILE_ONE   : Some("C:\\Program Files\\Git\\usr\\bin\\file.exe")
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(Opener { run: "code %*", block: false, orphan: true, desc: "code", for_: None, spread: true })
    block-create: Some(Opener { run: "code -w %*", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })
    block-rename: Some(Opener { run: "code -w %*", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })

Multiplexers
    TMUX               : 0
    tmux version       : program not found
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file          : 5.45
    ueberzugpp    : program not found
    ffmpeg/ffprobe: 5.1.2 / 5.1.2
    pdftoppm      : 24.07.0
    magick        : program not found
    fzf           : 0.54.2
    fd/fdfind     : 10.1.0 / program not found
    rg            : 14.1.0
    chafa         : program not found
    zoxide        : 0.9.4
    7z/7zz        : 19.00 / program not found
    jq            : 1.7.1

Clipboard
    wl-copy/paste: program not found / program not found
    xclip        : program not found
    xsel         : program not found
```

### Describe the bug

When I press g\<space\> command to open path input and then i paste path that looks like this: C:\Windows it is pasted as C:Windows, the backspace \ is missing.
It was already mentioned in #1534 but it was ignored and conversation focused on ß.

It is very unpractical, because in powershell, it accepts both / and \ characters in path.

https://github.com/user-attachments/assets/69a67ec7-fd1f-4472-b2bc-bdb6c35c8acc

### Minimal reproducer

copy "C:\Windows"
g\<space\>
paste
-> the \ are missing and path is incorrect

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
> It was already mentioned in https://github.com/sxyazi/yazi/issues/1534 but it was ignored and conversation focused on ß.

Are you sure your issue is the same as https://github.com/sxyazi/yazi/issues/1534, i.e. you're also using a German keyboard layout instead of an English layout? 

If so, as I mentioned in that issue, this cannot be fixed within Yazi because it's not a problem with Yazi itself. It's an issue with the `crossterm` crate that Yazi uses, which is not correctly reporting the `\` key, and this needs to be fixed upstream.

The good news is that there is already a PR in the `crossterm` repository to fix this, https://github.com/crossterm-rs/crossterm/pull/937

**Comment by panda7789** [comment]
I tried build yazi with crossterm fix and it works.
Thank you 😊
