### ISSUE TITLE
A more visually explicit cut/yank mode

### ISSUE THREAD

**Issue by musjj** [sxyazi/yazi#204]
We can mark files to be yanked by using `yank` or `yank --cut`, but it's impossible to tell visually which file has been marked. An explicit visual marker for yanked/cut files like in `select` or `visual_mode` would be useful.

**Comment by sxyazi** [comment]
>  Display of the number of currently selected/cut/copied files

Are you referring to this feature? which is documented in the [Feature Requests](https://github.com/sxyazi/yazi/issues/51)

**Comment by musjj** [comment]
Never mind, I was being dumb. It looks like that the help menu is binded to `~` now (previously, it was `?`).

**Comment by musjj** [comment]
Showing the number would be useful, but I was talking about highlighting the files that is being yanked/cut with an explicit color (like in select mode).

**Comment by sxyazi** [comment]
I'm not quite sure what you mean. Before you yank/cut, you need to select the file, and the selected file will be highlighted with a background color.

**Comment by musjj** [comment]
Yes, but it's impossible to distinguish between something that is *just* selected and something that is actually being yanked.

Having visual feedback for file operations is always nice since it helps prevents user errors.

Also if you choose to yank *without* selecting, now you don't have any visual feedback at all.

**Comment by sxyazi** [comment]
Hi @musjj, I want to implement it, but "visual feedback" is somewhat unclear to me.

I would like to know if there are any file managers that have implemented it and make it a reference. It would be appreciated if you could provide a screenshot of it. :)

**Comment by musjj** [comment]
It's the same as visual/select mode but just differently colored, nothing special.

An example with `lf`:

Select mode:
![image](https://github.com/sxyazi/yazi/assets/72612857/16233f14-02e6-4b4e-91ff-96a79bfb31ae)

Cut mode
![image](https://github.com/sxyazi/yazi/assets/72612857/9cdff9d6-1914-401f-87c2-36cb818a6339)

Yank mode:
![image](https://github.com/sxyazi/yazi/assets/72612857/b95d5214-346e-4886-a35f-f253504d04f0)

**Comment by sxyazi** [comment]
Sounds good, I like this idea, and it should be straightforward to implement!

I have one last question – if a file is both selected and yanked, what color should it be displayed in? Should it be "select over yank", or should we use a different third color?

**Comment by musjj** [comment]
I'd say that it should have the same color as a yank for simplicity.

But maybe if you want to be explicit about it, you can experiment with having two rows of highlights like this (just a mockup):

![image psd](https://github.com/sxyazi/yazi/assets/72612857/a7236e6e-7378-494f-b1fa-e205f2b70241)

This would make it clear that a file is both selected and cut without having to increase the number of color-coding.

**Comment by sxyazi** [comment]
I tried using 2 cells, but I couldn't get it to stay in the center of the divider, seems like using just one color makes sense. 🤣

<img width="309" alt="image" src="https://github.com/sxyazi/yazi/assets/17523360/4f45c0e3-eee6-4afa-9def-da6de559379a">

**Comment by ndtoan96** [comment]
If color is not good enough, we can think of changing font. For example: yanked files are underlined, cut files are gray out (dimmed text).

**Comment by Qwerty-Space** [comment]
Perhaps a selected file should also be offset, like in ranger.  
So if it's selected it's purple+offset, if it's yanked it's yellow, if it's selected and yanked it's yellow+offset

Example of a selected file compared to an unselected file in ranger:
![image](https://github.com/sxyazi/yazi/assets/6967592/41f69de4-6304-4f2c-8df5-fc92c100069d)
