### ISSUE TITLE
Opening folder location directly and calling 'quit' does not drop shell to folder

### ISSUE THREAD

**Issue by MrDwarf7** [sxyazi/yazi#2051]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Wezterm --version = wezterm 20240203-110809-5046fc22

### `yazi --debug` output

```Shell
Yazi
    Version: 0.4.1 (2275719 2024-12-10)
    Debug  : false
    Triple : x86_64-pc-windows-msvc (windows-x86_64)
    Rustc  : 1.83.0 (90b35a62 2024-11-26)

Ya
    Version: 0.4.1 (2275719 2024-12-10)

Emulator
    Brand.from_env      : Some(WezTerm)
    Emulator.detect     : Emulator { kind: Left(WezTerm), light: false, cell_size: None }
    Emulator.detect_full: Ok(Emulator { kind: Right(Unknown { kgp: false, sixel: false }), light: false, cell_size: None })

Adapter
    Adapter.matches: Iip

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

NVIM
    NVIM          : false
    Neovim version: 0.10.2

Variables
    SHELL           : Some("C:\\Applications\\PowerShell_start\\Powershell_linked\\pwsh.exe")
    EDITOR          : Some("nvim")
    VISUAL          : Some("nvim")
    YAZI_FILE_ONE   : Some("C:\\Program Files\\Git\\usr\\bin\\file.exe")
    YAZI_CONFIG_HOME: Some("C:\\Users\\MY_USERNAME\\dotfiles\\.config\\yazi")
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(Opener { run: "nvim %*", block: true, orphan: false, desc: "nvim (block)", for_: None, spread: true })
    block-create: Some(Opener { run: "nvim %*", block: true, orphan: false, desc: "nvim (block)", for_: None, spread: true })
    block-rename: Some(Opener { run: "nvim %*", block: true, orphan: false, desc: "nvim (block)", for_: None, spread: true })

Multiplexers
    TMUX               : 0
    tmux version       : program not found
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file          : 5.45
    ueberzugpp    : program not found
    ffmpeg/ffprobe: 7.1 / 7.1
    pdftoppm      : 24.08.0
    magick        : 7.1.1-41
    fzf           : 0.56.3
    fd/fdfind     : 10.2.0 / program not found
    rg            : 14.1.1
    chafa         : program not found
    zoxide        : 0.9.6
    7z/7zz        : 24.09 / program not found
    jq            : 1.7.1

Clipboard
    wl-copy/paste: program not found / program not found
    xclip        : program not found
    xsel         : program not found

# Note - small bug: 
post-running `yazi --debug` leaves a trailing '\' on Windows (I would assume this is an escape char - may be not needed in pwsh/powershell)
```

### Describe the bug

Calling `yazi C:\temp\' will correctly place the user into the folder (C:\temp).
Quitting yazi via the use of the quit command (See below on the bind I use etc.) results in yazi dropping to the current shell directory, not to the directory in the current yazi viewport, as it would when just calling 'yazi' from the commandline and navigating to a directory, then dropping via Quit.

Providing keybinds currently used - might be a conflict in binds, or might be state related.

```toml
# Swapping the C-c and q keys, drop via C-c now
[[manager.prepend_keymap]]
on = "Q"
run = "quit"
desc = "Quit the process"

[[manager.prepend_keymap]]
on = "q"     
run = "quit --no-cwd-file"
desc = "Quit the process without outputting cwd-file" 
```

yazi config files are also available in my dotfiles repo under '$ROOT/.config/yazi' if you need/want to check other configuration(s).

### Minimal reproducer

Baseline:
Run yazi, or the provided function call/alias from documentation ('y').
Navigate to directory.
Hit binding mapped to `run = "quit"` (Mine is mapped to Q/<S-q>)
Observe that yazi exits, placing the shell into the directory within the viewport.

Bug:
Run yazi, or the provided function call/alias from documentation ('y').
Call `yazi C:\temp\' (Or any folder directly).
Hit binding mapped to `run = "quit"` (Mine is mapped to `Q`/`S-Q`)
Observe that yazi exits, but does not drop to the viewport directory, instead dropping to the original starting location. The same as if 'quit --no-cwd-file' is used (For me is lowercase q).

Reproducible with both the provided function call/alias & with calling `yazi`

### Anything else?

Happy to provide further details if required - may be able to have a look at this if author can assist on whether this is likely to be a binding-type issues or a state-type issues.

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
> Call `yazi C:\temp\' (Or any folder directly).

No, you need to use `y C:\temp\` instead of `yazi C:\temp\`, because the feature of changing the current working directory when exiting is provided by the `y` shell wrapper, not by `yazi` itself.
