### ISSUE TITLE
zoxide plugin sometimes gets stuck on `zoxide add ...` if the pathes are not valid

### ISSUE THREAD

**Issue by c02y** [sxyazi/yazi#2053]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

alacritty 0.14.0 or kitty 0.37.0

### `yazi --debug` output

```Shell
$ yazi --debug

Yazi
    Version: 0.4.1 (Arch Linux 2024-12-10)
    Debug  : false
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.83.0 (90b35a62 2024-11-26)

Ya
    Version: 0.4.1 (Arch Linux 2024-12-10)

Emulator
    Brand.from_env      : Some(Kitty)
    Emulator.detect     : Emulator { kind: Left(Kitty), light: false, cell_size: Some((12, 26)) }
    Emulator.detect_full: Ok(Emulator { kind: Left(Kitty), light: false, cell_size: Some((12, 26)) })

Adapter
    Adapter.matches: Kgp

Desktop
    XDG_SESSION_TYPE           : Some("x11")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

NVIM
    NVIM          : false
    Neovim version: 0.10.2

Variables
    SHELL           : Some("/usr/bin/fish")
    EDITOR          : Some("vim")
    VISUAL          : None
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: Some("-e -m -0 --reverse --no-sort --preview \'fish -c \"fzf_previewer {}\"\' --preview-window=bottom:wrap --bind ctrl-a:select-all,ctrl-d:deselect-all,ctrl-t:toggle-all")

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : 2
    tmux version       : 3.4
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.41.2

Dependencies
    file          : 5.46
    ueberzugpp    : No such file or directory (os error 2)
    ffmpeg/ffprobe: 7.1 / 7.1
    pdftoppm      : 24.11.0
    magick        : 7.1.1-41
    fzf           : 0.56.3
    fd/fdfind     : 10.2.0 / No such file or directory (os error 2)
    rg            : 14.1.1
    chafa         : No such file or directory (os error 2)
    zoxide        : 0.9.6
    7z/7zz        : 17.05 / No such file or directory (os error 2)
    jq            : 1.7.1

Clipboard
    wl-copy/paste: No such file or directory (os error 2) / No such file or directory (os error 2)
    xclip        : 0.13
    xsel         : No such file or directory (os error 2)
```

### Describe the bug

I use alacritty+yazi or kitty+yazi as my default program for folder, mime info is `inode/directory = yazi.desktop`.

For example, when I use `Open Book Folder` in Calibre, it opens the terminal+yazi, there will be several zoxide processes running in the background and it gets stuck since the paths are not valid, it is Calibre's issue, but I'm not talking about why the paths are not valid here, I'm talking about the zoxide gets stuck if the paths are not valid.

I personally don't care if zoxide plugin fails, if it updates the db OK, then it is fine, if it fails, I'm OK if zoxide wouldn't handle it.

### Minimal reproducer

Set `inode/directory = yazi.desktop`, `Open Book Folder` in Calibre, I use `~/CalibreLibrary` as the library variable in its settings instead of the default `~/Calibre Library`, maybe this triggered the `paths are not valid` issue, not sure yet.

But I don't think this issue needs this reproduce process.

`~/.config/yazi/init.lua`:

`require("zoxide"):setup({ update_db = true })`

### Anything else?

The `/home/chz/file` in the following picture is not valid.

![image](https://github.com/user-attachments/assets/1430c365-3662-4e12-8c04-8f74e67a8e40)

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by c02y** [comment]
**UPDATER**:
The issue of `Open Book Folder` in Calibre it opens HOME directory instead of the `~/CalibreLibrary` is actually the yazi's problem.

I use TUI file manager like ranger or GUI file manager like DoubleCmd, `Open Book Folder` runs fine, now this is two bugs issue, one is zoxide plugin, one is yazi itself.

**Comment by sxyazi** [comment]
No debug info

**Comment by c02y** [comment]
You need debug info for zoxide plugin getting stuck on handling errors?

Sure, I'll attach debug info. You don't have to close it.

Check the debug info part, please.

**Comment by sxyazi** [comment]
Yeah I need debug info to confirm your zoxide version. Reopened

**Comment by sxyazi** [comment]
I can't reproduce it on either my macOS or Linux VM. 

When you set `update_db=true`, Yazi just runs a shell command in the background when switching directories:

https://github.com/sxyazi/yazi/blob/f4eef99f7e6b82be380a7d37c25e58f19b7ec39e/yazi-plugin/preset/plugins/zoxide.lua#L66-L74

So I tried hardcoding the path from your screenshot, but it didn't result in any failed tasks, because these shells run as orphans, detached from Yazi's task scheduler:

```lua
 		ya.manager_emit("shell", { 
 			orphan = true, 
 			confirm = true, 
 			"zoxide add '/home/chz/file:'", 
 		}) 
```

**Comment by c02y** [comment]
Is there anything like log I can provide for you to debug this issue?

**Comment by sxyazi** [comment]
When you use `Open Book Folder`, what path does Calibre pass to Yazi? Is it a valid path? If you run Yazi with this path directly in the terminal without Calibre, can you reproduce it? I don't use Calibre myself, so I'm not sure what it does behind the scenes.

**Comment by c02y** [comment]
When I use `inode/directory = ranger.desktop`  (I have to edit ranger.desktop, replace `Exec=ranger`	with `Exec=alacritty -e ranger` in case you want to reproduce it) or `inode/directory = doublecmd.desktop`, and `Open Book Folder` in Calibre, alacritty+ranger or doublecmd is opened directly into the book folder, for example, `~/CalibreLibrary/J.K. Rowling/Harry Potter1-7_ The Complete Collection (5277)/`

When I use `inode/directory = yazi.desktop` and `Open Book Folder` in Calibre, alacrity+yazi is opened into HOME directory and 5 zoxide processes running in the background, see the screenshot for the 5 processes. 

I don't know what path `Open Book Folder` is passed for yazi.

![image](https://github.com/user-attachments/assets/73ed9fac-1260-486d-898f-45286ae42e22)


When I run those zoxide commands in terminal, it says:
```
$ zoxide add '/home/chz/file:/home/chz'
zoxide: not a directory: /home/chz/file:/home/chz
$ zoxide add '/home/chz/file:'
zoxide: not a directory: /home/chz/file:
$ zoxide add '/home/chz/file:/home/chz/CalibreLibrary/J.K.%20Rowling'
zoxide: not a directory: /home/chz/file:/home/chz/CalibreLibrary/J.K.%20Rowling
```

When I use yazi on those paths:
```
$ yazi '/home/chz/file:'
# yazi runs without problem, in HOME, no background process in yazi

$ yazi '/home/chz/file:/home/chz'
# yazi runs with 1 process running in background, in HOME
# `Run "zoxide add '/home/chz/file:/home'" with `/home/chz/file:/home/chz /home/chz/file:/home/chz``

$ yazi '/home/chz/file:/home/chz/CalibreLibrary/J.K.%20Rowling'
# yazi runs with 3 processes running in background, in HOME
# Run "zoxide add '/home/chz/file:/home'"
# Run "zoxide add '/home/chz/file:/home/chz/CalibreLibrary'" with `/home/chz/file:/home/chz/CalibreLibrary/J.K.%20Rowling /home/chz/file:/home/chz/CalibreLibrary/J.K.%20
# Run "zoxide add '/home/chz/file:/home'"
```

If you want to reproduce this
1. edit zoxide plugin code, and add some debug/ingo log into it,
2. download and install calibre program, add an epub or pdf file in its library, and `Open Book Folder`, get the log


I once saw this issue as well when I use the [simple-mtpfs](https://github.com/boydaihungst/simple-mtpfs.yazi) plugin, but you have to own an Android device, so using calibre to reproduce this issue is easier.

**Comment by c02y** [comment]
Problem solved.

It is the problem of `Exec=` part in yazi.desktop file.

The builtin yazi.desktop of yazi package is `Exec=yazi %u`, if I don't change it, `inode/directory = yazi.desktop` won't work for functions like `Open Folder` in Download page of Firefox or `Open Book Folder` in Calibre, the file manager will not be opened at all.

So I copied the builtin yazi.desktop to `~/.local/share/applications/yazi.desktop` and changed `Exec=yazi %u` to `Exec=kitty yazi %u`, the `%u` works OK for Firefox, but not Calibre, after I delete the `%u`, it works fine now. Both the zoxide process issue and `Open Book Folder` of Calibre opening HOME issue are gone.
