### ISSUE TITLE
Keymap document outdated

### ISSUE THREAD

**Issue by fishBone000** [sxyazi/yazi#2061]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Alacritty

### `yazi --debug` output

```Shell
doesn't matter, see below
```

### Describe the bug

Doc on website is outdated, e.g. arg `--confirm` is missing:  
https://yazi-rs.github.io/docs/configuration/keymap/#manager.shell

### Minimal reproducer

doesn't matter

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [ ] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
> Doc on website is outdated, e.g. arg `--confirm` is missing:  

No, `--confirm` is already deprecated in Yazi 0.4, see https://github.com/sxyazi/yazi/issues/1772
