### ISSUE TITLE
preview issues

### ISSUE THREAD

**Issue by peakyet** [sxyazi/yazi#207]
I found that when previewing images and PDFs using Yazi, the preview position was incorrect. As shown in the following figure

![20230922_22h18m36s_grim](https://github.com/sxyazi/yazi/assets/77790246/bc93e8a8-84d1-4054-b6bc-4c1dcff6f262)
![20230922_22h13m56s_grim](https://github.com/sxyazi/yazi/assets/77790246/d0dd99d7-760b-4c4f-a574-9d71bbd4dec3)

I don't know how to deal with this issues. 

I use arch+hyprland+alacritty.

**Comment by peakyet** [comment]
Yes, I use Überzug++ and I try the steps you mentioned in [#134](https://github.com/sxyazi/yazi/issues/134#issuecomment-1714397167), and it works normally
![20230922_23h56m01s_grim](https://github.com/sxyazi/yazi/assets/77790246/2339538b-6fd8-467d-bd9a-6c2cfcafc0a2)

**Comment by sxyazi** [comment]
```diff
diff --git forkSrcPrefix/adaptor/src/ueberzug.rs forkDstPrefix/adaptor/src/ueberzug.rs
index 27d891b6fd1d3175372bbb5820afa1d587c84553..e587693c2207235e18d6d0873ab0e326adbfbbdc 100644
--- forkSrcPrefix/adaptor/src/ueberzug.rs
+++ forkDstPrefix/adaptor/src/ueberzug.rs
@@ -3,6 +3,7 @@ use std::{path::PathBuf, process::Stdio};
 use anyhow::Result;
 use ratatui::prelude::Rect;
 use tokio::{io::AsyncWriteExt, process::{Child, Command}, sync::mpsc::{self, UnboundedSender}};
+use tracing::info;
 
 use crate::Adaptor;
 
@@ -44,6 +45,7 @@ impl Ueberzug {
 
 	async fn send_command(child: &mut Child, cmd: Option<(PathBuf, Rect)>) -> Result<()> {
 		let stdin = child.stdin.as_mut().unwrap();
+		info!("cmd: {:?}", cmd);
 		if let Some((path, rect)) = cmd {
 			let s = format!(
 				r#"{{"action":"add","identifier":"yazi","x":{},"y":{},"max_width":{},"max_height":{},"path":"{}"}}{}"#,
@@ -54,6 +56,7 @@ impl Ueberzug {
 				path.to_string_lossy(),
 				"\n"
 			);
+			info!("cmd_str: {}", s);
 			stdin.write_all(s.as_bytes()).await?;
 		} else {
 			stdin
```

Please apply this patch, then perform the same operation, and paste the results of `cat ~/.local/state/yazi/yazi.log` here

**Comment by peakyet** [comment]
I apply that patch and I get:
```
cat .local/state/yazi/yazi.log
  2023-09-23T02:26:20.127673Z  INFO adaptor::ueberzug: cmd: Some(("/home/chun/tutorials/markdown/zjm1.jpeg", Rect { x: 112, y: 1, width: 65, height: 44 }))
    at adaptor/src/ueberzug.rs:48

  2023-09-23T02:26:20.127689Z  INFO adaptor::ueberzug: cmd_str: {"action":"add","identifier":"yazi","x":112,"y":1,"max_width":65,"max_height":44,"path":"/home/chun/tutorials/markdown/zjm1.jpeg"}

    at adaptor/src/ueberzug.rs:59

  2023-09-23T02:26:21.644346Z  INFO adaptor::ueberzug: cmd: None
    at adaptor/src/ueberzug.rs:48

  2023-09-23T02:26:21.644580Z  INFO adaptor::ueberzug: cmd: Some(("/tmp/yazi/6960cf4f510bc463afa60c4c1002b5d2", Rect { x: 112, y: 1, width: 65, height: 44 }))
    at adaptor/src/ueberzug.rs:48

  2023-09-23T02:26:21.644613Z  INFO adaptor::ueberzug: cmd_str: {"action":"add","identifier":"yazi","x":112,"y":1,"max_width":65,"max_height":44,"path":"/tmp/yazi/6960cf4f510bc463afa60c4c1002b5d2"}

    at adaptor/src/ueberzug.rs:59

  2023-09-23T02:26:23.104154Z  INFO adaptor::ueberzug: cmd: None
    at adaptor/src/ueberzug.rs:48

  2023-09-23T02:26:23.104577Z  INFO adaptor::ueberzug: cmd: Some(("/tmp/yazi/18997042968a29f182edb67ab5b24ef9", Rect { x: 112, y: 1, width: 65, height: 44 }))
    at adaptor/src/ueberzug.rs:48

  2023-09-23T02:26:23.104604Z  INFO adaptor::ueberzug: cmd_str: {"action":"add","identifier":"yazi","x":112,"y":1,"max_width":65,"max_height":44,"path":"/tmp/yazi/18997042968a29f182edb67ab5b24ef9"}

    at adaptor/src/ueberzug.rs:59
```

**Comment by sxyazi** [comment]
Try to use the JSON in the log to execute it in a terminal with the same size:

```json
{"action":"add","identifier":"yazi","x":112,"y":1,"max_width":65,"max_height":44,"path":"/tmp/yazi/18997042968a29f182edb67ab5b24ef9"}
```

**Comment by peakyet** [comment]
well, I think the x position is incorrect.
![20230923_10h37m23s_grim](https://github.com/sxyazi/yazi/assets/77790246/7030f702-d36d-4e02-a4f7-fa83869172ea)

**Comment by sxyazi** [comment]
What's your `tput cols` output?

**Comment by peakyet** [comment]
178

**Comment by sxyazi** [comment]
178 - x(112) = max_width(65) + 1(right margin)

Seems the value of `x` is correct? 🤔

**Comment by peakyet** [comment]
Well, it seems to be caused by Hyprland. Hyprland will automatically scale the monitor. When I set hyperland with a scale of 1, this problem disappears. Thanks a lot.

**Comment by sxyazi** [comment]
Would you like to provide feedback on this issue to Überzug++ and ask them to add support for scaling?

**Comment by sxyazi** [comment]
Oh I've found the relevant issue https://github.com/jstkdng/ueberzugpp/issues/122

Closing this issue then

**Comment by 15cm** [comment]
FYI I figured out a hacky way to fix it in Ranger https://github.com/jstkdng/ueberzugpp/issues/122#issuecomment-1774028257. I have no doubt that the scaling issue resides in ueberzugpp/hyprland/wayland. However, the similar fix doesn't work well in Yazi. Maybe I'm missing something or the position calculation doesn't mange it well for different terminal window sizes and tmux pane sizes.

**Comment by sxyazi** [comment]
> terminal/tmux_pane doesn't occupy the full screen

Are you referring to splitting screens in tmux? Does it work without tmux?

**Comment by 15cm** [comment]
By splitting screen I meant windows are tiled on the screen, not tmux panes. With and without tmux I got the same result.

Actually I realized that when patching Yazi I only down-scaled the coordinates but forgot to downscale the size. I did that later when patching Ranger. Now with [this patch](https://gist.github.com/15cm/ee723a4fc3d54d4a95c08f11928d3f6f) I got the same result as the fix in Ranger.

Before ueberzugpp figured out a fix on their side, a short term fix on the file manger side could be providing scaling and offset options for the users to plug in a value that works for their cases.

**Comment by sxyazi** [comment]
> Before ueberzugpp figures out a fix on their side, a short term fix on the file manger side could be providing scaling and offset options for the users to plug in values that work for their use cases.

Would you like to file an issue for that?

**Comment by 15cm** [comment]
Done. You can assignee it to me. Let me see if I can get some time to work on it. Rust is new to me. I'd go through https://learnxinyminutes.com/docs/rust/ first :)
