### ISSUE TITLE
Image-preview overlaying issue

### ISSUE THREAD

**Issue by Kang-geophysics** [sxyazi/yazi#2073]
### What system are you running Yazi on?

Windows WSL

### What terminal are you running Yazi in?

Pltaform: Terminal Preview

### `yazi --debug` output

```Shell
## Yazi --debug

Yazi
    Version: 0.4.1 (Homebrew 2024-12-10)
    Debug  : false
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.83.0 (90b35a62 2024-11-26)

Ya
    Version: 0.4.1 (Homebrew 2024-12-10)

Emulator
    Brand.from_env      : None
    Emulator.detect     : Emulator { kind: Right(Unknown { kgp: false, sixel: true }), light: false, cell_size: Some((16, 32)) }
    Emulator.detect_full: Ok(Emulator { kind: Right(Unknown { kgp: false, sixel: true }), light: false, cell_size: Some((16, 32)) })

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : Some("wayland-0")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: true

NVIM
    NVIM          : false
    Neovim version: 0.10.2

Variables
    SHELL           : Some("/home/linuxbrew/.linuxbrew/bin/zsh")
    EDITOR          : Some("nvim")
    VISUAL          : None
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : 2
    tmux version       : tmux 3.5a
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : Not a directory (os error 20)

Dependencies
    file          : 5.41
    ueberzugpp    : 2.9.6
    ffmpeg/ffprobe: 7.1 / 7.1
    pdftoppm      : 24.12.0
    magick        : 7.1.1-41
    fzf           : 0.57.0
    fd/fdfind     : 10.2.0 / Not a directory (os error 20)
    rg            : 14.1.1
    chafa         : 1.14.5
    zoxide        : 0.9.6
    7z/7zz        : Not a directory (os error 20) / 24.09
    jq            : 1.7.1

Clipboard
    wl-copy/paste: Not a directory (os error 20) / Not a directory (os error 20)
    xclip        : Not a directory (os error 20)
    xsel         : Not a directory (os error 20)
```

### Describe the bug

When I opend yazi in tmux session, the preview of image is overlapping with previous images and current images. However, when I opend it in normal terminal, it works well. 
<img width="956" alt="image" src="https://github.com/user-attachments/assets/f468a72b-0ba1-4795-856b-ba02ef6c0a58" />

How can I fix it?

Thank you for your efforts.

### Minimal reproducer

-  Checked [weird tmux behavior](https://github.com/sxyazi/yazi/issues/641). Tmux version of mine is latest version (3.5a)
- Changed `.tmux.conf` and restarted.
```
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
```

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
>     Adapter.matches: Sixel

Make sure your `tmux` supports Sixel, i.e. built with the `--enable-sixel` flag, see https://yazi-rs.github.io/docs/image-preview#tmux

**Comment by Kang-geophysics** [comment]
Actually I tried it.
"$ printf "\033[c";cat
^[[?1;2;4c"
Following your reference, 4 means SIXEL is supported by this build.
However, I don't know how to enable-sixel.
Could you let me know how to enable sixel flag?

**Comment by sxyazi** [comment]
4 means your tmux supports Sixel. You don't need to enable it yourself, Yazi will use it when it's available.

This might not be an issue with tmux itself, but rather due to ConPTY, which interferes with communication between Yazi and the actual terminal. The currently only way we recommended under WSL is to use `wezterm ssh`, see https://yazi-rs.github.io/docs/image-preview#wsl.

**Comment by Kang-geophysics** [comment]
Thank you for your recomendation. 

I tried "wezterm".

1. wezterm > wsl > ssh > Adapter: `Chafa` > Preview X (Black screen)
2. wezterm > wsl > ssh > Adapter: `Chafa` > Preview X (Black screen)
3. wezterm > wsl > tmux > Adapter: `KgpOld` > Preview X (Black screen)
4. wezterm > wsl > tmux > ssh > Adapter: `Sixel` > Preview X (SIXEL IMAGE (35x21)++++++++++)

In case of  method 4, I faced following problem.
![image](https://github.com/user-attachments/assets/878e6f1f-9d84-4a0b-8967-d9ba0871776b)

I found people who experience this issue like me. [link](https://www.reddit.com/r/commandline/comments/1dp31rk/remote_yazi_image_preview_issue/)

Thank you for your support and efforts to increase the productivity of CLI ecosystem.

I think there are many things I don't know and difficult problems I can't solve and the connection between ecosystem as you mentioned ConPTY is big problem.

I think you also have problem to solve this issue, which I only claimed with some letters, because each people has individual environment.

If you have insight about this, please let me know. Thank you for you huge supports!!

Thanks.

**Comment by sxyazi** [comment]
You can try the third method, which is to connect to WSL using the `wezterm ssh` command, and make sure to:

- Build tmux from the latest source code and specify `--enable-sixel` during the build to resolve https://github.com/tmux/tmux/issues/4208 via https://github.com/tmux/tmux/issues/4099.
- Use `WT_Session=1 yazi` to start Yazi

**Comment by Kang-geophysics** [comment]
Thank you for your help. I solved this problem. 
I removed tmux  installed with "homebrew".
And I reinstalled "[tmux-git ](https://github.com/tmux/tmux)" you recommended. 
To use this way, I have to install `autoconf`, `automake`, `pkg-config` and `byacc`.
After install this additional library, I installed tmux as follows

```
# Donwload tmux install package with git
git clone https://github.com/tmux/tmux.git
# 
cd tmux
# Install with option `--enable-sixel`
./configure --enable-sixel && make
```
In this way, I can use "image-preview mode" under `Windows-preview Terminal`.
There is no problem.

Thank you for your help.
