### ISSUE TITLE
opening compressed files doesn't work

### ISSUE THREAD

**Issue by ManuLinares** [sxyazi/yazi#2075]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

alacritty

### `yazi --debug` output

```Shell
Yazi
    Version: 0.4.3 (5bd71bf 2024-12-20)
    Debug  : false
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.83.0 (90b35a62 2024-11-26)

Ya
    Version: 0.4.3 (5bd71bf 2024-12-20)

Emulator
    Brand.from_env      : None
    Emulator.detect     : Emulator { kind: Right(Unknown { kgp: false, sixel: false }), light: false, cell_size: Some((8, 19)) }
    Emulator.detect_full: Ok(Emulator { kind: Right(Unknown { kgp: false, sixel: false }), light: false, cell_size: Some((8, 19)) })

Adapter
    Adapter.matches: X11

Desktop
    XDG_SESSION_TYPE           : Some("x11")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0.0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

NVIM
    NVIM          : false
    Neovim version: 0.10.2

Variables
    SHELL           : Some("/bin/bash")
    EDITOR          : Some("/usr/bin/micro")
    VISUAL          : None
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : 2
    tmux version       : tmux 3.5a
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file          : 5.46
    ueberzugpp    : 2.9.6
    ffmpeg/ffprobe: 7.1 / 7.1
    pdftoppm      : 24.11.0
    magick        : 7.1.1-41
    fzf           : 0.56.3
    fd/fdfind     : 10.2.0 / No such file or directory (os error 2)
    rg            : 14.1.1
    chafa         : 1.14.5
    zoxide        : No such file or directory (os error 2)
    7z/7zz        : 17.05 / No such file or directory (os error 2)
    jq            : 1.7.1

Clipboard
    wl-copy/paste: No such file or directory (os error 2) / No such file or directory (os error 2)
    xclip        : 0.13
    xsel         : No such file or directory (os error 2)
```

### Describe the bug

pressing the "right arrow" on a zip file does nothing.
pressing "enter" on a zip file opens the file in engrampa, my default system wide.

### Minimal reproducer

I'm on Archlinux using XFCE

alacritty 0.14.0-1
yazi 0.4.1-1
engrampa 1.28.2-2
p7zip 1:17.05-2

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
What's your zip's mimetype? - press <Tab> on it to spot it

What's your zip file's opener? Can you upload your zip file for me to test please?

**Comment by ManuLinares** [comment]
![image](https://github.com/user-attachments/assets/9a2e93e5-80c3-4b1b-9d88-62345f9e0345)

mimetype is: application/octet-stream

you can download it from: https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by sxyazi** [comment]
>     file          : 5.46

This is a bug in the latest `file(1)` 5.46 (See https://github.com/sxyazi/yazi/pull/1991) - it incorrectly identifies some `zip` files as `application/octet-stream` instead of `application/zip`. 

You can temporarily downgrade `file(1)` to an earlier version, and hopefully, they'll fix it soon.

Closing as not Yazi, nothing can be done here

**Comment by ManuLinares** [comment]
https://bugs.astron.com/view.php?id=571 this bug is marked as "fixed" but is not.

Even if it is an external bug, this bug should be open until upstream fixes it.
