### ISSUE TITLE
Expose the `confirm` component to plugin developers

### ISSUE THREAD

**Issue by hankertrix** [sxyazi/yazi#2082]
### `yazi --debug` output

```Shell
N/A
```

### Please describe the problem you're trying to solve

The `confirm` component has been implemented since Yazi v0.3.1, so I think it's a good time to expose it to plugin developers.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Just a Lua API to show the `confirm` component.

### Additional context

It seems like the API is marked with a `TODO` for a redesign. Maybe now that the component has somewhat stabilised, it may be easier to design the API for it.

### Checklist

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/2095

**Comment by hankertrix** [comment]
Awesome, thank you!

I'll add it to the documentation once I figure out how to use it.

**Comment by hankertrix** [comment]
Hmmm the confirm component doesn't appear when I use the API like this:

```lua
local confirmation = ya.confirm({
    pos = { "center", y = 2, w = 50 },
    title = "test",
    content = "test content",
})
```

The confirm component is still there, but there's no UI for some reason.
