### ISSUE TITLE
Video preview does not automatically play

### ISSUE THREAD

**Issue by mairs8** [sxyazi/yazi#2084]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.37.0

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Nixpkgs 2024-09-04)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Nixpkgs 2024-09-04)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: Some("12f9a0d0b93f691d4d9923716557154d74777b0a_1734858577_1295630307")
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/run/current-system/sw/bin/zsh")
    EDITOR             : Some("vim")
    VISUAL             : Some("vim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : Some("/nix/store/wkx0ji2kp3n0q6g32avhvwrprj897cfm-YAZI_CONFIG_HOME")

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.5a
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-40
    fzf              : 0.56.3
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.5
    zoxide           : 0.9.6
    7z               : No such file or directory (os error 2)
    7zz              : 24.08
    jq               : 1.7.1
```

### Describe the bug

In all the examples online, when the cursor moves over a .mp4 file the preview pane flicks through different thumbnails of the video file. On my system, it just shows one static thumbnail and does not move through.

Is there a configuration setting that i need to manually switch on or something else i am missing?

### Minimal reproducer

install yazi from the nixos repo. 
install the other dependencies as per the `yazi --debug` output above.
run yazi and go to a .mp4 file
video preview does not show a slideshow

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
Press `K` or `J` to scroll over the preview, see https://yazi-rs.github.io/docs/quick-start#navigation

Next time, please search through the documentation/issues before creating a new post - you can do better 👍

Closing as not even a bug
