### ISSUE TITLE
Run "yazi" does not display files and anything

### ISSUE THREAD

**Issue by mestrellaseidor** [sxyazi/yazi#2085]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

WezTerm 20240203-110809-5046fc22

### `yazi --debug` output

```Shell
Yazi
    Version: 0.4.2 (Homebrew 2024-12-20)
    Debug  : false
    Triple : aarch64-apple-darwin (macos-aarch64)
    Rustc  : 1.83.0 (90b35a62 2024-11-26)

Ya
    Version: 0.4.2 (Homebrew 2024-12-20)

Emulator
    Brand.from_env      : Some(WezTerm)
    Emulator.detect     : Emulator { kind: Left(WezTerm), light: false, cell_size: Some((17, 47)) }
    Emulator.detect_full: Ok(Emulator { kind: Left(WezTerm), light: false, cell_size: Some((17, 47)) })

Adapter
    Adapter.matches: Iip

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

NVIM
    NVIM          : false
    Neovim version: 0.10.3

Variables
    SHELL           : Some("/bin/zsh")
    EDITOR          : None
    VISUAL          : None
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: Some("--height 80% --layout=default --border --color=hl:#2dd4bf")

Text Opener
    default     : Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "neovim", for_: None, spread: true })
    block-create: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "neovim", for_: None, spread: true })
    block-rename: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "neovim", for_: None, spread: true })

Multiplexers
    TMUX               : 0
    tmux version       : tmux 3.5a
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file          : 5.41
    ueberzugpp    : No such file or directory (os error 2)
    ffmpeg/ffprobe: 7.1 / 7.1
    pdftoppm      : No such file or directory (os error 2)
    magick        : No such file or directory (os error 2)
    fzf           : 0.57.0
    fd/fdfind     : 10.2.0 / No such file or directory (os error 2)
    rg            : 14.1.1
    chafa         : 1.14.5
    zoxide        : 0.9.6
    7z/7zz        : No such file or directory (os error 2) / No such file or directory (os error 2)
    jq            : 1.6

Clipboard
    wl-copy/paste: No such file or directory (os error 2) / No such file or directory (os error 2)
    xclip        : No such file or directory (os error 2)
    xsel         : No such file or directory (os error 2)
```

### Describe the bug

I has yazi already installed and working well.. i run again "brew install yazi ffmpeg sevenzip jq poppler fd ripgrep fzf zoxide imagemagick font-symbols-only-nerd-font" and when run "yazi" command does not display any file or folder

### Minimal reproducer

run "brew install yazi ffmpeg sevenzip jq poppler fd ripgrep fzf zoxide imagemagick font-symbols-only-nerd-font" then run "yazi"

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [ ] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
> - [ ] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

Can you try this?

**Comment by sxyazi** [comment]
Also please upload your logs, https://yazi-rs.github.io/docs/plugins/overview#logging

**Comment by mestrellaseidor** [comment]
Thanks! The issue was that init.lua included plugins, but they weren’t installed on my Mac.

<img width="980" alt="SCR-20241222-qynn" src="https://github.com/user-attachments/assets/72758a3a-05fa-4feb-928d-00627a6cb038" />

**Comment by sxyazi** [comment]
`full-border` has already added v0.4 support two month ago in https://github.com/yazi-rs/plugins/commit/e01bc1690a5ba38f72fa25f6382abe7db9aa4708

Run `ya pack -u` to upgrade all your plugins
