### ISSUE TITLE
`fs.cwd()` API doesn't update as fast as `cx.active.current.cwd`

### ISSUE THREAD

**Issue by hankertrix** [sxyazi/yazi#2088]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

Ghostty 0.1.0-main+28c40f9b

### `yazi --debug` output

```Shell
Yazi
    Version: 0.4.3 (Arch Linux 2024-12-22)
    Debug  : false
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.83.0 (90b35a62 2024-11-26)

Ya
    Version: 0.4.3 (Arch Linux 2024-12-22)

Emulator
    Brand.from_env      : Some(Ghostty)
    Emulator.detect     : Emulator { kind: Left(Ghostty), light: true, cell_size: Some((15, 30)) }
    Emulator.detect_full: Ok(Emulator { kind: Left(Ghostty), light: true, cell_size: Some((15, 30)) })

Adapter
    Adapter.matches: Kgp

Desktop
    XDG_SESSION_TYPE           : Some("x11")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

NVIM
    NVIM          : false
    Neovim version: 0.10.3

Variables
    SHELL           : Some("/bin/bash")
    EDITOR          : Some("nvim")
    VISUAL          : Some("nvim")
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : 0
    tmux version       : No such file or directory (os error 2)
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file          : 5.46
    ueberzugpp    : No such file or directory (os error 2)
    ffmpeg/ffprobe: 7.1 / 7.1
    pdftoppm      : 24.11.0
    magick        : 7.1.1-41
    fzf           : 0.56.3
    fd/fdfind     : 10.2.0 / No such file or directory (os error 2)
    rg            : 14.1.1
    chafa         : No such file or directory (os error 2)
    zoxide        : No such file or directory (os error 2)
    7z/7zz        : 24.09 / No such file or directory (os error 2)
    jq            : 1.7.1

Clipboard
    wl-copy/paste: No such file or directory (os error 2) / No such file or directory (os error 2)
    xclip        : 0.13
    xsel         : No such file or directory (os error 2)
```

### Describe the bug

`fs.cwd()` updates much slower than `cx.active.current.cwd`, which can break some plugins or cause them to behave unexpectedly when plugin developers use the `fs.cwd()` API instead of `cx.active.current.cwd`.

Waiting for Yazi to load also doesn't fix the issue, unless `fs.cwd()` is called after using a function to get `cx.active.current.cwd`.

### Minimal reproducer

The easiest way to see this difference is to emit the `enter` command and then obtain the current working directory through `fs.cwd()` and `cx.active.current.cwd`.

An example plugin:

```lua
local get_current_directory = ya.sync(
    function(_) return tostring(cx.active.current.cwd) end
)

local function notify(message)
    return ya.notify({
        title = "Example plugin",
        timeout = 5,
        content = message,
        level = "info",
    })
end

local function entry()
    ya.manager_emit("enter", {})
    notify("fs.cwd(): " .. tostring(fs.cwd()))
    notify("cx.active.current.cwd: " .. get_current_directory())
end

return {
    entry = entry,
}
```

### Anything else?

I'm not sure if this should be a discussion or an issue, as I have no idea if this behaviour is intended or not, but it's definitely something plugin developers should note when developing their plugins. Feel free to convert this to a discussion if it belongs there.

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
This is the expected behavior. The whole point of adding it is that it differs from `cx.active.current.cwd`; otherwise, we wouldn't need a new API.

After the user changes the directory, `cx.active.current.cwd` is updated immediately, while updates to the CWD ([`chdir`](https://man7.org/linux/man-pages/man2/chdir.2.html)) are much slower because they involve IO operations (e.g., checking if the directory is valid). This is particularly noticeable on slow devices. In my tests, when an HDD is waking up from sleep, it typically takes 3-4 seconds.

So, there is a delay between `fs.cwd()` and `cx.active.current.cwd`. Generally, you never need `fs.cwd()`, and you always rely on the user's actions instead. It was added simply to fill in the gap where Lua lacks a [`getcwd`](https://man7.org/linux/man-pages/man3/getcwd.3.html) API, and to handle certain edge cases - it's useful if you just need a valid CWD as the process's CWD to start for some work that doesn't depend on the CWD.

**Comment by hankertrix** [comment]
Ahhh I see. That makes sense.

I opened the issue mostly to just clarify the purpose of the `fs.cwd()`. Time to add it to the documentation.

Thanks!
