### ISSUE TITLE
ya package manager does not work 

### ISSUE THREAD

**Issue by drewhodge** [sxyazi/yazi#2111]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Kitty 0.32.2

### `yazi --debug` output

```Shell
Yazi
    Version: 0.4.2 (VERGEN_IDEMPOTENT_OUTPUT 2024-12-28)
    Debug  : false
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.83.0 (90b35a62 2024-11-26)

Ya
    Version: 0.4.2 (VERGEN_IDEMPOTENT_OUTPUT 2024-12-28)

Emulator
    Brand.from_env      : Some(Kitty)
    Emulator.detect     : Emulator { kind: Left(Kitty), light: false, cell_size: Some((12, 27)) }
    Emulator.detect_full: Ok(Emulator { kind: Left(Kitty), light: false, cell_size: Some((12, 27)) })

Adapter
    Adapter.matches: Kgp

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-0")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

NVIM
    NVIM          : false
    Neovim version: No such file or directory (os error 2)

Variables
    SHELL           : Some("/usr/bin/zsh")
    EDITOR          : Some("hx")
    VISUAL          : None
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: Some("--height 80% --border rounded --layout reverse --color \'bg+:-1,fg:gray,fg+:white,border:black,spinner:0,hl:yellow,header:blue,info:green,pointer:red,marker:blue,prompt:red,hl+:red\' --prompt \'∷ \' --pointer ▶ --marker ⇒")

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : 0
    tmux version       : No such file or directory (os error 2)
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file          : 5.45
    ueberzugpp    : No such file or directory (os error 2)
    ffmpeg/ffprobe: No such file or directory (os error 2) / No such file or directory (os error 2)
    pdftoppm      : 24.02.0
    magick        : No such file or directory (os error 2)
    fzf           : 0.56.0
    fd/fdfind     : No such file or directory (os error 2) / No such file or directory (os error 2)
    rg            : 14.1.0
    chafa         : 1.14.0
    zoxide        : No such file or directory (os error 2)
    7z/7zz        : No such file or directory (os error 2) / No such file or directory (os error 2)
    jq            : 1.7

Clipboard
    wl-copy/paste: No such file or directory (os error 2) / No such file or directory (os error 2)
    xclip        : No such file or directory (os error 2)
    xsel         : No such file or directory (os error 2)
```

### Describe the bug

Tried to install a theme/flavour using the following command: 

  ya pack -a bennyyip/gruvbox-dark 

The 'ya' command was not found.

### Minimal reproducer

1. Installed yazi using the following command:

    cargo install --locked yazi-fm yazi-cli

2. Ran yazi and tested successfully.
3.  Ran the following command to install the gruvbox-dark theme:

     ya pack -a bennyyip/gruvbox-dark 

The 'ya' command was not found.

### Anything else?

Installed the theme/flavor manually and yazi picked it up and is working correctly.

Tried installing a plugin (ya pack -a yazi-rs/plugins:full-border ) -- same result.

Running Ubuntu 24.04 on an old intel iMac. 

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by hankertrix** [comment]
Is the `ya` binary present in your `~/.cargo/bin/`?

If it's not, try reinstalling both packages, as that would mean the installation failed for the `ya` binary.

**Comment by sxyazi** [comment]
Could you please try other build methods here: [Build from Source](https://yazi-rs.github.io/docs/installation#build-from-source), or you can download our pre-built binaries here: [Official Binaries](https://yazi-rs.github.io/docs/installation#official-binaries).

**Comment by drewhodge** [comment]
Thanks for your quick response. The ya binary wasn't in ~/.cargo/bin. I rebuilt from source and now I'm able to run ya -- successfully installed a plugin.
Thanks again for the excellent app and for your support!

**Comment by drewhodge** [comment]
Followed the advice above -- the ya package manager is now working on my Linux system. Closing this issue.

**Comment by drewhodge** [comment]
Followed the advice above -- the ya package manager is now working on my Linux system. Closing this issue.
