### ISSUE TITLE
Preview pane overflow bug

### ISSUE THREAD

**Issue by JustForFun88** [sxyazi/yazi#2115]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

wezterm 20240203-110809-5046fc22

### `yazi --debug` output

```Shell
Yazi
    Version: 0.4.2 (5cfcab3 2024-12-20)
    Debug  : false
    Triple : x86_64-pc-windows-msvc (windows-x86_64)
    Rustc  : 1.83.0 (90b35a62 2024-11-26)

Ya
    Version: 0.4.2 (5cfcab3 2024-12-20)

Emulator
    Brand.from_env      : Some(WezTerm)
    Emulator.detect     : Emulator { kind: Left(WezTerm), light: false, cell_size: None }
    Emulator.detect_full: Ok(Emulator { kind: Right(Unknown { kgp: false, sixel: false }), light: false, cell_size: None })

Adapter
    Adapter.matches: Iip

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

NVIM
    NVIM          : false
    Neovim version: program not found

Variables
    SHELL           : None
    EDITOR          : None
    VISUAL          : None
    YAZI_FILE_ONE   : Some("C:\\Program Files\\Git\\usr\\bin\\file.exe")
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(Opener { run: "hx %*", block: true, orphan: false, desc: "helix", for_: None, spread: true })
    block-create: Some(Opener { run: "hx %*", block: true, orphan: false, desc: "helix", for_: None, spread: true })
    block-rename: Some(Opener { run: "hx %*", block: true, orphan: false, desc: "helix", for_: None, spread: true })

Multiplexers
    TMUX               : 0
    tmux version       : program not found
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file          : 5.45
    ueberzugpp    : program not found
    ffmpeg/ffprobe: 7.1 / 7.1
    pdftoppm      : 24.08.0
    magick        : 7.1.1-43
    fzf           : 0.57.0
    fd/fdfind     : 10.2.0 / program not found
    rg            : 14.1.1
    chafa         : program not found
    zoxide        : 0.9.6
    7z/7zz        : 23.01 / program not found
    jq            : 1.7.1

Clipboard
    wl-copy/paste: program not found / program not found
    xclip        : program not found
    xsel         : program not found
```

### Describe the bug

If you split the terminal horizontally and use yazi in one of the panes, and if the preview size for images or PDFs is large vertically, the preview display overflows beyond the preview pane and into the bottom status bar. This results in residual images of the previous file (image or PDF) remaining visible when switching between files.

There are two possible solutions:

- Reduce the preview size for images or PDFs so they fit within the preview pane. However, this would require retrieving the actual size of the terminal pane.
- Refresh (re-render) the entire bottom status bar when switching between files to prevent residual images from remaining visible.

https://github.com/user-attachments/assets/901ea316-fbb6-4da7-932b-5dc4640f9a15

### Minimal reproducer

Split the terminal horizontally, run yazi in one pane, and open large images or PDFs. If the preview size exceeds the pane's vertical space, it overflows into the bottom status bar, leaving residual artifacts when switching files.

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [ ] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
All terminals do not support retrieving the actual pixel width and height of the terminal on Windows. Hence you need to manually limit the image to not exceed the preview area by using `max_width` and `max_height`, see https://yazi-rs.github.io/docs/image-preview#size.

Closing as expected
