### ISSUE TITLE
No .log file if running in debug and build from source 

### ISSUE THREAD

**Issue by HenningCode** [sxyazi/yazi#2125]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

alacritty 0.14.0

### `yazi --debug` output

```Shell
Yazi
    Version: 0.4.3 (2770e025 1980-01-01)
    Debug  : true
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.83.0 (90b35a62 2024-11-26)

Ya
    Version: 0.3.3 (Nixpkgs 2024-09-04)

Emulator
    Brand.from_env      : Some(Alacritty)
    Emulator.detect     : Emulator { kind: Left(Alacritty), light: false, cell_size: None }
    Emulator.detect_full: Ok(Emulator { kind: Right(Unknown { kgp: false, sixel: false }), light: false, cell_size: None })

Adapter
    Adapter.matches: Chafa

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-0")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

NVIM
    NVIM          : false
    Neovim version: 0.10.2

Variables
    SHELL           : Some("/nix/store/f33kh08pa7pmy4kvsmsibda46sh46s66-bash-interactive-5.2p37/bin/bash")
    EDITOR          : Some("nvim")
    VISUAL          : None
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : 0
    tmux version       : tmux 3.5a
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file          : 5.45
    ueberzugpp    : 2.9.6
    ffmpeg/ffprobe: No such file or directory (os error 2) / No such file or directory (os error 2)
    pdftoppm      : No such file or directory (os error 2)
    magick        : No such file or directory (os error 2)
    fzf           : 0.56.2
    fd/fdfind     : No such file or directory (os error 2) / No such file or directory (os error 2)
    rg            : No such file or directory (os error 2)
    chafa         : No such file or directory (os error 2)
    zoxide        : No such file or directory (os error 2)
    7z/7zz        : No such file or directory (os error 2) / No such file or directory (os error 2)
    jq            : No such file or directory (os error 2)

Clipboard
    wl-copy/paste: No such file or directory (os error 2) / No such file or directory (os error 2)
    xclip        : No such file or directory (os error 2)
    xsel         : No such file or directory (os error 2)
```

### Describe the bug

I am using alacritty and wanted to debug why images are not shown. After following the instructions on how to debug Überzug++. I cloned the repo and build it from source with `cargo build --locked` and ran it with `./target/release/yazi`. Sadly the log file is not created in this mode. Maybe this is not a bug more a feature request. 

### Minimal reproducer

git clone https://github.com/sxyazi/yazi.git
cd yazi
cargo build --locked
./target/release/yazi

### Checklist

- [X] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#official-binaries), and the issue is still reproducible
- [X] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [X] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

**Comment by sxyazi** [comment]
Have you set the `YAZI_LOG` environment variable? https://yazi-rs.github.io/docs/plugins/overview#logging

**Comment by HenningCode** [comment]
Yep, thats my bad. Sorry! 

But I am still not getting any logs for Ueberzug++. Only for PDF. 
`ERROR yazi_scheduler::prework::prework: Returned 0 when running preloader `pdf` with`

**Comment by sxyazi** [comment]
>     Adapter.matches: Chafa

This is because Yazi is using Chafa instead of Ueberzug++, since Ueberzug++ only supports Sway, Hyprland, and Wayfire, and you're not on any of those:


>     SWAYSOCK                   : None
>    HYPRLAND_INSTANCE_SIGNATURE: None
>    WAYFIRE_SOCKET             : None

See https://yazi-rs.github.io/docs/image-preview#protocol

**Comment by HenningCode** [comment]
@sxyazi And thanks for the quick and awesome replies! Awesome project!
