### ISSUE TITLE
Is it possible to run fzf in a floating window?

### ISSUE THREAD

**Issue by wfxr** [sxyazi/yazi#2128]
### `yazi --debug` output

```Shell
Not relevant.
```

### Please describe the problem you're trying to solve

Is it possible to run fzf in a floating window, like `fzf` plugin in vim?

![image](https://github.com/user-attachments/assets/58c545fc-bff4-4e69-80bd-96bf3752037f)

The floating window is more convenient for typing queries for fzf by referring to the information on the main window.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Just like `spot` does?

### Checklist

- [X] I have searched the existing issues/discussions
- [X] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#official-binaries) doesn't already have this feature

**Comment by sxyazi** [comment]
Neovim achieves this through its built-in terminal `:terminal` (the "TERMINAL" in the lower left of the screenshot indicates that it's a terminal)

However, Yazi doesn't have a built-in terminal, so this can't be achieved directly within Yazi. 

But if you're using `tmux`, `zellij`, or `wezterm`, you can use their floating terminals to do this. Here's an example: https://yazi-rs.github.io/docs/tips#helix-with-zellij

**Comment by wfxr** [comment]
> But if you're using tmux, zellij, or wezterm, you can use their floating terminals to do this. Here's an example: https://yazi-rs.github.io/docs/tips#helix-with-zellij

@sxyazi Sounds like a nice workaround, will try it. Thanks!
