### ISSUE TITLE
Add visible key to show wether currently hovered file is selected with relative width of left column set to 0

### ISSUE THREAD

**Issue by Brixy** [sxyazi/yazi#217]
If the left column width is set to `0`, e.g.

```
# yazi.toml
[manager]
layout = [ 0, 4, ,3]
```

you can not tell whether the currently hovered file is selected or not.

In each screenshot both files are selected.

Thank you!

![with-left-column](https://github.com/sxyazi/yazi/assets/1643010/1a5f30c7-0519-48e6-949e-f3a1aedff364)
![without-left-column](https://github.com/sxyazi/yazi/assets/1643010/826fe4f0-bc12-40f7-b3cc-e8243a87cb1c)

**Comment by sxyazi** [comment]
nice to have, just not get around to adding it...

**Comment by Brixy** [comment]
Confirming that this issue was solved by [#161](https://github.com/sxyazi/yazi/pull/161). Excellent work!

I am closing this issue; feel free to re-open it if necessary.
