### ISSUE TITLE
Weird text truncation on small screens

### ISSUE THREAD

**Issue by TieWay59** [sxyazi/yazi#219]
Hi @sxyazi, I love your project. you are making a great product.

### Problem

It's a little sad when I see this hint text on my small screen when I press `C`. 

![image](https://github.com/sxyazi/yazi/assets/40034603/3b8170eb-60f7-465e-8d84-7b048222dc81)

I understand this might be a trivial UX request, but I hope it can be taken into consideration.

### Possible solution (?)

Maybe arranging the paragraph box in some vertical container is helpful. Like helix-rs did:

![image](https://github.com/sxyazi/yazi/assets/40034603/5add1172-fdd4-45d3-9a8d-690c32aeecc7)

Or just wrap it, dunno which would be better.

**Comment by TieWay59** [comment]
https://github.com/sxyazi/yazi/blob/782f88b965970224917c0f76148f484b0af0d773/app/src/which/side.rs#L36

I saw this might caused by this line, it's related to [`ratatui: Span`](https://ratatui.rs/how-to/render/display-text.html?search=wrap)

But I can't find the wrapping behavior in their docs, so this may need some tricks.

**Comment by sxyazi** [comment]
I haven't used the text wrapping yet, I will find time to give it a try, thanks for the suggestions.
