### ISSUE TITLE
Image preview size/dimension is too small, changing the `max_width` doesn't take effect

### ISSUE THREAD

**Issue by 5183nischal** [sxyazi/yazi#223]
Hi, I just found yazi and love it!

I rely of preview to sort through all the pdf I happen to download (using lf for it now). But the preview from yazi is rather small even when there is enough space in the their column. I changed the max_width in config but didn't help and couldn't find something similar in the existing issues, so asking here to check if I'm missing something simple.

Example of how it looks:
![screenshot 4](https://github.com/sxyazi/yazi/assets/22991189/7b320372-dd3d-4a0a-8946-1d9114b1fd4d)

Thank you!

**Comment by sxyazi** [comment]
Hi, Yazi caches images to speed up image previews. After modifying the `max_width`, you need to clear the old cache, which can be done by doing `yazi --clear-cache`.

**Comment by 5183nischal** [comment]
> Hi, Yazi caches images to speed up image previews. After modifying the `max_width`, you need to clear the old cache, which can be done by doing `yazi --clear-cache`.

Thanks! that worked!
