### ISSUE TITLE
Why does yazi use BTreeMap for history?

### ISSUE THREAD

**Issue by ndtoan96** [sxyazi/yazi#224]
I realize that `forward` and `backward` are not implemented yet so I want to help but then I check `Tab::history` and it is a `BTreeMap`. Isn't it impossible to tell the order of insertion with a `BTreeMap`?

**Comment by sxyazi** [comment]
`Tab::history` is a record of previously opened directories, designed to quickly load without the need to read the fs again.

I think it's not suitable for `forward` / `backward` that requires a `Vec` structure. Consider:

```
folder_a -> folder_b -> folder_a
```

In this case, you would need to store the complete path, which can result in duplicates (folder_a) within the "history". I think we should create a new structure to store it, possibly called "crumbs" (or something else?).

**Comment by ndtoan96** [comment]
Well, in Android, they call it the back stack. But it only has backward and no forward so I'm not sure the name is suitable.
