### ISSUE TITLE
Hover touched or moved file

### ISSUE THREAD

**Issue by Brixy** [sxyazi/yazi#235]
Sorry, another idea ;-)

When you touch, move or rename a file or folder the file or folder should be hovered and in the visible area.

Currently there is no visible feedback at all if you e.g. touch a file which is created outside the displayed area.

I’m not sure what is the best to handle multiple files—maybe hover the first according to the current sorting?!

Thank you very much.

**Comment by Brixy** [comment]
Played a bit more because yazi is so fantastic.

It seems that when you find files using `fzf` (bound to `Z`) the selected file is not hovered when it lives in a sub directory.

Example from yazi’s repository:

- `Z`
- `sixel`
- `Enter`

Yazi enters the corresponding folder but does not hover `sixel.rs`.

Yet, it works correctly as soon as do a search in the same folder again:

- `hh` (go back to yazi’s root)
- `Z`
- `sixel`
- `Enter`

`sixel.rs` is hovered now.

When you go back to root and search for other files in yet other directories they are not hovered.

This might be a caching thing.

**Comment by sxyazi** [comment]
Thanks for your appreciation. The hover will be rewritten and completed before the release of Yazi v0.1.5.

**Comment by sxyazi** [comment]
Done by https://github.com/sxyazi/yazi/pull/269, let me know if it solved those issues for you!

**Comment by Brixy** [comment]
Wow! Excellent. Thank you very much for adressing this.

Everything works perfectly; I just noticed one flaw (but I don’t know whether this is adressed in the pull request):

When you move a file the file is not hovered afterwards.

This could be a solution: When two or more files are moved, the current behavior is optimal. When a single file is moved, it maybe should hovered afterwards.

Does this make sense to you?

Thanks again for all your work on yazi.

**Comment by sxyazi** [comment]
I'm not quite sure how to handle moving (copying and then deleting if it's a cross-mount operation) files.

If the files being moved are large, like 1GB, it might take some time to complete. During this time, the user may have already moved their cursor to a different location.

Is resetting the cursor after the file move/copy is complete the expected behavior? Wouldn't that disrupt the user's expectations?

**Comment by sxyazi** [comment]
Just tested Ranger and Finder (macOS's file manager), and they also don't implement re-hovering after moving.

I'm curious if there are other file managers that have implemented this feature. Maybe we can use them as a reference.

**Comment by Brixy** [comment]
> If the files being moved are large, like 1GB, it might take some time to complete. During this time, the user may have already moved their cursor to a different location.

Yes, this is a valid point.

I have been using nnn for years, hence this suggestion. nnn just blocks everything until file movements are completed.

So I think your implementation is perfect and more advanced!

**Comment by sxyazi** [comment]
Alright, let's merge that PR!
