### ISSUE TITLE
Find is not working

### ISSUE THREAD

**Issue by SergioQuijanoRey** [sxyazi/yazi#236]
When pressing "/", "?" or "-" nothing happens. When opening the help menu with "~", now "/" works for searching options.

This happens to me inside wezterm and alacritty. Both inside `zellij` session and outside (no program no manage sessions / panes / ...) I am using NixOS with Hyprland,

**Comment by tinted-knight** [comment]
Have the same issue with macOs 13.3.1. Both Terminal or iTerm2. I am using zsh by default, but changing to bash didn't solve(

**Comment by sxyazi** [comment]
"find" is a new feature, and it is being shipped with Yazi v0.1.5, you can build Yazi from code to experience it ahead

**Comment by SergioQuijanoRey** [comment]
Oh that explains the behavior! Thank you very much for the kind response :smile:
