### ISSUE TITLE
[Feature Request] Option to quit without writing cwd-file

### ISSUE THREAD

**Issue by XOR-op** [sxyazi/yazi#243]
## Background
Currently, users cannot choose whether quitting yazi with changing the current working directory. According to the [documentation](https://yazi-rs.github.io/docs/usage/quick-start/#changing-working-directory-when-exiting-yazi), users need to decide it before the launch of yazi, which is inconvenient in real life.

## Potential Solution
Add a dedicated keybinding for this type of quitting. After this action, yazi will write the $PWD before it's launched. Users can input "q" to write the current directory in yazi to the cwd-file normally.

**Comment by sxyazi** [comment]
> After this action, yazi will write the $PWD before it's launched

Not quite sure what it means

**Comment by XOR-op** [comment]
Suppose we have a new quit key "q2". We start with `yazi --cwd-file="123"` at `/etc`, and change the working directory to `/tmp` inside yazi. By default, when we press "q", yazi will write "/tmp" to file "123". What my current solution is, when pressing "q2", yazi will write "/etc" to "123" instead of "tmp".

**Comment by sxyazi** [comment]
Seems adding a new `--no-cwd-file` option to the `quit` command might solve this issue.
