### ISSUE TITLE
Sort is not triggered by default

### ISSUE THREAD

**Issue by ndtoan96** [sxyazi/yazi#244]
In a freshly opened yazi, files and folders are not sorted until `, a` is triggered.

**Comment by sxyazi** [comment]
Yazi defaults to sorting by modification time, rather than alphabetical order, and the default binding for `, a` is the latter.

https://github.com/sxyazi/yazi/blob/d721b01c37e6e680017db514cea60a176559f2a2/config/preset/yazi.toml#L3

**Comment by ndtoan96** [comment]
Oh, that's new to me. Thanks.
