### ISSUE TITLE
MacOS: got Permission Denied error when tried to open a file

### ISSUE THREAD

**Issue by osenvosem** [sxyazi/yazi#252]
MacOS 13.6, yazi 0.1.4, installed with Homebrew

<img width="629" alt="Screenshot 2023-10-09 at 17 12 52" src="https://github.com/sxyazi/yazi/assets/6762673/c876f8da-fbcb-4bb3-9167-2db7fed0c058">

**Comment by Hugobsb** [comment]
> Hey, could you paste your `yazi.toml` file here?

Hello :) if you guys allow me to add here, the same is happening to me. MacOS too.

As I don't know where the `yazi.toml` is located, I tried to figure it out [here](https://yazi-rs.github.io/docs/usage/configuration/overview). I presume it is inside `~/.config/yazi` directory.

<img width="749" alt="image" src="https://github.com/sxyazi/yazi/assets/58279735/c82e2e17-dd5d-4358-b830-b3970dfbf11c">

Plus, I installed using Homebrew. I tried to find it inside `/opt/homebrew` folder, no success at all too.

**Comment by osenvosem** [comment]
> Hey, could you paste your `yazi.toml` file here?

I use the default configuration.

**Comment by osenvosem** [comment]
> Thanks for the report.
> 
> If you don't have the [`~/.config/yazi/yazi.toml`](https://yazi-rs.github.io/docs/usage/configuration/yazi), it means you are using the default configuration. I am also using macOS and have installed Yazi v1.0.4 via Homebrew, using the default configuration, and I haven't encountered this issue. Could you please describe your steps so that I can reproduce it to understand what's happening?

I just installed yazi and used it for the first time. So there are no any additional steps actually. 🙂

**Comment by sxyazi** [comment]
If you are opening a text file, the default configuration uses `$EDITOR` as the editor.

Could you do a `echo $EDITOR` and paste the output here, and do a `sh -c '$EDITOR your-file-path'` to see what happens, which is the work behind Yazi.

**Comment by uncenter** [comment]
I think I might have had this issue when I was not using the `ya` wrapper function (https://yazi-rs.github.io/docs/usage/quick-start#changing-working-directory-when-exiting-yazi). Does it work if you use that?

**Comment by sxyazi** [comment]
> I think I might have had this issue when I was not using the [ya wrapper function](https://yazi-rs.github.io/docs/usage/quick-start#changing-working-directory-when-exiting-yazi) (I was changing from Zsh to Fish and I think that is the error I saw before I added the function to my Fish config from my Zsh config). Does it work if you use that?

Yeah, `ya` and `yazi` both are working well on my side.

**Comment by Endle** [comment]
Have you checked System Settings -> Privacy & Security -> Files and Folders?

**Comment by sxyazi** [comment]
Please reopen this if the problem still exists

**Comment by sxyazi** [comment]
https://github.com/sxyazi/yazi/issues/296 may be related
