### ISSUE TITLE
Character encoding error

### ISSUE THREAD

**Issue by awol2005ex** [sxyazi/yazi#253]
commit b48edfd764efac4f5b8f93baec46c445b68fecc6  rocky9  字符集 C.UTF-8 ，中文文件乱码  
![da899368a81f69bc81b0efbc5005125](https://github.com/sxyazi/yazi/assets/181391/a993d671-f359-4a00-bd81-820cd697f92b)

**Comment by sxyazi** [comment]
Are all the Chinese files displaying garbled characters, or is it just a specific one?

所有中文文件都乱码，还是只是某个特定文件？

**Comment by awol2005ex** [comment]
> Are all the Chinese files displaying garbled characters, or is it just a specific one? Will there be garbled characters if there is Chinese content in the file?
> 
> 所有中文文件都乱码，还是只是某个特定文件？文件中有中文内容会出现乱码吗？

所有中文文件名乱码，文件中内容没有乱码

**Comment by sxyazi** [comment]
I'm not quite sure how to reproduce it, can you try another terminal to see if it works?

我不太清楚该如何复现它，你可以尝试下其它终端看看是否能正常工作吗？

**Comment by sxyazi** [comment]
Please reopen this if the problem still exists

**Comment by awol2005ex** [comment]
这是mobaterm上传中文文件的文件名造成的，其他ssh客户端都没有这个问题
