### ISSUE TITLE
lazygit via Shell very laggy

### ISSUE THREAD

**Issue by Jinx-FX** [sxyazi/yazi#256]
When I use lazygit in yazi by shell, it gets very laggy and difficult
the error is reported as follows in Mac default terminal：

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', core/src/input/snap.rs:82:35
 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

and if I do something, it will be very troublesome to quit(this is in kitty): 

<img width="750" alt="截屏2023-10-11 23 36 36" src="https://github.com/sxyazi/yazi/assets/77578910/b25b27ed-73b8-49e0-b9c9-2cd182f2a1cd">

<img width="1149" alt="截屏2023-10-11 23 37 55" src="https://github.com/sxyazi/yazi/assets/77578910/e8c1555d-f0fb-4645-9311-498702abaf48">

I think when I use other tools I also have some problems like this

**Comment by sxyazi** [comment]
Could you paste your `yazi.toml` here and describe the steps to reproduce this issue?

**Comment by Jinx-FX** [comment]
> Could you paste your `yazi.toml` here and describe the steps to reproduce this issue?

To reproduce this issue:
1. enter yazi and use shell function ： `;` >> `lazygit` 
2. Then in the lazygit
   1. if you do nothing and quit it, you will back the yazi, but you can't see the yazi UI
   2. if you do something, you will feel it laggy and if your operations are very frequent, you may see the hint UI bug and thread bug and it's difficult to quit

this is my yazi.toml
```toml
[manager]
layout         = [ 1, 4, 3 ]
sort_by        = "modified"
sort_sensitive = true
sort_reverse   = true
sort_dir_first = true
show_hidden    = false
show_symlink   = true

[preview]
tab_size   = 2
max_width  = 600
max_height = 900
cache_dir  = ""

[opener]
folder = [
	{ exec = 'open -R "$@"', display_name = "Reveal in Finder" },
	{ exec = '$EDITOR "$@"' },
]
archive = [
	{ exec = 'unar "$1"', display_name = "Extract here" },
]
text = [
	{ exec = 'nvim "$@"', block = true },
]
image = [
	{ exec = 'open "$@"', display_name = "Open" },
	{ exec = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show EXIF" },
]
video = [
	{ exec = 'mpv "$@"' },
	{ exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
]
audio = [
	{ exec = 'mpv "$@"' },
	{ exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
]
fallback = [
	{ exec = 'open "$@"', display_name = "Open" },
	{ exec = 'open -R "$@"', display_name = "Reveal in Finder" },
]

[open]
rules = [
	{ name = "*/", use = "folder" },

	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "video" },
	{ mime = "audio/*", use = "audio" },
	{ mime = "inode/x-empty", use = "text" },

	{ mime = "application/json", use = "text" },
	{ mime = "*/javascript", use = "text" },

	{ mime = "application/zip", use = "archive" },
	{ mime = "application/gzip", use = "archive" },
	{ mime = "application/x-tar", use = "archive" },
	{ mime = "application/x-bzip", use = "archive" },
	{ mime = "application/x-bzip2", use = "archive" },
	{ mime = "application/x-7z-compressed", use = "archive" },
	{ mime = "application/x-rar", use = "archive" },

	{ mime = "*", use = "fallback" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false
```

**Comment by sxyazi** [comment]
This is the expected behavior; you should use `:` instead of `;` to run lazygit in blocking mode:

> Open in a blocking manner. After setting this, Yazi will hide into a secondary screen and display the program on the main screen until it exits. During this time, it can receive I/O signals, which is useful for interactive programs.

**Comment by sxyazi** [comment]
More details:

Yazi sets up piped stdio for processes launched in all *non-blocking* modes (`;`), but `lazygit` doesn't follow it. I suspect it writes the TUI directly to `/dev/tty`, causing it to preempt the terminal session with Yazi. You can test it with:

- `lazygit > /dev/null 2>&1`, and you can still see the TUI, indicating that it doesn't follow redirection.
- In contrast, `yazi > /dev/null 2>&1`, and you won't see any content since the TUI has been redirected.

**Comment by Jinx-FX** [comment]
> This is the expected behavior; you should use `:` instead of `;` to run lazygit in blocking mode:
> 
> > Open in a blocking manner. After setting this, Yazi will hide into a secondary screen and display the program on the main screen until it exits. During this time, it can receive I/O signals, which is useful for interactive programs.

thx, it works now 😘
