### ISSUE TITLE
new theme system leads to panic on selection

### ISSUE THREAD

**Issue by koopa1338** [sxyazi/yazi#258]
After updating to the latest commit, yazi panics on selecting an entry. In a debug build the application does not crash completely, I can move around and the preview does still work, but I can't see any entries in my current directory, see this screenshot:
![yazi_ui_crash](https://github.com/sxyazi/yazi/assets/20669804/bcb48ccd-9f4e-49d9-b4b8-4c96b7de0e3e)

I haven't managed to get any further debug info, but this regression came with the latest commit as a build from 15c34fed5c006c7b9b9152ffe6da32735ae77773 does work.

terminal: alacritty

**Comment by sxyazi** [comment]
Thanks for trying the new theme system in advance and reporting its issues!

Setting the parent layout width to 0 may be a reasonable guess as to what's causing the problem. I have [pushed a new commit](https://github.com/sxyazi/yazi/commit/cdd20f851005d1e379804ad90c3669f4d97e36d8), please give it a try to see if it resolves your issue.

**Comment by koopa1338** [comment]
I can confirm that it was the 0 width for the parent directory column that caused the issue. After the latest commit, the issue is resolved for me, and it works as before.
