### ISSUE TITLE
Unclear message on quit: There are 2 tasks running, sure to quit? (y/N)

### ISSUE THREAD

**Issue by kmicklas** [sxyazi/yazi#263]
This is likely user error of some kind, however I cannot figure out what I am doing wrong. Very often when I try to quit yazi I will be prompted with a question like

```
There are 2 tasks running, sure to quit? (y/N)
````

even though as far as I know I have not launched any tasks at all. How do I find what these tasks are?

**Comment by Brixy** [comment]
Hi! You can show the tasks manager with the default binding `w` and close a task with `x`.

**Comment by kmicklas** [comment]
Thanks! It looks like I was probably trying to open things by hitting Enter.
