### ISSUE TITLE
Questions when previewing and opening files

### ISSUE THREAD

**Issue by youn0g** [sxyazi/yazi#267]
Hello, I am very happy to use this tool.
However, it is not possible to preview certain types of files during use (it is possible to preview directories, and it is also not possible to open files.
I am certain that I have installed the most dependencies instructed in README(
apart from poppler).
Additionally, I have coped the 'the preset configs' as my own configs, just like this:
 
![image](https://github.com/sxyazi/yazi/assets/93355889/6e6ea5b9-7372-4182-9a37-c841ad433212)
Finally, a picture using yazi is attached:
![image](https://github.com/sxyazi/yazi/assets/93355889/d1dee89d-ef81-4fd7-a20d-efe4b6960aeb)

Waiting for your help! thx

**Comment by sxyazi** [comment]
Have you added Git to the `PATH` according to the [Windows Installation Guide](https://github.com/sxyazi/yazi/wiki/Windows-Installation-Guide#requirements)?

Please make sure the `file` command is available in your terminal, you can do a `file -v` to verify it.

**Comment by youn0g** [comment]
Based on the ideas you provided, I reconfirmed the git environment variables. 
The fact is that git is installed correctly, and the default installation of git on the window where the path added to the environment variable is C:\Program File\Git\cmd.
But I discovered something even more torturous: The 'file' command cannot be used in pwsh, but it can be used normally in git bash.That's not all,  using yazi in git bash will cause the page to stutter
![image](https://github.com/sxyazi/yazi/assets/93355889/ec41d285-3a66-4b80-839c-23bd6f312fc2)
<img width="439" alt="微信图片_20231013224352" src="https://github.com/sxyazi/yazi/assets/93355889/47ad6616-3000-4274-80c4-097d5275af22">

**Comment by sxyazi** [comment]
> The fact is that git is installed correctly, and the default installation of git on the window where the path added to the environment variable is C:\Program File\Git\cmd.

Note that it should be `C:\Program Files\Git\usr\bin`, rather than `C:\Program File\Git\cmd` in the [Windows Installation Guide](https://github.com/sxyazi/yazi/wiki/Windows-Installation-Guide#requirements).

<img width="829" alt="image" src="https://github.com/sxyazi/yazi/assets/17523360/b9f73f87-6724-4c3b-acce-85476b10db27">


> That's not all, using yazi in git bash will cause the page to stutter


This is a specific issue with the combination of Mintty (Git Bash) and ConPTY, not a bug in Yazi; [Windows Terminal](https://github.com/microsoft/terminal) should work properly.

**Comment by youn0g** [comment]
After resetting the environment variables, the file preview returned to normal. 
I misunderstood the meaning of the document, so I am very sorry for the inconvenience caused to you. Thank you very much for your kind help.
I should have learned the difference between the two paths in hindsight.
Now I have a new question. When setting the exec command of text in 'yazi.toml', it seems that setting the parameter to '%n' has no effect. 
![image](https://github.com/sxyazi/yazi/assets/93355889/77a4a1fa-ebd0-429d-9733-434b3960d318)
Trying to remove the parameters after nvim, this does open a file, but if there is a need to open multiple files at the same time, this is obviously not enough for me.
This problem also occurs when opening the compressed file, and I don't know how to set the unzip path to some fixed path (i.e. not the current path).
Where does my problem occur? thx

**Comment by youn0g** [comment]
And my title did not clearly express my meaning, so it caused you trouble. I apologize to you

**Comment by sxyazi** [comment]
%*, %1, %2, ... Support for these placeholders was added recently and will be shipped with Yazi v1.0.5, you can use it in advance from a source build.

See https://yazi-rs.github.io/docs/usage/configuration/yazi#opener for more details.

**Comment by youn0g** [comment]
Well, the current version is Yazi v0.1.4.
Then how to set the default path of the decompression to another path?
![image](https://github.com/sxyazi/yazi/assets/93355889/774860ca-160f-48f4-852b-6a9273d29b51)
The JS file cannot be previewed properly, nor can it be opened

**Comment by sxyazi** [comment]
Do other files work properly? Please do a `file -b --mime-type your-js-file-path.js` to see what output comes out

**Comment by youn0g** [comment]
![image](https://github.com/sxyazi/yazi/assets/93355889/c5325b07-2a77-4403-9288-cb68a5b725ed)
By the way, the vue files also can't work properly.
In addition, no other files were found not to work properly.

**Comment by youn0g** [comment]
The Java class file is also not working properly
Although this document is not much to read, but hope to provide you with an idea

**Comment by sxyazi** [comment]
So apart from the java class, it's only Vue files that can't be previewed? Regarding the java class, when the Yazi plugin system comes out, it will allow users to add their own previewer

**Comment by youn0g** [comment]
Yes, the most files in vue project can't be previewed.

**Comment by sxyazi** [comment]
Just tested, it works fine for me. Can you place the files that cannot be previewed here so that I can test using them?

<img width="845" alt="image" src="https://github.com/sxyazi/yazi/assets/17523360/21578bf7-865b-49bd-bcec-f1f48a696b5c">

**Comment by youn0g** [comment]
[waf.zip](https://github.com/sxyazi/yazi/files/12901765/waf.zip)
Of course. thx

**Comment by youn0g** [comment]
![image](https://github.com/sxyazi/yazi/assets/93355889/cfb107b9-4e47-4f82-97af-e31d7dd3209b)
When I configured Lunarvim(lvim) as the default text editor, the following error occurred

**Comment by sxyazi** [comment]
I noticed that you joined Yazi's Telegram group. Let's conclude this and continue on Telegram, since this is not a Yazi bug. Compared to an issue, the community group is an easier way to get help. 👍🏻
