### ISSUE TITLE
New version of tracing breaks build

### ISSUE THREAD

**Issue by ndtoan96** [sxyazi/yazi#270]
Run `cargo install --git https://github.com/sxyazi/yazi.git`. It will returns a ton of error about missing `option`, `iter`... in `core`.

Don't know what's wrong, I've set up a simple app and used tracing to log out an Option but it works fine.

Work around for now is `cargo install --locked --git https://github.com/sxyazi/yazi.git`

**Comment by sxyazi** [comment]
I have reproduced the issue, sadly, I don't know how to fix it. It might be a compiler bug, not sure...

**Comment by sxyazi** [comment]
Its a bug in tracing, see https://github.com/tokio-rs/tracing/issues/2761

**Comment by sxyazi** [comment]
Fixed by https://github.com/tokio-rs/tracing/pull/2762, closing then
