### ISSUE TITLE
(hyprland/foot) Image Previews don't work if $TERM is set to foot-extra 

### ISSUE THREAD

**Issue by pablo-888** [sxyazi/yazi#274]
If you leave $TERM as just "foot" it causes ncurses applications to misbehave (e.g https://codeberg.org/dnkl/foot/issues/1429) so installing foot-terminfo and setting $TERM to foot-extra is necessary. Problem is yazi doesn't preview images if you do that (At least for me. Can someone else confirm?)

(btw this is not a big deal since I can make a script that literally just runs "$TERM=foot yazi". thought i'd report it just in case still).

**Comment by sxyazi** [comment]
Interesting, just found out about `foot-extra`. Well, I'm not a die-hard fan of foot. 🤣

I've created a simple PR to fix it. Let me know if it works for you. https://github.com/sxyazi/yazi/pull/277

**Comment by pablo-888** [comment]
That worked. 👍
