### ISSUE TITLE
display the number of deleted files in the prompt

### ISSUE THREAD

**Issue by teto** [sxyazi/yazi#286]
Right now (0.1.4), Iit shows 
`Sure to move selected files to trash ?`
displaying additionnaly the number of files could help prevent errors, for instance:
`Sure to move 42 selected files to trash ?`

Also I wondered, what does it mean by "to trash" ? does it move the files into a specific folder or does it run a plain "rm" ?

NB: I am still not a fan of the prompt input "y/n" followed by "Enter". Any reason/is it planned to remove the need to press "Enter" ?

**Comment by magnetophon** [comment]
@teto I had made a similar request yesterday: https://github.com/sxyazi/yazi/issues/285

**Comment by teto** [comment]
my bad I missed that. I will let @sxyazi decide which one to keep this my issue looks better scoped :p

**Comment by sxyazi** [comment]
> Also I wondered, what does it mean by "to trash" ? does it move the files into a specific folder or does it run a plain "rm" ?

For `d`, it moves to the trash via (trash crate)[https://crates.io/crates/trash]; for `D`, it permanently deletes the file.

> NB: I am still not a fan of the prompt input "y/n" followed by "Enter". Any reason/is it planned to remove the need to press "Enter" ?

Some discussions [quoted from Discord](https://discord.com/channels/1136203602898194542/1146658361740369960/1161327530024906882):

not sure if making the Input component support not requiring an `Enter` is a good idea
sometimes people need the Enter (renaming), and sometimes they don't (deleting), which could lead to confusion since they really look quite similar
When people press `y` to delete a file but forget that it doesn't require an `Enter`, the file gets deleted... uh.

**Comment by teto** [comment]
thanks, I didnt know there was a spec for it https://specifications.freedesktop.org/trash-spec/trashspec-1.0.html so on linux it goes to $XDG_DATA_HOME/Trash for instance (since the crate was not explicit about it).

> sometimes people need the Enter (renaming), and sometimes they don't (deleting), which could lead to confusion since they really look quite similar
> When people press y to delete a file but forget that it doesn't require an Enter, the file gets deleted... uh.

one solution can be to make them look different. I dont find it surprising either. If I have to input a folder path, I have to press Enter to mark the end of the input but when it's a boolean choice, I dont see why I would press "y" to say "no". Also if it goes to trash it can be recovered.

**Comment by magnetophon** [comment]
> I dont find it surprising either. If I have to input a folder path, I have to press Enter to mark the end of the input but when it's a boolean choice, I dont see why I would press "y" to say "no". Also if it goes to trash it can be recovered.

Fully agreed.

**Comment by sxyazi** [comment]
> one solution can be to make them look different. I dont find it surprising either.

How to make it look different?

> If I have to input a folder path, I have to press Enter to mark the end of the input but when it's a boolean choice, I dont see why I would press "y" to say "no". Also if it goes to trash it can be recovered.

This kind of confusion has a global impact, not just on "trash". Currently, I can think of:

- Confirmation when trashing.
- Confirmation when deleting.
- Overwrite confirmation when renaming a file if it already exists.

This means you need to be mindful at all times. When renaming, you need an `Enter` when specifying the target path, and you don't need an `Enter` when confirming the overwriting on target file already exists. They both occur in a single `rename` operation.

Regarding the `trash`, in fact, it's not always available. When you need to trash files across mount points, you can only permanently delete them, and this is a risky operation. It cannot be undone. https://github.com/sxyazi/yazi/issues/246
