### ISSUE TITLE
Show symlink path below

### ISSUE THREAD

**Issue by alvaro17f** [sxyazi/yazi#287]
First of all, THANK YOU very much for such an awesome app.

I think that the way symlinks are shown make too much noise.

I mean:
```sh
filename -> /home/$USER/path/to/file
```

If you take a look at joshuto, the way it shows the path to the file is great. At the bottom of the TUI.

I know Yazi is able to hide the path of the symlink, but I still want to know it's a symlink and where it comes from.

Thanks in advance.

**Comment by sxyazi** [comment]
Thanks for your appreciation. Some users (like me) prefer symlinks displayed alongside directories, while others like them in the bottom status bar.

Ideally, Yazi would choose one, but to accommodate the needs of others, I put in a lot of effort to develop a theming system. You can use Lua to rewrite most of Yazi's UI, and for this case, it's should easy to implement.

I have added it to the tips of the doc, take a look at https://yazi-rs.github.io/docs/usage/tips#show-symlink-in-status-bar

(Note: The theme system is a new feature that will be shipped with v1.0.5, currently you need to build Yazi from main branch.)

<img width="1058" alt="image" src="https://github.com/sxyazi/yazi/assets/17523360/5d300676-44c2-4275-bfb4-95e90013f6ce">

**Comment by sxyazi** [comment]
[v0.1.6 will have it built-in](https://github.com/sxyazi/yazi/issues/262), but for now, you can achieve it also through a UI plugin.
