### ISSUE TITLE
chmod

### ISSUE THREAD

**Issue by alvaro17f** [sxyazi/yazi#288]
Would it be possible to add a way to set chmod from Yazi.

This is already possible in joshuto and in lf.

**Comment by sxyazi** [comment]
Currently, you can achieve this through the `shell` command, like this https://github.com/sxyazi/yazi/issues/51#issuecomment-1763697521, and there will be a new way to do it after the release of Yazi v1.0.6 shipped with the plugin system.

**Comment by alvaro17f** [comment]
Awesome, thank you very much @sxyazi , it helped me a lot.
In the meantime, if someone in the future is wondering how to achieve this, I've just added the following line:

```sh
  { on = ["="], exec = """
    shell 'printf "Mode Bits: "; read ans; chmod $ans "$@"' --block --confirm
  """, desc = "chmod" },
```
