### ISSUE TITLE
Syntax highlighting on macOS's Terminal.app is strange

### ISSUE THREAD

**Issue by mdesmedt** [sxyazi/yazi#295]
Trying yazi for the first time, it builds and runs perfectly on MacOS Sonoma. However, inside the Terminal app with the default "Basic" theme syntax highlighting looks weird. There's white-on-teal highlighting which shows up in nearly every file. Not sure if it's a code bug or possible config improvement for Mac.

<img width="1256" alt="Screenshot 2023-10-21 at 7 41 25 AM" src="https://github.com/sxyazi/yazi/assets/73319561/7ff723e5-0639-4124-a5a0-d7af193bea77">

**Comment by sxyazi** [comment]
Thanks for the report.

Currently, Yazi's code highlighting only supports terminals that have true color support. Unfortunately, macOS's Terminal.app is one of the few terminal emulators that still lacks true color support.

This is definitely a point for improvement, and it's already in the plans for v0.1.6. For now, you can use terminals like iTerm2, Kitty, etc., which not only offer more powerful functionality but also support image previews.

**Comment by sxyazi** [comment]
Done by https://github.com/sxyazi/yazi/pull/460
