### ISSUE TITLE
Invalid link in Windows Installation Guide

### ISSUE THREAD

**Issue by Dream4ever** [sxyazi/yazi#299]
[the preset configs](https://github.com/sxyazi/yazi/tree/main/config/preset) in wiki page [Windows Installation Guide](https://github.com/sxyazi/yazi/wiki/Windows-Installation-Guide) is invalid, maybe it should point to https://github.com/sxyazi/yazi/tree/main/yazi-config/preset or some specific file under that fold?

**Comment by sxyazi** [comment]
Thank you for the report. It should be fixed now.
