### ISSUE TITLE
warning: unused variable: `permissions` in yazi-shared\src\fs.rs:96:20

### ISSUE THREAD

**Issue by olivier-fs** [sxyazi/yazi#300]
Hi! 

THX for yazi, ultra fast, I love it !

When building with windows there is a warning:
```
warning: unused variable: `permissions`
  --> yazi-shared\src\fs.rs:96:20
   |
96 | pub fn permissions(permissions: Permissions) -> Option<String> {
   |                    ^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_permissions`
   |
   = note: `#[warn(unused_variables)]` on by default
```

```rust
pub fn permissions(permissions: Permissions) -> Option<String> {
	#[cfg(windows)]
	return None;

	#[cfg(unix)]
	...
```

So yes windows ACLs are still a TODO (a big one, I know ;-)

But this kind of warning is worrying at first sight.

Maybe put the whole permissions() in #[cfg(windows)], with a separate one for #[cfg(unix)] ?

Regards

**Comment by sxyazi** [comment]
Good idea.

Just curious, does Windows have something like specific user and file permissions similar to Unix?

**Comment by olivier-fs** [comment]
Thx for fixing the warning.

Yes Windows has "permissions" too they are called ACLs (Access Control Lists), each list having ACEs (Access Control Entries).

There is a crate for managing ACLs : [windows-acl](https://github.com/trailofbits/windows-acl). They have an ["introducing windows-acl" blog post](https://blog.trailofbits.com/2018/08/23/introducing-windows-acl-working-with-acls-in-rust/).

Not sure if the windows-rs crate has bindings for the various Security/Identity/Authorization APis...
