### ISSUE TITLE
Show file owner

### ISSUE THREAD

**Issue by alvaro17f** [sxyazi/yazi#308]
It would be awesome to see the owner of the files/folders in the statusbar.

Thank you.

**Comment by sxyazi** [comment]
> Would it be possible to put this behind a config flag, so there is at least the option to turn it off? I'm not interested in this information and really like the clean design of Yazi.

Yazi only provides essential UI APIs to users and a simple way to combine them, so this will not disrupt the expectations of existing users.

**Comment by sxyazi** [comment]
Done by https://github.com/sxyazi/yazi/pull/469, see this tip: https://yazi-rs.github.io/docs/tips#show-usergroup-of-files-in-status-bar

![owner](https://github.com/sxyazi/yazi/assets/17523360/df579ad7-4132-434c-9e47-ac86b56b99b7)
