### ISSUE TITLE
Running as sudo doesn't allow access to standard $USER folder

### ISSUE THREAD

**Issue by alvaro17f** [sxyazi/yazi#317]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

alacritty

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

When I run yazi as sudo, I am able to see root folders, but I'm not able to see my `/home/$USER` folder

### Expected Behavior

I would expect to be able to see every root directory that root have access to.

### To Reproduce

run: `sudo yazi` or `sudo -E yazi`

**Comment by sxyazi** [comment]
When you run as root, `$USER=root`, are you sure that the `/home/root` directory exists?

**Comment by alvaro17f** [comment]
No, I mean, if you run `sudo yazi`, you get accesss to `/root` but you're not able to acces anymore to `/home/$USER/`

**Comment by alvaro17f** [comment]
https://github.com/sxyazi/yazi/assets/89421445/aabbf99f-26cc-4dcc-a5ce-fffda762f73b

**Comment by sxyazi** [comment]
Please do a `ls -al /home/alvaro17f` and paste the output here.

**Comment by sxyazi** [comment]
From the video, there may be an issue with `sudo`, as it significantly slows down the startup compared to launching without `sudo`, I'm not sure what happened behind

**Comment by alvaro17f** [comment]
```sh
drwx--x--- alvaro17f alvaro17f 834 B  Wed Oct 25 11:08:32 2023  .
drwxr-xr-x root      root       18 B  Tue Oct 17 09:06:21 2023  ..
```

**Comment by alvaro17f** [comment]
BTW, it's working fine with `joshuto` or `lf`

**Comment by sxyazi** [comment]
Sadly I can't reproduce it and can't guess the possible reasons. Could you try to help debug it on your side?

**Comment by alvaro17f** [comment]
I have found where does the problem comes from.
It only occurrs when I have a folder mounted with fuse inside of my user's folder.

**Comment by sxyazi** [comment]
I made a PR https://github.com/sxyazi/yazi/issues/317, let me know if it works for you!

**Comment by alvaro17f** [comment]
Reviewed 👍🏻

**Comment by alvaro17f** [comment]
You're truly AWESOME.

Thank you @sxyazi
