### ISSUE TITLE
Quit Error on Large JSON file

### ISSUE THREAD

**Issue by Ziqi-Yang** [sxyazi/yazi#328]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

(both tested) kitty 0.30.1 and foot version: 1.16.2 +pgo +ime +graphemes -assertions

### Yazi version

0.1.5.r18.g2b73174-1

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

`yazi` on one folder with contains a large json file `Firefox 2023-10-31 14.30 profile.json` ( 18Mb). The other attribution of the file:
```bash
❯ file ./Firefox\ 2023-10-31\ 14.30\ profile.json
./Firefox 2023-10-31 14.30 profile.json: Unicode text, UTF-8 text, with very long lines (65534), with no line terminators
```
The bug happens(not immediately) when the cursor pass the position of  file `Firefox 2023-10-31 14.30 profile.json` (i.e preview). It works normal when I'm still in `yazi` (though cpu usage increases many) The problem is that though I can quit the TUI of `yazi`,  I cannot fully quit `yazi`, which means the program is stuck after I quit, and I cannot go back to my shell. I need to close the window of the terminal emulator that runs `yazi`. However, `yazi` is still not killed, I need to manually `pkill -9 yazi` to kill `yazi`.

### Expected Behavior

1. don't preview or preview first N characters of the json file.
2. normal quit behavior 

### To Reproduce

To get the required JSON file:
open firefox, open web developer tools, in the `performance` tab, record few seconds, and download the performance analysis file (top right corner -> `upload local profile` -> `download`. 

Since the JSON file may contain sensitive data, I will not share my file. 

### Configuration

no config

**Comment by sxyazi** [comment]
Ugh, that's quite unfortunate -- the highlighter works on a line-by-line basis. 

In the case of this JSON file, it contains all the content on a single line, which would be a nightmare for all highlighters. Hence the best approach is to fallback to plain text in this situation, which is also the behavior of most editors.

I've created a PR to address this, let me know if it works for you. https://github.com/sxyazi/yazi/pull/329
