### ISSUE TITLE
CSV preview

### ISSUE THREAD

**Issue by panday1995** [sxyazi/yazi#333]
### Is your feature request related to a problem? Please describe

I cannot know what is in a csv file from the tui

### Will you be willing to contribute this feature?

- [ ] Yes, I will try to implement it

### Describe the solution you'd like

I want to have a preview of csv files, e.g., the first few rows of the csv file

**Comment by sxyazi** [comment]
What tools do you use to preview CSV files?

**Comment by uncenter** [comment]
I don't use these but here are some popular ones:
- https://github.com/johnkerl/miller
- https://github.com/BurntSushi/xsv

**Comment by panday1995** [comment]
> What tools do you use to preview CSV files?

I never used a terminal for csv preview actually. I used to use a VScode csv viewer extension. But would like to know if it is possible to have this feature. (https://github.com/mechatroner/vscode_rainbow_csv/tree/master)

**Comment by januz** [comment]
previews using [`csvlens`](https://github.com/YS-L/csvlens) would be fantastic

**Comment by sxyazi** [comment]
Hi! Would you like to make it a previewer plugin?


Yazi allows you to create and use your own previewers and preloaders. You can start by copying the [json.lua](https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/plugins/json.lua) into your `~/.config/yazi/plugins/csv.yazi/init.lua`, see the docs here https://yazi-rs.github.io/docs/plugins/overview#previewer

And if you're willing, I'll add your repo url to the Yazi documentation somewhere, maybe "community plugins".

**Comment by Reledia** [comment]
I made miller a plugin previewer now: [miller.yazi](https://github.com/Reledia/miller.yazi). I couldnt go with csvlens as it's a TUI that won't support full piping (the author stated so in their issues), so I think mlr is the way to go (even if I dont like the way they handle colors).

**Comment by sxyazi** [comment]
Thank you! @Reledia 

Let's close this issue then
