### ISSUE TITLE
Command to enter a directory or open the selected file

### ISSUE THREAD

**Issue by Xgames123** [sxyazi/yazi#335]
### Is your feature request related to a problem? Please describe

I always press \<Enter\> on a directory to enter it but it opens it in the editor.

### Will you be willing to contribute this feature?

- [ ] Yes, I will try to implement it

### Describe the solution you'd like

A open-enter option in the keymap.toml
```
{ on = [ "\<Enter\>" ],   exec = "open-enter",  desc = "Open/enter the selected files or directories" },
```

### Describe alternatives you've considered
In open rules you could also have something like this
[open]
rules = [
  { mime = "inode/directory",             use = [ "enter" ] }
]

**Comment by Xgames123** [comment]
I didn't read the docs
https://yazi-rs.github.io/docs/faq#why-cant-open-and-enter-be-a-single-command

**Comment by SolitudeSF** [comment]
does the current plugin infrastructure allows for this to be implemented?
this is the only fm i know that insists on splitting this functionality and it makes using it very obnoxious.

**Comment by sxyazi** [comment]
Hi @SolitudeSF, Sadly to say that Yazi's plugin system has not been available yet.

I'm refactoring the code to prepare for the plugin system recently, https://github.com/sxyazi/yazi/pull/338.

**Comment by sxyazi** [comment]
We've supported it now, see this tip https://yazi-rs.github.io/docs/tips/#smart-enter-enter-for-directory-open-for-file.

Note that Yazi main branch is currently required.
