### ISSUE TITLE
Left Column Hover Changed when Showing/Hiding Hidden Files

### ISSUE THREAD

**Issue by EdgeRealm** [sxyazi/yazi#337]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

iTerm2

### Yazi version

0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

The left column hover position (parent folder) changed when Showing/Hiding Hidden Files. Now when you press left and then right, you will end up in a different folder.

### Expected Behavior

The hover position should remain unchanged.

### To Reproduce

https://github.com/sxyazi/yazi/assets/109451175/f7f7b9bb-a372-4555-a216-fa953077901b

**Comment by sxyazi** [comment]
Thanks for the reporting.

I made a PR to fix this, https://github.com/sxyazi/yazi/pull/339, let me know if it works for you!

**Comment by EdgeRealm** [comment]
Thanks for your fix! It works.
