### ISSUE TITLE
yazi crashes one the limit of open files is reached

### ISSUE THREAD

**Issue by teto** [sxyazi/yazi#340]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.30.1 

### Yazi version

yazi-0.1.5pre20231027_396f60d

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

when I've got a lot of stuff going on yazi fails with
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io(Os { code: 24, kind: Uncategorized, message: "Too many open files" }), paths: [] }', yazi-core/src/manager/watcher.rs:64:48
                    stack backtrace:
                                       0: rust_begin_unwind
                                                              1: core::panicking::panic_fmt
                                                                                              2: core::result::unwrap_failed
                                                                                                                               3: yazi_core::context::Ctx::make
                                                                                                                                                                  4: yazi::main
                                                                                                                                                                               note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
                                                                      zsh: abort (core dumped)  yazi
```
This seems expected since as soon as I run `ulimit -n 4096` (my default is 1024) yazi works again. Not sure what a proper fix is:
- dont crash and exit with the suggestion of using `limit -n`
- disable filewatching ?

### Expected Behavior

no crash

### To Reproduce

open tons of file descriptor (1024)

**Comment by sxyazi** [comment]
Hi I made a PR to address it, https://github.com/sxyazi/yazi/pull/342, let me know if it works for you!

**Comment by SolitudeSF** [comment]
what is the reason for opening so many fds?

**Comment by teto** [comment]
> what is the reason for opening so many fds?

I build a software + I have firefox open. It (seemingly) never posed any issue apart from yazi.

**Comment by SolitudeSF** [comment]
im asking why would yazi need to have so many fds open.
