### ISSUE TITLE
Possibility to open a file.

### ISSUE THREAD

**Issue by jdrupal-dev** [sxyazi/yazi#344]
### Is your feature request related to a problem? Please describe

It would make sense if yazi supported a file parameter, where it would then select the chosen file upon opening.
This could be done as it has been done in e.g "lf", there you can type "lf file.txt" and the file well be selected when it opens.

This feature would especially be helpful when integrating yazy into for example neovim, where you would want to open it relative to the currently opened file.

### Will you be willing to contribute this feature?

- [ ] Yes, I will try to implement it

### Describe the solution you'd like

Currently you can pass a directory to yazi, which determines which dir to open.
I would like to have that functionality extended to allow passing files as well.

**Comment by sxyazi** [comment]
Hi I've made a PR for this, https://github.com/sxyazi/yazi/pull/358, let me know if it works for you!

**Comment by jdrupal-dev** [comment]
Hi.
Your PR works perfectly. Thank you for the fix 👍

**Comment by sxyazi** [comment]
Thank you for testing!
