### ISSUE TITLE
Crash when entering or previewing Home

### ISSUE THREAD

**Issue by Gajus84** [sxyazi/yazi#356]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

wezterm-gui 20231107-082518-f0e3eecb

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Yazi crashes when entering or previewing home directory with following code:

`thread 'tokio-runtime-worker' panicked at library/std/src/sys/unix/time.rs:77:9: assertion failed: tv_nsec >= 0 && tv_nsec`

This does not happen further down the tree for example in .config/yazi

I was able to narrow it down to the feat: new reveal command #341 commit, if I'm not mistaken.

### Expected Behavior

No crash in home directory.

### To Reproduce

Not possible to say, without tracking down what file or else is causing the crash.

### Configuration

happens also with no config.

### Anything else?

Maybe you can give me further advise to track down the cause.

**Comment by sxyazi** [comment]
Thanks for your report. After some investigation, it appears to be a Rust bug, https://github.com/rust-lang/rust/issues/108277.

Your issue is similar to https://github.com/zellij-org/zellij/issues/2369, and the root cause is the presence of files with invalid creation times in the `$HOME`. In such cases, Rust panics instead of returning an error.

The problem arose in this PR due to the inclusion of a performance optimization - parsing time and other meta information prematurely to avoid multiple subsequent parses.

I will attempt to add a `catch_unwind` as a "temporary" fix until Rust addresses it.

**Comment by sxyazi** [comment]
Hi I made a PR to fix this, let me know if it works for you! https://github.com/sxyazi/yazi/pull/357

**Comment by Gajus84** [comment]
Unfortunately still crashing.

**Comment by sxyazi** [comment]
Hi, could you try to apply the following three patches and see which one works? I can't reproduce it on my side since I don't have a file with invalid times.

```diff
- accessed: m.accessed().ok(),
+ accessed:  std::panic::catch_unwind(|| m.accessed().ok()).ok().flatten(),
```

```diff
- created:  m.created().ok(),
+ created:  std::panic::catch_unwind(|| m.created().ok()).ok().flatten(),
```

```diff
- modified: m.modified().ok(),
+ modified:  std::panic::catch_unwind(|| m.modified().ok()).ok().flatten(),
```

https://github.com/sxyazi/yazi/blob/49919cc5f44902a33ae5999c98f1e526e6731ccc/yazi-shared/src/cha.rs#L59-L61

**Comment by Gajus84** [comment]
Hi, I tried every patch and then all three at once. Neither does solve the problem.

**Comment by sxyazi** [comment]
So weird, I checked and time operations only exist in this file. What would happen if you replaced these three with `None`?

```diff
- accessed: m.accessed().ok(),
+ accessed: None,
```

```diff
- created:  m.created().ok(),
+ created:  None,
```

```diff
- modified: m.modified().ok(),
+ modified: None,
```

**Comment by Gajus84** [comment]
Yes that works. So it is the correct part of the code. Maybe the "catch_unwind" does not work?

I did test a little further and it is the "created" bit that causes the problem.

**Comment by sxyazi** [comment]
Ah yeah [`catch_unwind` cannot catch all errors](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html#notes), but it is the only way we handle this issue.

I have pushed new code that [rewrites Rust's default panic handler](https://github.com/sxyazi/yazi/pull/357/commits/cd6c3800890b6d760073275013ab2d515f5a7636). Hope it will be effective. Please give it a try!

**Comment by Gajus84** [comment]
Unfortunately still panics.

**Comment by sxyazi** [comment]
What's the output?

**Comment by Gajus84** [comment]
Just the generic ZSH core dumped

`zsh: IOT instruction (core dumped)  yazi/target/release/yazi`

**Comment by sxyazi** [comment]
```rust
use yazi_shared::Term;

pub(super) struct Panic;

impl Panic {
	pub(super) fn install() {
		better_panic::install();

		let hook = std::panic::take_hook();
		std::panic::set_hook(Box::new(move |info| {
			_ = Term::goodbye(|| {
				println!("{}", info.to_string());
				false
			});
		}));
	}
}
```

Please use this code to completely replace the `yazi-fm/src/panic.rs` file of that PR, and then paste the output here.

**Comment by Gajus84** [comment]
`panicked at library/std/src/sys/unix/time.rs:77:9: assertion failed: tv_nsec >= 0 && tv_nsec < NSEC_PER_SEC as i64`

**Comment by sxyazi** [comment]
```
use yazi_shared::Term;

pub(super) struct Panic;

impl Panic {
	pub(super) fn install() {
		better_panic::install();

		let hook = std::panic::take_hook();
		std::panic::set_hook(Box::new(move |info| {}));
	}
}
```

Try this then

**Comment by Gajus84** [comment]
Back to the generic core dumped.

Also it builds, but throws three warnings:

`warning: unused import: "yazi_shared::Term"`
`warning: unused variable: "hook"`
`warning: unused variable: "info"`

**Comment by sxyazi** [comment]
Have you restored `catch_unwind` for `yazi/yazi-shared/src/cha.rs`? It should be like this:

```rust
accessed: m.accessed().ok(), 
created: std::panic::catch_unwind(|| m.created().ok()).ok().flatten(),
modified: m.modified().ok(), 
```

**Comment by Gajus84** [comment]
Yes, I altered and build it from an pr-64b2fdd0 checkout

**Comment by sxyazi** [comment]
Hmm no more idea, I'm not sure how to address it for now...

**Comment by Gajus84** [comment]
I'm pretty sure that I can solve my problem by just moving my files a little, so they get a new timestamp. Did not do that to allow testing.
But it might be an edge case and will not hit many until rust is fixing the problem.

**Comment by sxyazi** [comment]
I have decided to disable the creation time for now. This primarily affects users who sort files by creation time.

Disabling a sub-feature seems to have a smaller cost compared to the potential process crashes -- we are always to prevent the worst-case.

I will update the documentation to indicate that the feature is currently unavailable. Once Rust addresses it, we will restore the functionality.

**Comment by sxyazi** [comment]
I've pushed a new commit, please try it out to see if it's working now.

**Comment by Gajus84** [comment]
It's working. I'll leave the files in my /home untouched as good as I can, to allow possible testing after a Rust-fix. 
Pretty sure that some ancient dot-file is causing this.

**Comment by sxyazi** [comment]
Thank you very much for your assistance in testing, let's merge it now!

**Comment by Brixy** [comment]
Thank you for this pull request.

Despite the merged pr yazi still panics.

Previewing the home directory is not (and never was) a problem. For me, yazi only becomes unresponsive with `gh`. Entering the home directory e.g. with vim keys works.

If there is anything I can test, please let me know.

**Comment by sxyazi** [comment]
@Brixy Thank you for your report that helped me discover this potential bug.

I have created a quick fix for it, it should work. https://github.com/sxyazi/yazi/commit/c49bf02ca47fd0d53e69621743c6c2cc5d67cf93

**Comment by Brixy** [comment]
Everything works now, @sxyazi.

Thank you very again for your superior maintenance!
