### ISSUE TITLE
WezTerm + Yazi on Windows does not show Image Preview

### ISSUE THREAD

**Issue by mstormo** [sxyazi/yazi#363]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

WezTerm

### Yazi version

Yazi 0.1.4

### Did you try the latest main branch to see if the problem has already been fixed?

Not tried, and I'll explain why below

### Describe the bug

I'm using the latest binary.

![image](https://github.com/sxyazi/yazi/assets/1500/4ee27793-5520-4398-8792-5402bb33a525)

![image](https://github.com/sxyazi/yazi/assets/1500/c09219d4-cdb7-42dd-a845-472872a3cf9a)

### Expected Behavior

I expect the image to show up on in the preview portion of the terminal.

### To Reproduce

On a base Windows, install both WezTerm and Yazi with scoop, like:
    `scoop install wezterm yazi`

Start WezTerm and open Yazi, find an image.

**Comment by sxyazi** [comment]
Yazi version on Scoop is outdated. Could you please try downloading the latest version from the releases page https://github.com/sxyazi/yazi/releases

Also see this https://yazi-rs.github.io/docs/faq#why-cant-i-preview-files-on-windows

**Comment by mstormo** [comment]
0.1.5 doesn't show images either
![image](https://github.com/sxyazi/yazi/assets/1500/947dc866-918d-482d-9a2a-20e2143ba220)

**Comment by sxyazi** [comment]
Have you configure your `file(1)` as per https://github.com/sxyazi/yazi/wiki/Windows-Installation-Guide#requirements?

**Comment by mstormo** [comment]
Ah, bugger. WezTerm was not inheriting the environment from the calling process, so file wasn't working.
When I manually add the missing environment, it now works. 
Thanks!
