### ISSUE TITLE
Option to force-quit (ignore `There are X tasks running, sure to quit? (y/N)` message)

### ISSUE THREAD

**Issue by againstpetra** [sxyazi/yazi#366]
### Is your feature request related to a problem? Please describe

With other terminal file managers such as lf, even if there are tasks running, if you quit the program just quits, it doesn't prompt the user if they're sure first. (Or at least I've never had to tell lf to ignore the task list; if I press `q`, it closes)

It'd be nice if this behaviour was configurable.

### Will you be willing to contribute this feature?

- [x] Yes, I will try to implement it

### Describe the solution you'd like

Some option (e.g.`force_quit`) that lets users make `quit` ignore the task list and quit without prompting the user after the user tells yazi to quit.

**Comment by musjj** [comment]
Something nice would be to distinguish between "harmless" tasks run by yazi and custom tasks initiated by the user. For example, pre-cache tasks are perfectly safe to disrupt so it shouldn't trigger a confirmation IMO.

**Comment by sxyazi** [comment]
> Something nice would be to distinguish between "harmless" tasks run by yazi and custom tasks initiated by the user. For example, pre-cache tasks are perfectly safe to disrupt so it shouldn't trigger a confirmation IMO.

Yeah that's exactly what I thought, quoted from [Discord](https://discord.com/channels/1136203602898194542/1165430526660849694/1175978953094205450):

> ..., the image pre-caching task is preventing users from exiting Yazi, unlike normal tasks such as copying or deleting files that are triggered by the user.
>
> Therefore, my idea is to have a setting for "not reporting pre-caching tasks", when it's enabled, those tasks will be invisible to the user.
>
> This includes:
> 1. Ignoring those tasks when exiting, only counting tasks created by the user;
> 2. The progress bar numbers won't include those tasks;
> 3. The task list (press `w`) won't display them either.
>
> To implement this, it needs:
> 1. [Adding a `enum TaskKind` property to `Task`](https://github.com/sxyazi/yazi/blob/d2963b23a9d6d398e6c14b13f6ae87cf4c82293f/yazi-core/src/tasks/task.rs#L4), identifying the kind of task (pre-caching task or user task).
> 2. When [adding pre-caching tasks](https://github.com/sxyazi/yazi/blob/d2963b23a9d6d398e6c14b13f6ae87cf4c82293f/yazi-core/src/tasks/scheduler.rs#L367), set their kind to `Precache`.
> 3. When [obtaining all tasks for summary](https://github.com/sxyazi/yazi/blob/d2963b23a9d6d398e6c14b13f6ae87cf4c82293f/yazi-core/src/tasks/running.rs#L39), if the user has enabled "not reporting pre-caching tasks", filter them out
