### ISSUE TITLE
[Feature request] Hide yazi and show terminal

### ISSUE THREAD

**Issue by einhander** [sxyazi/yazi#371]
### Is your feature request related to a problem? Please describe

In the shell block I can't see the output of the previous command, run the previous command e.g. work in terminal.

### Will you be willing to contribute this feature?

- [ ] Yes, I will try to implement it

### Describe the solution you'd like

I prefer the Midnight Commander-like solution of toggle on/off the whole interface by hotkey, or the Ranger-like solution where the 'exit' command exits from the terminal.

**Comment by sxyazi** [comment]
How do I return to Yazi in the terminal? I haven't used this before, could you describe the process? It would be great if you could provide a screen recording.

**Comment by einhander** [comment]
Midnight Commander style:
https://github.com/sxyazi/yazi/assets/5439042/c0b0bf1f-7c3a-4a89-92d1-045712e354ea
Ranger style:

https://github.com/sxyazi/yazi/assets/5439042/8918864c-07b2-4df9-9299-de10a515dd1d

**Comment by einhander** [comment]
Upd. It seems that it's easily done with  exec = "shell --block zsh" but how to put Enter key after zsh command?

**Comment by sxyazi** [comment]
See https://yazi-rs.github.io/docs/tips#dropping-to-the-shell

**Comment by einhander** [comment]
Oh, thank you, I missed this.
