### ISSUE TITLE
When compiled on Alpine Linux, `libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE` covers UI

### ISSUE THREAD

**Issue by againstpetra** [sxyazi/yazi#372]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.31.0

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Not tried, and I'll explain why below

### Describe the bug

- Compiled yazi on my Alpine machine as yazi is not available in the Alpine repositories
- Seeing the above message in either the header or the footer of yazi's UI (`libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE`)
- yazi remains mostly functional, but sometimes the UI glitches enough where it's no longer usable and needs to be restarted

I didn't try the latest main branch because my laptop is very slow and it takes a very long time to compile yazi.

### Expected Behavior

The message doesn't appear in the yazi UI.

### To Reproduce

- Compile yazi: `cargo install --path .`
- Open yazi

### Anything else?

Default config

**Comment by sxyazi** [comment]
Could you please paste the full error log here?

**Comment by againstpetra** [comment]
There is no full error log - that's all that shows up. Is there somewhere yazi dumps error logs?

**Comment by sxyazi** [comment]
Hmm seems to be a compiler bug, https://github.com/llvm/llvm-project/issues/86, I'm not sure how to fix it...

**Comment by sxyazi** [comment]
Close as not Yazi
