### ISSUE TITLE
Image preview sometimes fail

### ISSUE THREAD

**Issue by hakan-demirli** [sxyazi/yazi#373]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.31.0

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Preview is not created for this specific png image. The image is 68MB so I had to upload it to Google Drive.
https://drive.google.com/file/d/1UeVzkmj4vHn0msZuC3ZIjWauxIwQj9od/view?usp=sharing

I am using yazi-git from AUR. 
Yazi can create preview for even bigger files in terms of both size and resolution. So, I believe there is something strange going on with this specific image. I do not think the image is corrupt since I can edit it on paint/kolourpaint and set it as background or open it in firefox.

### Expected Behavior

It should be able to create a preview.

### To Reproduce

Download the image and look at the preview.

### Configuration

Default.

**Comment by hakan-demirli** [comment]
I have found four more images that yazi can not create preview for. 
Here are the two 102MB and 149MB ones.
https://drive.google.com/file/d/1u0krOqepIPNVb2Wu7_LKG1wEzzcoerk0/view?usp=sharing
https://drive.google.com/file/d/1gbXUON43fxg6YMJxb-y2ssBmoYz4-8ss/view?usp=sharing
I also have 200MB and 300MB images which yazi fails. I didn't upload them due to their sizes. But, if you need more images to debug I will gladly upload them.

**Comment by sxyazi** [comment]
Yazi limits the maximum memory for decoding images to 512MB. Your first image size is `20480x11520`, which means the minimum memory requirement is 20480\*11520*3/1024/1024=675MB. My macOS image preview used 992MB of memory to render it:

![es](https://github.com/sxyazi/yazi/assets/17523360/553a0ac5-721e-4838-a20c-cf997464ba60)

I think the only way is to increase the memory limit. Maybe we can make it a user-configurable option?

**Comment by hakan-demirli** [comment]
Thank you for the quick response. 
Yea, it is a good idea to let the user configure it. Since if you default it to a high number low spec PCs will be nuked.

**Comment by sxyazi** [comment]
Hi, I've created a PR for this issue, https://github.com/sxyazi/yazi/pull/376, let me know if it works for you!

> So, I assume the 512MB limit is for the display part and not the memory limit during the decoding. I have no issues with memory so I don't mind excessive caching.

512MB is the limit per single image during image decoding for precache. Yazi decodes multiple images concurrently (depending on your `macro_workers` value), and this issue is not related to the "display" part since images are downscaled to smaller sizes during displaying (based on your `max_width` and `max_height` below `[preview]`).

I also created a PR to optimize the burst memory peak during image decoding, https://github.com/sxyazi/yazi/pull/375. Roughly calculated it reduced the peak memory footprint by 75% in my case, see the row of "peak memory footprint" in that PR.

**Comment by hakan-demirli** [comment]
Indeed max memory consumption is decreased. 

But, unfortunately preview of the mentioned images are still missing.
I tried both setting it to 0 and 999999999999.
```toml
image_alloc   = 0
image_bound   = [ 0, 0 ]
```
I also deleted my personal yazi.toml and replaced it with the one in the repo which didn't work.

**Comment by hakan-demirli** [comment]
It works.

I use direnv to automate environments. There was a scope issue and it was still using the binary from the main branch. 

BTW, currently extra fields in toml file are ignored. There is no `image_alloc` field in the main branch and I put it in my yazi.toml. It didn't give any warning or errors. I don't know if this is intentional. 

Anyway, thank you for the quick fix. I assume you will close the issue when the PR lands.

**Comment by Walker-00** [comment]
I don't know what's wrong. 

I've installed yazi by compiling from source just rn.
And also added 

```toml
image_alloc   = 0  # 512MB
image_bound   = [ 0, 0 ]
```

to `$HOME/.config/yazi/yazi.toml` but somehow image preview doesn't show up.

![Screenshot_2023-11-18_09-54-09](https://github.com/sxyazi/yazi/assets/85013114/e9fc017a-782a-45d9-9c37-0871f8b8457f)

**Comment by sxyazi** [comment]
Hey @Walker-00, Can you upload this image for me to investigate?

**Comment by Walker-00** [comment]
Sure 
![Screenshot-17_11_2023-08-18-20](https://github.com/sxyazi/yazi/assets/85013114/6f0c6cc8-b239-421f-a6c0-2cb65e16b424)
![Screenshot-17_11_2023-08-18-41](https://github.com/sxyazi/yazi/assets/85013114/ea0a6569-06b3-4adf-8677-73c022ca37d0)

They show up with ranger but I like rust programs more.

**Comment by sxyazi** [comment]
Hmm it works for me

![CleanShot 2023-11-18 at 11 59 37](https://github.com/sxyazi/yazi/assets/17523360/d8c79a17-7558-4b77-927e-37c79f0dc2b7)

What terminal are you using?

**Comment by Walker-00** [comment]
Alacritty with nushell

**Comment by sxyazi** [comment]
Have you [Überzug++](https://github.com/jstkdng/ueberzugpp) installed as per https://github.com/sxyazi/yazi#image-preview?

**Comment by Walker-00** [comment]
ahh sorry, installing [Überzug++](https://github.com/jstkdng/ueberzugpp) fixed issue, think should improve doc.
