### ISSUE TITLE
Ueberzug consumes unusual ammount of resources while previewing larger files

### ISSUE THREAD

**Issue by kriestof** [sxyazi/yazi#379]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Alacritty

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

This bug report is subpart of problems described previously in #374. Mainly, part describing freezing while operating on larger files. When hovering over larger files like books in .pdf, Ueberzug consumes high amount of RAM and CPU. I've got 64 GB and 8 cores so that should be enough to generate any kind of preview.

```ps -e -o %mem,%cpu,cmd --sort=-%mem
%MEM %CPU CMD
26.9 19.3 ueberzug layer -so wayland
```

### Expected Behavior

Yazi should not freeze while doing such operations. Surely, it's too much resources for any kind of preview.

### To Reproduce

Get some larger (say 30-100 MB) .pdf files and move cursor between them. In the meantime watch your RAM and CPU usage to exit before you get freeze and hard reboot will be needed.

### Configuration

6.5.9-arch2-1
btrfs
64 GB RAM
8 core amd CPU
ueberzugpp 2.9.2-1

**Comment by sxyazi** [comment]
Can you try to use it directly without Yazi as per https://github.com/sxyazi/yazi/issues/134#issuecomment-1714397167 to see if the issue still exists?

I think it's related to https://github.com/jstkdng/ueberzugpp/issues/135

**Comment by kriestof** [comment]
Yes, sir. So `ueberzug layer` fails while trying to generate preview for .djvu files. It seems there is some kind of memory leak. You can probably try to disable generating such previews, but of course it's more a problem on Ueberzug site.

**Comment by sxyazi** [comment]
Does it occur when you directly use Überzug++ without Yazi to preview images (not PDFs)?

Is the problem described in this issue specific to previewing .djvu files? Could you upload a .djvu file for me to test?

**Comment by kriestof** [comment]
Yes, it occurs as well when directly previewing Ueberzug. 

As far as I am concerned it is specific to .djvu files. It does not seem to be the case with any of .pdf files I currently have on disk, but for now I keep only a few of them. I also converted one .pdf to .djvu to check. With .pdf no problem, but after conversion same memory leak.

You can use [sample2.djvu](https://filesamples.com/formats/djvu) to test. Oddly, `sample1.djvu` seems to work... 

Just one additional fact. I've got a warning from ueberzug.
```
unable to load "/usr/lib/vips-modules-8.14/vips-openslide.so" -- libopenslide.so.0: cannot open shared object file: No such file or directory
```
Anyway, [openslide](https://openslide.org/) does not state it supports djvu so I don't see any obvious connection.

**Comment by sxyazi** [comment]
I can't reproduce it on my Linux X11, maybe this is a Wayland-specific issue. Would you like to file an issue with Ueberzug to ask them to investigate it further?

**Comment by kriestof** [comment]
I've just checked on X11 (i3/xfce) as well. Also 4k and smaller resolution. Everywhere this bug appears. Of course it may be specific to other part of my configuration like the [version](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ueberzugpp) of the package I use.

I will fill another bug report on their repo.

**Comment by jstkdng** [comment]
hey, I don't believe this is a bug. Ueberzugpp does support djvu through libvips and the memory consumption is due to libvips loading the file and doing its stuff, not much I can do about that.

**Comment by kriestof** [comment]
> hey, I don't believe this is a bug. Ueberzugpp does support djvu through libvips and the memory consumption is due to libvips loading the file and doing its stuff, not much I can do about that.

Well, but ~6GB for a file less than 1MB is pretty much. I am not in internals of djvu format so there may be some valid reason for that. If this is justified I would again suggest disabling djvu previews in yazi as they can end up with freezes.


> I can't reproduce it on my Linux X11, maybe this is a Wayland-specific issue. Would you like to file an issue with Ueberzug to ask them to investigate it further?

I can recommend one more thing. Just wait a while. In my case it takes around 10s before the preview from djvu file will be generated and the memory usage builds during that time.

**Comment by jstkdng** [comment]
It could also be that ueberzugpp loads all libvips frames to memory, that works for gif images but libvips uses the same  abstraction for other non image formats, causing all pages in a djvu or pdf to be loaded to memory. I'd suggest to add a blacklist/whitelist of formats to prevent such large loads.

**Comment by sxyazi** [comment]
> It could also be that ueberzugpp loads all libvips frames to memory, that works for gif images but libvips uses the same abstraction for other non image formats, causing all pages in a djvu or pdf to be loaded to memory. I'd suggest to add a blacklist/whitelist of formats to prevent such large loads.

Is it possible to load only the first frame for the .djvu file? Simply disabling it would lose the preview functionality of .djvu, or is .djvu itself not in the supported formats of ueberzugpp?

**Comment by jstkdng** [comment]
yeah that can be added as well.

**Comment by sxyazi** [comment]
> yeah that can be added as well.

That's great! I'll temporarily disable .djvu files in Yazi, and re-enable it once ueberzugpp adds support for .djvu
