### ISSUE TITLE
Image preview not working in gnome terminal

### ISSUE THREAD

**Issue by 766F6964** [sxyazi/yazi#388]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kgx (aka default gnome-terminal)

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

I don't get any image previews for any image (jpg, png ...) in yazi in the default gnome terminal. (preview colum just stays empty)

- `ueberzugpp` is installed, and also runs when executed manually, aka its in the `$PATH`
- The configurations (`yazi.toml`, `keymap.toml`, `theme.toml`) are the default presets from the repo

Am I missing something? It is not explicitly listed as supported in the README, but I thought it would classify under X11/Wayland.

Information about my system:
- OS: Arch Linux
- DE: Gnome 45.1
- Terminal: Default gnome terminal, binary is called kgx
- Kernel: Linux 6.6.2-arch1-1
- Display Server: Wayland

### Expected Behavior

Image previews should show up in gnome terminal.

### To Reproduce

- Install Arch Linux with Gnome 45.1
- Install yazi and ueberzugpp
- Apply default configs
- Notice that no preview is shown when selecting any image in yazi

### Configuration

no config

### Anything else?

When I install other terminals like kitty on the same system, it works fine.
So I assume it is an issue with the gnome terminal specifically.

**Comment by sxyazi** [comment]
![CleanShot](https://github.com/sxyazi/yazi/assets/17523360/bee78699-bafc-458f-8206-acd1ee46bd07)

I can get it to work on my Arch Linux X11 with Xfce + GNOME Terminal v3.50.1.

I'm not sure if this is a Wayland-specific issue; I haven't used Wayland...

**Comment by sxyazi** [comment]
Also please do a `echo $TERM, $TERM_PROGRAM, $XDG_SESSION_TYPE` and paste the output here.

**Comment by 766F6964** [comment]
> echo $TERM, $TERM_PROGRAM, $XDG_SESSION_TYPE

`xterm-256color, kgx, wayland`

**Comment by 766F6964** [comment]
> ![CleanShot](https://user-images.githubusercontent.com/17523360/284928532-bee78699-bafc-458f-8206-acd1ee46bd07.png)
> 
> I can get it to work on my Arch Linux X11 with Xfce + GNOME Terminal v3.50.1. (ueberzugpp 2.9.2)
> 
> I'm not sure if this is a Wayland-specific issue; I haven't used Wayland...

I assume the issue must be the combination of the gnome terminal and wayland.
Because apparently it works in the gnome terminal on X11 (as seen in your screenshot), and it also works with a different terminal (e.g. kitty) under wayland.

Maybe you could try to setup a VM with ArchLinux + Gnome + Wayland to see if the problem is reproducible?

**Comment by 766F6964** [comment]
Also:
I don't have the about-dialog in my GNOME Terminal. Is your version different or does Xfce make modifications? My interface looks like this:

![Screenshot from 2023-11-22 15-42-32](https://github.com/sxyazi/yazi/assets/34845270/5ebeafd4-3fb9-4862-b5f0-249b8782406f)

**Comment by 766F6964** [comment]
When I run `ueberzugpp layer` I immediately get a crash, before I can even enter the parameters:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  UNABLE TO CALCULATE TERMINAL SIZES
zsh: IOT instruction (core dumped)  ueberzugpp layer
```
Looking into the coredump, I can see that infact ueberzug fails to determine the terminal size on initialization and crashes right away:

```
$ coredumpctl dump 99828 --output=core.dump
           PID: 99828 (ueberzugpp)
           UID: 1000 (void)
           GID: 1000 (void)
        Signal: 6 (ABRT)
     Timestamp: Wed 2023-11-22 16:49:41 CET (1min 11s ago)
  Command Line: ueberzugpp layer
    Executable: /usr/bin/ueberzug
 Control Group: /user.slice/user-1000.slice/user@1000.service/session.slice/vte-spawn-744fac34-6dc4-4ead-9fa2-c1a84fc88d7f.scope
          Unit: user@1000.service
     User Unit: vte-spawn-744fac34-6dc4-4ead-9fa2-c1a84fc88d7f.scope
         Slice: user-1000.slice
     Owner UID: 1000 (void)
       Boot ID: 74ae884f35e542e38c99d79122b85f8d
    Machine ID: 4b143abed6ca48f299d115a1e1c4e862
      Hostname: arch
       Storage: /var/lib/systemd/coredump/core.ueberzugpp.1000.74ae884f35e542e38c99d79122b85f8d.99828.1700668181000000.zst (present)
  Size on Disk: 1.9M
       Message: Process 99828 (ueberzugpp) of user 1000 dumped core.
                
                Stack trace of thread 99828:
                #0  0x00007f1b9c4ac83c n/a (libc.so.6 + 0x8e83c)
                #1  0x00007f1b9c45c668 raise (libc.so.6 + 0x3e668)
                #2  0x00007f1b9c4444b8 abort (libc.so.6 + 0x264b8)
                #3  0x00007f1b9c69ca6f _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x9ca6f)
                #4  0x00007f1b9c6b011c _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xb011c)
                #5  0x00007f1b9c6b0189 _ZSt9terminatev (libstdc++.so.6 + 0xb0189)
                #6  0x00007f1b9c6b03ed __cxa_throw (libstdc++.so.6 + 0xb03ed)
                #7  0x000055e3b588ebc5 _ZN8Terminal17get_terminal_sizeEv (ueberzug + 0x18bc5)
                #8  0x000055e3b590a4f6 _ZN8TerminalC2Ev (ueberzug + 0x944f6)
                #9  0x000055e3b58fb08c _ZSt11make_uniqueI8TerminalJEENSt8__detail9_MakeUniqIT_E15__single_objectEDpOT0_ (ueberzug + 0x8508c)
                #10 0x000055e3b5893406 main (ueberzug + 0x1d406)
                #11 0x00007f1b9c445cd0 n/a (libc.so.6 + 0x27cd0)
                #12 0x00007f1b9c445d8a __libc_start_main (libc.so.6 + 0x27d8a)
                #13 0x000055e3b5893ba5 _start (ueberzug + 0x1dba5)
                ELF object binary architecture: AMD x86-64
```

**Comment by 766F6964** [comment]
I have a suspicion that by default wayland support is disabled for ueberzugpp ... 
Maybe that is the reason. I'll do a bit more digging and will report back.

**Comment by sxyazi** [comment]
Seems there's nothing Yazi can do; closing this issue then
