### ISSUE TITLE
Include commit hash in `yazi --version`

### ISSUE THREAD

**Issue by Hanaasagi** [sxyazi/yazi#391]
### Is your feature request related to a problem? Please describe

I installed `yay` from `yay -S`.

Hi, when I open an issue, I noticed that yazi --version doesn't include the commit sha. I installed `yazi-git` via `yay`, and it shouldn't be version 0.1.5 but rather the latest from git main branch. This can be confusing when reporting bugs.

### Will you be willing to contribute this feature?

- [X] Yes, I will try to implement it

### Describe the solution you'd like

something like

1) `1.0.13+f5bf67bd1`
2) rustc 1.75.0-nightly (fee5518cd 2023-11-05)

**Comment by sxyazi** [comment]
I'm not quite sure how to include it.

Yazi is a workspace structure, I modify all crates' versions before release using https://github.com/sxyazi/yazi/blob/main/scripts/bump.sh currently, then use the `version` command of clap to display it out to users when they do a `yazi -V`:

https://github.com/sxyazi/yazi/blob/5439c80a03987fe286e721e0025b5ad4c4105615/yazi-config/src/boot/cli.rs#L6

**Comment by Hanaasagi** [comment]
example https://github.com/sxyazi/yazi/pull/393
