### ISSUE TITLE
brew install yazi , not found

### ISSUE THREAD

**Issue by MichaelC001** [sxyazi/yazi#392]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

iterm2

### Yazi version

0

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

 No available formula with the name "yazi". Did you mean yaz?

### Expected Behavior

..

### To Reproduce

..

**Comment by sxyazi** [comment]
Yazi is indeed already in Homebrew, https://formulae.brew.sh/formula/yazi. Have you run `brew update` to fetch the latest available software sources?

If this method doesn't work, you can also install it via cargo or build it directly, see: 
- https://yazi-rs.github.io/docs/installation#cargo
- https://yazi-rs.github.io/docs/installation#build-from-source

**Comment by sxyazi** [comment]
Also you can download Yazi directly from https://github.com/sxyazi/yazi/releases/tag/v0.1.5 page
