### ISSUE TITLE
Override keybinds in addition to defaults

### ISSUE THREAD

**Issue by YodaEmbedding** [sxyazi/yazi#394]
### Is your feature request related to a problem? Please describe

Changing a single binding in `manager.keymap` requires one to restate all the default bindings. But the defaults sometimes change, and I want to stay up to date.

### Will you be willing to contribute this feature?

- [ ] Yes, I will try to implement it

### Describe the solution you'd like

In addition to `manager.keymap`, allow users to define `manager.override_keymap` if they want to override only a few bindings *on top* of the default bindings.

```toml
[manager]
override_keymap = [
	{ on = [ "<C-k>" ], exec = "peek -5", desc = "Peek up 5 units in the preview" },
	{ on = [ "<C-j>" ], exec = "peek 5",  desc = "Peek down 5 units in the preview" },
	{ on = [ "<C-PageUp>" ],   exec = "peek -5", desc = "Peek up 5 units in the preview" },
	{ on = [ "<C-PageDown>" ], exec = "peek 5",  desc = "Peek down 5 units in the preview" },
]
```

**Comment by hakan-demirli** [comment]
Duplicate? https://github.com/sxyazi/yazi/issues/158

**Comment by sxyazi** [comment]
> Duplicate? #158

Ah yep
