### ISSUE TITLE
Failed to run custom build command for `mlua-sys v0.4.0`

### ISSUE THREAD

**Issue by sudhanv09** [sxyazi/yazi#395]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Kitty 0.28.1

### Yazi version

yazi master

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

cargo build --release is failing.

`error: failed to run custom build command for `mlua-sys v0.4.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/zeus/code/yazi/target/debug/build/mlua-sys-c45bf365df33cc84/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running cd "/home/zeus/code/yazi/target/debug/build/mlua-sys-29e5f9e1412656c4/out/luajit-build/build/src" && BUILDMODE="static" STATIC_CC="/home/zeus/.nix-profile/bin/cc -O2 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m64" TARGET_AR="/home/zeus/.nix-profile/bin/ar rcus" TARGET_LD="/home/zeus/.nix-profile/bin/cc -O2 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m64" TARGET_STRIP="/home/zeus/.nix-profile/bin/strip" TARGET_SYS="Linux" XCFLAGS="-fPIC -DLUAJIT_ENABLE_LUA52COMPAT" "make" "-e"

  --- stderr
  thread 'main' panicked at /home/zeus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/luajit-src-210.5.2+113a168/src/lib.rs:259:39:
  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
     1: core::panicking::panic_fmt
               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
     2: core::result::unwrap_failed
               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
     3: core::result::Result<T,E>::unwrap
     4: luajit_src::Build::run_command
     5: luajit_src::Build::build_unix
     6: luajit_src::Build::build
     7: build_script_main::find::probe_lua
     8: build_script_main::main
     9: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...`

### Expected Behavior

build successful

### To Reproduce

NixOS 23.05

git clone https://github.com/sxyazi/yazi
cd yazi
RUST_BACKTRACE=1 cargo build --release

or 

cargo install --locked yazi-fm

**Comment by sxyazi** [comment]
What's your Rust version? Please try to do a `cargo clean` and redo the `cargo build --release` again to see if the issue disappears.

**Comment by sxyazi** [comment]
I found an issue that may related to the problem, https://github.com/khvzak/luajit-src-rs/issues/2#issuecomment-865868419, have you `make` installed?

BTW you can use Yazi itself as the nix source, do something like `nix run github:sxyazi/yazi`, https://github.com/sxyazi/yazi/blob/main/flake.nix

**Comment by sudhanv09** [comment]
ah ofcourse. thanks installing make fixed this.
