### ISSUE TITLE
Showcase link in README.md is dead

### ISSUE THREAD

**Issue by Adda0** [sxyazi/yazi#408]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Firefox 120

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

The [link to the showcase](https://yazi-rs.github.io/showcase) in the project's main `README.md` on GitHub in the [`Documentation`](https://github.com/sxyazi/yazi#documentation) section is dead. I am not sure where should the link point to.

### Expected Behavior

Point to a website with Yazi showcase. Presumably somewhere on [Yazi website](https://yazi-rs.github.io/).

### To Reproduce

Follow the [link to the showcase](https://yazi-rs.github.io/showcase) in the project's main `README.md` on GitHub in the [`Documentation`](https://github.com/sxyazi/yazi#documentation) section.

### Configuration

no config

**Comment by sxyazi** [comment]
Thanks for the report, it should be https://yazi-rs.github.io/features

Fixed in https://github.com/sxyazi/yazi/commit/57c7d20d39fd059fc8e0ffe9f32ebced858280c7
