### ISSUE TITLE
Option to set the selected file

### ISSUE THREAD

**Issue by Rolv-Apneseth** [sxyazi/yazi#412]
### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Basically I would like to be able to set which file is selected when launching `yazi`, like `ranger`'s `--selectfile` flag, which could either be a flag or maybe just by passing the file path directly to `yazi`?

Thank you for developing and maintaining this tool by the way I think it's great.

**Comment by sxyazi** [comment]
I want to know its use case, i.e., "Is your feature request related to a problem?"

This relates to how to implement it, such as simply selecting them or selecting them and entering "multi-select mode (`v` key)"

**Comment by Rolv-Apneseth** [comment]
Ah sorry, yes the use case would be for using this for a `neovim` plugin. I mean selecting only as in making it the currently focused file. This is so that when opening this program from a file in neovim, it will start focused on that file.
