### ISSUE TITLE
issue installing head version of yazi on macos

### ISSUE THREAD

**Issue by bassamsdata** [sxyazi/yazi#415]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

kitty 0.31.0

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

i'm encountering difficulties installing the head version of yazi on macos venture 13.6.1. i had successfully installed the head version about a month ago, but the current attempt is yielding an error related to cargo, stating that it's referring to a non-existent directory.

steps taken:
uninstalled the previous head version.
attempted to reinstall, but the issue persists.

error message:
```sh
==> cargo install --path=app
Last 15 lines from /Users/bassam/Library/Logs/Homebrew/yazi/01.cargo:
2023-12-01 03:53:58 +0000

cargo
install
--locked
--root=/usr/local/Cellar/yazi/HEAD-d549831
--path=app

error: `/private/tmp/yazi-20231130-3501-gu5u6c/app` is not a directory. --path must point to a directory containing a Cargo.toml file.

```

additional notes:
i understand that head versions can be unstable, and i apologize for opening this issue. the features i see are compelling, and i would like to explore them at my own pace. this is not a high-priority matter.

thank you for your understanding.

### Expected Behavior

installing HEAD successfully

### To Reproduce

`brew install yazi --HEAD`

**Comment by sxyazi** [comment]
Thanks for the report, the Yazi build script in Homebrew hasn't been updated. I've created a PR to fix it. https://github.com/Homebrew/homebrew-core/pull/156077

For now you can also build Yazi using Cargo as per https://yazi-rs.github.io/docs/installation#build-from-source. Thank you for your interest in the new features of Yazi 😊

**Comment by bassamsdata** [comment]
thank you for them prompt response and resolution, really appreciated!
