### ISSUE TITLE
Image preview does not work on Windows in wezterm

### ISSUE THREAD

**Issue by kardusenor** [sxyazi/yazi#42]

**Comment by sxyazi** [comment]
Are you running on WSL?

**Comment by kardusenor** [comment]
> Are you running on WSL?

Yes

**Comment by sxyazi** [comment]
I'm not familiar with Windows and don't have a Windows machine at the time, I might install a Windows VM sometime to investigate it :(

**Comment by sxyazi** [comment]
Update: 
<img width="608" alt="image" src="https://github.com/sxyazi/yazi/assets/17523360/3b81f14d-d6fa-4984-a246-db7be68bc302">
