### ISSUE TITLE
Shell Completion

### ISSUE THREAD

**Issue by MinaMatta98** [sxyazi/yazi#420]
### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Hello,

Could you support shell completion in the same way that perhaps https://github.com/gokcehan/lf does?

This can be incredibly useful, especially if you're also capable of aliasing $1 to $f or similar, such that you can run really quick commands from the tui.

Btw, thank you for this project. This is the best terminal file manager I have ever seen. I though that lf-go was, but this takes the cake.

**Comment by sxyazi** [comment]
I'm interested in this feature, but I'm not an lf user, could you please describe what kind of effect you want to achieve? It would be great if you could provide a GIF about it.

BTW, the latest main branch has been supporting "path completion":

https://github.com/sxyazi/yazi/assets/17523360/e4af2f37-5996-469a-8c2e-2507069adb38

**Comment by MinaMatta98** [comment]
Hello,

No, these are just standard shell commands. They seem different as I have downloaded additional binaries.

Basically, if you use zsh, anything you can <Tab> complete on would preferably be autocompleted.

**Comment by sxyazi** [comment]
Added to the [Feature Requests](https://github.com/sxyazi/yazi/issues/51), closing this issue in favor of that list.
