### ISSUE TITLE
Open File/s / Dir with the same key

### ISSUE THREAD

**Issue by MinaMatta98** [sxyazi/yazi#422]
### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Hello,

Is it possible to incorporate an alteration to the following line:
```toml
	{ on = [ "l" ], exec = [ "enter", "escape --visual --select" ], desc = "Enter the child directory" },
```
Such that if "$1" is a folder:

```toml
exec = [ "enter", "escape --visual --select" ]
```

If it is a file:

```toml
exec = "open"
```

This would allow you to use l to open files and disregard the need for <Enter>, which really improves productivity and feel.

**Comment by sxyazi** [comment]
See https://yazi-rs.github.io/docs/faq#why-cant-open-and-enter-be-a-single-command

When the plugin system is available (should be soon, https://github.com/sxyazi/yazi/pull/401), for users who *truly* don't need it, it will be easy to implement with just a few lines of code.
