### ISSUE TITLE
PDF seek

### ISSUE THREAD

**Issue by MinaMatta98** [sxyazi/yazi#425]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

Alacritty

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Minor Bug:

If you seek in a single page pdf, the preview will go blank and you can no longer recover the first page.

I do not know you have implemented seek, but I have previously done it via the following:

```shell
# Rendering Function
image() {
	if [ -f "$1" ] && [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && command -V ueberzug >/dev/null 2>&1; then
		printf '{"action": "add", "identifier": "PREVIEW", "x": {}, "y": {}, "width": {}, "height": {}, "scaler": "contain", "path": {}}\n' "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$FIFO_UEBERZUG"
	else
		mediainfo "$6"
	fi
}

# Decrease Page Number
decrease() {

case "$(file --dereference --brief --mime-type -- "$1")" in
	*/pdf)
	CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"
		Max=$(pdfinfo "$f" | awk '/^Pages:/ {print $2}')
		if [ $F -le 1 ]
		then
		F=1
		else
		F=$(bc <<<$F-1)
		fi
		if [ $F -eq $Max ]
		then F=$(bc <<<$Max-1)
		fi
		pdftoppm -jpeg -f "$F" -singlefile "$1" "$CACHE"
		image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
		echo "sleep 100 ; rm -r $CACHE.jpg" | at now
		echo "File=\"$f\"\nF=$F" >! ~/.config/lf/PDF
		;;
esac
}
```

You can likely very easily look for the constraint bounds using: https://docs.rs/pdf/latest/pdf/file/struct.File.html

```rust
let path = std::env::args().nth(1)?;

let pdf = pdf::file::File::new(path); 

let num_pages = pdf.num_pages();
```

### Expected Behavior

You cannot move to the second page if the pdf has 1 page.

### To Reproduce

Seek on a single page pdf

**Comment by sxyazi** [comment]
Should be fixed by https://github.com/sxyazi/yazi/pull/401, let me know if it works for you!
