### ISSUE TITLE
Uneccessary Image Size Coercion

### ISSUE THREAD

**Issue by MinaMatta98** [sxyazi/yazi#427]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

Alacritty

### Yazi version

yazi 0.1.5 (638a360 2023-12-02)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Image previews are coerced to maximal size:

![image](https://github.com/sxyazi/yazi/assets/81748812/c0eac96e-8d72-4a55-86aa-9ebe4ee2e1a9) 

### Expected Behavior

This should instead be (as an example for the calculations):
```rs
use image::image_dimensions;

// Use this to maintain image ratio after using ffmpeg/poppler/etc
// Avoid heap allocation of PathBuff since no path modification is needed
fn image_preview(image_path: std::path::Path) {
   
   // Note, you should not load the image into memory, but instead extract the metadata with:
    let (width, height): (u32, u32) = image_dimensions(image_path)
    let image_ratio = width / height;

    let comparitive_width_ratio = width / window.width;

    let comparitive_height_ratio = height / window.height;

    // Route for height being the dictating factor, such that image should be scaled with accordance to
    // image_height
  let (width, height) =
   if std::cmp::min(comparitive_width_ratio, comparitive_height_ratio) == comparitive_width_ratio {
        (image_ratio * window.height, window.height)

        // Use these values for $FIFO_UEBERZUG
        
    } 
    // Route for width being the dictating factor 
    else if std::cmp::min(comparitive_width_ratio, comparitive_height_ratio)
        == comparitive_height_ratio
    {
        (window.width, width / image_ratio)

        // Use these values for $FIFO_UEBERZUG
    } else {
    
    // Use standard width or height
    (width, height)
    }
}
```

Note that you can retrieve image stats via https://github.com/image-rs/image.

### To Reproduce

Go to any small image and the image will instead be enlarged to match the size of the whole window.

**Comment by sxyazi** [comment]
No, it's not a bug.

You just need to tune the [`max_width` and `max_height`](https://yazi-rs.github.io/docs/configuration/yazi#preview) up as what you want - which will fit your terminal automatically, that's necessary for [pre-caching images](https://yazi-rs.github.io/blog#pre-caching)

**Comment by sxyazi** [comment]
Ah you're right, I reproduced it, it's a really bug.

Sorry for the confusion on this issue. I'll create a PR to fix it shortly.
