### ISSUE TITLE
use yazi in docker can not show image

### ISSUE THREAD

**Issue by soluty** [sxyazi/yazi#431]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

wezterm

### Yazi version

0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

i can run yazi in wezterm and windows that can show image perfect.
but when i run it in docker container,  image cant show,
i dont know it is a bug, or i need a little setup.

### Expected Behavior

can show image when in docker container .

### To Reproduce

run a ubuntu docker container  and use  vcsxrv as  ubuntu's  x server,  then  `docker run -it  ubuntu` enter docker container, and  in
docker container, install  yazi, then look it cant show image.

**Comment by sxyazi** [comment]
This is because Docker connects via SSH, and Yazi cannot detect the terminal type.

I'll add a new configuration option later to allow users to manually specify the image protocol in this situation.

For now, you can use this workaround: 

```bash
alias yazi="WEZTERM_EXECUTABLE=1 yazi"
```

Just tested it works for me within the Docker container:

![CleanShot](https://github.com/sxyazi/yazi/assets/17523360/c3f176b0-e981-4e41-8a13-33eb4efb2a1c)

**Comment by soluty** [comment]
thank you for replying, but it is not work for me,  which yazi do you run , the yazi in windows or  yazi  in docker container?  
is your docker container use wsl2 mode or not? my docker container is not in wsl2 mode.

**Comment by sxyazi** [comment]
> which yazi do you run , the yazi in windows or yazi in docker container?

Yazi in Docker container on macOS, WezTerm version 20230815-112734-b3652256

**Comment by sxyazi** [comment]
Are you connecting to Docker from Windows using `wezterm ssh` (see [Yazi Linux Edition running on WSL](https://yazi-rs.github.io/docs/faq#why-cant-i-preview-files-on-windows))? And use it with `alias yazi="WEZTERM_EXECUTABLE=1 yazi"` if it can work?

**Comment by soluty** [comment]
i have no yazi linux edition running on wsl , my linux edition is running in docker container. and i  connect docker just use docker run -it ubuntu . yazi in my host machine work fine, i just want yazi in docker container also work, can i do this? If can , i can setup a n awesome dev enviroment image  by docker. I dont want use my host machines docker to show image.  
my docker has no xserver in, but it can start x app by  xserver in host machine.

**Comment by sxyazi** [comment]
> i just want yazi in docker container also work, can i do this

Yeah, I think the display modes for Docker and WSL are consistent. I don't have a Windows machine atm. Could you try it out? If it doesn't work, I'll set up a Windows VM to investigate further.

**Comment by soluty** [comment]
how can i connect docker use wezterm ssh ?? do i need more config to do with ssh or i can just run by a line of code, what is your way to connect docker  and use wezterm ssh?

**Comment by sxyazi** [comment]
You need to connect via IP using OpenSSH, it's the same as what is in WSL, see [the link I provided above](https://yazi-rs.github.io/docs/faq/#why-cant-i-preview-files-on-windows).

**Comment by soluty** [comment]
i Do you mean i need start a ssh server in container , and use wezterm ssh to connect docker ? Thank you very much and i will try i later, but i wonder  if i connect it with ssh  but not the way  `docker run -it`, i will have other problems,  such as  clipboard  not easy to share . what ever , i will try it.

**Comment by soluty** [comment]
oh.. my container now has no sshd, and i need some time to solve this.

**Comment by baitian752** [comment]
I found `imgcat` works when directly attaching to a container in `WezTerm`:

![image](https://github.com/sxyazi/yazi/assets/28034106/a49c2ba6-db7b-440c-93d3-7a51fa06916b)

**Comment by soluty** [comment]
> I found `imgcat` works when directly attaching to a container in `WezTerm`:
> 
> ![image](https://private-user-images.githubusercontent.com/28034106/289735825-a49c2ba6-db7b-440c-93d3-7a51fa06916b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTM2MTMsIm5iZiI6MTcwMjM1MzMxMywicGF0aCI6Ii8yODAzNDEwNi8yODk3MzU4MjUtYTQ5YzJiYTYtZGI3Yi00NDBjLTkzZDMtN2E1MWZhMDY5MTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAzNTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMjMzYmNlMmUxNTgzN2MwNjZjZGZlYWJiZGY3MWU3OTYyOGM5MmM0NDdlNWQxNmY0NGNmMTdmZTk4ZDdlNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AQqHAGWh-98d2iRxYntnINgL7xYD3AoaMaJ_eawSb_E)

thankyou very much, i ll try to use imgcat.  my container has no imgcat now..
bash: imgcat：未找到命令
