### ISSUE TITLE
Past symlink as symlink

### ISSUE THREAD

**Issue by einhander** [sxyazi/yazi#433]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.31.0

### Yazi version

yazi 0.1.5 (1d1a512 2023-12-06)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Copy-paste directory with symlinks inside it results in paste directory with files

### Expected Behavior

Copy and paste directory with symlinks

### To Reproduce

copy directory with symlinks inside it, paste it

### Configuration

no config

**Comment by sxyazi** [comment]
Done by https://github.com/sxyazi/yazi/pull/436
