### ISSUE TITLE
Open file with same button with enter directory

### ISSUE THREAD

**Issue by og900aero** [sxyazi/yazi#438]
### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Enter the children's directory and the file opening key (Right arrow) should also be used so that if you are standing on a file, it will be opened and standing directory, then enter the directory (aka lf file manager, vifm etc)

**Comment by sxyazi** [comment]
See https://yazi-rs.github.io/docs/faq#why-cant-open-and-enter-be-a-single-command

When the plugin system is available (should be soon, https://github.com/sxyazi/yazi/pull/401), for users who *truly* don't need it, it will be easy to implement with just a few lines of code.

**Comment by sxyazi** [comment]
We've supported it now, see this tip https://yazi-rs.github.io/docs/tips/#smart-enter-enter-for-directory-open-for-file.

Note that Yazi main branch is currently required.
