### ISSUE TITLE
Yazi not previewing images with --chooser-file flag

### ISSUE THREAD

**Issue by Brixy** [sxyazi/yazi#441]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot version: 1.16.2 -pgo +ime +graphemes -assertions

### Yazi version

yazi 0.1.5 (1d1a512 2023-12-05)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Hi again!

[Aerc](https://sr.ht/~rjarry/aerc/) has a `file-picker-cmd`, and I switched from fzf to yazi which works very well.

One thing came to my attention:

With

```
# aerc.conf
[compose]
file-picker-cmd = yazi --chooser-file "%f"
```

yazi does not preview images.

It's not crucial. Just wanted to give a hint because I don't if it is a yazi issue.

### Expected Behavior

Yazi should preview images with or without the `--chooser-file` flag.

### To Reproduce

Within aerc:

- `:compose` (or key binding)
- Go to main writing area, e.g. with `Ctrl + n`
- `:wp` (e.g. for helix or vim)
- `:attach -m<enter>` (or key binding)

**Comment by sxyazi** [comment]
When I start Yazi with `yazi --chooser-file /tmp/foo`, my image preview works fine.

I want to know if it works for you in Aerc without including `--chooser-file`?

**Comment by sxyazi** [comment]
When I followed your steps and did the final one I got:

```
stat -m: no such file or directory
```

**Comment by Brixy** [comment]
> When I followed your steps and did the final one I got:
> 
> ```
> stat -m: no such file or directory
> ```

Thanks! I cannot reproduce this but did some research

- Switched to original aerc config files and just set `file-picker-cmd`.
- `:attach -m` was added in aerc 0.14.0 (2023-01-04)
- `rg "stat .*"`: only slightly related in `commands/compose/attach.go`:
	```
	log.Errorf("failed to stat file: %v", err)
	```
- could not find anything relevant for `stat -m` asking the search engines.

Not being familiar with rust the only idea I have for the original issue: Maybe some `$TMP` variable is overwritten by aerc?! Aerc uses `/tmp/aerc-…` files.

**Comment by sxyazi** [comment]
Thank you for the pointer. I have reproduced it after upgrading `aerc`.

Unfortunately, Yazi identified and used the graphics protocol correctly, but aerc's built-in terminal emulator failed to interpret them, resulting in the images not being displayed on the terminal.

And I found this, [Tcell with Sixel image format](https://lists.sr.ht/~rjarry/aerc-discuss/%3CDBAP193MB09386748AE6727572960F01EDD039%40DBAP193MB0938.EURP193.PROD.OUTLOOK.COM%3E#%3CCOAP6TV3FTGS.GMFJYZSEXWY0@ramon%3E). It seems that `aerc` doesn't support any graphic protocols currently.

![](https://github.com/sxyazi/yazi/assets/17523360/bad44ccb-46a6-43ab-96bb-e7afa8b505a2)

**Comment by Brixy** [comment]
Ah interesting. Thank you so much for investigating this. I did not know that yazi kind of 'inherits' this.

So this is a pure aerc issue. If you agree I’ll close this issue and provide news here when the aerc issue is solved.

Yazi as a file picker within aerc is fantastic anyways.

---

By the way: As a temporary solution for previewing images in aerc I use this setting within the `[filter]` section—but just didn’t remember:

```
image/* = chafa --format symbols -
```

**Comment by sxyazi** [comment]
I will [add a new config option to Yazi](https://github.com/sxyazi/yazi/issues/431#issuecomment-1846285652) to allow users to manually specify the graphics mode to use, with chafa as a fallback in this scenario.
