### ISSUE TITLE
Copy path not working

### ISSUE THREAD

**Issue by baitian752** [sxyazi/yazi#444]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

WezTerm 20230712-072601-f4abf8fd

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Not tried, and I'll explain why below

### Describe the bug

***In my case, yazi is running on linux server, not X11!***

My system is windows, and I use wezterm ssh connect to my linux server, then run yazi, the copy path reletive commands not working.

Also, I have tested run yazi in zellij, it's not working either.

### Expected Behavior

The path copied to my system clipboard.

### To Reproduce

As my use scenario.

### Anything else?

I think the copy path feature could add OSC-52 support, then my use scenario (via ssh) maybe OK (as some terminals and zellij support OSC-52).

**Comment by sxyazi** [comment]
Yazi not only needs to write content to the clipboard, but also needs to read content from it (used by `p` in Vi mode), both achievable through `OSC 52`. While there are no issues with the former, I'm unsure about how to implement the latter. 

Currently, Yazi uses `crossterm`, which seems to disallow creating custom event handlers and reading and parsing specific `OSC 52 ?` responses from the terminal.

I'm looking for a way to accomplish this, if anyone knows, please let me know!

**Comment by baitian752** [comment]
I have tested #447 , which works.

Thanks for your work :)
