### ISSUE TITLE
Parse dircolors / LS_COLORS for file name colors

### ISSUE THREAD

**Issue by cd-a** [sxyazi/yazi#450]
### Is your feature request related to a problem? Please describe

It's an amazing file manager, however it's hard to navigate around since almost all the files look the same.

I know, there are colours that can be set for mime types in the theme.toml file, but why not use something that most users already have?

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Parse the `LS_COLORS` env var, or if not present read the dircolors file. It makes the app look exactly like the terminal, and users feel right at home.

Like how vifm is doing it

**Comment by sxyazi** [comment]
Sorry, I'm afraid I might not add it, for the following reasons:

- It would introduce new cross-platform issues - I'm unsure if Windows also has dircolors/LS_COLORS, or similar equivalents, and whether they are customary behavior.
- This also brings in more external dependencies, requiring users not only to configure Yazi itself but also ensure these external dependencies work properly (personally, I've never configured `LS_COLORS`).
- It would fragment Yazi's existing comprehensive theme system, requiring not just the release of `theme.toml` but also prompting users to configure `LS_COLORS` somewhere when creating a theme for Yazi.
- Its functionality is limited - afaik, it can only render colors based on filename/extension, not supporting mimetype, while Yazi supports both.

Maybe it could be implemented as a Lua plugin by the community once the [Yazi plugin system](https://github.com/sxyazi/yazi/pull/401) is ready. Yazi allows for the majority of the UI to be rewritten via Lua.

**Comment by cd-a** [comment]
Ok, I see your point. Thanks for your detailed reasoning!
