### ISSUE TITLE
How to cancel the copy or cut operation?

### ISSUE THREAD

**Issue by 396458015** [sxyazi/yazi#453]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Alacritty

### Yazi version

0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

After copying or cutting the selected file, a yellow or red flag appears on the file. So how to cancel this copy or cut operation (i.e., remove the yellow or red flag in front of the file).
Just as the space bar selects a file, press the space bar again to deselect it. No shortcut to uncopy or uncut found. Also, there is no related process in the task manager. To cancel copy and cut, I can only exit yazi and enter again.

### Expected Behavior

Whether the copy and paste shortcut keys can have the function of toggle.

### To Reproduce

Open Yazi in terminal windows, select the file and enter the shortcut key for copying or cutting it.

**Comment by sxyazi** [comment]
There's an RFC https://github.com/sxyazi/yazi/issues/319 that includes this feature request, and I will assess its feasibility after [Yazi's plugin system](https://github.com/sxyazi/yazi/pull/401) is done.
