### ISSUE TITLE
Config files doesn't loading

### ISSUE THREAD

**Issue by asim215** [sxyazi/yazi#46]
Hello. Config files don't load by default. 

I download config files from preset and put them into `~/.config/yazi/`. I change to show hidden files to true `show_hidden  = true`. But after restart application they don't load. So my home folder doesn't show hidden files with `.`. Where can be problem?

Also in config, how I can change `bat` to use `--theme="gruvbox-light"`? I write `syntect_theme = "gruvbox-light"` in `theme.toml` but it doesn't seems to work.

**Comment by sxyazi** [comment]
> after restart application they don't load
It seems a bug, I'll fix it now!

> how I can change bat to use --theme="gruvbox-light"?

Yazi uses the built-in highlighter that's `syntect`, which is also the engine behind the `bat`, but not `bat` be used directly, so it can use the same theme that is available in `bat`. You can download the `gruvbox theme` file from https://github.com/subnut/gruvbox-tmTheme, and config the `syntect_theme` as its path.
