### ISSUE TITLE
copy/cut/pastle file  across multiple yazi window

### ISSUE THREAD

**Issue by fastfading** [sxyazi/yazi#463]
### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

copy/cut/pastle file  across multiple yazi window
for example 
I copy a file in   yazi window 1
then I wish to pastle that file in yazi window 2   which is in another path.

**Comment by fastfading** [comment]
this is supported in https://github.com/gokcehan/lf

**Comment by sxyazi** [comment]
There's an RFC that covers this feature request, https://github.com/sxyazi/yazi/issues/319, but there are still some implementation barriers at the moment.

Please feel free to leave your thoughts on that RFC, and I will evaluate its feasibility soon. Closing this issue in favor of that RFC, discussing them in one place.
