### ISSUE TITLE
Image not display on ubuntu over SSH

### ISSUE THREAD

**Issue by fastfading** [sxyazi/yazi#465]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

iTerm2 3.4.15

### Yazi version

yazi 0.15

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

login server is ubuntu 22.04
client is mac iterm2 
ssh  ubuntu@xxx.xxx.xx.xx

I try to preview the image with iterm2 , nothing shows

env | grep TERM
LC_TERMINAL_VERSION=3.4.15
LC_TERMINAL=iTerm2
TERM=xterm-256color

env | grep XDG_SESSION_TYPE
XDG_SESSION_TYPE=tty

I tried install ueberzugpp  
only a image with big color block is showed.   

how to solve that 

### Expected Behavior

a image with high resolution is showed

### To Reproduce

ssh  ubuntu@xxx.xxx.xx.xx 
yazi 
preview image  *.png *.jpg

**Comment by fastfading** [comment]
<img width="263" alt="image" src="https://github.com/sxyazi/yazi/assets/8351732/e62cbd52-f33a-4cc0-9b4b-475d9c69a5ca">

**Comment by sxyazi** [comment]
Try:

```bash
TERM_PROGRAM="iTerm.app" yazi
```

if it works.

I will add a new option to allow the user to configure the graphics protocol manually.

**Comment by fastfading** [comment]
yes, it works.   please add the option in

**Comment by sxyazi** [comment]
Hi I made a PR to fix this, let me know if it works for you, https://github.com/sxyazi/yazi/pull/585
