### ISSUE TITLE
yazi not able to follow "default" symlinks created by Windows

### ISSUE THREAD

**Issue by RioNight** [sxyazi/yazi#471]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Wezterm

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Not tried, and I'll explain why below

### Describe the bug

I'm using the git bash shell on Windows in Wezterm.
symlinks on created by git bash's `ln` are able to be followed, i.e., I can press the letter `l` to enter into the symlink target.

What doesn't work is pressing `l` to enter into the default symlinks created by Windows which appear in the user's home directory. Windows appears to create a set of default symlinks, such as `Recent` in the home directory, which maps to `/c/<user>/KhanH/AppData/Roaming/Microsoft/Windows/Recent` (this is a Git Bash path corresponding to `C:\Users\<user>\AppData\Roaming\Microsoft\Windows\Recent`). Instead, nothing occurs, (i.e., there is no crash on any error message).

`file Recent` outputs: `Recent: symbolic link to /c/Users/<user>/AppData/Roaming/Microsoft/Windows/Recent`. I am using git bash's `file` command.
`cd Recent` works as well.

Note: To create a symlink with git bash's `ln`, you need to enable Developer Mode on Windows and set this in your `~/.bashrc`:
`export MSYS=winsymlinks:nativestrict`.

### Expected Behavior

I would expect `l` to follow the Windows default symlinks.

### To Reproduce

1. On Windows, `scoop install git wezterm yazi ...`
2. In the `~/.wezterm.lua` file, set: `config.default_prog = { 'c:\\users\\<user>\\scoop\\apps\\git\\current\\bin\\bash.exe -i -l' }`. Check [here](https://wezfurlong.org/wezterm/config/files.html) for more details on the Wezterm config.
3. In Wezterm + Git Bash, `cd` to `~`
4. Run `yazi`.
5. Try to press `l` on any of the Windows default symlink folders. So, `Recent`,, "Start Menu", "Application Data", etc.

### Configuration

no config

`~/.wezterm.lua`:
```lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
config.default_prog = { 'c:\\users\\<user>\\scoop\\apps\\git\\current\\bin\\bash.exe -i -l' }

-- and finally, return the configuration to wezterm
return config

```

**Comment by sxyazi** [comment]
Is there anyone familiar with Windows and would like to take a look at this issue?

**Comment by RioNight** [comment]
#527 doesn't seem to work on these files created by Windows. It works on normal symlinks created by pwsh like `New-Item -Path .\pwsh-symlink -ItemType SymbolicLink -Value .\testdir\`.

The mimetype of the `pwsh-symlink` created with the above command is `inode/directory`.

The mimetype of a Windows directory "default" symlink directory is also `inode/directory`.

`~/Recent` is an example of a Windows "default" symlink directory. You have it in the image you provided.

![image](https://github.com/sxyazi/yazi/assets/58403689/241a9ae3-a055-48c2-8cf8-903530eee9fb)

**Comment by RioNight** [comment]
By the way, you can create symlinks in Windows without admin privileges by enabling Developer Mode in Windows Settings.

**Comment by sxyazi** [comment]
> The mimetype of the pwsh-symlink created with the above command is inode/directory.

Hmm weird, why it's `inode/directory` not `inode/symlink`? Are there any docs about the "default" symlink on Windows? I'm not quite familiar with it...

**Comment by sxyazi** [comment]
Let me merge that PR first

**Comment by RioNight** [comment]
I think it might be a permission error.

One thing about these WIndows folders is that to view them in the File Explorer you need to enable something.
To configure File Explorer click on the three dots at the top, View, or Options. Somehow you should reach a popup window in which you can enable viewing of Hidden Files, File Extensions / Types, and Protected Operating System Files.
Recent is only shown when you enable viewing of Protected OS Files.

Also, `cmd`'s `dir`, and `pwsh`'s `get-childitem` and `ls` cannot list the files in Recent. They give a permission denied message.
However, `bash`'s `ls` can list these files.

`fx` (felix) and `lf` both can't view it either. Here is what is shown in `lf`:
![image](https://github.com/sxyazi/yazi/assets/58403689/266ccd21-2415-4ccb-89f1-5f7e7aea17e1)

**Comment by RioNight** [comment]
I don't know about the mime-type though. This is bash:
![image](https://github.com/sxyazi/yazi/assets/58403689/5df06d34-7fcf-400c-80a3-816da7543758)

**Comment by RioNight** [comment]
![image](https://github.com/sxyazi/yazi/assets/58403689/de1fd248-fe90-4088-b6de-1f8ef3f01af7)

**Comment by sxyazi** [comment]
It seems there's not much Yazi can do; it's just a weird permission problem on Windows - In fact, Yazi just simply calls Rust's [`fs::read_dir()`](https://doc.rust-lang.org/std/fs/fn.read_dir.html) to read the directory list, I can't think of anything that could be the issue with Yazi.

Closing as not Yazi.

**Comment by RioNight** [comment]
I see. Could something be added on the right pane to show what's happening? Something like "permission denied". Right now yazi shows no files and treats it like an empty directory.
