### ISSUE TITLE
Aliases don't work in yazi

### ISSUE THREAD

**Issue by flpFlan** [sxyazi/yazi#472]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Kitty 0.31.0

### Yazi version

yazi 0.1.5 (82bab0f 2023-12-26)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Here's a snippet from my zshrc:
```zsh
alias astronvim="NVIM_APPNAME=astronvim neovide"
alias vim=astronvim
export EDITOR=astronvim
```
When I try to open a text file with yazi, it reports an error saying `command not found: astronvim`, then I try to open it in yazi's shell command and it doesn't work either.

BTW, shell functions also do not work.

### Expected Behavior

My nvim opens correctly with the environment variable and is used to edit the corresponding files

### To Reproduce

Set an alias for your nvim/vim and set $EDITOR to that alias, then try to open a text file with yazi

**Comment by sxyazi** [comment]
Please do an `echo $EDITOR` and `sh -c 'echo $EDITOR'` and paste it here.

And do a `sh -c "$EDITOR your-file-path"` to see if the file opens as expected; this is the command executed behind Yazi.

**Comment by SolitudeSF** [comment]
`EDITOR` shouldnt be an alias. it should be a path to a binary or a binary name in PATH.

**Comment by flpFlan** [comment]
Not being able to use alias has really caused me some inconvenience, as I have both an `astronvim` and an `lunarvim` on my computer.

**Comment by flpFlan** [comment]
> But then ran into another problem that, when I launch yazi in my terminal, everything works just fine, but if I use a shortcut key to launch it, it report `"Permission denied"` when I try to open a text file.
> 
This problem has been solved since I move the environment variable definitions to hyprland's config file.

**Comment by flpFlan** [comment]
Ok I replaced the aliases with extra scripts and now this issue can be closed!

**Comment by sxyazi** [comment]
Nice to hear your problem is resolved!

BTW, "Permission denied" is because the command corresponding to `$EDITOR` cannot be found or executed, it's usually because it's not in the `$PATH`. e.g. `export EDITOR=not-exists-command` will result in the same error.
