### ISSUE TITLE
Unable to scroll preview

### ISSUE THREAD

**Issue by DreamMaoMao** [sxyazi/yazi#478]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

konsole 23.08.4

### Yazi version

yazi 0.1.5 (63f81f6 2024-01-03)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Preview scrolling can only be triggered once, and it cannot be triggered again.

https://github.com/sxyazi/yazi/assets/30348075/6e66f80d-a5cf-4d83-916f-a4b733196620

### To Reproduce

1.open yazi in konsole
2.select a file
3.toggle preview Peek down

### Configuration

keymap config:
![image](https://github.com/sxyazi/yazi/assets/30348075/b6bf5659-4df2-4bef-bfef-83a02b6bb118)

**Comment by DreamMaoMao** [comment]
when Rollback version  to Release 0.15.  This problem will not exist. It just appears in the latest source code.

**Comment by manfred3000** [comment]
https://github.com/sxyazi/yazi/issues/461

**Comment by DreamMaoMao** [comment]
it work,thanks.
