### ISSUE TITLE
Kitty image previews are not scaled 

### ISSUE THREAD

**Issue by dmtrKovalenko** [sxyazi/yazi#479]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

kitty 0.31.0 

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Terminal images previews in kitty does not scale and are not usable

<img width="1739" alt="image" src="https://github.com/sxyazi/yazi/assets/16926049/568a512b-6096-49fa-b94c-fe57564affe5">

### Expected Behavior

This is how fzf with the jcorrect preview working 
```
  EXTERNAL_COLUMNS=$COLUMNS \
  fzf $argv \
  --preview='kitten icat --clear --transfer-mode=memory --scale-up --place="$COLUMNS"x"$LINES"@(math $EXTERNAL_COLUMNS-$COLUMNS)x0 --align center --stdin=no {} > /dev/tty' \
  --preview-window "right,50%,border-left"
```

<img width="1739" alt="image" src="https://github.com/sxyazi/yazi/assets/16926049/6167e340-8c0e-46ec-b381-478b8a7c2911">

### To Reproduce

Open any folder containing images using yazi in kitty

### Configuration

This is reproducible on totally default configuration 

### Anything else?

I assume that there might be a missing `--scale-up` argument when getting a preview from the kitty. I can try to check the code and see if I can fix this issue once will get a green light from maintainers.

**Comment by sxyazi** [comment]
Hi, you need to tune the [`max_width` and `max_height`](https://yazi-rs.github.io/docs/configuration/yazi#preview) up as what you want - which will fit your terminal automatically, that's necessary for [pre-caching images](https://yazi-rs.github.io/blog#pre-caching)

**Comment by dmtrKovalenko** [comment]
<img width="3120" alt="image" src="https://github.com/sxyazi/yazi/assets/16926049/ac66f98b-2466-47ad-b8b6-88d8eb012595">

Thank you, @sxyazi for a quick answer, I am sorry for somehow missing this. I did what you said and set both of them to 4000. I also set `image_alloc` to 0 and image_bound to [0,0] (all unlimited) and still seeing this 

<img width="3120" alt="image" src="https://github.com/sxyazi/yazi/assets/16926049/f8ee60ee-dc59-4f77-b3f5-32bfbf1e431f">

**Comment by sxyazi** [comment]
Did you do a `yazi --clear-cache` after setting `max_width` and `max_height` inside `[preview]` in your `~/.config/yazi/yazi.toml`?

**Comment by dmtrKovalenko** [comment]
Yes exactly

**Comment by sxyazi** [comment]
Oh, sorry, I seem to have misunderstood your intention.

Are you looking to enlarge an image that is initially smaller than your terminal window and to fill in it, rather than having an image larger than the terminal window to downscale to the terminal size? 

If so currently, this is only can be implemented by the custom previewer - I'm not sure if it makes sense since enlarging a small image usually results in blurriness. However, I'm willing to discuss it and explore any possible way to impl it. Let me know your thoughts.

**Comment by Reledia** [comment]
I'm sorry to come back to a closed issue, but I feel this is a feature that could be interesting in some cases.
I'm not well versed in Rust, but I looked at the Image implementation, especially at the downscale method: to me it seems like it could already work as a upscale method too if a (to add) flag can be passed to skip the fast path check and the check before the resize.

Pseudo-code (idk if its correct Rust):
```rust
// Fast path.
if img.width() <= w && img.height() <= h && orientation <= 1 && !upscale {
	return Ok(img);
}

tokio::task::spawn_blocking(move || {
	if (img.width() > w || img.height() > h) || upscale  {
		img = img.resize(w, h, Self::filter())
	}
	Ok(Self::rotate(img, orientation))
})
```
