### ISSUE TITLE
Previews of hidden files not shown with `show_hidden = false`

### ISSUE THREAD

**Issue by Brixy** [sxyazi/yazi#480]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot version: 1.16.2

### Yazi version

yazi 0.1.5 (9bdbc55 2024-01-05)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

With

```
# yazi.toml
[manager]
show_hidden = false
```

contents of hidden files are not shown after pressing `.`.

Yet, the contents of hidden folders are shown in the preview pane.

With `show_hidden = true` previews work as expected.

I think this issue is pretty because I’ve never realized it before.

### Expected Behavior

Content of hidden files should be shown when hovered in the preview pane.

### To Reproduce

- Use config posted above.
- Press `.` in yazi.
- Hover a hidden file.

### Anything else?

Let me repeat what I’ve written several times: All recent additions to yazi are excellent: Thank you very much.

**Comment by sxyazi** [comment]
Nice catch! I'll investigate it.

BTW I also reproduced this issue in the Yazi v0.1.5 release version as well, it seems to have been around for a while.

**Comment by sxyazi** [comment]
Fixed in https://github.com/sxyazi/yazi/commit/b229c8a5e32a6c667c46448020b43bbd2c2d9097, thanks for the report!
