### ISSUE TITLE
For vertical images, the preview image is rotated

### ISSUE THREAD

**Issue by og900aero** [sxyazi/yazi#486]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

alacritty 0.11.0

### Yazi version

yazi 0.1.5 (63f81f6 2024-01-04)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

If I take a photo in a vertical position and look at it under yazi based on the preview image, it is turned.

![screenshot_1704576512](https://github.com/sxyazi/yazi/assets/49487376/18b5743b-ea62-4fc7-ab9e-2923775dbe19)

### Expected Behavior

Show the preview image properly. Exiftool can be used to read whether it is necessary to rotate or not:

If I take photos horizontally, the Exiftool show:
Orientation : Horizontal (normal)

If I photograph vertically, the Exiftool show:
Orientation : Rotate 90 CW

### To Reproduce

Take a photo in a vertical position and look at it under yazi based on the preview image, it will be turned.

**Comment by sxyazi** [comment]
Could you please send me an image that rotated?

**Comment by og900aero** [comment]
> Could you please send me an image that rotated?

I sent to the sxyazi+gh@gmail.com.

**Comment by sxyazi** [comment]
Hi, I made a PR to support it, https://github.com/sxyazi/yazi/pull/488, please try it out to see if it works.

**Comment by sxyazi** [comment]
Oh forgot to mention, you need to do a `yazi --clear-cache` to clear the cache to take effect.

**Comment by og900aero** [comment]
Not working for me. I try the following steps in terminal:

1. cargo install --locked --git https://github.com/sxyazi/yazi.git
2. yazi -V -> yazi 0.1.5 (1908ff2 2024-01-07)
3. yazi --clear-cache
4. yazi
The problem is the same before yazi 0.1.5 (1908ff2 2024-01-07)

**Comment by sxyazi** [comment]
You need to [use the code from that PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally) instead of the main branch, then `cargo build --release`, see https://yazi-rs.github.io/docs/installation#build-from-source

**Comment by og900aero** [comment]
Uhh, it is high for me.

1. git clone https://github.com/sxyazi/yazi.git
2. cd yazi
3. git fetch origin pull/488/head:pr-2e27aed0
4. git switch pr-2e27aed0
5. cargo build --release

Is it right?

**Comment by sxyazi** [comment]
Ah sorry about that, I'll merge the PR into the main branch now - It's been tested on my side and works fine.

So after the merge, you can simply do `cargo install --locked --git https://github.com/sxyazi/yazi.git` without any additional steps.

Of course, if you encounter any issues after that, feel free to reply to this issue, and I'll continue fixing it.

**Comment by og900aero** [comment]
I type in terminal the:
1. cargo install --locked --git https://github.com/sxyazi/yazi.git
2. yazi --clear-cache
3. yazi

But not working. The picture is not good.
yazi -V  ->  yazi 0.1.5 (085f7e3 2024-01-08)

**Comment by sxyazi** [comment]
Weird, let's first confirm if it worked for the photo you sent me earlier - only used it for testing. If it doesn't work, what does it look like? Could you take a screenshot?

**Comment by og900aero** [comment]
Umm. It's really weird. I downloaded picture, that sent to you. That is show corectly. Then I navigate to the Norway folder to the original picture, and now show corectly and other pictures too. I dont understand. But it does not matter. It works well :)

**Comment by og900aero** [comment]
Don't be upset that I'm still writing on the ticket here, but could you also check if the image is rotated 180 degrees?
In this case, the exiftool program shows the following:
Orientation: Mirror vertical

**Comment by sxyazi** [comment]
Please file an issue with your problematic image

**Comment by og900aero** [comment]
> Please file an issue with your problematic image

I sent u by email. Thank u so much!

**Comment by sxyazi** [comment]
@og900aero  Fixed in https://github.com/sxyazi/yazi/commit/82359ef29012d1028009410e4239c161320ac452

**Comment by og900aero** [comment]
> @og900aero Fixed in [82359ef](https://github.com/sxyazi/yazi/commit/82359ef29012d1028009410e4239c161320ac452)

Thx, working fine!
