### ISSUE TITLE
some problem about Image preview within tmux

### ISSUE THREAD

**Issue by KeepSmile1** [sxyazi/yazi#493]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

bash

### Yazi version

yazi 0.1.5 (3fcc201 2024-01-05)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

To enable Yazi's image preview to work correctly in tmux, add the following 3 options to your tmux.conf:

set -g allow-passthrough on

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

but when I follow this step and restart tmux, I reported an error when opening tmux.
.tmux.conf:5: invalid option: allow-passthrough

### Expected Behavior

null

### To Reproduce

modify ~/.tmux.conf.

**Comment by KeepSmile1** [comment]
In normal mode, the new configuration can be seen, but there is no change in tmux and an error is also reported

**Comment by sxyazi** [comment]
What's your tmux version? And please paste your full `~/.tmux.conf` content here

**Comment by KeepSmile1** [comment]
this is my ~/.tmux.conf:
set -g default-terminal "xterm-256color"                                                                                                                               
 #set -g default-terminal "screen-256color"
 set -g renumber-windows

#set -g allow-passthrough on
 set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
run-shell /home/tt/tmux_config/tmux-onedark-theme.tmux

and tmux -V is tmux 3.0a

**Comment by sxyazi** [comment]
tmux 3.0a does not support passthrough mode, which is an option introduced in tmux 3.3, see https://raw.githubusercontent.com/tmux/tmux/3.3/CHANGES:

```
CHANGES FROM 3.2a TO 3.3
...
* Add an option (default off) to control the passthrough escape sequence.
```

Please upgrade your tmux to the latest version.
