### ISSUE TITLE
Binary cache for nix builds

### ISSUE THREAD

**Issue by musjj** [sxyazi/yazi#495]
### Is your feature request related to a problem? Please describe

This project provides a flake for nix users, but without a binary cache users will always have to build locally on every update. This is is especially annoying since the build time tends to be pretty long on low-power machines.

### Will you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Use cachix as a binary cache. It's free for open-source projects, with a 5GB quota.

There's instructions here for setting up a GitHub CI: https://nix.dev/tutorials/nixos/continuous-integration-github-actions

I'd like to help with this, but the process requires privileges for setting up the secrets.

### Describe alternatives you've considered

The alternative is to build the flake locally every time.

### Additional context

Some projects that provides cachix support, for reference:

- https://github.com/hyprwm/Hyprland
- https://github.com/helix-editor/helix
- https://github.com/nix-community/neovim-nightly-overlay
- https://github.com/Aylur/ags

**Comment by PhotonQuantum** [comment]
Thumbs up for this feature request! Yazi currently contributes the most to my Nix rebuild time. Any update on this? @sxyazi 
Also, it would be better if we could also have a build cache for darwin-aarch64: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by sxyazi** [comment]
Sounds good to me, I'd appreciate a PR for this 👍

**Comment by musjj** [comment]
Made a PR: https://github.com/sxyazi/yazi/pull/740
But you need to still have someone with the appropriate privileges to set up the secrets.

**Comment by musjj** [comment]
@sxyazi 
It looks like that the build failed. I also tested it locally and it also failed, so it's not some kind of GitHub Actions shenanigan.

It seems related to: https://github.com/sxyazi/yazi/pull/306
The install script is expecting completion files in `./yazi-config/completions`, but it's not there. Was the [build script](https://github.com/sxyazi/yazi/blob/main/yazi-boot/build.rs) not triggered or something? Some help would be appreciated.

**Comment by sxyazi** [comment]
Fixed in https://github.com/sxyazi/yazi/pull/745 by @musjj, thanks!

**Comment by musjj** [comment]
The binary cache is now (well, since a few hours ago) fully live at https://yazi.cachix.org! :tada:
