### ISSUE TITLE
Files/folder missing in view when yazi is moved in tiling window manager

### ISSUE THREAD

**Issue by Brixy** [sxyazi/yazi#499]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot version: 1.16.2

### Yazi version

yazi 0.1.5 (c3a8bdc 2024-01-09)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

I use a tiling window manager.

When a window is resized vertically, yazi works as expected.

But when yazi is moved from window 2 to window 1 (see figure below), only files and folder that were visible when yazi was in window 2 are visible in yazi in window 1 and the rest of the vertical space stays blank.

As soon as I press `j` or `k` in yazi the missing files/folders show up.

```
+-----------+ +-----------+
|           | |           |
|           | |     2     |
|           | |           |
|     1     | +-----------+
|           | +-----------+
|           | |           |
|           | |     3     |
|           | |           |
+-----------+ +-----------+
```

Tested in

- river and
- sway.

This is absolutely no problem for me; just wanted to report.

### Expected Behavior

All files and folders should be visible when yazi is moved from window 2 to 1.

### To Reproduce

- Open yazi in window 2 and cd to a folder containing many files/subfolders.
- Move yazi to window 1 using you window manager’s key bindings.

**Comment by Brixy** [comment]
#505 also (almost?) solved this issue, I think. Thanks a lot.

Just tested moving window many times, and only once files and folders did not show up as described above.

Closing this issue.

**Comment by sxyazi** [comment]
Wow I didn't expect that PR to solve this issue, but that's great! Have a good day ;)
