### ISSUE TITLE
Add nushell syntax to previewer

### ISSUE THREAD

**Issue by LatjoLajbin** [sxyazi/yazi#508]
### Is your feature request related to a problem? Please describe

Running Ubuntu 22.04 on WSL 2.

Preview of .nu files seem to have no syntax highlighting. I could not find anything related to nushell in the yazi/prebuild repo and could not find a way to add custom syntaxes in the configuration.

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Build nushell according from this (?) repo and add to the prebuild.

https://github.com/stevenxxiu/sublime_text_nushell

### Additional context

![image](https://github.com/sxyazi/yazi/assets/7878254/da0bf667-c5e4-48ea-963a-52feed54347e)

**Comment by sxyazi** [comment]
Yazi uses the syntax file from `bat` currently, but unfortunately, `bat` does not yet support nushell.

I'm thinking that maybe we can implement it as a custom previewer, like the [json.lua](https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/plugins/json.lua) does, is there are any external CLI tools that support highlighting for nushell?

**Comment by LatjoLajbin** [comment]
Missed replying to this for a few days but tried again today. Since the syntax cache is built for bat locally, a copy of the json plugin that runs bat instead of jq indeed works. 

It runs on all text/* files and probably has some quirks, but it works for me at the moment. Thank you!

![image](https://github.com/sxyazi/yazi/assets/7878254/3022d020-0235-4064-a18c-864bc296e1e0)

![image](https://github.com/sxyazi/yazi/assets/7878254/26a1b488-16c5-48d1-843f-1bd430699034)

**Comment by sxyazi** [comment]
You can use the `name` rule and apply it only to files with the `.nu` extension:

```toml
[plugin]
prepend_previewers = [
  # Plugin path: ~/.config/yazi/plugins/nushell.yazi/init.lua
  { name = "*.nu", exec = "nushell" }
]
```

See the docs here: https://yazi-rs.github.io/docs/configuration/yazi#previewers
