### ISSUE TITLE
Can  not load ui.lua plugin

### ISSUE THREAD

**Issue by linglingqi007** [sxyazi/yazi#515]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

iterm2 3.4.23

### Yazi version

0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

thread 'main' panicked at 'failed to load plugin: "/Users/a007/.config/yazi/ui.lua"', plugin/src/plugin.rs:58:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Expected Behavior

normal loading

### To Reproduce

Tips in the documentation
https://yazi-rs.github.io/docs/tips#full-border

<img width="433" alt="image" src="https://github.com/sxyazi/yazi/assets/6560524/f47b1a86-8e0d-4e00-a8ba-d2267a045ff3">

### Configuration

[plugins]
preload = [
	"~/.config/yazi/ui.lua"
]

**Comment by sxyazi** [comment]
Please paste your `/Users/a007/.config/yazi/ui.lua` contents here

**Comment by linglingqi007** [comment]
Here

Manager = {
	area = ui.Rect.default,
}

function Manager:render(area)
	self.area = area

	local chunks = ui.Layout()
		:direction(ui.Layout.HORIZONTAL)
		:constraints({
			ui.Constraint.Ratio(MANAGER.ratio.parent, MANAGER.ratio.all),
			ui.Constraint.Ratio(MANAGER.ratio.current, MANAGER.ratio.all),
			ui.Constraint.Ratio(MANAGER.ratio.preview, MANAGER.ratio.all),
		})
		:split(area)

	return ya.flat {
		-- Borders
		ui.Bar(chunks[1], ui.Bar.RIGHT):symbol(THEME.manager.border_symbol):style(THEME.manager.border_style),
		ui.Bar(chunks[3], ui.Bar.LEFT):symbol(THEME.manager.border_symbol):style(THEME.manager.border_style),

		-- Parent
		Parent:render(chunks[1]:padding(ui.Padding.x(1))),
		-- Current
		Current:render(chunks[2]),
		-- Preview
		Preview:render(chunks[3]:padding(ui.Padding.x(1))),
	}
end

**Comment by sxyazi** [comment]
Hi, I just released Yazi v0.2.0, please use it with the following code:

```lua
function Manager:render(area)
	self.area = area

	local chunks = ui.Layout()
		:direction(ui.Layout.HORIZONTAL)
		:constraints({
			ui.Constraint.Ratio(MANAGER.ratio.parent, MANAGER.ratio.all),
			ui.Constraint.Ratio(MANAGER.ratio.current, MANAGER.ratio.all),
			ui.Constraint.Ratio(MANAGER.ratio.preview, MANAGER.ratio.all),
		})
		:split(area)

	local bar = function(c, x, y)
		return ui.Bar(
			ui.Rect { x = math.max(0, x), y = math.max(0, y), w = math.min(1, area.w), h = math.min(1, area.h) },
			ui.Bar.TOP
		):symbol(c)
	end

	return ya.flat {
		-- Borders
		ui.Border(area, ui.Border.ALL):type(ui.Border.ROUNDED),
		ui.Bar(chunks[1], ui.Bar.RIGHT),
		ui.Bar(chunks[3], ui.Bar.LEFT),

		bar("┬", chunks[1].right - 1, chunks[1].y),
		bar("┴", chunks[1].right - 1, chunks[1].bottom - 1),
		bar("┬", chunks[2].right, chunks[2].y),
		bar("┴", chunks[2].right, chunks[1].bottom - 1),

		-- Parent
		Parent:render(chunks[1]:padding(ui.Padding.xy(1))),
		-- Current
		Current:render(chunks[2]:padding(ui.Padding.y(1))),
		-- Preview
		Preview:render(chunks[3]:padding(ui.Padding.xy(1))),
	}
end
```

**Comment by linglingqi007** [comment]
Thanks. update to 0.2.1 and copy the code to ~/.config/yazi/init.lua and it would work.

**Comment by linglingqi007** [comment]
Thanks. update to 0.2.1 and copy the code to ~/.config/yazi/init.lua and it would work.
