### ISSUE TITLE
Specify theme.toml and config.toml

### ISSUE THREAD

**Issue by bcp-dev-ops** [sxyazi/yazi#517]
### Is your feature request related to a problem? Please describe

Looking to be able to specify 
yazi —config /path/to/config.toml —theme /path/to/theme.toml (and any other tomls)

the two use cases I’m trying to solve for:
1. Wrapping yazi to specify a theme based on whether or not my computer is in “dark” mode
2. Using slightly different config when running yazi as a process inside of neovim (eg different openers, keymaps, etc)

Thank you for your consideration!

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Enable specifying a —theme and —config option in the CLI

**Comment by bcp-dev-ops** [comment]
Have not frequently coded in rust is my only hesitation to making a PR

**Comment by uncenter** [comment]
I believe you can use the `YAZI_CONFIG_DIR` environment variable to change the location of the config directory.

**Comment by sxyazi** [comment]
Yeah you can use `YAZI_CONFIG_HOME`, docs here https://yazi-rs.github.io/docs/configuration/overview#custom-config-directory
