### ISSUE TITLE
yazi seemingly crashes on Wezterm + pwsh + Windows

### ISSUE THREAD

**Issue by RioNight** [sxyazi/yazi#520]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

wezterm 20230712-072601-f4abf8fd

### Yazi version

yazi 0.2.0 (cb80ca8 2024-01-15)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

When exiting yazi, the terminal gets messed up and the cursor disappears. I need to run `vim` or some other command that takes up the whole terminal screen and then exit that command to get the cursor back.

Before yazi:
![image](https://github.com/sxyazi/yazi/assets/58403689/9b048183-628e-4499-8897-543c3578b465)

After exiting yazi with `q`:
![image](https://github.com/sxyazi/yazi/assets/58403689/fd0346f1-ed75-4ee6-b30a-037452d06105)
I can run `clear`, but the cursor disappears too.

After running and exiting vim:
![image](https://github.com/sxyazi/yazi/assets/58403689/ad3f0a01-1993-4c7c-b07f-201a12e86de8)

Note that the vim command is not shown in the command prompt output history.

In powershell, `echo $LASTEXITCODE` returns 0 and `echo $?` returns true.

Here is the output from gdb:
1.
![image](https://github.com/sxyazi/yazi/assets/58403689/73c00bb2-c976-405a-aee6-f75a6cbecb7f)
2. I enter `run` into the gdb prompt
3. 
![image](https://github.com/sxyazi/yazi/assets/58403689/6dca4f3c-eed7-47c5-97fd-503ee847522f)

### Expected Behavior

The terminal should remain normal when exiting yazi.

### To Reproduce

1. On Windows, install powershell, wezterm, yazi, and git with `scoop install pwsh wezterm yazi git`
2. Add the git usr/bin to the path to let yazi use file(1)
3. Set the ~/.wezterm.lua file as shown below.
4. Run yazi.
5. Quit with `q`
6. Observe error

```lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

config.default_prog = { 'pwsh' }
config.default_cursor_style = 'SteadyBlock'
config.background = {
	{
		source = { File = 'c:\\users\\<user>\\wallpaper.png' },
		hsb = { brightness = 0.01 },
	},
}

-- and finally, return the configuration to wezterm
return config

```

### Configuration

no config

**Comment by sxyazi** [comment]
Hi, I made a PR trying to fix this, let me know if it works for you! https://github.com/sxyazi/yazi/pull/525

**Comment by RioNight** [comment]
Hello. I compiled the latest code. It works now. Thanks.
