### ISSUE TITLE
Residual Content Persists After Exiting Yazi with 'q' Key When No Operations Are Performed

### ISSUE THREAD

**Issue by Loongphy** [sxyazi/yazi#521]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Windows Terminal v1.18.3181.0

### Yazi version

yazi 0.2.1 (1036685 2024-01-16)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Executing the yazi command without any operations and then exiting with the 'q' key leaves residual content. However, if directories are switched using arrow keys, the issue does not occur.

![image](https://github.com/sxyazi/yazi/assets/42089082/3a608765-de37-467e-a293-74be3c8821c2)

### Expected Behavior

The terminal should remain normal when exiting yazi.

### To Reproduce

1. Open the windows terminal
2. Run yazi
3. Quit with `q` key
4. The error

**Comment by themql** [comment]
I have the same question, and the abnormal exit causes some problems with the cursor and scrollbar of windows terminal.

**Comment by sxyazi** [comment]
Hi, I made a PR trying to fix this, let me know if it works for you! https://github.com/sxyazi/yazi/pull/525

**Comment by themql** [comment]
I try it and i think its ok. Thanks to your work❤

**Comment by sxyazi** [comment]
Thanks for testing, let me merge it.

I will release a new version in the next two days, for now please use the main branch.
