### ISSUE TITLE
Current folder listing is completely empty when filenames contain non ASCII characters on a filesystem that does not support UTF-8

### ISSUE THREAD

**Issue by thibaultdouzon** [sxyazi/yazi#524]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

Windows Terminal

### Yazi version

yazi 0.2.1 (1036685 2024-01-16)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Tested on the most recent release, which is the last commit on WSL Ubuntu.
Let "/mnt/network_drive" be a cifs-mounted network drive which does not support UTF-8, if it contains a file or folder named with a non-ASCII character, the navigation preview of the content of the folder is empty but it is still possible to navigate inside.
This folder contains an empty folder `é` (or any non ASCII character).

The content of the current folder is not displayed but we can navigate and inspect files like `text.txt`
![text.txt file yazi](https://github.com/sxyazi/yazi/assets/23520944/1326d52e-d23c-4584-b376-11b5ffee9557)

If I create a file from inside yazi with the included shell commands, I can use non ASCII characters and they are displayed properly
![é.txt file yazi](https://github.com/sxyazi/yazi/assets/23520944/20cd6063-02d4-4161-b0f5-b99ec308e688)

But its name is badly encoded for windows outside of yazi
![é.txt windows file explorer](https://github.com/sxyazi/yazi/assets/23520944/2bca2bc9-1c75-4eab-af45-5680a598997b)

When hovering the faulty folder, its name is not displayed at the bottom
![same folder, hovering an empty folder é](https://github.com/sxyazi/yazi/assets/23520944/34d93bfd-1405-4efe-9b23-ca375d3a0c09)

### Expected Behavior

The content of the folder should preview normally except the faulty characters.

### To Reproduce

folder mounted without UTF-8 support with `sudo mount -t cifs //network_drive /mnt/network_drive -o username=user,uid=$(id -u),gid=$(id -g),forceuid,forcegid,rw` (add `iocharset=utf8` to support UTF-8)
Create a folder from outside yazi with `mkdir/mnt/network_drive/é`
Navigate to /mnt/network_drive with yazi

### Configuration

no config

### Anything else?

ranger previews the content of the folder except the badly encoded characters which are replaced with a blank space.

**Comment by sxyazi** [comment]
Are there any errors in the log file `~/.local/state/yazi/yazi.log`?

**Comment by thibaultdouzon** [comment]
Yes indeed, navigating through the folder produces ~1000 lines of error logs. Here is an extract:

```
 2024-01-16T17:07:27.247259Z ERROR [0m1;31myazi::app::commands::plugin: bad argument #1: error converting Lua string to String (invalid utf-8 sequence of 1 bytes from index 1)
stack traceback:
    [C]: in field 'Span'
    [string "yazi-fm/src/app/commands/plugin.rs:40:27"]:16: in function <[string "yazi-fm/src/app/commands/plugin.rs:40:27"]:3>

    [0m2;3mat yazi-fm/src/app/commands/plugin.rs:52

  2024-01-16T17:07:28.688555Z ERROR [0m1;31myazi::components::manager: bad argument #1: error converting Lua string to String (invalid utf-8 sequence of 1 bytes from index 1)
stack traceback:
    [C]: in field 'Span'
    [string "yazi-plugin/src/plugin.rs:17:13"]:5: in field 'highlight_ranges'
    [string "yazi-plugin/src/plugin.rs:23:13"]:31: in method 'highlighted_name'
    [string "yazi-plugin/src/plugin.rs:22:13"]:11: in method 'render'
    [string "yazi-plugin/src/plugin.rs:25:13"]:25: in function <[string "yazi-plugin/src/plugin.rs:25:13"]:5>

    [0m2;3mat yazi-fm/src/components/manager.rs:17

  2024-01-16T17:07:28.696499Z ERROR [0m1;31myazi::components::manager: bad argument #1: error converting Lua string to String (invalid utf-8 sequence of 1 bytes from index 1)
stack traceback:
    [C]: in field 'Span'
    [string "yazi-plugin/src/plugin.rs:17:13"]:5: in field 'highlight_ranges'
    [string "yazi-plugin/src/plugin.rs:23:13"]:31: in method 'highlighted_name'
    [string "yazi-plugin/src/plugin.rs:22:13"]:11: in method 'render'
    [string "yazi-plugin/src/plugin.rs:25:13"]:25: in function <[string "yazi-plugin/src/plugin.rs:25:13"]:5>

    [0m2;3mat yazi-fm/src/components/manager.rs:17

  2024-01-16T17:07:28.713819Z ERROR [0m1;31myazi::app::commands::plugin: bad argument #1: error converting Lua string to String (invalid utf-8 sequence of 1 bytes from index 1)
stack traceback:
    [C]: in field 'Span'
    [string "yazi-fm/src/app/commands/plugin.rs:40:27"]:16: in function <[string "yazi-fm/src/app/commands/plugin.rs:40:27"]:3>
```

**Comment by sxyazi** [comment]
Hi, I made a PR to fix this, https://github.com/sxyazi/yazi/pull/529, let me know if it works for you!

**Comment by thibaultdouzon** [comment]
Pulled #529 , results looks good to me. 
big thanks for the quick fix.
![image](https://github.com/sxyazi/yazi/assets/23520944/82b387d0-cdba-48db-a414-ad5a7e60148a)
