### ISSUE TITLE
XDG Desktop Entry

### ISSUE THREAD

**Issue by fufexan** [sxyazi/yazi#528]
### Is your feature request related to a problem? Please describe

An XDG Desktop Entry could be useful for:
- launching from an app launcher
- providing MimeType info for directly opening yazi from GUI apps

### Will you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

What I've seen other Rust projects do is have a `data` or `contrib` folder with the logo, .desktop file and optionally an [AppData XML](https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData). Perhaps something similar could be done here. I would do it myself, but I don't know how to actually install the files into place, only in Nix.

**Comment by sxyazi** [comment]
Sounds good to me, do you want to raise a PR to add it?

**Comment by fufexan** [comment]
Sure, but I don't know how to actually install the files. I only know how to do that in Nix.
