### ISSUE TITLE
Unable to see command that was be typed in shell with dark mode terminal

### ISSUE THREAD

**Issue by trunglebka** [sxyazi/yazi#535]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

wezterm/terminator

### Yazi version

yazi 0.2.1 (1036685 2024-01-16)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

As title and this image, I can't see the the command that I typed in shell if my terminal is dark

![image](https://github.com/sxyazi/yazi/assets/16150250/c641a9fe-0411-4a4b-837a-8a5e41c18539)

If I press Esc, it show the character at the pointer position only
![image](https://github.com/sxyazi/yazi/assets/16150250/ce455970-db61-4910-9ca6-621a525cfbc9)

But search box is fine:
![image](https://github.com/sxyazi/yazi/assets/16150250/a914ebcb-ddc2-4f09-b841-677f49d98769)

### Expected Behavior

See the command in shell in dark mode

### To Reproduce

`;` to enter shell and type a command

**Comment by knodalyte** [comment]
Also happens running on kitty in X11.

**Comment by sxyazi** [comment]
Thank you for the report, should be fixed in #536, let me know if it works for you!

**Comment by trunglebka** [comment]
It worked:
![image](https://github.com/sxyazi/yazi/assets/16150250/044be7a4-386a-41d5-b2dd-69574099a4e8)
