### ISSUE TITLE
Alacritty Wayland ueberzugpp images not properly aligned

### ISSUE THREAD

**Issue by fritzrehde** [sxyazi/yazi#541]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

alacritty 0.13.1 (fe2a3c56)

### Yazi version

yazi 0.1.5 (c3a8bdc 2024-01-09)

### Did you try the latest main branch to see if the problem has already been fixed?

Not tried, and I'll explain why below

### Describe the bug

See: 

https://github.com/sxyazi/yazi/assets/80471265/5bf021cc-0907-4eee-b816-d5040d07c4d9

When moving the cursor, the image preview is displayed too far off to the right, so most of it is cut off. **Important**: I tried using `kitty` and `foot` terminals, and both **worked**, so this must be alacritty-related. So I'm not sure if there is anything yazi can do/fix to fix this issue.

### Expected Behavior

The full image should be shown on preview, aligned to the left.

### To Reproduce

Use alacritty terminal on Wayland with `ueberzugpp` and preview any image file.

**Comment by jstkdng** [comment]
hey, that could be an issue with fractional scaling. Try using using `ueberzugpp` from master

**Comment by sxyazi** [comment]
Yea please try the latest ueberzugpp from master branch.

If it doesn't work, you can also use `ueberzug_scale` and `ueberzug_offset` to adjust the relative offset position of ueberzugpp according to your needs. See the docs here: https://yazi-rs.github.io/docs/configuration/yazi#ueberzug-specific

**Comment by fritzrehde** [comment]
> jstkdng

Ah yes, I do have fractional scaling enabled (currently `1.2` on my laptop with which I ran `yazi`).
