### ISSUE TITLE
`Enter` in selection within interactive change directory should change to that selected directory

### ISSUE THREAD

**Issue by paletochen** [sxyazi/yazi#542]
### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

During `Change directory` mode (`<g>space`)

![image](https://github.com/sxyazi/yazi/assets/109062850/944a1f4b-51e6-45ea-ac0a-383b374b77d9)

when searching for a directory

![image](https://github.com/sxyazi/yazi/assets/109062850/62e14e93-9e54-47f8-9bc9-681e709b899a)

and selecting one (`Downloads` in the below example)

![image](https://github.com/sxyazi/yazi/assets/109062850/97649173-0389-4daf-b171-a19660d7d8a5)

pressing `Enter` should change to the selected directory.

Currently, when pressing `Enter` yazi exits interactive move and remains in its original location.

**Comment by sxyazi** [comment]
You need to use `Tab` for completion, and `Enter` to submit. This uses the same keys as shell completion but provides a better presentation: 

https://github.com/sxyazi/yazi/blob/1bfd1c002fc737f7c9466311b9f1fd88513b418e/yazi-config/preset/keymap.toml#L258-L271

**Comment by paletochen** [comment]
> You need to use `Tab` for completion, and `Enter` to submit. This uses the same keys as shell completion but provides a better presentation:
> 
> https://github.com/sxyazi/yazi/blob/1bfd1c002fc737f7c9466311b9f1fd88513b418e/yazi-config/preset/keymap.toml#L258-L271

Yes,
I am aware of the current workflow.
I'd like to avoid the need of using 'Tab' when all I want is entering the directory.
The 'Tab' workflow makes sense when you want to go deeper into further sub directories. But feels too slow in the use case I am mentioning.

Also, I don't think adding this functionality would conflict with current workflow.

Lastly, current situation, where pressing 'Enter' does nothing, feels to me like a bug. That's how I felt the first minutes when I was trying to understand what was going on, why pressing 'Enter' would not do anything.
I think it would be a nice added value

**Comment by sxyazi** [comment]
If `Enter` is used for completion, how would you enter a directory? For example, if you type `/fo` and press `Enter`, it completes to `/foo/`. At this point, it continues to display the completion menu. When you press `Enter` again, it might complete to `/foo/bar/`, and pressing `Enter` again could complete to `/foo/bar/baz/`. This entire process prevents you from entering the directory until it continues until there are no more files.

**Comment by paletochen** [comment]
> If `Enter` is used for completion, how would you enter a directory? For example, if you type `/fo` and press `Enter`, it completes to `/foo/`. At this point, it continues to display the completion menu. When you press `Enter` again, it might complete to `/foo/bar/`, and pressing `Enter` again could complete to `/foo/bar/baz/`. This entire process prevents you from entering the directory until it continues until there are no more files.

The process I had in my mind was: once you press 'Enter' on selection, you exit the menu (like you do now) but inside the selected directory.

**Comment by sxyazi** [comment]
This sounds like a mix of completion and entering, meaning people have to remember that the final step must be `Enter`, not `Tab`, or they might not be able to enter the target directory — even if they did complete the path with `Tab`.

This also results in losing the ability to input the full path, which often happens when users copy a path inside (using the `cp` command) or outside Yazi, and want to quickly navigate to it using `g<Space>`. In such cases, users must manually delete the last part of the path, then select it through completion, and finally press `Enter`.

This conflicts with the current behavior, altering the shell-like workflow, and I'm not sure if it's reasonable.

**Comment by paletochen** [comment]
> This also results in losing the ability to input the full path, which often happens when users copy a path inside (using the [`cd` keymap](https://yazi-rs.github.io/docs/quick-start#copying-paths)) or outside Yazi, and want to quickly navigate to it using `g<Space>`. In such cases, users must manually delete the last part of the path, then select it through completion, and finally press `Enter`.
> 
> This conflicts with the current behavior, altering the shell-like workflow, and I'm not sure if it's reasonable.

I think I am confused now because I am not understanding how this proposal of adding an action to `Enter` in the interactive directory change popup can affect the actions that you just mentioned.

Currently, in this view:
![image](https://github.com/sxyazi/yazi/assets/109062850/c8f2a10f-891e-41c8-b361-ea0b40d3e662)

- `Enter` does nothing else but exiting from the menu. It brings you back to the moment before you press <g>space. The reason being is that there is only `D` written on the input box, which is not a file nor directory
- `Tab` completes the path based on the selection (`Documents`), fills the input box with that selection and the user can continue searching, or press `Enter` to land in the `Documents` folder.

Once the user has pressed `Tab` once and started filling the input box, `Enter` will exit you to whatever path is being indicated.

The FR that i was discussing here has to do only with that very first moment when the input box is empty, there are only characters from the user while searching for something.
The current behavior is to exit if those characters don't mean anything.
My proposal is to exit to the path that the selection is pointing to.
`Escape` is the natural way for me to cancel the process, if i want to go back, and the way to clean the menu and exit from it. I have difficulties relating `Enter` to "don't do anything, cancel".

> This sounds like a mix of completion and entering, meaning people have to remember that the final step must be `Enter`, not `Tab`, or they might not be able to enter the target directory — even if they did complete the path with `Tab`.

Isn't `Enter` always the last step that one needs to do? I cannot exit the "change directory" menu pressing `Tab`.
I am not sure I understand this explanation.

**Comment by sxyazi** [comment]
Ah you're right.

What I meant is that if you copy a path like `/foo/bar` and paste it into the `g<Space>` input box, it won't navigate to `/foo/bar`.

This is based on the fact that I forgot autocompletion only triggers for paths ending in `/`, so it only affects users who copied `/foo/bar/` – they need to remove the trailing `/` and then press `Enter`. But this doesn't seem to be very common.

**Comment by sxyazi** [comment]
Done by https://github.com/sxyazi/yazi/pull/565
