### ISSUE TITLE
Allow the filtering of the interactive cd (`g<space>`) results to be case insensitive

### ISSUE THREAD

**Issue by RioNight** [sxyazi/yazi#547]
### Is your feature request related to a problem? Please describe

When I interactive cd with `g<space>` I would like to quickly navigate to some subdirectory. It would be much easier and ergonomic if filtering the drop down against the user input were smart cased or case insensitive, like the slash `/` searching.

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Smart casing is when the default search is case-insensitive but when you input a upper case letter the search becomes case sensitive.
A simple case insensitive would also be good.

### Additional context
If you're in a directory with subdirectories `Desktop`, `Documents`, and `downloads`, entering `d` into the `g<space>` search bar will filter out `Documents` and `Desktop`, leaving only `downloads`.
However, in the `/` search, searching for `d` still keeps the uppercased directories.

_No response_

**Comment by sxyazi** [comment]
Added to the [Feature Requests](https://github.com/sxyazi/yazi/issues/51), closing in favor of that list.

**Comment by sxyazi** [comment]
Hi, this feature has been implemented by @ndtoan96 in https://github.com/sxyazi/yazi/pull/910! :tada:
