### ISSUE TITLE
Directories have inconsistent slashes on Windows

### ISSUE THREAD

**Issue by RioNight** [sxyazi/yazi#548]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

wezterm 20230712-072601-f4abf8fd

### Yazi version

yazi 0.2.2 (93dc1b7 2024-01-20)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

(1)
The current working directory shown at the top has forward slashes on Windows:
![image](https://github.com/sxyazi/yazi/assets/58403689/50cd1746-ce9e-47cb-86c6-6cf84e56928d)

However, when entering into new directories, the new directories are appended to the current working directory after a back slash:
![image](https://github.com/sxyazi/yazi/assets/58403689/107c1900-4936-4e53-a422-91600a44ed68)
![image](https://github.com/sxyazi/yazi/assets/58403689/5ea83ac9-07a4-4518-8be8-a320a9a85d1e)

(2)
When showing the target of a symlink, the slashes are displayed with back slashes:
![image](https://github.com/sxyazi/yazi/assets/58403689/6e2f3e18-1b60-4b3f-89a6-caec34272e17)

(3)
The search results for the interactive cd have a back slash.
![image](https://github.com/sxyazi/yazi/assets/58403689/cd68c1ba-3862-44a2-afdf-c5a0f78d5603)
But when you input a forward slash the search results disappear.
![image](https://github.com/sxyazi/yazi/assets/58403689/bdcfc3ea-a371-4148-b07d-36871fe620a8)
However, you can enter into `testdir` in the above image despite the forward slash with `Enter`.

(4)
The help menus says to create a directory with `a`, the name, followed by a `/`. But this does not work. It only works with `a`, the name, followed by a `\`.

### Expected Behavior

It would be nice for everything to just be forward slashes.
Windows `cmd` and `pwsh` support `cd`-ing into directory paths with forward slashes. The Windows File Explorer also supports this. Making it all forward slashes would keep the ui consistent througout.

The back slash is an escape character on Windows, so when you for the back slash often you need to escape it, like `dir1\\dir2\\file.txt`.

Many programs also only display forward slashes for Windows paths. For example, vim, neovim, the focus editor.
Other programs do a mix of both. They display backslashes but allow normally navigating a directory tree with forward slashes.

For problem (3) and (4) mentioned above, this is when a user enters the path separator. You could allow both on Windows, or just the forward slash.

### To Reproduce

scoop install all dependencies, follow the Windows setup guide, and build yazi from source.

### Configuration

no config

**Comment by sxyazi** [comment]
Using "\" for all seems to be the simplest and easiest solution, this way we can avoid cache invalidation issues - HashMap will only encounter one file path, not a mix of the two.

**Comment by RioNight** [comment]
In that case, can `\` be used everywhere but `/` be used in `g<space>` somehow?
In my experience, it is the most common way to navigate directories, between being able to in cmd and pwsh, and natively in bash (in Windows), and then also in wsl.

Currently, `/` will not allow you to go to a subdirectory:
![image](https://github.com/sxyazi/yazi/assets/58403689/403395d3-7d7d-4711-b813-8071bcf5ff30)

You always need the `\` like so:
![image](https://github.com/sxyazi/yazi/assets/58403689/c32cb7c9-5071-4c13-9691-b6824e8117d8)

**Comment by sxyazi** [comment]
Yeah, it is intentionally designed that way - [using `\` on Windows instead of `/`](https://github.com/sxyazi/yazi/blob/74bcae037b43c840698a8335c17afa7f3778001f/yazi-shared/src/fs/path.rs#L52), and this [also applies to `create`](https://github.com/sxyazi/yazi/blob/74bcae037b43c840698a8335c17afa7f3778001f/yazi-core/src/manager/commands/create.rs#L35). The standard library in Rust has the same behavior - when concatenating two paths, `/` is used for Unix, and `\` for Windows.

**Comment by RioNight** [comment]
I believe the rust crate allows creation of directories with `/` in Windows.
for example, in yazi creating with `a` you can enter, `dir/dir\` to create dir with a subdirectory dir. `dir/file` also works. But `dir/dir/` won't work because yazi is looking for the MAIN_SEPARATOR.

**Comment by sxyazi** [comment]
Should also be fixed in https://github.com/sxyazi/yazi/pull/909
