### ISSUE TITLE
Disambiguate the `s` and `S` search boxes

### ISSUE THREAD

**Issue by RioNight** [sxyazi/yazi#549]
### Is your feature request related to a problem? Please describe

I don't remember what one does, but do know that two different search modes exist. Currently, both just show "Search:":
![image](https://github.com/sxyazi/yazi/assets/58403689/121ee313-fa1f-476f-aee0-e3cf37f6bf32)

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Disambiguating the two with better titles like `Search by file name:` and `Search by file content:` would be great.

**Comment by sxyazi** [comment]
Sounds good to me. Would you like to raise a PR to add it?

**Comment by RioNight** [comment]
Thanks, but I would take longer than necessary to do so. You could do it.
