### ISSUE TITLE
Search only triggers on second try

### ISSUE THREAD

**Issue by EmiOnGit** [sxyazi/yazi#554]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Kitty 0.31

### Yazi version

main [yazi 0.2.2 (69dec96 2024-01-21)]

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

When pressing `s/S` respectively the prompt for searching is shown. 
However after entering a input and pressing enter, nothing is shown.
If `s/S` is pressed again, the search suddenly works.

### Expected Behavior

The search should show results on the first try.

### To Reproduce

```cargo r -r ``` in the main repository directly.
![image](https://github.com/sxyazi/yazi/assets/95967983/07fc4a4d-de43-4cc1-8e6c-77c6d5b5175f)

`S` to enter search by content and type "color"
![image](https://github.com/sxyazi/yazi/assets/95967983/586dce2f-63f4-4e52-9b62-7d2f099bb62a)

press enter to issue search. No results are shown
![image](https://github.com/sxyazi/yazi/assets/95967983/df9d8365-cb40-47cb-a96e-18f715e21cfc)

press `S` again and type "color". The results show now
![image](https://github.com/sxyazi/yazi/assets/95967983/ffcde229-24df-474f-85c9-e3f9097aaccc)

### Anything else?

That's a great project btw :)

**Comment by EmiOnGit** [comment]
Seem to work properly on version 0.1.5 (arch release)

**Comment by EmiOnGit** [comment]
I did narrow the bug with git bisect. It seems it was introduced in commit `69dec968334b6baf57307440f1b940bd0f141dd5`.. which is actually the latest commit in main :p

**Comment by sxyazi** [comment]
Thanks for the reporting! I'll investigate it soon.

**Comment by sxyazi** [comment]
Fixed in https://github.com/sxyazi/yazi/commit/2b1b66e5e027e7e1586758168feb6203e3f61d72
