### ISSUE TITLE
Editor unusable after resuming a suspended (neo)vim

### ISSUE THREAD

**Issue by codido** [sxyazi/yazi#555]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Alacritty

### Yazi version

yazi 0.2.2 (69dec96 2024-01-21)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

When opening a file with vim or neovim, suspending the editor with ctrl-z, and resuming it with fg, the terminal becomes unusable. It looks as if both yazi and vim both try to control the terminal at the same time.

### Expected Behavior

When resuming vim, only vim should control the terminal, keeping yazi seemingly suspended.

### To Reproduce

1. Set the EDITOR environment variable to either vim or nvim
2. Start yazi
3. Open a text file
4. Type ctrl-z to suspend vim
5. Return to vim with `fg`

### Configuration

no config

**Comment by sxyazi** [comment]
Thanks for reporting! I'll investigate it soon.

**Comment by sxyazi** [comment]
Hi, I made a PR to fix this, let me know if it works for you! https://github.com/sxyazi/yazi/pull/556

**Comment by codido** [comment]
Seems to work great, thank you!
