### ISSUE TITLE
Syntect color displays incorrectly

### ISSUE THREAD

**Issue by NeumoNeumo** [sxyazi/yazi#557]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.27.1

### Yazi version

yazi 0.2.2 (701c08c 2024-01-22)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

When using [catppuccin-latte theme](https://github.com/yazi-rs/themes/tree/main/catppuccin-latte), the background of code highlighting is as weird as a patchwork as shown below
![image](https://github.com/sxyazi/yazi/assets/107997665/90ef8b69-619d-4153-bb82-457e6875794f)

### Expected Behavior

The background color should behave correctly.

### To Reproduce

Build the latest(701c08c) yazi and then move the official [catppuccin-latte theme](https://github.com/yazi-rs/themes/tree/main/catppuccin-latte) including `theme.toml` and `Catppuccin-latte.tmTheme` to `~/.config/yazi`.

An interesting thing is that you can also reproduce this bug even without a customized theme because the default theme **also** treats background colors incorrectly.
*Default theme*:
![image](https://github.com/sxyazi/yazi/assets/107997665/eb87f543-312d-4761-95a4-7c38ed2e36cc)

### Configuration

`theme.toml` is the same as the official [catppuccin-latte theme](https://github.com/yazi-rs/themes/tree/main/catppuccin-latte) and `Catppuccin-latte.tmTheme` is also used. No `yazi.toml` and `keymap.toml`

**Comment by sxyazi** [comment]
I can't reproduce it with the latest main branch: yazi 0.2.2 (701c08c 2024-01-22)

![1](https://github.com/sxyazi/yazi/assets/17523360/30e73b6d-d88d-428a-813e-d86c3b9fecf4)

**Comment by NeumoNeumo** [comment]
> I noticed that you are using tmux. Ensure that you have correctly configured your `$TERM` inside tmux, or it may result in rendering errors in tmux:
> 
> ```
> # Change the default $TERM to tmux-256color
> set -g default-terminal "tmux-256color"
> # Enable RGB colour if running in xterm(1)
> set -ga terminal-overrides ",xterm*:Tc"
> ```

Yeah, you are right. That's an issue with tmux. Thank you!
