### ISSUE TITLE
Image preview quality degrades too heavily

### ISSUE THREAD

**Issue by AlexKurisu** [sxyazi/yazi#562]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

wezterm 20240121-180215-76028ca1

### Yazi version

yazi 0.2.2 (acb8b47 2024-01-22)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

Image previews quality is heavily degraded compared to just running `chafa -f iterm2 <filename>` or `wezterm imgcat <filename>`

### Expected Behavior

Even considering scaling down, image quality should not degrade THAT much. Changing `max_width` and `max_height` does nothing, and so does changing `image_alloc`

### To Reproduce

Just run `yazi` in `wezterm` terminal and preview some images. JPEG's are the most noticeable, but others should be noticeable too.

### Configuration

No config

### Anything else?

Screenshots
<details>
<summary>**WARNING**: Kinda NSFW (sorry, I have no other images)</summary>

Yazi preview:
![image](https://github.com/sxyazi/yazi/assets/60626727/2e4781dc-c77f-4ff4-9bdc-8a700f8f2081)

`wezterm imgcat` output:
![image](https://github.com/sxyazi/yazi/assets/60626727/854f971f-e789-4ffb-98e0-56890dfa8870)

`chafa -f iterm2` output:
![image](https://github.com/sxyazi/yazi/assets/60626727/78adde20-5de6-4721-81a4-2a13f34c8974)

</details>

**Comment by sxyazi** [comment]
I think this is not a bug, it's just that Yazi's default image compression strategy is more aggressive.

I'll add a new config option to allow users to adjust the compression level manually. Of course, any PRs are highly welcome!

**Comment by bvr-yr** [comment]
sadly #576 didn't made it better in this case:

```toml
image_quality   = 90
sixel_fraction	= 10
```

- yazi output 600px
![image_2024-01-25_11-38-58.png](https://github.com/sxyazi/yazi/assets/130279855/1938a6ca-a563-4576-a7d2-48d8e550528e)

- [viu](https://github.com/atanunq/viu) (uses libsixel)
![image_2024-01-25_11-44-17](https://github.com/sxyazi/yazi/assets/130279855/a8dcae51-37a1-40b8-ae81-fe2dc022b68a)

- libsixel native tool
![image_2024-01-25_11-48-49](https://github.com/sxyazi/yazi/assets/130279855/1a6f2edc-113e-4314-876b-ca7760733d1c)

- yazi output 900px, better
![image_2024-01-25_12-14-15](https://github.com/sxyazi/yazi/assets/130279855/e7fc2141-3934-44cd-bdd9-964b25d600c5)


- ranger, imagemagick convert under the hood (uses its own sixel convert, not libsixel)
![image_2024-01-25_12-13-48](https://github.com/sxyazi/yazi/assets/130279855/37a256fd-2ad8-4555-b352-269eb2cc3d7a)


original image
![cover](https://github.com/sxyazi/yazi/assets/130279855/94299951-5bf8-4784-a05b-88f226c5c5af)


u can check viu's backend [viuer](https://github.com/atanunq/viuer), particularly  [sixel-rs](https://crates.io/crates/sixel-rs)
seems like neural-thingy doesn't make it :rofl:

**Comment by sxyazi** [comment]
@bvr-yr  Currently, `image_quality` is intentionally limited to a maximum of 90, and `sixel_fraction` is set to a minimum of 10. This strikes a relative balance between performance and image quality, and I believe it's a reasonably appropriate range.

If you think sacrificing some CPU resources for better image quality is necessary, please create a new issue, and I will remove that restriction.

As for `sixel-rs`, it's not an acceptable solution as it introduces additional external C library dependencies, making it harder for users to build.

**Comment by sxyazi** [comment]
FIY: sixel-sys, which is a dependency of sixel-rs, hasn't been maintained for 7 years. I don't think it should be used anymore. The build issues in its issue list have been there for almost 3 years, and still haven't been resolved, https://github.com/AdnoC/sixel-sys/issues

**Comment by sxyazi** [comment]
In case someone passing by:

The difference in image quality mentioned by @bvr-yr is unrelated to Yazi's Sixel implementation (also unrelated to the two newly added options `image_quality` and `sixel_fraction`), see https://github.com/sxyazi/yazi/issues/577#issuecomment-1909940548 and https://github.com/sxyazi/yazi/issues/577#issuecomment-1910077953

But it's related to the use of different filters during image downscaling. I have added a new option `image_filter`, to allow users to configure it, https://github.com/sxyazi/yazi/pull/586
