### ISSUE TITLE
Audio files preview

### ISSUE THREAD

**Issue by og900aero** [sxyazi/yazi#567]
### Is your feature request related to a problem? Please describe

Currently, in the case of audio files, we get the following preview image:

![screenshot_1706019824](https://github.com/sxyazi/yazi/assets/49487376/e7239684-100d-4452-b6fa-97a8b4c2ac8a)

I think it would be better if we could get more information using the exiftool program:

![screenshot_1706019819](https://github.com/sxyazi/yazi/assets/49487376/23ee2821-d361-4ed0-9194-e5727b2580ce)

### Will you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

The Exiftool program is required. Usage:

exiftool filename

**Comment by sxyazi** [comment]
Hi! Would you like to make it a previewer plugin?


Yazi allows you to create and use your own previewers and preloaders. You can start by copying the [file.lua](https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/plugins/file.lua) into your `~/.config/yazi/plugins/audio.yazi/init.lua`, see the docs here https://yazi-rs.github.io/docs/plugins/overview#previewer

And if you're willing, I'll add your repo url to the Yazi documentation somewhere, maybe "community plugins".

**Comment by og900aero** [comment]
> Hi! Would you like to make it a previewer plugin?
> 
> Yazi allows you to create and use your own previewers and preloaders. You can start by copying the [file.lua](https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/plugins/file.lua) into your `~/.config/yazi/plugins/audio.yazi/init.lua`, see the docs here https://yazi-rs.github.io/docs/plugins/overview#previewer
> 
> And if you're willing, I'll add your repo url to the Yazi documentation somewhere, maybe "community plugins".

The code:

```
local M = {}

function M:peek()
	local output, code = Command("exiftool")
		:args({
			tostring(self.file.url),
		})
		:stdout(Command.PIPED)
		:output()

	local p
	p = ui.Paragraph.parse(self.area, output.stdout)

	ya.preview_widgets(self, { p:wrap(ui.Paragraph.WRAP) })
end

function M:seek(units)
	local h = cx.active.current.hovered
	if h and h.url == self.file.url then
		local step = math.floor(units * self.area.h / 10)
		ya.manager_emit("peek", {
			tostring(math.max(0, cx.active.preview.skip + step)),
			only_if = tostring(self.file.url),
		})
	end
end

return M
```

1. Working the preview.
2. Not working the previewed text scrolling

**Comment by sxyazi** [comment]
Oh I see. Please copy [json.lua](https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/plugins/json.lua) instead of file.lua. It handles scrolling well.

**Comment by og900aero** [comment]
Uhh, the code became much longer.
Now working both functions.

```
local M = {}

function M:peek()
	local child = Command("exiftool")
		:args({
			tostring(self.file.url),
		})
		:stdout(Command.PIPED)
		:stderr(Command.PIPED)
		:spawn()

	if not child then
		return self:fallback_to_builtin()
	end

	local limit = self.area.h
	local i, lines = 0, ""
	repeat
		local next, event = child:read_line()
		if event == 1 then
			return self:fallback_to_builtin()
		elseif event ~= 0 then
			break
		end

		i = i + 1
		if i > self.skip then
			lines = lines .. next
		end
	until i >= self.skip + limit

	child:start_kill()
	if self.skip > 0 and i < self.skip + limit then
		ya.manager_emit("peek", { tostring(math.max(0, i - limit)), only_if = tostring(self.file.url), upper_bound = "" })
	else
		lines = lines:gsub("\t", string.rep(" ", PREVIEW.tab_size))
		ya.preview_widgets(self, { ui.Paragraph.parse(self.area, lines) })
	end
end

function M:seek(units)
	local h = cx.active.current.hovered
	if h and h.url == self.file.url then
		local step = math.floor(units * self.area.h / 3)
		ya.manager_emit("peek", {
			tostring(math.max(0, cx.active.preview.skip + step)),
			only_if = tostring(self.file.url),
		})
	end
end

function M:fallback_to_builtin()
	local _, bound = ya.preview_code(self)
	if bound then
		ya.manager_emit("peek", { tostring(bound), only_if = tostring(self.file.url), upper_bound = "" })
	end
end

return M
```

**Comment by sxyazi** [comment]
`fallback_to_builtin` seems unnecessary, you can remove it.

**Comment by og900aero** [comment]
Then there were two examples. The first one lists every single piece of information, so you can scroll through the preview image. The second example lists only the essential/important information. In this case, there is no scrolling option, because it is not needed.

1 All information:

```
local M = {}

function M:peek()
	local child = Command("exiftool")
		:args({
			tostring(self.file.url),
		})
		:stdout(Command.PIPED)
		:stderr(Command.PIPED)
		:spawn()

	if not child then
		return self:fallback_to_builtin()
	end

	local limit = self.area.h
	local i, lines = 0, ""
	repeat
		local next, event = child:read_line()
		if event == 1 then
			return self:fallback_to_builtin()
		elseif event ~= 0 then
			break
		end

		i = i + 1
		if i > self.skip then
			lines = lines .. next
		end
	until i >= self.skip + limit

	child:start_kill()
	if self.skip > 0 and i < self.skip + limit then
		ya.manager_emit("peek", { tostring(math.max(0, i - limit)), only_if = tostring(self.file.url), upper_bound = "" })
	else
		lines = lines:gsub("\t", string.rep(" ", PREVIEW.tab_size))
		ya.preview_widgets(self, { ui.Paragraph.parse(self.area, lines) })
	end
end

function M:seek(units)
	local h = cx.active.current.hovered
	if h and h.url == self.file.url then
		local step = math.floor(units * self.area.h / 3)
		ya.manager_emit("peek", {
			tostring(math.max(0, cx.active.preview.skip + step)),
			only_if = tostring(self.file.url),
		})
	end
end

return M
```

2. Only important information

```
local M = {}

function M:peek()
	local output, code = Command("exiftool")
		:args({
			"-File*",
			"-SampleRate",
			"-Channels",
			"-BitsPerSample",
			"-AlbumArtist",
			"-Artist",
			"-Album",
			"-Composer",
			"-Date",
			"-Genre",
			"-Discnumber",
			"-Organization",
			"-Title",
			"-Tracktotal",
			"-TrackNumber",
			"-Duration",
			tostring(self.file.url),
		})
		:stdout(Command.PIPED)
		:output()

	local p
	p = ui.Paragraph.parse(self.area, output.stdout)

	ya.preview_widgets(self, { p:wrap(ui.Paragraph.WRAP) })
end

function M:seek(units)
	local h = cx.active.current.hovered
	if h and h.url == self.file.url then
		local step = math.floor(units * self.area.h / 10)
		ya.manager_emit("peek", {
			tostring(math.max(0, cx.active.preview.skip + step)),
			only_if = tostring(self.file.url),
		})
	end
end

return M
```

**Comment by sxyazi** [comment]
Nice work! Would you like to create a repo for it, like https://github.com/Reledia/glow.yazi? I can add it to the documentation of Yazi to help other people to use it.

**Comment by og900aero** [comment]
> Nice work! Would you like to create a repo for it, like https://github.com/Reledia/glow.yazi? I can add it to the documentation of Yazi to help other people to use it.

Uhh. I only use github minimally. Mostly just for asking questions and commenting. Feel free to use the code I wrote in your own documentation.

**Comment by sxyazi** [comment]
Okay, I'll see if someone wants to do this. Let's finish this issue then
