### ISSUE TITLE
Markdown preview with glow

### ISSUE THREAD

**Issue by idan-at** [sxyazi/yazi#572]
### Is your feature request related to a problem? Please describe

Previewing markdown files currently show the raw file. Having a custom plugin could be awesome :)

### Will you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Similar to the json plugin that relies on `jq`, we can rely on [glow](https://github.com/charmbracelet/glow) for rendering the markdown preview.

### Describe alternatives you've considered

I found glow from a quick google search. Tested it on my Linux, and it works well. If you are familiar with a different CLI, we can integrate it instead of glow.

**Comment by sxyazi** [comment]
Hi! Would you like to make it a previewer plugin?


Yazi allows you to create and use your own previewers and preloaders. You can start by copying the [json.lua](https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/plugins/json.lua) file into your `~/.config/yazi/plugins/markdown.yazi/init.lua`, see the docs here https://yazi-rs.github.io/docs/plugins/overview#previewer

And if you're willing, I'll add your repo url to the Yazi documentation somewhere, maybe "community plugins".

**Comment by Reledia** [comment]
Hello. I tried to make a glow plugin and 'it works on my machine'. If you want to try it: [yazi-plugins](https://github.com/Reledia/yazi-plugins)

**Comment by sxyazi** [comment]
@Reledia Awesome, it works very well!

![1](https://github.com/sxyazi/yazi/assets/17523360/79cdfa85-6f53-46ce-af03-3e8de94df192)

**Comment by idan-at** [comment]
@Reledia works great, thanks!

@sxyazi What mime type did you use? `text/markdown` nor `text/x-markdown` worked for me (tested it using `text/*`, but I don't want to define it that widely).

**Comment by sxyazi** [comment]
Hmm I used `name` rule, i.e. `{ name = "*.md", exec = "glow" }`

**Comment by idan-at** [comment]
Much better. Thanks. As far as I'm concerned you can close this issue

**Comment by sxyazi** [comment]
Okay. Added to docs, https://yazi-rs.github.io/docs/resources/
