### ISSUE TITLE
Preview is distorted on some images

### ISSUE THREAD

**Issue by SolitudeSF** [sxyazi/yazi#577]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty v0.32.0

### Yazi version

yazi 0.2.2 (ba0c860 2024-01-25)

Some images seem to be scaled improperly, because they have jarring horizontal lines that look like resizing artifacts.
![image](https://github.com/sxyazi/yazi/assets/10168645/4d819902-6674-428b-be94-b20caf14ef0c)

### To Reproduce

Source image
![F7Rb51YbkAALpOB](https://github.com/sxyazi/yazi/assets/10168645/bf7d56f7-e784-440e-add9-5af44e79e5eb)

reproduces consistently on my machine, but it should be dependant on monitor resolution, terminal size and cell size, i guess.

### Configuration

quality setting is irrelevant and it doesnt look like a compression artifact.

**Comment by sxyazi** [comment]
I think it might be related to the filter used during downscale.

Yazi currently uses the `Triangle` filter: 
![Triangle](https://github.com/sxyazi/yazi/assets/17523360/bcfff54c-7b64-4589-8382-68a4e3e2c901)


This is switching to the `Lanczos3` filter:
![Lanczos3](https://github.com/sxyazi/yazi/assets/17523360/67826fa8-3e9d-46bf-850f-94c752f4bc50)


It seems like `Lanczos3` better preserves the texture of the background, but I'm not sure, my eyes have stopped working. 😅 Perhaps we can make the filter a configurable option?

cc @bvr-yr, do you think it's related to [the issue you mentioned before](https://github.com/sxyazi/yazi/issues/562#issuecomment-1909730948) - is it possible that the difference in image quality is due to different filters rather than Sixel itself?

**Comment by bvr-yr** [comment]
@sxyazi i'll try it now.
btw, just for curiosity and to be sure, i removed validation and tried with
```toml
image_quality   = 100
sixel_fraction	= 1
```
wich gave almost no quality increase but alot CPU load :laughing:

**Comment by SolitudeSF** [comment]
I have the same artifacts with `Lanczos3`

**Comment by sxyazi** [comment]
Have you changed both filters at

https://github.com/sxyazi/yazi/blob/ba0c860b2e4098318fb1a07f67ac81d7c08f230d/yazi-adaptor/src/image.rs#L29

and 

https://github.com/sxyazi/yazi/blob/ba0c860b2e4098318fb1a07f67ac81d7c08f230d/yazi-adaptor/src/image.rs#L72

and do a `yazi --clear-cache`?

**Comment by SolitudeSF** [comment]
shoud've grepped, no, only one.

**Comment by bvr-yr** [comment]
well i tried them all, changed both lines:

- Nearest
![145106-area- 1186 576-149x122 -Nearest](https://github.com/sxyazi/yazi/assets/130279855/9c1f352f-341b-40e8-b490-47bb763398ba)
- CatmullRom
![144906-area- 1192 584-153x108 -CatmullRom](https://github.com/sxyazi/yazi/assets/130279855/df58d606-c734-41b8-bef8-c6fd272b82ec)
- Lanczos3
![145243-area- 1202 589-131x104 -Lanczos3](https://github.com/sxyazi/yazi/assets/130279855/15e1f5a4-3348-4441-8d32-7ff3d3cea440)
- Gaussian
![145440-area- 1197 588-151x104 -Gaussian](https://github.com/sxyazi/yazi/assets/130279855/18024fc9-b6a5-4017-a2f8-fde81100c661)
- Triangle
![145632-area- 1199 592-150x101 -Triangle](https://github.com/sxyazi/yazi/assets/130279855/60c836e3-57e5-456e-8691-852a8abec85f)


so it seems like not the sixel problem itself, rather it is as whole conversion chain

Nearest gives best result, but it might look too pixelated (keep in mind github converts imges itself)

I think best option is to give freedom (as always :wink:) and just introduce another config option to choose filter, as it might be different results with sixel/kitty/iterm/etc

**Comment by SolitudeSF** [comment]
Nope, doesnt help. Same artifacts are visible. Just for the reference, in ranger, no matter how i resize the terminal image clean without artifacts.

**Comment by bvr-yr** [comment]
as offtopic about sixel:
ranger does primary caching slow due to calling `imagemagick`, but it does another caching (as for sixel atleast), for current running ranger instance so that sixel doesn't need to be generated every time image is previewed and as a result it is rendered instantly, whereas yazi regenerates sixel data every time

is this thing hard to implement? if not so, i can create feature request if needed

**Comment by SolitudeSF** [comment]
> Does increasing the pre-cache image size help?
> 
> https://github.com/sxyazi/yazi/blob/ba0c860b2e4098318fb1a07f67ac81d7c08f230d/yazi-config/preset/yazi.toml#L17-L18

increased to 2000x2000. no change.

**Comment by sxyazi** [comment]
> as offtopic about sixel: ranger does primary caching slow due to calling `imagemagick`, but it does another caching (as for sixel atleast), for current running ranger instance so that sixel doesn't need to be generated every time image is previewed and as a result it is rendered instantly, whereas yazi regenerates sixel data every time
> 
> is this thing hard to implement? if not so, i can create feature request if needed

How ranger creates new sixel data on existing sixel data when the user terminal size changes? We can create sixel data on images that have already been downscaled, but we cannot create new sixel data on already encoded sixel data. This requires some form of reverse parsing of the sixel format

**Comment by sxyazi** [comment]
> > Does increasing the pre-cache image size help?
> > https://github.com/sxyazi/yazi/blob/ba0c860b2e4098318fb1a07f67ac81d7c08f230d/yazi-config/preset/yazi.toml#L17-L18
> 
> increased to 2000x2000. no change.

Hmm no more idea. All image processing is done in the [image.rs](https://github.com/sxyazi/yazi/blob/main/yazi-adaptor/src/image.rs) file, and then it's just [base64 encoded](https://github.com/sxyazi/yazi/blob/main/yazi-adaptor/src/kitty.rs) according to the Kitty documentation. I don't think the encoding would be any different for ranger.

**Comment by sxyazi** [comment]
Ah forgot to mention, have you changed the `image_quality` and `sixel_fraction`?

https://github.com/sxyazi/yazi/blob/ba0c860b2e4098318fb1a07f67ac81d7c08f230d/yazi-config/preset/yazi.toml#L20-L21

Docs here https://yazi-rs.github.io/docs/configuration/yazi#preview

**Comment by SolitudeSF** [comment]
yes, i didnt matter, because its not related.

**Comment by sxyazi** [comment]
Does this problem exist in other terminals like Konsole, WezTerm? Please try using the kitty old protocol to see if the problem still by changing:

https://github.com/sxyazi/yazi/blob/ba0c860b2e4098318fb1a07f67ac81d7c08f230d/yazi-adaptor/src/adaptor.rs#L86

to

```rust
			Emulator::Kitty => vec![Self::KittyOld],
```

**Comment by SolitudeSF** [comment]
With WezTerm or with KittyOld preview is correct.

**Comment by sxyazi** [comment]
Oh I see now. Ranger and Yazi use different kitty graphics protocols.

Ranger uses the classic protocol, which does not support tmux and lacks support for partial erasure (resulting in overlapping popup components and images).

And Yazi uses the new [Unicode placeholders](https://sw.kovidgoyal.net/kitty/graphics-protocol/#unicode-placeholders). The old protocol is currently only in use by a few old terminals and is expected to be deprecated in the future. So I guess this might be a bug related to kitty Unicode placeholders, and I'm not sure what Yazi can do about it.

**Comment by SolitudeSF** [comment]
Can this be isolated so it can be reported upstream? And can a config option be provided to override whatever graphics protocol is yazi selecting, so i dont have to run a patched version.

**Comment by sxyazi** [comment]
> Can this be isolated so it can be reported upstream?

I think you can reproduce it using the built-in `icat` command in Kitty:

```bash
kitten icat --unicode-placeholder image.jpg
```

> And can a config option be provided to override whatever graphics protocol is yazi selecting, so i dont have to run a patched version?

You can trick Yazi into using the `OldKitty` protocol through `TERM_PROGRAM` to start:

```bash
TERM_PROGRAM=ghostty yazi
```

**Comment by SolitudeSF** [comment]
thanks. reported upstream.

**Comment by SolitudeSF** [comment]
https://github.com/kovidgoyal/kitty/issues/7070#issuecomment-1913120358

i think that yazi shouldnt target image placeholders by default with kitty.

**Comment by sxyazi** [comment]
No, that's not feasible.

Yazi needs to partially erase the overlapping parts of the pop-up component with the image, [as I mentioned before](https://github.com/sxyazi/yazi/issues/577#issuecomment-1910251008), regular image display does not have this capability. See:

## Unicode placeholders: Correctly

![placeholders](https://github.com/sxyazi/yazi/assets/17523360/bb267341-b7d3-4fd5-8757-a22c1094c4e8)

## Classic protocol: The pop-up component is being covered by the image

![regular](https://github.com/sxyazi/yazi/assets/17523360/99c8ea83-ec42-41c4-bf18-88a8beaacf33)

## Classic protocol with `z=-1`: The image penetrates the pop-up component, becoming the background, incorrectly

![regular-with-z](https://github.com/sxyazi/yazi/assets/17523360/f11f6524-bd22-4cbc-80a9-468dfaca9e0b)
