### ISSUE TITLE
When a directory has been entered by way of zoxide, it should be selected in parent (left) column

### ISSUE THREAD

**Issue by knodalyte** [sxyazi/yazi#580]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.31.0

### Yazi version

yazi 0.2.2 (a19e263 2024-01-24)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

When I navigate to a directory, it is shown and highlighted in the parent column, but if I jump to a directory using zoxide, the highlighted directory is not updated in the parent column.

### Expected Behavior

Regardless of how I enter a directory, it should be shown and highlighted in the parent column.

### To Reproduce

Jump to a directory using zoxide. Note that the directory is not highlighted in the parent column.

### Configuration

Not relevant

**Comment by sxyazi** [comment]
Should be fixed in https://github.com/sxyazi/yazi/pull/581
