### ISSUE TITLE
[Feature request] Smarter conflict management in copy/paste action if file already exists at destination

### ISSUE THREAD

**Issue by freijon** [sxyazi/yazi#582]
### Is your feature request related to a problem? Please describe

Today, when you yank `file.ext` and paste it in a folder where a file with the same name already exists, the new file will be called `file_1.ext`. Most of the time I would prefer to overwrite. So the most efficient way would be to first delete the file in the destination, then insert the yanked file. But deleting a file first can have some disadvantages, e.g. you lose the history information of certain cloud integrations.

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

`yazi` should offer three options for all conflicts:

1. overwrite
2. rename
3. abort

With option *rename*, start a (bulk) rename before pasting where you can refine the filename(s) of the conflicting files to be inserted. Repeat if you enter names that already exist.

**Comment by sxyazi** [comment]
Please use `paste --force`, its behavior is consistent with what you described.

See the docs here https://yazi-rs.github.io/docs/configuration/keymap#operation

**Comment by freijon** [comment]
> Please use `paste --force`, its behavior is consistent with what you described.

Thank you. I know about this keymap, but it's not "smart". My feature request is to make it *smarter*, because I think the current UX is not great. I need to bind an extra key to Paste-Overwrite. And the `_1` extension is not great.

I think the file manager `vifm` has the perfect UX:
![example](https://user-images.githubusercontent.com/1387831/235599768-e77e1918-81b0-492a-b867-64e27c8ae94b.png)

**Comment by freijon** [comment]
I'd say it's **during** the copying process, but you could do it before when gathering the tasks. The popup shows up for every conflict.

Maybe a demo helps to visualise how `vifm` works in this context: https://asciinema.org/a/dMS6LaFdzDigMhgEq80nV8On7

- For the first conflicting file I choose "[r]ename" and choose file8.txt
- For the second conflicting file I choose [o]verwrite
