### ISSUE TITLE
Image preview does not scale on a 4k screen on Wezterm + Windows

### ISSUE THREAD

**Issue by RioNight** [sxyazi/yazi#583]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

wezterm 20230712-072601-f4abf8fd

### Yazi version

yazi 0.2.2 (a19e263 2024-01-24)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

When I view images on a 4k screen, the image preview is small, relative to the pane, as shown in the issue here: https://github.com/sxyazi/yazi/issues/479.
When viewing on the smae image on a normal screen, the image fits to the pane normally.

### Expected Behavior

The image should take up the size of the pane properly.

### To Reproduce

Windows + scoop install of yazi, pwsh, Wezterm

### Configuration

no config

**Comment by sxyazi** [comment]
Have you set [max_width and max_height](https://yazi-rs.github.io/docs/configuration/yazi#preview)?

**Comment by RioNight** [comment]
I don't. Do I need to? I thought it would scale according to the screen size.

**Comment by sxyazi** [comment]
Yes, please do.

BTW this is not the same issue as the one you mentioned.
