### ISSUE TITLE
Previewer Seek Broken

### ISSUE THREAD

**Issue by MinaMatta98** [sxyazi/yazi#588]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

alacritty 0.13.1 (fe2a3c56)

### Yazi version

yazi 0.2.2

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

The previewer does not seek beyond a single increment.

The last version where seek within preview (Ctrl-J, Ctrl-K) was v 0.1.5 of yazi-fm.

### Expected Behavior

Seek to EOF

### To Reproduce

Go to a previewed file and (Ctrl-J, Ctrl-K)  to preview. It will not move beyond a single increment.

**Comment by sxyazi** [comment]
See https://github.com/sxyazi/yazi/issues/461
