### ISSUE TITLE
at least 3 letters are needed to jump around directory that would make things easier.

### ISSUE THREAD

**Issue by allgoldore** [sxyazi/yazi#589]
### Is your feature request related to a problem? Please describe

![2024-01-27_21-01-59](https://github.com/sxyazi/yazi/assets/74093447/c53e2ac1-4015-49b4-ae87-dfff1f05f65b)

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I would apreciate if this feature be added like lf .(https://github.com/gokcehan/lf)

**Comment by sxyazi** [comment]
It's already there, see:

https://github.com/sxyazi/yazi/blob/c325c332de595d40ade79163050bfbe3d517e5c6/yazi-config/preset/keymap.toml#L141-L146
