### ISSUE TITLE
Yazi hang when enter a very large directory

### ISSUE THREAD

**Issue by trunglebka** [sxyazi/yazi#596]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

wezterm

### Yazi version

yazi 0.2.2 (68ffd82 2024-01-29)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

When entering a very large directory (contains 838684 .mp3 files) yazi hang and I can't do anything with it. 

### Expected Behavior

Working normally (for that large directory I really don't care much about detail of every file and just want to peek some of it since I can't read all of it)

### To Reproduce

using ya:
- Enter it directly by: `ya <very large dir>` - It will fully loaded (list files) after about 30s (not measured exactly). From this I can leave and re-enter the dir smoothly
- Enter it indirectly by: `ya <it's parent>` and then enter it by arrow keys, sometime it can list the files, sometime it freeze like the below image - about 13 minutes with 100% CPU
![image](https://github.com/sxyazi/yazi/assets/16150250/8b4ae70f-4174-4ea7-bb83-62046c426e30)

### Anything else?
The bigger problem is that it's very difficult to navigate to other files or directories when they are located beneath such a large directory.

**Comment by trunglebka** [comment]
Well, it was able to enter that directory after 14 minutes (approximated by CPU time since I'm not using it and it is almost 0% CPU now)
![image](https://github.com/sxyazi/yazi/assets/16150250/a12456cb-f12f-4540-96a3-ff605d42ed38)

**Comment by sxyazi** [comment]
I noticed that you are using the old version v0.2.1, please try if it exists in the latest version of v0.2.2, https://github.com/sxyazi/yazi/releases/tag/v0.2.2

**Comment by sxyazi** [comment]
Hi, I made a PR to fix this, let me know if it works for you, https://github.com/sxyazi/yazi/pull/599.

**Comment by trunglebka** [comment]
It's still, `yazi 0.2.2 (6735516 2024-01-29)`
![image](https://github.com/sxyazi/yazi/assets/16150250/b443012c-d5ce-4de7-bbc7-5bee1cbdbed8)

**Comment by sxyazi** [comment]
Weird, it works fine on my side...

Could you record a GIF so I can see what was happening?

**Comment by trunglebka** [comment]
Please see this video: https://1drv.ms/u/s!AjwpLQ8KafRujq4jOWTLlAJE-wSkdw?e=CRSFVM
At 10s from start, I entered the clips dir (the large one) by right arrow

**Comment by sxyazi** [comment]
What happens if you enter the `clips` directory directly through `yazi clips`? Please record a GIF.

Also, do a 'time ls -l clips > /dev/null' and paste the output here.

**Comment by sxyazi** [comment]
Let's merge that PR first.

**Comment by trunglebka** [comment]
`time ls -l clips > /dev/null` output:
```
ls --color=tty -l clips > /dev/null  12.65s user 3.74s system 99% cpu 16.396 total
```

Gif about enter the `clips` directly:
![ezgif com-animated-gif-maker](https://github.com/sxyazi/yazi/assets/16150250/fcd14074-7d89-442f-8f86-3de423a87fec)

**Comment by sxyazi** [comment]
Try this PR https://github.com/sxyazi/yazi/pull/607
