### ISSUE TITLE
[Feature request] Support variables in shell commands

### ISSUE THREAD

**Issue by freijon** [sxyazi/yazi#597]
### Is your feature request related to a problem? Please describe

Today it's not easy to use the file manager with shell commands. I think completions are on the way(?) but even with completions it would it can be tricky to get the command right.

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

It would be very handy if `yazi` would support placeholder variables.

Example to use the `file` command:

- Without placeholder variables:
  - Press shell command keybind (by default ":")
  - `file very_long_filename_which_is_hard_to_type.txt`
- With placeholder variables:
  - Move cursor to file you want to perform action on
  - Press shell command keybind (by default ":")
  - `file %f` (completes %f to file under cursor)

With only a few placeholder variables, `yazi` could become much more powerful. I like the basics for the `[opener]` config, but I'd like to see them extended a bit. Here some additional ideas, extending on `[opener]`:

- %f - File under cursor
- %f1, %f2, %f3, ... - File under cursor in Tab n (would be handy to make a quick diff with files in two tabs: `diff %f1 %f2` without having to select them)
- %d - Current directory
- %d1, %d2, %d3, ... - Current directory Tab n
- ... I'm sure there are other candidates that would be interesting.

### Describe alternatives you've considered

- File completion would help, but would never be as efficient as placeholder variables.
- You already have this more or less for `[opener]`, but supporting those in shell commands is much more flexible, no config files need to be edited

### Additional context

It certainly would make sense to align the variable names / behavior between shell commands and the `[opener]` config.

**Comment by freijon** [comment]
Also, I just noticed that with `[opener]` it's apparently not supported to select two files in two different tabs and open them. The variables only work on the current tab.

**Comment by sxyazi** [comment]
Sounds good to me. Does anyone want to give it a try?

**Comment by rplanchuelo** [comment]
I'd add select files %f, not only fle under cursor

**Comment by Vaisakhkm2625** [comment]
wait, isn't this already possible? mark files and give variables $1 $2 .. to for the completion

![image](https://github.com/sxyazi/yazi/assets/68694876/7d618783-bc29-4d7c-bac8-c64f1a12aa5c)

![image](https://github.com/sxyazi/yazi/assets/68694876/33e8e9c2-8da8-4f29-927b-5e7772c66776)

**Comment by sxyazi** [comment]
Ah I misunderstood the OP's meaning, yeah this is a supported feature.

Sorry for the confusion.

**Comment by Vaisakhkm2625** [comment]
> Ah I misunderstood the OP's meaning, yeah this is a supported feature.
> 
> Sorry for the confusion.

i came to this issue to ask, can i execute any command parallely on specified file? 
eg:

echo $1 -> 

echo file1
echo file2
echo file3 ...

**Comment by freijon** [comment]
While this is a good start, it's far from what I proposed. I can use these arguments when all files are on the same level but not:
- When the selected files are in different folders
- When the selected files are on different tabs (which is a very common case in my way of working, I heavily use tabs)

Also, what about my proposal of %d for the current directory?

I don't understand why this issue is being closed when only a small subset of the requested functionality is currently supported?

**Comment by sxyazi** [comment]
@Vaisakhkm2625 

`shell` command doesn't support parallelism atm. To avoid redundant writing, you can use a shell template like `shell 'your long command line'`.

---

@freijon 


Closing the issue because I think you and OP don't realize that `$` exists, there's no mention of it anywhere in this issue, and even I've forgotten about it - I've only ever used it in keybindings

As for the `%` proposal, I think it conflicts with `$`. Ideally there should only be one manifestation to avoid confusing users.

**Comment by sxyazi** [comment]
> - `%f` (File under cursor): Use the reserved `$0` instead - it's not supported yet, but I can add it if you need.

Done in https://github.com/sxyazi/yazi/pull/738 by @rrveex
