### ISSUE TITLE
Termux package

### ISSUE THREAD

**Issue by luisdavim** [sxyazi/yazi#598]
### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Hi, I'd like to see this project packaged in Termux and I've opened https://github.com/termux/termux-packages/issues/18935 but it seems there are some issues compiling the app for that platform.

**Comment by sxyazi** [comment]
I'll investigate it

**Comment by sxyazi** [comment]
Close this issue, and I will keep track on https://github.com/termux/termux-packages/issues/18935
