### ISSUE TITLE
In Linux Wayland, the ueberzugpp session malfunctions for alacritty and gnome terminal

### ISSUE THREAD

**Issue by royess** [sxyazi/yazi#603]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

alacritty 0.12.2, GNOME Terminal 3.49.92 (using VTE 0.74.0 +BIDI +GNUTLS +ICU +SYSTEMD)

### Yazi version

yazi 0.2.2 (a19e263 2024-01-24)

### Did you try the latest main branch to see if the problem has already been fixed?

Not tried, and I'll explain why below

### Describe the bug

For alacritty in Wayland, the image preview is not integrated into the terminal session. When selecting an image or a pdf, a standalone ueberzugpp session appears in the wrong position, and I have to manually switch back (e.g. by clicking it) to the alacritty session to continue navigating the files.

![Screenshot from 2024-01-30 15-04-15](https://github.com/sxyazi/yazi/assets/31059422/6f0670de-454e-452f-aea5-f92f9932c658)

Also, gnome terminal in Wayland also has a problem. No image preview appears.

The problem may be related to Wayland. In X11, it works fine in both alacritty and gnome terminal.

### Expected Behavior

behaves like the image preview demo

### To Reproduce

In Linux Wayland, open yazi from alacritty and preview an image.

### Configuration

no config

### Anything else?

wayland version: The X.Org Foundation Xwayland Version 23.2.0 (12302000)

**Comment by sxyazi** [comment]
ueberzugpp does not support using GNOME Terminal/Alacritty on Wayland with non-sway, hyprland, and wayfire environments:

Quoted from [README.md](https://github.com/jstkdng/ueberzugpp/blob/b5d00222e90476d346508af24055a926e6fe35b1/README.md?plain=1#L10):
> support for wayland: sway, hyprland and wayfire

Also see https://github.com/jstkdng/ueberzugpp/issues/154
