### ISSUE TITLE
Failed to build in path with `:`

### ISSUE THREAD

**Issue by xtexChooser** [sxyazi/yazi#605]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

Konsole

### Yazi version

.

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

```
xtex@xtex /m/s/o/h/y/yazi (main)> cargo build --release
error: failed to join paths from `$LD_LIBRARY_PATH` together

Check if any of path segments listed below contain an unterminated quote character or path separator:
    "/mnt/src/oS/home:xtexChooser/yazi/yazi/target/release/deps"
    "/opt/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib"
    "/opt/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib"

Caused by:
  path segment contains separator `:`
xtex@xtex /m/s/o/h/y/yazi (main) [101]> pwd
/mnt/src/oS/home:xtexChooser/yazi/yazi
```

### Expected Behavior

build properly

### To Reproduce

Create a directory with `:`, cd it, and build yazi.

**Comment by sxyazi** [comment]
This seems to be an issue with the build tool itself, as Yazi does not have specific restrictions on characters in the build path. I am not sure what Yazi can do in this case...
