### ISSUE TITLE
Flexoki theme

### ISSUE THREAD

**Issue by Reledia** [sxyazi/yazi#606]
### Will you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

I made this theme for yazi: [flexoki.yazi](https://github.com/Reledia/flexoki.yazi)

**Comment by sxyazi** [comment]
Awesome! Would you like to create a PR and add your repo to https://github.com/yazi-rs/themes?

**Comment by Reledia** [comment]
I think I did. First time doing a PR, let me know if something is wrong
