### ISSUE TITLE
Feature Request: Open with option in open --interactive menu.

### ISSUE THREAD

**Issue by helixoid** [sxyazi/yazi#608]
### Is your feature request related to a problem? Please describe

I want to open my manga collection with zathura as most of them are in **.cbz** format. When opening through yazi it simply just extracts them instead of opening as the `xdg-mime filetype` is `application/zip`.

**So, I can't make zathura default through xdg-mime as all archived format will start opening in zathura.**

**In Thunar, there is an context menu to open with other apps.**

I would really appreciate this feature in yazi. I really love this project and want to use it on daily basis.

Edit: I am able to open .cbz with zathura by defining:

```
[opener]
read = [
              { exec = 'zathura "$@"', block = true, for = "unix" },
]

[open]
rules = [
               { name = "*.cbz",             			use = [ "read", "reveal" ] },
               { name = "*.cbr",             			use = [ "read", "reveal" ] },
]
```
**But I have to remove { mime = "application/zip",      use = "extract" },**

### Will you be willing to contribute this feature?

Sorry I don't know how to code.

### Describe the solution you'd like

`Open with other application` option in **open --interactive menu**.

**Comment by helixoid** [comment]
Adding file allocations to the config might be a good option too like [ranger](https://wiki.archlinux.org/title/Ranger#File_association).

Like: `ext cbz = zathura "$@"`

**Comment by og900aero** [comment]
Try putting the mime zip back like this:

[open]
rules = [
               { name = "*.cbz",             			use = [ "read", "reveal" ] },
               { name = "*.cbr",             			use = [ "read", "reveal" ] },
               { mime = "application/zip",             	use = [ "extract", "reveal" ] },
]

This is how it will work, as it reads the data in order and selects the first match. Just like the firewall. In other words, it is worth putting the extensions first in the queue, and the mime ones at the end.

**Comment by sxyazi** [comment]
I think you just need to add `mime = 'application/zip'` below `*.cbz` to make it work, like this:

```toml
[opener]
read = [
  { exec = 'zathura "$@"', orphan = true, for = "unix" },
]

[open]
rules = [
  { name = "*.cbz", use = [ "read", "reveal" ] },
  { name = "*.cbr", use = [ "read", "reveal" ] },

  { mime = "application/zip", use = "extract" },
]
```

The default opener rules for Yazi are kept to a minimum since different users use different programs, making it challenging to cater to all user needs at the same time. So I encourage creating your own opener rules through the way above.

**Comment by helixoid** [comment]
It worked!
Thank you so much for the help <3.

Also, is there any way to access **MTP(Android) devices** and access the recycle bin without `cd into ~/.local/share/Trash` and restore what I deleted earlier.
