### ISSUE TITLE
Image preview bugged on ST

### ISSUE THREAD

**Issue by giuskywalker** [sxyazi/yazi#610]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

ST 0.9 with some patches

### Yazi version

yazi 0.1.5

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

The image preview looks buggy, blurry.

![2024-02-01_07-39-24](https://github.com/sxyazi/yazi/assets/83036320/c24234f8-d319-41d3-921f-0d2a7bbe9506)

### Expected Behavior

The image preview should work normally

### To Reproduce

Install ST, ueberzugpp, yazi and try to use image preview

### Configuration

no config

**Comment by sxyazi** [comment]
Hi! I noticed that you are using the old version v0.1.5, please try if it exists in the latest version of v0.2.2, https://github.com/sxyazi/yazi/releases/tag/v0.2.2

**Comment by giuskywalker** [comment]
> Hi! I noticed that you are using the old version v0.1.5, please try if it exists in the latest version of v0.2.2, https://github.com/sxyazi/yazi/releases/tag/v0.2.2

It's the latest available that i could install using pacman, when i arrive at my home i will test using this new version compiling from source.

**Comment by giuskywalker** [comment]
The issue does not happen when using yazi-git package from AUR.

**Comment by sxyazi** [comment]
Yeah, yazi-git is the latest version.

Nice to hear that your problem has been resolved. Let me close this issue then.
