### ISSUE TITLE
quick grid view

### ISSUE THREAD

**Issue by Vaisakhkm2625** [sxyazi/yazi#612]
### Is your feature request related to a problem? Please describe

# grid view

a simple toggleable grid view for files would be a great feature. This allow to select images much more quickly as we can preview files all at once.

here example how timg utility does this 
![image](https://github.com/sxyazi/yazi/assets/68694876/6b9c5497-00e3-45b5-a2dd-4c2f3b376a49)

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

a grid to show file name and it's preview. h,j,k,l can be used to navigate left down up right remaining all work the same, but remaining all key binds are same
![image](https://github.com/sxyazi/yazi/assets/68694876/477e77e9-308c-4823-9391-85cbfdb35cc9)

### Describe alternatives you've considered

![image](https://github.com/sxyazi/yazi/assets/68694876/1c70357c-ca10-44c5-b62a-7b153a615125)

sxiv has this feature nicely implemented. but as it is not in terminal, it can't be used over ssh.

we could make a plugin to communicate with sxiv or similar program and use it to select picture/pdf/file and give back the list to yazi.

**Comment by sxyazi** [comment]
I think this would require a considerable effort, but I don't have enough time. Without someone willing to drive it forward, it's challenging to make it a reality.

Perhaps I can provide the necessary APIs (file lists, key events, image rendering, etc.) in the future, and let the community implement it as a plugin efficiently.

Closing issue as not in plans, sorry.
