### ISSUE TITLE
selection with fzf, carried on yazi ?

### ISSUE THREAD

**Issue by evanescente-ondine** [sxyazi/yazi#613]
### Is your feature request related to a problem? Please describe

Hi,
i am a new user.
I find that selecting multiple things would be much easier with fzf, but I see that beside "jump fzf", it doesn't seem possible to configure that call to fzf (what it shoes), despite it taking the whole screen/terminal, so it wouldn't mess with the interface nor the keymap.

### Will you be willing to contribute this feature?

- [x] Yes, I'll give it a shot

### Describe the solution you'd like

I wish I could :
1. customize fzf called inside yazi
2. getting multi-selection with fzf, that all selected files or directories become selected in yazi when exiting fzf, then I would apply any mass action on them all.

Maybe it's already possible, I don't know.

**Comment by sxyazi** [comment]
Hi, I have reimplemented `fzf` as a built-in plugin, which will allow users to easily copy its code template and make any changes to fit their workflow, see https://github.com/sxyazi/yazi/pull/884 and https://github.com/sxyazi/yazi/issues/865 for details
