### ISSUE TITLE
Multiple source selection and collective action

### ISSUE THREAD

**Issue by evanescente-ondine** [sxyazi/yazi#614]
### Is your feature request related to a problem? Please describe

Hi,
i tried to browser across the distinction but do not understand what is the statute of cross-directory selection right now, is it a todo task or has it been ruled out by design/choice ? Currently if the collective action can't reach all selected files it's not very useful, for instance to move stuff elsewhere or delete it all at once.
Sorry if it's already been answered :smi

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Ideally it would work like broot's stage panel, albeit without the need for a panel. Select things would put them in a virtual directory of sort, then you do your action. to move that would be selection + yank + go inside the target directory, paste. If possible without the "yank", but it's your choice as I read, and not a big deal (one more letter argggggggg lol).
I would like a dialog to see what's been selected across directories (and tabs ? don't care, I don't use them);

**Comment by evanescente-ondine** [comment]
sorry, I see that it does work with fd. Just not with the normal navigation mode. It shouldn't be difficult to implement then ,

**Comment by sxyazi** [comment]
Hi, sorry for the delayed response.

Cross-directory operations were implemented in the past few days, in https://github.com/sxyazi/yazi/pull/693, you can now build from the latest main branch and try it out to see if it fits your workflow. I think it's very similar to the broot workflow you described, although I haven't used broot before :)
