### ISSUE TITLE
Alacritty Ueberzug++ Image Preview Stopped Working

### ISSUE THREAD

**Issue by Aparaxium** [sxyazi/yazi#615]
### What system are you running Yazi on?

6.7.2-arch1-2 X11

### What terminal are you running Yazi in?

alacritty 0.13.1

### Yazi version

yazi 0.2.2

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

For a while I had the image preview working just fine, but today it stopped working. I have not overwritten the default config file to my knowledge.

```
echo $TERM
alacritty
```
```
echo $TERM_PROGRAM
alacritty
```
```
echo $XDG_SESSION_TYPE
x11
```
```
pacman -Q | rg ueb
ueberzugpp 2.9.2-2
```

### Expected Behavior

Image preview works as expected.

### To Reproduce

Honestly I have no idea what caused it to break, looking for some direction to troubleshoot.

### Configuration

no config

### Anything else?

**Comment by og900aero** [comment]
Arch Linux is a rolling release type, so updates are constantly coming to it on a daily basis. Could it be that an update was run in the last day that affects this? What does /var/log/pacman.log show for the last 1-2 days?

**Comment by og900aero** [comment]
That's exactly why I left Arch Linux after 5 years, because I got tired of package breaks on a weekly/monthly basis...

**Comment by Aparaxium** [comment]
Forcing a rebuild on ueberzugpp with the latest dependencies fixes the issue. The ueberzugpp AUR package was updated to force a rebuild.
