### ISSUE TITLE
Sort_by function not work very well with hungarian letters

### ISSUE THREAD

**Issue by og900aero** [sxyazi/yazi#616]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

alacritty 0.11.0

### Yazi version

yazi 0.2.2 (e607943 2024-01-31)

### Did you try the latest main branch to see if the problem has already been fixed?

Not tried, and I'll explain why below

### Describe the bug

Yazi does not take into account accented characters when sorting files and folders. He always puts it at the bottom of the list, like this:

![screenshot_1706856499](https://github.com/sxyazi/yazi/assets/49487376/5e500061-0f38-4010-a07d-2f08f5ed3072)

### Expected Behavior

The correct order would be the following for accented characters (Hungarian):

Alpha
Átrium
Beta
.
Elemér
Érvényes
.
Hedvig
Ilona
Írott
.
Olga
Órmotlan
Öveges
Őzike
.
Ubul
Útvonal
Üveg
Űr
.

### To Reproduce

Create files:
Alpha
Átrium
Beta
Elemér
Érvényes
Hedvig
Ilona
Írott
Olga
Órmotlan
Öveges
Őzike
Ubul
Útvonal
Üveg
Űr

and the problem will be visible

### Configuration

```
[manager]
ratio          = [ 0, 2, 2 ]
# ratio          = [ 0, 2, 2 ]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true

```

**Comment by sxyazi** [comment]
This is the expected behavior, `Ö` and `O` are different characters. Isn't it more intuitive to separate them into distinct groups, just like Yazi is currently doing?

![1](https://github.com/sxyazi/yazi/assets/17523360/a745c8fe-75c9-4207-ba4f-fa627968236c)

**Comment by og900aero** [comment]
No, because for us Hungarians, the accents in the abc come in the line described above, we still look for these characters.

**Comment by sxyazi** [comment]
Added to the [Feature Requests](https://github.com/sxyazi/yazi/issues/51), closing in favor of that list.

**Comment by sxyazi** [comment]
Hi, this feature has now been implemented by @clispios in https://github.com/sxyazi/yazi/pull/1053! :tada:
