### ISSUE TITLE
Crashes everytime when terminal closes

### ISSUE THREAD

**Issue by bitterhalt** [sxyazi/yazi#618]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

Crashes on: **foot, kitty**

I tested same with **Alacritty** and it does not crash if I kill the terminal window

### Yazi version

yazi 0.1.5-1

### Describe the bug

Yazi dumps core every time when I exit the terminal where yazi live

### Expected Behavior

Should not crash with those terminal emulators

### To Reproduce

Open yazi in terminal

Kill the terminal

Yazi makes coredump

### Configuration

default

### Anything else?

https://github.com/sxyazi/yazi/assets/95308907/b376e63c-b5e8-449f-b3bb-79c6617a01d4

**Comment by sxyazi** [comment]
Hi! I noticed that you are using the old version v0.1.5, please try if it exists in the latest version of v0.2.2, https://github.com/sxyazi/yazi/releases/tag/v0.2.2

**Comment by bitterhalt** [comment]
> Hi! I noticed that you are using the old version v0.1.5, please try if it exists in the latest version of v0.2.2, https://github.com/sxyazi/yazi/releases/tag/v0.2.2

Thank you. Seems like that the versions in arch repos and AUR are very outdated so I test when it is updated.

**Comment by sxyazi** [comment]
You can use `yazi-git` to install the latest main branch, see https://yazi-rs.github.io/docs/installation#arch-linux

**Comment by sxyazi** [comment]
You can use `yazi-git` to install the latest main branch, see https://yazi-rs.github.io/docs/installation#arch-linux

**Comment by bitterhalt** [comment]
> You can use `yazi-git` to install the latest main branch, see https://yazi-rs.github.io/docs/installation#arch-linux

Git version does not crash, so I close this know. Thank you for helping!
