### ISSUE TITLE
Y/n confirmation dialogues shouldn't require pressing enter

### ISSUE THREAD

**Issue by jyothisv** [sxyazi/yazi#624]
### Is your feature request related to a problem? Please describe

Generally in shells, answering y/n dialogues require only one key-press. However, in Yazi, we need to press two keys (y/n and then enter).

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

In Yazi, there seems to be only one way to accept keyboard input from the user.  We need another dialogue box for single letter inputs.

**Comment by sxyazi** [comment]
Hi! You can bind `dy ==> remove --force` to achieve this (`dy` means delete and yes).

See the docs here https://yazi-rs.github.io/docs/configuration/keymap#remove

**Comment by jyothisv** [comment]
> Hi! You can bind `dy ==> remove --force` to achieve this (`dy` means delete and yes).
> 
> See the docs here https://yazi-rs.github.io/docs/configuration/keymap#remove

I know this is a minor issue, but `remove --force` is not having confirmation at all. I would like to have a confirmation. It just seems an overkill to require two keypresses for a single letter response.

**Comment by sxyazi** [comment]
All inputs require `Enter` confirmation, but the most dangerous deletion doesn't.

I think this inconsistency might confuse users, and they could easily forget about this behavior since each input looks too similar.

**Comment by jyothisv** [comment]
> All inputs require `Enter` confirmation, but the most dangerous deletion doesn't.
> 
> I think this inconsistency might confuse users, and they could easily forget about this behavior since each input looks too similar.

A fair point. The current behavior does make sense in that way.

My use case is  cleaning up directories with a large number of not-so-important files. This might involve repeated deletions. Asking confirmation is still important to avoid accidental deletions, but always having to press `Enter` would be cumbersome.

**Comment by sxyazi** [comment]
You can press `Space` to select multiple files and then delete them all at once.

Alternatively, you can also press `v` to enter visual mode, batch-select entire sections of files, and delete them all at once.

**Comment by sxyazi** [comment]
BTW, I plan to expose the input component as an API. At that time, if you really need it, you can implement it with just a few lines of code. It will be as simple as https://yazi-rs.github.io/docs/tips#smart-enter-enter-for-directory-open-for-file.

**Comment by jyothisv** [comment]
> BTW, I plan to expose the input component as an API. At that time, if you really need it, you can implement it with just a few lines of code. It will be as simple as https://yazi-rs.github.io/docs/tips#smart-enter-enter-for-directory-open-for-file.

Sounds great, thanks!

**Comment by jyothisv** [comment]
> BTW, I plan to expose the input component as an API. At that time, if you really need it, you can implement it with just a few lines of code. It will be as simple as https://yazi-rs.github.io/docs/tips#smart-enter-enter-for-directory-open-for-file.

A related question: is there a way to open only the current file even when there is a selection?

**Comment by sxyazi** [comment]
Not supported yet, but we can add it, something like `open --hovered`

**Comment by sxyazi** [comment]
> Not supported yet, but we can add it, something like `open --hovered`

Done by https://github.com/sxyazi/yazi/issues/673
