### ISSUE TITLE
New command: compress

### ISSUE THREAD

**Issue by rplanchuelo** [sxyazi/yazi#626]
### Is your feature request related to a problem? Please describe

I would like to compress several selected files into one file, the name of the new compressed file would be a parameter 

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

You could use the atool that contains many elements:
- apack to compress
- als for listing 
- aunpack to extract 
unarchiver (unar) could be substituted by atool 

### Additional context

It's in Ranger (python)

**Comment by TornaxO7** [comment]
I'd recommend to use [`ouch`](https://github.com/ouch-org/ouch)! It's basically an all-in-one (de)compress tool!

**Comment by rplanchuelo** [comment]
Ouch is in Rust, maybe it is easier folk it into yazi to build this new feature

**Comment by sxyazi** [comment]
Hi! Would you like to implement it as a plugin?

Once it's stable enough, it can be seamlessly integrated into Yazi as a built-in plugin (similar to existing plugins like image preview, code highlighting, folder preview, etc. – all of which are built-in plugins).

In Yazi, plugins are treated as first-class citizens, just like commands, but offering greater flexibility.

**Comment by rplanchuelo** [comment]
I could do with a file with cx.active.current.hovered, but I dont know if it is possible with a range of select files

**Comment by rplanchuelo** [comment]
Command function doesn`t work for me. Error:

  2024-02-05T17:45:09.863472Z ERROR yazi::app::commands::plugin: runtime error: [string "/home/rober/.cargo/registry/src/index.crates...."]:10: attempt to call a nil value (global 'Command')
stack traceback:
	[C]: in global 'Command'
	[string "/home/rober/.cargo/registry/src/index.crates...."]:10: in function <[string "/home/rober/.cargo/registry/src/index.crates...."]:4>
    at /home/rober/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yazi-fm-0.2.2/src/app/commands/plugin.rs:52

_local child = os.execute(cmd)_ work
_local child = Command(cmd)_ doesn't work (error)

And args in  plugin test --sync --args='foo bar' change the string to hexadecimal code

**Comment by sxyazi** [comment]
> I could do with a file with cx.active.current.hovered, but I dont know if it is possible with a range of select files

I will add this API in the next target. For now you can use `manager_emit("shell")` to implement it, like this https://github.com/sxyazi/yazi/issues/51#issuecomment-1763697521

See the docs here https://yazi-rs.github.io/docs/plugins/utils/#manager_emitcmd-args-data

**Comment by bertradio** [comment]
I use this in keymap.toml to compress the selected files with 7z:

[[manager.prepend_keymap]]
on = ["c", "s"]
run = """ shell 'echo; printf ">>> Zip name (no ext): "; read name; 7z a "$name.zip" "$@"; 7z t "$name.zip"; read p' --block --confirm
"""
desc = "Zip selected"

**Comment by sxyazi** [comment]
Hi, @KKV9 just made a plugin for it, https://github.com/KKV9/archive.yazi 🎉
