### ISSUE TITLE
Error during a `trash` operation: [...] PermissionDenied

### ISSUE THREAD

**Issue by nivit** [sxyazi/yazi#638]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 0.31.0

### Yazi version

yazi 0.2.3 (tested also with 0.2.2)

### Did you try the latest main branch to see if the problem has already been fixed?

Not tried, and I'll explain why below

### Describe the bug

It is impossible to move any file to trash, because the task fails with the error:

```
Failed to work on this task: Error during a `trash` operation: FileSystem { path: "/usr/home/.Trash-1001", source: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }
```

Maybe the problem is that `yazi` tries to create the directory `Trash-*` under `/usr/home`, where the user doesn't have permissions? Note that in FreeBSD `/home` is a soft link to `/usr/home`.

### Expected Behavior

Move the file to the trash.

### To Reproduce

Choose a file, press `d` (answer `y`), then `w` and `Enter` to see why the task fails.

### Configuration

no config

**Comment by sxyazi** [comment]
> Maybe the problem is that yazi tries to create the directory Trash-* under /usr/home, where the user doesn't have permissions?

Yes, according to [the FreeDesktop.org Trash specification](https://specifications.freedesktop.org/trash-spec/trashspec-1.0.html), Yazi must create the corresponding `.Trash-$uid` directory under `$topdir`:

> When trashing a file, if an $topdir/.Trash-$uid directory does not exist, the implementation MUST immediately create it, without any warnings or delays for the user.

Is `/usr/home` the mount point for your system (or the default for FreeBSD)? I'm not familiar with FreeBSD.

> Top directory , $topdir — the directory where a file system is mounted. “/” is the top directory for the root file system, but not for the other mounted file systems. For example, separate file systems might be mounted on “/home”, “/media/flash”, etc. In this text, the designation “$topdir” is used for “any top directory”.

**Comment by nivit** [comment]
Thanks for the answer and the links, and yes `/usr/home` is a "root" mount point on my system. However, reading this excerpt from that Trash specification
```
"For every user a “home trash” directory MUST be available.
Its name and location are $XDG_DATA_HOME/Trash; $XDG_DATA_HOME is the base directory
for user-specific data, as defined in the Desktop Base Directory Specification.

The “home trash” SHOULD function as the user's main trash directory. Files that the user trashes
from the same file system (device/partition) SHOULD be stored here.
```

it seems to me that the "trash home" for a simple user should be `~/.local/share/Trash`. Though other file managers have their own directory, for example `vifm` save files under `~/.local/share/vifm/Trash`. So I don't know...

**Comment by sxyazi** [comment]
Oh I see. Would you like to file an issue for [trash crate](https://github.com/Byron/trash-rs)? This issue needs to be fixed upstream.
