### ISSUE TITLE
weird tmux behavior

### ISSUE THREAD

**Issue by Korygauger** [sxyazi/yazi#641]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

Kitty 0.30.1

### Yazi version

yazi 0.2.3 (VERGEN_IDEMPOTENT_OUTPUT 2024-02-07)

### Did you try the latest main branch to see if the problem has already been fixed?

Not tried, and I'll explain why below

### Describe the bug

I opened yazi in tmux because I was messing with the config in a session and just scrolling through the items in my folders makes things randomly open in whatever application they need to be opened in. If I open it in a normal terminal it works fine, maybe tmux is adding new inputs that I can't see?

### Expected Behavior

just scroll through content normally

### To Reproduce

open up yazi in a tmux session and scroll over open-able files and it should reproduce. It could be just me though.

### Configuration

I haven't actually changed anything in the configs yet so it works with the default.

### Anything else?

I did a cargo build so I wasn't able to test the very latest version but maybe I should go ahead and install from source. Great work btw guys I wanted a good alternative to ranger because rangers themeing options suck and it seems like you got something good here.

**Comment by Korygauger** [comment]
@sxyazi sorry for the late reply ended up with a ton of assignments this week. Yes it the bug still occurs when I open it up with the command you posted. Maybe try and create a folder with just pdfs in it and spam j and k cause I don't even have to try to get it to behave weird. If I have time later I will do a short video showing what it does.

**Comment by sxyazi** [comment]
What's your tmux version? Have you set your tmux as per our docs https://github.com/sxyazi/yazi/wiki/Image-preview-within-tmux here?

**Comment by Korygauger** [comment]
I have not let me try that.

**Comment by Korygauger** [comment]
@sxyazi I get an error invalid option: allow-passthrough and the bug is still there

**Comment by sxyazi** [comment]
What's your tmux version?

**Comment by Korygauger** [comment]
3.2a

**Comment by sxyazi** [comment]
tmux 3.2a does not support passthrough mode, which is an option introduced in tmux 3.3, see https://raw.githubusercontent.com/tmux/tmux/3.3/CHANGES:

```
CHANGES FROM 3.2a TO 3.3
...
* Add an option (default off) to control the passthrough escape sequence.
```

Please upgrade your tmux to the latest version.
