### ISSUE TITLE
Vim scrolling

### ISSUE THREAD

**Issue by Korygauger** [sxyazi/yazi#642]
### Is your feature request related to a problem? Please describe

n/a

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

In vim you can scroll a specified number of lines by hitting the number keys and then j or k. It would be cool to be able to do that. It would be better to add relative line numbers alongside this though because it would be difficult to use without them.

### Describe alternatives you've considered

n/a

**Comment by BigLadDylan** [comment]
I too would like this feature! #698

**Comment by Sonico98** [comment]
There's a plugin that does that, it's just missing the line numbers for now: https://github.com/dedukun/relative-motions.yazi

**Comment by dedukun** [comment]
Hey, I had some time today and updated [relative-motions.yazi](https://github.com/dedukun/relative-motions.yazi). I've fixed a couple of issues and added the line numbers, as well as a README with some instructions.

If someone is still interested, you can check it out.

**Comment by sxyazi** [comment]
Awesome, thank you for your work on this plugin! @dedukun

**Comment by sxyazi** [comment]
I tested [relative-motions.yazi](https://github.com/dedukun/relative-motions.yazi), and it works quite well. I think we can close this issue now.
