### ISSUE TITLE
Treesitter support

### ISSUE THREAD

**Issue by kflak** [sxyazi/yazi#648]
### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Hi,

Is there any way to use treesitter for syntax highlighting? That way one would get good syntax highlighter for a whole bunch of languages out of the box...

### Describe alternatives you've considered

I was thinking of using nvim as a previewer, but haven't yet managed to get this working. It's also not a very portable solution...

**Comment by sxyazi** [comment]
Yeah you can, but why - is the current built-in code highlighting in Yazi not meeting your needs?

If you really need it, there's a CLI command in treesitter called [`tree-sitter highlight`](https://github.com/tree-sitter/tree-sitter/blob/master/cli/README.md) that you can use to create a previewer for it - just copy https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/plugins/json.lua as your `~/.config/yazi/plugins/my-previewer.yazi/init.lua` then change `jq` to `tree-sitter`

Document here https://yazi-rs.github.io/docs/configuration/yazi#previewers and https://yazi-rs.github.io/docs/plugins/overview#previewer

**Comment by kflak** [comment]
The reason I'm asking is that I'm missing syntax highlighting for supercollider files... Will give tree-sitter cli a go, thanks for the tip!
