### ISSUE TITLE
Enable the ability to sort the which key

### ISSUE THREAD

**Issue by taylo2allen** [sxyazi/yazi#652]
### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

In the yazi.toml add [which] that has the methods sort_by & sort_sensitive that allows you to sort the which menu.

### Describe alternatives you've considered

One way for me to sort the which menu is to physically go to my keymap.toml and sort my keybinding definitions.

**Comment by sxyazi** [comment]
Sounds good to me. Does anyone want to give it a try?

**Comment by abhaysp95** [comment]
@taylo2allen I completed the rust basics and I have just started using Yazi. I would like to help. I want to understand few points for this issue:
* What is meant by sorting the which key ?
* Currently, sort_by & sort_sensitive option are under [manager]. What is wanted is to created a new table named [which] ?
* Can you kindly show the steps of what you are doing for 'alternatives' you mentioned

CC: @sxyazi

**Comment by sxyazi** [comment]
Thank you very much for the help! @abhaysp95

I'll wait for OP's reply and provide more detailed suggestions on how to implement it :)

**Comment by taylo2allen** [comment]
I have a lot of keykindings to move to different folders on my system for example:
`
	{ on = [ "g", "C" ], exec = "cd ~/.config", desc = "GoTo: ~/.config" },
	{ on = [ "g", "c", "b" ], exec = "cd ~/.config/xmobar", desc = "GoTo: ~/C/xmobar" },
	{ on = [ "g", "c", "f" ], exec = "cd ~/.config/fish", desc = "GoTo: ~/C/fish" },
	{ on = [ "g", "c", "q" ], exec = "cd ~/.config/qutebrowser", desc = "GoTo: ~/C/qutebrowser" },
	{ on = [ "g", "c", "r" ], exec = "cd ~/.config/ranger", desc = "GoTo: ~/C/ranger" },
	{ on = [ "g", "c", "x" ], exec = "cd ~/.config/xmonad", desc = "GoTo: ~/C/xmonad" },

`
in the code above I use "g", "c" as a leader key to go to all of the folders I have bookmarked in my .config folder. When I press the "g" key the whichkey menu pops up with the next possible keys you can press, I would like to sort the options for keybindings like "c", "b" to be shown first before "c", "x". The only way I found to sort the list of keybindings is to shift the definitions around in my keymap.toml file.
![2024-02-10_20-59](https://github.com/sxyazi/yazi/assets/15933691/45ab3013-75f1-4675-832b-2c1b263bb0b7)

**Comment by abhaysp95** [comment]
@taylo2allen  Okay. So this has nothing to do with sorting options present under [manager]. Got it.

* sort_by can only have "alphabetically" and "alphabetically (reverse)', right ? or do you have some more options in mind ?

@sxyazi I'm going through the source code, I'll try to implement it in the free time I get between my work. This is a nice project and looks like a fun way to get good with Rust.

**Comment by taylo2allen** [comment]
What file deals with printing the possible keys to the screen?

**Comment by taylo2allen** [comment]
Thank you for taking a look @sxyazi @abhaysp95 I believe this would be possible to implement this feature with the sort function found in yazi-core/src/folder/sorter.rs instead of feeding two files into the sort fn you can pass two items in the list of possible keybindings before the text can be displayed on the screen.

**Comment by sxyazi** [comment]
>  I'm going through the source code, I'll try to implement it in the free time I get between my work. This is a nice project and looks like a fun way to get good with Rust.

Thanks.

> I believe this would be possible to implement this feature with the sort function found in yazi-core/src/folder/sorter.rs instead of feeding two files into the sort fn you can pass two items in the list of possible keybindings before the text can be displayed on the screen.

No, it's a file-specific sorting, not applicable to keys, as keys don't have file-specific attributes like modification time, creation time, extension, etc., and they are also hard to share. Therefore, the simplest way is to directly invoke [`natsort`](https://github.com/sxyazi/yazi/blob/b6f572ececa92ee1c69312e1a9e5043db117c5b5/yazi-shared/src/natsort.rs#L67-L67) function to sort.

We can add the sorting logic after

https://github.com/sxyazi/yazi/blob/b6f572ececa92ee1c69312e1a9e5043db117c5b5/yazi-core/src/which/commands/show.rs#L48-L53


It's the only place that needs to change, with:

- `sort_by` (String): `"key"` or `"description"`
- `sort_sensitive` (Boolean): Whether sort case-sensitively

**Comment by abhaysp95** [comment]
@taylo2allen I have created the PR #662 . You can try to confirm the behaviour if it fits you

CC: @sxyazi
