### ISSUE TITLE
Type annotations for Lua

### ISSUE THREAD

**Issue by UtkarshVerma** [sxyazi/yazi#657]
### Is your feature request related to a problem? Please describe

When defining the configuration in Lua, I have to hop between my editor and the docs. Having type annotations for classes and functions in the code base would greatly help this.

For example, users can hover over the function or class and get up-to-date information about them through language servers like [lua-language-server](https://github.com/LuaLS/lua-language-server).

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

The Neovim ecosystem has already embraced the [LuaCATS annotations](https://luals.github.io/wiki/annotations/) and it would fit in this project as well.

**Comment by teto** [comment]
if sxyazi agrees, would you be ready to contribute those annotations ? I find them quite powerful in the neovim ecosystem

**Comment by sxyazi** [comment]
I agree, this is a great improvement for plugin development experience, but I don't have enough time to maintain another set of type definitions besides documentation. I would be very grateful if someone is willing to help maintain them 🙏🏻

**Comment by sxyazi** [comment]
Closing as not in the plan

**Comment by sxyazi** [comment]
Now it's supported! 🎉 🎉 

https://github.com/yazi-rs/plugins/tree/main/types.yazi

It's generated from the documentation so that I can still only maintain one copy to reduce the workload :)
