### ISSUE TITLE
Yazi does not preview via Ueberzug, even though ueberzug layer command works

### ISSUE THREAD

**Issue by swishkin** [sxyazi/yazi#658]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

st

### Yazi version

yazi 0.2.3 (20b6f26 2024-02-09)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

When navigating a folder containing image files (PNG and JPG), Yazi does not show a preview for the selected image.

### Expected Behavior

Yazi should show previews for known image files in the right section.

### To Reproduce

On an Arch-based system, install the yazi-git package from the AUR, or install the current git version via `cargo build --release`. 

Open Yazi via `yazi` or `./target/release/yazi` and navigate to a folder containing images.

Yazi fails to show previews for any images.

### Configuration

```
[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]
...
previewers = [
	{ name = "*/", exec = "folder", sync = true },
	# Code
	{ mime = "text/*",                 exec = "code" },
	{ mime = "*/xml",                  exec = "code" },
	{ mime = "*/javascript",           exec = "code" },
	{ mime = "*/x-wine-extension-ini", exec = "code" },
	# JSON
	{ mime = "application/json", exec = "json" },
	# Image
	{ mime = "image/vnd.djvu", exec = "noop" },
	{ mime = "image/*",        exec = "image" },
	# Video
	{ mime = "video/*", exec = "video" },
	# PDF
	{ mime = "application/pdf", exec = "pdf" },
	# Archive
	{ mime = "application/zip",             exec = "archive" },
	{ mime = "application/gzip",            exec = "archive" },
	{ mime = "application/x-tar",           exec = "archive" },
	{ mime = "application/x-bzip",          exec = "archive" },
	{ mime = "application/x-bzip2",         exec = "archive" },
	{ mime = "application/x-7z-compressed", exec = "archive" },
	{ mime = "application/x-rar",           exec = "archive" },
	{ mime = "application/xz",              exec = "archive" },
	# Fallback
	{ name = "*", exec = "file" },
]
```

### Anything else?

I'm running Artix Linux, st, dwm, picom, zsh, and have ueberzug installed via either pacman or yay (can't remember).

I tried installing yazi through both `yay` and `git clone` + `cargo build --release`, with `pacman -R yazi` between the two attempts.

Running the ueberzug layer command with the filename replaced with an existing PNG on my system works fine.

**Comment by swishkin** [comment]
`st-256color, , tty`

Does $TERM_PROGRAM need to be defined in zshrc or xprofile...or something else?

**Comment by sxyazi** [comment]
Why your `XDG_SESSION_TYPE` is `"tty"` rather than `"x11"`?

Please also do an `echo $WAYLAND_DISPLAY, $DISPLAY` and paste the output here.

**Comment by og900aero** [comment]
> Why your `XDG_SESSION_TYPE` is `"tty"` rather than `"x11"`?
> 

I think he/she uses tiling window manager. I try with my config, and show tty value too. And I use bspwm. Tried dk tiling windows manager, and also show tty value.

**Comment by swishkin** [comment]
```
echo $WAYLAND_DISPLAY, $DISPLAY
, :0
```

No Wayland output probably because I'm on X11.

**Comment by sxyazi** [comment]
Any content in `~/.local/state/yazi/yazi.log`?

**Comment by swishkin** [comment]
I'm on a different computer with the same OS, WM, and terminal, trying to install from source, but it seems like I made a mistake, because it's failing to find the plugins when I try to launch it.

```
  [2m2024-02-13T15:21:31.640855Z[0m [31mERROR[0m [1;31myazi_plugin::isolate::peek[0m[31m: [31mplugin not found: ueberzugpp layer[0m
    [2;3mat[0m yazi-plugin/src/isolate/peek.rs:50

  [2m2024-02-13T15:21:31.644025Z[0m [31mERROR[0m [1;31myazi_scheduler::preload::preload[0m[31m: [31mPreload task `image` returned 2[0m
    [2;3mat[0m yazi-scheduler/src/preload/preload.rs:42

  [2m2024-02-13T15:21:31.644510Z[0m [31mERROR[0m [1;31myazi_scheduler::preload::preload[0m[31m: [31mPreload task `image` returned 2[0m
    [2;3mat[0m yazi-scheduler/src/preload/preload.rs:42

  [2m2024-02-13T15:21:31.645006Z[0m [31mERROR[0m [1;31myazi_scheduler::preload::preload[0m[31m: [31mPreload task `image` returned 2[0m
    [2;3mat[0m yazi-scheduler/src/preload/preload.rs:42

  [2m2024-02-13T15:21:31.645901Z[0m [31mERROR[0m [1;31myazi_scheduler::preload::preload[0m[31m: [31mPreload task `image` returned 2[0m
    [2;3mat[0m yazi-scheduler/src/preload/preload.rs:42

  [2m2024-02-13T15:21:32.148947Z[0m [31mERROR[0m [1;31myazi_plugin::isolate::peek[0m[31m: [31mplugin not found: ueberzugpp layer[0m
    [2;3mat[0m yazi-plugin/src/isolate/peek.rs:50

  [2m2024-02-13T15:21:32.695115Z[0m [31mERROR[0m [1;31myazi_plugin::isolate::peek[0m[31m: [31mplugin not found: ueberzugpp layer[0m
    [2;3mat[0m yazi-plugin/src/isolate/peek.rs:50

  [2m2024-02-13T15:21:40.207628Z[0m [31mERROR[0m [1;31myazi_plugin::isolate::peek[0m[31m: [31mplugin not found: ueberzugpp layer[0m
    [2;3mat[0m yazi-plugin/src/isolate/peek.rs:50

  [2m2024-02-13T15:21:40.208648Z[0m [31mERROR[0m [1;31myazi_scheduler::preload::preload[0m[31m: [31mPreload task `image` returned 2[0m
    [2;3mat[0m yazi-scheduler/src/preload/preload.rs:42

  [2m2024-02-13T15:21:40.208659Z[0m [31mERROR[0m [1;31myazi_scheduler::preload::preload[0m[31m: [31mPreload task `image` returned 2[0m
    [2;3mat[0m yazi-scheduler/src/preload/preload.rs:42

  [2m2024-02-13T15:21:40.208768Z[0m [31mERROR[0m [1;31myazi_scheduler::preload::preload[0m[31m: [31mPreload task `image` returned 2[0m
    [2;3mat[0m yazi-scheduler/src/preload/preload.rs:42

  [2m2024-02-13T15:21:40.208805Z[0m [31mERROR[0m [1;31myazi_scheduler::preload::preload[0m[31m: [31mPreload task `image` returned 2[0m
    [2;3mat[0m yazi-scheduler/src/preload/preload.rs:42
```

I'm going to try installing via yay (AUR) again. I didn't try this earlier because I was seeing 0.1.5 on there and it wasn't even using ueberzug.

**Comment by Rolv-Apneseth** [comment]
After a `cargo build --release` the binary should be at `target/release/yazi` so if you want to install that manually you'd put it somewhere on your `$PATH` like `/usr/bin/`.

If you're just testing if it works differently from the version downloaded from the AUR though just do `./target/release/yazi` like the guide suggests to run it without moving it anywhere.

**Comment by sxyazi** [comment]
I think this is because you modified the default previewers. According to the log, you added a plugin named “ueberzugpp layer” as the previewer, but it does not exist. 

Please delete your “yazi.toml” and try again with the default configuration to see if it works.

**Comment by swishkin** [comment]
I think you're correct! After deleting yazi.toml and restarting yazi, it's working as expected. Thanks for your quick responses and for bearing with me!

**Comment by sxyazi** [comment]
nice to hear your problem got resolved, closing this issue then
