### ISSUE TITLE
Sort with dotfiles at the end

### ISSUE THREAD

**Issue by Yair-Ziv** [sxyazi/yazi#666]
### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I'd like to have an option in the [manager] area of the yazi.toml that declares whether dotfiles come before normal files or after

Right now with configuration of alphabetical, sort_dir_first I get
Alphabetical dotdirectories
Alphabetical directories
Alphabetical dotfiles
Alphabetical files

When I would have liked to get 
Alphabetical directories
Alphabetical dotfiles
Alphabetical files
Alphabetical dotfiles

**Comment by sxyazi** [comment]
I prefer not to add it because I don't see a use case for it. I did a quick search on two popular file managers ranger and lf and neither of them supports it.

Closing as it's not in the plan, sorry.
