### ISSUE TITLE
show git status icons

### ISSUE THREAD

**Issue by cap153** [sxyazi/yazi#668]
### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

![image](https://github.com/sxyazi/yazi/assets/67049883/63efb270-1ad7-45ea-8861-31dfe47fc168)

ranger can show this, this is useful. I hope yazi also do this! 0^0

**Comment by sxyazi** [comment]
It is already in [Feature Requests](https://github.com/sxyazi/yazi/issues/51), I haven't found time to impl it
