### ISSUE TITLE
Add a new option `--hovered` to the `open` command allowing users to only open the currently hovered file

### ISSUE THREAD

**Issue by sxyazi** [sxyazi/yazi#673]
I am posting some simple tasks here as "good first issues" that don't require too much of my attention.

I need to allocate my limited time to tasks that require my direct involvement.

---

Does anyone want to give it a try? The `open` command file is https://github.com/sxyazi/yazi/blob/main/yazi-core/src/manager/commands/open.rs

**Comment by abhaysp95** [comment]
When I move to a file and press 'o' (bind to open command), it opens the file for me. What does `hovered` file means here ?

**Comment by sxyazi** [comment]
If some files are selected, it will `open` the selected files instead of the hovered file.

`--hovered` will always open the hovered file regardless of the selection state.

**Comment by evpeople** [comment]
Hi ,

I came across the "good first issue" regarding adding a new `--hovered` option to the open command, allowing users to only open the currently hovered file. I'm very interested in tackling this issue and would like to give it a try.

I believe I understand the requirements and have a preliminary idea of how to approach the solution. However, I'm open to any suggestions or guidance you might have to offer.

Please let me know if there's any additional information or specific guidelines I should follow while working on this issue.

Looking forward to contributing to yazi!

Best regards

**Comment by fakerepic** [comment]
> Hi ,
> 
> I came across the "good first issue" regarding adding a new `--hovered` option to the open command, allowing users to only open the currently hovered file. I'm very interested in tackling this issue and would like to give it a try.
> 
> I believe I understand the requirements and have a preliminary idea of how to approach the solution. However, I'm open to any suggestions or guidance you might have to offer.
> 
> Please let me know if there's any additional information or specific guidelines I should follow while working on this issue.
> 
> Looking forward to contributing to yazi!
> 
> Best regards

Hi, I happen to have already done this just now before seeing your reply, but haven't made a pull request yet [(check this)](https://github.com/fakerepic/yazi/commit/4f87c887e25152de4e659b74fefd0ce0accfa532). i think my implementation should match the requirements, hope you can point out more suggestions!

**Comment by fakerepic** [comment]
@sxyazi  Okay, thanks! https://github.com/sxyazi/yazi/pull/687

**Comment by sxyazi** [comment]
Done by @fakerepic in https://github.com/sxyazi/yazi/pull/687, thanks!
