### ISSUE TITLE
flat view

### ISSUE THREAD

**Issue by finviman** [sxyazi/yazi#676]
### Is your feature request related to a problem? Please describe

no

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

show all files in a folder with a flat level.

**Comment by sxyazi** [comment]
It's already supported via [`fd`](https://github.com/sharkdp/fd) by searching with an empty (`""`) keyword, see:

https://github.com/sxyazi/yazi/assets/17523360/d2c9df9b-b7ef-41ec-889f-26b2f1117cd0

The `search` command docs: https://yazi-rs.github.io/docs/configuration/keymap/#search
