### ISSUE TITLE
Yazi got showing folders in unorganized way 

### ISSUE THREAD

**Issue by AnkurAlpha** [sxyazi/yazi#681]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot

### Yazi version

0.2.3

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

The file manager is now showing files and folder in not properly arranged way, in version `0.1.5-1`  it was looking like this 
![2024-02-15T11:26:37,834938812+05:30](https://github.com/sxyazi/yazi/assets/132189303/674dd639-b61b-468d-8d2f-49622e45c5e8)
But now it looks like this : 
![2024-02-15T11:27:53,925230897+05:30](https://github.com/sxyazi/yazi/assets/132189303/607a8f74-ba16-4af6-bd82-134bb5536983)
While looking at files it makes it hard to find a to which I am looking.

Please make it rearranged again .
 Thanks 😄 !!

### Expected Behavior

in version `0.1.5-1`  it was looking like this 
![2024-02-15T11:26:37,834938812+05:30](https://github.com/sxyazi/yazi/assets/132189303/674dd639-b61b-468d-8d2f-49622e45c5e8)

### To Reproduce

just update to version `0.2.3`

### Configuration

I don't have configurations , I use it as it is .

**Comment by sxyazi** [comment]
Hi, in Yazi 0.2.3, some adjustments have been made to the default sorting method, making it behave more like the `ls`. If you want to prioritize sorting by directories, please add:


```toml
[manager]
sort_dir_first = true
# ... other options
```

to your `yazi.toml`. The docs here https://yazi-rs.github.io/docs/configuration/yazi#sort_dir_first
