### ISSUE TITLE
Hide specified files or directories

### ISSUE THREAD

**Issue by grig-iv** [sxyazi/yazi#694]
### Is your feature request related to a problem? Please describe

It's nice to have control over file/folder visibility, e.g. folders like `Desktop`, `go` and `steam` in my home directory are an eyesore for me, I would like to hide them, and some people may want to treat their `.config` as visible folder****

### Will you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

There should be an option in `yazi.toml` where the user can add rules for how to treat certain files and folders. It probably should resides under the `[manager]` category alongside with `show_hidden`. 

**Which is a more intuitive way to represent this option?**
1) An array of patterns with a specification how to treat them
```toml
[manager]
visibility_rules = [
    { pattern = "~/.config", visible = true,  }
    { pattern = "~/Desktop", visible = false, }
    { pattern = "~/go"     , visible = false, }
]
```
2) Two arrays - one for visible entries, one for hidden entries
```toml
[manager]
treat_as_visible = [ "~/.config", ]
treat_as_hidden = [ "~/Desktop", "~/go", ]
```

### Additional context

Requested by @5ouma, https://github.com/sxyazi/yazi/issues/51#issuecomment-1725011140

**Comment by grig-iv** [comment]
Also is there already a function for checking url for a pattern?

**Comment by sxyazi** [comment]
I think this is a bit too complicated, it's a performance challenge

If there are 10,000 files in the directory and there are 5 rules like this, it will need to match 50,000 times. My idea is that it should just be a simple regular expression, not a set of rules.

**Comment by grig-iv** [comment]
Just to be clear, should regex be checked upon filename or full path? And what config type should I use?

**Comment by jmlucjav** [comment]
Total commander does support this, it's called Ignore list

**Comment by sxyazi** [comment]
@jmlucjav  Sorry could you be more specific? How does it support it - like, what does the configuration file look like? I haven't used it.

**Comment by jmlucjav** [comment]
the easiest would be to paste the help contents...

> Configuration - Ignore list                            [Back](https://github.com/sxyazi/yazi/issues/options_config.htm)
>  
> Ignore specific files/folders: They will be neither displayed nor copied. Only files in the file system can be ignored. Files on ftp servers, within archives, plugins or virtual folders like the desktop cannot be ignored.
>  
> Ignore (don't show) the following files and folders:
> Master switch to turn option on and off.
> <Listbox> List files and folders which you want to ignore. The following entry types are supported:
> 1. Full path to file. Example: c:\config.sys
> 2. Path relative to the root of ALL drives. Example: \RECYCLER
> 3. Name which will be hidden in all paths. Example: descript.ion
> Notes:
> - All 3 options above also support the wildcards * and ?, e.g. *.br1
> - Multiple names with wildcards can be put on 1 line, separated by space or ";", e.g. *.bak *.old
> - Relative or absolute path items must be put on a separate line each.
> - When a name is ended with a backslash, it will match only directories
> - Attention: If a name contains both spaces and wildcards, it must be written in double quotes the following way: \"System Volume*" or c:\path\"long name*"
>  
> Save in: Location and name where the ignore list will be stored. Default is tcignore.txt
>  
> Add selected names with full path
> Enabled only when some files are selected in the last active panel of Total Commander. Allows you to add these files/dirs with full path to the above list.
>  
> Add selected names Enabled only when some files are selected in the last active panel of Total Commander. Allows you to add these files/dirs without path, which means that they will be hidden in ALL directories.
>  
> Note: Use the internal command cm_SwitchIgnoreList to turn this option on and off via a button, menu item, or hotkey.

![image](https://github.com/sxyazi/yazi/assets/1813237/01c9459e-29e5-4f9b-a380-b44d825d5e58)

![image](https://github.com/sxyazi/yazi/assets/1813237/f86cfdb2-65f8-4a89-b49a-71da394f2c06)

**Comment by LGraz** [comment]
I was just looking for this feature I missed from ranger.

There it is implemented with the following defaults in the `rc.conf` file  (in case this serves as useful inspiration):
```
# Which files should be hidden? (regular expression)
set hidden_filter ^\.|\.(?:pyc|pyo|bak|swp)$|^lost\+found$|^__(py)?cache__$
```
[c.f. source](https://github.com/ranger/ranger/blob/master/ranger/config/rc.conf)

**Comment by sxyazi** [comment]
Anyone want to give https://github.com/sxyazi/yazi/issues/694#issuecomment-1952107692 a go?

**Comment by pawel-szopinski** [comment]
lf file manager also has this feature implemented. It's just one line in the config file, e.g.:
```
set hiddenfiles .DS_Store:.localized:.sync_*
```

It would be awesome to have this feature in yazi, especially on macOS, since most directories are polluted by files like .DS_Store.

**Comment by DirkFi** [comment]
> Anyone want to give [#694 (comment)](https://github.com/sxyazi/yazi/issues/694#issuecomment-1952107692) a go?

Hi, there. I'm interested in solving this issue but i'm new to this project's code base. 
I tried to read and understand how this `hidden` attribute works in the code. Currently, my idea is to refactor the  struct `Manager` in `yazi-config` with new `visibility_rules` attribute added and modify the `is_hidden()` function of `Url` in `yazi-shared/fs` to implement the rule. 
Do you think it's a good way to go? Is there a better way for it?

**Comment by LGraz** [comment]
What are your thoughts on adding the option `ignorefile`? Like:
```
[manager]
visibility_rules = [
    { dir = "~/", hide = "go|\.git", ignorefile = ".gitignore|.stignore"},
    { dir = "*/", hide = "\.git", ignorefile = ".gitignore" }  # fallback
]
```

just a brainstorm idea :)

**Comment by DirkFi** [comment]
I haven't thought about `ignorefile` yet. I think it can still be implemented with Regx in `hide`.

**Comment by sxyazi** [comment]
Tracked by https://github.com/sxyazi/yazi/issues/51
