### ISSUE TITLE
Touch confifguration

### ISSUE THREAD

**Issue by aspauldingcode** [sxyazi/yazi#695]
### Is your feature request related to a problem? Please describe

Can't use on the phone. 

### Will you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

yazi is going to be amazing IF I can use it on my phone. 
Enable Touch/click configuration. Similar to ranger. Yazi would beat everything a terminal file manager could be, if you add touch support.

### Describe alternatives you've considered

Ranger. LF - but requires config change to support touch.

**Comment by sxyazi** [comment]
It's already in the [Feature Requests](https://github.com/sxyazi/yazi/issues/51) as "Mouse actions binding in keymap.toml" - I'll add basic mouse support at some point in the future, [just like lf](https://github.com/gokcehan/lf/issues/268#issuecomment-762506668).

Welcome any PRs to accelerate its implementation. Closing as duplicate

**Comment by sxyazi** [comment]
Hi, this feature has now been implemented by @qsdrqs in https://github.com/sxyazi/yazi/pull/1038! 🎉
