### ISSUE TITLE
last linux binary: fd and rg commands do nothing. yet work in the shell.

### ISSUE THREAD

**Issue by evanescente-ondine** [sxyazi/yazi#696]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot version: 1.16.2 +pgo +ime +graphemes -assertions

### Yazi version

yazi 0.2.3 (3f27532 2024-02-18)

### Did you try the latest main branch to see if the problem has already been fixed?

Tried, but the problem is still present

### Describe the bug

the fd and rg command do not work. those two commands do work in my terminal by virtue of an alias in my shell (fish, version 3.7.0) as I'm on debian now, yet it seems yazi doesn't see that. keymap.toml is indeed read and used, but it's written "search fd" so I don't know what could be wrong here. you press the keys and enter, and nothing happens.

### Expected Behavior

Well fd and rg should work.

### To Reproduce

Just use the last binary.

### Configuration

no config

**Comment by sxyazi** [comment]
> those two commands do work in my terminal by virtue of an alias in my shell (fish, version 3.7.0)

I think that's the issue here. Yazi uses `sh` instead of `fish`, as not all users have `fish` installed.

So it can't recognize the aliases you've defined in `fish`. Please add `fd` and `rg` to your `$PATH` so that `sh` can find them. You can check it with `sh -c "fd"`.

**Comment by evanescente-ondine** [comment]
Strange, I swear I was using fish too before, sole difference is I was on Arch/endeavouros. No matter, symlinks will do.
