### ISSUE TITLE
Acessing `state` in plugin's `setup` function

### ISSUE THREAD

**Issue by dedukun** [sxyazi/yazi#703]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

wezterm 20240123-102946-02bdd7ed

### Yazi version

yazi 0.2.3 (8efafd6 2024-02-19)

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### Describe the bug

Yazi panics when trying to access the `state` variable inside a `setup` function as demonstrated in https://yazi-rs.github.io/docs/plugins/overview#sync-vs-async.

### Expected Behavior

It should be possible to set variables in the `state` so that the plugins can have custom configurations.

### To Reproduce

I've created a [new branch in bookmarks.yazi](https://github.com/dedukun/bookmarks.yazi/tree/setup) which has a simple `setup` function that tries to set a table in the `state` variable.

To recreate the issue, simply call the `setup` method in `init.lua`

### Anything else?

I've looked a bit into the lua API and I think that the issue is because the `require` just runs the lua code without the context of `YAZI_PLUGIN_NAME`.

A possible solution might be to have a custom `require` that does something similar to [entry](https://github.com/sxyazi/yazi/blob/8efafd6c9104684920c819aa3fc762d9d61689e1/yazi-plugin/src/isolate/entry.rs#L7).

**Comment by dedukun** [comment]
This is a bit off topic, but in the example that I gave I'm using `print` in the `setup` function instead of `ya.err` because [`init.lua`](https://github.com/sxyazi/yazi/blob/2e9b6b7b7b7bd2d0b70232f4cf776b2a4cc63110/yazi-fm/src/main.rs#L47) is executed before the [logs are initialized](https://github.com/sxyazi/yazi/blob/2e9b6b7b7b7bd2d0b70232f4cf776b2a4cc63110/yazi-fm/src/app/app.rs#L20).

Do you want me to make a PR to fix this?

**Comment by dedukun** [comment]
> Thank you for the report, this is a known issue, and I am still considering how to address it.
> 
> You can use `state("your-plugin-name")` as a workaround for now:
> 
> ```lua
> return {
>   setup = function(self, opts) 
>     local st = state("your-plugin-name")
>     st.foo = "bar"
>   end
> }
> ```
> 
> Needs [0cb572a](https://github.com/sxyazi/yazi/commit/0cb572a83787a88c8e6ef30aec148d509902a659)

Cool, thanks for the quick workaround, I'll use it in the mean time.

**Comment by sxyazi** [comment]
Hi, I made a PR trying to fix it, https://github.com/sxyazi/yazi/pull/710, let me know if it works for you!
