### ISSUE TITLE
Feature request: configurable column_ratio

### ISSUE THREAD

**Issue by KeqiZeng** [sxyazi/yazi#71]
Hi, first of all thanks for such a good project.

I have tried to migrate from `ranger` to `yazi` recently, It's super fast and has many features out of box. But I think the preview area a bit small for me. If the user can define the `column_ratio` their own just like in `joshuto`, it will be very great I think. It maybe looks like:
![image](https://github.com/sxyazi/yazi/assets/75246050/beb88e2c-5abb-4dd9-85b4-474ded3cf8be)

Thank you again for what you've done for yazi!

**Comment by sxyazi** [comment]
I will evaluate the complexity and implement it soon. Thanks for the appreciation!

**Comment by sxyazi** [comment]
Done by https://github.com/sxyazi/yazi/pull/76, closing then
