### ISSUE TITLE
Linux musl release

### ISSUE THREAD

**Issue by rafi** [sxyazi/yazi#723]
### Please describe the problem you're trying to solve

On Linux with no glib:
```
yazi: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by yazi)
```

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Release asset for x86-64 linux musl

**Comment by sxyazi** [comment]
Sounds good! Does anyone want to give it a try? I think adding a new target in the release workflow should do it:

https://github.com/sxyazi/yazi/blob/b6fb02fda3317652270930043e298b63fd1d1f97/.github/workflows/release.yml#L13-L26
