### ISSUE TITLE
Failed to stop searching after `yazi` is quitted

### ISSUE THREAD

**Issue by NeumoNeumo** [sxyazi/yazi#726]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.32.2

### Yazi version

yazi 0.2.3 (42cbedb 2024-02-25)

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### Describe the bug

When searching using`rg` or `fd` in a large directory, it is OK to take a long time. However, when I want to cancel the process by just quitting `yazi`. The processes of `rg` or `fd` are still running in the background.

Open `yazi`: 
![image](https://github.com/sxyazi/yazi/assets/107997665/750222d6-b8e6-4297-a754-71c245fb9464)

Searching for some file in `yazi`:
![image](https://github.com/sxyazi/yazi/assets/107997665/3a0db7d8-90ce-4869-bc7f-1366cfba1cac)

`fd` is still running without the presence of `yazi`:
![image](https://github.com/sxyazi/yazi/assets/107997665/128f4b8b-c18c-4b18-9d9c-f9290da3e5b1)
![image](https://github.com/sxyazi/yazi/assets/107997665/f9b63e7e-6a42-4df1-98e4-bbab57ee2ce9)
(The server is using NFS so the REAL disk IO is actually displayed in the `Network` instead of `Disk IO` in the above screenshot of `htop`)

### Expected Behavior

After quitting `yazi`, all processes related to it should be killed.

### To Reproduce

1. Find a large directory, for example, the root.
2. Open `yazi` and search for some file, like "gagaga".
3. Before the `yazi` completes the search task, quit it.
4. You would find the searching process is still running in the background.

### Configuration

no config

**Comment by sxyazi** [comment]
How did you exit Yazi, by using `q` to quit it normally, or by forcefully ending it with something like `kill yazi`?

**Comment by NeumoNeumo** [comment]
> Hi, I made a PR trying to fix this issue #812, let me know if it works for you

Thank you. It works! :smile:
