### ISSUE TITLE
Central column directory/file list disappears when file is selected

### ISSUE THREAD

**Issue by swamp-fish** [sxyazi/yazi#733]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

konsole 23.08.4

### Yazi version

yazi 0.2.3 (8ea7556 2024-02-24)

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### Describe the bug

I'm connecting to Ubuntu 22.04 through ssh.
Yazi has 3 columns, when i navigate folders i can see list of folders and files in the middle column but:
- when i step on a file middle column disappears, file preview is shown on the right column
- when i step on a folder middle column appears and i can see list of files and folders

### Expected Behavior

Navigating through files and folders without middle column content disappearing.

### To Reproduce

1. Connect with ssh to Linux machine (in my case with Ubuntu 22.04)
2. Navigate through some folders that contains both folders and files (ARROW_UP/ARROW_DOWN)
3. Middle column content disappears when you step on a file

### Anything else?

https://github.com/sxyazi/yazi/assets/9247853/8c269214-5ec9-41ca-854e-0f2e13128181

**Comment by sxyazi** [comment]
Hi, thanks for reporting!

I noticed you're not using the latest main branch - this issue has been fixed in the latest HEAD.

**Comment by swamp-fish** [comment]
Yes, it's fixed now. I forgot to git pull. Sorry.

**Comment by sxyazi** [comment]
Nice to hear that, let's close this issue then
