### ISSUE TITLE
Implement help page

### ISSUE THREAD

**Issue by elkarouh** [sxyazi/yazi#736]
### Please describe the problem you're trying to solve

I am a casual user so I can't remember all key mapings.
I don't see a way to invoke the help. I tried F1 but it did nothing.
Am i missing something obvious ?

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

When pressing <F1>, i want to see a key mapping

**Comment by elkarouh** [comment]
Help page exists but the keybinding ~ is unusual.
I would prefer <F1>

**Comment by sxyazi** [comment]
“?” has been used as find forward like Vim does
