### ISSUE TITLE
View shell output

### ISSUE THREAD

**Issue by swamp-fish** [sxyazi/yazi#737]
### Please describe the problem you're trying to solve

When you run a shell command it may result in an error or information that you seek.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Seeing the shell command output by pressing buttons in a similar window that shows the task manager or by turning off UI the way mc does it.

**Comment by sxyazi** [comment]
Hi!

This is a feature that is already supported. Use the inspect command (Enter key ) in the task manager to view the real-time output of the shell task.

**Comment by swamp-fish** [comment]
I press `:` then enter `ls -l`. Command executes but when i press `w` i see nothing in there, still i press `Enter` and nothing happens. To see the result i need to quit yazi. With `;` some commands don't work, `systemctl list-timers` for another example.

If i run something more time consuming and thing that can be run with `;` like `ffmpeg -i *mkv file.mp4` It shows in the task manager `w`  and i can look upon it in realtime but if the command finishes its job i can't see it anymore.

**Comment by sxyazi** [comment]
> I press `:` then enter `ls -l`. Command executes but when i press `w` i see nothing in there, still i press `Enter` and nothing happens. To see the result i need to quit yazi. With `;` some commands don't work, `systemctl list-timers` for another example.

Use `ls -l; read` instead of `ls -l`, otherwise, your task will end immediately after execution and return to Yazi.

> If i run something more time consuming and thing that can be run with `;` like `ffmpeg -i *mkv file.mp4` It shows in the task manager `w`  and i can look upon it in realtime but if the command finishes its job i can't see it anymore.

This is the expected behavior; only tasks that are in progress or have failed will be retained in the task list.

**Comment by swamp-fish** [comment]
After `ls -l; read` i see this in task list `Execute ls -l; read with /etc/cron.d` and when i press it i get `ls -l` output + error:
```
: 1: read: arg count
Exited with status code: 2
Process failed
```
So by using `read` i intentionally trigger error mechanism so that it would remain in history and i could watch output?

**Comment by sxyazi** [comment]
Nope, I mean you can use `read` within `:`, not `;`, because `;` does not have `stdin`.

Are you looking to execute your tasks synchronously (`:`) or asynchronously (`;`)? Their mechanisms are different, if you want asynchronous execution, it's expected for the task to disappear from the task manager after it succeeds. If you don't want it to disappear, don't let the task end - you can add something like `sleep 999`, although I think only failed tasks appearing in the task manager make sense.

**Comment by swamp-fish** [comment]
Ah, i see now, yes i can see the output just fine when i use `read` with `:`
Do you have plans to add autocompletion to the shell if it's not realized already? I see an entry called `completion` in the `keymap.toml` what is it for?
Is there a way to remember all opened tabs upon exit?

**Comment by sxyazi** [comment]
> Do you have plans to add autocompletion to the shell if it's not realized already? 

Yeah it's already in the [Feature Requests](https://github.com/sxyazi/yazi/issues/51) as "Shell completion", I haven't had time to implement it yet.

> I see an entry called completion in the keymap.toml what is it for?

It's file path completion when `g<Space>`.

> Is there a way to remember all opened tabs upon exit?

I plan to implement it as a plugin, and if all goes well it should be supported in the next target (v0.2.5).
