### ISSUE TITLE
Better path display for deeply nested directories

### ISSUE THREAD

**Issue by d-sonuga** [sxyazi/yazi#743]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

GNOME v3.48.1

### Yazi version

yazi 0.2.2

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### Describe the bug

When navigating through directories, the path to the directory is displayed at the top of the UI.
In deeply nested directories, only the first part of the path that can be displayed on the screen is displayed.
For example, if the path is a/b/c/d/e/f/g/h/i/j/k and only a path of length 5 can be displayed, then a/b/c/d/e will be displayed.

### Expected Behavior

The last part of the path should be displayed, not the first as the purpose of the path display is for users to know where they are. For example, if the path a/b/c/d/e/f/g/h/i/j/k is navigated into and only paths of length 5 can be displayed, then .../g/h/i/j/k should be displayed, not a/b/c/d/e.

### To Reproduce

Navigate into a deeply nested directory whose path can't be contained in the area for path display. 

### Configuration

no config

**Comment by sxyazi** [comment]
Thanks for the report! 

This sounds more like a feature request than a bug, as it's the current expected behavior - I'll add an "enhancement" label to it.

**Comment by sxyazi** [comment]
https://github.com/sxyazi/yazi/blob/b6fb02fda3317652270930043e298b63fd1d1f97/yazi-plugin/preset/components/header.lua#L5-L13

I think we just need to truncate the text here, anyone want to give it a try?

**Comment by og900aero** [comment]
I don't understand where it cuts off. I brought these directories over, went in, and it shows full length.

![screenshot_1709102399](https://github.com/sxyazi/yazi/assets/49487376/1af69d40-83bc-454c-9792-6d10fe2993d7)

**Comment by d-sonuga** [comment]
@og900aero, my example assumes that the max path length that can be displayed is 5. It doesn't cut off on your computer because the max path length is greater than needed. If the path length can't fit in the allotted space for the path display, you will see the cutoff.
