### ISSUE TITLE
2 panes no longer works

### ISSUE THREAD

**Issue by derrickcope** [sxyazi/yazi#746]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 

### Yazi version

0.2.3 arch linux

### Did you try the latest main branch to see if the problem got fixed?

Not tried, and I'll explain why below

### Describe the bug

setting the first layout number to 0 no longer gives 2 panes

### Expected Behavior

before I got 2 panes rather than 3

### To Reproduce

put 0 for the first layout number

### Configuration

yazi.toml

**Comment by sxyazi** [comment]
See https://github.com/sxyazi/yazi/issues/461
