### ISSUE TITLE
iTerm2 image protocol for vscode

### ISSUE THREAD

**Issue by jerch** [sxyazi/yazi#756]
### Please describe the problem you're trying to solve

Is there a specific reason why you use Sixel for vscode terminal? Wouldn't the iterm protocol give higher quality output and be faster to process?

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

```diff
--- a/yazi-adaptor/src/adaptor.rs
+++ b/yazi-adaptor/src/adaptor.rs
@@ -92,9 +92,9 @@ impl Adaptor {
                        Emulator::Foot => vec![Self::Sixel],
                        Emulator::Ghostty => vec![Self::KittyOld],
                        Emulator::BlackBox => vec![Self::Sixel],
-                       Emulator::VSCode => vec![Self::Sixel],
-                       Emulator::Tabby => vec![Self::Sixel],
-                       Emulator::Hyper => vec![Self::Sixel],
+                       Emulator::VSCode => vec![Self::Iterm2],
+                       Emulator::Tabby => vec![Self::Iterm2],
+                       Emulator::Hyper => vec![Self::Iterm2],
                        Emulator::Mintty => vec![Self::Iterm2],
                        Emulator::Neovim => vec![],
                };
```

### Additional context

Resizing is not yet working, but I think you already got that covered upstream in https://github.com/crossterm-rs/crossterm/pull/810.

**Comment by sxyazi** [comment]
😲 Interesting, I just found out that they support the iTerm2 protocol...

I will test them and create a commit to switch to IIP, thank you for letting me know this.

**Comment by sxyazi** [comment]
Done in https://github.com/sxyazi/yazi/commit/c3a11035298c92204fda815ce4ce7a9252ca35c5 and https://github.com/yazi-rs/yazi-rs.github.io/commit/d4249f12a730ed78abfcc65bd24687e1f9ba6e9e
