### ISSUE TITLE
Drop to shell in empty dir doesn't work

### ISSUE THREAD

**Issue by rrveex** [sxyazi/yazi#764]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot 1.16

### Yazi version

yazi 0.2.3 (bd57270 2024-03-02)

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### Describe the bug

Since https://github.com/sxyazi/yazi/commit/2efda755f1179c29556fd5c8809247530ef84c00 trying to open a shell (as described here: https://yazi-rs.github.io/docs/tips#dropping-to-the-shell ) in an empty directory  doesn't work.

### Expected Behavior

Shell opens

### To Reproduce

- navigate to an empty dir (=> no cursor)
- press shortcut to open shell

### Configuration

`{ on = [ "S" ], 'shell "$SHELL" --block --confirm' }, `

### Anything else?

```
diff --git a/yazi-core/src/tasks/tasks.rs b/yazi-core/src/tasks/tasks.rs
index 4656e7a..22f6a6b 100644
--- a/yazi-core/src/tasks/tasks.rs
+++ b/yazi-core/src/tasks/tasks.rs
@@ -69,9 +69,7 @@ impl Tasks {
 	}
 
 	pub fn file_open_with(&self, opener: &Opener, args: &[impl AsRef<OsStr>]) {
-		if args.len() < 2 {
-			return;
-		} else if opener.spread {
+		if opener.spread {
 			self.scheduler.process_open(opener, args);
 			return;
 		}
```

This would fix the issue, but I don't know what implications it has.

**Comment by sxyazi** [comment]
Thanks for reporting, should be fixed in https://github.com/sxyazi/yazi/commit/1835fba8ea417db89acc13db3df297011a8c642f
