### ISSUE TITLE
[Feature request] modify file permission

### ISSUE THREAD

**Issue by ListenV** [sxyazi/yazi#781]
### Please describe the problem you're trying to solve

Fast modify file permission

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

command: `permission`.
args: 

- like chmod's args： `755` or `a+r -R`. (User-friendly keymap)
- `--input`：input popup to input the permission

**Comment by ListenV** [comment]
想到一个办法，可以通过 manger 中的 `shell` 执行 `chmod` 命令，不过要先判断一下是否是 Unix 环境。

**Comment by sxyazi** [comment]
Done, https://github.com/yazi-rs/plugins/tree/main/chmod.yazi


https://github.com/sxyazi/yazi/assets/17523360/6bae1adb-61ce-4d1d-91e1-f59aceb6020f
