### ISSUE TITLE
File info not auto update

### ISSUE THREAD

**Issue by ListenV** [sxyazi/yazi#783]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

Windows Terminal

### Yazi version

0.2.3

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### Describe the bug

不通过yazi的manager命令来修改文件，修改后，文件信息没有更新

### Expected Behavior

auto update file info

### To Reproduce

比如：在外部使用 `chmod` 修改文件权限后，yazi显示的不是最新的权限

**Comment by sxyazi** [comment]
I can't reproduce this issue in the latest main branch.


I noticed you mentioned trying the latest main branch - which commit are you trying? Please do a `yazi -V` and paste the version here.

https://github.com/sxyazi/yazi/assets/17523360/b9191a46-ddc0-4f4e-8b88-91a098d81281

**Comment by ListenV** [comment]
抱歉，没有贴全部的版本信息

我目前更新到 `0.2.4` 问题依旧

`yazi -V` 结果：`yazi 0.2.4 (Arch Linux 2024-03-10)`

以下是我基于这个版本的视频：


https://github.com/sxyazi/yazi/assets/45219522/eb09c1fa-3e7f-45f1-a9b1-107d09dc2489

**Comment by ListenV** [comment]
`yazi --debug`：

```
Yazi
    yazi 0.2.4 (Arch Linux 2024-03-10)

Environment
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Unknown([])

Adaptor
    Adaptor.matches: KittyOld

tmux
    TMUX: false

Zellij
    ZELLIJ_SESSION_NAME: None

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

Ueberzug
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: true


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/sky03/.local/state/yazi" directory.
```

**Comment by sxyazi** [comment]
You are in WSL right? What's your file system?

**Comment by ListenV** [comment]
Yes, I'm use ArchLinux in WSL, and WSL2 only support the ext4.
