### ISSUE TITLE
add the keymap view

### ISSUE THREAD

**Issue by hackers267** [sxyazi/yazi#79]
# add the keymap view

As an file-manage, the keymap is important, and let the user to learn about the keymap is more important. So if can use a keymap to see the keymap, the more people should use *yazi*. 

If use the key `?` to see the keymap view ,like this:

![image](https://github.com/sxyazi/yazi/assets/22020318/c5a3486f-8d3b-4729-9d4d-c306acf6fecc)

**Comment by sxyazi** [comment]
I'll add it as soon, but the description is not yet clear how to get it.

Right now the description of each command appears in the markdown docs separately, probably I'll move the description to the code later and have the code generates docs.

**Comment by sxyazi** [comment]
Done by https://github.com/sxyazi/yazi/pull/93, please give it a try!

**Comment by hackers267** [comment]
> Done by #93, please give it a try!

Yes. This is very good.

> Note: If you want to try this, you should copy the `keymap.toml` to your `~/.config/yazi` if you had the *dir*.

**Comment by sxyazi** [comment]
Thanks for the testing, I'll close this issue then.
