### ISSUE TITLE
imagepreview can not use in x11

### ISSUE THREAD

**Issue by yuzhegan** [sxyazi/yazi#793]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

st

### Yazi version

yazi0.2.3

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### Describe the bug

ueberzug layer
{"action":"add","identifier":"preview","max_height":0,"max_width":0,"path":"/your/image-path.jpg","x":0,"y":0}
可以显示图片在终端
![](https://gitss.oss-cn-shenzhen.aliyuncs.com/md/1709955868540.png)
![1709955839235.png](https://gitss.oss-cn-shenzhen.aliyuncs.com/md/1709955839235.png)

### Expected Behavior

yazi里面不能显示图片,
![1709955935798.png](https://gitss.oss-cn-shenzhen.aliyuncs.com/md/1709955935798.png)
我用的是[ueberzugpp](https://github.com/jstkdng/ueberzugpp) 
在lf中用它的脚本,
[lfub](https://github.com/jstkdng/ueberzugpp/blob/master/scripts/lf/lfub) 
[preview](https://github.com/jstkdng/ueberzugpp/blob/master/scripts/lf/preview) 
可以预览图片,在ranger中也可以预览图片
![1709956651584.png](https://gitss.oss-cn-shenzhen.aliyuncs.com/md/1709956651584.png)

### To Reproduce

[preview]
tab_size        = 2
max_width       = 0
max_height      = 0
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]
图片预览配置

### Configuration
我用的wsl2,用wsl2 gui应用开的st终端
_No response_

### Anything else?
根据**ueberzug**的要求配置**~/.config/ueberzugpp/config.json**
{
	"layer": {
		"silent": true,
		"use-escape-codes": true,
		"no-stdin": true,
		"output": "x11"
	},
	"action": "add",
	"identifier": "preview",
	"max_height": 0,
	"max_width": 0,
	"path": "/path/image.ext",
	"x": 0,
	"y": 0
}

_No response_

**Comment by sxyazi** [comment]
Closing this issue as discussed in the Yazi Telegram group with OP.
