### ISSUE TITLE
Ability to run executables

### ISSUE THREAD

**Issue by nolemretaWxd** [sxyazi/yazi#795]
### Please describe the problem you're trying to solve

I want to use yazi like I do File Explorer on Windows. It's almost perfect in that regard, but I can't run executables, trying to open them causes my web browser to open and try to download a file even though yazi recognizes that it's an ELF file. I'd probably add this myself as an opener, but there's no standardized extension for ELF files nor mimetype.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Ability to run executables like an any other file.

### Additional context

The closest function is "run a shell command" function but I'd like to just press enter or o and have it run the executable.

**Comment by sxyazi** [comment]
Hi, what's your Yazi version? Just tried in my Windows VM, with the default "Open" opener, I can get it to open the executable file:

https://github.com/sxyazi/yazi/blob/b10f2de16d46df3ed7f6efe99ac966fd49d6e919/yazi-config/preset/yazi.toml#L36


https://github.com/sxyazi/yazi/assets/17523360/28e663b5-8439-419a-88e3-84e7c3fb2722

My Yazi version:

```
yazi 0.2.4 (b10f2de 2024-03-11)
```

**Comment by nolemretaWxd** [comment]
> Hi, what's your Yazi version? Just tried in my Windows VM, with the default "Open" opener, I can get it to open the executable file:
> 
> https://github.com/sxyazi/yazi/blob/b10f2de16d46df3ed7f6efe99ac966fd49d6e919/yazi-config/preset/yazi.toml#L36
> 
> windows.open.mp4
> 
> My Yazi version:
> 
> ```
> yazi 0.2.4 (b10f2de 2024-03-11)
> ```

Hi, it's
`yazi 0.2.4 (Arch Linux 2024-03-10)`

**Comment by sxyazi** [comment]
Are you on Windows right? Why is `Arch Linux` included in the version?

**Comment by sxyazi** [comment]
> It works, but with `run` in opener set to `'"$@"'`, without xdg-open

Yeah that's how it works, just like when you directly execute it in the shell.

Nice to hear it's working; I think we can close this issue now.
