### ISSUE TITLE
cross language

### ISSUE THREAD

**Issue by xienuss** [sxyazi/yazi#798]
### Please describe the problem you're trying to solve

i have eng/rus keyboard and i need to switch keyboard template every time i open yazi

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

cross-language feature

**Comment by sxyazi** [comment]
Hi, could you elaborate more on how Yazi can achieve this function? I didn't quite understand what you meant.

**Comment by xienuss** [comment]
> Hi, could you elaborate more on how Yazi can achieve this function? I didn't quite understand what you meant.

if i switch my keyboard layout to russian (maybe it works with other

**Comment by xienuss** [comment]
I accidentally clicked "close with comment", srry
when I switch the keyboard layout to some language other than english then yazi`s binds like D,S,W,Y,P e.t.c. doesn`t work because its another language with another symbols/letters

**Comment by sxyazi** [comment]
Hi, you can set different key rules in your `keymap.toml` based on the different keyboard layouts.

If you use two keyboard layouts simultaneously, the simplest way is to create two `keymap.toml` files and specify different configuration files when starting Yazi according to your keyboard layout, through `YAZI_CONFIG_HOME`.

See https://yazi-rs.github.io/docs/configuration/overview and https://yazi-rs.github.io/docs/configuration/keymap
