### ISSUE TITLE
yazi-adaptor not compiling

### ISSUE THREAD

**Issue by LucasTavaresA** [sxyazi/yazi#801]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

st 0.9 (custom build)

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### `yazi --debug` output

i fixed it by changing the code cargo downloaded, which updated successfully, it does not even check if the previously downloaded changed or something XD

### Describe the bug

when updating all my cargo pkgs with `cargo install-update -g -a`, yazi-adaptor fails to compile with this error

```console
error[E0308]: mismatched types
   --> /home/lucas/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/yazi-adaptor-0.2.4/src/image.rs:42:5
    |
38  |             JpegEncoder::new_with_quality(&mut buf, PREVIEW.image_quality).encode(
    |                                                                            ------ arguments to this method are incorrect
...
42  |                 img.color(),
    |                 ^^^^^^^^^^^ expected `ExtendedColorType`, found `ColorType`
    |
note: method defined here
   --> /home/lucas/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/image-0.25.0/src/codecs/jpeg/encoder.rs:443:12
    |
443 |     pub fn encode(
    |            ^^^^^^
help: call `Into::into` on this expression to convert `ColorType` into `ExtendedColorType`
    |
42  |                 img.color().into(),
    |                            +++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `yazi-adaptor` (lib) due to 1 previous error
```

i added `.into()` to line 42 in image.rs and it compiles and seems to work fine.

im know nothing about rust so please check what this is in the first place and if it is the thing you actually want to do

### Expected Behavior

compile

### To Reproduce

compiling the latest yazi version and all its dependencies

**Comment by rplanchuelo** [comment]
Same for my

**Comment by sxyazi** [comment]
Hi, when building Yazi, the `--locked` flag is needed. It seems that `cargo-update` does not support it, but I [found a workaround](https://github.com/nabijaczleweli/cargo-update/issues/191):

```sh
CARGO_INSTALL_OPTS=--locked cargo install-update -a
```

You can also build it directly [using cargo](https://yazi-rs.github.io/docs/installation#cargo):

```sh
cargo install --locked yazi-fm
```

Let me know if it works for you!

**Comment by rplanchuelo** [comment]
It works for me

> Hi, when building Yazi, the `--locked` flag is needed. It seems that `cargo-update` does not support it, but I [found a workaround](https://github.com/nabijaczleweli/cargo-update/issues/191):
> 
> ```shell
> CARGO_INSTALL_OPTS=--locked cargo install-update -a
> ```
> 
> You can also build it directly [using cargo](https://yazi-rs.github.io/docs/installation#cargo):
> 
> ```shell
> cargo install --locked yazi-fm
> ```
> 
> Let me know if it works for you!

**Comment by LucasTavaresA** [comment]
yeah it works just fine
