### ISSUE TITLE
Image preview in Terminator

### ISSUE THREAD

**Issue by madjin** [sxyazi/yazi#802]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

Terminator 2.1.2

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### `yazi --debug` output

```sh
Yazi
    yazi 0.2.4 (b10f2de 2024-03-09)

Environment
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Unknown([])

Adaptor
    Adaptor.matches: X11

tmux
    TMUX: false

Zellij
    ZELLIJ_SESSION_NAME: None

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY: None
    DISPLAY: Some(":0.0")

Ueberzug
    Version: Ok(Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "Usage:\n    ueberzug layer [options]\n    ueberzug library\n    ueberzug version\n    ueberzug query_windows PIDS ...\n" })

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

```

### Describe the bug

Running `ueberzug layer` independently shows an image preview, but in yazi it doesn't work whether using tmux or not. I even updated my tmux config, restarted tmux, restarted my laptop. I'm running Debian 12 and using one of the compiled versions of yazi from release

### Expected Behavior

Show image preview inside yazi

### To Reproduce

Start terminator, open yazi, hover over an image (png, jpg)

### Configuration

All default from https://github.com/sxyazi/yazi/releases/tag/v0.2.4

### Anything else?

![image](https://github.com/sxyazi/yazi/assets/32600939/84ea061a-2a60-4b19-9916-60754e9d090b)

**Comment by madjin** [comment]
> Hi, are you using https://github.com/jstkdng/ueberzugpp?

yeah here's a test with `ueberzug layer` + `{"action":"add","identifier":"preview","max_height":0,"max_width":0,"path":"/home/jin/Pictures/memes/cat-look.png","x":0,"y":0}`

![image](https://github.com/sxyazi/yazi/assets/32600939/9a84eccf-2782-4de1-8a38-96c7c736db7f)

**Comment by sxyazi** [comment]
What is your ueberzugpp version? I noticed that the `yazi --debug` you provided above does not include a proper version for ueberzugpp.

`yazi --debug` is essentially doing `ueberzug --version` in the background. What is the output when you manually run it?

**Comment by madjin** [comment]
18.1.9, seems old lol 
I'ma grab a newer one and test

**Comment by madjin** [comment]
![image](https://github.com/sxyazi/yazi/assets/32600939/beff94d7-0a74-42a8-b00f-21328fe17d64)

It's working now! Just not with optimal placement within the right pane :sweat_smile:

**Comment by sxyazi** [comment]
Nice to hear that it works now. You can fine-tune the position of Ueberzug using `ueberzug_scale` and `ueberzug_offset`, see https://yazi-rs.github.io/docs/configuration/yazi#ueberzug-specific. I think we can close this issue now. 

By the way, you might also want to install nerd-fonts and configure it for your terminal to allow Yazi to display icon fonts properly, or simply [disable it](https://yazi-rs.github.io/docs/faq#i-dont-like-nerdfonts) ;)
