### ISSUE TITLE
Operate on selected files only when the hovered file is selected

### ISSUE THREAD

**Issue by hankertrix** [sxyazi/yazi#807]
### Please describe the problem you're trying to solve

With the cross-directory selection feature, it is very unexpected to select items in a parent directory, and then navigate into the child directory to attempt to open a file, only for yazi to open the selected items in the parent directory.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Since most users will likely be hovering over a selected file when they want to operate on the items that they have selected, I think it makes more sense to only open the selected files when the hovered item is also selected, instead of opening the selected files when the hovered item isn't selected, which I think most will find to be very confusing.

### Additional context

This issue is especially obvious when using the smart-enter plugin that combines the enter and open commands.

**Comment by sxyazi** [comment]
Thanks for the PR!

This is why I made `smart-enter` as a tip rather than directly supporting it, it conflicts with Yazi's design pattern, where `enter`/`leave` always operates on the hovered *single* entry, while open always prioritizes the selection, users might select *multiple* files and want to open all of them.

However, `open` now supports the [`--hovered` option](https://yazi-rs.github.io/docs/configuration/keymap#open), which can simply be achieved by changing smart-entry's code without touching this fundamental design change:

```diff
return {
  entry = function()
    local h = cx.active.current.hovered
-   ya.manager_emit(h and h.cha.is_dir and "enter" or "open", {})
+   ya.manager_emit(h and h.cha.is_dir and "enter" or "open", { hovered = true })
  end,
}
```

Alternatively, it can also be achieved by disabling cross-directory selection in a simple way, see https://github.com/sxyazi/yazi/pull/693#issuecomment-1986949939

**Comment by hankertrix** [comment]
Ahhhh I see. I'll close my PR then.

Is there a way to access the current list of selected items? I would like to open the selected items when the current hovered item is selected and open the hovered item only otherwise. The above would always open the hovered item.

**Comment by sxyazi** [comment]
Sure use this:

```lua
for idx, url in pairs(cx.active.selected)
```

**Comment by hankertrix** [comment]
Thank you!

I got the smart-enter plugin to behave the way I want it:

```lua
-- Smartly enter a directory or open a file based on what the hovered item is
return {
    entry = function()

        -- Gets the hovered item
        local hovered_item = cx.active.current.hovered

        -- If no item is hovered, exit the function
        if not hovered_item then return end

        -- If the hovered item is a directory,
        -- enter the current directory and exit the function
        if hovered_item.cha.is_dir then
            return ya.manager_emit("enter", {})
        end

        -- Iterates over all the selected items
        for _, url in pairs(cx.active.selected) do

            -- If the hovered item is the same as the current item
            if hovered_item.url == url then

                -- Open all the selected items and exit the function
                return ya.manager_emit("open", {})

            end
        end

        -- Otherwise, open the hovered item only
        return ya.manager_emit("open", { hovered = true })
    end,
}

```

I'll close this issue then.

**Comment by sxyazi** [comment]
If you want to check if `hovered_item` is in the selection list, you can simplify this loop by using `hovered_item:is_selected()`. Something like this should work:

```lua
return {
    entry = function()
        -- Gets the hovered item
        local hovered_item = cx.active.current.hovered

        -- If no item is hovered, exit the function
        if not hovered_item then return

        -- Otherwise, if the hovered item is a directory,
        -- enter the current directory and exit the function
        elseif hovered_item.cha.is_dir then
            return ya.manager_emit("enter", {})

        -- Open all the selected items and exit the function
        elseif hovered_item:is_selected() then
            return ya.manager_emit("open", {})
        end

        -- Otherwise, open the hovered item only
        return ya.manager_emit("open", { hovered = true })
    end,
}
```

**Comment by hankertrix** [comment]
Oh, that's great! Thank you!
