### ISSUE TITLE
feature request for "find" aka jump to matching file/folder

### ISSUE THREAD

**Issue by teto** [sxyazi/yazi#81]
thanks for creating this ! I used to use ranger but was tempted by joshuto for the rust bonus but either choice had issues and I feel yazi has strong foundamentals and can become the best choice for me:
- (image & text) preview by default !
- it was the fastest when opening my 200GB /nix/store that joshuto and ranger have difficulty with. I believe it could be even better and refresh the listing dynamically (I still had to wait ~8 sec) but it's much better than the other two.

The feature I miss the most currently is "search" or "filter". In ranger/joshuto, I could type `/` to start typing a folder name and go to it. Maybe it's possible in yazi but I couldn't find how ?

NB: nitpicks: PageUp and PageDown are not bound byu default and when the prompt to quit appears asking for "yes or no", I think it should quit on "y" press while right now I had to press "Enter" too.

**Comment by Gajus84** [comment]
> 
> The feature I miss the most currently is "search" or "filter". In ranger/joshuto, I could type `/` to start typing a folder name and go to it. Maybe it's possible in yazi but I couldn't find how ?
> 

There are two possibilities, provided you have the requirements installed. FD and ripgrep (rg). Those are executed with "s" and "S". 

You can consult (https://github.com/sxyazi/yazi/tree/main/config/preset) for default keycodes.

I hope this is of help.

**Comment by sxyazi** [comment]
Hi, thanks for the appreciation! Yazi integrates fzf and rg as the "search" feature; what you're looking for is called "find", which is documented in [Feature requests](https://github.com/sxyazi/yazi/issues/51), and I'll implement it sometime in the near future.

It's true that there's a lot of optimization potential in Yazi, such as dynamically loading file metadata, putting file sorting into a separate blocking threads pool, etc. It's a matter of finding the performance bottlenecks and optimizing for them, but I'll probably need to install a Nix before I can do that 🤣

Regarding the last point, does "yes or no" refer to the prompt triggered by quitting while there are still tasks left to complete?

**Comment by teto** [comment]
> what you're looking for is called "find", which is documented in https://github.com/sxyazi/yazi/issues/51, and I'll implement it sometime in the near future.

cool ! let me know if you need testers 

> Regarding the last point, does "yes or no" refer to the prompt triggered by quitting while there are still tasks left to complete?

Yes that's exactly it. I am not sure what/how I created the tasks but the message mentioned those.

**Comment by sxyazi** [comment]
You can press `w` key (the default) to see the tasks in progress

**Comment by sxyazi** [comment]
Done by https://github.com/sxyazi/yazi/pull/104, please give it a try!

**Comment by teto** [comment]
I am not sure what you meant by "filter" in the PR but here is what I would like to have in yazi, live update of the selected item upon keypress (it's enabled with `/` in ranger):

[Kooha-2023-09-06-00-08-33.webm](https://github.com/sxyazi/yazi/assets/886074/7634fe63-1fb6-4b97-afb4-7fae04008796)

NB: Kooha only worked with a fullscreen capture in my setup.

**Comment by sxyazi** [comment]
Oh, I think I understand what you mean now. I will see if this is complex and try to implement it.

**Comment by sxyazi** [comment]
Currently, Yazi performs chunk pre-loading when the cursor is hovered.

I am still considering whether it should be extended to direct opening -- this depends on whether the effect is noticeable.

You can try `cargo run -- /nix`, then navigate to the `store`, and enter it to see the effect.

**Comment by teto** [comment]
wow indeed I just tried it and it was instantaneous !!!! Never dreamed of it considering how slow ranger and joshuto were. I will get you champagne if you come to france ;)

**Comment by sxyazi** [comment]
Haha, thanks for your testing! I'm curious, how long does it take now? I only created 100,000 empty files for testing locally, and they take up almost no space. I'm not sure how it would perform under the pressure of 200GB. I haven't even installed NixOS yet 🤣

**Comment by teto** [comment]
it is faster than anything I can notice, so I would say <100ms.
