### ISSUE TITLE
copy directory name etc (c+...) don't function

### ISSUE THREAD

**Issue by tripleducky** [sxyazi/yazi#811]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot 1.16.2 and/or alacritty 0.12.

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### `yazi --debug` output

```sh
Add `disable_exec_warn = true` to your `yazi.toml` under `[headsup]` to suppress this warning.

Yazi
    yazi 0.2.4 (VERGEN_IDEMPOTENT_OUTPUT 1980-01-01)

Environment
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("foot", "")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect: Foot

Adaptor
    Adaptor.matches: Sixel

tmux
    TMUX: false

Zellij
    ZELLIJ_SESSION_NAME: None

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY: Some("wayland-1")
    DISPLAY: Some(":1")

Ueberzug
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false
```

### Describe the bug

pressing c+c or c+ ...) doesn't do anything.

### Expected Behavior

Would copy to my clipboard so I can paste it in the terminal or anywhere else.

### To Reproduce

Press c. dialog comes up suggesting keys to press. Press one of those keys. Exit yazi. ctrl+shift+v in terminal. A previous copied phrase appears.

### Configuration

I didn't edit anything related to this in my config.

### Anything else?

I searched through closed issues but the issue I found didn't have a solution that I could see.

**Comment by sxyazi** [comment]
Hi, do you have `wl-copy` installed? Yazi uses it to copy content to the clipboard under Wayland.

**Comment by tripleducky** [comment]
I'm embarassed thank you.

**Comment by tripleducky** [comment]
thanks

**Comment by tripleducky** [comment]
If anyone googles this later or whatever, for the record its called wl-cipboard not wl-copy.
