### ISSUE TITLE
Enter directory of files from search results.

### ISSUE THREAD

**Issue by wastee** [sxyazi/yazi#813]
### Please describe the problem you're trying to solve

Enter the directory of the file from the search results.

### Describe the solution you'd like

Press the Enter key in the search results view, then enter the file directory.

**Comment by tripleducky** [comment]
I think you can just press h or left arrow key to do that.

**Comment by wastee** [comment]
> I think you can just press h or left arrow key to do that.

I am such an idiot. It's a straightforward way to put it. Thank you!
