### ISSUE TITLE
Messy output after moving cursor

### ISSUE THREAD

**Issue by CarterLi** [sxyazi/yazi#815]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

iTerm 3.5.20240306-nightly

### Did you try the latest main branch to see if the problem got fixed?

Not tried, and I'll explain why below

### `yazi --debug` output

<details>

```sh
$ yazi --debug                                                                                                              USAGE
error: unexpected argument '--debug' found

  tip: to pass '--debug' as a value, use '-- --debug'

Usage: yazi [OPTIONS] [ENTRY]

For more information, try '--help'.
```

</details>

### Describe the bug

https://github.com/sxyazi/yazi/assets/6134068/964d8489-0b7a-48f2-8746-b2407fb6e764

### Expected Behavior

Screen doesn't go messy

### To Reproduce

`brew install yazi`

Run yazi and move cursor up and down

### Configuration

no config

My first yazi try with a clean yazi installed with brew.

### Anything else?

Also the theme doesn't seem to be good, notably the word `NORMAL` at the left bottom corner

**Comment by sxyazi** [comment]
Duplicate of https://github.com/sxyazi/yazi/issues/709, https://github.com/sxyazi/yazi/issues/760

Hi, this issue has been fixed in the latest version v0.2.4. Please upgrade to the latest version, https://github.com/sxyazi/yazi/releases/tag/v0.2.4

**Comment by CarterLi** [comment]
I'm sorry but I didn't notice that I installed an outdated version.

Homebrew usually upgrades formulae very fast. They upgrade my fastfetch in less than half a day, but I have no idea what happened to yazi.

**Comment by sxyazi** [comment]
The security policies of macOS have caused Yazi to get [stuck on Homebrew's testing CI](https://github.com/Homebrew/homebrew-core/pull/165615), and I'm not sure how to resolve it.

As for the visibility issue, v0.2.4 should have been greatly improved, but I still recommend choosing a theme that matches your terminal colors: https://github.com/yazi-rs/themes.

Anyway, glad to hear the problem has been resolved!
