### ISSUE TITLE
ya.notify API long string display bug

### ISSUE THREAD

**Issue by BBOOXX** [sxyazi/yazi#822]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

iTerm2 v3.4.23

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
Yazi
    yazi 0.2.4 (ca49a2d 2024-03-16)

Environment
    OS: macos-aarch64 (unix)
    Debug: true

Emulator
    Emulator.via_env: ("xterm-256color", "tmux")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Iterm2

Adaptor
    Adaptor.matches: Iterm2

tmux
    TMUX: true

Zellij
    ZELLIJ_SESSION_NAME: None

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false


```

</details>

### Describe the bug

```lua
ya.notify({
title = "Hello, World!",
content = "1234567890123456789012345678901234567890",
timeout = 6.5,
--level = "info",
})
```
<img width="324" alt="image" src="https://github.com/sxyazi/yazi/assets/7044834/10884865-d14d-485b-bf54-aa1bf9b25d05">

```lua
ya.notify({
title = "Hello, World!",
content = "12345678901234567890123456789012345678901",
timeout = 6.5,
--level = "info",
})
```
<img width="316" alt="image" src="https://github.com/sxyazi/yazi/assets/7044834/1d31e759-0787-4a9f-8528-87bc1cda0283">

```lua
ya.notify({
title = "Hello, World!",
content = "1234567890\n123456789012345678901234567890",
timeout = 6.5,
--level = "info",
})

```
<img width="320" alt="image" src="https://github.com/sxyazi/yazi/assets/7044834/08c3bee1-8f62-4e41-bb39-d1eaf03d2186">

```lua
ya.notify({
title = "Hello, World!",
content = "1234567890\n1234567890123456789012345678901",
timeout = 6.5,
--level = "info",
})
```

<img width="321" alt="image" src="https://github.com/sxyazi/yazi/assets/7044834/1d6b921f-5e7e-436b-82eb-cb3a3c175db1">

```lua
ya.notify({
title = "Hello, World!",
content = "1234567890\n1234567890\n12345678901234567890",
timeout = 6.5,
--level = "info",
})
```

<img width="328" alt="image" src="https://github.com/sxyazi/yazi/assets/7044834/8aa8fb90-f68d-4e9d-9a7c-02499cef0536">

```lua
ya.notify({
title = "Hello, World!",
content = "1234567890\n1234567890\n123456789012345678901",
timeout = 6.5,
--level = "info",
})
```
<img width="327" alt="image" src="https://github.com/sxyazi/yazi/assets/7044834/e6ac54b9-81c2-476b-ad69-fbb2adfeba0f">

🤔

### Expected Behavior

the correct and complete display of the full string.

### To Reproduce

Refer to the problem description

**Comment by Rolv-Apneseth** [comment]
Thanks for reporting - the examples were helpful
