### ISSUE TITLE
option to use bold variant of font for the interface

### ISSUE THREAD

**Issue by Aneeqasif** [sxyazi/yazi#825]
### Please describe the problem you're trying to solve

i think it looks visually appealinng. But you guyz have final say
![image](https://github.com/sxyazi/yazi/assets/78728701/a0e619db-c489-4b5a-9686-ae7221fe8be6)

![image](https://github.com/sxyazi/yazi/assets/78728701/51521665-3914-4ae4-a1a3-a901c1a1bd67)

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

An option to allow using bold font for the interface

**Comment by mikavilpas** [comment]
Hi, just to clarify, you mean either
- having everything in bold text (this would be a new feature)
- having everything in regular text (current behaviour)

Or do you mean only some parts of the ui should be bold?

**Comment by sxyazi** [comment]
Yup, just like @mikavilpas said, you can specify it in your `theme.toml` file with `bold = true`.

Closing as it's already supported.
