### ISSUE TITLE
Sort directories first does not work after re-sort

### ISSUE THREAD

**Issue by bertradio** [sxyazi/yazi#830]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.33

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh

```

</details>
Yazi
    yazi 0.2.4 (b10f2de 2024-03-09)

Environment
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect: Kitty

Adaptor
    Adaptor.matches: Kitty

tmux
    TMUX: false

Zellij
    ZELLIJ_SESSION_NAME: None

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY: None
    DISPLAY: Some(":0")

Ueberzug
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

### Describe the bug

In yazi.toml i set directories first. This works.

But if I sort within yazi using "," and then go back to an alpha or normal sort the directories sort within the files.

### Expected Behavior

When I return to an alpha or normal sort the directories should be first.

### To Reproduce

Start yazi with directories sorted first. Sort by something else, for example ",M". Then sort by alpha ",a". You will see the directories are no longer first

### Configuration

from yazi,toml:

sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true

### Anything else?

I just moved over from ranger and LOVE yazi. Still at the stage of configuring and learning. Still need to figure out how to preview MS Office and Open Office files. Was able to do it in ranger.

Also would like to be able to specify files or extensions to be included in hidden files as is possible with ranger. This is a nice way to hide directories.

Thanks for the great work!

**Comment by sxyazi** [comment]
Hi, the `sort` command has a `--dir-first` option, you can do something like this if you want to keep the directories on the top:

```
sort alphabetical --dir-first
```

Doc of `sort` command: https://yazi-rs.github.io/docs/configuration/keymap/#sort

> Still need to figure out how to preview MS Office and Open Office files

You can achieve this by configuring custom openers and previewers:

- Opener document: https://yazi-rs.github.io/docs/configuration/yazi#opener
- Previewers document: https://yazi-rs.github.io/docs/configuration/yazi#previewers

> Also would like to be able to specify files or extensions to be included in hidden files as is possible with ranger. This is a nice way to hide directories.

There's a request about it https://github.com/sxyazi/yazi/issues/694

**Comment by bertradio** [comment]
> Hi, the `sort` command has a `--dir-first` option, you can do something like this if you want to keep the directories on the top:
> 
> ```
> sort alphabetical --dir-first
> ```
> 
> Doc of `sort` command: https://yazi-rs.github.io/docs/configuration/keymap/#sort
> 
> > Still need to figure out how to preview MS Office and Open Office files
> 
> You can achieve this by configuring custom openers and previewers:
> 
> * Opener document: https://yazi-rs.github.io/docs/configuration/yazi#opener
> * Previewers document: https://yazi-rs.github.io/docs/configuration/yazi#previewers
> 
> > Also would like to be able to specify files or extensions to be included in hidden files as is possible with ranger. This is a nice way to hide directories.
> 
> There's a request about it #694

Thank you so much for the prompt response. The sort option does exactly what I need. I will check out the previewer options.

**Comment by bertradio** [comment]
For some reason the link to previewers API on the site does not work. 

Is there somewhere I could see an example?

Thanks

On Tue, Mar 19, 2024, at 09:10, 三咲雅 · Misaki Masa wrote:
> 
> 
> Hi, the `sort` command has a `--dir-first` option, you can do something like this if you want to keep the directories on the top:
> 
> `sort alphabetical --dir-first
`

**Comment by sxyazi** [comment]
Yeah, it's here https://yazi-rs.github.io/docs/plugins/overview#previewer

You can start by copying the [json.lua](https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/plugins/json.lua) file into your `~/.config/yazi/plugins/office.yazi/init.lua`, then replace the `jq` command within it with a command that can preview MS Office file.

**Comment by bertradio** [comment]
Perfect!

Thanks so much.
