### ISSUE TITLE
Bulk rename

### ISSUE THREAD

**Issue by Korygauger** [sxyazi/yazi#839]
### Please describe the problem you're trying to solve

Sorry if this has already been requested but having a bulk rename feature like in ranger would be great. That feature is the only reason why I open up ranger at all now. 
Also the naming/renaming prompt should be updated a bit so that I can use skip word (<C-left/right>) or delete word (<C-Backspace>) in the prompt because it feels kind of clunky to use to me right now. 

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

With the bulk rename I would like to highlight a a bunch of files then hit a key command, then be sent to a text editor to rename all of those files. It should be a text editor so that I can use vim and macros otherwise I might as well use the standard prompt.

**Comment by sxyazi** [comment]
Hi, this is a supported feature, see the documentation https://yazi-rs.github.io/docs/configuration/keymap/#manager.rename
