### ISSUE TITLE
Support <C-BackTab> in keymap.toml

### ISSUE THREAD

**Issue by Runeword** [sxyazi/yazi#840]
### Please describe the problem you're trying to solve

Add support for `<C-BackTab>` so we could use it in keymap.toml

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

```
[manager]
keymap = [
	{ on = [ "<C-BackTab>" ], exec = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
	{ on = [ "<C-Tab>" ], exec = "tab_switch 1 --relative",  desc = "Switch to the next tab" },
]
```

**Comment by sxyazi** [comment]
We have already supported `[`, which only needs one key press, isn't it better than `<C-BackTab>`? - it requires pressing 3 keys simultaneously: `Ctrl` + `Shift` + `Tab`.

https://github.com/sxyazi/yazi/blob/f8e0aee311a1828ba15ed16904fd388e3e3636e9/yazi-config/preset/keymap.toml#L135-L135

**Comment by Runeword** [comment]
Thanks for your feedback, I agree it's not the easiest key binding.
It is more specific to my workflow where I try to be consistent with other applications, such as browsers like chrome that use C-S-Tab to switch to the previous tab.

**Comment by Runeword** [comment]
Thanks, I've used `prepend_keymap` with the `<C-BackTab>` key binding, but it is not working, I'm on yazi 0.2.4.
```
prepend_keymap = [
     { on = ["<C-BackTab>"], run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
   ]
```

**Comment by sxyazi** [comment]
What terminal are you using? Some terminal emulators do not support `Ctrl+Shift+Tab`.

I tested Alacritty and Kitty, and they work; but WezTerm and iTerm2 do not - neither of them reported any key events to Yazi.

**Comment by Runeword** [comment]
Sorry, it was due to Tmux sending the wrong key sequence, it has nothing to do with yazi.
