### ISSUE TITLE
Produce LS_COLORS output when invoked with special flag

### ISSUE THREAD

**Issue by claes** [sxyazi/yazi#852]
### Please describe the problem you're trying to solve

I want to configure my environment so that ls and yazi uses the same colors for file listings

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I have seen the closed feature requests suggesting yazi to parse LS_COLORS and use that for configuration.

But perhaps an opposite approach can be considered? 

That yazi includes a command line option, which when invoked produces output compatible with the dircolors command. I.e something like

`# yazi --dircolors
LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*'; # etc...
export LS_COLORS
`

or just the actual value

`# yazi --dircolors
rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*
`

This way the yazi configuration is master and users could easily invoke it to set LS_COLORS during shell initialization. 

Since yazi supports configuring colors per mime-type it would need to know what extensions are commonly used per mimetype, so this may be a complication but a best-effort approach would go a long way

This suggestion may seem to be out of scope for yazi itself, but I think it could help increase adoption.

**Comment by sxyazi** [comment]
Hi, Yazi now has an ls-color theme, https://github.com/Mellbourn/ls-colors.yazi, that includes over 300 different file types, I recommend using it directly, it's based on [trapd00r/LS_COLORS](https://github.com/trapd00r/LS_COLORS) and should satisfy most users. 

![](https://raw.githubusercontent.com/Mellbourn/ls-colors.yazi/main/Screenshot.png)

If you have your own customized LS_COLORS, you can also convert it into a Yazi theme using the https://github.com/Mellbourn/lsColorsToToml script with just a few lines of command.

Let me know if these meet your needs!

**Comment by claes** [comment]
Hi, yes I found that while researching for solutions. I think it may be useful, but I also thought that this suggestion is more elegant in that you don't need to maintain multiple configurations and keep them in sync. I realized while looking for options that yazi has a flexible system to define the file colors that could be useful in more ways than just for "internal" yazi use.

**Comment by sxyazi** [comment]
> don't need to maintain multiple configurations and keep them in sync

What do you mean by multiple configuration files here?

> yazi has a flexible system to define the file colors that could be useful in more ways than just for "internal" yazi use

What does "internal use" refer to? Is it about Yazi's [Color](https://yazi-rs.github.io/docs/configuration/theme#types.color) and [Style](https://yazi-rs.github.io/docs/configuration/theme#types.style) system?

**Comment by claes** [comment]
> What do you mean by multiple configuration files here?

I mean, if I want to custom-style both ls and yazi, I need to create configuration LS_COLORS for ls first, run it through the program you suggested, and then update yazi's configuration. So I would have two configurations, although one manually updated from the other. If instead yazi could generate the LS_COLORS value from it's configuration, I would just need to configure yazi, and it would automatically generate LS_COLORS. Basically .bashrc could contain

export LS_COLORS=$(yazi --dircolors) 

or similar, and the user would immediately have ls colors in the same style as yazi.

> What does "internal use" refer to? Is it about Yazi's [Color](https://yazi-rs.github.io/docs/configuration/theme#types.color) and [Style](https://yazi-rs.github.io/docs/configuration/theme#types.style) system?

Yes exactly. What you have developed there is very similar to some of the projects that are specialized in generating LS_COLORS. Although it is only possible to use for yazi (it is internal to yazi so to say).

I understand if this is out of scope for yazi 
But it would be a very useful convenience function, simpler than running additional software to get a unified color experience.

**Comment by sxyazi** [comment]
I think Yazi's color system and LS_COLORS are not one-to-one mappings, this means that formats supported by Yazi cannot be represented in LS_COLORS, such as mime-type rule `{ mime = "text/*", fg = "#458ee6" }`, or `is` rules like `{ is = "link", fg = "#458ee6" }`.

This is also why I haven't added LS_COLORS support, I'm not sure how to make LS_COLORS and Yazi's color system coexist well, such as when a user wants to use LS_COLORS while also using the `is="link"` rule to highlight symlink files.

**Comment by claes** [comment]
I understand your point of view. I think it would be possible to make it to work, not perfectly, but quite well, but I understand if it is not in scope or a priority.

**Comment by sxyazi** [comment]
I've created a new issue that includes this one, closing in favor of https://github.com/sxyazi/yazi/issues/914
