### ISSUE TITLE
Preserve timestamp

### ISSUE THREAD

**Issue by cdtut** [sxyazi/yazi#863]
### Please describe the problem you're trying to solve

`y` and `x` changes file attribute like timestamp after `p`.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

All actions in yazi should always keep all original attribute.

**Comment by sxyazi** [comment]
> All actions in yazi should always keep all original attribute.

‘All actions’ is vague to me. Please list all the operations you want to keep track of. 

And should it be the default behavior? Should the previous behavior be preserved (e.g., by adding a different configuration option)? It would be very useful if you could provide some implementations of other file managers for me to use as a reference.

**Comment by cdtut** [comment]
Copy file should be like `cp --preserve=all`. Move should be like `mv` which doesn't change anything on file. Other file manager like ranger do that.

It should be default. Previous behavior should not be there, you would never expect moving file to change anything.

**Comment by sxyazi** [comment]
Thanks for the explanation, but why should `copy` be like `cp --preserve=all` instead of just `cp`, if `move` is like `mv`?

I just tested locally, and the default behavior of `cp` (without `--preserve=all`) does not preserve timestamps. Why should we preserve them?

**Comment by sxyazi** [comment]
Sounds good to me.

Does anyone want to give it a try? `copy_with_progress` should be the only place that needs to be changed:

https://github.com/sxyazi/yazi/blob/e7dc971416af2c59b0d1498579102318885642ca/yazi-shared/src/fs/fns.rs#L37

**Comment by alexandruoprinca** [comment]
I cannot seem reproduce the issue on MacOS.
I ran the app locally both in debug and release mode (not that it would matter for this particular scenario)
I tried to copy the project README and rustfmt. For the rustfmt i also cut it and pasted it again
This is the output after a ls:
`user@192-168-0-0 yazi % date
Wed Apr 10 19:19:06 EEST 2024
user@192-168-0-0 yazi % ls -al
total 264
drwxr-xr-x  32 user  staff   1024 Apr 10 19:15 .
drwxr-xr-x@ 41 user  staff   1312 Apr 10 19:13 ..
-rw-r--r--@  1 user  staff   6148 Apr 10 19:15 .DS_Store
-rw-r--r--   1 user  staff      9 Apr 10 11:09 .envrc
drwxr-xr-x  12 user  staff    384 Apr 10 11:09 .git
drwxr-xr-x   4 user  staff    128 Apr 10 11:09 .github
-rw-r--r--   1 user  staff     85 Apr 10 11:09 .gitignore
-rw-r--r--   1 user  staff  73151 Apr 10 11:09 Cargo.lock
-rw-r--r--   1 user  staff    200 Apr 10 11:09 Cargo.toml
-rw-r--r--   1 user  staff   1065 Apr 10 11:09 LICENSE
-rw-r--r--   1 user  staff   4719 Apr 10 11:09 README.md
-rw-r--r--   1 user  staff   4719 Apr 10 11:09 README_1.md
drwxr-xr-x   4 user  staff    128 Apr 10 11:09 assets
-rw-r--r--   1 user  staff   1444 Apr 10 11:09 cspell.json
-rw-r--r--   1 user  staff   2100 Apr 10 11:09 flake.lock
-rw-r--r--   1 user  staff   1555 Apr 10 11:09 flake.nix
drwxr-xr-x   4 user  staff    128 Apr 10 11:09 nix
-rw-r--r--   1 user  staff   1154 Apr 10 11:09 rustfmt.toml
-rw-r--r--   1 user  staff   1154 Apr 10 11:09 rustfmt_1_1.toml
drwxr-xr-x   5 user  staff    160 Apr 10 11:09 scripts
drwxr-xr-x   3 user  staff     96 Apr 10 11:09 snap
drwxr-xr-x@  6 user  staff    192 Apr 10 19:13 target
drwxr-xr-x   4 user  staff    128 Apr 10 11:09 yazi-adaptor
drwxr-xr-x   5 user  staff    160 Apr 10 11:09 yazi-boot
drwxr-xr-x   5 user  staff    160 Apr 10 11:09 yazi-config
drwxr-xr-x   4 user  staff    128 Apr 10 11:09 yazi-core
drwxr-xr-x   4 user  staff    128 Apr 10 11:09 yazi-dds
drwxr-xr-x   4 user  staff    128 Apr 10 11:09 yazi-fm
drwxr-xr-x   5 user  staff    160 Apr 10 11:10 yazi-plugin
drwxr-xr-x   4 user  staff    128 Apr 10 11:10 yazi-proxy
drwxr-xr-x   4 user  staff    128 Apr 10 11:10 yazi-scheduler
drwxr-xr-x   4 user  staff    128 Apr 10 11:10 yazi-shared`

**Comment by sxyazi** [comment]
Hi, I tested it in my Linux VM, and it did change the file's timestamp:
```
-rw-r--r--  1 ika ika  1555 Dec 27 17:07 flake.nix
-rw-r--r--  1 ika ika  1555 Apr 11 00:54 flake_1.nix
```

I think this should be the different behavior exhibited by Rust's std::fs::copy() [on different platforms](https://doc.rust-lang.org/std/fs/fn.copy.html#platform-specific-behavior).
