### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by guo335864019** [sxyazi/yazi#864]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

iterm2

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
➜  ~ yazi -- debug
thread 'main' panicked at yazi-config/src/keymap/keymap.rs:85:59:
called `Result::unwrap()` on an `Err` value: Error { inner: Error { inner: TomlError { message: "missing field `exec`", original: Some("\"$schema\" = \"https://yazi-rs.github.io/schemas/keymap.json\"\n\n[[manager.keymap]]\non = [\"<Esc>\"]\nrun = \"escape\"\ndesc = \"Exit visual mode, clear selected, or cancel search\"\n\n.....
```

</details>

### Describe the bug

I just install yazi with homebrew,and copy preset config files to my mac,then just run yazi,but failed.

### Expected Behavior

run yazi 

### To Reproduce

brew install yazi ffmpegthumbnailer unar jq poppler fd ripgrep fzf zoxide
then
copy the preset config files to ~/.conifg/yazi/
$ yazi

**Comment by sxyazi** [comment]
For some reason, Homebrew is not up to date. Please upgrade your Yazi to the latest version. You can [download the official binary](https://yazi-rs.github.io/docs/installation#official-binaries) directly or [use Cargo to install it](https://yazi-rs.github.io/docs/installation#cargo).
