### ISSUE TITLE
add a manpage

### ISSUE THREAD

**Issue by teto** [sxyazi/yazi#870]
### Please describe the problem you're trying to solve

```
➜ man yazi       
No manual entry for yazi
```
is sad. Yazi has so many features an offline doc is helpful

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

generate a manpage

**Comment by sxyazi** [comment]
Hi, you can download the [Yazi documentation](https://github.com/yazi-rs/yazi-rs.github.io/tree/main/docs) to your local machine and use any tool you like to view them. Let me know if this can meet your needs!

Perhaps we can explore converting these Markdown files into manpage format, but I'm not sure if the result would be ideal or if it's worth it.

**Comment by teto** [comment]
> you can download the [Yazi documentation](https://github.com/yazi-rs/yazi-rs.github.io/tree/main/docs?rgh-link-date=2024-04-04T09%3A07%3A51Z) to your local machine and use any tool you like to view them. Let me know if this can meet your needs!

it's true for much software, yet software usually have their manpage because it's standardized and convenient for the users and the package maintainers. It's not critical but I thought I would raise the point as `yazi --help` can't cover all the features in yazi.
I try a lot of software for different reasons, and I've grown attached to manpages xD

**Comment by ccoVeille** [comment]
I second @teto point of view

when I type man whatever I expect to see the help

each app implements things differently

```
whatever --help
whatever -help
whatever -h
whatever help
```

having a man page is a decent thing, even if the man page simply mentions the app name and the argument to launch to get the help

**Comment by sxyazi** [comment]
> having a man page is a decent thing, even if the man page simply mentions the app name and the argument to launch to get the help

It's already there, when you type `yazi --help`, you will be able to see the application name and the list of launchable parameters:

```sh
❯ yazi --help
Usage: yazi [OPTIONS] [ENTRY]

Arguments:
  [ENTRY]  Set the current working entry

Options:
      --cwd-file <CWD_FILE>            Write the cwd on exit to this file
      --chooser-file <CHOOSER_FILE>    Write the selected files to this file on open fired
      --clear-cache                    Clear the cache directory
      --local-events <LOCAL_EVENTS>    Report the specified local events to stdout
      --remote-events <REMOTE_EVENTS>  Report the specified remote events to stdout
      --debug                          Print debug information
  -V, --version                        Print version
  -h, --help                           Print help
```

**Comment by sxyazi** [comment]
I played around with it a bit, and converted these markdown files to manpage format using [`pandoc`](https://pandoc.org/). Although a lot of information was lost (anchors, images, videos, etc.), it works. Here is the converted file:


[yazi.1.zip](https://github.com/sxyazi/yazi/files/14886801/yazi.1.zip)

You can preview it by running:

```sh
man ./yazi.0
```

**Comment by ccoVeille** [comment]
You closed the ticket, but I don't see any issue or pull request about this.

When will it be added ?
