### ISSUE TITLE
History for shell commands

### ISSUE THREAD

**Issue by lomaharshana** [sxyazi/yazi#873]
### Please describe the problem you're trying to solve

Currently the shell command execution doesn't maintain history, so the user needs to re-type the past commands in 'shell' textbox.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Please add a feature to maintain shell command history, which can be recalled with up-down arrow keys. (Similar to vim command history).

**Comment by sxyazi** [comment]
Hi, it's already included in the [Feature Requests](https://github.com/sxyazi/yazi/issues/51), but I haven't found time to implement it yet. PRs are highly welcome!

Closing as duplicate
