### ISSUE TITLE
Disk Usage Analyzer

### ISSUE THREAD

**Issue by sxzz** [sxyazi/yazi#88]
Like project https://github.com/dundee/gdu, I think it's great to integrate with disk usage analyzer.

At least, adding the file/directory size and sort by size.

**Comment by sxyazi** [comment]
Sorting files/directories by size is currently supported, and directory sizes are only calculated lazily if you switch the sort method as size by (default) pressing `,s` or `,S`, or configure it in `yazi.toml` permanently.

https://github.com/sxyazi/yazi/blob/main/config/docs/yazi.md#manager

**Comment by sxzz** [comment]
Great, there's also one thing we can do is when sorting by size, we can note the size on the right of file list.

**Comment by sxyazi** [comment]
Yep, this is a thing that can be improved. I will add it to the Feature Requests and close this issue then in favor of that list.
