### ISSUE TITLE
Opening multiple files through yazi, does not open the files in an alphabetical order.

### ISSUE THREAD

**Issue by ThGrSoRu** [sxyazi/yazi#889]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot version: 1.17.0 +pgo +ime +graphemes -assertions

### Did you try the latest main branch to see if the problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.4 (884de41 2024-04-08)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("foot", "")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect: Foot

Adaptor
    Adaptor.matches: Sixel

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY: Some("wayland-1")
    DISPLAY: Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/bin/fish")
    EDITOR: Some("micro")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.45\nmagic file from /usr/share/file/misc/magic\nseccomp support included\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "micro \"$@\"", block: true, orphan: false, desc: "micro", for_: None, spread: true })
    block: Some(Opener { run: "micro \"$@\"", block: true, orphan: false, desc: "micro", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

```

</details>

### Describe the bug

Opening multiple files through yazi, causes the order in which the files are opened to be non-alphabetical.
Opening the files through a shell, like `mpv ./*`, orders the files alphabetically (correctly).

### Expected Behavior

Files are ordered alphabetically.

### To Reproduce

See above.

**Comment by sxyazi** [comment]
Hi, is it work to do `mpv ./*` directly in the shell without Yazi? 

I don't think there's a factor in this command that affects the order, Yazi does this work in the background: `sh -c "mpv ./*"`

**Comment by ThGrSoRu** [comment]
Using `mpv ./*` in the shell causes the correct behaviour, meaning the files are played alphabetically in mpv.
Using `sh -c "mpv ./*"` also plays the files alphabetically in mpv.

**Comment by sxyazi** [comment]
What is your opener rule for video files?

**Comment by ThGrSoRu** [comment]
For videos and images: `{run='mpv "$@"',orphan=true},`.
For audio: `{run='foot mpv "$@"',orphan=true},`.

**Comment by ThGrSoRu** [comment]
The issue occurs with videos,images,audio,text files opened with micro,midi files opened with fluidsynth.
So all filetypes and openers are probably affected.

**Comment by sxyazi** [comment]
Ah I see, this should be related to `$@`, will investigate it.

**Comment by sxyazi** [comment]
Please try this PR, https://github.com/sxyazi/yazi/pull/890

**Comment by ThGrSoRu** [comment]
Using `Yazi 0.2.4 (3beeefe 2024-04-09)`.

I selected all files from top to bottom, using natural sorting with directories first and opened them multiple times to confirm a pattern.
This was the order of files played in mpv, everytime I opened them as stated above.
The first file listed was always the first file played in mpv.
```
I'm My Own Master Now (Phase 4).wav
I'm My Own Master Now (Phase 1).wav
I'm My Own Master Now (Phase 2).wav
I'm My Own Master Now (Phase 3).wav
```
```
A Stranger I Remain (Phase 1).wav
A Stranger I Remain (Phase 2).wav
A Stranger I Remain (Phase 4).wav
A Stranger I Remain (Phase 3).wav
```
```
The Stains of Time (Phase 1).wav
The Stains of Time (Phase 2).wav
The Stains of Time (Phase 3).wav
```
After quitting and opening yazi another time, the ordering was different for the same files.
```
I'm My Own Master Now (Phase 3).wav
I'm My Own Master Now (Phase 4).wav
I'm My Own Master Now (Phase 2).wav
I'm My Own Master Now (Phase 1).wav
```
```
A Stranger I Remain (Phase 1).wav
A Stranger I Remain (Phase 3).wav
A Stranger I Remain (Phase 2).wav
A Stranger I Remain (Phase 4).wav
```
```
The Stains of Time (Phase 3).wav
The Stains of Time (Phase 1).wav
The Stains of Time (Phase 2).wav
```

It seems that the ordering is "seeded" on every startup.

**Comment by sxyazi** [comment]
Hi, I pushed a new commit, please try it again

**Comment by ThGrSoRu** [comment]
That seems to have corrected it. All files are now opened in the order they were selected.
Huge thanks!
