### ISSUE TITLE
Ability to change yazi CWD from external process

### ISSUE THREAD

**Issue by z0rc** [sxyazi/yazi#891]
### Please describe the problem you're trying to solve

Practical use case.

From yazi exec to shell, shell starts in the same dir as yazi cwd, in shell cd to other dir, exit shell, yazi should be in last cwd from shell.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Some kind of protocol to allow external processes execute yazi commands. Might be a part of DDS.

### Additional context

This isn't a unique feature. MC implements it [natively](https://github.com/MidnightCommander/mc/blob/4.8.31/src/subshell/common.c#L1071-L1186), Ranger allows user to implement it via [IPC](https://github.com/ranger/ranger/blob/master/examples/plugin_ipc.py) and [shell hook on exit](https://github.com/z0rc/dotfiles/blob/main/zsh/rc.d/09_file_managers.zsh#L51-L57).

**Comment by sxyazi** [comment]
Docs added to https://yazi-rs.github.io/docs/dds/#cli and https://yazi-rs.github.io/docs/dds/#dds.lua
