### ISSUE TITLE
Allow to specify a "trash" command

### ISSUE THREAD

**Issue by Allaman** [sxyazi/yazi#892]
### Please describe the problem you're trying to solve

Hi, 

I am coming from Lf, and it is outstanding how much yazi can do ootb! How ever, I am missing one thing from Lf. In Lf I have defined the trash command to use [trash-cli](https://github.com/andreafrancia/trash-cli). It would be nice to have the option to define a delete command with yazi, too.

I have trash aliased to `rm` and my Neovim config also uses trash for deleting files, so my trash is consistent in `.local/share/Trash/files`. Currently, yazi puts the files in the mac bin, which is probably fine for 99% out there, but I cannot restore files via `trash-restore` 😆 

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Something like an optional trash_cmd = trash

**Comment by sxyazi** [comment]
Hi, you can achieve it using the [`shell` command](https://yazi-rs.github.io/docs/configuration/keymap#manager.shell), like this:

```sh
{ on = [ "d" ], run = '''
    shell --confirm 'trash-put "$@"'
''' }
```

It will invoke `trash-put` to move the selected file to the trash. If you want it to be more secure, you can remove the `--confirm` parameter, which will wait for an `Enter` key press before actually executing. 

You can also implement it as a plugin by calling [`ya.input()`](https://github.com/sxyazi/yazi/pull/762) to achieve the same prompt style as the built-in trash. Let me know if it works for you!

**Comment by Allaman** [comment]
OMG, what a remarkable software! It works. Thank you very much!
