### ISSUE TITLE
Can't show directory size in linemode

### ISSUE THREAD

**Issue by majutsushi** [sxyazi/yazi#897]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty 0.30.1

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
$ yazi --debug
Yazi
yazi 0.2.4 (VERGEN_IDEMPOTENT_OUTPUT 2024-03-10)

Environment
OS: linux-x86_64 (unix)
Debug: false

Emulator
Emulator.via_env: ("xterm-kitty", "")
Emulator.via_csi: Ok(Kitty)
Emulator.detect: Kitty

Adaptor
Adaptor.matches: Kitty

tmux
TMUX: false

Zellij
ZELLIJ_SESSION_NAME: None

Desktop
XDG_SESSION_TYPE: Some("x11")
WAYLAND_DISPLAY: None
DISPLAY: Some(":0")

Ueberzug
Version: Ok(Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "Usage:\n    ueberzug layer [options]\n    ueberzug library\n    ueberzug version\n    ueberzug query_windows PIDS ...\n" })

WSL
/proc/sys/fs/binfmt_misc/WSLInterop: false


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/jan/.local/state/yazi" directory.
```

</details>

### Describe the bug

I'm not entirely sure if this is a bug, but it does seem to contradict the documentation as I understand it.

The default `linemode` function does this if it set to `size`:
```
			local size = f:size()
			spans[#spans + 1] = ui.Span(size and ya.readable_size(size) or "")
```

The documentation for the `size()` method says this:
> size() - The size of this file, returns an integer representing the size in bytes, or nil if its a directory and it has not been scanned

However, this method always returns `nil` for me for directories, even after I have descended into the directories (which presumably implies that they got scanned). In addition the `ya.readable_size()` function wouldn't really make sense for parsing the size of a directory (assuming that "size" means the number of files in it).

### Expected Behavior

Show the size (number of files) of a directory in the linemode

### To Reproduce

Open a directory with subdirectories

### Anything else?

It would be really useful if yazi could show the number of files in subdirectories, just like Ranger does. It would be totally fine if this information was gathered in a lazy/async way, or maybe even just after you have "hovered" over a directory.

**Comment by sxyazi** [comment]
Hi, the `size()` method here refers to the byte size of a file, not the number of files. But it currently has some usage limitations, see https://github.com/sxyazi/yazi/discussions/492

I'll create a PR to add more details to the document.

**Comment by sxyazi** [comment]
Done in https://github.com/yazi-rs/yazi-rs.github.io/commit/530091df74b72754df646e01a6e3e0c2e24e3043

**Comment by majutsushi** [comment]
Thanks, that's much clearer! I also saw that someone just posted in #51 exactly what I would like, simply showing the number of files in a directory by default. The actual (recursive) size could then be calculated following some kind of user action.

**Comment by sxyazi** [comment]
> I also saw that someone just posted in https://github.com/sxyazi/yazi/issues/51 exactly what I would like, simply showing the number of files in a directory by default. The actual (recursive) size could then be calculated following some kind of user action.

Sounds good to me, I'll consider adding it.
