### ISSUE TITLE
Respect EDITOR environment variable

### ISSUE THREAD

**Issue by cloudlena** [sxyazi/yazi#90]
Currently, when opening a text file, Yazi just seems to try to use `vim` to open it. It would be great if instead it was referring to the `EDITOR` environment variable and use that value instead, with a fallback of `vim` if the variable is not set.

**Comment by sxyazi** [comment]
Sorry, I may not add it for the following reasons:

- `EDITOR` seems to be a Unix-specific variable, that doesn't exist for Windows. (Yazi for Windows coming soon!)
- You can use your own config file -- copy [`yazi.toml`](https://github.com/sxyazi/yazi/blob/main/config/preset/yazi.toml) to `~/.config/yazi/yazi.toml`, and [modify the text opener as you like](https://github.com/sxyazi/yazi/blob/a36dabfe8503fd96f3ab398466d1491384ff6d6e/config/preset/yazi.toml#L23)

**Comment by cloudlena** [comment]
Thanks for your quick reply, @sxyazi!
It pretty much seems like a very established standard on Unix systems, so it would be a pity if that didn't work. Couldn't we implement it as I suggested above, with using `vim` as a default if the `EDITOR` environment variable is not set? I think, by doing so, it wouldn't make a difference for Windows users but allow us to implement this de facto standard for Unix systems :smiley:

**Comment by sxyazi** [comment]
In fact, Yazi currently has support for it by simply modifying:

```toml
text = [
	{ exec = 'vim "$1"', block = true },
]
```

to:

```toml
text = [
	{ exec = '$EDITOR "$1"', block = true },
]
```

I can change it in the preset config, but it's unclear if this applies to all users.

Perhaps I could add it to the preset first, and make a conditional constraint in the following format later when the Windows version comes out:

```toml
text = [
	{ exec = '$EDITOR "$1"', block = true, for = "unix" }
]
```

**Comment by cloudlena** [comment]
That would be awesome! :rocket:
