### ISSUE TITLE
Store video thumbnails

### ISSUE THREAD

**Issue by Gajus84** [sxyazi/yazi#92]
Please correct me if I'm mistaken, but it seems like Yazi is saving video thumbnails only for the current session. Depending on the amount of (video) files this can grow into a major bottleneck. Especially when using the Wrapper. 

LF and Ueberzug++ are solving this by storing the generated thumbnails in the users tmp/cache directory and using those as a source (via the videos path afaik) before calling ffmpegthumbnailer again. That's ofc much quicker.

I believe that could be a good approach to follow by yazi too?

**Comment by sxyazi** [comment]
Hey, Yazi not only caches and reuses all thumbnails of images, videos, PDFs, etc. but also downscales them in advance asynchronously, so there should be no bottleneck here.

You can run `yazi --clear-cache` with the latest HEAD code to clear the existing cache and see the path of those cached files.

**Comment by Gajus84** [comment]
Thanks! The clear-cache did the trick, now it works again. Do I need to do that every time I rebuild or was this related to the latest refactoring commit?

**Comment by Gajus84** [comment]
> 
> This may be exactly why your cache is failing, good idea, I'll add it, but it may require you to delete the cache periodically to prevent size inflation as it doesn't go away after a reboot

That's why I thought making it optional is the better way. It's perfectly reasonable not to "clutter" the user's system by default.

Thank you again, for your great support!
