### ISSUE TITLE
Option to filter by MIME type category

### ISSUE THREAD

**Issue by xxyxxyxyx1** [sxyazi/yazi#924]
### Please describe the problem you're trying to solve

I would like to filter by all the images in a directory. 

Perhaps this could be accomplished by searching for a string within all file MIME types. Images, for example, have MIME types that begin with `image/` such as `image/jpeg`, `image/vnd.microsoft.icon`, `image/svg+xml`, `image/png`, etc. 

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

I would like to type some shortcut or command, then type a string, e.g. `image`, to filter all files that have a MIME type containing that string. It could be similar to the current `f` filter command.

**Comment by sxyazi** [comment]
Hi, the mime-type isn't an inherent property of files, it needs to be calculated for each file, which is a time-consuming operation, especially for directories with many images and videos.

Currently, Yazi lazily computes them, only calculating the mime-types for a few files on the current page. However, the requested feature of "filtering files by MIME type" would require calculating the mime-types for all files at once, which would consume a considerable amount of time and computational resources.

This wouldn't provide a good user experience, so I've decided not to add it, sorry. I recommend using file extensions for filtering instead. Yazi's `filter` command supports regular expressions, so theoretically, you can achieve it using a powerful expression syntax.

You can also implement it in a programmable way through the plugin system; Yazi allows you to [access all file information](https://yazi-rs.github.io/docs/plugins/types#app-data) via the plugin API.

Closing as not in the plan.

**Comment by sxyazi** [comment]
Sorry for the late reply. 

You can add the `filter_do` command to your `keymap.toml` to implement it: 

```
{ on = [ "F" ], run = 'filter_do "\.(jpg|png|gif)$" --smart --done' }
```

Note that this command is still unstable, which means its parameters might change in the future, but you can use it for now.
