### ISSUE TITLE
Windows下在yazi内切换盘符后图片预览不能正常工作

### ISSUE THREAD

**Issue by BusyPacket** [sxyazi/yazi#936]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Wezterm

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
Yazi
    yazi 0.2.4 (b10f2de 2024-03-09)

Environment
    OS: windows-x86_64 (windows)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: WezTerm

Adaptor
    Adaptor.matches: Iterm2

tmux
    TMUX: false

Zellij
    ZELLIJ_SESSION_NAME: None

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

Ueberzug
    Version: Err(Error { kind: NotFound, message: "program not found" })

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "C:\\Users\\hsh\\AppData\\Roaming\\yazi\\state" directory.
```

</details>

### Describe the bug

在powershell中，我在C盘进入yazi，可以正常预览图片，如果我在yazi内切换到D盘，则不显示图片预览
但如果先在powershell中切换盘符再进入pazi，则没有这个问题

### Expected Behavior

在yazi中切换盘符后，图片预览正常工作

### To Reproduce

在powershell中，进入yazi，可以正常预览图片，在yazi内切换到D盘，则不显示图片预览

**Comment by sxyazi** [comment]
Yazi is an international project, please use English
