### ISSUE TITLE
Picture preview cannot work properly after switching drive letters in yazi

### ISSUE THREAD

**Issue by BusyPacket** [sxyazi/yazi#939]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

Wezterm

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
Yazi
    yazi 0.2.4 (b10f2de 2024-03-09)

Environment
    OS: windows-x86_64 (windows)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: WezTerm

Adaptor
    Adaptor.matches: Iterm2

tmux
    TMUX: false

Zellij
    ZELLIJ_SESSION_NAME: None

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

Ueberzug
    Version: Err(Error { kind: NotFound, message: "program not found" })

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "C:\\Users\\hsh\\AppData\\Roaming\\yazi\\state" directory.
```

</details>

### Describe the bug

When entering yazi on the C drive, you can preview the images on the C drive normally, but if you switch to the D drive within yazi, the image preview function will become invalid. Switching drive letters before entering yazi will not have this issue

### Expected Behavior

After switching drive letters in yazi, the image preview works normally

### To Reproduce

Entering yazi allows you to preview images normally, but switching drive letters within yazi does not display image previews

**Comment by sxyazi** [comment]
Please record a GIF to let me see your steps

**Comment by BusyPacket** [comment]
![gif](https://github.com/sxyazi/yazi/assets/72989817/35147599-8afc-425e-9ae8-290d111afd30)

**Comment by sxyazi** [comment]
Can you upload your keymap.toml? It seems there are some issues with the key bindings.

**Comment by BusyPacket** [comment]
This is my keymap.toml
```
# Goto
	{ on = [ "g", "h" ],       run = "cd ~",             desc = "Go to the home directory" },
	{ on = [ "g", "c" ],       run = "cd ~/.config",     desc = "Go to the config directory" },
	{ on = [ "g", "d" ],       run = "cd ~/Downloads",   desc = "Go to the downloads directory" },
	{ on = [ "g", "t" ],       run = "cd /tmp",          desc = "Go to the temporary directory" },
	{ on = [ "g", "<Space>" ], run = "cd --interactive", desc = "Go to a directory interactively" },
	{ on = [ "g", "C" ], run = "cd C:", desc = "Go to C part" },
	{ on = [ "g", "D" ], run = "cd D:", desc = "Go to D part" },
	{ on = [ "g", "E" ], run = "cd E:", desc = "Go to E part" },

	# Help
	{ on = [ "~" ], run = "help", desc = "Open help" },

```

**Comment by sxyazi** [comment]
Does `cd 'D:\\'` work for you?

**Comment by BusyPacket** [comment]
The problem has been solved. Thank you very much. I am not very clear about the difference between `D:` and `D:\\`
