### ISSUE TITLE
Unable to preview text files with encoding other than utf-8

### ISSUE THREAD

**Issue by MasouShizuka** [sxyazi/yazi#942]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

wezterm 20240203-110809-5046fc22

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh
Yazi
    Version: 0.2.5 (c65a14c 2024-04-23)
    OS: windows-x86_64 (windows)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: WezTerm

Adaptor
    Adaptor.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("C:\\msys64\\usr\\bin\\zsh.exe")
    EDITOR: Some("nvim")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: Some("C:/Program Files/Git/usr/bin/file.exe")
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(ExitStatus(0)), stdout: "file-5.45\nmagic file from /usr/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "code \"%*\"", block: false, orphan: true, desc: "code", for_: None, spread: true })
    block: Some(Opener { run: "code -w \"%*\"", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Error { kind: NotFound, message: "program not found" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "C:\\Users\\MasouShizuka\\AppData\\Roaming\\yazi\\state" directory.
```

</details>

### Describe the bug

When switching to `UTF-8` encoded text files, the preview works correctly.
But when switching to other encodings, such as `gbk`, the preview is blank.

I tested on both `windows` and `wsl` with the same results.
Did I miss some settings?

### Expected Behavior

The preview works fine.

### To Reproduce

Create a new file utf-8 encoded file `utf-8.txt` with the following content:
```
测试行1
测试行2
测试行3
```
Switch to the `utf-8.txt` file, and the preview on the right displays the file content normally.

Create a new `gbk` encoded file with the same content and switch to the file. The preview on the right is empty.

**Comment by sxyazi** [comment]
Reported to the upstream, closing in favor of https://github.com/Byron/trash-rs/issues/105

**Comment by sxyazi** [comment]
Oops replied to the wrong issue, they were both UTF-8 problems, reopened.
