### ISSUE TITLE
Strange behavior with DDS Session Plugin

### ISSUE THREAD

**Issue by Gajus84** [sxyazi/yazi#947]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot 1.17.2

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>
Yazi
    Version: 0.2.5 (Arch Linux 2024-04-25)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect: Foot

Adaptor
    Adaptor.matches: Sixel

Desktop
    XDG_SESSION_TYPE: Some("wayland")
    WAYLAND_DISPLAY: Some("wayland-1")
    DISPLAY: Some(":0")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("zsh")
    EDITOR: Some("hx")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: Some("/home/gajus/.config/yazi")

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.45\nmagic file from /usr/share/file/misc/magic\nseccomp support included\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "[ -n \"chezdit\" ] &&  chezdit \"$@\"", block: true, orphan: false, desc: "chezdit", for_: None, spread: true })
    block: Some(Opener { run: "[ -n \"chezdit\" ] &&  chezdit \"$@\"", block: true, orphan: false, desc: "chezdit", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "ueberzugpp 2.9.4\n", stderr: "" })

</details>

### Describe the bug

After a new start the sync feature is not working between different yazi-instances. This changes after renaming the config-folder and starting a new instance. Then sync starts working and does until restart. 

That includes closing all instances, deleting the newly generated config folder, renaming the old one back and starting of new instances with my custom config.

### Expected Behavior

Sync feature works without that "workaround"

### To Reproduce

Hard to say, as I have no idea of the root cause. Maybe trying the sync feature in a Hyprland environment as well.

### Anything else?
Edit:
Without custom configs (else then init.lua) it seems to work. So it is my config. But only on startup.

**Comment by sxyazi** [comment]
Hi, is it possible to provide a GIF to let me see what happens?

Also make sure that when using DDS, all instances of Yazi running are of the same version, and kill any previous background processes by running `killall yazi`, as I recently received reports on the Yazi Telegram that DDS is not working due to running two different versions of Yazi. I will add version checking in the next release, but for now, please manually kill them.

**Comment by Gajus84** [comment]
I narrowed it down. It's setting

`cache_dir  = "/home/gajus/.cache/yazi/"` in yazi.toml

If this is set empty (like in the example conf) it will work. Yazi only needs to be started once with this empty setting, then I can switch it to my custom cache_dir and DDS will still work.

Afterwards, as long as I don't reboot the whole system, it will continue to work. "Killall yazi" included.

**Comment by Gajus84** [comment]
I believe I found the root cause.

With a custom cache_dir no /tmp/yazi/ is created. So DDS can not write the socket-info in it. If the /tmp/yazi folder is created manually and a new instance of yazi is started /tmp/yazi/.dds-1000.sock will be created and ofc DDS will then work as intended.

**Comment by sxyazi** [comment]
Thanks for the thorough investigation! I think I've figured out the cause of the issue, I'll create a patch for it soon.

**Comment by sxyazi** [comment]
Please try https://github.com/sxyazi/yazi/pull/956

**Comment by Gajus84** [comment]
Yes, fixes the issue. Thanks for the quick help :)

**Comment by sxyazi** [comment]
Nice to hear that, let me merge the PR now
