### ISSUE TITLE
Documentation website search does not work

### ISSUE THREAD

**Issue by xxyxxyxyx1** [sxyazi/yazi#949]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

web browser

### Did you try the latest code to see if this problem got fixed?

Not tried, and I'll explain why below

### `yazi --debug` output

n/a

### Describe the bug

The search feature of the documentation website returns no results when results do exist. 

For example, searching `fzf` gives no results, when `fzf` is certainly mentioned in the website:
[https://yazi-rs.github.io/search?q=fzf](https://yazi-rs.github.io/search?q=fzf)
![image](https://github.com/sxyazi/yazi/assets/25559220/38999947-8bf7-406f-bd6b-756e14a1d9d2)

### Expected Behavior

Search results are provided

### To Reproduce

Search for something in the documentation website

### Configuration

I have tried with current Firefox and current Vivaldi browsers

**Comment by sxyazi** [comment]
Please move this issue to https://github.com/yazi-rs/yazi-rs.github.io repository
