### ISSUE TITLE
be able to open yazi at arbitrary path

### ISSUE THREAD

**Issue by teto** [sxyazi/yazi#95]
I would like to be able to do `yazi ~/Downloads` and have yazi open with `~/Downloads` as the current folder similar to what ranger can do ( `ranger ~/Downloads` works)

**Comment by sxyazi** [comment]
I think you can use `yazi -c ~/Downloads` to do the same thing with ranger

**Comment by teto** [comment]
sry I should have mentioned my version, I use 0.1.3 from nixpkgs for which it is not available. I wonder if  this could'nt be made as a positional argument instead (so without the `-c`) since it looks like a natural thing to do and is faster to type

**Comment by sxyazi** [comment]
Yes, `-c` was added recently.

It does seem that the positional argument would be more intuitive, and I will replace `-c` with it.

**Comment by teto** [comment]
thank you !
