### ISSUE TITLE
Complete mouse support

### ISSUE THREAD

**Issue by Zeioth** [sxyazi/yazi#950]
### Please describe the problem you're trying to solve

Scrolling the file preview with the mouse wheel.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

**On the manager**:
* Clicking an item of the list should move the cursor to it.

**On the right panel**:
* Using the mouse wheel over the file preview, should scroll the preview.

### Additional context

* With this we would have feature parity with ranger. 
* This is a particularly good UX improvement for people using trackball.

**Comment by sxyazi** [comment]
Hi, it's already in the Feature Requests, closing in favor of https://github.com/sxyazi/yazi/issues/51

**Comment by sxyazi** [comment]
Hi, this feature has now been implemented by @qsdrqs in https://github.com/sxyazi/yazi/pull/1038! 🎉
