### ISSUE TITLE
Option to specify scrollwheel distance

### ISSUE THREAD

**Issue by Zeioth** [sxyazi/yazi#954]
### Please describe the problem you're trying to solve

By default, using the scrollwheel, move 3 positions on the manager list.

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

It would be nice having an option to specify how many positions the scroll move.

**Comment by sxyazi** [comment]
I didn't quite get your meaning - Yazi currently doesn't support any mouse operations.

**Comment by mikavilpas** [comment]
We discussed mouse support in https://github.com/mikavilpas/yazi.nvim/issues/49 and added basic/hacky support (when embedded in neovim). It seems at least wezterm forwards scroll events to yazi and they do work on a basic level.

**Comment by sxyazi** [comment]
It looks like WezTerm converted the user's mouse scroll into `<Up>` and `<Down>` keys. When I add:

```bash
{ on = [ "<Up>" ],   run = "noop" },
{ on = [ "<Down>" ], run = "noop" },
```

to `keymap.toml`, scrolling stops working.

So I don't think there's something Yazi can do, as this is not a real mouse scroll event, Yazi just receives the atomic events `<Up>` and `<Down>` from the terminal.

**Comment by sxyazi** [comment]
I believe this is a fallback behavior when the terminal detects that the CLI program hasn't requested mouse support, while both Ranger and Joshuto have requested it from the terminal, but accordingly, the CLI program needs to handle the mouse events.

**Comment by mikavilpas** [comment]
@Zeioth you can work around this and kind of get what you are looking for by setting this in `keymap.toml` in the`[manager]` section:

```toml
  { on = [
    "<Up>",
  ], run = "arrow -3", desc = "Move cursor up" },
  { on = [
    "<Down>",
  ], run = "arrow 3", desc = "Move cursor down" },
```

**Comment by Zeioth** [comment]
You are correct it's my terminal emulating the scroll. I was able to change it on foot terminal adding this to `~/.config/foot/foot.ini`

```toml
[scrollback]
lines=10000
multiplier=1.0
# instead of
multiplier=3.0
```
Still, I can confirm ranger allow clicking items on the manager. It's not super critical because one can just filter, but still something nice.

**Comment by sxyazi** [comment]
Glad to see the problem solved. Closing as invalid since this is a terminal behavior

**Comment by sxyazi** [comment]
> I agree that mouse support would be a useful feature, and many users have requested it.

This feature has now been implemented by @qsdrqs in https://github.com/sxyazi/yazi/pull/1038! 🎉
