### ISSUE TITLE
Redefining default keybinds in submap displays duplicates

### ISSUE THREAD

**Issue by SolitudeSF** [sxyazi/yazi#955]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

kitty

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>
<summary>Details</summary>

Yazi
    Version: 0.2.5 (c65a14c 2024-04-23)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect: Kitty

Adaptor
    Adaptor.matches: Kitty

Desktop
    XDG_SESSION_TYPE: Some("tty")
    WAYLAND_DISPLAY: None
    DISPLAY: Some(":1")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/bedrock/cross/bin/bash")
    EDITOR: Some("kak")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.45\nmagic file from /usr/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

</details>

### Describe the bug

![image](https://github.com/sxyazi/yazi/assets/10168645/078c8be4-3aed-44c0-8154-3ff6367a9055)

### Expected Behavior

No duplicates displayed

### To Reproduce

add duplicate submap keybinds via prepend_keymap

### Configuration

```toml
[manager]
prepend_keymap = [
  { on = [ "g", "d" ], run = "plugin shellcd --args='xdg-user-dir DOWNLOAD'", desc = "Go to downloads" },
  { on = [ "g", "m" ], run = "plugin shellcd --args='echo /run/media/$USER'", desc = "Go to mounted media" },
  { on = [ "g", "c" ], run = "plugin shellcd --args='echo $XDG_CONFIG_HOME'", desc = "Go to config directory" },
  { on = [ "g", "D" ], run = "plugin shellcd --args='echo $XDG_DATA_HOME'", desc = "Go to data directory" },
]
```

**Comment by sxyazi** [comment]
Maybe we can filter them out when displaying the `which` components. Anyone want to give it a try? 

https://github.com/sxyazi/yazi/blob/681612f9764d45f61bbac622c57e0a48342b05c1/yazi-core/src/which/commands/show.rs#L48-L53

should be the only place that needs to change.

**Comment by mikavilpas** [comment]
I think I was able to solve this. Will open a PR soon.
