### ISSUE TITLE
Filecount for directories

### ISSUE THREAD

**Issue by bvr-yr** [sxyazi/yazi#960]
### Please describe the problem you're trying to solve

That could be useful to display it instead of nothing unless size is evaluated

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

as a `Cha` property

### Additional context

I have a working solution, but I faced some issues related to #842

As an additional context, that might be kind of a bug, if not intended

Things mentioned in #842, but it's not only about size, and not only about dirs, you can try to `chmod` if on Unix and see that perms not changed unless you `touch -m`, which updates mtime

However, if you delete or create a file within a directory, even if it is hovered its `Cha` is never updated, although mtime of that directory is changed

I was trying to implement this with async only ofc, but ended up with calling sync `std::fs::read_dir` anyway on hovered only, as a separate lua method just to reflect updates.

Would be great if watchers got fixed, I'd made a MR then

**Comment by sxyazi** [comment]
> However, if you delete or create a file within a directory, even if it is hovered its Cha is never updated, although mtime of that directory is changed

I didn't quite understand what you meant, are you saying that when a file in the CWD is changed (added or deleted), but the CWD is not updated in its parent directory? If so, this is by design, Yazi only updates the CWD but not its parent.

**Comment by bvr-yr** [comment]
I mean that if I hover a directory, and create a file in that directory, I see it in preview but Cha of hovered dir is not updated at all untill I explicitly change its mtime, although actual mtime is already changed(at least as `stat -c '%y'` shows), it just not getting in event handler I guess. I tried to debug all events that are proccessed and only creation of the file comes in, but not the directory mtime change.
I suppose that's also by design, this just prevents the new Cha prop (let say dirlen) from updating

**Comment by sxyazi** [comment]
How did you get the `dirlen` through `Cha`? IIRC there is no such property.

**Comment by bvr-yr** [comment]
> new Cha prop
> I have a working solution

I made for personal use since I can't get it fully working with async only (as above)
All seems ok except no updates until explicit mtime change.  Not ready for MR obviously

**Comment by sxyazi** [comment]
You can go ahead and submit it. I need to see the code to know how to help you.
