### ISSUE TITLE
Add a new `--args` parameter to the `search` command

### ISSUE THREAD

**Issue by sxyazi** [sxyazi/yazi#962]
### Please describe the problem you're trying to solve

With the new `--args` parameter, users can pass custom arguments to `fd` or `rg`, for example, `search fd --args='-e -H'`.

You can parse the `--args` string into an array using the [`shell-words`](https://crates.io/crates/shell-words) crate. Anyone want to give it a shot?

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

.

**Comment by LatentDream** [comment]
I'll take a look!

**Comment by sxyazi** [comment]
Thank you! @LatentDream

**Comment by LatentDream** [comment]
@sxyazi
PR here: https://github.com/sxyazi/yazi/pull/1013
