### ISSUE TITLE
Add some common `[filetype]` rules to the default theme configuration

### ISSUE THREAD

**Issue by sxyazi** [sxyazi/yazi#963]
### Please describe the problem you're trying to solve

Yazi has added support for the [new `is` rule](https://yazi-rs.github.io/docs/configuration/theme#filetype), which is used to match specific file types (such as executable files or orphaned link files). I think we should add them by default because they are very useful for many users.

Perhaps we can refer to other popular terminal file managers, such as ranger, lf, nnn, etc., to optimize the existing `[filetype]`. In other words, I am open to changing the existing `[filetype]` as long as it can bring a better user experience. 

This is a complex aesthetic work, but I don't have much confidence in my own aesthetics, so I hope to see someone interested in trying it out :)

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

.

**Comment by Brixy** [comment]
This is what I use. Would this be a start? I came to yazi from nnn, hence the colors.

```
	# Empty files
	{ mime = "inode/x-empty", fg = "red" },

	# Is rules
	{ name = "*",  is = "orphan", fg = "red" },
	{ name = "*",  is = "link",   fg = "cyan" },
	{ name = "*/", is = "link",   fg = "cyan" },
	{ name = "*",  is = "exec",   fg = "green" },

```

**Comment by sxyazi** [comment]
Looks good! Would you like to raise a PR for it?

**Comment by Brixy** [comment]
With pleasure! I’m on the road for a few hours now, but I’ll get back to it today.

**Comment by sxyazi** [comment]
Done in https://github.com/sxyazi/yazi/pull/966, thanks!
