### ISSUE TITLE
Feature request: option to repeat command by prefixing with a number (Vim style) e.g. `4j` goes 4 items down

### ISSUE THREAD

**Issue by wis** [sxyazi/yazi#971]
### Please describe the problem you're trying to solve

I tried using a number prefix before pressing the key, so to repeat the command, but it did not work..

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

commands should repeat when prefixed with a number, like in Vim, and in Ranger.

### Additional context

I remember being able to do this from the time I used Ranger-fm, and I got used to using it.

**Comment by sxyazi** [comment]
Hi, https://github.com/dedukun/relative-motions.yazi is what you're looking for. You can find more awesome plugins at https://yazi-rs.github.io/docs/resources

Closing as already exists
