### ISSUE TITLE
"Reveal" on Windows does not seem to work

### ISSUE THREAD

**Issue by RioNight** [sxyazi/yazi#972]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

wezterm 20240203-110809-5046fc22

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh

Yazi
    Version: 0.2.5 (c65a14c 2024-04-23)
    OS: windows-x86_64 (windows)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: WezTerm

Adaptor
    Adaptor.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: None
    EDITOR: None
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: Some("C:\\Users\\KhanH\\scoop\\apps\\git\\current\\usr\\bin\\file.exe")
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(ExitStatus(0)), stdout: "file-5.45\nmagic file from /usr/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "code \"%*\"", block: false, orphan: true, desc: "code", for_: None, spread: true })
    block: Some(Opener { run: "code -w \"%*\"", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Error { kind: NotFound, message: "program not found" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "C:\\Users\\USERNAME\\AppData\\Roaming\\yazi\\state" directory.


```

</details>

### Describe the bug

`O` > `Reveal` on a folder just opens the Explorer, not in any specific directory.

If I "Reveal" any directory, the File Explorer simply opens here:

![image](https://github.com/sxyazi/yazi/assets/58403689/95193949-0b26-4269-aa4f-76175491f2ea)

### Expected Behavior

I would expect it to do what's done here:
https://github.com/sxyazi/yazi/blob/latest/yazi-config/preset/yazi.toml

### To Reproduce

1. Open yazi
2. Navigate to any directory
3. `O` > `Reveal`
4. Observe that the Explorer opens like so:
![image](https://github.com/sxyazi/yazi/assets/58403689/95193949-0b26-4269-aa4f-76175491f2ea)

### Configuration

no config

**Comment by sxyazi** [comment]
Please upload your yazi.toml config file

**Comment by cjqfeng** [comment]
i have encounter similar situation
when run yazi in msys2 `Reveal` show the same result
when run in alacritty which start from cmd or explorer,there is no problem
maybe the path(cygpath) represent in msys2 like `/f/dir/subdir` cause the problem
