### ISSUE TITLE
`yazi --debug` on Wezterm / mintty on Windows behaves unexpectedly

### ISSUE THREAD

**Issue by RioNight** [sxyazi/yazi#973]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

wezterm 20240203-110809-5046fc22

### Did you try the latest code to see if this problem got fixed?

Tried, but the problem still

### `yazi --debug` output

<details>

```sh

Yazi
    Version: 0.2.5 (c65a14c 2024-04-23)
    OS: windows-x86_64 (windows)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: WezTerm

Adaptor
    Adaptor.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: None
    EDITOR: None
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: Some("C:\\Users\\KhanH\\scoop\\apps\\git\\current\\usr\\bin\\file.exe")
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(ExitStatus(0)), stdout: "file-5.45\nmagic file from /usr/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "code \"%*\"", block: false, orphan: true, desc: "code", for_: None, spread: true })
    block: Some(Opener { run: "code -w \"%*\"", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Error { kind: NotFound, message: "program not found" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "C:\\Users\\KhanH\\AppData\\Roaming\\yazi\\state" directory.


```

</details>

### Describe the bug

The four common shells on Windows are bash (installed with Git), Windows Powershell, pwsh (new powershell) and cmd.

On Windows Terminal with any of these shells, `yazi --debug` works as expected.

On Wezterm `yazi --debug` works strangely:

With bash, `yazi --debug` hangs after outputting the debug information. Ctrl+C does not kill it. It crashes the terminal after a while.
`yazi --debug` copies the debug info, but there is a trailing ` :>|WezTerm 20240203-110809-5046fc22^[\` on the new command prompt.

With cmd, pwsh, and powershell, there is an extra `\` in the new prompt:
![image](https://github.com/sxyazi/yazi/assets/58403689/ea610294-14dc-4df6-8355-92eba1006848)

On mintty / Git Bash:
`yazi --debug` works, but there is a trailing ` :>|mintty 3.7.0^[\` on the new command prompt.
![image](https://github.com/sxyazi/yazi/assets/58403689/e8820fc0-8822-4cac-a9a4-181bf5c7bd21)

`yazi --debug | clip` causes:
![image](https://github.com/sxyazi/yazi/assets/58403689/aa7611be-2450-4e1d-856c-7dd818f38302)

With mintty with pwsh, causes a hang with no output:
![image](https://github.com/sxyazi/yazi/assets/58403689/1390c2cf-bf92-4a40-b49e-7d3c4ac26a28)

### Expected Behavior

I would expect yazi to exit or return after outputting the debug information.

### To Reproduce

Run `yazi --debug` in Wezterm with Git Bash.

This is my `~/.wezterm.lua` file.

```lua
local wezterm = require 'wezterm'
local act = wezterm.action

local config = {}

config.check_for_updates = false

config.default_prog = { 'C:\\Users\\USERNAME\\scoop\\apps\\git\\current\\bin\\bash.exe -i -l' }
-- config.default_prog = { 'pwsh' }

config.keys = {
	{ key = 'l', mods = 'ALT', action = act.ShowLauncher },
	{ key = 'v', mods = 'ALT', action = act.SplitHorizontal{ domain =  'CurrentPaneDomain' } },
	{ key = 'LeftArrow', mods = 'ALT', action = act.ActivatePaneDirection 'Prev' },
	{ key = 'RightArrow', mods = 'ALT', action = act.ActivatePaneDirection 'Next' },
}

return config

```

### Configuration

no config

**Comment by sxyazi** [comment]
I noticed you are not using the latest code. Please try the latest code to see if this issue still

**Comment by sxyazi** [comment]
Oh I think I know the reason now. 

This is expected behavior because in `--debug` mode, CSI sequences are used to probe the terminal type. I want to see how the terminal responds to understand its behavior. For some reason, the Windows terminal responds with some strange characters. 

I don't think this is a bug because it doesn't happen during normal use of Yazi.

**Comment by RioNight** [comment]
What constitutes a normal use of yazi?
On Wezterm + pwsh, there is a trailing \ in the new command prompt:
![image](https://github.com/sxyazi/yazi/assets/58403689/d794c681-c860-4c1c-82a6-903870f5ba3f)

**Comment by sxyazi** [comment]
Does it still when you run `yazi` without `--debug`?
