### ISSUE TITLE
Choose image preview method in config/auto detect available method

### ISSUE THREAD

**Issue by linsui** [sxyazi/yazi#98]
IIUC, the preview method is hard-coded. I can use `TERM=foot yazi` to enable sixel preview but this is ugly. It's better to detect supported preview method or allow setting it in the config file.

**Comment by sxyazi** [comment]
Please paste the output of `echo $TERM, $TERM_PROGRAM, $XDG_SESSION_TYPE` here

**Comment by linsui** [comment]
```
xterm-256color, BlackBox, wayland
```

**Comment by sxyazi** [comment]
You are using the [Black Box](https://gitlab.gnome.org/raggesilver/blackbox) terminal, right?

**Comment by sxyazi** [comment]
Please give it a try with https://github.com/sxyazi/yazi/pull/99, and see if it's working without `TERM=foot`
