### ISSUE TITLE
Add `--force-window` flag to mpv on `play` opener in the preset configuration

### ISSUE THREAD

**Issue by fmorroni** [sxyazi/yazi#983]
### Please describe the problem you're trying to solve

With the default configuration, audio files that have no cover art will open in the background with no way to interact with them.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

Audio files should always open the mpv window so we can interact with it. This should be fixed by just adding the `--force-window` flag to the opener command in `yazi.toml`.
```toml
play = [
	{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
]
```

**Comment by sxyazi** [comment]
Sounds good to me, please raise a PR for it
