### ISSUE TITLE
when use in msys2/mingw using msys's bash and envs,not the native windows cmd and system variables

### ISSUE THREAD

**Issue by cjqfeng** [sxyazi/yazi#984]
### Please describe the problem you're trying to solve

current when run yazi in msys2
 **g h** will go to `c:\Users\chen`
config locate is `C:\Users\Chen\AppData\Roaming\yazi\config\yazi.toml`
can't recognize bash commands in `$PATH`

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

when run yazi in msys2/mingw,behavier like in linux will be more powerfull
using bash envs as `$HOME` `PATH` .etc 
using bash to run shell command
config like `{ run = '${EDITOR:=nvim} "$@"', desc = "$EDITOR", block = true, for = "mingw or cygwin" },`

**Comment by sxyazi** [comment]
Are you running the Linux version of yazi or the Windows version in msys2? What does yazi --debug say?

**Comment by cjqfeng** [comment]
the **`yazi-x86_64-pc-windows-msvc`** version log as below
```

Yazi
    Version: 0.2.5 (c65a14c 2024-04-23)
    OS: windows-x86_64 (windows)
    Debug: false

Emulator
    Emulator.via_env: ("xterm-256color", "mintty")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Mintty

Adaptor
    Adaptor.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("I:\\msys64\\usr\\bin\\bash.exe")
    EDITOR: None
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(ExitStatus(0)), stdout: "file-5.44\nmagic file from /usr/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "neovide \"%*\"", block: false, orphan: true, desc: "code", for_: None, spread: true })
    block: Some(Opener { run: "code -w \"%*\"", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Error { kind: NotFound, message: "program not found" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "C:\\Users\\Chen\\AppData\\Roaming\\yazi\\state" directory.


```
---
the compiled in the msys version's log as below
```

Yazi
    Version: 0.2.5 (bdb28f7 2024-05-01)
    OS: windows-x86_64 (windows)
    Debug: true

Emulator
    Emulator.via_env: ("xterm-256color", "mintty")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Mintty

Adaptor
    Adaptor.matches: Iterm2

Desktop
    XDG_SESSION_TYPE: None
    WAYLAND_DISPLAY: None
    DISPLAY: None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("I:\\msys64\\usr\\bin\\bash.exe")
    EDITOR: None
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(ExitStatus(0)), stdout: "file-5.44\nmagic file from /usr/share/misc/magic\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "neovide \"%*\"", block: false, orphan: true, desc: "code", for_: None, spread: true })
    block: Some(Opener { run: "code -w \"%*\"", block: true, orphan: false, desc: "code (block)", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Err(Error { kind: NotFound, message: "program not found" })


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "C:\\Users\\Chen\\AppData\\Roaming\\yazi\\state" directory.


```

**Comment by sxyazi** [comment]
Does `{ run = 'bash -c "echo 123"' }` work for you?

**Comment by cjqfeng** [comment]
i record a gif with config as below
`filepath.txt` is empty
`runState.txt` is `success`
how to check the filename passed in?

```toml
[opener]
edit = [
	{ run = 'bash -c "echo $@ > filepath.txt"'}, # filepath.txt is empty
	{ run = 'notepad "%1"'}, # will run notepad with file loaded
]
open = [
	{ run = 'neovide'}, # will stuck
	{ run = 'bash -c "neovide"'}, # will run neovide
	{ run = 'bash -c "neovide $@"'}, # will run neovide without file loaded

]
reveal = [
	{ run = 'bash -c "echo success > runState.txt"'}, # runState.txt contains success
]


```

https://github.com/sxyazi/yazi/assets/38670468/dd8900d7-5fcc-4967-b4ba-2dbfa2028cde

**Comment by sxyazi** [comment]
try something like 

run = 'bash -c "neovide $@" "" %*'

**Comment by cjqfeng** [comment]
thanks now is working , i thing  #972 is the same reason
now the popup all show `bash`,is there some way to change it
how let yazi load config file from other location other than the `c:\user\...`

> try something like
> 
> run = 'bash -c "neovide $@" "" "%*"'

![Snipaste_2024-05-02_15-57-16](https://github.com/sxyazi/yazi/assets/38670468/2ff56057-2900-47ce-b25c-87537d904f77)

**Comment by cjqfeng** [comment]
so in this issue ,the essential reason is the shell ？ can i change it from somewhere

**Comment by sxyazi** [comment]
> now the popup all show bash,is there some way to change it

Use `desc` to change it, https://yazi-rs.github.io/docs/configuration/yazi/#opener

> how let yazi load config file from other location other than the c:\user\...

You can set the `YAZI_CONFIG_HOME` environment variable to specify a config folder path

> so in this issue ,the essential reason is the shell ？ can i change it from somewhere

Currently the shell is controlled through [conditional compilation](https://doc.rust-lang.org/reference/conditional-compilation.html), with `cmd.exe` for Windows and `sh` for Unix. 

Perhaps we can consider msys2 as a Unix platform, as it's something between Windows and Unix, although that sounds strange. This would require changing all existing conditional compilation directives and moving them to runtime, which would be a significant amount of work. I'd be willing to accept a PR about it if you're interested.
