### ISSUE TITLE
Add git commit hash to `--version` for `ya` CLI tool

### ISSUE THREAD

**Issue by sxyazi** [sxyazi/yazi#994]
### Please describe the problem you're trying to solve

Currently, running `ya --version` will output: 

```
ya 0.2.5
```

which looks plain and lacks sufficient information to confirm the specific version the user is using. 

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

It would be great if it could include the git commit hash at build time, similar to `yazi --version`:

```
Yazi 0.2.5 (36b3ffa 2024-05-02)
```

This is the code used to get the commit hash for `yazi --version`:

https://github.com/sxyazi/yazi/blob/36b3ffafc1a2e227959b742002d4ff60aa31df16/yazi-boot/src/boot.rs#L40-L47

**Comment by fzdwx** [comment]
just call `Boot::action_version()` ?

**Comment by mikavilpas** [comment]
@fzdwx I think this suggestion could be what you want

1. Add support to `ya` for a new argument (`--version`) here https://github.com/sxyazi/yazi/blob/edd162a6859b0ed69e1e1bf537771282403db6bd/yazi-cli/src/args.rs?plain=1#L6-L20
2. Add the implementation for that command by copying from the `action_version` above
3. Follow the errors and implement build time version generation etc from `yazi-fm`

**Comment by fzdwx** [comment]
@mikavilpas Hello, thank you tip for me. Please check it https://github.com/sxyazi/yazi/pull/1006.

**Comment by sxyazi** [comment]
Done in https://github.com/sxyazi/yazi/pull/1006
